import { TRACK, DIFFICULTY } from '../schema/types.js';

const { FOUNDATIONS, CORE, BROWSER, ASYNC, ADVANCED, PROFESSIONAL, INTERVIEW } = TRACK;
const { BEGINNER, EASY, MEDIUM, HARD, EXPERT } = DIFFICULTY;

/**
 * The 47 modules of the JSPath curriculum, in teaching order.
 *
 * Modules declare metadata only. `lessonIds` is derived by the content registry
 * from the lessons that claim `moduleId`, so there is exactly one source of
 * truth for which lessons belong where and the two can never drift apart.
 */
export const MODULES = [
  {
    id: 'm00', slug: 'orientation', order: 0, track: FOUNDATIONS, difficulty: BEGINNER,
    title: 'Programming & JavaScript Orientation',
    shortTitle: 'Orientation',
    description: 'What programming actually is, what JavaScript is, where it runs, and how to run your first line of code.',
    icon: 'rocket_launch',
    topicIds: ['orientation', 'js-runtime', 'devtools', 'syntax'],
    objectives: [
      'Explain what a program is and how a computer executes instructions',
      'Describe what JavaScript is, where it runs, and what a JavaScript engine does',
      'Open and use the browser console to run JavaScript',
      'Read a JavaScript error message and understand what it is telling you',
    ],
    prerequisites: [],
  },
  {
    id: 'm01', slug: 'variables', order: 1, track: FOUNDATIONS, difficulty: BEGINNER,
    title: 'Variables & Values',
    shortTitle: 'Variables',
    description: 'Storing and naming values with let, const and var — including what const really protects.',
    icon: 'data_object',
    topicIds: ['variables'],
    objectives: [
      'Declare and assign variables with let and const',
      'Choose correctly between let, const and var',
      'Explain why a const object can still be mutated',
      'Name variables using professional conventions',
    ],
    prerequisites: ['m00'],
  },
  {
    id: 'm02', slug: 'data-types', order: 2, track: FOUNDATIONS, difficulty: BEGINNER,
    title: 'Data Types',
    shortTitle: 'Data Types',
    description: 'The seven primitives, objects, and the difference between value and reference semantics.',
    icon: 'category',
    topicIds: ['types'],
    objectives: [
      'Name every primitive type and describe what it represents',
      'Use typeof correctly and explain its known quirks',
      'Predict whether an assignment copies a value or shares a reference',
      'Distinguish mutable from immutable values',
    ],
    prerequisites: ['m01'],
  },
  {
    id: 'm03', slug: 'coercion', order: 3, track: CORE, difficulty: BEGINNER,
    title: 'Type Conversion & Coercion',
    shortTitle: 'Coercion',
    description: 'Explicit conversion, implicit coercion, and the equality rules that trip up most developers.',
    icon: 'swap_horiz',
    topicIds: ['coercion', 'types'],
    objectives: [
      'Convert between strings, numbers and booleans deliberately',
      'Predict the result of implicit coercion in common expressions',
      'Explain why == and === differ and when each is appropriate',
      'Avoid the classic coercion traps',
    ],
    prerequisites: ['m02'],
  },
  {
    id: 'm04', slug: 'operators', order: 4, track: CORE, difficulty: BEGINNER,
    title: 'Operators & Expressions',
    shortTitle: 'Operators',
    description: 'Arithmetic, comparison, logical, nullish and optional chaining — plus precedence and short-circuiting.',
    icon: 'calculate',
    topicIds: ['operators'],
    objectives: [
      'Use arithmetic, comparison and logical operators correctly',
      'Apply ?? and ?. to handle missing values safely',
      'Explain short-circuit evaluation and use it deliberately',
      'Reason about operator precedence instead of guessing',
    ],
    prerequisites: ['m03'],
  },
  {
    id: 'm05', slug: 'strings', order: 5, track: CORE, difficulty: BEGINNER,
    title: 'Strings',
    shortTitle: 'Strings',
    description: 'Template literals, immutability, and the string methods you will use every working day.',
    icon: 'text_fields',
    topicIds: ['strings'],
    objectives: [
      'Build strings with template literals and interpolation',
      'Explain why strings are immutable and what that implies',
      'Choose the right method for searching, slicing and transforming text',
      'Process real text data confidently',
    ],
    prerequisites: ['m02'],
  },
  {
    id: 'm06', slug: 'numbers', order: 6, track: CORE, difficulty: BEGINNER,
    title: 'Numbers & Math',
    shortTitle: 'Numbers',
    description: 'Floating-point reality, safe integers, numeric validation and the Math object.',
    icon: 'functions',
    topicIds: ['numbers'],
    objectives: [
      'Explain why 0.1 + 0.2 !== 0.3 and how to work around it',
      'Validate numeric input robustly',
      'Use the Math object for rounding and randomness',
      'Recognise the limits of Number and when BigInt is needed',
    ],
    prerequisites: ['m03'],
  },
  {
    id: 'm07', slug: 'control-flow', order: 7, track: CORE, difficulty: BEGINNER,
    title: 'Booleans, Conditions & Control Flow',
    shortTitle: 'Control Flow',
    description: 'Truthiness, if/else, switch, ternaries and the guard-clause style professionals prefer.',
    icon: 'alt_route',
    topicIds: ['booleans', 'control-flow'],
    objectives: [
      'List the falsy values from memory',
      'Write clear conditional logic without deep nesting',
      'Choose between if/else, switch and the ternary operator',
      'Use guard clauses and early returns to flatten code',
    ],
    prerequisites: ['m04'],
  },
  {
    id: 'm08', slug: 'functions', order: 8, track: CORE, difficulty: BEGINNER,
    title: 'Functions Fundamentals',
    shortTitle: 'Functions',
    description: 'Declarations, expressions, parameters, return values, and functions as first-class values.',
    icon: 'code',
    topicIds: ['functions'],
    objectives: [
      'Write function declarations and expressions',
      'Explain the difference between returning and logging',
      'Use default and rest parameters',
      'Treat functions as values that can be passed around',
    ],
    prerequisites: ['m07'],
  },
  {
    id: 'm09', slug: 'arrow-functions', order: 9, track: CORE, difficulty: EASY,
    title: 'Arrow Functions & Function Patterns',
    shortTitle: 'Arrow Functions',
    description: 'Arrow syntax, callbacks, higher-order functions, purity, and when arrows are the wrong choice.',
    icon: 'arrow_right_alt',
    topicIds: ['arrow-functions', 'higher-order', 'functions'],
    objectives: [
      'Write arrow functions with implicit and explicit returns',
      'Explain how arrow functions treat `this` differently',
      'Write and consume higher-order functions',
      'Identify pure functions and side effects',
    ],
    prerequisites: ['m08'],
  },
  {
    id: 'm10', slug: 'scope-hoisting', order: 10, track: CORE, difficulty: EASY,
    title: 'Scope, Hoisting & Execution Basics',
    shortTitle: 'Scope & Hoisting',
    description: 'Lexical scope, the scope chain, shadowing, hoisting and the Temporal Dead Zone — precisely.',
    icon: 'layers',
    topicIds: ['scope', 'hoisting'],
    objectives: [
      'Trace how JavaScript resolves an identifier through the scope chain',
      'State precisely what hoisting does and does not do',
      'Explain the Temporal Dead Zone and why it exists',
      'Predict the output of classic scope puzzles',
    ],
    prerequisites: ['m08'],
  },
  {
    id: 'm11', slug: 'loops', order: 11, track: CORE, difficulty: BEGINNER,
    title: 'Loops & Iteration',
    shortTitle: 'Loops',
    description: 'for, while, for...of, for...in — and how to pick the right one every time.',
    icon: 'repeat',
    topicIds: ['loops'],
    objectives: [
      'Write for, while and do...while loops correctly',
      'Use break and continue deliberately',
      'Choose between for...of and for...in and explain why',
      'Avoid the common causes of infinite loops',
    ],
    prerequisites: ['m07'],
  },
  {
    id: 'm12', slug: 'arrays', order: 12, track: CORE, difficulty: EASY,
    title: 'Arrays Fundamentals',
    shortTitle: 'Arrays',
    description: 'Indexes, length, and the classic array methods — with mutation behaviour made explicit.',
    icon: 'view_list',
    topicIds: ['arrays'],
    objectives: [
      'Create, read and modify arrays confidently',
      'State which array methods mutate and which return a new array',
      'Use slice, splice, concat and sort correctly',
      'Explain why sort() needs a comparator for numbers',
    ],
    prerequisites: ['m11'],
  },
  {
    id: 'm13', slug: 'array-methods', order: 13, track: CORE, difficulty: EASY,
    title: 'Array Iteration Methods',
    shortTitle: 'Array Methods',
    description: 'map, filter, reduce and the whole iteration family — the daily language of professional JavaScript.',
    icon: 'transform',
    topicIds: ['array-methods', 'higher-order'],
    objectives: [
      'Choose the correct iteration method for a given transformation',
      'Write reduce confidently, including object accumulators',
      'Chain methods readably without creating wasteful intermediates',
      'Answer the map-vs-forEach and find-vs-filter interview questions',
    ],
    prerequisites: ['m12', 'm09'],
  },
  {
    id: 'm14', slug: 'objects', order: 14, track: CORE, difficulty: EASY,
    title: 'Objects Fundamentals',
    shortTitle: 'Objects',
    description: 'Properties, methods, dot vs bracket access, destructuring, spread and reference semantics.',
    icon: 'inventory_2',
    topicIds: ['objects', 'destructuring'],
    objectives: [
      'Read and write nested object data safely',
      'Destructure objects with renaming and defaults',
      'Copy objects and explain what "shallow" means',
      'Check for property existence correctly',
    ],
    prerequisites: ['m12'],
  },
  {
    id: 'm15', slug: 'object-utilities', order: 15, track: CORE, difficulty: MEDIUM,
    title: 'Object Utilities & Advanced Object Basics',
    shortTitle: 'Object Utilities',
    description: 'Object.keys/values/entries, freeze, getters and setters, and safe access patterns.',
    icon: 'construction',
    topicIds: ['object-utilities', 'objects'],
    objectives: [
      'Convert between objects and arrays with entries/fromEntries',
      'Use Object.freeze and understand its shallowness',
      'Define getters and setters',
      'Traverse deeply nested data without crashing',
    ],
    prerequisites: ['m14'],
  },
  {
    id: 'm16', slug: 'dates-regex', order: 16, track: CORE, difficulty: MEDIUM,
    title: 'Date, Time, RegExp & Built-in Utilities',
    shortTitle: 'Dates & Regex',
    description: 'Working with dates and time zones, formatting with Intl, and practical regular expressions.',
    icon: 'schedule',
    topicIds: ['dates', 'regex'],
    objectives: [
      'Create, compare and format dates without off-by-one bugs',
      'Format numbers, currencies and dates for real users with Intl',
      'Read and write regular expressions for common validation tasks',
      'Recognise regex pitfalls including catastrophic backtracking',
    ],
    prerequisites: ['m05'],
  },
  {
    id: 'm17', slug: 'dom', order: 17, track: BROWSER, difficulty: EASY,
    title: 'DOM Fundamentals',
    shortTitle: 'DOM',
    description: 'The document object model, selecting elements, and changing content, attributes and styles.',
    icon: 'account_tree',
    topicIds: ['dom'],
    objectives: [
      'Explain what the DOM is and that it is a browser API, not JavaScript',
      'Select elements with querySelector and friends',
      'Change text, attributes, classes and styles safely',
      'Explain why innerHTML with user data is dangerous',
    ],
    prerequisites: ['m14'],
  },
  {
    id: 'm18', slug: 'dom-manipulation', order: 18, track: BROWSER, difficulty: EASY,
    title: 'DOM Creation & Traversal',
    shortTitle: 'DOM Building',
    description: 'Creating elements, moving through the tree, and rendering data-driven lists efficiently.',
    icon: 'schema',
    topicIds: ['dom-manipulation', 'dom'],
    objectives: [
      'Build DOM structures from data without string concatenation',
      'Traverse between parents, children and siblings',
      'Use DocumentFragment to batch insertions',
      'Use closest() and matches() for delegation-friendly code',
    ],
    prerequisites: ['m17'],
  },
  {
    id: 'm19', slug: 'events', order: 19, track: BROWSER, difficulty: MEDIUM,
    title: 'Events',
    shortTitle: 'Events',
    description: 'Listeners, the event object, propagation, delegation and listener lifecycle management.',
    icon: 'touch_app',
    topicIds: ['events'],
    objectives: [
      'Attach and remove event listeners correctly',
      'Explain capturing, targeting and bubbling',
      'Implement event delegation and say why it scales',
      'Distinguish target from currentTarget',
    ],
    prerequisites: ['m18'],
  },
  {
    id: 'm20', slug: 'forms', order: 20, track: BROWSER, difficulty: MEDIUM,
    title: 'Forms & Validation',
    shortTitle: 'Forms',
    description: 'Reading input, constraint validation, custom rules, FormData and accessible error reporting.',
    icon: 'edit_note',
    topicIds: ['forms', 'events'],
    objectives: [
      'Read values from every common input type',
      'Combine native constraint validation with custom rules',
      'Use FormData to collect and submit form state',
      'Report errors accessibly and explain why client validation is not security',
    ],
    prerequisites: ['m19'],
  },
  {
    id: 'm21', slug: 'modern-javascript', order: 21, track: CORE, difficulty: MEDIUM,
    title: 'Modern JavaScript (ES6+)',
    shortTitle: 'Modern JS',
    description: 'The syntax that defines contemporary JavaScript, consolidated and applied.',
    icon: 'auto_awesome',
    topicIds: ['modern-js', 'destructuring'],
    objectives: [
      'Apply destructuring, spread and rest fluently',
      'Use optional chaining and nullish coalescing precisely',
      'Recognise which features are syntax sugar and which change semantics',
      'Read modern codebases without hesitation',
    ],
    prerequisites: ['m14', 'm09'],
  },
  {
    id: 'm22', slug: 'errors-debugging', order: 22, track: PROFESSIONAL, difficulty: MEDIUM,
    title: 'Error Handling & Debugging',
    shortTitle: 'Errors & Debugging',
    description: 'Error objects, try/catch/finally, custom errors, stack traces and a real debugging method.',
    icon: 'bug_report',
    topicIds: ['errors', 'debugging'],
    objectives: [
      'Distinguish syntax, runtime and logic errors',
      'Use try/catch/finally without swallowing failures',
      'Create and throw meaningful custom errors',
      'Debug systematically with breakpoints instead of guessing',
    ],
    prerequisites: ['m08'],
  },
  {
    id: 'm23', slug: 'async-foundations', order: 23, track: ASYNC, difficulty: MEDIUM,
    title: 'Asynchronous JavaScript Foundations',
    shortTitle: 'Async Basics',
    description: 'Why JavaScript is single-threaded but not blocking: timers, callbacks and Web APIs.',
    icon: 'hourglass_top',
    topicIds: ['async-foundations', 'event-loop'],
    objectives: [
      'Explain synchronous vs asynchronous execution accurately',
      'Use setTimeout and setInterval and clean them up',
      'Write and read callback-based APIs',
      'Explain what "callback hell" costs and why Promises replaced it',
    ],
    prerequisites: ['m09'],
  },
  {
    id: 'm24', slug: 'promises', order: 24, track: ASYNC, difficulty: MEDIUM,
    title: 'Promises',
    shortTitle: 'Promises',
    description: 'States, chaining, error propagation, and the four combinators.',
    icon: 'account_tree',
    topicIds: ['promises'],
    objectives: [
      'Describe the three Promise states and how they transition',
      'Chain promises and propagate errors correctly',
      'Choose between all, allSettled, race and any',
      'Avoid the classic Promise mistakes',
    ],
    prerequisites: ['m23'],
  },
  {
    id: 'm25', slug: 'async-await', order: 25, track: ASYNC, difficulty: MEDIUM,
    title: 'async / await',
    shortTitle: 'async/await',
    description: 'Writing asynchronous code that reads sequentially — without accidentally serialising it.',
    icon: 'sync_alt',
    topicIds: ['async-await', 'promises'],
    objectives: [
      'Convert promise chains to async/await and back',
      'Handle rejections with try/catch',
      'Run independent work in parallel instead of awaiting in sequence',
      'Avoid async callbacks in forEach and similar traps',
    ],
    prerequisites: ['m24'],
  },
  {
    id: 'm26', slug: 'http-fetch', order: 26, track: ASYNC, difficulty: MEDIUM,
    title: 'HTTP, JSON, Fetch & APIs',
    shortTitle: 'Fetch & APIs',
    description: 'The client/server model, JSON, the Fetch API, error handling, cancellation and CORS.',
    icon: 'cloud',
    topicIds: ['http', 'async-await'],
    objectives: [
      'Describe an HTTP request and response accurately',
      'Fetch, parse and render remote data with loading and error states',
      'Explain why fetch does not reject on 404 and handle it correctly',
      'Cancel requests with AbortController and reason about CORS',
    ],
    prerequisites: ['m25'],
  },
  {
    id: 'm27', slug: 'storage-web-apis', order: 27, track: BROWSER, difficulty: MEDIUM,
    title: 'Browser Storage & Web APIs',
    shortTitle: 'Storage & Web APIs',
    description: 'localStorage, URL handling, History, observers, and the browser capabilities worth knowing.',
    icon: 'database',
    topicIds: ['storage', 'web-apis'],
    objectives: [
      'Persist and restore state with localStorage safely',
      'Build and read URLs with URL and URLSearchParams',
      'Use IntersectionObserver for lazy and scroll-driven behaviour',
      'State clearly what localStorage is not safe for',
    ],
    prerequisites: ['m26'],
  },
  {
    id: 'm28', slug: 'modules', order: 28, track: CORE, difficulty: MEDIUM,
    title: 'Modules & Code Organization',
    shortTitle: 'Modules',
    description: 'import/export, module scope, dynamic import, and how to structure a growing codebase.',
    icon: 'widgets',
    topicIds: ['modules', 'clean-code'],
    objectives: [
      'Use named and default exports appropriately',
      'Explain module scope and single evaluation',
      'Split code with dynamic import()',
      'Organise a project so dependencies point in one direction',
    ],
    prerequisites: ['m21'],
  },
  {
    id: 'm29', slug: 'this', order: 29, track: ADVANCED, difficulty: HARD,
    title: 'The `this` Keyword',
    shortTitle: '`this`',
    description: 'Call-site binding rules, lost context, call/apply/bind, and why arrows are different.',
    icon: 'my_location',
    topicIds: ['this'],
    objectives: [
      'Determine the value of `this` from the call site every time',
      'Explain why a method loses its receiver when passed as a callback',
      'Use call, apply and bind correctly',
      'Answer `this` interview traps with confidence',
    ],
    prerequisites: ['m14', 'm09'],
  },
  {
    id: 'm30', slug: 'prototypes', order: 30, track: ADVANCED, difficulty: HARD,
    title: 'Prototypes & Prototypal Inheritance',
    shortTitle: 'Prototypes',
    description: 'The prototype chain, delegation, constructor functions and how inheritance really works.',
    icon: 'linear_scale',
    topicIds: ['prototypes'],
    objectives: [
      'Trace a property lookup along the prototype chain',
      'Distinguish [[Prototype]] from the .prototype property',
      'Build inheritance with Object.create and constructor functions',
      'Explain why mutating built-in prototypes is dangerous',
    ],
    prerequisites: ['m29'],
  },
  {
    id: 'm31', slug: 'classes', order: 31, track: ADVANCED, difficulty: MEDIUM,
    title: 'Classes & OOP',
    shortTitle: 'Classes',
    description: 'Class syntax, fields, private state, inheritance, and composition over inheritance.',
    icon: 'account_balance',
    topicIds: ['classes', 'prototypes'],
    objectives: [
      'Write classes with constructors, fields and methods',
      'Use private fields and static members',
      'Extend classes correctly with super',
      'Argue when composition beats inheritance',
    ],
    prerequisites: ['m30'],
  },
  {
    id: 'm32', slug: 'closures', order: 32, track: ADVANCED, difficulty: HARD,
    title: 'Closures',
    shortTitle: 'Closures',
    description: 'The single most-tested advanced concept: retained lexical environments and what they enable.',
    icon: 'lock',
    topicIds: ['closures', 'scope'],
    objectives: [
      'Define a closure precisely and identify one in any code',
      'Use closures for private state and factory functions',
      'Explain the classic var-in-a-loop puzzle',
      'Recognise when closures retain memory unnecessarily',
    ],
    prerequisites: ['m10'],
  },
  {
    id: 'm33', slug: 'event-loop', order: 33, track: ADVANCED, difficulty: HARD,
    title: 'Execution Context, Call Stack & Event Loop',
    shortTitle: 'Event Loop',
    description: 'How JavaScript actually runs: stack frames, task queue, microtask queue and ordering.',
    icon: 'sync',
    topicIds: ['execution-context', 'event-loop'],
    objectives: [
      'Describe what happens when a function is called',
      'Explain the difference between the task and microtask queues',
      'Predict the exact output order of mixed sync, promise and timer code',
      'Explain why a long synchronous task freezes the page',
    ],
    prerequisites: ['m25', 'm32'],
  },
  {
    id: 'm34', slug: 'data-structures', order: 34, track: ADVANCED, difficulty: MEDIUM,
    title: 'Advanced Data Structures',
    shortTitle: 'Map & Set',
    description: 'Map, Set, WeakMap, WeakSet, structuredClone, and shallow vs deep copying.',
    icon: 'hub',
    topicIds: ['data-structures', 'copying'],
    objectives: [
      'Choose between an object and a Map with reasons',
      'Use Set for uniqueness and fast membership tests',
      'Explain what "weak" means for garbage collection',
      'Copy nested data correctly with structuredClone',
    ],
    prerequisites: ['m15'],
  },
  {
    id: 'm35', slug: 'iterators-generators', order: 35, track: ADVANCED, difficulty: HARD,
    title: 'Iterators & Generators',
    shortTitle: 'Iterators',
    description: 'The iteration protocols, custom iterables, generator functions and lazy evaluation.',
    icon: 'repeat_one',
    topicIds: ['iterators'],
    objectives: [
      'Implement the iterable protocol with Symbol.iterator',
      'Write generator functions and explain yield',
      'Build lazy, potentially infinite sequences',
      'Explain what for...of actually does under the hood',
    ],
    prerequisites: ['m34'],
  },
  {
    id: 'm36', slug: 'metaprogramming', order: 36, track: ADVANCED, difficulty: EXPERT,
    title: 'Metaprogramming',
    shortTitle: 'Metaprogramming',
    description: 'Symbols, property descriptors, Proxy and Reflect — power tools with real costs.',
    icon: 'auto_fix_high',
    topicIds: ['metaprogramming'],
    objectives: [
      'Use symbols for collision-free and well-known behaviour',
      'Control property visibility and writability with descriptors',
      'Intercept operations with Proxy traps',
      'Judge when metaprogramming hurts maintainability',
    ],
    prerequisites: ['m35'],
  },
  {
    id: 'm37', slug: 'functional', order: 37, track: ADVANCED, difficulty: HARD,
    title: 'Functional JavaScript',
    shortTitle: 'Functional JS',
    description: 'Purity, immutability, composition, currying, and knowing when functional style helps.',
    icon: 'polyline',
    topicIds: ['functional', 'higher-order'],
    objectives: [
      'Write pure functions and isolate side effects',
      'Compose small functions into pipelines',
      'Apply currying and partial application',
      'Recognise when functional style reduces readability',
    ],
    prerequisites: ['m13', 'm32'],
  },
  {
    id: 'm38', slug: 'recursion', order: 38, track: ADVANCED, difficulty: HARD,
    title: 'Recursion & Problem Solving',
    shortTitle: 'Recursion',
    description: 'Base cases, recursive cases, tree traversal, and a method for decomposing problems.',
    icon: 'account_tree',
    topicIds: ['recursion', 'algorithms'],
    objectives: [
      'Write recursive functions with correct base cases',
      'Traverse nested structures of unknown depth',
      'Convert between recursion and iteration',
      'Explain and avoid stack overflow',
    ],
    prerequisites: ['m32'],
  },
  {
    id: 'm39', slug: 'algorithms', order: 39, track: ADVANCED, difficulty: HARD,
    title: 'Algorithms & Data Structure Fundamentals',
    shortTitle: 'Algorithms',
    description: 'Big O intuition, core structures, and the problem-solving patterns interviews actually test.',
    icon: 'insights',
    topicIds: ['algorithms', 'data-structures'],
    objectives: [
      'Estimate the time and space complexity of your own code',
      'Implement stacks, queues and hash-map lookups in JavaScript',
      'Apply frequency counters, two pointers and sliding windows',
      'Explain why a hash map turns an O(n²) problem into O(n)',
    ],
    prerequisites: ['m38'],
  },
  {
    id: 'm40', slug: 'clean-code', order: 40, track: PROFESSIONAL, difficulty: MEDIUM,
    title: 'Clean JavaScript',
    shortTitle: 'Clean Code',
    description: 'Naming, cohesion, nesting, abstraction and refactoring — shown as before and after.',
    icon: 'cleaning_services',
    topicIds: ['clean-code'],
    objectives: [
      'Name things so comments become unnecessary',
      'Flatten nested code with guard clauses and extraction',
      'Apply DRY, KISS and YAGNI without over-abstracting',
      'Recognise common code smells and refactor them',
    ],
    prerequisites: ['m28'],
  },
  {
    id: 'm41', slug: 'design-patterns', order: 41, track: PROFESSIONAL, difficulty: HARD,
    title: 'JavaScript Design Patterns',
    shortTitle: 'Patterns',
    description: 'Module, factory, singleton, observer, strategy and friends — in idiomatic JavaScript.',
    icon: 'dashboard_customize',
    topicIds: ['design-patterns', 'clean-code'],
    objectives: [
      'Implement the core patterns in modern JavaScript',
      'Recognise patterns already present in browser APIs',
      'Choose a pattern to solve a real problem, not to show off',
      'Explain when a pattern is unnecessary ceremony',
    ],
    prerequisites: ['m40'],
  },
  {
    id: 'm42', slug: 'testing', order: 42, track: PROFESSIONAL, difficulty: MEDIUM,
    title: 'Testing JavaScript',
    shortTitle: 'Testing',
    description: 'Unit, integration and end-to-end testing; assertions, mocks, async tests, testable design.',
    icon: 'science',
    topicIds: ['testing'],
    objectives: [
      'Write unit tests with arrange/act/assert',
      'Test asynchronous code and rejected promises',
      'Use mocks and spies without over-mocking',
      'Structure code so it is testable in the first place',
    ],
    prerequisites: ['m40'],
  },
  {
    id: 'm43', slug: 'performance', order: 43, track: PROFESSIONAL, difficulty: HARD,
    title: 'Performance',
    shortTitle: 'Performance',
    description: 'Measuring first, DOM cost, debounce and throttle, memory leaks and code splitting.',
    icon: 'speed',
    topicIds: ['performance'],
    objectives: [
      'Measure before optimising using real browser tooling',
      'Implement debounce and throttle from scratch',
      'Identify and fix the common memory leak sources',
      'Reduce layout thrashing and unnecessary DOM work',
    ],
    prerequisites: ['m33'],
  },
  {
    id: 'm44', slug: 'security', order: 44, track: PROFESSIONAL, difficulty: HARD,
    title: 'JavaScript Security',
    shortTitle: 'Security',
    description: 'Trust boundaries, XSS, safe DOM APIs, token storage and dependency risk — defensively.',
    icon: 'shield',
    topicIds: ['security'],
    objectives: [
      'Identify trust boundaries in a front-end application',
      'Prevent XSS by choosing safe DOM APIs and escaping output',
      'Explain why client-side validation is never a security control',
      'Reason about token storage trade-offs honestly',
    ],
    prerequisites: ['m26'],
  },
  {
    id: 'm45', slug: 'workflow', order: 45, track: PROFESSIONAL, difficulty: MEDIUM,
    title: 'Professional JavaScript Workflow',
    shortTitle: 'Workflow',
    description: 'DevTools, npm, semantic versioning, bundlers, environment variables and reading docs well.',
    icon: 'terminal',
    topicIds: ['tooling', 'debugging'],
    objectives: [
      'Navigate browser DevTools beyond console.log',
      'Understand package.json, lockfiles and semantic versioning',
      'Explain what a bundler does and why Vite is fast',
      'Handle environment variables without leaking secrets',
    ],
    prerequisites: ['m28'],
  },
  {
    id: 'm46', slug: 'interview-mastery', order: 46, track: INTERVIEW, difficulty: HARD,
    title: 'Interview Mastery',
    shortTitle: 'Interview Mastery',
    description: 'Turning knowledge into precise, confident answers — technique, structure and rehearsal.',
    icon: 'workspace_premium',
    topicIds: ['interview'],
    objectives: [
      'Structure a technical answer in 30 seconds, then go deeper on request',
      'Reason aloud through code-output questions methodically',
      'Debug and refactor under observation',
      'Identify and close your own weakest topics before the interview',
    ],
    prerequisites: ['m33', 'm39'],
  },
];

export const MODULE_BY_ID = Object.fromEntries(MODULES.map((m) => [m.id, m]));
export const MODULE_BY_SLUG = Object.fromEntries(MODULES.map((m) => [m.slug, m]));
