import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm35';

export default [
  /* ================================================================== */
  {
    id: 'l-m35-01',
    slug: 'the-iteration-protocol',
    moduleId: M,
    order: 1,
    title: 'The Iteration Protocol',
    description: 'What `for...of` actually requires — and the difference between an iterable and an iterator.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 18,
    xp: 45,
    topicIds: ['iterators'],
    prerequisites: ['l-m34-04'],
    learningObjectives: [
      'Distinguish an iterable from an iterator precisely',
      'Drive an iterator manually with next()',
      'Explain which built-ins are iterable and which are not',
      'Contrast for...of with for...in',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Two different things',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Iterable and iterator are not synonyms',
        body: [
          'An **iterable** is an object with a **`[Symbol.iterator]()`** method. It answers "can you be looped over?" by handing back an iterator.',
          'An **iterator** is an object with a **`next()`** method returning `{ value, done }`. It answers "what comes next?" and holds the position.',
          'One object can be **both** — implementing `next()` *and* returning itself from `[Symbol.iterator]()`. Every built-in iterator does exactly that, which is why the two are so often conflated.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Getting an iterator from an iterable, by hand.',
        code: [
          '"use strict";',
          '',
          'const array = ["a", "b"];',
          '',
          '// The array is ITERABLE — it has the method',
          'console.log("iterable:", typeof array[Symbol.iterator]);',
          '',
          '// Calling it gives an ITERATOR — a separate object with position',
          'const iterator = array[Symbol.iterator]();',
          '',
          'console.log("is the array:", iterator === array);',
          'console.log("has next    :", typeof iterator.next);',
          '',
          'console.log(iterator.next());',
          'console.log(iterator.next());',
          'console.log(iterator.next());',
          'console.log(iterator.next());',
        ].join('\n'),
        output: [
          'iterable: function',
          'is the array: false',
          'has next    : function',
          '{value: "a", done: false}',
          '{value: "b", done: false}',
          '{value: undefined, done: true}',
          '{value: undefined, done: true}',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Note the array is **not** its own iterator — calling `[Symbol.iterator]()` produced a distinct object. That is what allows two independent loops over the same array.',
          'Once exhausted, `next()` keeps returning `{ value: undefined, done: true }` forever. An iterator never restarts; you get a fresh one by calling `[Symbol.iterator]()` again.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A built-in iterator is also iterable — returning itself.',
        code: [
          '"use strict";',
          '',
          'const iterator = [1, 2, 3][Symbol.iterator]();',
          '',
          '// It has next(), so it is an iterator',
          'console.log("iterator:", typeof iterator.next);',
          '',
          '// It ALSO has [Symbol.iterator], returning itself',
          'console.log("iterable:", typeof iterator[Symbol.iterator]);',
          'console.log("self    :", iterator[Symbol.iterator]() === iterator);',
          '',
          '// Which is why an iterator can be used with for...of directly',
          'iterator.next();                      // consume the first value',
          '',
          'const rest = [];',
          'for (const value of iterator) rest.push(value);',
          '',
          'console.log("resumed :", rest);',
        ].join('\n'),
        output: [
          'iterator: function',
          'iterable: function',
          'self    : true',
          'resumed : [2, 3]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'An iterator is consumed, not reset',
        body: [
          'The loop above started at `2` because `next()` had already taken `1`. Iterating an iterator **continues from its position** rather than restarting.',
          'This causes real bugs: passing the same iterator to two loops leaves the second with nothing, and `[...iterator]` after a partial loop yields only the remainder. Pass the **iterable** when you want repeatability.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'What `for...of` does',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The loop, written out manually.',
        code: [
          '"use strict";',
          '',
          'function manualForOf(iterable) {',
          '  const collected = [];',
          '',
          '  // 1. Ask the iterable for an iterator',
          '  const iterator = iterable[Symbol.iterator]();',
          '',
          '  // 2. Call next() until done',
          '  let result = iterator.next();',
          '',
          '  while (!result.done) {',
          '    collected.push(result.value);',
          '    result = iterator.next();',
          '  }',
          '',
          '  return collected;',
          '}',
          '',
          'console.log("array :", manualForOf([1, 2, 3]));',
          'console.log("string:", manualForOf("hey"));',
          'console.log("set   :", manualForOf(new Set([1, 1, 2])));',
          'console.log("map   :", manualForOf(new Map([["k", 1]])));',
        ].join('\n'),
        output: [
          'array : [1, 2, 3]',
          'string: ["h", "e", "y"]',
          'set   : [1, 2]',
          'map   : [["k", 1]]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'That is the entire protocol. Anything implementing `[Symbol.iterator]` works with `for...of`, spread, destructuring, `Array.from`, `Promise.all`, and the `Map`/`Set` constructors — they all consume iterables through this one mechanism.',
          'Note `done` is checked **before** using `value`: the final `{ done: true }` result\'s `value` is not part of the sequence, which is why `for...of` never yields it.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Everywhere the protocol is used.',
        code: [
          '"use strict";',
          '',
          'const set = new Set(["a", "b", "c"]);',
          '',
          'console.log("spread     :", [...set]);',
          'console.log("destructure:", (([first, second]) => [first, second])(set));',
          'console.log("Array.from :", Array.from(set));',
          '',
          '// Function call spread uses it too',
          'console.log("arguments  :", Math.max(...new Set([3, 1, 4])));',
          '',
          '// And so does the Map constructor, given pairs',
          'console.log("Map from   :", [...new Map([["x", 1]])]);',
        ].join('\n'),
        output: [
          'spread     : ["a", "b", "c"]',
          'destructure: ["a", "b"]',
          'Array.from : ["a", "b", "c"]',
          'arguments  : 4',
          'Map from   : [["x", 1]]',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'Plain objects are not iterable',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The most common iteration error.',
        code: [
          '"use strict";',
          '',
          'const object = { a: 1, b: 2 };',
          '',
          'console.log("has the method:", typeof object[Symbol.iterator]);',
          '',
          'try {',
          '  for (const value of object) console.log(value);',
          '} catch (error) {',
          '  console.log("for...of :", error.name);',
          '  console.log("message  :", error.message);',
          '}',
          '',
          '// The usual fixes',
          'console.log("keys    :", Object.keys(object));',
          'console.log("values  :", Object.values(object));',
          'console.log("entries :", Object.entries(object));',
          '',
          'for (const [key, value] of Object.entries(object)) {',
          '  console.log("entry   :", key, value);',
          '}',
        ].join('\n'),
        output: [
          'has the method: undefined',
          'for...of : TypeError',
          'message  : object is not iterable',
          'keys    : ["a", "b"]',
          'values  : [1, 2]',
          'entries : [["a", 1], ["b", 2]]',
          'entry   : a 1',
          'entry   : b 2',
        ].join('\n'),
      },
      {
        kind: SECTION.TABLE,
        headers: ['', '`for...of`', '`for...in`'],
        rows: [
          ['Iterates', '**Values**, via the iteration protocol', '**Keys**, as strings'],
          ['Works on', 'Iterables — arrays, strings, `Map`, `Set`', 'Any object'],
          ['Plain objects', '**TypeError**', 'Works'],
          ['Prototype chain', 'Not involved', '**Walks it** — needs a `hasOwn` guard'],
          ['Arrays', 'Elements, in order', 'Indices **as strings**, plus any extra properties'],
          ['`break` / `continue`', 'Yes', 'Yes'],
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Why for...in is the wrong tool for arrays.',
        code: [
          '"use strict";',
          '',
          'const array = ["a", "b"];',
          'array.extra = "not an element";',
          '',
          'const viaIn = [];',
          'for (const key in array) viaIn.push(key);',
          '',
          'const viaOf = [];',
          'for (const value of array) viaOf.push(value);',
          '',
          'console.log("for...in :", viaIn);',
          'console.log("for...of :", viaOf);',
          '',
          '// The indices are STRINGS, which breaks arithmetic',
          'console.log("index type:", typeof viaIn[0]);',
          'console.log("index + 1 :", viaIn[0] + 1);',
        ].join('\n'),
        output: [
          'for...in : ["0", "1", "extra"]',
          'for...of : ["a", "b"]',
          'index type: string',
          'index + 1 : 01',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Never use `for...in` on an array',
        body: [
          'It yields **string** keys, so `key + 1` concatenates rather than adds — the same coercion trap as a form value. It also includes any non-index properties, and it walks the prototype chain.',
          'Use `for...of` for values, `entries()` when you need the index, or an array method. `for...in` belongs to plain objects, and even there `Object.entries` is usually clearer.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const it = [1, 2, 3][Symbol.iterator]();',
          '',
          'console.log([...it]);',
          'console.log([...it]);',
        ].join('\n'),
        options: [
          '[1, 2, 3] then []',
          '[1, 2, 3] then [1, 2, 3]',
          '[] then []',
          'It throws on the second',
        ],
        correct: 0,
        explanation:
          'Spreading consumes the iterator to completion, so the first line yields `[1, 2, 3]`. An iterator holds its **position** and never restarts — after exhaustion `next()` returns `{ value: undefined, done: true }` forever — so the second spread finds nothing and produces `[]`. It does not throw, because an exhausted iterator is still a valid iterable that returns itself. Spreading the **array** twice would give `[1, 2, 3]` both times, since each spread calls `[Symbol.iterator]()` and gets a **fresh** iterator. This is why you pass the iterable, not the iterator, when the consumer may need to iterate more than once.',
      },
    ],
    exercises: [
      {
        id: 'ex-m35-01-a',
        title: 'Iterable or iterator?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['iterators'],
        instructions:
          'What is the difference between an iterable and an iterator?',
        options: [
          'They are the same thing',
          'An iterable has [Symbol.iterator]() returning an iterator; an iterator has next() returning { value, done }',
          'An iterable has next(); an iterator has [Symbol.iterator]()',
          'An iterator only works with arrays',
        ],
        correct: 1,
        hints: [
          'Which one holds the current position?',
        ],
        solution: 'An iterable has [Symbol.iterator]() returning an iterator; an iterator has next() returning { value, done }',
        solutionExplanation:
          'The iterable answers "can you be looped over?" by producing an iterator; the iterator answers "what comes next?" and holds the **position**. They are commonly conflated because every built-in iterator is *also* iterable, returning itself from `[Symbol.iterator]()` — which is what lets you pass an iterator straight to `for...of`. The practical consequence of the distinction is that an iterator is consumed once, while an iterable produces a fresh iterator each time.',
      },
      {
        id: 'ex-m35-01-b',
        title: 'Drive an iterator manually',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['iterators'],
        instructions:
          'Write `take(iterable, count)` returning an array of at most the first `count` values, without using `for...of`, spread or `Array.from` — drive the iterator with `next()`.',
        starterCode: [
          'function take(iterable, count) {',
          '  // Get an iterator, then call next() at most `count` times.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'takes from an array', body: 'expect(take([1, 2, 3, 4], 2)).toEqual([1, 2]);' },
          { name: 'takes from a string', body: 'expect(take("hello", 3)).toEqual(["h", "e", "l"]);' },
          { name: 'takes from a Set', body: 'expect(take(new Set([1, 2, 3]), 2)).toEqual([1, 2]);' },
          { name: 'stops early when exhausted', body: 'expect(take([1], 5)).toEqual([1]);' },
          { name: 'takes zero', body: 'expect(take([1, 2], 0)).toEqual([]);' },
          { name: 'handles an empty iterable', body: 'expect(take([], 3)).toEqual([]);' },
          { name: 'does not consume more than needed', body: 'const it = [1, 2, 3][Symbol.iterator](); take(it, 1); expect(it.next().value).toBe(2);', hidden: true },
        ],
        hints: [
          '`const iterator = iterable[Symbol.iterator]()`',
          'Loop while you have taken fewer than `count`.',
          'Break as soon as a result has `done: true`.',
        ],
        solution: [
          'function take(iterable, count) {',
          '  const iterator = iterable[Symbol.iterator]();',
          '  const result = [];',
          '',
          '  while (result.length < count) {',
          '    const next = iterator.next();',
          '',
          '    if (next.done) break;',
          '',
          '    result.push(next.value);',
          '  }',
          '',
          '  return result;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Checking `next.done` **before** using `next.value` is essential: the final result carries `undefined` as its value and is not part of the sequence, so pushing it would append a spurious entry. The `result.length < count` condition handles `count: 0` without a special case, since the loop simply never runs. The hidden test is the important one — calling `next()` exactly as many times as needed leaves the iterator positioned for the caller, which is what makes this composable and what a spread-based implementation could not do.',
      },
      {
        id: 'ex-m35-01-c',
        title: 'Why is a plain object not iterable?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['iterators'],
        instructions:
          '`for (const x of { a: 1 })` throws. Why, and what should you use?',
        options: [
          'Objects have no properties to iterate',
          'A plain object has no [Symbol.iterator] method — use Object.keys, values or entries',
          'for...of only works on arrays',
          'You must use JSON.stringify first',
        ],
        correct: 1,
        hints: [
          'What exactly does for...of ask the value for?',
        ],
        solution: 'A plain object has no [Symbol.iterator] method — use Object.keys, values or entries',
        solutionExplanation:
          '`for...of` requires the iteration protocol, and `Object.prototype` provides no `[Symbol.iterator]`, so the loop throws `TypeError: object is not iterable`. This is deliberate: an object is a **record**, and there is no single obvious sequence — keys, values or entries are all reasonable, so the language makes you say which. `for...of` works on arrays, strings, `Map`, `Set` and anything else implementing the protocol, which lesson 2 shows you can do yourself.',
      },
      {
        id: 'ex-m35-01-d',
        title: 'for...of versus for...in',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['iterators'],
        instructions:
          'For `const a = ["x", "y"]`, what does `for (const k in a)` yield?',
        options: ['"x" and "y"', 'The strings "0" and "1"', 'The numbers 0 and 1', 'Nothing'],
        correct: 1,
        hints: [
          'What type is an object key?',
        ],
        solution: 'The strings "0" and "1"',
        solutionExplanation:
          '`for...in` enumerates **keys**, and object keys are always strings — so you get `"0"` and `"1"`, not numbers. That breaks arithmetic silently: `"0" + 1` is `"01"`. It would also include any non-index property added to the array and would walk the prototype chain. Use `for...of` for values, or `array.entries()` when you genuinely need a numeric index.',
      },
    ],
    quiz: {
      id: 'qz-m35-01',
      questions: [
        {
          id: 'q-m35-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['iterators'],
          prompt: 'What must an object have to work with for...of?',
          options: ['A length property', 'A [Symbol.iterator]() method', 'A next() method', 'Numeric keys'],
          correct: 1,
          optionExplanations: [
            'Array-likes need Array.from.',
            'Correct — that is the iterable protocol.',
            'That makes it an iterator, not an iterable.',
            'Keys are irrelevant.',
          ],
          explanation:
            '`for...of` calls `[Symbol.iterator]()` to obtain an iterator, then calls `next()` until `done`. Anything providing that method is iterable.',
        },
        {
          id: 'q-m35-01-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['iterators'],
          prompt: 'What does an iterator\'s next() return?',
          options: ['The value', '{ value, done }', 'true or false', 'An array'],
          correct: 1,
          optionExplanations: [
            'It is wrapped in a result object.',
            'Correct — check done before using value.',
            'That is the done flag only.',
            'A plain object.',
          ],
          explanation:
            'A result object with `value` and `done`. The final result has `done: true` and a `value` that is not part of the sequence, so `done` must be checked first.',
        },
        {
          id: 'q-m35-01-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['iterators'],
          prompt: 'You can iterate the same iterator twice and get the same values.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It holds a position and does not restart.',
            'Correct — the second pass gets nothing.',
          ],
          explanation:
            'An iterator is consumed. Iterate the **iterable** instead, which produces a fresh iterator each time.',
        },
        {
          id: 'q-m35-01-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['iterators'],
          prompt: 'Which is NOT iterable?',
          options: ['A string', 'A Map', 'A plain object', 'A Set'],
          correct: 2,
          optionExplanations: [
            'Strings iterate by character.',
            'Maps yield [key, value] pairs.',
            'Correct — use Object.entries.',
            'Sets yield their values.',
          ],
          explanation:
            'Plain objects have no `[Symbol.iterator]`, deliberately — keys, values and entries are all reasonable sequences, so you must choose with `Object.keys`, `Object.values` or `Object.entries`.',
        },
      ],
    },
    summary:
      'An **iterable** has a **`[Symbol.iterator]()`** method returning an iterator; an **iterator** has a **`next()`** method returning `{ value, done }` and holds the **position**. They are conflated because every built-in iterator is *also* iterable, returning **itself** — which is why an iterator can be passed straight to `for...of`. The practical difference is that an **iterator is consumed**: it never restarts, `next()` returns `{ done: true }` forever once exhausted, and spreading it twice gives the values then nothing. Pass the **iterable** when the consumer may iterate more than once. `for...of` is exactly: call `[Symbol.iterator]()`, then `next()` until `done` — checking `done` **before** using `value`, since the final result\'s value is not part of the sequence. The same protocol powers **spread, destructuring, `Array.from`, `Promise.all`** and the `Map`/`Set` constructors, so implementing it once makes an object work everywhere. **Plain objects are not iterable** — deliberately, since keys, values and entries are all reasonable sequences — so `for...of` throws and you choose with `Object.entries`. Finally, **never use `for...in` on an array**: it yields **string** keys (so `key + 1` concatenates), includes non-index properties, and walks the prototype chain.',
    keyTakeaways: [
      'Iterable has [Symbol.iterator](); iterator has next() and holds position',
      'Built-in iterators are also iterable, returning themselves',
      'An iterator is consumed once — pass the iterable for repeat iteration',
      'Check done before using value; the final value is not part of the sequence',
      'Spread, destructuring, Array.from and Promise.all all use this protocol',
      'Plain objects are not iterable; for...in on an array yields string keys',
    ],
    relatedLessons: ['l-m35-02', 'l-m35-03'],
    interviewConnections: [
      'What is the difference between an iterable and an iterator?',
      'What does for...of require of a value?',
      'Why can you not use for...of on a plain object?',
      'Why should you not use for...in on an array?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m35-02',
    slug: 'custom-iterables',
    moduleId: M,
    order: 2,
    title: 'Custom Iterables',
    description: 'Implementing the protocol yourself, and making your own types work with everything.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 16,
    xp: 45,
    topicIds: ['iterators'],
    prerequisites: ['l-m35-01'],
    learningObjectives: [
      'Write an iterator by hand',
      'Make an object iterable with [Symbol.iterator]',
      'Ensure repeated iteration works correctly',
      'Make a class iterable',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'An iterator by hand',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Just an object with a next() method.',
        code: [
          '"use strict";',
          '',
          'function createCounter(limit) {',
          '  let current = 1;',
          '',
          '  return {',
          '    next() {',
          '      if (current <= limit) {',
          '        return { value: current++, done: false };',
          '      }',
          '',
          '      return { value: undefined, done: true };',
          '    },',
          '  };',
          '}',
          '',
          'const counter = createCounter(3);',
          '',
          'console.log(counter.next());',
          'console.log(counter.next());',
          'console.log(counter.next());',
          'console.log(counter.next());',
          '',
          '// But it is NOT iterable — it has no [Symbol.iterator]',
          'try {',
          '  for (const n of createCounter(2)) console.log(n);',
          '} catch (error) {',
          '  console.log("for...of:", error.name);',
          '}',
        ].join('\n'),
        output: [
          '{value: 1, done: false}',
          '{value: 2, done: false}',
          '{value: 3, done: false}',
          '{value: undefined, done: true}',
          'for...of: TypeError',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The state lives in a closure — Module 32 — and `next()` reads and advances it. That is a complete iterator.',
          'But `for...of` asks for `[Symbol.iterator]`, and this object has none. Adding it is one line.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Making it iterable by returning itself.',
        code: [
          '"use strict";',
          '',
          'function createCounter(limit) {',
          '  let current = 1;',
          '',
          '  return {',
          '    next() {',
          '      return current <= limit',
          '        ? { value: current++, done: false }',
          '        : { value: undefined, done: true };',
          '    },',
          '',
          '    // Now it is both an iterator AND an iterable',
          '    [Symbol.iterator]() { return this; },',
          '  };',
          '}',
          '',
          'const collected = [];',
          'for (const n of createCounter(3)) collected.push(n);',
          '',
          'console.log("for...of:", collected);',
          'console.log("spread  :", [...createCounter(4)]);',
          '',
          '// The consumed-once caveat applies, because it IS the iterator',
          'const counter = createCounter(3);',
          'console.log("first   :", [...counter]);',
          'console.log("again   :", [...counter]);',
        ].join('\n'),
        output: [
          'for...of: [1, 2, 3]',
          'spread  : [1, 2, 3, 4]',
          'first   : [1, 2, 3]',
          'again   : []',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Returning `this` makes it single-use',
        body: [
          '`[Symbol.iterator]() { return this; }` is the right shape for something that genuinely represents a **one-time stream**, and it is what every built-in iterator does.',
          'But for a **collection** — something that should be iterable repeatedly, like a range — it is wrong: the second loop finds the position already at the end. The next example fixes that by returning a **fresh** iterator each time.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'A repeatable iterable',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A fresh iterator per call — the correct shape for a collection.',
        code: [
          '"use strict";',
          '',
          'const range = {',
          '  from: 1,',
          '  to: 4,',
          '',
          '  [Symbol.iterator]() {',
          '    // The position lives in the ITERATOR, not in the range',
          '    let current = this.from;',
          '    const last = this.to;',
          '',
          '    return {',
          '      next() {',
          '        return current <= last',
          '          ? { value: current++, done: false }',
          '          : { value: undefined, done: true };',
          '      },',
          '    };',
          '  },',
          '};',
          '',
          'console.log("first pass :", [...range]);',
          'console.log("second pass:", [...range]);',
          '',
          '// Two loops can run over it independently',
          'const pairs = [];',
          'for (const a of range) {',
          '  for (const b of range) {',
          '    if (a + b === 5) pairs.push(`${a}+${b}`);',
          '  }',
          '}',
          'console.log("nested     :", pairs);',
        ].join('\n'),
        output: [
          'first pass : [1, 2, 3, 4]',
          'second pass: [1, 2, 3, 4]',
          'nested     : ["1+4", "2+3", "3+2", "4+1"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Where the position lives is the whole design decision',
        body: [
          'Putting `current` **inside** `[Symbol.iterator]()` means each call creates a new one, so every loop starts fresh and nested loops do not interfere — which the nested example proves.',
          'Putting it on the object itself would make all loops share one position, producing exactly the bug the previous example demonstrated.',
          'Rule of thumb: a **collection** returns a fresh iterator; a **stream** returns itself.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Making a class iterable',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'One method makes a class work with every consumer.',
        code: [
          '"use strict";',
          '',
          'class Playlist {',
          '  #tracks = [];',
          '',
          '  add(track) {',
          '    this.#tracks.push(track);',
          '    return this;',
          '  }',
          '',
          '  // Delegate to the array\'s own iterator — simplest correct approach',
          '  [Symbol.iterator]() {',
          '    return this.#tracks[Symbol.iterator]();',
          '  }',
          '',
          '  get size() { return this.#tracks.length; }',
          '}',
          '',
          'const playlist = new Playlist().add("one").add("two").add("three");',
          '',
          'console.log("for...of  :", (() => {',
          '  const out = [];',
          '  for (const track of playlist) out.push(track);',
          '  return out;',
          '})());',
          '',
          'console.log("spread    :", [...playlist]);',
          'console.log("destructure:", (([first]) => first)(playlist));',
          'console.log("Array.from:", Array.from(playlist, (t) => t.toUpperCase()));',
          'console.log("repeatable:", [...playlist].length, [...playlist].length);',
        ].join('\n'),
        output: [
          'for...of  : ["one", "two", "three"]',
          'spread    : ["one", "two", "three"]',
          'destructure: one',
          'Array.from: ["ONE", "TWO", "THREE"]',
          'repeatable: 3 3',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Delegating to the internal array\'s iterator is both the simplest and the most correct option: it is repeatable, correctly ordered, and requires no manual position tracking. The private field stays private — consumers get values, not the array.',
          'Note this exposes iteration **without** exposing the array, so a caller cannot push into it. Compare with returning `this.#tracks` directly, which would hand out mutability, as Module 32 warned.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Multiple iteration orders, as named methods.',
        code: [
          '"use strict";',
          '',
          'class Matrix {',
          '  constructor(rows) { this.rows = rows; }',
          '',
          '  // The default: row by row',
          '  [Symbol.iterator]() {',
          '    return this.byRow();',
          '  }',
          '',
          '  *byRow() {',
          '    for (const row of this.rows) {',
          '      for (const value of row) yield value;',
          '    }',
          '  }',
          '',
          '  *byColumn() {',
          '    const width = this.rows[0].length;',
          '',
          '    for (let c = 0; c < width; c++) {',
          '      for (const row of this.rows) yield row[c];',
          '    }',
          '  }',
          '}',
          '',
          'const matrix = new Matrix([[1, 2], [3, 4]]);',
          '',
          'console.log("default :", [...matrix]);',
          'console.log("by row  :", [...matrix.byRow()]);',
          'console.log("by col  :", [...matrix.byColumn()]);',
        ].join('\n'),
        output: [
          'default : [1, 2, 3, 4]',
          'by row  : [1, 2, 3, 4]',
          'by col  : [1, 3, 2, 4]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Those `*` methods are generators — lesson 3',
        body: [
          'Writing `byColumn` as a hand-written iterator would need explicit row and column counters and careful `done` handling. As a **generator** it is two nested loops and a `yield`.',
          'That is the point of generators: they let you write the *traversal* directly and have the iterator built for you. Every custom iterable in this lesson could be written more briefly as one, which lesson 3 does.',
          'Note `Symbol.iterator` is a **well-known symbol** — a name the language itself looks for, which is why it is a symbol rather than a string. Module 36 covers those properly.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const bad = {',
          '  current: 0,',
          '  [Symbol.iterator]() { return this; },',
          '  next() {',
          '    return this.current < 2',
          '      ? { value: this.current++, done: false }',
          '      : { done: true };',
          '  },',
          '};',
          '',
          'console.log([...bad], [...bad]);',
        ].join('\n'),
        options: [
          '[0, 1] then []',
          '[0, 1] then [0, 1]',
          '[] then []',
          'It throws',
        ],
        correct: 0,
        explanation:
          'The position `current` lives **on the object itself**, and `[Symbol.iterator]()` returns `this` — so both spreads share one position. The first consumes it to `2`, and the second finds `current` already past the limit and yields nothing. To make it repeatable, move the position **inside** `[Symbol.iterator]()` so each call creates a fresh iterator with its own `current`. The general rule: a **collection** returns a new iterator each time; only a genuine one-time **stream** should return `this`.',
      },
    ],
    exercises: [
      {
        id: 'ex-m35-02-a',
        title: 'Make a range iterable',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['iterators'],
        instructions:
          'Write `createRange(from, to)` returning an object that is iterable over the inclusive integers, and that can be iterated **repeatedly**. Do not use a generator.',
        starterCode: [
          'function createRange(from, to) {',
          '  // Where you put the position decides whether it is repeatable.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'iterates inclusively', body: 'expect([...createRange(1, 3)]).toEqual([1, 2, 3]);' },
          { name: 'works with for...of', body: 'const out = []; for (const n of createRange(1, 2)) out.push(n); expect(out).toEqual([1, 2]);' },
          { name: 'is repeatable', body: 'const r = createRange(1, 3); expect([[...r], [...r]]).toEqual([[1, 2, 3], [1, 2, 3]]);' },
          { name: 'handles a single value', body: 'expect([...createRange(5, 5)]).toEqual([5]);' },
          { name: 'handles an empty range', body: 'expect([...createRange(3, 1)]).toEqual([]);' },
          { name: 'supports nested loops', body: 'const r = createRange(1, 2); const out = []; for (const a of r) for (const b of r) out.push(`${a}${b}`); expect(out).toEqual(["11", "12", "21", "22"]);' },
          { name: 'works with Array.from', body: 'expect(Array.from(createRange(1, 2))).toEqual([1, 2]);', hidden: true },
        ],
        hints: [
          'Return an object with a `[Symbol.iterator]()` method.',
          'Declare the position variable **inside** that method.',
          'Return `{ next() { ... } }` from it.',
        ],
        solution: [
          'function createRange(from, to) {',
          '  return {',
          '    [Symbol.iterator]() {',
          '      let current = from;',
          '',
          '      return {',
          '        next() {',
          '          return current <= to',
          '            ? { value: current++, done: false }',
          '            : { value: undefined, done: true };',
          '        },',
          '      };',
          '    },',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Declaring `current` **inside** `[Symbol.iterator]()` is the whole exercise: each call creates a fresh iterator with its own position, which is what makes the third and sixth tests pass — repeated and nested iteration both work because the loops never share state. Putting `current` on the returned object instead would make the second pass empty. The empty-range case needs no special handling, since `current <= to` is false immediately. `Array.from` passes for free, because it consumes the same protocol.',
      },
      {
        id: 'ex-m35-02-b',
        title: 'Make a class iterable',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['iterators'],
        instructions:
          'Write a class `Bag` with `add(item)` (chainable) and a `size` getter, iterable over its items in insertion order, without exposing the internal array.',
        starterCode: [
          'class Bag {',
          '  // Keep the items private; delegate iteration to them.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'iterates its items', body: 'expect([...new Bag().add(1).add(2)]).toEqual([1, 2]);' },
          { name: 'add is chainable', body: 'expect(new Bag().add(1).add(2).size).toBe(2);' },
          { name: 'starts empty', body: 'expect([...new Bag()]).toEqual([]);' },
          { name: 'works with for...of', body: 'const out = []; for (const x of new Bag().add("a")) out.push(x); expect(out).toEqual(["a"]);' },
          { name: 'is repeatable', body: 'const b = new Bag().add(1); expect([[...b], [...b]]).toEqual([[1], [1]]);' },
          { name: 'does not expose the array', body: 'const b = new Bag().add(1); expect(Object.keys(b)).toEqual([]);' },
          { name: 'preserves insertion order', body: 'expect([...new Bag().add("c").add("a").add("b")]).toEqual(["c", "a", "b"]);', hidden: true },
        ],
        hints: [
          'Use a `#items = []` private field.',
          '`[Symbol.iterator]() { return this.#items[Symbol.iterator](); }`',
          '`add` returns `this` to chain.',
        ],
        solution: [
          'class Bag {',
          '  #items = [];',
          '',
          '  add(item) {',
          '    this.#items.push(item);',
          '    return this;',
          '  }',
          '',
          '  get size() { return this.#items.length; }',
          '',
          '  [Symbol.iterator]() {',
          '    return this.#items[Symbol.iterator]();',
          '  }',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Delegating to the array\'s own iterator is the simplest correct implementation: it is repeatable (a fresh iterator per call, so the fifth test passes), correctly ordered, and needs no manual position tracking. The private field keeps the array unreachable, which the sixth test confirms — consumers receive **values** without gaining the ability to mutate the collection, unlike returning `this.#items` directly. Returning `this` from `add` makes the calls chain, exactly as `Map.prototype.set` and `Set.prototype.add` do.',
      },
      {
        id: 'ex-m35-02-c',
        title: 'Why is my iterable empty the second time?',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.HARD,
        xp: 30,
        topicIds: ['iterators'],
        instructions:
          'Write `createSteps(count)` returning a repeatable iterable over `1..count`. The naive version below is single-use — put the position in the right place.',
        starterCode: [
          'function createSteps(count) {',
          '  // BROKEN shape — the position is shared:',
          '  // let current = 1;',
          '  // return { [Symbol.iterator]() { return this; }, next() { ... } };',
          '}',
        ].join('\n'),
        tests: [
          { name: 'iterates once correctly', body: 'expect([...createSteps(3)]).toEqual([1, 2, 3]);' },
          { name: 'iterates again correctly', body: 'const s = createSteps(3); [...s]; expect([...s]).toEqual([1, 2, 3]);' },
          { name: 'three passes all match', body: 'const s = createSteps(2); expect([[...s], [...s], [...s]]).toEqual([[1, 2], [1, 2], [1, 2]]);' },
          { name: 'handles zero', body: 'expect([...createSteps(0)]).toEqual([]);' },
          { name: 'independent instances', body: 'const a = createSteps(2); [...a]; expect([...createSteps(2)]).toEqual([1, 2]);' },
          { name: 'nested iteration works', body: 'const s = createSteps(2); const out = []; for (const a of s) for (const b of s) out.push(a + b); expect(out).toEqual([2, 3, 3, 4]);', hidden: true },
        ],
        hints: [
          'Do not keep `current` in the outer function scope.',
          'Declare it inside `[Symbol.iterator]()`.',
          'That method should return a **new** object with `next`.',
        ],
        solution: [
          'function createSteps(count) {',
          '  return {',
          '    [Symbol.iterator]() {',
          '      let current = 1;',
          '',
          '      return {',
          '        next() {',
          '          return current <= count',
          '            ? { value: current++, done: false }',
          '            : { value: undefined, done: true };',
          '        },',
          '      };',
          '    },',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The broken version keeps one `current` in the factory scope and returns `this`, so every consumer shares a single position — the second pass starts already exhausted. Moving the declaration **inside** `[Symbol.iterator]()` gives each call its own position, which is exactly what the repeat and nested tests check: the inner loop in the hidden test would otherwise consume the outer loop\'s iterator and terminate it early. `count` stays captured from the factory because it never changes; only the mutable position needs to be per-iterator.',
      },
      {
        id: 'ex-m35-02-d',
        title: 'Fresh iterator or this?',
        kind: EXERCISE_KIND.CHOOSE_IMPLEMENTATION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['iterators'],
        instructions:
          'You are implementing a `Playlist` class that users will loop over many times. Should `[Symbol.iterator]()` return `this` or a fresh iterator?',
        options: [
          'Return this — it is simpler',
          'Return a fresh iterator, so each loop starts from the beginning',
          'Either works identically',
          'Return the internal array',
        ],
        correct: 1,
        hints: [
          'What happens on the second loop if the position is shared?',
        ],
        solution: 'Return a fresh iterator, so each loop starts from the beginning',
        solutionExplanation:
          'A playlist is a **collection**, so every loop should see all the tracks — returning `this` would share one position, leaving the second loop empty and breaking nested loops. Returning `this` is correct only for a genuine one-time **stream**, which is what built-in iterators are. Returning the internal array would work for iteration but hands out mutability, letting callers push into your private state — delegating with `this.#items[Symbol.iterator]()` gives repeatable iteration while keeping the array unreachable.',
      },
    ],
    quiz: {
      id: 'qz-m35-02',
      questions: [
        {
          id: 'q-m35-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['iterators'],
          prompt: 'What is the minimum to make an object work with for...of?',
          options: [
            'A next() method',
            'A [Symbol.iterator]() method returning an object with next()',
            'A length property',
            'Extending Array',
          ],
          correct: 1,
          optionExplanations: [
            'That alone is an iterator, not an iterable.',
            'Correct — that is the whole requirement.',
            'Array-likes need Array.from.',
            'No inheritance is needed.',
          ],
          explanation:
            '`for...of` calls `[Symbol.iterator]()` and expects an object with `next()`. An object with only `next()` throws "is not iterable".',
        },
        {
          id: 'q-m35-02-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['iterators'],
          prompt: 'Where should the iteration position live for a repeatable collection?',
          options: [
            'On the object itself',
            'Inside [Symbol.iterator](), so each call gets a fresh one',
            'In a global variable',
            'On the prototype',
          ],
          correct: 1,
          optionExplanations: [
            'That makes it single-use.',
            'Correct — new position per iteration.',
            'Worse — shared across instances.',
            'Also shared.',
          ],
          explanation:
            'Declaring the position inside the method gives every loop its own, so repeated and nested iteration both work. On the object, all loops share one position.',
        },
        {
          id: 'q-m35-02-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['iterators'],
          prompt: 'Returning `this` from [Symbol.iterator]() is always wrong.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It is right for a one-time stream.',
            'Correct — every built-in iterator does exactly that.',
          ],
          explanation:
            'It is correct for something representing a single pass — which is why built-in iterators do it. It is wrong for a collection meant to be looped repeatedly.',
        },
        {
          id: 'q-m35-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['iterators'],
          prompt: 'What is the simplest way to make a class iterable over a private array?',
          options: [
            'Return the array from [Symbol.iterator]()',
            'Delegate: return this.#items[Symbol.iterator]()',
            'Extend Array',
            'Add a next() method',
          ],
          correct: 1,
          optionExplanations: [
            'An array is iterable but is not an iterator.',
            'Correct — repeatable, ordered, and keeps the array private.',
            'Unnecessary and awkward.',
            'That makes it an iterator, not an iterable.',
          ],
          explanation:
            'Delegating gives a fresh, correctly ordered iterator with no manual bookkeeping, and consumers receive values without gaining a reference they could mutate.',
        },
      ],
    },
    summary:
      'An **iterator** is just an object with a `next()` method returning `{ value, done }`, with its position typically held in a **closure**. Adding **`[Symbol.iterator]()`** makes something iterable — and *where you put the position* is the whole design decision. Returning **`this`** makes the object both iterator and iterable, which is exactly right for a one-time **stream** and is what every built-in iterator does — but it makes the object **single-use**, so a second loop finds the position already at the end and nested loops interfere. For a **collection**, declare the position **inside** `[Symbol.iterator]()` so each call produces a **fresh** iterator; then repeated and nested iteration both work. For a class, the simplest correct implementation is to **delegate** to an internal array\'s iterator: repeatable, correctly ordered, no manual bookkeeping — and it exposes **values** without handing out a mutable reference to the private array. Implementing this one method makes a type work with `for...of`, spread, destructuring, `Array.from`, `Promise.all` and the `Map`/`Set` constructors at once. Additional traversal orders can be exposed as extra named methods, and generators (lesson 3) make writing all of these dramatically shorter.',
    keyTakeaways: [
      'An iterator is an object with next(); [Symbol.iterator] makes it iterable',
      'Where the position lives decides whether iteration is repeatable',
      'Return this for a one-time stream; a fresh iterator for a collection',
      'Delegating to a private array\'s iterator is the simplest correct class approach',
      'Iteration exposes values without exposing the underlying collection',
      'One method makes a type work with every iterable consumer',
    ],
    relatedLessons: ['l-m35-01', 'l-m35-03'],
    interviewConnections: [
      'How do you make an object iterable?',
      'Why is my custom iterable empty on the second loop?',
      'When should [Symbol.iterator] return this?',
      'How would you make a class iterable over private data?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m35-03',
    slug: 'generators',
    moduleId: M,
    order: 3,
    title: 'Generators',
    description: 'Functions that pause and resume — writing traversals directly and producing values lazily.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 19,
    xp: 50,
    topicIds: ['iterators'],
    prerequisites: ['l-m35-02'],
    learningObjectives: [
      'Write generator functions and explain suspension',
      'Use generators to implement iterables concisely',
      'Produce values lazily without building a collection',
      'Explain return, delegation and two-way communication',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'A function that pauses',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Calling a generator runs none of its body.',
        code: [
          '"use strict";',
          '',
          'function* numbers() {',
          '  console.log("  body: starting");',
          '  yield 1;',
          '  console.log("  body: resumed after 1");',
          '  yield 2;',
          '  console.log("  body: resumed after 2");',
          '}',
          '',
          'console.log("calling the generator...");',
          'const iterator = numbers();',
          'console.log("nothing ran yet");',
          '',
          'console.log("next 1:", iterator.next());',
          'console.log("next 2:", iterator.next());',
          'console.log("next 3:", iterator.next());',
        ].join('\n'),
        output: [
          'calling the generator...',
          'nothing ran yet',
          '  body: starting',
          'next 1: {value: 1, done: false}',
          '  body: resumed after 1',
          'next 2: {value: 2, done: false}',
          '  body: resumed after 2',
          'next 3: {value: undefined, done: true}',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Calling a generator function does not run it',
        body: [
          'It returns a **generator object** — an iterator — with the body **suspended before the first line**. Nothing executes until the first `next()`.',
          'Each `next()` runs until the next `yield`, hands back that value, and **suspends again with all local state intact**. That is what makes generators different from any ordinary function: they can be paused mid-execution and resumed.',
          'When the body finishes, the result is `{ value: undefined, done: true }` — and the generator is exhausted permanently, exactly like any other iterator.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A generator object is an iterator AND iterable.',
        code: [
          '"use strict";',
          '',
          'function* letters() {',
          '  yield "a";',
          '  yield "b";',
          '  yield "c";',
          '}',
          '',
          'const gen = letters();',
          '',
          'console.log("has next    :", typeof gen.next);',
          'console.log("is iterable :", typeof gen[Symbol.iterator]);',
          'console.log("returns self:", gen[Symbol.iterator]() === gen);',
          '',
          '// So all the usual consumers work',
          'console.log("spread   :", [...letters()]);',
          'console.log("for...of :", (() => { const o = []; for (const l of letters()) o.push(l); return o; })());',
          'console.log("Array.from:", Array.from(letters()));',
          '',
          '// But a single generator object is still consumed once',
          'console.log("first  :", [...gen]);',
          'console.log("again  :", [...gen]);',
        ].join('\n'),
        output: [
          'has next    : function',
          'is iterable : function',
          'returns self: true',
          'spread   : ["a", "b", "c"]',
          'for...of : ["a", "b", "c"]',
          'Array.from: ["a", "b", "c"]',
          'first  : ["a", "b", "c"]',
          'again  : []',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'Generators as iterables',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The same range, hand-written versus generated.',
        code: [
          '"use strict";',
          '',
          '// Lesson 2\'s version, for comparison',
          'function rangeManual(from, to) {',
          '  return {',
          '    [Symbol.iterator]() {',
          '      let current = from;',
          '      return {',
          '        next() {',
          '          return current <= to',
          '            ? { value: current++, done: false }',
          '            : { value: undefined, done: true };',
          '        },',
          '      };',
          '    },',
          '  };',
          '}',
          '',
          '// The generator version — and it is repeatable, because',
          '// the method creates a NEW generator object on every call',
          'function rangeGenerated(from, to) {',
          '  return {',
          '    *[Symbol.iterator]() {',
          '      for (let i = from; i <= to; i++) yield i;',
          '    },',
          '  };',
          '}',
          '',
          'const manual = rangeManual(1, 3);',
          'const generated = rangeGenerated(1, 3);',
          '',
          'console.log("manual    :", [...manual], [...manual]);',
          'console.log("generated :", [...generated], [...generated]);',
        ].join('\n'),
        output: [
          'manual    : [1, 2, 3] [1, 2, 3]',
          'generated : [1, 2, 3] [1, 2, 3]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Generators handle the bookkeeping for you',
        body: [
          'The generator version is four lines instead of twelve, and there is no `{ value, done }` construction, no manual position variable, and no chance of forgetting `done`.',
          'It is also **repeatable** for free: `*[Symbol.iterator]()` is a generator *method*, so each call creates a new generator object with a fresh suspended body — exactly the "fresh iterator per call" rule from lesson 2, achieved without thinking about it.',
          'This is why almost all real custom iterables are written as generators.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Traversing a tree — where generators genuinely shine.',
        code: [
          '"use strict";',
          '',
          'const tree = {',
          '  value: 1,',
          '  children: [',
          '    { value: 2, children: [{ value: 4, children: [] }] },',
          '    { value: 3, children: [] },',
          '  ],',
          '};',
          '',
          '// Recursion + yield* — a hand-written iterator here would need',
          '// an explicit stack and careful state management',
          'function* walk(node) {',
          '  yield node.value;',
          '',
          '  for (const child of node.children) {',
          '    yield* walk(child);          // delegate to another generator',
          '  }',
          '}',
          '',
          'console.log("depth first:", [...walk(tree)]);',
          '',
          '// yield* delegates to ANY iterable, not only generators',
          'function* mixed() {',
          '  yield 0;',
          '  yield* [1, 2];',
          '  yield* "ab";',
          '  yield* new Set([3]);',
          '}',
          '',
          'console.log("delegated  :", [...mixed()]);',
        ].join('\n'),
        output: [
          'depth first: [1, 2, 4, 3]',
          'delegated  : [0, 1, 2, "a", "b", 3]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: '`yield*` delegates, `yield` emits',
        body: [
          '`yield value` produces one value. **`yield* iterable`** produces **every** value from that iterable, one at a time, as if they had been yielded individually.',
          'That makes recursive traversal almost trivial — `yield* walk(child)` handles an entire subtree — where a hand-written iterator would need an explicit stack to remember where it was in each branch.',
          'Note `yield*` works with any iterable, not just generators, which is why arrays, strings and `Set`s all delegate cleanly above.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Laziness',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Values are produced only when asked for.',
        code: [
          '"use strict";',
          '',
          'let produced = 0;',
          '',
          'function* naturals() {',
          '  let n = 1;',
          '',
          '  // An unbounded sequence — safe, because nothing runs unasked',
          '  while (true) {',
          '    produced += 1;',
          '    yield n++;',
          '  }',
          '}',
          '',
          '// A bounded consumer is what keeps this finite',
          'function* take(iterable, count) {',
          '  let taken = 0;',
          '',
          '  for (const value of iterable) {',
          '    if (taken >= count) return;',
          '    taken += 1;',
          '    yield value;',
          '  }',
          '}',
          '',
          'console.log("first five:", [...take(naturals(), 5)]);',
          'console.log("produced  :", produced);',
          '',
          '// Composing lazy steps — still nothing computed yet',
          'function* map(iterable, fn) {',
          '  for (const value of iterable) yield fn(value);',
          '}',
          '',
          'const pipeline = take(map(naturals(), (n) => n * n), 4);',
          'console.log("pipeline  :", "not consumed yet");',
          'console.log("squares   :", [...pipeline]);',
        ].join('\n'),
        output: [
          'first five: [1, 2, 3, 4, 5]',
          'produced  : 6',
          'pipeline  : not consumed yet',
          'squares   : [1, 4, 9, 16]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'An infinite generator is safe — spreading one is not',
        body: [
          '`produced` is `6`, not infinity: the unbounded `while (true)` ran a handful of times and then stopped, because values are produced only when requested. That is laziness, and it is what makes an infinite sequence usable at all.',
          'Why **6** rather than 5 is worth a moment. `take` pulls a value from the loop *before* it can check whether it already has enough, so it requests one more than it keeps and then returns. That one-value **overshoot** is inherent to any consumer that decides *after* looking — `takeWhile` has exactly the same property. It matters when producing a value is expensive or has a side effect.',
          'But `[...naturals()]` would **hang forever**, and so would `for (const n of naturals())` without a `break`. The generator is safe; an unbounded **consumer** is not.',
          'Always bound the consumption — with a `take`, a `break`, or a condition. Note the pipeline composed two generators and computed nothing until spread, which is exactly how lazy sequences differ from `array.map().slice()`, where `map` would process everything first.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'return, and sending values in',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A returned value is not part of the sequence.',
        code: [
          '"use strict";',
          '',
          'function* withReturn() {',
          '  yield 1;',
          '  yield 2;',
          '  return "finished";',
          '}',
          '',
          'const gen = withReturn();',
          '',
          'console.log(gen.next());',
          'console.log(gen.next());',
          'console.log(gen.next());',
          'console.log(gen.next());',
          '',
          '// for...of and spread STOP at done, so they never see it',
          'console.log("spread  :", [...withReturn()]);',
          '',
          '// .return() ends a generator early',
          'const early = withReturn();',
          'early.next();',
          'console.log("early   :", early.return("stopped"));',
          'console.log("after   :", early.next());',
        ].join('\n'),
        output: [
          '{value: 1, done: false}',
          '{value: 2, done: false}',
          '{value: "finished", done: true}',
          '{value: undefined, done: true}',
          'spread  : [1, 2]',
          'early   : {value: "stopped", done: true}',
          'after   : {value: undefined, done: true}',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'A `return` value arrives with `done: true`, and because every iterable consumer stops **at** `done`, it is invisible to `for...of`, spread and `Array.from`. Only manual `next()` calls see it — so do not use `return` to deliver a result you expect a loop to receive.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Two-way communication — `next(value)` becomes the result of `yield`.',
        code: [
          '"use strict";',
          '',
          'function* conversation() {',
          '  const name = yield "What is your name?";',
          '  const age = yield `Hello ${name}. How old are you?`;',
          '',
          '  return `${name} is ${age}`;',
          '}',
          '',
          'const chat = conversation();',
          '',
          '// The FIRST next() argument is discarded — nothing is waiting yet',
          'console.log(chat.next("ignored").value);',
          '',
          '// From now on, the argument becomes the value of the paused yield',
          'console.log(chat.next("Ada").value);',
          'console.log(chat.next(42).value);',
        ].join('\n'),
        output: [
          'What is your name?',
          'Hello Ada. How old are you?',
          'Ada is 42',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'The first `next()` argument goes nowhere',
        body: [
          'This trips up nearly everyone. `next(value)` supplies the **result of the `yield` that is currently paused** — and on the first call the body has not started, so there is no paused `yield` to receive it. The argument is silently discarded.',
          'The mental model that works: `const x = yield y` **sends `y` out** and then **waits**; the value the caller passes to the *next* `next()` becomes `x`.',
          'Two-way generators are genuinely useful for state machines and were how `async`/`await` was implemented before it was standardised. They are also easy to over-use — for ordinary work, plain functions are clearer.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Do not reach for generators by default',
        body: [
          'Most application code never needs one. `map`, `filter` and `reduce` handle ordinary collection work more readably, and an ordinary function is clearer than a generator for anything that simply returns a value.',
          'Generators earn their place for **custom iteration** (especially recursive traversal with `yield*`), **lazy or unbounded sequences**, and **state machines** — and they are worth understanding because they explain how iteration and `async` functions work underneath.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'function* g() {',
          '  console.log("A");',
          '  yield 1;',
          '  console.log("B");',
          '  yield 2;',
          '}',
          '',
          'const it = g();',
          'console.log("C");',
          'it.next();',
          'console.log("D");',
        ].join('\n'),
        options: [
          'C A D',
          'A C D',
          'C A B D',
          'A B C D',
        ],
        correct: 0,
        explanation:
          'Calling `g()` runs **none** of the body — it returns a generator object suspended before the first line — so `"C"` prints first. The first `next()` then runs the body until the first `yield`, printing `"A"` and suspending there. `"B"` never prints, because a second `next()` would be needed to resume past that `yield`. Finally `"D"` prints. This is the defining behaviour of generators: the body executes only in response to `next()`, pausing at each `yield` with all local state preserved.',
      },
    ],
    exercises: [
      {
        id: 'ex-m35-03-a',
        title: 'What does calling a generator do?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['iterators'],
        instructions:
          'What happens when you call a generator function?',
        options: [
          'The body runs to the first yield',
          'It returns a generator object with the body suspended — nothing runs until the first next()',
          'The whole body runs and the yields are collected',
          'It throws unless you use for...of',
        ],
        correct: 1,
        hints: [
          'Would a log on the first line of the body print?',
        ],
        solution: 'It returns a generator object with the body suspended — nothing runs until the first next()',
        solutionExplanation:
          'Calling the function only creates the generator object; the body is suspended **before its first line**, so even a `console.log` on line one does not run. The first `next()` executes up to the first `yield`, returns that value, and suspends again with all local state intact. This suspension is what distinguishes generators from every ordinary function and is what makes lazy and unbounded sequences possible.',
      },
      {
        id: 'ex-m35-03-b',
        title: 'Write a range generator',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['iterators'],
        instructions:
          'Write a generator `range(from, to, step = 1)` yielding values from `from` up to and including `to`.',
        starterCode: [
          'function* range(from, to, step = 1) {',
          '  // A loop and a yield.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'yields an inclusive range', body: 'expect([...range(1, 4)]).toEqual([1, 2, 3, 4]);' },
          { name: 'honours a step', body: 'expect([...range(0, 10, 5)]).toEqual([0, 5, 10]);' },
          { name: 'handles a single value', body: 'expect([...range(3, 3)]).toEqual([3]);' },
          { name: 'yields nothing for an inverted range', body: 'expect([...range(5, 1)]).toEqual([]);' },
          { name: 'works with for...of', body: 'const out = []; for (const n of range(1, 3)) out.push(n); expect(out).toEqual([1, 2, 3]);' },
          { name: 'is lazy — a fresh call each time', body: 'expect([[...range(1, 2)], [...range(1, 2)]]).toEqual([[1, 2], [1, 2]]);' },
          { name: 'stops before overshooting', body: 'expect([...range(1, 6, 2)]).toEqual([1, 3, 5]);', hidden: true },
        ],
        hints: [
          '`for (let i = from; i <= to; i += step)`',
          '`yield i` inside the loop.',
          'The loop condition handles the inverted case automatically.',
        ],
        solution: [
          'function* range(from, to, step = 1) {',
          '  for (let i = from; i <= to; i += step) {',
          '    yield i;',
          '  }',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The generator handles all the iterator bookkeeping — no `{ value, done }` objects, no position variable, no `[Symbol.iterator]`. The `i <= to` condition covers both edge cases for free: an inverted range never enters the loop, and a step that would overshoot simply ends it, which the hidden test checks. Note each **call** to `range` creates a new generator object, which is why the sixth test can spread twice — it is the same "fresh iterator per call" rule from lesson 2, obtained without effort.',
      },
      {
        id: 'ex-m35-03-c',
        title: 'Flatten a tree with yield*',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['iterators'],
        instructions:
          'Write a generator `flatten(value)` yielding every non-array value from an arbitrarily nested array, in order. Use `yield*` for recursion.',
        starterCode: [
          'function* flatten(value) {',
          '  // Arrays recurse; everything else is yielded.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'flattens one level', body: 'expect([...flatten([1, 2, 3])]).toEqual([1, 2, 3]);' },
          { name: 'flattens nesting', body: 'expect([...flatten([1, [2, [3, [4]]]])]).toEqual([1, 2, 3, 4]);' },
          { name: 'preserves order', body: 'expect([...flatten([[1, 2], 3, [4]])]).toEqual([1, 2, 3, 4]);' },
          { name: 'handles an empty array', body: 'expect([...flatten([])]).toEqual([]);' },
          { name: 'skips empty nested arrays', body: 'expect([...flatten([1, [], [2]])]).toEqual([1, 2]);' },
          { name: 'handles a non-array input', body: 'expect([...flatten(5)]).toEqual([5]);' },
          { name: 'preserves falsy values', body: 'expect([...flatten([0, [null, [false]]])]).toEqual([0, null, false]);', hidden: true },
        ],
        hints: [
          '`Array.isArray(value)` decides which branch you are in.',
          'For an array, loop and `yield* flatten(item)`.',
          'Otherwise `yield value`.',
        ],
        solution: [
          'function* flatten(value) {',
          '  if (Array.isArray(value)) {',
          '    for (const item of value) {',
          '      yield* flatten(item);',
          '    }',
          '  } else {',
          '    yield value;',
          '  }',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`yield*` is what makes this short: it delegates to the recursive call and emits every value that call produces, so the nesting unwinds without any explicit stack — a hand-written iterator would need one to remember its position in each branch. `Array.isArray` is the correct test rather than `typeof`, which reports `"object"` for arrays. Yielding the value directly, with no truthiness filtering, preserves `0`, `null` and `false`, which the hidden test checks. The empty-array cases work because the loop simply yields nothing.',
      },
      {
        id: 'ex-m35-03-d',
        title: 'Take from an infinite sequence',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['iterators'],
        instructions:
          'Write a generator `takeWhile(iterable, predicate)` yielding values while the predicate holds, then stopping. It must work on an infinite generator without hanging.',
        starterCode: [
          'function* takeWhile(iterable, predicate) {',
          '  // Stop as soon as the predicate fails.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'takes the leading run', body: 'expect([...takeWhile([1, 2, 5, 1], (n) => n < 3)]).toEqual([1, 2]);' },
          { name: 'stops at the first failure', body: 'expect([...takeWhile([5, 1], (n) => n < 3)]).toEqual([]);' },
          { name: 'takes everything when always true', body: 'expect([...takeWhile([1, 2], () => true)]).toEqual([1, 2]);' },
          { name: 'handles an empty iterable', body: 'expect([...takeWhile([], () => true)]).toEqual([]);' },
          { name: 'works on an infinite generator', body: 'function* nat() { let n = 1; while (true) yield n++; } expect([...takeWhile(nat(), (n) => n <= 4)]).toEqual([1, 2, 3, 4]);' },
          { name: 'does not over-consume', body: 'let made = 0; function* nat() { let n = 1; while (true) { made++; yield n++; } } [...takeWhile(nat(), (n) => n <= 2)]; expect(made).toBe(3);' },
          { name: 'passes the value to the predicate', body: 'const seen = []; [...takeWhile([1, 2], (n) => { seen.push(n); return true; })]; expect(seen).toEqual([1, 2]);', hidden: true },
        ],
        hints: [
          '`for (const value of iterable)` works on generators too.',
          '`if (!predicate(value)) return;` ends the generator.',
          'Otherwise `yield value`.',
        ],
        solution: [
          'function* takeWhile(iterable, predicate) {',
          '  for (const value of iterable) {',
          '    if (!predicate(value)) return;',
          '',
          '    yield value;',
          '  }',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The infinite-generator test passes because generators are **lazy**: `for...of` pulls one value at a time, and `return` ends the loop before another is requested — so the unbounded `while (true)` never runs unasked. The sixth test pins that down precisely: producing two accepted values requires **three** pulls, because the third must be produced before the predicate can reject it. That one-value overshoot is inherent to `takeWhile` and worth understanding. Using `return` rather than `break` is equivalent here, both ending the generator cleanly.',
      },
    ],
    quiz: {
      id: 'qz-m35-03',
      questions: [
        {
          id: 'q-m35-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['iterators'],
          prompt: 'What does yield do?',
          options: [
            'Returns from the function permanently',
            'Produces a value and suspends the function with its state intact',
            'Throws an error',
            'Starts a new thread',
          ],
          correct: 1,
          optionExplanations: [
            'return does that.',
            'Correct — it can be resumed by next().',
            'Nothing is thrown.',
            'Generators are single-threaded.',
          ],
          explanation:
            '`yield` emits a value and pauses the body. The next `next()` resumes exactly where it left off, with all locals preserved.',
        },
        {
          id: 'q-m35-03-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['iterators'],
          prompt: 'What does yield* do?',
          options: [
            'Yields an array',
            'Delegates to another iterable, emitting all of its values',
            'Yields twice',
            'Marks the generator as async',
          ],
          correct: 1,
          optionExplanations: [
            'It yields each value individually.',
            'Correct — and it works with any iterable.',
            'It emits as many values as the iterable has.',
            'That is async function*.',
          ],
          explanation:
            '`yield* iterable` emits every value from it as though yielded individually — which makes recursive traversal a single line.',
        },
        {
          id: 'q-m35-03-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['iterators'],
          prompt: 'for...of receives a generator\'s return value.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It arrives with done: true.',
            'Correct — consumers stop at done.',
          ],
          explanation:
            'A `return` value comes back with `done: true`, and every iterable consumer stops there — so only manual `next()` calls ever see it.',
        },
        {
          id: 'q-m35-03-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['iterators'],
          prompt: 'What happens to the argument passed to the FIRST next()?',
          options: [
            'It becomes the first yielded value',
            'It is discarded — no yield is paused yet to receive it',
            'It throws',
            'It sets the return value',
          ],
          correct: 1,
          optionExplanations: [
            'It has no such effect.',
            'Correct — the body has not started.',
            'No error occurs.',
            'return sets that.',
          ],
          explanation:
            '`next(value)` supplies the result of the **currently paused** `yield`. On the first call the body has not started, so there is nothing waiting and the argument is silently ignored.',
        },
      ],
    },
    summary:
      'Calling a generator function **runs none of its body** — it returns a generator object with execution suspended **before the first line**. Each `next()` runs to the next `yield`, emits that value, and **suspends again with all local state intact**; that resumable suspension is what no ordinary function can do. A generator object is both **iterator and iterable** (returning itself), so it works with `for...of`, spread and `Array.from` — and is therefore **consumed once**. Written as `*[Symbol.iterator]()`, a generator method gives a **fresh** generator per call, so custom iterables become repeatable for free and in a quarter of the code, with no `{ value, done }` construction and no chance of mishandling `done`. **`yield*`** delegates to any iterable, emitting all of its values, which makes **recursive traversal** a single line where a hand-written iterator would need an explicit stack. Generators are **lazy**: an unbounded `while (true)` is perfectly safe because values are produced only when requested — but an unbounded **consumer** such as `[...naturals()]` hangs forever, so always bound the consumption. A **`return`** value arrives with `done: true` and is therefore invisible to `for...of` and spread. **`next(value)`** supplies the result of the currently paused `yield`, so the argument to the **first** `next()` is silently discarded. Reach for generators for custom iteration, lazy sequences and state machines — not for ordinary collection work.',
    keyTakeaways: [
      'Calling a generator runs nothing — the body is suspended until next()',
      'yield emits a value and pauses with local state intact',
      'A generator method makes a repeatable custom iterable in a few lines',
      'yield* delegates to any iterable — recursive traversal in one line',
      'Generators are lazy: infinite sequences are safe, infinite consumers are not',
      'A return value is invisible to for...of; the first next() argument is discarded',
    ],
    relatedLessons: ['l-m35-02', 'l-m35-01'],
    interviewConnections: [
      'What happens when you call a generator function?',
      'What is the difference between yield and yield*?',
      'How can an infinite generator be safe?',
      'Why is the first next() argument ignored?',
    ],
  },
];
