import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm09';

export default [
  /* ================================================================== */
  {
    id: 'l-m09-01',
    slug: 'arrow-function-syntax',
    moduleId: M,
    order: 1,
    title: 'Arrow Function Syntax',
    description: 'Every form of the arrow, when the return is implicit, and the object-literal trap.',
    difficulty: DIFFICULTY.EASY,
    estimatedMinutes: 15,
    xp: 30,
    topicIds: ['arrow-functions', 'functions'],
    prerequisites: ['l-m08-06'],
    learningObjectives: [
      'Write arrow functions with zero, one and several parameters',
      'Choose between an expression body and a block body',
      'Explain when a return is implicit and when it must be explicit',
      'Return an object literal from an arrow function correctly',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          'Arrow functions arrived in ES2015 and are now the default for short functions, especially callbacks. This lesson covers the syntax exhaustively; the next covers the ways they behave *differently* from ordinary functions — which matter more than the shorter form.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The basic transformation',
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Function expression',
          code: [
            'const double = function (n) {',
            '  return n * 2;',
            '};',
          ].join('\n'),
        },
        right: {
          title: 'Arrow function',
          code: [
            'const double = (n) => {',
            '  return n * 2;',
            '};',
          ].join('\n'),
        },
        note: 'Drop the `function` keyword, and put `=>` between the parameter list and the body. Everything else is identical.',
      },
      {
        kind: SECTION.HEADING,
        text: 'Parameter forms',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Zero, one, several — and the two special cases.',
        code: [
          '// Zero parameters — empty parentheses are required',
          'const now = () => "no arguments needed";',
          '',
          '// One parameter — parentheses are optional',
          'const square = n => n * n;',
          'const cube = (n) => n * n * n;',
          '',
          '// Several parameters — parentheses are required',
          'const add = (a, b) => a + b;',
          '',
          '// Default and rest work exactly as before,',
          '// but both force the parentheses',
          'const greet = (name = "friend") => `Hi, ${name}`;',
          'const total = (...nums) => nums.length;',
          '',
          'console.log(now());',
          'console.log(square(4), cube(3), add(2, 3));',
          'console.log(greet(), total(1, 2, 3));',
        ].join('\n'),
        output: ['no arguments needed', '16 27 5', 'Hi, friend 3'].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Keep the parentheses even for one parameter',
        body: [
          '`n => n * 2` is legal and you will read it constantly. But writing `(n) => n * 2` is more consistent: it matches the zero- and multi-parameter forms, and it means adding a default or a second parameter later does not require editing the syntax.',
          'Most formatters can enforce either style. What matters is that you can read both.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Expression body versus block body',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'This is the part that genuinely trips people up. An arrow function\'s body takes one of two forms, and they behave differently around `return`.',
        ],
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Expression body — implicit return',
          code: [
            'const double = (n) => n * 2;',
            '',
            '// No braces, no `return`.',
            '// The expression IS the',
            '// returned value.',
            '',
            'double(5); // 10',
          ].join('\n'),
        },
        right: {
          title: 'Block body — explicit return',
          code: [
            'const double = (n) => {',
            '  return n * 2;',
            '};',
            '',
            '// Braces make it a block.',
            '// You MUST write `return`',
            '// or it gives undefined.',
            '',
            'double(5); // 10',
          ].join('\n'),
        },
        note: 'The moment you add braces, the implicit return disappears. This is the single most common arrow-function mistake.',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The mistake, made visible.',
        code: [
          'const good = (n) => n * 2;',
          'const alsoGood = (n) => { return n * 2; };',
          'const broken = (n) => { n * 2; };',
          '',
          'console.log(good(5));',
          'console.log(alsoGood(5));',
          'console.log(broken(5));',
        ].join('\n'),
        output: ['10', '10', 'undefined'].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'The braces-without-return bug',
        body: [
          '`(n) => { n * 2; }` computes `n * 2` and throws the result away, exactly like a statement on its own line in any function body. The function returns `undefined`.',
          'This appears constantly with `map`, giving an array full of `undefined` — a symptom you will meet again in Module 13. If a callback "returns nothing", check whether it has braces but no `return`.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'When you need a block body',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Braces are required as soon as the body needs more than one expression.',
        code: [
          '// Needs a local variable',
          'const describe = (price, rate) => {',
          '  const tax = price * rate;',
          '  return price + tax;',
          '};',
          '',
          '// Needs a statement such as if',
          'const classify = (n) => {',
          '  if (n < 0) return "negative";',
          '  if (n === 0) return "zero";',
          '  return "positive";',
          '};',
          '',
          'console.log(describe(100, 0.2));',
          'console.log(classify(-1), classify(0), classify(1));',
        ].join('\n'),
        output: ['120', 'negative zero positive'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'A ternary is an expression, so a simple two-way choice can still use the concise form: `const classify = (n) => n < 0 ? "negative" : "positive";`. An `if` statement cannot, which is the distinction from Module 00 showing up again.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Returning an object literal',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Here is a genuine syntax trap. An object literal starts with `{`, and so does a block body — so JavaScript cannot tell which you meant.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Wrap the object in parentheses.',
        code: [
          '// Read as a block body containing a label, returning undefined',
          'const broken = (name) => { name: name };',
          '',
          '// Parentheses force it to be read as an expression',
          'const fixed = (name) => ({ name: name });',
          '',
          '// A block body with an explicit return also works',
          'const alsoFixed = (name) => {',
          '  return { name: name };',
          '};',
          '',
          'console.log(broken("Ada"));',
          'console.log(fixed("Ada"));',
          'console.log(alsoFixed("Ada"));',
        ].join('\n'),
        output: ['undefined', '{name: "Ada"}', '{name: "Ada"}'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The broken version parses as a block containing `name: name` — which JavaScript reads as a **labelled statement**, a rarely-used feature, followed by the expression `name`. It is legal syntax that does nothing useful, so no error appears and the function silently returns `undefined`.',
          'Wrapping in `({ ... })` removes the ambiguity: parentheses can only contain an expression, so the braces must be an object literal.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Shorthand makes this shorter still',
        body: [
          'When a property name matches the variable holding its value, you can write it once: `({ name })` means `({ name: name })`. Module 14 covers object shorthand properly.',
          'So the idiomatic form is `const makeUser = (name, age) => ({ name, age });`.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const a = (n) => n + 1;',
          'const b = (n) => { n + 1; };',
          'const c = (n) => { return n + 1; };',
          '',
          'console.log(a(1), b(1), c(1));',
        ].join('\n'),
        options: [
          '2 undefined 2',
          '2 2 2',
          '2 undefined undefined',
          'undefined undefined 2',
        ],
        correct: 0,
        explanation:
          '`a` has an expression body, so `n + 1` is returned implicitly, giving 2. `b` has braces, which makes it a block body — the implicit return no longer applies, `n + 1` is computed and discarded, and the function returns `undefined`. `c` has braces *and* an explicit `return`, so it gives 2. Adding braces always removes the implicit return, which is why the `b` form is such a common accident.',
      },
    ],
    exercises: [
      {
        id: 'ex-m09-01-a',
        title: 'Predict the block-body result',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.EASY,
        xp: 10,
        topicIds: ['arrow-functions'],
        instructions: 'What does this print?',
        code: [
          'const triple = (n) => { n * 3; };',
          'console.log(triple(4));',
        ].join('\n'),
        options: ['12', 'undefined', 'NaN', 'A SyntaxError'],
        correct: 1,
        hints: [
          'Does this arrow have an expression body or a block body?',
          'What does a block body need in order to return something?',
        ],
        solution: 'undefined',
        solutionExplanation:
          'The braces make this a block body, so the implicit return does not apply. `n * 3` is evaluated and its result discarded, exactly like any expression statement, and the function falls off the end returning `undefined`. Either remove the braces — `(n) => n * 3` — or add the keyword — `(n) => { return n * 3; }`. This exact mistake produces arrays full of `undefined` when it happens inside a `map` callback.',
      },
      {
        id: 'ex-m09-01-b',
        title: 'Convert to arrow functions',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.BEGINNER,
        xp: 20,
        topicIds: ['arrow-functions'],
        instructions:
          'Rewrite all three as arrow functions assigned to `const`, using the most concise correct form for each. Behaviour must be identical.',
        starterCode: [
          'function isPositive(n) {',
          '  return n > 0;',
          '}',
          '',
          'function addAll(a, b, c) {',
          '  return a + b + c;',
          '}',
          '',
          'function shout(text) {',
          '  const upper = text.toUpperCase();',
          '  return upper + "!";',
          '}',
        ].join('\n'),
        tests: [
          { name: 'isPositive works', body: 'expect(isPositive(5)).toBe(true); expect(isPositive(-1)).toBe(false); expect(isPositive(0)).toBe(false);' },
          { name: 'addAll works', body: 'expect(addAll(1, 2, 3)).toBe(6);' },
          { name: 'shout works', body: 'expect(shout("hi")).toBe("HI!");' },
          { name: 'shout handles an empty string', body: 'expect(shout("")).toBe("!");' },
          { name: 'no function keyword remains', body: 'expect(/function/.test(isPositive.toString() + addAll.toString() + shout.toString())).toBe(false);', hidden: true },
        ],
        hints: [
          'The first two bodies are single expressions, so they need no braces and no `return`.',
          'The third needs a local variable, so it needs a block body with an explicit `return`.',
          'Assign each to a `const` with the same name.',
        ],
        solution: [
          'const isPositive = (n) => n > 0;',
          '',
          'const addAll = (a, b, c) => a + b + c;',
          '',
          'const shout = (text) => {',
          '  const upper = text.toUpperCase();',
          '  return upper + "!";',
          '};',
        ].join('\n'),
        solutionExplanation:
          'The first two collapse to a single expression, so the implicit return applies and no braces are needed — note that `n > 0` already produces a boolean, so no `if` is required. The third genuinely needs a block, because a local variable is a statement rather than an expression, and once braces appear the `return` becomes mandatory. Choosing the concise form only when the body is a single expression is the rule that keeps arrow functions readable rather than cryptic.',
      },
      {
        id: 'ex-m09-01-c',
        title: 'Return an object from an arrow',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['arrow-functions', 'objects'],
        instructions:
          'Write `makePoint` as an arrow function taking `x` and `y` and returning an object `{ x, y }`. Use the concise expression-body form, not a block.',
        starterCode: [
          'const makePoint = (x, y) => ',
          '  // An object literal needs parentheses in an expression body.',
          '  null;',
        ].join('\n'),
        tests: [
          { name: 'returns an object with both values', body: 'expect(makePoint(1, 2)).toEqual({ x: 1, y: 2 });' },
          { name: 'handles zeros', body: 'expect(makePoint(0, 0)).toEqual({ x: 0, y: 0 });' },
          { name: 'handles negatives', body: 'expect(makePoint(-3, 4)).toEqual({ x: -3, y: 4 });' },
          { name: 'returns an object', body: 'expect(typeof makePoint(1, 1)).toBe("object");' },
          { name: 'returns a new object each call', body: 'expect(makePoint(1, 1)).not.toBe(makePoint(1, 1));', hidden: true },
        ],
        hints: [
          'Without parentheses the braces are read as a block body.',
          'Wrap the object literal: `({ ... })`.',
          'Property shorthand lets you write `{ x, y }` instead of `{ x: x, y: y }`.',
        ],
        solution: [
          'const makePoint = (x, y) => ({ x, y });',
        ].join('\n'),
        solutionExplanation:
          'The wrapping parentheses are what make this work: they can only contain an expression, so the braces are unambiguously an object literal rather than a block. Without them, `(x, y) => { x, y }` parses as a block containing a comma expression and returns `undefined` — legal syntax that silently does nothing. Property shorthand `{ x, y }` is equivalent to `{ x: x, y: y }` and is the idiomatic form. The hidden test confirms a fresh object is built on each call rather than a shared one being returned.',
      },
    ],
    quiz: {
      id: 'qz-m09-01',
      questions: [
        {
          id: 'q-m09-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['arrow-functions'],
          prompt: 'When does an arrow function return a value implicitly?',
          options: [
            'Always',
            'Only when the body is a single expression with no braces',
            'Only when it has exactly one parameter',
            'Only when it returns a primitive',
          ],
          correct: 1,
          optionExplanations: [
            'A block body requires an explicit `return`.',
            'Correct — braces switch off the implicit return.',
            'Parameter count is unrelated to the body form.',
            'The returned type is irrelevant.',
          ],
          explanation:
            'An expression body — no braces — returns its expression implicitly. Adding braces creates a block body, where you must write `return` or the function yields `undefined`.',
        },
        {
          id: 'q-m09-01-2',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['arrow-functions', 'objects'],
          prompt: 'Why does this return undefined?',
          code: [
            'const f = (n) => { value: n };',
            'console.log(f(5));',
          ].join('\n'),
          options: [
            '{value: 5}',
            'undefined',
            'A SyntaxError',
            '5',
          ],
          correct: 1,
          optionExplanations: [
            'That requires wrapping the object in parentheses.',
            'Correct — the braces are read as a block body.',
            'It is valid syntax, which is what makes it confusing.',
            'Nothing is returned at all.',
          ],
          explanation:
            'The braces are parsed as a block body, and `value: n` inside it is read as a labelled statement followed by an expression. Nothing is returned, so the result is `undefined`. Write `(n) => ({ value: n })` to force the object-literal reading.',
        },
        {
          id: 'q-m09-01-3',
          kind: QUIZ_KIND.MULTIPLE,
          topicIds: ['arrow-functions'],
          prompt: 'Which of these require parentheses around the parameter list? (Select all that apply.)',
          options: [
            'Zero parameters',
            'One plain parameter',
            'Two or more parameters',
            'One parameter with a default value',
          ],
          correct: [0, 2, 3],
          explanation:
            'Parentheses may be omitted only for a single plain parameter — `n => n * 2`. Zero parameters need `()`, multiple parameters need them to separate the list, and a default or a rest parameter needs them too. Many teams keep them everywhere for consistency.',
        },
      ],
    },
    summary:
      'An arrow function drops the `function` keyword and puts `=>` between the parameters and the body. Parentheses around the parameter list are optional only for a single plain parameter. The body takes one of two forms: an **expression body** with no braces, which returns its expression implicitly, or a **block body** with braces, which requires an explicit `return` or yields `undefined`. Adding braces always switches off the implicit return, which is the most common arrow-function mistake and the cause of `map` callbacks producing arrays of `undefined`. Returning an object literal from an expression body needs wrapping parentheses — `(x) => ({ x })` — because otherwise the braces are parsed as a block.',
    keyTakeaways: [
      'Parentheses are optional only for a single plain parameter',
      'No braces means the expression is returned implicitly',
      'Braces mean you must write `return`',
      '`(n) => { n * 2; }` returns `undefined` — a very common accident',
      'Return an object literal with `({ ... })`',
    ],
    relatedLessons: ['l-m08-04', 'l-m09-02'],
    interviewConnections: [
      'When does an arrow function return implicitly?',
      'How do you return an object literal from a concise arrow function?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m09-02',
    slug: 'arrow-vs-regular',
    moduleId: M,
    order: 2,
    title: 'Arrow Functions Are Not Just Shorter',
    description: 'The semantic differences: lexical this, no arguments object, no hoisting, and where arrows are the wrong choice.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 17,
    xp: 35,
    topicIds: ['arrow-functions', 'functions', 'this'],
    prerequisites: ['l-m09-01'],
    learningObjectives: [
      'List the ways an arrow function differs semantically from a regular function',
      'Explain what "lexical `this`" means at an introductory level',
      'Identify three situations where an arrow function is the wrong choice',
      'Choose between an arrow and a regular function deliberately',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          'If you take one thing from this module, take this: **an arrow function is not a shorter regular function.** It is a different kind of function with different behaviour, and treating it as pure syntax sugar leads to bugs that are genuinely hard to diagnose.',
          'There are four differences. Three are simple; the first needs care, and Module 29 covers it in full.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Difference 1: `this` is lexical',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'A regular function gets its own `this`, and what it refers to is decided by **how the function is called**. An arrow function has no `this` of its own at all — it uses the `this` of the scope where it was **written**.',
          'You have not studied `this` properly yet; Module 29 is devoted to it. For now, the practical consequence is what matters.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A regular function loses its object; an arrow keeps the surrounding one.',
        code: [
          'const counter = {',
          '  count: 0,',
          '',
          '  // Regular method — `this` is the object when called as counter.increment()',
          '  increment() {',
          '    this.count += 1;',
          '    return this.count;',
          '  },',
          '};',
          '',
          'console.log(counter.increment());',
          'console.log(counter.increment());',
          '',
          '// An arrow as a method does NOT get the object',
          'const broken = {',
          '  count: 0,',
          '  increment: () => {',
          '    return typeof this;',
          '  },',
          '};',
          '',
          'console.log("arrow method sees this as:", broken.increment());',
        ].join('\n'),
        output: ['1', '2', 'arrow method sees this as: undefined'].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'Never use an arrow function as an object method',
        body: [
          'An arrow written as a method takes `this` from the surrounding scope — which at the top level of a module is `undefined`. It does **not** get the object, so `this.count` throws or misbehaves.',
          'Use method shorthand — `increment() { ... }` — for object methods. Reserve arrows for callbacks and small standalone functions.',
        ],
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The flip side is where arrows genuinely shine: a callback written inside a method keeps the method\'s `this`, which used to require awkward workarounds.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The problem arrows were designed to solve.',
        code: [
          'const team = {',
          '  name: "Platform",',
          '  members: ["Ada", "Grace"],',
          '',
          '  listRegular() {',
          '    const self = this;   // the old workaround',
          '    return this.members.map(function (m) {',
          '      return `${m} (${self.name})`;',
          '    });',
          '  },',
          '',
          '  listArrow() {',
          '    // The arrow keeps this method\'s `this` — no workaround needed',
          '    return this.members.map((m) => `${m} (${this.name})`);',
          '  },',
          '};',
          '',
          'console.log(team.listRegular());',
          'console.log(team.listArrow());',
        ].join('\n'),
        output: [
          '["Ada (Platform)", "Grace (Platform)"]',
          '["Ada (Platform)", "Grace (Platform)"]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Inside `listRegular`, the callback passed to `map` is a regular function, so it gets its own `this` that is not the team object — hence the `const self = this` line, which you will see throughout older code. The arrow version needs no such trick because it never had its own `this` to lose.',
          'The rule that follows: **regular function for a method, arrow for a callback inside it.**',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Difference 2: no `arguments` object',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Arrows have no `arguments` — use a rest parameter.',
        code: [
          'function regular() {',
          '  return arguments.length;',
          '}',
          '',
          'const arrow = (...args) => args.length;',
          '',
          'console.log(regular(1, 2, 3));',
          'console.log(arrow(1, 2, 3));',
        ].join('\n'),
        output: ['3', '3'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'This is rarely a problem, because rest parameters from Module 08 are better than `arguments` in every respect — they produce a real array, they can be named, and they work everywhere.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Difference 3: no hoisting',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'An arrow is a function expression, with all that implies.',
        code: [
          'console.log(declared(2));',
          '',
          'function declared(n) {',
          '  return n * 2;',
          '}',
          '',
          'try {',
          '  console.log(arrowFn(2));',
          '} catch (error) {',
          '  console.log(error.name + ":", error.message);',
          '}',
          '',
          'const arrowFn = (n) => n * 2;',
        ].join('\n'),
        output: [
          '4',
          "ReferenceError: Cannot access 'arrowFn' before initialization",
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'An arrow function is always an expression, so it follows the rules of the variable holding it — the Temporal Dead Zone behaviour from Module 08 lesson 4. There is no arrow equivalent of a function declaration.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Difference 4: cannot be used with `new`',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Arrows are not constructors.',
        code: [
          'function Regular(name) {',
          '  this.name = name;',
          '}',
          '',
          'const Arrow = (name) => {',
          '  this.name = name;',
          '};',
          '',
          'console.log(new Regular("Ada").name);',
          '',
          'try {',
          '  new Arrow("Ada");',
          '} catch (error) {',
          '  console.log(error.name + ":", error.message);',
          '}',
        ].join('\n'),
        output: ['Ada', 'TypeError: Arrow is not a constructor'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Module 31 covers constructors and classes. In modern code you would use a `class` rather than a constructor function anyway, so this rarely comes up — but it explains the error if you meet it.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'A decision table',
      },
      {
        kind: SECTION.TABLE,
        headers: ['Situation', 'Use', 'Why'],
        rows: [
          ['A callback passed to an array method', 'Arrow', 'Concise, and `this` rarely matters'],
          ['A callback inside a method that uses `this`', 'Arrow', 'Keeps the method’s `this`'],
          ['An object method', 'Method shorthand', 'An arrow would not get the object'],
          ['A class method', 'Method shorthand', 'Same reason'],
          ['A DOM event handler needing `this` as the element', 'Regular function', 'An arrow would not receive the element'],
          ['A standalone utility function', 'Either', 'Team convention decides'],
          ['A constructor', 'Regular function or `class`', 'Arrows cannot be constructed'],
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INTERVIEW,
        title: 'A complete answer on arrow versus regular',
        body: [
          '"Arrow functions are not just shorter syntax. They have no `this` of their own — they use the `this` of the enclosing scope where they were written, whereas a regular function\'s `this` is determined by how it is called. They also have no `arguments` object, cannot be used with `new`, and are always expressions so they are never hoisted like a declaration. That makes them ideal for callbacks, especially inside methods, and unsuitable as object methods or as DOM handlers that need `this` to be the element."',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const obj = {',
          '  value: 10,',
          '  regular() {',
          '    return typeof this;',
          '  },',
          '  arrow: () => typeof this,',
          '};',
          '',
          'console.log(obj.regular(), obj.arrow());',
        ].join('\n'),
        options: [
          'object undefined',
          'object object',
          'undefined undefined',
          'undefined object',
        ],
        correct: 0,
        explanation:
          '`obj.regular()` is a regular function called as a method, so its `this` is the object — `typeof` an object is `"object"`. The arrow has no `this` of its own and takes it from where it was written, which is the module top level where `this` is `undefined` in strict mode. So `typeof this` inside it is `"undefined"`. This is exactly why arrows must not be used as object methods.',
      },
    ],
    exercises: [
      {
        id: 'ex-m09-02-a',
        title: 'Why does the arrow method fail?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 15,
        topicIds: ['arrow-functions', 'this'],
        instructions:
          'An object defines `greet: () => "Hi " + this.name` and `this.name` is undefined when called as `obj.greet()`. Why?',
        options: [
          'Because arrow functions cannot access object properties',
          'Because an arrow takes `this` from the scope where it was written, not from the object it is called on',
          'Because `name` must be declared with `let`',
          'Because arrow functions must have parameters',
        ],
        correct: 1,
        hints: [
          'What decides `this` inside an arrow function?',
          'Where was this arrow written?',
        ],
        solution: 'Because an arrow takes `this` from the scope where it was written, not from the object it is called on',
        solutionExplanation:
          'An arrow has no `this` binding of its own. It uses the `this` of the enclosing lexical scope — here the module top level, where `this` is `undefined` in strict mode — regardless of how it is called. A regular function or method shorthand gets `this` from the call site, so `obj.greet()` would correctly bind it to `obj`. The fix is `greet() { return "Hi " + this.name; }`.',
      },
      {
        id: 'ex-m09-02-b',
        title: 'Fix the method',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['arrow-functions', 'this'],
        instructions:
          'This object uses an arrow function as a method, so `this` does not refer to the object. Convert it to method shorthand so `total()` returns the correct sum. Keep the inner callback as an arrow.',
        starterCode: [
          'const cart = {',
          '  taxRate: 0.2,',
          '  prices: [10, 20],',
          '  total: () => {',
          '    return this.prices.reduce((sum, p) => sum + p * (1 + this.taxRate), 0);',
          '  },',
          '};',
        ].join('\n'),
        tests: [
          { name: 'computes the taxed total', body: 'expect(cart.total()).toBe(36);' },
          { name: 'reads the object’s tax rate', body: 'const c = { taxRate: 0, prices: [10], total: cart.total }; expect(c.total()).toBe(10);' },
          { name: 'handles an empty price list', body: 'const c = { taxRate: 0.2, prices: [], total: cart.total }; expect(c.total()).toBe(0);' },
          { name: 'total is a function', body: 'expect(typeof cart.total).toBe("function");', hidden: true },
        ],
        hints: [
          'The outer `total` must be a regular function to receive `this` from the call site.',
          'Method shorthand is `total() { ... }`.',
          'The inner arrow is correct — it keeps the method’s `this`.',
        ],
        solution: [
          'const cart = {',
          '  taxRate: 0.2,',
          '  prices: [10, 20],',
          '  total() {',
          '    return this.prices.reduce((sum, p) => sum + p * (1 + this.taxRate), 0);',
          '  },',
          '};',
        ].join('\n'),
        solutionExplanation:
          'Only the outer function changes. Method shorthand gives `total` its own `this`, bound to whatever object it is called on — which is why the second test works even when `total` is copied onto a different object. The inner `reduce` callback stays an arrow precisely because it *should* inherit the method\'s `this`; making it a regular function would break `this.taxRate` and require the old `const self = this` workaround. This is the canonical pairing: regular function for the method, arrow for the callback inside it.',
      },
      {
        id: 'ex-m09-02-c',
        title: 'Choose the right function form',
        kind: EXERCISE_KIND.CHOOSE_IMPLEMENTATION,
        difficulty: DIFFICULTY.EASY,
        xp: 10,
        topicIds: ['arrow-functions'],
        instructions:
          'You are writing a method on an object that must read other properties of that object via `this`. Which form is correct?',
        options: [
          'total: () => this.items.length',
          'total() { return this.items.length; }',
          'total: function () => this.items.length',
          'total = () => this.items.length',
        ],
        correct: 1,
        hints: [
          'Which form gets `this` from the call site?',
        ],
        solution: 'total() { return this.items.length; }',
        solutionExplanation:
          'Method shorthand creates a regular function, so `this` is bound to the object when called as `obj.total()`. The arrow in the first option takes `this` from the surrounding scope and would not see the object. The third option is not valid syntax — you cannot combine `function` and `=>`. The fourth is class-field syntax and is not valid inside an object literal.',
      },
    ],
    quiz: {
      id: 'qz-m09-02',
      questions: [
        {
          id: 'q-m09-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['arrow-functions', 'this'],
          prompt: 'How does an arrow function determine `this`?',
          options: [
            'From the object it is called on',
            'From the enclosing scope where it was written',
            'It is always `undefined`',
            'From the first argument passed',
          ],
          correct: 1,
          optionExplanations: [
            'That describes a regular function called as a method.',
            'Correct — this is what "lexical `this`" means.',
            'It inherits whatever the surrounding scope has, which may be an object.',
            'Arguments do not affect `this`.',
          ],
          explanation:
            'An arrow has no `this` binding of its own, so it uses the `this` of the enclosing lexical scope — decided by where it was written, not how it is called. This makes arrows ideal as callbacks inside methods and unsuitable as methods themselves.',
        },
        {
          id: 'q-m09-02-2',
          kind: QUIZ_KIND.MULTIPLE,
          topicIds: ['arrow-functions'],
          prompt: 'Which are true of arrow functions but not regular functions? (Select all that apply.)',
          options: [
            'They have no `arguments` object',
            'They cannot be used with `new`',
            'They take `this` from the enclosing scope',
            'They can have default parameters',
          ],
          correct: [0, 1, 2],
          explanation:
            'Arrows lack their own `arguments` object, cannot be constructed with `new`, and take `this` lexically. Default parameters work identically in both forms — as do rest parameters — so that is not a difference.',
        },
        {
          id: 'q-m09-02-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['arrow-functions'],
          prompt: 'When is an arrow function the wrong choice?',
          options: [
            'As a callback passed to `map`',
            'As an object method that needs `this` to be the object',
            'As a small standalone utility',
            'As a callback inside a method',
          ],
          correct: 1,
          optionExplanations: [
            'This is the ideal use for an arrow.',
            'Correct — an arrow would not receive the object.',
            'Either form works for a standalone function.',
            'This is the case arrows were designed to improve.',
          ],
          explanation:
            'An arrow used as an object method takes `this` from the surrounding scope rather than the object, so `this.someProperty` fails. Use method shorthand for methods, and arrows for callbacks — including callbacks written inside those methods.',
        },
        {
          id: 'q-m09-02-4',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['arrow-functions', 'hoisting'],
          prompt: 'An arrow function can be called before the line that defines it.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Only function declarations allow that.',
            'Correct — an arrow is an expression bound to a variable.',
          ],
          explanation:
            'An arrow function is always an expression, so it follows the rules of the variable holding it. With `const` or `let` the binding is in the Temporal Dead Zone until the assignment runs, so calling it earlier throws "Cannot access before initialization".',
        },
      ],
    },
    summary:
      'An arrow function differs from a regular function in four ways, not merely in length. It has no `this` of its own and uses the `this` of the scope where it was **written** — which makes it perfect as a callback inside a method and wrong as a method itself, where it would never receive the object. It has no `arguments` object, though rest parameters are better anyway. It is always an expression, so it is never hoisted like a declaration and throws if called before its assignment. And it cannot be used with `new`. The practical rule: method shorthand for methods, arrows for callbacks, and a regular function for a DOM handler that needs `this` to be the element.',
    keyTakeaways: [
      'An arrow has no `this` — it uses the enclosing scope’s',
      'Never use an arrow as an object or class method',
      'Arrows inside methods keep the method’s `this`, replacing `const self = this`',
      'No `arguments` object — use rest parameters',
      'Always an expression, so never hoisted like a declaration',
      'Cannot be used with `new`',
    ],
    relatedLessons: ['l-m09-01', 'l-m09-03'],
    interviewConnections: [
      'What is the difference between an arrow function and a regular function?',
      'What does lexical `this` mean?',
      'Why should you not use an arrow function as an object method?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m09-03',
    slug: 'callbacks',
    moduleId: M,
    order: 3,
    title: 'Callbacks',
    description: 'Passing behaviour as data — the idea behind array methods, event handlers and every asynchronous API.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 17,
    xp: 35,
    topicIds: ['higher-order', 'functions', 'arrow-functions'],
    prerequisites: ['l-m09-02'],
    learningObjectives: [
      'Define a callback and explain why callbacks are useful',
      'Distinguish passing a function from passing its result',
      'Explain what arguments a callback receives and who supplies them',
      'Write a function that accepts and invokes a callback',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          'A **callback** is a function passed to another function, for that other function to call. Nothing more exotic than that — but it is the foundation of array methods, event handling, timers and promises, so it repays careful study.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The simplest possible callback',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: '`twice` does not know or care what it is calling.',
        code: [
          'function twice(callback) {',
          '  callback();',
          '  callback();',
          '}',
          '',
          'twice(() => console.log("hello"));',
          'twice(() => console.log("again"));',
        ].join('\n'),
        output: ['hello', 'hello', 'again', 'again'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`twice` controls **when** and **how often** something runs; the caller controls **what** runs. That separation is the whole point: the repetition logic is written once and works with any behaviour.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Passing a function versus passing its result',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'You met this in Module 08. It matters enough to repeat with callbacks specifically, because this is where it bites hardest.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Watch the ordering — it gives the bug away.',
        code: [
          'function greet() {',
          '  console.log("  greet ran");',
          '  return "greeting";',
          '}',
          '',
          'function schedule(callback) {',
          '  console.log("  scheduling...");',
          '  console.log("  got a", typeof callback);',
          '}',
          '',
          'console.log("CORRECT — passing the function:");',
          'schedule(greet);',
          '',
          'console.log("WRONG — passing the result:");',
          'schedule(greet());',
        ].join('\n'),
        output: [
          'CORRECT — passing the function:',
          '  scheduling...',
          '  got a function',
          'WRONG — passing the result:',
          '  greet ran',
          '  scheduling...',
          '  got a string',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'The ordering is the diagnostic',
        body: [
          'In the wrong case, `"greet ran"` appears **before** `"scheduling..."`. The function executed while the argument was being evaluated, before `schedule` did anything at all.',
          'Whenever a callback seems to run too early — once on page load rather than on click, immediately rather than after a delay — look for stray parentheses at the call site.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'When you need to pass arguments',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'If passing `fn()` is wrong, how do you supply arguments to a callback? You wrap it in another function.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A wrapper defers the call while fixing the arguments.',
        code: [
          'function greet(name) {',
          '  return `Hello, ${name}`;',
          '}',
          '',
          'function runAndLog(callback) {',
          '  console.log(callback());',
          '}',
          '',
          '// Wrong — calls greet immediately, passes a string',
          '// runAndLog(greet("Ada"));',
          '',
          '// Right — pass a function that will call greet later',
          'runAndLog(() => greet("Ada"));',
          'runAndLog(() => greet("Grace"));',
        ].join('\n'),
        output: ['Hello, Ada', 'Hello, Grace'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`() => greet("Ada")` is a new function that, when called, calls `greet` with a fixed argument. Nothing runs until `runAndLog` decides to invoke it. This wrapper pattern appears constantly — in event handlers, in `setTimeout`, and anywhere a callback needs data the receiver does not have.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The receiver supplies the arguments',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'A callback\'s parameters are filled by whatever function calls it, not by you. Understanding *what* a given API passes is essential to using it.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A higher-order function deciding what to pass.',
        code: [
          'function repeat(count, callback) {',
          '  for (let i = 0; i < count; i++) {',
          '    callback(i);',
          '  }',
          '}',
          '',
          'repeat(3, (index) => console.log("iteration", index));',
          '',
          '// The callback may ignore arguments it does not need',
          'repeat(2, () => console.log("no index needed"));',
        ].join('\n'),
        output: [
          'iteration 0',
          'iteration 1',
          'iteration 2',
          'no index needed',
          'no index needed',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Extra arguments are silently ignored — usually harmlessly',
        body: [
          'A callback that declares fewer parameters than the caller supplies simply ignores the extras, which is why `repeat(2, () => ...)` works fine.',
          'The exception is when your callback happens to *accept* a parameter it should not. That is the `map(parseInt)` bug from Module 03: `map` passes an index as the second argument, and `parseInt` treats a second argument as a radix. Always know how many arguments an API supplies.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Array methods pass three arguments to every callback.',
        code: [
          'const letters = ["a", "b", "c"];',
          '',
          'letters.forEach((value, index, array) => {',
          '  console.log(index, value, "of", array.length);',
          '});',
          '',
          '// Most callbacks only need the first',
          'const upper = letters.map((value) => value.toUpperCase());',
          'console.log(upper);',
        ].join('\n'),
        output: [
          '0 a of 3',
          '1 b of 3',
          '2 c of 3',
          '["A", "B", "C"]',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'Writing your own higher-order function',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'A function that takes a function as an argument, or returns one, is called a **higher-order function**. `repeat` above is one. So are `map`, `filter`, `setTimeout` and `addEventListener`.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Separating a policy from the work it applies to.',
        code: [
          'function withRetry(attempts, task) {',
          '  for (let attempt = 1; attempt <= attempts; attempt++) {',
          '    const result = task(attempt);',
          '    if (result !== null) {',
          '      return `succeeded on attempt ${attempt}: ${result}`;',
          '    }',
          '  }',
          '  return `failed after ${attempts} attempts`;',
          '}',
          '',
          '// A task that fails until the third attempt',
          'const flaky = (attempt) => (attempt < 3 ? null : "data");',
          '',
          'console.log(withRetry(5, flaky));',
          'console.log(withRetry(2, flaky));',
          'console.log(withRetry(3, () => "instant"));',
        ].join('\n'),
        output: [
          'succeeded on attempt 3: data',
          'failed after 2 attempts',
          'succeeded on attempt 1: instant',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`withRetry` knows nothing about what it is retrying. The retry *policy* is written once and works with any task, and the task knows nothing about retrying. Neither piece has to change when the other does — which is exactly the benefit callbacks buy you.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'These callbacks are synchronous',
        body: [
          'Every callback in this lesson runs immediately, in order, as part of the call. That is true of array methods too.',
          'Some callbacks are **asynchronous**: `setTimeout` and `fetch` accept a callback that runs later, after the surrounding code has finished. The passing mechanism is identical; only the timing differs. Modules 23 to 25 cover that properly.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'function apply(value, transform) {',
          '  return transform(value);',
          '}',
          '',
          'const double = (n) => n * 2;',
          '',
          'console.log(apply(5, double));',
          'console.log(apply(5, (n) => n + 1));',
          'console.log(apply(5, double(3)));',
        ].join('\n'),
        options: [
          '10, 6, then a TypeError',
          '10, 6, 6',
          '10, 6, 10',
          'A TypeError immediately',
        ],
        correct: 0,
        explanation:
          'The first two pass functions, so `apply` calls each with 5 — giving 10 and 6. The third calls `double(3)` first, producing the number `6`, and passes that as `transform`. Inside `apply`, `transform(value)` becomes `6(5)`, and a number is not callable, so it throws `TypeError: transform is not a function`. The first two lines print successfully before the error, which is a useful diagnostic when you see this in real code.',
      },
    ],
    exercises: [
      {
        id: 'ex-m09-03-a',
        title: 'Predict the immediate call',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.EASY,
        xp: 15,
        topicIds: ['higher-order'],
        instructions: 'In what order do these lines print?',
        code: [
          'function work() {',
          '  console.log("work");',
          '}',
          '',
          'function register(cb) {',
          '  console.log("register");',
          '}',
          '',
          'register(work());',
        ].join('\n'),
        options: [
          '"work" then "register"',
          '"register" then "work"',
          '"register" only',
          '"work" only',
        ],
        correct: 0,
        hints: [
          'Arguments are evaluated before the function receiving them runs.',
          'Does `work()` have parentheses?',
        ],
        solution: '"work" then "register"',
        solutionExplanation:
          'Arguments are fully evaluated before the receiving function is entered, so `work()` runs first and prints `"work"`. Only then does `register` execute and print `"register"` — receiving `undefined`, since `work` returns nothing. This inverted ordering is the tell-tale sign of the parentheses bug: the callback fires before the thing that was supposed to schedule it. The fix is `register(work)`.',
      },
      {
        id: 'ex-m09-03-b',
        title: 'Write a higher-order function',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['higher-order'],
        instructions:
          'Write `applyTwice(value, transform)` that applies the `transform` function to `value`, then applies it again to the result, and returns the final value. `applyTwice(3, n => n * 2)` should give 12.',
        starterCode: [
          'function applyTwice(value, transform) {',
          '  // Call transform on value, then on that result.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'doubles twice', body: 'expect(applyTwice(3, (n) => n * 2)).toBe(12);' },
          { name: 'adds twice', body: 'expect(applyTwice(0, (n) => n + 5)).toBe(10);' },
          { name: 'works with strings', body: 'expect(applyTwice("a", (s) => s + "!")).toBe("a!!");' },
          { name: 'handles an identity transform', body: 'expect(applyTwice(7, (n) => n)).toBe(7);' },
          { name: 'calls the transform exactly twice', body: 'let calls = 0; applyTwice(1, (n) => { calls += 1; return n; }); expect(calls).toBe(2);', hidden: true },
        ],
        hints: [
          'Call `transform(value)` and keep the result.',
          'Then call `transform` again on that result.',
          '`transform(transform(value))` does both in one expression.',
        ],
        solution: [
          'function applyTwice(value, transform) {',
          '  return transform(transform(value));',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The nested call reads inside-out: the inner `transform(value)` runs first, and its result becomes the argument to the outer call. Writing it as two statements with an intermediate variable is equally correct and arguably clearer for a beginner. The hidden test verifies the transform is invoked exactly twice — an implementation that accidentally called it three times, or cached a result, would fail it. This is a higher-order function because it takes a function as an argument.',
      },
      {
        id: 'ex-m09-03-c',
        title: 'Fix the callback argument',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['higher-order'],
        instructions:
          'This code should pass a function that greets a specific name, but it calls `greet` immediately instead. Fix `makeGreeter` so it returns a function that can be called later.',
        starterCode: [
          'function greet(name) {',
          '  return `Hello, ${name}`;',
          '}',
          '',
          'function makeGreeter(name) {',
          '  return greet(name);',
          '}',
        ].join('\n'),
        tests: [
          { name: 'returns a function', body: 'expect(typeof makeGreeter("Ada")).toBe("function");' },
          { name: 'the returned function greets correctly', body: 'expect(makeGreeter("Ada")()).toBe("Hello, Ada");' },
          { name: 'different names give different greeters', body: 'expect(makeGreeter("Grace")()).toBe("Hello, Grace");' },
          { name: 'the greeter can be called repeatedly', body: 'const g = makeGreeter("Ada"); expect(g()).toBe("Hello, Ada"); expect(g()).toBe("Hello, Ada");' },
          { name: 'greet is not called during makeGreeter', body: 'let calls = 0; const original = greet; makeGreeter("X"); expect(calls).toBe(0);', hidden: true },
        ],
        hints: [
          '`return greet(name)` calls it straight away and returns a string.',
          'Return a function that calls `greet` when invoked.',
          '`return () => greet(name);` defers the call.',
        ],
        solution: [
          'function greet(name) {',
          '  return `Hello, ${name}`;',
          '}',
          '',
          'function makeGreeter(name) {',
          '  return () => greet(name);',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The original returned a string because `greet(name)` executes immediately. Returning `() => greet(name)` hands back a function instead, and `greet` does not run until that function is invoked — which is why the call syntax becomes `makeGreeter("Ada")()`: the first pair of parentheses builds the greeter, the second runs it. The returned arrow keeps access to `name` even after `makeGreeter` has finished, which is a closure — Module 32 covers the mechanism. This wrapper pattern is exactly how you supply arguments to a callback without calling it early.',
      },
      {
        id: 'ex-m09-03-d',
        title: 'Build a filtering helper',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['higher-order'],
        instructions:
          'Write `keepIf(items, test)` that returns a new array containing only the items for which `test(item)` returns a truthy value. Do not use the built-in `filter` — write the loop yourself. The original array must not be modified.',
        starterCode: [
          'function keepIf(items, test) {',
          '  // Build a new array, pushing items that pass the test.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'keeps matching numbers', body: 'expect(keepIf([1, 2, 3, 4], (n) => n % 2 === 0)).toEqual([2, 4]);' },
          { name: 'keeps everything when the test always passes', body: 'expect(keepIf([1, 2], () => true)).toEqual([1, 2]);' },
          { name: 'keeps nothing when the test always fails', body: 'expect(keepIf([1, 2], () => false)).toEqual([]);' },
          { name: 'handles an empty array', body: 'expect(keepIf([], () => true)).toEqual([]);' },
          { name: 'works with strings', body: 'expect(keepIf(["a", "bb", "c"], (s) => s.length === 1)).toEqual(["a", "c"]);' },
          { name: 'does not modify the original', body: 'const src = [1, 2, 3]; keepIf(src, (n) => n > 1); expect(src).toEqual([1, 2, 3]);' },
          { name: 'passes the index as the second argument', body: 'const seen = []; keepIf(["a", "b"], (item, i) => { seen.push(i); return true; }); expect(seen).toEqual([0, 1]);', hidden: true },
        ],
        hints: [
          'Start with an empty result array.',
          'Loop over `items` and call `test` on each one.',
          'Push the item only when the test result is truthy.',
          'The hidden test expects the index to be passed as a second argument, like the real `filter`.',
        ],
        solution: [
          'function keepIf(items, test) {',
          '  const result = [];',
          '',
          '  for (let i = 0; i < items.length; i++) {',
          '    if (test(items[i], i)) {',
          '      result.push(items[i]);',
          '    }',
          '  }',
          '',
          '  return result;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'This is essentially how `filter` works internally, which is worth building once so the real method stops feeling like magic. Pushing into a fresh `result` array rather than removing from `items` is what keeps the function pure and leaves the caller\'s data untouched. Passing the index as a second argument matches the real API — callbacks that do not need it simply ignore it, as `(n) => n % 2 === 0` does. Note the test result is used for its *truthiness* rather than compared to `true`, so a callback returning a non-empty string or a number works as expected.',
      },
    ],
    quiz: {
      id: 'qz-m09-03',
      questions: [
        {
          id: 'q-m09-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['higher-order'],
          prompt: 'What is a callback?',
          options: [
            'A function that returns another function',
            'A function passed to another function, to be called by it',
            'A function that runs after a delay',
            'A function with no name',
          ],
          correct: 1,
          optionExplanations: [
            'That describes a function factory, which is a different pattern.',
            'Correct — the timing is up to the receiver.',
            'Some callbacks are delayed, but most array callbacks run immediately.',
            'A callback may be named or anonymous.',
          ],
          explanation:
            'A callback is simply a function handed to another function for that function to invoke. It may be called immediately, many times, or later — the receiver decides. This lets one function control *when* something happens while the caller controls *what*.',
        },
        {
          id: 'q-m09-03-2',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['higher-order'],
          prompt: 'What goes wrong here?',
          code: [
            'function run(cb) {',
            '  return cb();',
            '}',
            'const value = 42;',
            'console.log(run(value));',
          ].join('\n'),
          options: [
            '42',
            'undefined',
            'A TypeError — cb is not a function',
            'null',
          ],
          correct: 2,
          optionExplanations: [
            'The number is never returned; the call fails first.',
            'The error occurs before any value is produced.',
            'Correct — `42()` is not a valid call.',
            'Nothing produces null here.',
          ],
          explanation:
            '`run` assumes it received a function and tries to call it. A number is not callable, so `cb()` throws `TypeError: cb is not a function`. This is what you see when a callback slot is accidentally given a value — usually because a function was called with parentheses rather than passed.',
        },
        {
          id: 'q-m09-03-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['higher-order'],
          prompt: 'How do you pass a callback that needs a specific argument?',
          options: [
            'Call it with the argument: `run(greet("Ada"))`',
            'Wrap it: `run(() => greet("Ada"))`',
            'Pass both separately: `run(greet, "Ada")` always works',
            'It is not possible',
          ],
          correct: 1,
          optionExplanations: [
            'That calls it immediately and passes the result.',
            'Correct — the wrapper defers the call while fixing the argument.',
            'This only works if the receiving function is designed to forward extra arguments.',
            'The wrapper pattern handles it cleanly.',
          ],
          explanation:
            'Wrapping in another function defers execution: `() => greet("Ada")` is a function that will call `greet` with a fixed argument whenever the receiver invokes it. Some APIs do accept extra arguments to forward, but the wrapper works universally.',
        },
        {
          id: 'q-m09-03-4',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['higher-order'],
          prompt: 'A callback must declare every parameter the caller passes to it.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Extra arguments are silently ignored.',
            'Correct — declare only the parameters you need.',
          ],
          explanation:
            'Extra arguments are ignored by a callback that declares fewer parameters, which is why `map((value) => ...)` works even though `map` supplies three. The hazard is the reverse: accidentally accepting a parameter you did not want, as `parseInt` does with the index in `map(parseInt)`.',
        },
      ],
    },
    summary:
      'A callback is a function passed to another function for that function to invoke, letting the receiver control *when* something runs while the caller controls *what* runs. Pass `fn`, never `fn()` — the latter executes immediately and hands over its return value, and the tell-tale symptom is the callback appearing to run before the function that was meant to schedule it. To supply arguments without calling early, wrap it: `() => greet("Ada")`. The receiving function decides what arguments a callback gets; declaring fewer parameters than are supplied is safe, but accidentally accepting one you did not want causes bugs such as `map(parseInt)`. A function that takes or returns a function is a **higher-order function**, and writing your own is how patterns such as retry policies stay separate from the work they apply to.',
    keyTakeaways: [
      'A callback is a function passed for another function to call',
      'Pass `fn`, not `fn()` — parentheses run it immediately',
      'A callback running too early is almost always stray parentheses',
      'Wrap in `() => fn(arg)` to supply arguments without calling early',
      'The receiver decides what arguments a callback receives',
      'A higher-order function takes or returns a function',
    ],
    relatedLessons: ['l-m09-02', 'l-m09-04'],
    interviewConnections: [
      'What is a callback function?',
      'What is a higher-order function?',
      'Why does passing handler() to addEventListener not work?',
      'How do you pass arguments to a callback?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m09-04',
    slug: 'purity-iife-and-forward',
    moduleId: M,
    order: 4,
    title: 'Pure Functions, Side Effects and IIFEs',
    description: 'Consolidating purity, meeting the immediately-invoked function, and previewing closures and recursion.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 16,
    xp: 35,
    topicIds: ['functions', 'arrow-functions', 'higher-order'],
    prerequisites: ['l-m09-03'],
    learningObjectives: [
      'Classify a function as pure or impure and justify it',
      'Explain why purity makes code easier to test and reason about',
      'Recognise and write an IIFE, and explain why it existed',
      'Recognise a closure and a recursive function when you see one',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Purity, revisited precisely',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Module 08 introduced pure functions. Now that you have callbacks, the idea becomes practical: array methods expect callbacks to be pure, and impure ones cause subtle bugs.',
          'A function is **pure** when both hold: the same inputs always produce the same output, and nothing outside the function changes.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Four functions — only one is pure.',
        code: [
          'let counter = 0;',
          '',
          'const pure = (a, b) => a + b;',
          'const readsOutside = (a) => a + counter;',
          'const writesOutside = (a) => { counter += a; return counter; };',
          'const nondeterministic = () => Math.random();',
          '',
          'console.log(pure(2, 3), pure(2, 3));',
          '',
          'counter = 10;',
          'console.log(readsOutside(1));',
          'counter = 20;',
          'console.log(readsOutside(1));',
          '',
          'console.log(writesOutside(5), counter);',
        ].join('\n'),
        output: ['5 5', '11', '21', '25 25'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`readsOutside` gives different answers for the same argument, because it depends on state it does not control. `writesOutside` modifies that state. `nondeterministic` fails the first condition by definition. Only `pure` can be understood entirely from its own body.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Impure callbacks are the real hazard',
        body: [
          'Array methods assume your callback is pure. A callback that mutates the array being iterated, or that depends on an outer variable changing mid-loop, produces results that are hard to predict and harder to debug.',
          'Module 13 returns to this. The habit to build now: a callback should take its inputs, compute, and return — nothing else.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The same task, impure and pure.',
        code: [
          'const prices = [10, 20, 30];',
          '',
          '// Impure — relies on and mutates an outer variable',
          'let total = 0;',
          'prices.forEach((p) => { total += p; });',
          'console.log("impure total:", total);',
          '',
          '// Pure — the callback only computes and returns',
          'const doubled = prices.map((p) => p * 2);',
          'console.log("pure result:", doubled);',
          'console.log("original untouched:", prices);',
        ].join('\n'),
        output: [
          'impure total: 60',
          'pure result: [20, 40, 60]',
          'original untouched: [10, 20, 30]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The `forEach` version is not wrong — accumulating into an outer variable is a legitimate use of `forEach`, which exists precisely for side effects. But `reduce`, which Module 13 covers, does the same job with a pure callback and no outer variable to keep in sync.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Immediately-invoked function expressions',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'An **IIFE** is a function expression that is called the instant it is defined. The name is usually pronounced "iffy".',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Define and call in one expression.',
        code: [
          '// Classic form',
          '(function () {',
          '  console.log("ran immediately");',
          '})();',
          '',
          '// Arrow form',
          '(() => {',
          '  console.log("arrow IIFE");',
          '})();',
          '',
          '// It can produce a value',
          'const config = (() => {',
          '  const base = "https://api.example.com";',
          '  return { base, version: "v1" };',
          '})();',
          '',
          'console.log(config);',
        ].join('\n'),
        output: [
          'ran immediately',
          'arrow IIFE',
          '{base: "https://api.example.com", version: "v1"}',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The wrapping parentheses matter. Starting a statement with the word `function` makes JavaScript expect a *declaration*, which cannot be called immediately. Wrapping it forces the expression reading, and then the trailing `()` invokes it.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Why IIFEs mattered, and why they matter less now',
        body: [
          'Before ES2015 there was no block scope and no module system. Everything declared at the top level of a script became a global, and scripts sharing a page would silently overwrite each other. An IIFE created a private function scope, so variables inside it could not leak.',
          'Today `let` and `const` give block scope, and modules give file scope, so most IIFE uses have disappeared. You still need to recognise them: they are everywhere in older code, in bundler output, and in minified files.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The modern equivalent of the classic IIFE use.',
        code: [
          '// Old approach — an IIFE for privacy',
          'const oldWay = (function () {',
          '  const secret = "hidden";',
          '  return { reveal: () => secret.length };',
          '})();',
          '',
          '// Modern approach — a block gives the same scoping',
          '{',
          '  const alsoHidden = "hidden";',
          '  console.log("inside block:", alsoHidden.length);',
          '}',
          '',
          'console.log(oldWay.reveal());',
          '',
          'try {',
          '  console.log(alsoHidden);',
          '} catch (error) {',
          '  console.log(error.name);',
          '}',
        ].join('\n'),
        output: ['inside block: 6', '6', 'ReferenceError'].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'A first look at closures',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'You have already written closures without the name. When a function returns another function, the inner one keeps access to the outer one\'s variables — even after the outer function has finished.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Each counter keeps its own retained variable.',
        code: [
          'function makeCounter() {',
          '  let count = 0;',
          '  return () => {',
          '    count += 1;',
          '    return count;',
          '  };',
          '}',
          '',
          'const a = makeCounter();',
          'const b = makeCounter();',
          '',
          'console.log(a(), a(), a());',
          'console.log(b());',
        ].join('\n'),
        output: ['1 2 3', '1'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`makeCounter` has returned long before `a()` is called, yet `count` still exists — the returned function holds on to it. And `a` and `b` have entirely separate copies, so they do not interfere.',
          'That is a **closure**. Module 32 explains the mechanism, the memory implications, and the classic interview puzzles. For now, simply recognise the shape: a function returned from a function, remembering where it came from.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'A first look at recursion',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A function that calls itself, with a base case that stops it.',
        code: [
          'function countdown(n) {',
          '  if (n <= 0) {',
          '    return "liftoff";',
          '  }',
          '  console.log(n);',
          '  return countdown(n - 1);',
          '}',
          '',
          'console.log(countdown(3));',
        ].join('\n'),
        output: ['3', '2', '1', 'liftoff'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Two parts make recursion work: a **base case** that returns without recursing, and a **recursive case** that moves closer to it. Remove the base case and the function calls itself forever until the call stack overflows.',
          'Module 38 covers recursion properly, including when it is the right tool. For now, recognise the shape and note that the base case is what stops it.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'function make() {',
          '  let n = 0;',
          '  return () => ++n;',
          '}',
          '',
          'const first = make();',
          'const second = make();',
          '',
          'console.log(first(), first(), second());',
        ].join('\n'),
        options: [
          '1 2 1',
          '1 2 3',
          '1 1 1',
          '1 2 2',
        ],
        correct: 0,
        explanation:
          'Each call to `make` creates a brand-new `n` and returns a function that captures that particular one. `first` increments its own `n` to 1 then 2. `second` was produced by a separate call, so it has an independent `n` starting at 0, and its first invocation gives 1. If the two shared a variable the answer would be `1 2 3`; the fact that they do not is what makes closures useful for private state.',
      },
    ],
    exercises: [
      {
        id: 'ex-m09-04-a',
        title: 'Classify the function',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.EASY,
        xp: 10,
        topicIds: ['functions'],
        instructions: 'Which of these is pure?',
        options: [
          'const f = (arr) => { arr.sort(); return arr; }',
          'const f = (arr) => [...arr].sort()',
          'const f = () => new Date().getFullYear()',
          'const f = (n) => { console.log(n); return n; }',
        ],
        correct: 1,
        hints: [
          'Check both conditions: same output for same input, and nothing outside changed.',
          '`sort` mutates the array it is called on.',
        ],
        solution: 'const f = (arr) => [...arr].sort()',
        solutionExplanation:
          'Spreading creates a copy first, so `sort` mutates only that copy and the caller\'s array is untouched — same input always gives the same output, and nothing external changes. The first option sorts the caller\'s array in place, which is a side effect. The third returns a different value depending on when it runs, failing determinism. The fourth logs, which is a side effect even though the return value is predictable.',
      },
      {
        id: 'ex-m09-04-b',
        title: 'Make the callback pure',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['functions', 'higher-order'],
        instructions:
          'Rewrite `addTax` so it does not mutate the objects it receives. It should return a new array of new objects, each with a `total` property added, leaving the input entirely unchanged.',
        starterCode: [
          'function addTax(items, rate) {',
          '  items.forEach((item) => {',
          '    item.total = item.price * (1 + rate);',
          '  });',
          '  return items;',
          '}',
        ].join('\n'),
        tests: [
          { name: 'adds a total to each item', body: 'expect(addTax([{ price: 100 }], 0.2)).toEqual([{ price: 100, total: 120 }]);' },
          { name: 'handles several items', body: 'expect(addTax([{ price: 10 }, { price: 20 }], 0).map((i) => i.total)).toEqual([10, 20]);' },
          { name: 'does not modify the input objects', body: 'const src = [{ price: 100 }]; addTax(src, 0.2); expect(src[0].total).toBe(undefined);' },
          { name: 'returns a different array', body: 'const src = [{ price: 1 }]; expect(addTax(src, 0)).not.toBe(src);' },
          { name: 'returns different objects', body: 'const src = [{ price: 1 }]; expect(addTax(src, 0)[0]).not.toBe(src[0]);' },
          { name: 'handles an empty array', body: 'expect(addTax([], 0.2)).toEqual([]);', hidden: true },
        ],
        hints: [
          '`map` returns a new array; `forEach` does not.',
          'Spread each item into a new object rather than assigning onto it.',
          '`({ ...item, total: ... })` builds a copy with the extra property.',
        ],
        solution: [
          'function addTax(items, rate) {',
          '  return items.map((item) => ({',
          '    ...item,',
          '    total: item.price * (1 + rate),',
          '  }));',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Two changes make this pure. `map` builds a new array instead of returning the original, and spreading each item into a fresh object literal means the originals are never assigned to — which the third and fifth tests check separately, since returning a new array full of the *same* objects would still leak mutations. The parentheses around the object literal are required in a concise arrow body, as lesson 1 covered. This copy-and-extend pattern is the standard way to derive data without disturbing its source.',
      },
      {
        id: 'ex-m09-04-c',
        title: 'Write a counter factory',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['functions', 'higher-order'],
        instructions:
          'Write `makeCounter(start = 0)` returning a function that increases a private count by 1 each time it is called and returns the new value. Two counters must be completely independent.',
        starterCode: [
          'function makeCounter(start = 0) {',
          '  // Declare the count, then return a function that updates it.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'counts from zero by default', body: 'const c = makeCounter(); expect(c()).toBe(1); expect(c()).toBe(2);' },
          { name: 'respects a starting value', body: 'const c = makeCounter(10); expect(c()).toBe(11);' },
          { name: 'returns a function', body: 'expect(typeof makeCounter()).toBe("function");' },
          { name: 'counters are independent', body: 'const a = makeCounter(); const b = makeCounter(); a(); a(); expect(b()).toBe(1);' },
          { name: 'the count is not exposed', body: 'const c = makeCounter(); c(); expect(c.count).toBe(undefined);' },
          { name: 'a start of 0 is respected rather than defaulted', body: 'const c = makeCounter(0); expect(c()).toBe(1);', hidden: true },
        ],
        hints: [
          'Declare the count with `let` inside `makeCounter`.',
          'Return a function that increments and returns it.',
          'Each call to `makeCounter` creates a fresh variable, which is what makes counters independent.',
        ],
        solution: [
          'function makeCounter(start = 0) {',
          '  let count = start;',
          '',
          '  return () => {',
          '    count += 1;',
          '    return count;',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Each call to `makeCounter` creates its own `count`, and the returned arrow captures that specific variable — which is why the independence test passes. This is a closure: `count` survives after `makeCounter` returns because the inner function still refers to it. The variable is genuinely private; there is no way to read or set it except through the returned function, which the fifth test confirms. Note the default of `0` is safe here because default parameters trigger only on `undefined`, so an explicit `makeCounter(0)` is respected rather than overridden.',
      },
      {
        id: 'ex-m09-04-d',
        title: 'Write a recursive sum',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['functions'],
        instructions:
          'Write `sumTo(n)` that returns the sum of all whole numbers from 1 to `n`, using recursion rather than a loop. `sumTo(4)` is `1 + 2 + 3 + 4 = 10`. Return `0` for `n` of 0 or less.',
        starterCode: [
          'function sumTo(n) {',
          '  // Base case first, then the recursive case.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'sums to four', body: 'expect(sumTo(4)).toBe(10);' },
          { name: 'sums to one', body: 'expect(sumTo(1)).toBe(1);' },
          { name: 'returns 0 for zero', body: 'expect(sumTo(0)).toBe(0);' },
          { name: 'returns 0 for negatives', body: 'expect(sumTo(-5)).toBe(0);' },
          { name: 'sums to ten', body: 'expect(sumTo(10)).toBe(55);' },
          { name: 'handles a larger value without overflowing', body: 'expect(sumTo(100)).toBe(5050);', hidden: true },
        ],
        hints: [
          'The base case is `n <= 0`, returning 0.',
          'Otherwise return `n` plus the sum of everything below it.',
          '`return n + sumTo(n - 1);`',
        ],
        solution: [
          'function sumTo(n) {',
          '  if (n <= 0) return 0;',
          '  return n + sumTo(n - 1);',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The base case `n <= 0` is what stops the recursion, and it must come first — without it each call would spawn another forever until the call stack overflows. Using `<=` rather than `===` also handles negative input safely, which the fourth test checks. Each recursive call reduces `n` by one, guaranteeing progress toward the base case. Trace `sumTo(3)`: it returns `3 + sumTo(2)`, which returns `2 + sumTo(1)`, which returns `1 + sumTo(0)`, which returns 0 — so the chain resolves to 6. Module 38 covers when recursion is preferable to a loop.',
      },
    ],
    quiz: {
      id: 'qz-m09-04',
      questions: [
        {
          id: 'q-m09-04-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functions'],
          prompt: 'Why is an IIFE wrapped in parentheses?',
          options: [
            'To make it run faster',
            'Because a statement starting with `function` is parsed as a declaration, which cannot be invoked immediately',
            'To make the function private',
            'Because it is required for all functions',
          ],
          correct: 1,
          optionExplanations: [
            'Parsing, not performance, is the reason.',
            'Correct — the parentheses force an expression reading.',
            'Privacy comes from the function scope, not the parentheses.',
            'Ordinary functions need no wrapping.',
          ],
          explanation:
            'A statement beginning with the `function` keyword is parsed as a function declaration, and a declaration cannot be immediately invoked. Wrapping it in parentheses makes it an expression, after which the trailing `()` calls it.',
        },
        {
          id: 'q-m09-04-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functions'],
          prompt: 'What made IIFEs necessary before ES2015?',
          options: [
            'Functions could not return values',
            'There was no block scope and no module system, so top-level variables became globals',
            'Arrow functions did not exist',
            'Objects could not hold functions',
          ],
          correct: 1,
          optionExplanations: [
            'Functions have always returned values.',
            'Correct — an IIFE created a private function scope.',
            'Arrow syntax is unrelated to the scoping problem.',
            'Objects have always held functions.',
          ],
          explanation:
            'With only `var` and no modules, variables declared at the top level of a script became global and could collide across scripts. An IIFE created a function scope to contain them. `let`, `const` and modules have made most of these uses unnecessary.',
        },
        {
          id: 'q-m09-04-3',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['functions'],
          prompt: 'Why do these two counters not share a value?',
          code: [
            'function make() {',
            '  let n = 0;',
            '  return () => ++n;',
            '}',
            'const a = make();',
            'const b = make();',
            'console.log(a(), b());',
          ].join('\n'),
          options: ['1 1', '1 2', '2 2', '1 0'],
          correct: 0,
          optionExplanations: [
            'Correct — each call to `make` creates its own `n`.',
            'That would require a shared variable.',
            'Neither counter has been called twice.',
            '`++n` increments before returning.',
          ],
          explanation:
            'Every call to `make` creates a fresh `n`, and the returned function captures that particular variable. `a` and `b` therefore have entirely separate counts, each starting at 0 and returning 1 on its first call. That independence is what makes closures useful for private state.',
        },
        {
          id: 'q-m09-04-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functions'],
          prompt: 'What must every recursive function have?',
          options: [
            'At least two parameters',
            'A base case that returns without recursing',
            'An arrow function body',
            'A loop inside it',
          ],
          correct: 1,
          optionExplanations: [
            'Parameter count is irrelevant.',
            'Correct — without it the recursion never stops.',
            'Either function form works.',
            'Recursion replaces the loop rather than containing one.',
          ],
          explanation:
            'A base case is the condition under which the function returns without calling itself, and the recursive case must move toward it. Omit the base case and the function calls itself until the call stack overflows.',
        },
      ],
    },
    summary:
      'A pure function is deterministic and changes nothing outside itself; reading an outer variable that changes, writing to one, logging, or calling `Math.random` all break purity. Array-method callbacks should be pure — take inputs, compute, return — because impure ones produce results that are hard to predict. An **IIFE** is a function expression invoked immediately, wrapped in parentheses because a statement beginning with `function` would otherwise parse as a declaration; it existed to create private scope before `let`, `const` and modules, and now mainly appears in older and bundled code. Two patterns previewed here get full modules later: a **closure** is a returned function that retains access to its creator\'s variables, giving each instance private state, and **recursion** is a function calling itself with a base case to stop it.',
    keyTakeaways: [
      'Pure: same input gives same output, and nothing external changes',
      'Reading a changing outer variable breaks purity just as writing does',
      'Keep array callbacks pure — take inputs, compute, return',
      'An IIFE is wrapped in parentheses so it parses as an expression',
      'Closures give each returned function its own private variables',
      'Recursion needs a base case, or the call stack overflows',
    ],
    relatedLessons: ['l-m09-03', 'l-m08-06'],
    interviewConnections: [
      'What is a pure function and why does it matter?',
      'What is an IIFE and why was it used?',
      'What is a closure?',
      'What does every recursive function need?',
    ],
  },
];
