import { REFERENCE_CATEGORY as C, REFERENCE_ENV as E } from '../schema/types.js';

/**
 * Array reference — construction, access, and the methods that add, remove or
 * extract elements.
 *
 * The single most important fact this file records is which methods mutate. The
 * `mutates` flag on every entry is authoritative: `push`, `pop`, `shift`,
 * `unshift`, `splice`, `sort`, `reverse` and `fill` change the array in place;
 * everything else returns something new.
 */

const A = { category: C.ARRAY, environment: E.ECMASCRIPT };

export default [
  {
    ...A,
    id: 'ref-array-ctor',
    slug: 'array-constructor',
    name: 'Array()',
    aliases: ['new Array', 'array constructor', 'create array'],
    topicIds: ['arrays'],
    mutates: false,
    syntax: 'Array(arrayLength)\nArray(element0, element1, /* … */)\nnew Array(/* … */)',
    summary: 'Creates a new array. With a single numeric argument it creates a **sparse** array of that length instead of an array containing that number.',
    parameters: [
      { name: 'arrayLength', description: 'When exactly one number is passed, the new array has this `length` and no elements at all.' },
      { name: 'element0, element1, …', description: 'With any other argument list, these become the array\'s elements.' },
    ],
    returns: 'A new array.',
    throws: '`RangeError` if the single numeric argument is negative or not an integer.',
    description: [
      'The one-argument special case is the whole reason this entry exists. `Array(3)` is an array of `length` 3 with **no** elements — three holes — while `Array(3, 4)` is `[3, 4]`. `Array("3")` is `["3"]`, because the argument is not a number.',
      'Holes are not `undefined` values: `map` and `forEach` skip them, so `Array(3).map(() => 0)` is still three holes. `Array(3).fill(0)` or `Array.from({ length: 3 }, () => 0)` produces real elements.',
      'Array literals (`[]`, `[1, 2]`) are clearer and have no special cases. Use `Array()` only when you deliberately want a pre-sized array, and always fill it.',
      '`new Array(...)` and `Array(...)` behave identically — the constructor works with or without `new`.',
    ],
    examples: [
      {
        code: [
          'console.log(Array(3).length);',
          'console.log(Array(3));',
          'console.log(Array(3, 4));',
          'console.log(Array(3).map(() => 0));',
          'console.log(Array(3).fill(0));',
          'console.log(Array.from({ length: 3 }, (_, i) => i));',
        ].join('\n'),
        output: '3\n[undefined, undefined, undefined]\n[3, 4]\n[undefined, undefined, undefined]\n[0, 0, 0]\n[0, 1, 2]',
        caption: 'Array(3) has length 3 but no elements — map cannot fill it.',
      },
    ],
    caveats: [
      'One numeric argument sets the length; two or more become elements.',
      'The resulting holes are skipped by `map`, `forEach`, `filter` and `reduce`.',
      'The console prints holes as `undefined`, which hides the difference — use `0 in arr` to tell them apart.',
    ],
    commonMistakes: ['Using `Array(n).map(...)` to build an array of `n` values.'],
    relatedEntries: ['ref-array-from', 'ref-array-fill', 'ref-array-of'],
    lessonId: 'l-m12-01',
  },

  {
    ...A,
    id: 'ref-array-isarray',
    slug: 'array-isarray',
    name: 'Array.isArray()',
    aliases: ['isArray', 'check if array', 'is array'],
    topicIds: ['arrays', 'types'],
    mutates: false,
    syntax: 'Array.isArray(value)',
    summary: 'Returns `true` if the value is an array. The only reliable array test.',
    parameters: [{ name: 'value', description: 'Any value.' }],
    returns: '`true` for an array, otherwise `false`.',
    description: [
      '`typeof []` is `"object"`, so `typeof` cannot answer this question at all.',
      'It works **across realms**. An array created inside an `<iframe>` or a `Worker` has a different `Array` constructor, so `arr instanceof Array` is `false` for it while `Array.isArray(arr)` is `true`. Any code that receives arrays from another document or from `postMessage` needs this distinction.',
      'It returns `false` for array-**like** objects such as `arguments`, a `NodeList`, or `{ length: 2 }`. Convert those with `Array.from()` before using array methods on them.',
    ],
    examples: [
      {
        code: [
          'console.log(Array.isArray([1, 2]));',
          'console.log(Array.isArray("ab"));',
          'console.log(Array.isArray({ length: 2 }));',
          'console.log(typeof []);',
          'console.log(Array.isArray(Array.from({ length: 2 })));',
        ].join('\n'),
        output: 'true\nfalse\nfalse\nobject\ntrue',
        caption: 'Array-like is not array — convert before treating it as one.',
      },
    ],
    caveats: ['Returns `false` for `arguments`, `NodeList` and other array-like objects.'],
    commonMistakes: ['Using `instanceof Array` on values that may come from another realm.'],
    relatedEntries: ['ref-array-from', 'ref-string-tostring-tag'],
    lessonId: 'l-m02-02',
  },

  {
    ...A,
    id: 'ref-array-from',
    slug: 'array-from',
    name: 'Array.from()',
    aliases: ['Array.from', 'convert to array', 'array like to array'],
    topicIds: ['arrays', 'iterators'],
    mutates: false,
    syntax: 'Array.from(iterable)\nArray.from(arrayLike)\nArray.from(source, mapFn)',
    summary: 'Creates a new array from anything iterable or array-like, optionally mapping each element as it goes.',
    parameters: [
      { name: 'source', description: 'An iterable (`Set`, `Map`, string, generator) or an array-like object with a `length` property.' },
      { name: 'mapFn', optional: true, description: 'Called as `(element, index)` for each element. Applied during construction, so no intermediate array is created.' },
    ],
    returns: 'A new array.',
    description: [
      'It handles two different kinds of source. **Iterables** — `Set`, `Map`, `NodeList`, strings, generators — are consumed through their iterator. **Array-likes** — `arguments`, `{ length: 3 }` — are read by index up to `length`.',
      'Spread (`[...source]`) only works on iterables. `Array.from` is the one that also handles plain array-like objects, which is why `Array.from({ length: 3 }, (_, i) => i)` is the standard "range" idiom.',
      'Unlike `Array(n)`, the result is **dense** — every index exists — so the optional `mapFn` runs for all of them. This is why `Array.from` can fill an array where `Array(n).map()` cannot.',
      'For a string it iterates by code point, so `Array.from("🙂")` has length 1 while `"🙂".split("")` has length 2.',
    ],
    examples: [
      {
        code: [
          'console.log(Array.from(new Set([1, 1, 2])));',
          'console.log(Array.from("ab🙂").length);',
          'console.log(Array.from({ length: 4 }, (_, i) => i * 2));',
          'console.log(Array.from(new Map([["a", 1]])));',
          'console.log(Array.from({ length: 2 }));',
        ].join('\n'),
        output: '[1, 2]\n3\n[0, 2, 4, 6]\n[["a", 1]]\n[undefined, undefined]',
        caption: 'The length-plus-mapFn form is the idiomatic way to build a range.',
      },
    ],
    caveats: ['An object without a `length` property produces an empty array rather than an error.'],
    commonMistakes: ['Using spread on an array-like that is not iterable, which throws.'],
    relatedEntries: ['ref-array-of', 'ref-array-ctor', 'ref-array-isarray'],
    lessonId: 'l-m13-06',
  },

  {
    ...A,
    id: 'ref-array-of',
    slug: 'array-of',
    name: 'Array.of()',
    aliases: ['Array.of'],
    topicIds: ['arrays'],
    mutates: false,
    syntax: 'Array.of(element0, element1, /* … */)',
    summary: 'Creates an array from its arguments, without the single-number special case that makes `Array()` surprising.',
    parameters: [{ name: 'element0, element1, …', description: 'The elements of the new array. Any number of them, of any type.' }],
    returns: 'A new array containing exactly the arguments given.',
    description: [
      'It exists purely to fix `Array()`: `Array.of(3)` is `[3]` while `Array(3)` is a three-hole array of length 3.',
      'In everyday code an array literal does the same job more clearly. `Array.of` earns its place when the element list is genuinely dynamic — for example inside a generic helper that must not care whether it received one number.',
      'It is also useful with subclassed arrays, where it constructs an instance of the subclass rather than a plain `Array`.',
    ],
    examples: [
      {
        code: [
          'console.log(Array.of(3));',
          'console.log(Array(3));',
          'console.log(Array.of(1, "a", null));',
          'console.log(Array.of());',
        ].join('\n'),
        output: '[3]\n[undefined, undefined, undefined]\n[1, "a", null]\n[]',
        caption: 'Array.of has no single-number special case.',
      },
    ],
    caveats: ['Rarely needed — an array literal is clearer for a fixed list.'],
    commonMistakes: ['Reaching for it where `[x]` would do.'],
    relatedEntries: ['ref-array-ctor', 'ref-array-from'],
    lessonId: 'l-m12-01',
  },

  {
    ...A,
    id: 'ref-array-length',
    slug: 'array-length',
    name: 'Array.prototype.length',
    aliases: ['array length', 'arr.length', 'count elements'],
    topicIds: ['arrays'],
    mutates: false,
    syntax: 'arr.length\narr.length = newLength',
    summary: 'One more than the highest index in the array. It is **writable** — assigning a smaller value truncates the array in place.',
    parameters: [],
    returns: 'A non-negative integer up to 2^32 − 1.',
    description: [
      'Unlike `String.prototype.length`, this property is writable. `arr.length = 0` is a fast, in-place way to empty an array that every other reference to it also sees — useful precisely when you must not replace the array object.',
      'Setting a larger length adds **holes**, not `undefined` values, so the array becomes sparse.',
      'Because `length` is one past the highest index, it counts holes: `const a = []; a[99] = 1;` gives a `length` of 100 with a single element.',
      'To count actual elements in a possibly-sparse array, use `arr.filter(() => true).length` or `Object.keys(arr).length`.',
    ],
    examples: [
      {
        code: [
          'const a = [1, 2, 3];',
          'a.length = 1;',
          'console.log(a);',
          '',
          'const b = [];',
          'b[4] = "x";',
          'console.log(b.length, Object.keys(b).length);',
          '',
          'const c = [1, 2];',
          'c.length = 4;',
          'console.log(c.length, 3 in c);',
        ].join('\n'),
        output: '[1]\n5 1\n4 false',
        caption: 'Writing length truncates; a sparse index inflates it.',
      },
    ],
    caveats: [
      'Assigning a smaller `length` silently deletes elements.',
      'Counts holes, so it is not a count of present elements in a sparse array.',
    ],
    commonMistakes: ['Using `length` as an element count on an array built by assigning arbitrary indices.'],
    relatedEntries: ['ref-array-ctor', 'ref-array-fill'],
    lessonId: 'l-m12-01',
  },

  {
    ...A,
    id: 'ref-array-at',
    slug: 'array-prototype-at',
    name: 'Array.prototype.at()',
    aliases: ['array at', 'last element', 'negative index'],
    topicIds: ['arrays'],
    mutates: false,
    syntax: 'arr.at(index)',
    summary: 'Returns the element at an index, accepting negative indices that count back from the end.',
    parameters: [{ name: 'index', description: 'Integer position. Negative values count from the end, so `-1` is the last element.' }],
    returns: 'The element, or `undefined` if the index is out of range.',
    description: [
      'The reason it exists: `arr[-1]` reads a **property** named `"-1"`, which does not exist, so it returns `undefined` rather than the last element.',
      'Before `at()`, the last element was written `arr[arr.length - 1]`, which repeats the array expression and breaks when that expression is a function call with side effects.',
      'It returns `undefined` for an out-of-range index, exactly like bracket access, so an empty array gives `undefined` rather than throwing.',
    ],
    examples: [
      {
        code: [
          'const items = ["a", "b", "c"];',
          '',
          'console.log(items.at(0));',
          'console.log(items.at(-1));',
          'console.log(items[-1]);',
          'console.log(items.at(9));',
          'console.log([].at(-1));',
        ].join('\n'),
        output: 'a\nc\nundefined\nundefined\nundefined',
        caption: 'Bracket access with a negative index reads a nonexistent property.',
      },
    ],
    caveats: ['Returns `undefined` rather than throwing for an out-of-range index.'],
    commonMistakes: ['Expecting `arr[-1]` to work like Python.'],
    relatedEntries: ['ref-array-length', 'ref-array-slice', 'ref-string-at'],
    lessonId: 'l-m12-01',
  },

  {
    ...A,
    id: 'ref-array-push',
    slug: 'array-prototype-push',
    name: 'Array.prototype.push()',
    aliases: ['push', 'add to end', 'append'],
    topicIds: ['arrays'],
    mutates: true,
    syntax: 'arr.push(element)\narr.push(element0, element1, /* … */)',
    summary: 'Appends one or more elements to the end of the array **in place** and returns the new length.',
    parameters: [{ name: 'element0, element1, …', description: 'Values to append. Any number of them, of any type.' }],
    returns: 'The new `length` of the array — not the array, and not the pushed element.',
    description: [
      'The return value catches people out: `const a = [].push(1)` gives `1`, the new length. Chaining is not possible; `push` is a statement, not an expression that yields the array.',
      'It mutates, so every reference to the array sees the change. In code built around immutable updates, use `[...arr, item]` instead, which creates a new array.',
      'To append many elements from another array, spread it — `arr.push(...other)` — but note that spreading a very large array can exceed the argument limit and throw a `RangeError`. `arr = arr.concat(other)` or a loop is safer for big data.',
    ],
    examples: [
      {
        code: [
          'const a = [1, 2];',
          'const result = a.push(3, 4);',
          '',
          'console.log(result);',
          'console.log(a);',
          '',
          'const b = [1];',
          'const c = [...b, 2];',
          'console.log(b, c);',
        ].join('\n'),
        output: '4\n[1, 2, 3, 4]\n[1] [1, 2]',
        caption: 'push returns the new length; spread leaves the original alone.',
      },
    ],
    caveats: [
      'Returns the new length, so it cannot be chained.',
      '`arr.push(...huge)` can throw `RangeError` for very large arrays.',
    ],
    commonMistakes: ['Writing `arr = arr.push(x)`, which replaces the array with a number.'],
    relatedEntries: ['ref-array-pop', 'ref-array-unshift', 'ref-array-concat'],
    lessonId: 'l-m12-02',
  },

  {
    ...A,
    id: 'ref-array-pop',
    slug: 'array-prototype-pop',
    name: 'Array.prototype.pop()',
    aliases: ['pop', 'remove last'],
    topicIds: ['arrays'],
    mutates: true,
    syntax: 'arr.pop()',
    summary: 'Removes the **last** element in place and returns it.',
    parameters: [],
    returns: 'The removed element, or `undefined` if the array was empty.',
    description: [
      'Together with `push`, this makes an array a stack: both operate at the end and are O(1).',
      'On an empty array it returns `undefined` and leaves `length` at `0` — it does not throw and does not go negative.',
      'Because `undefined` is also a legitimate element value, `pop()` returning `undefined` does not prove the array was empty. Check `length` first if the distinction matters.',
    ],
    examples: [
      {
        code: [
          'const stack = [1, 2, 3];',
          '',
          'console.log(stack.pop());',
          'console.log(stack);',
          'console.log([].pop());',
          '',
          'const withUndef = [undefined];',
          'console.log(withUndef.pop(), withUndef.length);',
        ].join('\n'),
        output: '3\n[1, 2]\nundefined\nundefined 0',
        caption: 'An undefined result does not distinguish "empty" from "held undefined".',
      },
    ],
    caveats: ['Returns `undefined` for an empty array, which is ambiguous if the array can contain `undefined`.'],
    commonMistakes: ['Using `pop()` in a `while` loop condition, which stops early on a falsy element.'],
    relatedEntries: ['ref-array-push', 'ref-array-shift', 'ref-array-splice'],
    lessonId: 'l-m12-02',
  },

  {
    ...A,
    id: 'ref-array-shift',
    slug: 'array-prototype-shift',
    name: 'Array.prototype.shift()',
    aliases: ['shift', 'remove first'],
    topicIds: ['arrays'],
    mutates: true,
    syntax: 'arr.shift()',
    summary: 'Removes the **first** element in place and returns it, re-indexing everything after it.',
    parameters: [],
    returns: 'The removed element, or `undefined` if the array was empty.',
    description: [
      'Because every remaining element moves down one index, `shift` is **O(n)**, not O(1). Using it to drain a queue in a loop makes the whole operation O(n²).',
      'For a queue over a large array, keep a read index and advance it (`queue[head++]`) instead of shifting; that is O(1) per item at the cost of not reclaiming the memory until you slice.',
      'Like `pop`, it returns `undefined` for an empty array without throwing.',
    ],
    examples: [
      {
        code: [
          'const queue = ["a", "b", "c"];',
          '',
          'console.log(queue.shift());',
          'console.log(queue);',
          '',
          'const items = ["x", "y"];',
          'let head = 0;',
          'console.log(items[head++], items[head++], items[head]);',
        ].join('\n'),
        output: 'a\n["b", "c"]\nx y undefined',
        caption: 'An index-based queue avoids the O(n) re-indexing shift performs.',
      },
    ],
    caveats: ['O(n) per call — draining a large array with `shift` is quadratic.'],
    commonMistakes: ['Using `shift` in a hot loop over a large array.'],
    relatedEntries: ['ref-array-unshift', 'ref-array-pop', 'ref-array-slice'],
    lessonId: 'l-m12-02',
  },

  {
    ...A,
    id: 'ref-array-unshift',
    slug: 'array-prototype-unshift',
    name: 'Array.prototype.unshift()',
    aliases: ['unshift', 'add to start', 'prepend'],
    topicIds: ['arrays'],
    mutates: true,
    syntax: 'arr.unshift(element)\narr.unshift(element0, element1, /* … */)',
    summary: 'Inserts one or more elements at the **start** of the array in place and returns the new length.',
    parameters: [{ name: 'element0, element1, …', description: 'Values to insert. They keep their relative order at the front.' }],
    returns: 'The new `length` of the array.',
    description: [
      'Like `shift`, it re-indexes every existing element, so it is **O(n)** per call.',
      'Multiple arguments are inserted as a block in the order given: `[3].unshift(1, 2)` gives `[1, 2, 3]`, not `[2, 1, 3]`.',
      'The immutable equivalent is `[item, ...arr]`, which is usually clearer in code that avoids mutation.',
    ],
    examples: [
      {
        code: [
          'const a = [3];',
          'const len = a.unshift(1, 2);',
          '',
          'console.log(len);',
          'console.log(a);',
          'console.log([0, ...a]);',
        ].join('\n'),
        output: '3\n[1, 2, 3]\n[0, 1, 2, 3]',
        caption: 'Multiple arguments keep their order at the front.',
      },
    ],
    caveats: ['O(n) per call — repeated `unshift` in a loop is quadratic.'],
    commonMistakes: ['Assuming multiple arguments are inserted one at a time and end up reversed.'],
    relatedEntries: ['ref-array-shift', 'ref-array-push', 'ref-array-splice'],
    lessonId: 'l-m12-02',
  },

  {
    ...A,
    id: 'ref-array-slice',
    slug: 'array-prototype-slice',
    name: 'Array.prototype.slice()',
    aliases: ['array slice', 'copy array', 'shallow copy array', 'subarray'],
    topicIds: ['arrays', 'copying'],
    mutates: false,
    syntax: 'arr.slice()\narr.slice(start)\narr.slice(start, end)',
    summary: 'Returns a **shallow copy** of a portion of the array. The original is never modified.',
    parameters: [
      { name: 'start', optional: true, description: 'Index to begin at, defaulting to `0`. Negative counts from the end.' },
      { name: 'end', optional: true, description: 'Index to stop **before**, defaulting to `length`. Negative counts from the end.' },
    ],
    returns: 'A new array containing the selected elements.',
    description: [
      '`slice()` with no arguments is the classic shallow copy. Modern code usually writes `[...arr]`, which is equivalent.',
      'Shallow means one level: the new array is a new object, but its elements are the **same references**. Mutating `copy[0].name` also changes `original[0].name`.',
      'The end index is exclusive, so `slice(1, 3)` returns two elements.',
      'Compare with `splice`, whose name differs by one letter and which mutates, removes, and returns the **removed** elements. Confusing the two is a common source of destroyed data.',
    ],
    examples: [
      {
        code: [
          'const items = [{ n: 1 }, { n: 2 }, { n: 3 }];',
          'const copy = items.slice();',
          '',
          'console.log(copy === items);',
          'console.log(copy[0] === items[0]);',
          'console.log(items.slice(1, 3).length);',
          'console.log(items.slice(-1).length);',
          'console.log(items.length);',
        ].join('\n'),
        output: 'false\ntrue\n2\n1\n3',
        caption: 'A new array, but the same element objects inside it.',
      },
    ],
    caveats: [
      'Shallow — nested objects are shared with the original.',
      'Easily confused with `splice`, which mutates.',
    ],
    commonMistakes: ['Treating `slice()` as a deep copy.'],
    relatedEntries: ['ref-array-splice', 'ref-array-concat', 'ref-string-slice'],
    lessonId: 'l-m12-03',
  },

  {
    ...A,
    id: 'ref-array-splice',
    slug: 'array-prototype-splice',
    name: 'Array.prototype.splice()',
    aliases: ['splice', 'remove element', 'insert element', 'delete from array'],
    topicIds: ['arrays'],
    mutates: true,
    syntax: 'arr.splice(start)\narr.splice(start, deleteCount)\narr.splice(start, deleteCount, item0, item1, /* … */)',
    summary: 'Removes and/or inserts elements **in place**, returning an array of the removed elements.',
    parameters: [
      { name: 'start', description: 'Index to begin changing at. Negative counts from the end.' },
      { name: 'deleteCount', optional: true, description: 'How many elements to remove. Omitted entirely, everything from `start` onwards is removed; `0` removes nothing.' },
      { name: 'item0, item1, …', optional: true, description: 'Elements to insert at `start` after the removal.' },
    ],
    returns: 'A new array of the **removed** elements — empty if nothing was removed.',
    description: [
      'The return value is the removed elements, **not** the resulting array. `const a = [1,2,3].splice(0, 1)` gives `[1]`, which surprises people expecting `[2, 3]`.',
      'Omitting `deleteCount` is very different from passing `0`. `splice(1)` removes everything from index 1 onwards; `splice(1, 0, "x")` removes nothing and inserts `"x"`.',
      'This is the one method that can insert, remove and replace in a single call, which makes it powerful and easy to misuse.',
      'Removing while iterating forwards skips elements, because every removal shifts later items down while the loop index still advances. Iterate backwards, or use `filter` to build a new array.',
      'Each call is O(n) because the tail is shifted, so repeated `splice` inside a loop is quadratic.',
    ],
    examples: [
      {
        code: [
          'const a = [1, 2, 3, 4];',
          'const removed = a.splice(1, 2, "x");',
          '',
          'console.log(removed);',
          'console.log(a);',
          '',
          'const b = [1, 2, 3];',
          'console.log(b.splice(1, 0, "ins"), b);',
        ].join('\n'),
        output: '[2, 3]\n[1, "x", 4]\n[] [1, "ins", 2, 3]',
        caption: 'It returns what was removed; deleteCount 0 inserts without removing.',
      },
    ],
    caveats: [
      'Returns the removed elements, not the modified array.',
      'Omitting `deleteCount` removes everything from `start` onwards.',
      'Removing during a forward loop skips elements.',
    ],
    commonMistakes: ['Confusing it with `slice`.', 'Assigning the result back over the original array.'],
    relatedEntries: ['ref-array-slice'],
    lessonId: 'l-m12-02',
  },

  {
    ...A,
    id: 'ref-array-concat',
    slug: 'array-prototype-concat',
    name: 'Array.prototype.concat()',
    aliases: ['concat', 'merge arrays', 'join arrays', 'combine arrays'],
    topicIds: ['arrays', 'copying'],
    mutates: false,
    syntax: 'arr.concat()\narr.concat(value0, value1, /* … */)',
    summary: 'Returns a new array joining this array with additional arrays or values. Nothing is modified.',
    parameters: [{ name: 'value0, value1, …', description: 'Arrays whose elements are appended, or single values appended as-is.' }],
    returns: 'A new array.',
    description: [
      'Arrays passed as arguments are flattened by **exactly one level**; non-array values are appended whole. `[1].concat([2, [3]])` gives `[1, 2, [3]]`.',
      '`[...a, ...b]` is the modern equivalent and reads better for a fixed number of arrays. `concat` still wins when the arrays come from a variable list, and it avoids the argument-count limit that spreading into `push` hits.',
      '`concat()` with no arguments is a shallow copy, equivalent to `slice()`.',
      'An object with `Symbol.isConcatSpreadable` set to `true` is also flattened — rarely relevant, but it explains why some array-likes behave unexpectedly here.',
    ],
    examples: [
      {
        code: [
          'const a = [1, 2];',
          'const b = [3, [4]];',
          '',
          'console.log(a.concat(b));',
          'console.log(a.concat(5));',
          'console.log(a);',
          'console.log([...a, ...b]);',
        ].join('\n'),
        output: '[1, 2, 3, [4]]\n[1, 2, 5]\n[1, 2]\n[1, 2, 3, [4]]',
        caption: 'One level of flattening; the original is untouched.',
      },
    ],
    caveats: ['Flattens only one level — nested arrays stay nested.'],
    commonMistakes: ['Expecting deep flattening; use `flat(Infinity)` for that.'],
    relatedEntries: ['ref-array-push', 'ref-array-slice'],
    lessonId: 'l-m12-03',
  },

  {
    ...A,
    id: 'ref-array-join',
    slug: 'array-prototype-join',
    name: 'Array.prototype.join()',
    aliases: ['join', 'array to string', 'implode'],
    topicIds: ['arrays', 'strings'],
    mutates: false,
    syntax: 'arr.join()\narr.join(separator)',
    summary: 'Joins all elements into a single string, separated by a delimiter.',
    parameters: [{ name: 'separator', optional: true, description: 'Text placed between elements, defaulting to `","`. Pass `""` for no separator.' }],
    returns: 'A string. An empty array returns `""`.',
    description: [
      '`null` and `undefined` elements become **empty strings**, not the text `"null"` — so `[1, null, 2].join("-")` is `"1--2"`. Filter first if that matters.',
      'Every other element is converted with `String()`, so nested arrays are joined recursively and objects become `"[object Object]"`.',
      'This is the inverse of `String.prototype.split()`, and the two round-trip cleanly only when the separator does not occur inside the elements.',
    ],
    examples: [
      {
        code: [
          'console.log([1, 2, 3].join("-"));',
          'console.log([1, 2, 3].join());',
          'console.log([1, null, undefined, 2].join("-"));',
          'console.log([].join("-"));',
          'console.log([[1, 2], [3]].join(";"));',
        ].join('\n'),
        output: '1-2-3\n1,2,3\n1---2\n\n1,2;3',
        caption: 'null and undefined become empty strings, not "null".',
      },
    ],
    caveats: ['`null`/`undefined` join as empty strings.', 'Objects become `"[object Object]"`.'],
    commonMistakes: ['Joining a list that may contain `null` without filtering.'],
    relatedEntries: ['ref-string-split', 'ref-string-concat'],
    lessonId: 'l-m12-03',
  },

  {
    ...A,
    id: 'ref-array-includes',
    slug: 'array-prototype-includes',
    name: 'Array.prototype.includes()',
    aliases: ['array includes', 'array contains', 'has element'],
    topicIds: ['arrays'],
    mutates: false,
    syntax: 'arr.includes(searchElement)\narr.includes(searchElement, fromIndex)',
    summary: 'Reports whether the array contains a value, comparing with SameValueZero so `NaN` is found.',
    parameters: [
      { name: 'searchElement', description: 'The value to look for. Objects are compared by reference.' },
      { name: 'fromIndex', optional: true, description: 'Index to start from, defaulting to `0`. Negative counts from the end.' },
    ],
    returns: '`true` if the value is present, otherwise `false`.',
    description: [
      'It uses **SameValueZero**, which is `===` with one change: `NaN` equals itself. `[NaN].includes(NaN)` is `true` while `[NaN].indexOf(NaN)` is `-1`.',
      'It also differs from `indexOf` on holes: `includes` treats a hole as `undefined` and finds it, whereas `indexOf` skips holes entirely.',
      'Objects are compared by reference, so `[{a:1}].includes({a:1})` is `false`. Use `some()` with an explicit predicate to compare by field.',
      'For membership tests inside a loop, a `Set` gives O(1) lookups where `includes` is O(n).',
    ],
    examples: [
      {
        code: [
          'console.log([1, 2, 3].includes(2));',
          'console.log([NaN].includes(NaN));',
          'console.log([NaN].indexOf(NaN));',
          'console.log([{ a: 1 }].includes({ a: 1 }));',
          'console.log([1, , 3].includes(undefined));',
        ].join('\n'),
        output: 'true\ntrue\n-1\nfalse\ntrue',
        caption: 'includes finds NaN and holes; indexOf finds neither.',
      },
    ],
    caveats: ['Objects compare by reference.', 'O(n) — use a `Set` for repeated lookups.'],
    commonMistakes: ['Expecting it to match structurally equal objects.'],
    relatedEntries: ['ref-array-indexof'],
    lessonId: 'l-m12-03',
  },

  {
    ...A,
    id: 'ref-array-indexof',
    slug: 'array-prototype-indexof',
    name: 'Array.prototype.indexOf()',
    aliases: ['array indexOf', 'find position', 'element index'],
    topicIds: ['arrays'],
    mutates: false,
    syntax: 'arr.indexOf(searchElement)\narr.indexOf(searchElement, fromIndex)',
    summary: 'Returns the index of the first matching element using strict equality, or `-1`.',
    parameters: [
      { name: 'searchElement', description: 'The value to find. Compared with `===`.' },
      { name: 'fromIndex', optional: true, description: 'Index to start from, defaulting to `0`. Negative counts from the end.' },
    ],
    returns: 'The index of the first match, or `-1`.',
    description: [
      'It uses strict equality, so `NaN` is never found and objects match only by reference.',
      'The `-1` sentinel is truthy, so `if (arr.indexOf(x))` is wrong in two directions: truthy for any index except 0, and falsy exactly when the element is first. Test `!== -1`, or use `includes()`.',
      'It skips holes, which is why `[, 1].indexOf(undefined)` is `-1` while `includes(undefined)` is `true`.',
      'When you need the position of an element matching a **condition** rather than a value, use `findIndex()`.',
    ],
    examples: [
      {
        code: [
          'const items = ["a", "b", "a"];',
          '',
          'console.log(items.indexOf("a"));',
          'console.log(items.indexOf("a", 1));',
          'console.log(items.indexOf("z"));',
          'console.log([NaN].indexOf(NaN));',
        ].join('\n'),
        output: '0\n2\n-1\n-1',
        caption: 'fromIndex is how you find later occurrences.',
      },
    ],
    caveats: ['Cannot find `NaN`.', '`-1` is truthy — never test the result for truthiness.'],
    commonMistakes: ['Writing `if (arr.indexOf(x))` instead of `!== -1`.'],
    relatedEntries: ['ref-array-includes', 'ref-array-lastindexof'],
    lessonId: 'l-m12-03',
  },

  {
    ...A,
    id: 'ref-array-lastindexof',
    slug: 'array-prototype-lastindexof',
    name: 'Array.prototype.lastIndexOf()',
    aliases: ['array lastIndexOf', 'last position'],
    topicIds: ['arrays'],
    mutates: false,
    syntax: 'arr.lastIndexOf(searchElement)\narr.lastIndexOf(searchElement, fromIndex)',
    summary: 'Returns the index of the last matching element using strict equality, or `-1`.',
    parameters: [
      { name: 'searchElement', description: 'The value to find. Compared with `===`.' },
      { name: 'fromIndex', optional: true, description: 'Index to start searching **backwards** from, defaulting to `length - 1`.' },
    ],
    returns: 'The index of the last match, or `-1`.',
    description: [
      'The search runs backwards but the returned index is still counted from the start.',
      'Like `indexOf` it uses strict equality and cannot find `NaN`.',
      'For a condition rather than a value, `findLastIndex()` is the equivalent.',
    ],
    examples: [
      {
        code: [
          'const items = ["a", "b", "a", "c"];',
          '',
          'console.log(items.lastIndexOf("a"));',
          'console.log(items.lastIndexOf("a", 1));',
          'console.log(items.lastIndexOf("z"));',
        ].join('\n'),
        output: '2\n0\n-1',
        caption: 'fromIndex caps how far right the backwards search begins.',
      },
    ],
    caveats: ['Cannot find `NaN`.', '`-1` is truthy.'],
    commonMistakes: ['Assuming the index is counted from the end.'],
    relatedEntries: ['ref-array-indexof'],
    lessonId: 'l-m12-03',
  },

  {
    ...A,
    id: 'ref-array-fill',
    slug: 'array-prototype-fill',
    name: 'Array.prototype.fill()',
    aliases: ['fill', 'fill array', 'initialise array'],
    topicIds: ['arrays'],
    mutates: true,
    syntax: 'arr.fill(value)\narr.fill(value, start)\narr.fill(value, start, end)',
    summary: 'Fills a range of the array with a single value **in place** and returns the same array.',
    parameters: [
      { name: 'value', description: 'The value written to every position in the range. Objects are written **by reference**.' },
      { name: 'start', optional: true, description: 'Index to begin at, defaulting to `0`. Negative counts from the end.' },
      { name: 'end', optional: true, description: 'Index to stop before, defaulting to `length`.' },
    ],
    returns: 'The same array, now modified.',
    description: [
      'The standard use is turning a sparse `Array(n)` into a dense array: `Array(3).fill(0)` gives `[0, 0, 0]` where `map` would have produced nothing.',
      'The critical caveat is that an **object** value is stored by reference, so every position holds the **same** object. `Array(3).fill([])` gives three references to one array, and pushing to one appears to change all three. Use `Array.from({ length: 3 }, () => [])` to get distinct objects.',
      'It mutates and returns the same array reference, which is what makes the `Array(n).fill(0)` idiom read as a single expression.',
    ],
    examples: [
      {
        code: [
          'console.log(Array(3).fill(0));',
          '',
          'const shared = Array(2).fill([]);',
          'shared[0].push("x");',
          'console.log(shared);',
          '',
          'const distinct = Array.from({ length: 2 }, () => []);',
          'distinct[0].push("x");',
          'console.log(distinct);',
        ].join('\n'),
        output: '[0, 0, 0]\n[["x"], ["x"]]\n[["x"], []]',
        caption: 'fill stores one reference; Array.from calls the factory per element.',
      },
    ],
    caveats: ['An object argument is shared across every filled position.'],
    commonMistakes: ['Using `fill([])` or `fill({})` to create independent objects.'],
    relatedEntries: ['ref-array-from', 'ref-array-ctor', 'ref-array-length'],
    lessonId: 'l-m12-02',
  },
];
