import { REFERENCE_CATEGORY as C, REFERENCE_ENV as E } from '../schema/types.js';

/**
 * Map, Set, the weak collections, and structuredClone.
 *
 * `Map` and `Set` compare keys with **SameValueZero**: `===` except that `NaN`
 * equals itself, and `0` and `-0` are the same key. Objects are still compared
 * by reference, which is the fact that decides whether these structures solve
 * your problem or not.
 *
 * `structuredClone` is a Web API rather than ECMAScript — its `environment`
 * field says so — but it belongs here because it is the deep-copy counterpart
 * to everything else in this file.
 */

const M = { category: C.COLLECTIONS, environment: E.ECMASCRIPT };

export default [
  {
    ...M,
    id: 'ref-map-ctor',
    slug: 'map-constructor',
    name: 'Map()',
    aliases: ['new Map', 'map constructor', 'map vs object', 'dictionary'],
    topicIds: ['data-structures'],
    mutates: false,
    syntax: 'new Map()\nnew Map(iterable)',
    summary: 'Creates a keyed collection that accepts **any** value as a key, preserves insertion order, and has a real `size`.',
    parameters: [{ name: 'iterable', optional: true, description: 'An iterable of `[key, value]` pairs — an array of pairs, another `Map`, or `Object.entries(obj)`.' }],
    returns: 'A new `Map`.',
    description: [
      'Choose `Map` over a plain object when keys come from **data** rather than from your code. Four differences drive that decision.',
      '**Any key type.** Object property names are always strings or symbols, so `obj[1]` and `obj["1"]` are the same property. A `Map` keeps `1` and `"1"` distinct, and accepts objects, functions and `NaN` as keys.',
      '**True insertion order.** Objects reorder integer-like keys ahead of everything else, so an object keyed by numeric ids comes back sorted numerically. A `Map` iterates strictly in insertion order.',
      '**No prototype collisions.** A plain object inherits from `Object.prototype`, so a data-derived key of `"constructor"` or `"__proto__"` reaches inherited machinery. A `Map` has no such keys at all — which is why it is the safer container for untrusted keys.',
      '**A real `size`** and direct iterability, instead of `Object.keys(obj).length` and a conversion step.',
      'Plain objects remain better for fixed, code-authored shapes, and are the only option when the value must be `JSON.stringify`d — a `Map` serialises as `{}`.',
    ],
    examples: [
      {
        code: [
          'const m = new Map([["a", 1], [2, "two"]]);',
          '',
          'console.log(m.size);',
          'console.log(m.get(2), m.get("2"));',
          'console.log([...m.keys()]);',
          '',
          'const fromObj = new Map(Object.entries({ x: 1 }));',
          'console.log(fromObj.get("x"));',
          '',
          'console.log(JSON.stringify({ m: new Map([["a", 1]]) }));',
        ].join('\n'),
        output: '2\ntwo undefined\n["a", 2]\n1\n{"m":{}}',
        caption: 'Numeric and string keys stay distinct — and a Map cannot be JSON-serialised.',
      },
    ],
    caveats: [
      '`JSON.stringify` turns a `Map` into `{}` — convert with `Object.fromEntries` or `[...map]` first.',
      'Object keys are compared by reference, so a lookalike object never matches.',
    ],
    commonMistakes: ['Using a plain object for a cache keyed by user-supplied strings.'],
    relatedEntries: ['ref-map-set', 'ref-map-get', 'ref-set-ctor', 'ref-object-entries'],
    lessonId: 'l-m34-01',
  },

  {
    ...M,
    id: 'ref-map-set',
    slug: 'map-prototype-set',
    name: 'Map.prototype.set()',
    aliases: ['map set', 'add to map'],
    topicIds: ['data-structures'],
    mutates: true,
    syntax: 'map.set(key, value)',
    summary: 'Adds or replaces an entry **in place** and returns the map itself, so calls can be chained.',
    parameters: [
      { name: 'key', description: 'Any value. Compared with SameValueZero, so objects match only by reference.' },
      { name: 'value', description: 'Any value.' },
    ],
    returns: 'The **map itself** — not the value, and not the previous value. This is what makes chaining work.',
    description: [
      'Returning the map is deliberate and differs from `Array.prototype.push`, which returns a length. `map.set("a", 1).set("b", 2)` is the idiomatic chained form.',
      'Setting an existing key **replaces the value but keeps the original insertion position**. It does not move the entry to the end — which is exactly why an LRU cache implemented on a `Map` must `delete` before re-inserting.',
      '`NaN` works as a key because SameValueZero treats it as equal to itself, and `0` and `-0` collapse to the same key.',
    ],
    examples: [
      {
        code: [
          'const m = new Map();',
          'm.set("a", 1).set("b", 2);',
          '',
          'console.log([...m.keys()]);',
          '',
          'm.set("a", 99);',
          'console.log([...m.keys()], m.get("a"));',
          '',
          'm.set(NaN, "nan");',
          'console.log(m.get(NaN));',
          'console.log(m.set("c", 3) === m);',
        ].join('\n'),
        output: '["a", "b"]\n["a", "b"] 99\nnan\ntrue',
        caption: 'Re-setting a key updates the value without moving its position.',
      },
    ],
    caveats: ['Re-setting an existing key does not change its iteration order.'],
    commonMistakes: ['Expecting `set` to return the value, as an assignment expression would.'],
    relatedEntries: ['ref-map-get', 'ref-map-ctor', 'ref-map-delete'],
    lessonId: 'l-m34-01',
  },

  {
    ...M,
    id: 'ref-map-get',
    slug: 'map-prototype-get',
    name: 'Map.prototype.get()',
    aliases: ['map get', 'read from map', 'lookup'],
    topicIds: ['data-structures'],
    mutates: false,
    syntax: 'map.get(key)',
    summary: 'Returns the value stored for a key, or `undefined` when the key is absent.',
    parameters: [{ name: 'key', description: 'The key to look up, compared with SameValueZero.' }],
    returns: 'The stored value, or `undefined`.',
    description: [
      'Lookup is O(1) on average, which is the reason to prefer a `Map` over repeatedly scanning an array with `find`.',
      '`undefined` is ambiguous when the map can legitimately store `undefined` as a value. Use `has()` to distinguish "absent" from "present but undefined".',
      'Object keys are matched by reference, so `m.get({ id: 1 })` never finds an entry stored under a different `{ id: 1 }` object. Key on a primitive — an id — when you need value-based lookup.',
      'The common "get or create" pattern is `const list = m.get(k) ?? (m.set(k, []), m.get(k))`, or more readably an explicit `if (!m.has(k)) m.set(k, [])`.',
    ],
    examples: [
      {
        code: [
          'const m = new Map([["present", undefined]]);',
          '',
          'console.log(m.get("present"));',
          'console.log(m.get("absent"));',
          'console.log(m.has("present"), m.has("absent"));',
          '',
          'const key = { id: 1 };',
          'const byRef = new Map([[key, "found"]]);',
          'console.log(byRef.get(key), byRef.get({ id: 1 }));',
        ].join('\n'),
        output: 'undefined\nundefined\ntrue false\nfound undefined',
        caption: 'Only has() separates a stored undefined from a missing key.',
      },
    ],
    caveats: ['`undefined` does not prove the key is absent — use `has()`.', 'Object keys match by reference only.'],
    commonMistakes: ['Using `if (map.get(k))` as a presence test, which fails for falsy stored values.'],
    relatedEntries: ['ref-map-has', 'ref-map-set', 'ref-map-ctor'],
    lessonId: 'l-m34-01',
  },

  {
    ...M,
    id: 'ref-map-has',
    slug: 'map-prototype-has',
    name: 'Map.prototype.has()',
    aliases: ['map has', 'key exists', 'set has'],
    topicIds: ['data-structures'],
    mutates: false,
    syntax: 'map.has(key)\nset.has(value)',
    summary: 'Returns whether a key exists, without regard to what value it holds. `Set.prototype.has()` behaves the same for members.',
    parameters: [{ name: 'key', description: 'The key (or, for a `Set`, the member) to test. Compared with SameValueZero.' }],
    returns: 'A boolean.',
    description: [
      'This is the correct presence test, because a stored value of `undefined`, `0`, `""` or `false` would make a `get`-based truthiness check wrong.',
      'On a `Set`, `has()` is the whole reason the structure exists: membership testing is O(1), where `array.includes` is O(n). Converting an array to a `Set` once before a loop of lookups turns an O(n²) algorithm into O(n).',
      'SameValueZero means `has(NaN)` works, unlike `indexOf`.',
    ],
    examples: [
      {
        code: [
          'const m = new Map([["zero", 0]]);',
          'console.log(m.has("zero"), Boolean(m.get("zero")));',
          '',
          'const blocked = new Set(["a", "b"]);',
          'console.log(blocked.has("a"), blocked.has("z"));',
          '',
          'console.log(new Set([NaN]).has(NaN));',
          'console.log([NaN].indexOf(NaN) !== -1);',
        ].join('\n'),
        output: 'true false\ntrue false\ntrue\nfalse',
        caption: 'has() is correct where a truthiness check on the value is not.',
      },
    ],
    caveats: ['Object keys and members match by reference.'],
    commonMistakes: ['Testing presence with `get()` and truthiness.'],
    relatedEntries: ['ref-map-get', 'ref-set-add', 'ref-array-includes'],
    lessonId: 'l-m34-02',
  },

  {
    ...M,
    id: 'ref-map-delete',
    slug: 'map-prototype-delete',
    name: 'Map.prototype.delete()',
    aliases: ['map delete', 'remove key', 'Map.prototype.clear', 'clear map', 'set delete'],
    topicIds: ['data-structures'],
    mutates: true,
    syntax: 'map.delete(key)\nmap.clear()',
    summary: '`delete()` removes one entry and reports whether it existed. `clear()` removes everything and returns `undefined`.',
    parameters: [{ name: 'key', description: 'The key to remove. Compared with SameValueZero.' }],
    returns: '`delete()`: `true` if the entry existed and was removed, `false` if it was not there. `clear()`: `undefined`.',
    description: [
      'The boolean from `delete()` is genuinely useful — it distinguishes "removed" from "was not there" without a preceding `has()` call.',
      'It is unrelated to the `delete` **operator** used on object properties, which returns `true` in almost all cases and says nothing about whether the property existed.',
      '`delete` followed by `set` is how you move an entry to the end of the iteration order, which is the core of an LRU cache built on a `Map`.',
      'The same pair exists on `Set`, with `delete(value)` and `clear()`.',
      'Deleting during iteration is safe: entries removed before being reached are simply not visited, and the collection is not corrupted.',
    ],
    examples: [
      {
        code: [
          'const m = new Map([["a", 1], ["b", 2]]);',
          '',
          'console.log(m.delete("a"));',
          'console.log(m.delete("a"));',
          'console.log(m.size);',
          '',
          'm.set("c", 3);',
          'const v = m.get("b");',
          'm.delete("b");',
          'm.set("b", v);',
          'console.log([...m.keys()]);',
          '',
          'm.clear();',
          'console.log(m.size);',
        ].join('\n'),
        output: 'true\nfalse\n1\n["c", "b"]\n0',
        caption: 'delete-then-set is what moves a key to the end — the LRU refresh.',
      },
    ],
    caveats: ['Different from the `delete` operator on object properties.'],
    commonMistakes: ['Re-`set`ting a key expecting it to move to the end of the order.'],
    relatedEntries: ['ref-map-set', 'ref-map-size', 'ref-map-has'],
    lessonId: 'l-m34-01',
  },

  {
    ...M,
    id: 'ref-map-size',
    slug: 'map-size',
    name: 'Map.prototype.size',
    aliases: ['map size', 'set size', 'count entries', 'Set.prototype.size'],
    topicIds: ['data-structures'],
    mutates: false,
    syntax: 'map.size\nset.size',
    summary: 'The number of entries, as a read-only accessor property. `Set.prototype.size` is identical for members.',
    parameters: [],
    returns: 'A non-negative integer.',
    description: [
      'It is a **property, not a method** — `map.size`, never `map.size()`. Calling it throws `TypeError: map.size is not a function`.',
      'It is also read-only. Unlike `Array.prototype.length`, assigning to it does nothing; use `clear()` to empty the collection.',
      'This is one of the ergonomic wins over a plain object, where counting requires `Object.keys(obj).length` — an O(n) operation that allocates an array.',
      '`new Set(array).size` is the compact way to count distinct values in an array.',
    ],
    examples: [
      {
        code: [
          'const s = new Set([1, 1, 2, 3, 3]);',
          '',
          'console.log(s.size);',
          'console.log(new Set("hello").size);',
          '',
          'const m = new Map([["a", 1]]);',
          'try {',
          '  m.size = 99;',
          '} catch (err) {',
          '  console.log(err.constructor.name);',
          '}',
          'console.log(m.size);',
          '',
          'console.log(Object.keys({ a: 1, b: 2 }).length);',
        ].join('\n'),
        output: '3\n4\nTypeError\n1\n2',
        caption: 'size is a getter with no setter — assigning to it throws in strict mode.',
      },
    ],
    caveats: ['A property, not a method.', 'Read-only — assigning to it throws in strict mode.'],
    commonMistakes: ['Writing `map.size()`.'],
    relatedEntries: ['ref-map-delete', 'ref-array-length', 'ref-set-ctor'],
    lessonId: 'l-m34-01',
  },

  {
    ...M,
    id: 'ref-map-entries',
    slug: 'map-prototype-entries',
    name: 'Map.prototype.entries()',
    aliases: ['map entries', 'Map.prototype.keys', 'Map.prototype.values', 'Map.prototype.forEach', 'iterate map', 'map to array'],
    topicIds: ['data-structures', 'iterators'],
    mutates: false,
    syntax: 'map.entries()\nmap.keys()\nmap.values()\nmap.forEach(callbackFn)',
    summary: 'Iterate a map in insertion order. `entries()` is the default iterator, so `for...of` over a map yields `[key, value]` pairs directly.',
    parameters: [{ name: 'callbackFn', optional: true, description: 'For `forEach`, called as `(value, key, map)` — **value first**, which is the reverse of the entry order.' }],
    returns: 'An **iterator** for `entries`/`keys`/`values`; `undefined` for `forEach`.',
    description: [
      '`Map.prototype[Symbol.iterator]` is `entries`, so `for (const [k, v] of map)` works without calling anything, and `[...map]` gives an array of pairs.',
      'The `forEach` callback signature is `(value, key, map)` — **value before key** — which mirrors `Array.prototype.forEach`\'s `(element, index)` but reads backwards next to `entries()`. Getting this the wrong way round is a common bug.',
      'All of these return iterators, not arrays, so `.map()` and `.filter()` are unavailable until you spread. They are also single-use.',
      'Iteration order is strict insertion order, unaffected by key type — the guarantee a plain object does not give.',
      '`Object.fromEntries(map)` converts to a plain object, but stringifies the keys and drops duplicates that differed only by type.',
    ],
    examples: [
      {
        code: [
          'const m = new Map([["a", 1], ["b", 2]]);',
          '',
          'for (const [key, value] of m) {',
          '  console.log(key, value);',
          '}',
          '',
          'm.forEach((value, key) => console.log("forEach:", key, value));',
          '',
          'console.log([...m.keys()], [...m.values()]);',
          'console.log(Object.fromEntries(m));',
        ].join('\n'),
        output: 'a 1\nb 2\nforEach: a 1\nforEach: b 2\n["a", "b"] [1, 2]\n{a: 1, b: 2}',
        caption: 'for...of gives [key, value]; forEach gives (value, key).',
      },
    ],
    caveats: [
      '`forEach` passes `(value, key)`, the reverse of the entry order.',
      'Iterators are single-use and have no array methods.',
    ],
    commonMistakes: ['Writing `map.forEach((key, value) => …)`.'],
    relatedEntries: ['ref-map-ctor', 'ref-object-fromentries', 'ref-array-entries'],
    lessonId: 'l-m34-01',
  },

  {
    ...M,
    id: 'ref-set-ctor',
    slug: 'set-constructor',
    name: 'Set()',
    aliases: ['new Set', 'set constructor', 'unique values', 'deduplicate array'],
    topicIds: ['data-structures'],
    mutates: false,
    syntax: 'new Set()\nnew Set(iterable)',
    summary: 'Creates a collection of unique values with O(1) membership testing, preserving insertion order.',
    parameters: [{ name: 'iterable', optional: true, description: 'Any iterable — an array, a string, another `Set`. Duplicates are dropped during construction.' }],
    returns: 'A new `Set`.',
    description: [
      '`[...new Set(array)]` is the standard array deduplication idiom, and it preserves first-occurrence order.',
      'Uniqueness uses SameValueZero, so `NaN` deduplicates correctly and `0`/`-0` collapse — but **objects compare by reference**, so `new Set([{a:1}, {a:1}])` has size 2. To deduplicate objects, key a `Map` by an id or another stable field.',
      'A `Set` built from a string iterates by code point, so `new Set("aab")` has three members and handles emoji correctly.',
      'Its real value is membership testing. Building a `Set` once before a loop turns repeated `array.includes` scans from O(n²) into O(n).',
      'Like `Map`, it serialises as `{}` under `JSON.stringify` — convert with `[...set]` first.',
    ],
    examples: [
      {
        code: [
          'const nums = [3, 1, 3, 2, 1];',
          'console.log([...new Set(nums)]);',
          '',
          'console.log(new Set([{ a: 1 }, { a: 1 }]).size);',
          'console.log(new Set([NaN, NaN, 0, -0]).size);',
          '',
          'const allowed = new Set(["read", "write"]);',
          'console.log(["read", "admin"].filter((p) => allowed.has(p)));',
        ].join('\n'),
        output: '[3, 1, 2]\n2\n2\n["read"]',
        caption: 'Deduplication keeps first-occurrence order; objects are not deduplicated.',
      },
    ],
    caveats: [
      'Does not deduplicate structurally equal objects.',
      '`JSON.stringify(set)` is `{}`.',
    ],
    commonMistakes: ['Expecting a `Set` to remove duplicate objects with the same fields.'],
    relatedEntries: ['ref-set-add', 'ref-map-has', 'ref-map-ctor'],
    lessonId: 'l-m34-02',
  },

  {
    ...M,
    id: 'ref-set-add',
    slug: 'set-prototype-add',
    name: 'Set.prototype.add()',
    aliases: ['set add', 'add to set'],
    topicIds: ['data-structures'],
    mutates: true,
    syntax: 'set.add(value)',
    summary: 'Adds a value **in place** if it is not already present, and returns the set itself so calls can be chained.',
    parameters: [{ name: 'value', description: 'Any value. Compared with SameValueZero against existing members.' }],
    returns: 'The **set itself** — not a boolean, and not the value.',
    description: [
      'Adding a value that is already present is a silent no-op; the set is unchanged and the original insertion position is kept.',
      'Because it returns the set, `s.add(1).add(2)` chains — the same design as `Map.prototype.set`.',
      'It gives no indication of whether the value was new. Call `has()` first if you need to know, or compare `size` before and after.',
      'The modern set-operation methods — `union`, `intersection`, `difference`, `symmetricDifference`, `isSubsetOf` — are ES2025 and not yet universally available; `filter` with `has()` is the portable equivalent.',
    ],
    examples: [
      {
        code: [
          'const s = new Set();',
          's.add("a").add("b").add("a");',
          '',
          'console.log(s.size, [...s]);',
          'console.log(s.add("c") === s);',
          '',
          'const before = s.size;',
          's.add("a");',
          'console.log(s.size === before);',
          '',
          'const other = new Set(["b", "z"]);',
          'console.log([...s].filter((v) => other.has(v)));',
        ].join('\n'),
        output: '2 ["a", "b"]\ntrue\ntrue\n["b"]',
        caption: 'Adding a duplicate is a silent no-op, and add returns the set.',
      },
    ],
    caveats: ['Gives no signal about whether the value was already present.'],
    commonMistakes: ['Expecting a boolean return like `Map.prototype.delete`.'],
    relatedEntries: ['ref-set-ctor', 'ref-map-has', 'ref-map-delete'],
    lessonId: 'l-m34-02',
  },

  {
    ...M,
    id: 'ref-weakmap',
    slug: 'weakmap',
    name: 'WeakMap()',
    aliases: ['new WeakMap', 'WeakSet', 'weak references', 'private data', 'metadata for objects'],
    topicIds: ['data-structures'],
    mutates: false,
    syntax: 'new WeakMap()\nnew WeakMap(iterable)\nnew WeakSet()',
    summary: 'A keyed collection whose keys must be objects and are held **weakly** — an entry does not stop its key being garbage-collected.',
    parameters: [{ name: 'iterable', optional: true, description: 'An iterable of `[objectKey, value]` pairs.' }],
    returns: 'A new `WeakMap` (or `WeakSet`).',
    throws: '`TypeError` if a primitive is used as a key.',
    description: [
      'The single purpose is **associating data with an object you do not own** without keeping that object alive. A regular `Map` holding DOM nodes as keys prevents those nodes from ever being collected; a `WeakMap` does not.',
      'Keys must be objects (or, since ES2023, non-registered symbols). Primitives throw a `TypeError`.',
      'It is deliberately **not iterable and not inspectable**: no `size`, no `keys()`, no `values()`, no `forEach`, no `clear()`. Only `get`, `set`, `has` and `delete`. This is a specification requirement, not an oversight — exposing iteration would make garbage-collection timing observable to the program.',
      'That non-observability is the honest limitation to state: you cannot test that an entry was collected, and nothing in the specification says when — or even whether — collection happens. Do not write code or tests that depend on it.',
      'Typical uses: caching a computed value per object, storing private state for instances, and marking objects as already-processed. `WeakSet` is the membership-only version.',
      '`WeakRef` and `FinalizationRegistry` expose weakness more directly, and carry the same warning far more strongly — their callbacks may never run.',
    ],
    examples: [
      {
        code: [
          'const meta = new WeakMap();',
          'const obj = { id: 1 };',
          '',
          'meta.set(obj, { visits: 0 });',
          'console.log(meta.has(obj), meta.get(obj).visits);',
          '',
          'try {',
          '  meta.set("primitive", 1);',
          '} catch (err) {',
          '  console.log(err.constructor.name);',
          '}',
          '',
          'console.log("size" in meta, typeof meta.forEach);',
          '',
          'const seen = new WeakSet();',
          'seen.add(obj);',
          'console.log(seen.has(obj), seen.has({ id: 1 }));',
        ].join('\n'),
        output: 'true 0\nTypeError\nfalse undefined\ntrue false',
        caption: 'No size, no forEach — weakness must not be observable.',
      },
    ],
    caveats: [
      'Keys must be objects; primitives throw.',
      'Not iterable and has no `size` — by design.',
      'Collection timing is unobservable and unguaranteed. Never assert that an entry was collected.',
    ],
    commonMistakes: ['Trying to iterate it.', 'Writing a test that asserts a key was garbage-collected.'],
    relatedEntries: ['ref-map-ctor', 'ref-map-get'],
    lessonId: 'l-m34-03',
  },

  {
    ...M,
    id: 'ref-structuredclone',
    slug: 'structuredclone',
    name: 'structuredClone()',
    aliases: ['structured clone', 'deep copy', 'deep clone'],
    environment: E.WEB_API,
    topicIds: ['copying', 'data-structures'],
    mutates: false,
    syntax: 'structuredClone(value)\nstructuredClone(value, { transfer })',
    summary: 'Creates a **deep** copy of a value using the structured clone algorithm — handling nested objects, cycles, `Map`, `Set`, `Date` and typed arrays.',
    parameters: [
      { name: 'value', description: 'The value to clone. Must be structured-cloneable.' },
      { name: 'options', optional: true, description: 'A `transfer` array of transferable objects, which are moved rather than copied and become unusable in the source.' },
    ],
    returns: 'A deep copy, sharing no references with the original.',
    throws: '`DataCloneError` (a `DOMException`) for functions, symbols, DOM nodes and other non-cloneable values.',
    description: [
      'It handles the things a hand-written clone usually gets wrong: **cycles** terminate correctly, and shared references stay shared rather than being duplicated into two objects.',
      'Cloneable types include plain objects, arrays, `Map`, `Set`, `Date`, `RegExp`, `ArrayBuffer`, typed arrays, `Blob` and `File`.',
      '**Not cloneable**: functions, symbols, DOM nodes, `WeakMap`/`WeakSet`, and anything holding them. These throw a `DataCloneError` rather than being silently dropped — which is better than the silent losses of the JSON approach.',
      '**Prototypes are not preserved.** A class instance clones into a **plain object** with the same own properties, so `clone instanceof MyClass` is `false` and its methods are gone. Getters are also flattened into plain data properties.',
      'Compare with `JSON.parse(JSON.stringify(x))`, which drops `undefined`, functions and symbols; turns `Date` into a string; renders `Map` and `Set` as `{}`; converts `NaN`/`Infinity` to `null`; and throws on cycles. `structuredClone` is strictly better for plain data.',
      'It is a **Web API**, defined by HTML rather than ECMAScript. Available in browsers and in Node 17+, but not in every JavaScript runtime.',
      'For a deep clone of class instances, or where structured cloning is unavailable, a purpose-built library or a hand-written recursive clone that copies the prototype is still needed.',
    ],
    examples: [
      {
        code: [
          'const original = {',
          '  when: new Date(0),',
          '  tags: new Set(["a"]),',
          '  lookup: new Map([["k", { n: 1 }]]),',
          '};',
          'original.self = original;',
          '',
          'const copy = structuredClone(original);',
          '',
          'console.log(copy.self === copy);',
          'console.log(copy.when instanceof Date, copy.when.toISOString());',
          'console.log(copy.tags instanceof Set, copy.lookup.get("k").n);',
          'console.log(copy.lookup.get("k") === original.lookup.get("k"));',
          '',
          'class P { constructor() { this.x = 1; } }',
          'console.log(structuredClone(new P()) instanceof P);',
          '',
          'try {',
          '  structuredClone({ fn: () => {} });',
          '} catch (err) {',
          '  console.log(err.name);',
          '}',
        ].join('\n'),
        output: 'true\ntrue 1970-01-01T00:00:00.000Z\ntrue 1\nfalse\nfalse\nDataCloneError',
        caption: 'Cycles survive, Date and Map survive — but the class prototype does not.',
      },
    ],
    caveats: [
      'Throws `DataCloneError` on functions, symbols and DOM nodes.',
      'Does **not** preserve prototypes — class instances become plain objects.',
      'Getters are flattened into data properties.',
      'A Web API, not ECMAScript — absent from some runtimes.',
    ],
    commonMistakes: ['Expecting a cloned class instance to keep its methods.', 'Reaching for JSON round-tripping instead.'],
    relatedEntries: ['ref-object-assign', 'ref-json-stringify', 'ref-array-slice'],
    lessonId: 'l-m34-04',
  },
];
