import { REFERENCE_CATEGORY as C, REFERENCE_ENV as E } from '../schema/types.js';

/**
 * Events and forms.
 *
 * The listener-identity rule underlies most of this file: `removeEventListener`
 * needs the **same function reference** that was added, which is why inline arrow
 * functions can never be removed and why `AbortController` signals have largely
 * replaced manual removal.
 */

const V = { category: C.EVENTS, environment: E.DOM };
const F = { category: C.FORMS, environment: E.DOM };

const FIXTURE = '<form id="f"><input name="q" value="start"><input name="tag" value="a"><input name="tag" value="b">'
  + '<input type="checkbox" name="agree"><input type="email" name="email" required><button id="btn">Go</button></form>'
  + '<ul id="list"><li data-id="1"><span>Row</span></li></ul>';

export default [
  {
    ...V,
    id: 'ref-events-addeventlistener',
    slug: 'eventtarget-addeventlistener',
    name: 'EventTarget.addEventListener()',
    aliases: ['addEventListener', 'listen for event', 'event handler', 'once', 'passive', 'capture'],
    topicIds: ['events'],
    mutates: true,
    syntax: 'target.addEventListener(type, listener)\ntarget.addEventListener(type, listener, options)',
    summary: 'Registers a function to run when an event of the given type reaches the target. Multiple listeners can coexist on one target.',
    parameters: [
      { name: 'type', description: 'The event name **without** an `on` prefix — `"click"`, not `"onclick"`. Case-sensitive.' },
      { name: 'listener', description: 'A function receiving the `Event`. Inside a non-arrow function, `this` is the `currentTarget`.' },
      { name: 'options', optional: true, description: 'An object: `capture` to fire during the capture phase, `once` to auto-remove after one call, `passive` to promise never to call `preventDefault`, `signal` to remove via an `AbortController`. A bare boolean means `capture`.' },
    ],
    returns: '`undefined`.',
    description: [
      'Pass the function **reference**, not a call. `addEventListener("click", handler())` invokes `handler` immediately and registers its return value — usually `undefined`, which is accepted silently and never fires. This is one of the quietest bugs in the DOM API.',
      'Adding the **exact same** function reference for the same type and capture setting twice is a no-op; the listener is registered once. Two structurally identical but distinct arrow functions, however, are two listeners.',
      '`{ once: true }` removes the listener automatically after it runs — the clean way to handle one-shot events without manual removal.',
      '`{ passive: true }` tells the browser you will not call `preventDefault()`, so it can start scrolling without waiting for your handler. Browsers already default `wheel`, `touchstart` and `touchmove` listeners on the document to passive for this reason. Calling `preventDefault()` in a passive listener is ignored with a console warning.',
      '`{ signal }` is the modern cleanup mechanism: one `controller.abort()` removes every listener registered with that signal, however many targets they span.',
      'Listeners fire in registration order within a phase. Capture-phase listeners on ancestors run before the target, then bubble-phase listeners run on the way back up.',
    ],
    examples: [
      {
        code: [
          'const btn = document.querySelector("#btn");',
          'let count = 0;',
          '',
          'const handler = () => { count += 1; };',
          'btn.addEventListener("click", handler);',
          'btn.addEventListener("click", handler);',
          'btn.click();',
          'console.log("same reference twice:", count);',
          '',
          'btn.addEventListener("click", () => { count += 10; }, { once: true });',
          'btn.click();',
          'btn.click();',
          'console.log("once fired a single time:", count);',
          '',
          'const controller = new AbortController();',
          'btn.addEventListener("click", () => { count += 100; }, { signal: controller.signal });',
          'controller.abort();',
          'btn.click();',
          'console.log("aborted listener never ran:", count);',
        ].join('\n'),
        output: 'same reference twice: 1\nonce fired a single time: 13\naborted listener never ran: 14',
        caption: 'Duplicate registration is ignored; once and signal handle their own cleanup.',
        needsDom: true,
        html: FIXTURE,
      },
    ],
    caveats: [
      'Passing `handler()` instead of `handler` registers `undefined` and fails silently.',
      'The type has no `on` prefix.',
      '`preventDefault()` does nothing in a passive listener.',
      'An anonymous function cannot be removed later.',
    ],
    commonMistakes: ['Calling the handler in the registration.', 'Registering in a loop without cleanup, accumulating listeners.'],
    relatedEntries: ['ref-events-removeeventlistener', 'ref-events-target', 'ref-events-preventdefault'],
    lessonId: 'l-m19-01',
  },

  {
    ...V,
    id: 'ref-events-removeeventlistener',
    slug: 'eventtarget-removeeventlistener',
    name: 'EventTarget.removeEventListener()',
    aliases: ['removeEventListener', 'remove listener', 'cleanup listener', 'memory leak'],
    topicIds: ['events', 'performance'],
    mutates: true,
    syntax: 'target.removeEventListener(type, listener)\ntarget.removeEventListener(type, listener, options)',
    summary: 'Removes a previously registered listener. It only works when given the **identical function reference** and a matching `capture` setting.',
    parameters: [
      { name: 'type', description: 'The event type, matching the registration.' },
      { name: 'listener', description: 'The **same function object** that was added. A structurally identical new function does not match.' },
      { name: 'options', optional: true, description: 'Only `capture` is compared. `once` and `passive` are ignored here.' },
    ],
    returns: '`undefined`. There is **no** indication of whether anything was removed.',
    description: [
      'Identity is the whole story. `el.addEventListener("click", () => f())` can never be removed, because the arrow function was not stored anywhere. Neither can `el.removeEventListener("click", this.handler.bind(this))` — `bind` returns a **new** function every call, so the one passed to `remove` is not the one that was added.',
      'The fix is to store the reference once: `this.onClick = this.onClick.bind(this)` in a constructor, or a class field arrow, or a plain named function.',
      'The `capture` flag must match. A listener added with `{ capture: true }` is a different registration from one added without it, and removing needs the same flag.',
      'It fails **silently** when nothing matches, which is why accumulating listeners often goes unnoticed until scroll performance degrades.',
      'Listeners that are never removed are a common memory leak: the listener closes over its scope, and a listener on `window` or `document` keeps a detached element and its whole subtree reachable. The DevTools Memory panel can filter for detached nodes to find these.',
      'In modern code an `AbortController` signal is preferable — one `abort()` removes everything registered with it, with no references to track.',
    ],
    examples: [
      {
        code: [
          'const btn = document.querySelector("#btn");',
          'let count = 0;',
          '',
          'btn.addEventListener("click", () => { count += 1; });',
          'btn.removeEventListener("click", () => { count += 1; });',
          'btn.click();',
          'console.log("anonymous not removed:", count);',
          '',
          'const named = () => { count += 10; };',
          'btn.addEventListener("click", named);',
          'btn.removeEventListener("click", named);',
          'btn.click();',
          'console.log("named removed:", count);',
          '',
          'const fn = () => { count += 100; };',
          'btn.addEventListener("click", fn, { capture: true });',
          'btn.removeEventListener("click", fn);',
          'btn.click();',
          'console.log("capture mismatch, still fires:", count);',
        ].join('\n'),
        output: 'anonymous not removed: 1\nnamed removed: 2\ncapture mismatch, still fires: 103',
        caption: 'A different function object, or a mismatched capture flag, removes nothing.',
        needsDom: true,
        html: FIXTURE,
      },
    ],
    caveats: [
      'Needs the identical function reference.',
      '`.bind()` produces a new function each call.',
      'The `capture` flag must match.',
      'Fails silently — no return value, no error.',
    ],
    commonMistakes: ['Calling `.bind(this)` inline in the removal.', 'Forgetting the `capture` flag.'],
    relatedEntries: ['ref-events-addeventlistener', 'ref-function-bind'],
    lessonId: 'l-m19-05',
  },

  {
    ...V,
    id: 'ref-events-target',
    slug: 'event-target',
    name: 'Event.target',
    aliases: ['event.target', 'currentTarget', 'event delegation', 'which element was clicked'],
    topicIds: ['events'],
    mutates: false,
    syntax: 'event.target\nevent.currentTarget',
    summary: '`target` is the deepest element where the event originated. `currentTarget` is the element whose listener is currently running.',
    parameters: [],
    returns: 'An `EventTarget`, usually an `Element`. `currentTarget` becomes `null` once dispatch finishes.',
    description: [
      'They are the same for a listener attached directly to the element that was clicked, and differ whenever the event has propagated — which is exactly the case delegation depends on.',
      'In a delegated handler neither is used raw. `currentTarget` is always the container, which says nothing about which row was hit; `target` may be an icon or a `<span>` nested inside the control. The correct bridge is `event.target.closest(selector)`, paired with a `container.contains(match)` guard.',
      '`currentTarget` is only valid **during** dispatch. Reading it after an `await`, inside a `setTimeout`, or in a promise callback gives `null`, because the browser clears it when dispatch ends. Capture what you need synchronously.',
      'Inside a non-arrow listener, `this` equals `currentTarget`. An arrow function has no such binding, so `currentTarget` is the explicit form that works either way.',
      '`relatedTarget` carries the element being left or entered for `mouseover`/`mouseout` and `focusin`/`focusout`. `composedPath()` returns the full propagation path, including nodes inside a shadow root that `target` deliberately hides.',
    ],
    examples: [
      {
        code: [
          'const list = document.querySelector("#list");',
          'const span = document.querySelector("#list span");',
          '',
          'list.addEventListener("click", (event) => {',
          '  console.log("target:", event.target.tagName);',
          '  console.log("currentTarget:", event.currentTarget.tagName);',
          '',
          '  const row = event.target.closest("[data-id]");',
          '  console.log("resolved row:", row && row.dataset.id);',
          '  console.log("inside container:", list.contains(row));',
          '});',
          '',
          'span.click();',
        ].join('\n'),
        output: 'target: SPAN\ncurrentTarget: UL\nresolved row: 1\ninside container: true',
        caption: 'The click landed on the span; closest resolved it to the row.',
        needsDom: true,
        html: FIXTURE,
      },
    ],
    caveats: [
      '`currentTarget` is `null` after dispatch ends.',
      'Raw `target` can be a nested element you did not expect.',
      '`target` is retargeted at shadow boundaries — use `composedPath()`.',
    ],
    commonMistakes: ['Using `currentTarget` in a delegated handler.', 'Reading `currentTarget` after an `await`.'],
    relatedEntries: ['ref-dom-closest', 'ref-events-addeventlistener', 'ref-dom-contains'],
    lessonId: 'l-m19-02',
  },

  {
    ...V,
    id: 'ref-events-preventdefault',
    slug: 'event-preventdefault',
    name: 'Event.preventDefault()',
    aliases: ['preventDefault', 'stop form submit', 'stop link navigation', 'cancel event'],
    topicIds: ['events', 'forms'],
    mutates: true,
    syntax: 'event.preventDefault()',
    summary: 'Cancels the browser\'s built-in action for the event — navigation, form submission, checkbox toggling — while letting the event continue to propagate.',
    parameters: [],
    returns: '`undefined`.',
    description: [
      'It cancels the **default action** only. Propagation is unaffected: ancestor listeners still run and can see `event.defaultPrevented`.',
      'It works only on **cancelable** events. `event.cancelable` reports whether it will have any effect; `scroll` and `focus`, for instance, are not cancelable.',
      'It is ignored in a **passive** listener, with a console warning. Because browsers default `wheel` and `touchstart` on the document to passive, a scroll-blocking handler must opt out with `{ passive: false }`.',
      'It must be called **synchronously** during dispatch. A `preventDefault()` after an `await` is too late — the browser has already decided. In an async submit handler, call it as the first statement.',
      'For a form, cancelling the submit event is what enables client-side handling — but validation performed there is a user-experience feature, never a security control. The server must revalidate.',
    ],
    examples: [
      {
        code: [
          'const form = document.querySelector("#f");',
          'let submitted = 0;',
          '',
          'form.addEventListener("submit", (event) => {',
          '  event.preventDefault();',
          '  submitted += 1;',
          '  console.log("cancelable:", event.cancelable);',
          '  console.log("defaultPrevented:", event.defaultPrevented);',
          '});',
          '',
          'form.dispatchEvent(new Event("submit", { cancelable: true }));',
          'console.log("handled without navigating:", submitted);',
          '',
          'const notCancelable = new Event("custom", { cancelable: false });',
          'notCancelable.preventDefault();',
          'console.log("ignored:", notCancelable.defaultPrevented);',
        ].join('\n'),
        output: 'cancelable: true\ndefaultPrevented: true\nhandled without navigating: 1\nignored: false',
        caption: 'On a non-cancelable event the call is silently ignored.',
        needsDom: true,
        html: FIXTURE,
      },
    ],
    caveats: [
      'Does not stop propagation — that is `stopPropagation()`.',
      'Silently ignored on non-cancelable events and in passive listeners.',
      'Must be called before any `await` in the handler.',
    ],
    commonMistakes: ['Expecting it to stop the event reaching ancestors.', 'Calling it after an `await`.'],
    relatedEntries: ['ref-events-stoppropagation', 'ref-form-checkvalidity', 'ref-events-addeventlistener'],
    lessonId: 'l-m19-03',
  },

  {
    ...V,
    id: 'ref-events-stoppropagation',
    slug: 'event-stoppropagation',
    name: 'Event.stopPropagation()',
    aliases: ['stopPropagation', 'stopImmediatePropagation', 'stop bubbling', 'event bubbling'],
    topicIds: ['events'],
    mutates: true,
    syntax: 'event.stopPropagation()\nevent.stopImmediatePropagation()',
    summary: 'Stops the event travelling further through the tree. `stopImmediatePropagation()` additionally prevents other listeners on the **same** element from running.',
    parameters: [],
    returns: '`undefined`.',
    description: [
      'It stops **propagation**, not the default action. A link with only `stopPropagation()` still navigates — cancelling that needs `preventDefault()`. The two are independent and neither implies the other.',
      '`stopPropagation()` lets the remaining listeners on the current element finish; `stopImmediatePropagation()` cuts those off too, in registration order.',
      'It is **overused**. It is a local fix with global consequences: any delegated handler higher up silently stops receiving the event — analytics, a click-outside-to-close dropdown, a framework root listener. Prefer a condition in the outer handler over stopping the event at the source.',
      'Events propagate in three phases: capture (root down to target), at-target, then bubble (target back up). A capture-phase listener calling `stopPropagation()` prevents the target\'s own listeners from ever running.',
      'Some events do not bubble at all — `focus`, `blur`, `mouseenter`, `mouseleave`, and `load` on most elements. Their bubbling counterparts are `focusin` and `focusout`.',
      'Returning `false` from a jQuery handler did both `preventDefault` and `stopPropagation`. In plain DOM code it does neither, except inside inline `on*` attributes where it cancels the default.',
    ],
    examples: [
      {
        code: [
          'const list = document.querySelector("#list");',
          'const row = document.querySelector("[data-id]");',
          'const order = [];',
          '',
          'list.addEventListener("click", () => order.push("ancestor-bubble"));',
          'row.addEventListener("click", (e) => { order.push("target-1"); e.stopPropagation(); });',
          'row.addEventListener("click", () => order.push("target-2"));',
          '',
          'row.click();',
          'console.log(order);',
          '',
          'order.length = 0;',
          'const row2 = document.createElement("li");',
          'row2.addEventListener("click", (e) => { order.push("a"); e.stopImmediatePropagation(); });',
          'row2.addEventListener("click", () => order.push("b"));',
          'row2.click();',
          'console.log(order);',
        ].join('\n'),
        output: '["target-1", "target-2"]\n["a"]',
        caption: 'stopPropagation lets siblings finish; stopImmediatePropagation does not.',
        needsDom: true,
        html: FIXTURE,
      },
    ],
    caveats: [
      'Does not cancel the default action.',
      'Silently breaks delegated handlers higher up the tree.',
      'Several common events do not bubble at all.',
    ],
    commonMistakes: ['Using it instead of a condition in the outer handler.', 'Expecting it to prevent navigation.'],
    relatedEntries: ['ref-events-preventdefault', 'ref-events-target', 'ref-events-dispatchevent'],
    lessonId: 'l-m19-03',
  },

  {
    ...V,
    id: 'ref-events-dispatchevent',
    slug: 'eventtarget-dispatchevent',
    name: 'EventTarget.dispatchEvent()',
    aliases: ['dispatchEvent', 'CustomEvent', 'trigger event', 'fire event', 'custom events'],
    topicIds: ['events', 'design-patterns'],
    mutates: false,
    syntax: 'target.dispatchEvent(event)\nnew CustomEvent(type, { detail, bubbles, cancelable, composed })',
    summary: 'Dispatches an event on a target **synchronously**, running every matching listener before the call returns.',
    parameters: [
      { name: 'event', description: 'An `Event` or `CustomEvent`. `CustomEvent` carries application data in its `detail` property.' },
    ],
    returns: '`false` if a listener called `preventDefault()` on a cancelable event, otherwise `true`.',
    description: [
      'Dispatch is **synchronous**. Every listener runs to completion before `dispatchEvent` returns, so a slow listener blocks the code that fired the event. This is the opposite of how a message queue behaves and surprises people using events as a decoupling mechanism.',
      '`bubbles` defaults to **`false`** for events you construct. A `CustomEvent` dispatched without `{ bubbles: true }` never reaches an ancestor listener — by far the most common reason a custom event "does not fire".',
      'Application data belongs in **`detail`**, the property the `CustomEvent` constructor is designed to carry. It can hold any value, including objects.',
      'Namespace custom types — `"cart:add"` rather than `"add"` — so they cannot collide with built-in events or with another feature.',
      '`composed: true` is additionally required for an event to escape a shadow root.',
      'For components with no common ancestor, `new EventTarget()` is a dependency-free event bus supporting `addEventListener` and `dispatchEvent` without being attached to the document.',
      'The tradeoff worth stating: events decouple publisher from subscriber, but make control flow implicit. Beyond a handful, "what happens when I click this?" becomes a search across the codebase.',
    ],
    examples: [
      {
        code: [
          'const list = document.querySelector("#list");',
          'const row = document.querySelector("[data-id]");',
          '',
          'list.addEventListener("cart:add", (e) => {',
          '  console.log("received:", e.detail.id, e.detail.qty);',
          '});',
          '',
          'row.dispatchEvent(new CustomEvent("cart:add", { detail: { id: 1, qty: 2 } }));',
          'console.log("without bubbles, ancestor saw nothing");',
          '',
          'row.dispatchEvent(new CustomEvent("cart:add", {',
          '  detail: { id: 1, qty: 2 },',
          '  bubbles: true,',
          '}));',
          '',
          'const bus = new EventTarget();',
          'bus.addEventListener("ping", () => console.log("bus works"));',
          'console.log(bus.dispatchEvent(new Event("ping")));',
        ].join('\n'),
        output: 'without bubbles, ancestor saw nothing\nreceived: 1 2\nbus works\ntrue',
        caption: 'bubbles defaults to false — the first dispatch never reached the list.',
        needsDom: true,
        html: FIXTURE,
      },
    ],
    caveats: [
      '`bubbles` defaults to `false`.',
      'Dispatch is synchronous — a slow listener blocks the caller.',
      '`composed: true` is needed to cross a shadow boundary.',
    ],
    commonMistakes: ['Omitting `bubbles: true`.', 'Putting data on the event object instead of in `detail`.'],
    relatedEntries: ['ref-events-addeventlistener', 'ref-events-stoppropagation'],
    lessonId: 'l-m19-06',
  },

  {
    ...F,
    id: 'ref-form-formdata',
    slug: 'formdata',
    name: 'FormData',
    aliases: ['FormData', 'read form values', 'getAll', 'form submit data', 'file upload'],
    topicIds: ['forms', 'http'],
    mutates: false,
    syntax: 'new FormData(formElement)\ndata.get(name)\ndata.getAll(name)\ndata.has(name)\ndata.append(name, value)',
    summary: 'Collects a form\'s control values by **`name`**, including checkboxes, radios and files, in a structure that can be sent directly as a `fetch` body.',
    parameters: [{ name: 'formElement', optional: true, description: 'A `<form>`. Omitted, an empty `FormData` is created for you to `append` to.' }],
    returns: 'A `FormData` object, iterable as `[name, value]` pairs.',
    description: [
      'Controls are collected by their **`name` attribute**, not their `id`. A control with no `name` is silently omitted — the most common reason a field "disappears" on submit. Disabled controls are excluded too, by specification.',
      '**An unchecked checkbox contributes nothing at all** — not `false`, not an empty string. `Object.fromEntries(new FormData(form))` therefore has no key for it, so unchecked boxes must be handled separately.',
      '`get()` returns the **first** value for a name; `getAll()` returns every value. A multi-select or a group of same-named checkboxes needs `getAll()`, and `Object.fromEntries` silently keeps only the last of them.',
      'Every value is a **string** except file inputs, which yield `File` objects. Convert numbers explicitly; `input.valueAsNumber` is better than `Number(value)` for numeric fields because it gives `NaN` for empty rather than `0`.',
      'It can be passed straight to `fetch` as a body, which sets the multipart content type and boundary automatically. For a JSON API, convert to an object and `JSON.stringify` instead — but note that loses files.',
      '`new URLSearchParams(formData)` converts to a URL-encoded body, which is the right shape for a traditional form POST.',
    ],
    examples: [
      {
        code: [
          'const form = document.querySelector("#f");',
          'const data = new FormData(form);',
          '',
          'console.log(data.get("q"));',
          'console.log(data.get("tag"), data.getAll("tag"));',
          'console.log(data.has("agree"));',
          '',
          'console.log(Object.fromEntries(data));',
          '',
          'const noName = document.createElement("input");',
          'noName.value = "invisible";',
          'form.append(noName);',
          'console.log([...new FormData(form).keys()]);',
        ].join('\n'),
        output: 'start\na ["a", "b"]\nfalse\n{q: "start", tag: "b", email: ""}\n["q", "tag", "tag", "email"]',
        caption: 'fromEntries kept only the last tag; the unchecked box and unnamed input are absent.',
        needsDom: true,
        html: FIXTURE,
      },
    ],
    caveats: [
      'Collects by `name`, never `id`; unnamed and disabled controls are omitted.',
      'Unchecked checkboxes contribute nothing, not `false`.',
      '`Object.fromEntries` loses repeated names — use `getAll()`.',
      'All values are strings except files.',
    ],
    commonMistakes: ['Reading values by `id`.', 'Expecting an unchecked checkbox to appear as `false`.'],
    relatedEntries: ['ref-form-value', 'ref-object-fromentries'],
    lessonId: 'l-m20-03',
  },

  {
    ...F,
    id: 'ref-form-value',
    slug: 'htmlinputelement-value',
    name: 'HTMLInputElement.value',
    aliases: ['input value', 'checked', 'valueAsNumber', 'read input', 'form control value'],
    topicIds: ['forms'],
    mutates: true,
    syntax: 'input.value\ninput.value = string\ninput.checked\ninput.valueAsNumber',
    summary: 'The control\'s **current** value — always a string, even for `type="number"` and `type="date"`.',
    parameters: [],
    returns: 'A string. `checked` is a boolean; `valueAsNumber` is a number or `NaN`.',
    description: [
      '`value` is a **string for every input type**. `type="number"` constrains what can be typed and shows a spinner, but does not change the property\'s type. Adding two of them concatenates: `"1" + "2"` is `"12"`.',
      '`valueAsNumber` is the purpose-built numeric reader for `number` and `date` inputs. It returns `NaN` for an empty or invalid field, which is a cleaner signal than `Number("")` returning `0`.',
      'The **property is the current state; the attribute is the default.** After a user types, `input.value` is what they typed while `getAttribute("value")` is still the original — and a form reset restores the attribute. The same split applies to `checked` and `selected`.',
      'For checkboxes and radios, read `checked` (a boolean), not `value` — `value` is the string sent when the control is checked, and it is the same whether or not it is.',
      'Setting `value` programmatically does **not** fire `input` or `change` events. Frameworks and validation listening for those will not react; dispatch the event manually if that matters.',
      'For a `<select multiple>`, `value` is only the first selected option — use `[...select.selectedOptions].map((o) => o.value)`.',
    ],
    examples: [
      {
        code: [
          'const q = document.querySelector("[name=q]");',
          'const agree = document.querySelector("[name=agree]");',
          '',
          'console.log(q.value, typeof q.value);',
          '',
          'q.value = "typed";',
          'console.log(q.value, q.getAttribute("value"));',
          '',
          'console.log(agree.checked, agree.value);',
          'agree.checked = true;',
          'console.log(agree.checked);',
          '',
          'const num = document.createElement("input");',
          'num.type = "number";',
          'console.log(JSON.stringify(num.value), num.valueAsNumber);',
          'num.value = "5";',
          'console.log(typeof num.value, num.valueAsNumber + 1);',
        ].join('\n'),
        output: 'start string\ntyped start\nfalse on\ntrue\n"" NaN\nstring 6',
        caption: 'The attribute keeps the default; an empty number input is NaN, not 0.',
        needsDom: true,
        html: FIXTURE,
      },
    ],
    caveats: [
      'Always a string, including for `type="number"`.',
      'Setting it does not fire `input`/`change`.',
      'For checkboxes read `checked`, not `value`.',
      '`select.value` on a multi-select gives only the first selection.',
    ],
    commonMistakes: ['Adding two number-input values and getting concatenation.', 'Reading state with `getAttribute("value")`.'],
    relatedEntries: ['ref-form-formdata', 'ref-dom-getattribute', 'ref-form-checkvalidity'],
    lessonId: 'l-m20-01',
  },

  {
    ...F,
    id: 'ref-form-checkvalidity',
    slug: 'htmlformelement-checkvalidity',
    name: 'HTMLFormElement.checkValidity()',
    aliases: ['checkValidity', 'reportValidity', 'setCustomValidity', 'validity', 'form validation', 'constraint validation'],
    topicIds: ['forms', 'security'],
    mutates: false,
    syntax: 'form.checkValidity()\nform.reportValidity()\ninput.setCustomValidity(message)\ninput.validity',
    summary: 'The Constraint Validation API. `checkValidity()` tests silently, `reportValidity()` tests **and shows** the browser\'s messages, and `setCustomValidity()` adds your own rules.',
    parameters: [{ name: 'message', description: 'For `setCustomValidity`: the error text. An **empty string clears** the custom error and marks the field valid.' }],
    returns: 'Booleans from `checkValidity()`/`reportValidity()`. `validity` is a `ValidityState` object.',
    description: [
      'The difference between the two check methods is user-visible feedback: `checkValidity()` returns a boolean and shows nothing, while `reportValidity()` also focuses the first invalid control and displays its message. Use `reportValidity()` when the user pressed submit.',
      '`setCustomValidity(message)` marks a control invalid with your text. Crucially, you must call `setCustomValidity("")` to **clear** it — a control with a non-empty custom message stays invalid forever, which is the classic bug with this API.',
      '`input.validity` is a `ValidityState` reporting exactly which constraint failed: `valueMissing`, `typeMismatch`, `patternMismatch`, `tooShort`, `rangeUnderflow`, `badInput`, `customError`, and the summary `valid`. Branching on these gives better messages than one generic string.',
      'Built-in constraints come from the markup: `required`, `type="email"`, `pattern`, `min`/`max`, `minlength`/`maxlength`. Using them gets accessible, localised messages and keyboard behaviour for free.',
      'The `:invalid` CSS pseudo-class matches immediately, including before the user has typed anything — which is why styling usually keys off `:user-invalid` instead.',
      'None of this is security. Every constraint here runs on the user\'s machine and can be bypassed by sending the request directly. **The server must revalidate everything.**',
    ],
    examples: [
      {
        code: [
          'const form = document.querySelector("#f");',
          'const email = document.querySelector("[name=email]");',
          '',
          'console.log(form.checkValidity());',
          'console.log(email.validity.valueMissing, email.validity.typeMismatch);',
          '',
          'email.value = "not-an-email";',
          'console.log(email.validity.valueMissing, email.validity.typeMismatch);',
          '',
          'email.value = "a@b.com";',
          'console.log(email.validity.valid, form.checkValidity());',
          '',
          'email.setCustomValidity("Use a work address");',
          'console.log(email.validity.customError, email.validationMessage);',
          '',
          'email.setCustomValidity("");',
          'console.log(email.validity.valid);',
        ].join('\n'),
        output: 'false\ntrue false\nfalse true\ntrue true\ntrue Use a work address\ntrue',
        caption: 'ValidityState says which rule failed; an empty string clears the custom error.',
        needsDom: true,
        html: FIXTURE,
      },
    ],
    caveats: [
      '`setCustomValidity` must be cleared with `""` or the field stays invalid.',
      '`checkValidity()` shows nothing — use `reportValidity()` for feedback.',
      '`:invalid` matches before the user interacts; prefer `:user-invalid`.',
      'Client validation is UX only. The server must revalidate.',
    ],
    commonMistakes: ['Never clearing a custom validity message.', 'Treating client-side validation as a security control.'],
    relatedEntries: ['ref-form-value', 'ref-form-formdata', 'ref-events-preventdefault'],
    lessonId: 'l-m20-04',
  },
];
