import { REFERENCE_CATEGORY as C, REFERENCE_ENV as E } from '../schema/types.js';

/**
 * Globals and conversions that the coverage review found missing.
 *
 * These are the APIs the curriculum, challenges and examples lean on constantly
 * — `console` above all — plus the conversion and encoding functions that other
 * entries in this reference point at.
 */

const G = { category: C.LANGUAGE, environment: E.ECMASCRIPT, mutates: false };
const W = { category: C.WEB_APIS, environment: E.WEB_API, mutates: false };

export default [
  {
    ...W,
    id: 'ref-console-log',
    slug: 'console-log',
    name: 'console.log()',
    aliases: ['console', 'console.error', 'console.warn', 'console.table', 'console.time', 'console.group', 'print', 'debug output'],
    topicIds: ['debugging', 'js-runtime'],
    syntax: 'console.log(...values)\nconsole.error(msg)\nconsole.table(data)\nconsole.time(label) / console.timeEnd(label)',
    summary: 'Writes values to the console. Multiple arguments are printed space-separated, and objects are shown as inspectable structures rather than strings.',
    parameters: [{ name: 'values', description: 'Any number of values of any type. A leading string may contain format specifiers such as `%s`, `%d`, `%o` and `%c`.' }],
    returns: '`undefined`.',
    description: [
      'It accepts **multiple arguments** and separates them with a space, so `console.log("count:", n)` is better than string concatenation — the value keeps its type and stays inspectable.',
      '`console.error()` and `console.warn()` write to stderr in Node and are filterable by level in browser devtools; `console.error` also captures a stack trace. Use them rather than prefixing `log` output with "ERROR".',
      '**Logged objects are live references in browser devtools.** Expanding an object logged earlier shows its state **at expansion time**, not at log time — the notorious "the log shows the wrong value" confusion. Log a snapshot (`structuredClone(obj)`, or `JSON.stringify`) when the object will change.',
      'The useful specialised methods: `console.table()` renders an array of objects as a real table, `console.time(label)`/`timeEnd(label)` measure elapsed time, `console.group()`/`groupEnd()` nest related output, `console.count()` tallies calls, and `console.assert(cond, msg)` logs only when the condition fails.',
      '`console.trace()` prints a stack trace without throwing — often faster than a breakpoint for answering "who called this?".',
      'It is a **host API**, not part of ECMAScript: the browser, Node and this project\'s sandbox each supply their own, and formatting differs between them. Nothing about its output format is standardised.',
      'Left in production it leaks internal state to anyone who opens devtools, and logging in a hot loop is genuinely slow. Strip it from production builds.',
    ],
    examples: [
      {
        code: [
          'const user = { id: 1, name: "Ada" };',
          '',
          'console.log("user:", user, "active:", true);',
          'console.log([1, 2, 3]);',
          'console.log({ nested: { deep: true } });',
          '',
          'console.group("details");',
          'console.log("nested");',
          'console.groupEnd();',
        ].join('\n'),
        output: 'user: {id: 1, name: "Ada"} active: true\n[1, 2, 3]\n{nested: {deep: true}}\ndetails\nnested',
        caption: 'Multiple arguments keep their types — no concatenation needed.',
      },
    ],
    caveats: [
      'A host API, not ECMAScript — output format varies by environment.',
      'Browser devtools show logged objects live, not as a snapshot.',
      'Slow in hot loops; strip from production builds.',
      '`console.log` is not a substitute for a debugger when you need to inspect a call stack.',
      'This project\'s sandbox implements a subset — `count` and `assert` produce no output there.',
    ],
    commonMistakes: ['Concatenating values into one string and losing their structure.', 'Trusting an expanded object to show its state at log time.'],
    relatedEntries: ['ref-structuredclone', 'ref-json-stringify'],
    lessonId: 'l-m22-05',
  },

  {
    ...G,
    id: 'ref-boolean',
    slug: 'boolean-function',
    name: 'Boolean()',
    aliases: ['Boolean', 'truthy', 'falsy', 'to boolean', 'double negation', 'coerce boolean'],
    topicIds: ['booleans', 'coercion', 'types'],
    syntax: 'Boolean(value)\n!!value',
    summary: 'Converts any value to `true` or `false` using the truthiness rules. Exactly **eight** values are falsy; everything else is truthy.',
    parameters: [{ name: 'value', description: 'Any value.' }],
    returns: 'A primitive boolean.',
    description: [
      'The complete list of **falsy** values is short and worth memorising: `false`, `0`, `-0`, `0n`, `""`, `null`, `undefined` and `NaN`. **Everything else is truthy**, including `[]`, `{}`, `"0"`, `"false"` and every function.',
      '`[]` and `{}` being truthy is the most common surprise. To test whether an array is empty use `arr.length === 0`; for an object use `Object.keys(obj).length === 0`.',
      '`"0"` and `"false"` are non-empty strings and therefore truthy — which is why a `data-*` attribute or a `localStorage` value of `"false"` passes a naive `if` check. Compare explicitly: `value === "true"`.',
      '`!!value` is the terse idiom and does exactly the same conversion; `Boolean(value)` is clearer and is what to use with `filter`.',
      '`arr.filter(Boolean)` removes every falsy element in one step — but note it also removes `0` and `""`, which are often legitimate data.',
      'Never use `new Boolean(false)`: the wrapper is an **object**, and every object is truthy, so `if (new Boolean(false))` runs the branch.',
    ],
    examples: [
      {
        code: [
          'const falsy = [false, 0, -0, 0n, "", null, undefined, NaN];',
          'console.log(falsy.every((v) => Boolean(v) === false));',
          '',
          'console.log(Boolean([]), Boolean({}), Boolean("0"), Boolean("false"));',
          '',
          'console.log([0, 1, "", "a", null].filter(Boolean));',
          '',
          'console.log([].length === 0, Object.keys({}).length === 0);',
          '',
          'console.log(Boolean(new Boolean(false)));',
        ].join('\n'),
        output: 'true\ntrue true true true\n[1, "a"]\ntrue true\ntrue',
        caption: 'Empty array, empty object and the string "false" are all truthy.',
      },
    ],
    caveats: [
      '`[]`, `{}`, `"0"` and `"false"` are all truthy.',
      '`filter(Boolean)` also discards `0` and `""`.',
      '`new Boolean(false)` is a truthy object.',
    ],
    commonMistakes: ['Testing an array for emptiness with `if (arr)`.', 'Trusting a stored string `"false"` in a condition.'],
    relatedEntries: ['ref-syntax-nullish', 'ref-number-ctor', 'ref-array-filter'],
    lessonId: 'l-m03-03',
  },

  {
    ...G,
    id: 'ref-bigint',
    slug: 'bigint',
    name: 'BigInt',
    aliases: ['BigInt', 'big integer', 'large numbers', '123n', 'arbitrary precision'],
    topicIds: ['numbers', 'types'],
    syntax: 'BigInt(value)\n123n',
    summary: 'An integer type with **arbitrary precision**, for values beyond the safe range of a regular number. Written with an `n` suffix.',
    parameters: [{ name: 'value', description: 'An integer number, or a string of digits. A fractional number throws.' }],
    returns: 'A `BigInt` primitive. `typeof` reports `"bigint"`.',
    throws: '`RangeError` when converting a non-integer number; `TypeError` when mixed with a regular number in arithmetic.',
    description: [
      'Regular numbers are doubles and lose integer precision above 2^53 − 1. `BigInt` is exact at any size, which makes it the correct type for 64-bit database ids, snowflake ids, and cryptographic or financial integer arithmetic.',
      '**It cannot be mixed with `Number` in arithmetic** — `1n + 1` throws a `TypeError`. That is deliberate: an implicit conversion would silently reintroduce the precision loss the type exists to prevent. Convert explicitly, and accept that `Number(bigint)` may lose precision.',
      'Comparison is more permissive than arithmetic: `1n == 1` is `true` (loose equality converts) while `1n === 1` is `false` (different types). Relational operators like `<` also work across the two.',
      'Division **truncates** towards zero, because there is no fractional part: `7n / 2n` is `3n`.',
      '`JSON.stringify` **throws** on a `BigInt` — JSON has no representation for it. Convert to a string before serialising, and parse back on the other side.',
      '`Math` methods do not accept it: `Math.max(1n, 2n)` throws.',
      'It is slower than `Number` arithmetic, so use it only where the range genuinely demands it.',
    ],
    examples: [
      {
        code: [
          'const big = 9007199254740993n;',
          'console.log(big, typeof big);',
          'console.log(Number(big));',
          '',
          'console.log(2n ** 64n);',
          'console.log(7n / 2n);',
          '',
          'console.log(1n == 1, 1n === 1, 1n < 2);',
          '',
          'try { console.log(1n + 1); } catch (err) { console.log(err.constructor.name); }',
          'try { JSON.stringify({ v: 1n }); } catch (err) { console.log(err.constructor.name); }',
        ].join('\n'),
        output: '9007199254740993n bigint\n9007199254740992\n18446744073709551616n\n3n\ntrue false true\nTypeError\nTypeError',
        caption: 'Converting to Number lost the last digit — which is the whole reason BigInt exists.',
      },
    ],
    caveats: [
      'Cannot be mixed with `Number` in arithmetic — that throws.',
      '`JSON.stringify` throws on it.',
      'Division truncates.',
      '`Math` methods reject it.',
      'Slower than regular number arithmetic.',
    ],
    commonMistakes: ['Mixing `BigInt` and `Number` in a calculation.', 'Serialising one to JSON without converting first.'],
    relatedEntries: ['ref-number-maxsafeinteger', 'ref-number-issafeinteger', 'ref-json-stringify'],
    lessonId: 'l-m06-01',
  },

  {
    ...G,
    id: 'ref-globalthis',
    slug: 'globalthis',
    name: 'globalThis',
    aliases: ['globalThis', 'global object', 'window vs global', 'global scope'],
    topicIds: ['js-runtime', 'scope'],
    syntax: 'globalThis\nglobalThis.myValue = 1',
    summary: 'The portable reference to the global object — `window` in a browser, `global` in Node, `self` in a worker.',
    parameters: [],
    returns: 'The global object for the current realm.',
    description: [
      'Before it existed, portable code had to sniff for `window`, then `global`, then `self`. `globalThis` is the one name that works everywhere, including workers and edge runtimes.',
      'In a **module** or under strict mode, top-level `this` is `undefined`, not the global object — so `this.x` at module top level does not reach a global. In a classic non-strict script, top-level `this` **is** the global object.',
      '`var` and function declarations at the top level of a **classic script** become properties of the global object. `let`, `const`, `class`, and anything inside a **module**, do not — module scope is its own scope, which is a large part of why modules avoid global collisions.',
      'Deliberately writing to it is occasionally justified — a debugging handle, a polyfill, a singleton shared across independently-loaded bundles — but it is global mutable state, and every caveat about that applies.',
      'Accidentally creating globals is the more common problem: assigning to an undeclared variable in sloppy mode creates one silently. Strict mode turns that into a `ReferenceError`, which is one of the strongest arguments for it.',
      'Each realm — a page, an iframe, a worker — has its **own** global object and its own built-in constructors, which is why `instanceof Array` fails across an iframe boundary while `Array.isArray` does not.',
    ],
    examples: [
      {
        code: [
          '"use strict";',
          '',
          'console.log(typeof globalThis);',
          'console.log(globalThis === globalThis.globalThis);',
          '',
          'globalThis.__debugHandle = { version: 1 };',
          'console.log(__debugHandle.version);',
          '',
          'console.log(typeof globalThis.Array, globalThis.Array === Array);',
          '',
          'try {',
          '  undeclared = 1;',
          '} catch (err) {',
          '  console.log("strict mode blocked an accidental global:", err.constructor.name);',
          '}',
        ].join('\n'),
        output: 'object\ntrue\n1\nfunction true\nstrict mode blocked an accidental global: ReferenceError',
        caption: 'Strict mode turns an accidental global into a ReferenceError.',
      },
    ],
    caveats: [
      'Top-level `this` is `undefined` in modules and strict mode, not the global object.',
      '`let`/`const` never become global-object properties.',
      'Each realm has its own global and its own constructors.',
    ],
    commonMistakes: ['Using `window` in code that must also run in Node or a worker.', 'Relying on top-level `this` being the global object.'],
    relatedEntries: ['ref-array-isarray', 'ref-syntax-import'],
    lessonId: 'l-m10-05',
  },

  {
    ...G,
    id: 'ref-encodeuricomponent',
    slug: 'encodeuricomponent',
    name: 'encodeURIComponent()',
    aliases: ['encodeURIComponent', 'decodeURIComponent', 'encodeURI', 'url encode', 'percent encoding', 'escape url'],
    topicIds: ['strings', 'http', 'security'],
    syntax: 'encodeURIComponent(str)\ndecodeURIComponent(str)\nencodeURI(str)',
    summary: 'Percent-encodes a string so it can safely appear **inside** a URL component — a query value, a path segment, a fragment.',
    parameters: [{ name: 'str', description: 'The component value to encode. Non-strings are converted first.' }],
    returns: 'The percent-encoded string.',
    throws: '`URIError` for a lone surrogate, and for malformed input to `decodeURIComponent`.',
    description: [
      'The distinction from `encodeURI` matters. `encodeURIComponent` escapes the URL **delimiters** — `&`, `=`, `?`, `#`, `/`, `+` — because it is meant for a single value inside a URL. `encodeURI` leaves them alone, because it is meant for a whole URL that still needs its structure.',
      'Using `encodeURI` where `encodeURIComponent` was needed is a real bug: a value containing `&` or `=` then breaks out of its parameter and injects extra ones.',
      'It does **not** escape `!`, `\'`, `(`, `)` or `*`, which are legal in a URI but problematic in some contexts — a further `replace` is occasionally needed for strict RFC 3986 conformance.',
      'In practice, prefer **`URLSearchParams`**, which encodes every value correctly and handles repeated keys, over building a query string by hand. Reach for `encodeURIComponent` directly mainly for path segments, where `URLSearchParams` does not apply.',
      'Percent-encoding is **not** an escaping mechanism for HTML. It does nothing about XSS: a `javascript:` URL survives encoding of its component parts, so URL validation still needs a scheme allowlist via `new URL()`.',
      '`decodeURIComponent` reverses it, and throws a `URIError` on malformed sequences such as a stray `%` — so decoding untrusted input belongs in a `try`/`catch`.',
    ],
    examples: [
      {
        code: [
          'const value = "a&b=c d/e";',
          '',
          'console.log(encodeURIComponent(value));',
          'console.log(encodeURI(value));',
          '',
          'console.log(`/search?q=${encodeURIComponent(value)}`);',
          'console.log(new URLSearchParams({ q: value }).toString());',
          '',
          'console.log(decodeURIComponent(encodeURIComponent(value)) === value);',
          '',
          'try { decodeURIComponent("%E0%A4%A"); }',
          'catch (err) { console.log(err.constructor.name); }',
        ].join('\n'),
        output: 'a%26b%3Dc%20d%2Fe\na&b=c%20d/e\n/search?q=a%26b%3Dc%20d%2Fe\nq=a%26b%3Dc+d%2Fe\ntrue\nURIError',
        caption: 'encodeURI left & and = intact — which would have injected extra parameters.',
      },
    ],
    caveats: [
      '`encodeURI` does not escape URL delimiters — wrong for a single value.',
      'Leaves `!`, `\'`, `(`, `)`, `*` unescaped.',
      'Not an HTML or XSS defence.',
      '`decodeURIComponent` throws on malformed input.',
    ],
    commonMistakes: ['Using `encodeURI` for a query parameter value.', 'Treating percent-encoding as sanitisation.'],
    relatedEntries: ['ref-url-searchparams', 'ref-url', 'ref-dom-textcontent'],
    lessonId: 'l-m26-01',
  },

  {
    ...W,
    id: 'ref-queuemicrotask',
    slug: 'queuemicrotask',
    name: 'queueMicrotask()',
    aliases: ['queueMicrotask', 'microtask', 'defer', 'schedule microtask'],
    topicIds: ['event-loop', 'async-foundations'],
    syntax: 'queueMicrotask(callback)',
    summary: 'Schedules a callback on the **microtask queue** — after the current synchronous work, and before any timer or rendering.',
    parameters: [{ name: 'callback', description: 'A function taking no arguments. It runs once.' }],
    returns: '`undefined`.',
    description: [
      'Microtasks run **after the current script or task completes and before the event loop takes another task**, so they always precede a `setTimeout(fn, 0)` callback and any rendering.',
      'Promise reactions use the **same queue**. `queueMicrotask(fn)` and `Promise.resolve().then(fn)` are ordered together in FIFO — there is no separate, higher-priority "promise queue".',
      'It is the direct way to defer work without the allocation of a promise, and unlike the promise form it does **not** swallow errors: a throw inside surfaces as an uncaught error rather than a silent rejection.',
      'The whole queue is drained before the loop continues, and a microtask may enqueue more. A microtask that recursively enqueues another **starves rendering and input indefinitely** — the page freezes with no error, because the loop can never reach the rendering step. A recursive `setTimeout` does not have this problem, since each is a separate task.',
      'Use it when ordering matters — batching state changes so observers see a consistent view, or deferring a callback so it cannot run synchronously during a constructor. Use `setTimeout` when you actually want to yield to rendering.',
    ],
    examples: [
      {
        code: [
          'const order = [];',
          '',
          'setTimeout(() => order.push("timeout"), 0);',
          'queueMicrotask(() => order.push("microtask 1"));',
          'Promise.resolve().then(() => order.push("promise"));',
          'queueMicrotask(() => order.push("microtask 2"));',
          'order.push("sync");',
          '',
          'setTimeout(() => console.log(order), 1);',
        ].join('\n'),
        output: '["sync", "microtask 1", "promise", "microtask 2", "timeout"]',
        caption: 'queueMicrotask and promise reactions share one FIFO queue.',
      },
    ],
    caveats: [
      'Recursive enqueueing starves rendering with no error.',
      'A throw inside becomes an uncaught error, not a rejection.',
      'Runs before rendering — not a way to yield to the browser.',
    ],
    commonMistakes: ['Assuming promise callbacks outrank `queueMicrotask`.', 'Using it to yield to the UI, where `setTimeout` is needed.'],
    relatedEntries: ['ref-settimeout', 'ref-promise-then', 'ref-requestanimationframe'],
    lessonId: 'l-m33-02',
  },

  {
    ...W,
    id: 'ref-performance-now',
    slug: 'performance-now',
    name: 'performance.now()',
    aliases: ['performance.now', 'measure time', 'high resolution time', 'benchmark', 'elapsed time'],
    topicIds: ['performance', 'dates'],
    syntax: 'performance.now()\nperformance.mark(name)\nperformance.measure(name, start, end)',
    summary: 'Returns a **monotonic**, sub-millisecond timestamp measured from page load — the correct clock for measuring durations.',
    parameters: [],
    returns: 'A `DOMHighResTimeStamp` in milliseconds, with a fractional part.',
    description: [
      'It is **monotonic**: it only ever moves forward, and is unaffected by the system clock being adjusted, by NTP corrections, or by daylight saving. `Date.now()` has none of those guarantees, so a duration measured with it can come out negative.',
      'Its origin is the page load (`performance.timeOrigin`), not the Unix epoch, so the absolute value is meaningless — only differences matter.',
      'Resolution is deliberately **coarsened** by browsers as a defence against timing and speculative-execution attacks, often to around 100 microseconds and sometimes worse without cross-origin isolation. Do not treat it as a precise instrument.',
      'For anything but the crudest measurement, run the operation many times and average — a single measurement is dominated by JIT warm-up, garbage collection and scheduling noise.',
      '`performance.mark()` and `performance.measure()` record named entries that appear in the DevTools Performance panel timeline, which is far more useful than console timing for anything nontrivial.',
      'Micro-benchmarks mislead in general: engines optimise a tight benchmark loop in ways they will not optimise a real call site. Profile the actual application before acting on a number.',
    ],
    examples: [
      {
        code: [
          'const start = performance.now();',
          '',
          'let total = 0;',
          'for (let i = 0; i < 100000; i++) total += i;',
          '',
          'const elapsed = performance.now() - start;',
          '',
          'console.log(typeof elapsed, elapsed >= 0);',
          'console.log(Number.isFinite(elapsed));',
          'console.log(performance.now() >= start);',
          'console.log(total);',
        ].join('\n'),
        output: 'number true\ntrue\ntrue\n4999950000',
        caption: 'Assert the properties, not the duration — the elapsed time is not reproducible.',
      },
    ],
    caveats: [
      'The origin is page load, not the epoch — only differences are meaningful.',
      'Resolution is deliberately coarsened for security.',
      'A single measurement is dominated by noise.',
      'Micro-benchmarks do not predict real-world performance.',
    ],
    commonMistakes: ['Measuring durations with `Date.now()` across a clock adjustment.', 'Drawing conclusions from one unrepeated measurement.'],
    relatedEntries: ['ref-date-now', 'ref-requestanimationframe'],
    lessonId: 'l-m43-01',
  },

  {
    ...W,
    id: 'ref-crypto-randomuuid',
    slug: 'crypto-randomuuid',
    name: 'crypto.randomUUID()',
    aliases: ['randomUUID', 'crypto.getRandomValues', 'secure random', 'generate id', 'uuid'],
    topicIds: ['security', 'web-apis'],
    syntax: 'crypto.randomUUID()\ncrypto.getRandomValues(typedArray)',
    summary: 'Generates a cryptographically secure random UUID v4. `getRandomValues()` fills a typed array with secure random bytes.',
    parameters: [{ name: 'typedArray', description: 'For `getRandomValues`: an integer typed array to fill in place. At most 65,536 bytes per call.' }],
    returns: '`randomUUID()` returns a 36-character UUID string. `getRandomValues()` returns the **same** array, now filled.',
    throws: '`QuotaExceededError` if the array exceeds 65,536 bytes. `TypeError` for a non-integer typed array.',
    description: [
      '**`Math.random()` is not cryptographically secure** and must never be used for tokens, session identifiers, password-reset links, or anything an attacker should not be able to predict. These are the correct APIs for that.',
      '`randomUUID()` produces a version 4 UUID with 122 bits of randomness — enough that collisions are not a practical concern. It is the right default for client-generated ids, idempotency keys and correlation ids.',
      '`getRandomValues()` fills the array **in place** and also returns it, so both `crypto.getRandomValues(arr)` and `const filled = crypto.getRandomValues(arr)` work.',
      'Both require a **secure context** — HTTPS or localhost. On plain HTTP, `crypto.randomUUID` is `undefined`, so a feature check is worth having.',
      'Generating an id on the client does not make it trustworthy. A client-supplied id must still be validated server-side; the client cannot be the authority on uniqueness or authorisation.',
      'The wider `crypto.subtle` API covers hashing, signing and encryption — and the standing advice there is to use vetted primitives rather than composing your own scheme.',
    ],
    examples: [
      {
        code: [
          'const id = crypto.randomUUID();',
          '',
          'console.log(typeof id, id.length);',
          'console.log(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(id));',
          'console.log(crypto.randomUUID() !== crypto.randomUUID());',
          '',
          'const bytes = new Uint8Array(8);',
          'const same = crypto.getRandomValues(bytes);',
          'console.log(same === bytes, bytes.length);',
          'console.log(bytes.every((b) => b >= 0 && b <= 255));',
        ].join('\n'),
        output: 'string 36\ntrue\ntrue\ntrue 8\ntrue',
        caption: 'Assert the shape, not the values — the output is random by design.',
      },
    ],
    caveats: [
      'Requires a secure context; `undefined` on plain HTTP.',
      '`getRandomValues` is capped at 65,536 bytes per call.',
      'A client-generated id is still untrusted input to the server.',
      '`Math.random()` is never an acceptable substitute here.',
    ],
    commonMistakes: ['Generating security tokens with `Math.random()`.', 'Trusting a client-supplied id without server validation.'],
    relatedEntries: ['ref-math-random', 'ref-storage-local'],
    lessonId: 'l-m44-02',
  },
];
