import { REFERENCE_CATEGORY as C, REFERENCE_ENV as E } from '../schema/types.js';

/**
 * Number and Math reference.
 *
 * Every JavaScript number is an IEEE-754 double, and most of the surprises in
 * this category trace back to that one fact: `0.1 + 0.2`, the safe-integer
 * ceiling, and why `toFixed` rounds the way it does.
 *
 * `Math` is deliberately not exhaustive here — the trigonometric and logarithmic
 * functions are well covered by their own signatures and add nothing a reference
 * reader needs explained.
 */

const N = { category: C.NUMBER, environment: E.ECMASCRIPT, mutates: false };

export default [
  {
    ...N,
    id: 'ref-number-ctor',
    slug: 'number-function',
    name: 'Number()',
    aliases: ['number conversion', 'to number', 'string to number'],
    topicIds: ['numbers', 'coercion', 'types'],
    syntax: 'Number(value)',
    summary: 'Converts a value to a number, returning `NaN` when the whole value is not a valid numeric literal.',
    parameters: [{ name: 'value', description: 'Any value. Strings are parsed **completely**; trailing junk produces `NaN`.' }],
    returns: 'A number, or `NaN` if the value cannot be fully converted.',
    description: [
      'The key difference from `parseInt`/`parseFloat` is that `Number()` is all-or-nothing. `Number("12abc")` is `NaN`, while `parseInt("12abc")` is `12`. For validating user input that is almost always what you want.',
      'It understands the full numeric literal grammar, including hexadecimal (`"0x1f"`), binary (`"0b11"`), octal (`"0o17"`) and exponent notation (`"1e3"`).',
      'The conversions worth memorising because they surprise people: `Number("")` and `Number("   ")` are both `0`, `Number(null)` is `0`, `Number(undefined)` is `NaN`, `Number(true)` is `1`, and `Number([])` is `0` while `Number([1, 2])` is `NaN`.',
      'Because empty input converts to `0`, always check for an empty string **before** converting form values, or a blank field silently becomes zero.',
    ],
    examples: [
      {
        code: [
          'console.log(Number("42"));',
          'console.log(Number("12abc"));',
          'console.log(Number(""));',
          'console.log(Number(null));',
          'console.log(Number(undefined));',
          'console.log(Number("0x1f"));',
          'console.log(Number([]));',
        ].join('\n'),
        output: '42\nNaN\n0\n0\nNaN\n31\n0',
        caption: 'Empty string and null become 0 — the trap when validating form input.',
      },
    ],
    caveats: [
      '`Number("")` is `0`, not `NaN` — check for empty input separately.',
      '`Number(null)` is `0` but `Number(undefined)` is `NaN`.',
      'Never use `new Number()`; the wrapper object is truthy and not `===` to the primitive.',
    ],
    commonMistakes: ['Treating a blank form field as a valid `0` because `Number("")` succeeded.'],
    relatedEntries: ['ref-number-parseint', 'ref-number-parsefloat', 'ref-number-isnan', 'ref-number-isfinite'],
    lessonId: 'l-m06-02',
  },

  {
    ...N,
    id: 'ref-number-parseint',
    slug: 'parseint',
    name: 'parseInt()',
    aliases: ['parse int', 'string to integer', 'radix'],
    category: C.LANGUAGE,
    topicIds: ['numbers', 'coercion'],
    syntax: 'parseInt(string, radix)',
    summary: 'Parses an integer from the **start** of a string, stopping at the first character that is not a valid digit.',
    parameters: [
      { name: 'string', description: 'The text to parse. Leading whitespace is ignored.' },
      { name: 'radix', optional: true, description: 'The base, 2–36. **Always pass `10`** — omitting it is the source of the classic bug.' },
    ],
    returns: 'An integer, or `NaN` if no leading digits could be parsed.',
    description: [
      'Parsing is **partial and permissive**: it reads as many valid digits as it can and ignores everything after. `parseInt("12px")` is `12`, which is genuinely useful for CSS values and genuinely dangerous for validating user input.',
      'The `radix` argument is technically optional but should always be supplied. Without it the base is inferred, and a leading `0x` switches to hexadecimal — so `parseInt("0x10")` is `16`.',
      'The famous `["10","10","10"].map(parseInt)` producing `[10, NaN, 2]` is an arity accident: `map` passes the index as the second argument, which `parseInt` reads as the radix. Radix `1` is invalid (`NaN`) and radix `2` is binary (`2`).',
      'It truncates rather than rounds, and it discards the fractional part entirely: `parseInt("3.9")` is `3`.',
    ],
    examples: [
      {
        code: [
          'console.log(parseInt("42px", 10));',
          'console.log(parseInt("3.9", 10));',
          'console.log(parseInt("abc", 10));',
          'console.log(parseInt("0x10"));',
          'console.log(["10", "10", "10"].map(parseInt));',
          'console.log(["10", "10", "10"].map((s) => parseInt(s, 10)));',
        ].join('\n'),
        output: '42\n3\nNaN\n16\n[10, NaN, 2]\n[10, 10, 10]',
        caption: 'Passing parseInt directly to map lets the index become the radix.',
      },
    ],
    caveats: [
      'Silently accepts trailing junk — use `Number()` to validate.',
      'Never pass `parseInt` directly as a callback to `map`.',
      'Cannot parse numbers written with a thousands separator or a non-period decimal mark.',
    ],
    commonMistakes: ['Omitting the radix.', 'Using it to validate that a whole string is numeric.'],
    relatedEntries: ['ref-number-parsefloat', 'ref-number-ctor', 'ref-math-trunc'],
    lessonId: 'l-m03-02',
  },

  {
    ...N,
    id: 'ref-number-parsefloat',
    slug: 'parsefloat',
    name: 'parseFloat()',
    aliases: ['parse float', 'string to decimal'],
    category: C.LANGUAGE,
    topicIds: ['numbers', 'coercion'],
    syntax: 'parseFloat(string)',
    summary: 'Parses a decimal number from the start of a string, stopping at the first character that cannot be part of it.',
    parameters: [{ name: 'string', description: 'The text to parse. Leading whitespace is ignored.' }],
    returns: 'A number, or `NaN` if no leading number could be parsed.',
    description: [
      'Like `parseInt` it is partial, but it keeps the fractional part and understands exponent notation. It takes no radix argument, so it is always base 10.',
      'It recognises `"Infinity"` and returns `Infinity`, which `Number()` also does but which surprises people validating input.',
      'For "is this entire string a valid number?", use `Number()` combined with `Number.isFinite()`. `parseFloat` answers a different question: "what number does this string start with?"',
    ],
    examples: [
      {
        code: [
          'console.log(parseFloat("3.14 is pi"));',
          'console.log(parseFloat("1.5e3"));',
          'console.log(parseFloat(".5"));',
          'console.log(parseFloat("Infinity"));',
          'console.log(parseFloat("abc"));',
        ].join('\n'),
        output: '3.14\n1500\n0.5\nInfinity\nNaN',
        caption: 'Partial parsing keeps the fraction and understands exponents.',
      },
    ],
    caveats: ['Accepts trailing junk.', 'Returns `Infinity` for the string `"Infinity"`.'],
    commonMistakes: ['Using it as a validity check rather than a parser.'],
    relatedEntries: ['ref-number-parseint', 'ref-number-ctor', 'ref-number-isfinite'],
    lessonId: 'l-m03-02',
  },

  {
    ...N,
    id: 'ref-number-isnan',
    slug: 'number-isnan',
    name: 'Number.isNaN()',
    aliases: ['isNaN', 'check NaN', 'not a number'],
    topicIds: ['numbers', 'types'],
    syntax: 'Number.isNaN(value)',
    summary: 'Returns `true` only when the value is exactly the number `NaN`, with no type coercion.',
    parameters: [{ name: 'value', description: 'Any value. Non-numbers return `false` rather than being converted.' }],
    returns: '`true` if the value is `NaN`, otherwise `false`.',
    description: [
      '`NaN` is the only value in JavaScript not equal to itself, so `x === NaN` is always `false` and cannot be used to detect it. This function exists for that reason.',
      'It differs from the **global** `isNaN()`, which coerces its argument first: `isNaN("abc")` is `true` because `Number("abc")` is `NaN`, and `isNaN("")` is `false` because `Number("")` is `0`. That is almost never the question being asked.',
      'For validating input, `Number.isFinite()` is usually the better test, since it rejects `NaN` and both infinities in a single check.',
    ],
    examples: [
      {
        code: [
          'console.log(Number.isNaN(NaN));',
          'console.log(Number.isNaN("abc"));',
          'console.log(isNaN("abc"));',
          'console.log(NaN === NaN);',
          'console.log(Number.isNaN(0 / 0));',
        ].join('\n'),
        output: 'true\nfalse\ntrue\nfalse\ntrue',
        caption: 'The global isNaN coerces first; Number.isNaN does not.',
      },
    ],
    caveats: ['The global `isNaN()` is a different function with coercion — prefer `Number.isNaN`.'],
    commonMistakes: ['Comparing with `=== NaN`.', 'Using the global `isNaN` and inheriting its coercion.'],
    relatedEntries: ['ref-number-isfinite'],
    lessonId: 'l-m02-04',
  },

  {
    ...N,
    id: 'ref-number-isfinite',
    slug: 'number-isfinite',
    name: 'Number.isFinite()',
    aliases: ['isFinite', 'check finite number'],
    topicIds: ['numbers', 'types'],
    syntax: 'Number.isFinite(value)',
    summary: 'Returns `true` when the value is a number that is neither `NaN` nor infinite, with no coercion.',
    parameters: [{ name: 'value', description: 'Any value. Non-numbers return `false` without conversion.' }],
    returns: '`true` for a finite number, otherwise `false`.',
    description: [
      'This is the most useful single validity check for a numeric value: it rejects `NaN`, `Infinity`, `-Infinity` and every non-number in one call.',
      'Like `Number.isNaN`, it differs from the global `isFinite()`, which coerces — so `isFinite("42")` is `true` while `Number.isFinite("42")` is `false`. The strict version is what you want after an explicit `Number()` conversion.',
      'The usual pattern is convert, then check: `const n = Number(raw); if (!Number.isFinite(n)) reject();`',
    ],
    examples: [
      {
        code: [
          'const check = (raw) => {',
          '  const n = Number(raw);',
          '  return Number.isFinite(n) ? n : "invalid";',
          '};',
          '',
          'console.log(check("42"));',
          'console.log(check("abc"));',
          'console.log(check(""));',
          'console.log(Number.isFinite(1 / 0));',
          'console.log(Number.isFinite("42"));',
        ].join('\n'),
        output: '42\ninvalid\n0\nfalse\nfalse',
        caption: 'Convert then check — but note the empty string still converts to 0.',
      },
    ],
    caveats: ['Does not coerce, so it returns `false` for numeric **strings** — convert first.'],
    commonMistakes: ['Relying on it alone for form input, forgetting `Number("")` is `0`.'],
    relatedEntries: ['ref-number-isnan', 'ref-number-isinteger', 'ref-number-ctor'],
    lessonId: 'l-m06-02',
  },

  {
    ...N,
    id: 'ref-number-isinteger',
    slug: 'number-isinteger',
    name: 'Number.isInteger()',
    aliases: ['isInteger', 'check whole number'],
    topicIds: ['numbers', 'types'],
    syntax: 'Number.isInteger(value)',
    summary: 'Returns `true` when the value is a number with no fractional part.',
    parameters: [{ name: 'value', description: 'Any value. Non-numbers return `false` without conversion.' }],
    returns: '`true` for an integer-valued number, otherwise `false`.',
    description: [
      'It tests the **value**, not the storage: all JavaScript numbers are doubles, so `5.0` and `5` are the same value and both are integers.',
      'It returns `false` for `NaN` and both infinities, so it doubles as a finiteness check for whole numbers.',
      'It says nothing about whether the integer is exactly representable. Above 2^53 many "integers" are rounded neighbours — `Number.isSafeInteger()` is the check that also covers that.',
    ],
    examples: [
      {
        code: [
          'console.log(Number.isInteger(5));',
          'console.log(Number.isInteger(5.0));',
          'console.log(Number.isInteger(5.1));',
          'console.log(Number.isInteger("5"));',
          'console.log(Number.isInteger(Infinity));',
          'console.log(Number.isInteger(2 ** 53 + 2));',
        ].join('\n'),
        output: 'true\ntrue\nfalse\nfalse\nfalse\ntrue',
        caption: 'An unsafe integer is still an integer — use isSafeInteger for that.',
      },
    ],
    caveats: ['Returns `true` for values above the safe range that are no longer exactly representable.'],
    commonMistakes: ['Using it to validate an id that may exceed 2^53.'],
    relatedEntries: ['ref-number-issafeinteger', 'ref-number-isfinite', 'ref-math-trunc'],
    lessonId: 'l-m06-02',
  },

  {
    ...N,
    id: 'ref-number-issafeinteger',
    slug: 'number-issafeinteger',
    name: 'Number.isSafeInteger()',
    aliases: ['isSafeInteger', 'safe integer'],
    topicIds: ['numbers'],
    syntax: 'Number.isSafeInteger(value)',
    summary: 'Returns `true` when the value is an integer that can be represented exactly and distinguished from its neighbours.',
    parameters: [{ name: 'value', description: 'Any value. Non-numbers return `false`.' }],
    returns: '`true` if the value is an integer within ±(2^53 − 1), otherwise `false`.',
    description: [
      'A "safe" integer is one where `n` and `n + 1` are actually different values. Above 2^53 the gap between representable doubles exceeds 1, so consecutive integers collapse onto each other.',
      'This matters for identifiers. A 64-bit database id or a Twitter/X snowflake id can exceed the safe range, and parsing it into a `Number` silently corrupts it. Keep such ids as **strings**, or use `BigInt`.',
      '`JSON.parse` produces numbers, so a large integer in a JSON payload is already corrupted before you can check it — the fix has to happen on the wire format, not in JavaScript.',
    ],
    examples: [
      {
        code: [
          'console.log(Number.MAX_SAFE_INTEGER);',
          'console.log(Number.isSafeInteger(2 ** 53 - 1));',
          'console.log(Number.isSafeInteger(2 ** 53));',
          'console.log(2 ** 53 === 2 ** 53 + 1);',
          'console.log(JSON.parse("9007199254740993"));',
        ].join('\n'),
        output: '9007199254740991\ntrue\nfalse\ntrue\n9007199254740992',
        caption: 'A large id loses its last digit just by being parsed.',
      },
    ],
    caveats: ['`JSON.parse` corrupts oversized integers before any check can run — transmit them as strings.'],
    commonMistakes: ['Storing 64-bit ids as numbers.'],
    relatedEntries: ['ref-number-maxsafeinteger', 'ref-number-isinteger'],
    lessonId: 'l-m06-01',
  },

  {
    ...N,
    id: 'ref-number-maxsafeinteger',
    slug: 'number-max-safe-integer',
    name: 'Number.MAX_SAFE_INTEGER',
    aliases: ['Number.MIN_SAFE_INTEGER', 'MAX_SAFE_INTEGER', 'largest integer', 'Number.MAX_VALUE'],
    topicIds: ['numbers'],
    syntax: 'Number.MAX_SAFE_INTEGER\nNumber.MIN_SAFE_INTEGER',
    summary: 'The largest and smallest integers that a JavaScript number can represent exactly: ±9,007,199,254,740,991.',
    parameters: [],
    returns: 'A number constant. `MAX_SAFE_INTEGER` is 2^53 − 1; `MIN_SAFE_INTEGER` is its negation.',
    description: [
      'Beyond this range integers are still representable but no longer **distinguishable** — the spacing between adjacent doubles grows past 1, so arithmetic silently returns a rounded neighbour.',
      'Do not confuse this with `Number.MAX_VALUE` (about 1.8 × 10^308), which is the largest representable **magnitude**. Numbers between the safe integer limit and `MAX_VALUE` exist but lose integer precision.',
      'Anything larger needs `BigInt`, which is exact at any size. `BigInt` cannot be mixed with regular numbers in arithmetic without an explicit conversion, which is a deliberate guard against accidental precision loss.',
    ],
    examples: [
      {
        code: [
          'console.log(Number.MAX_SAFE_INTEGER);',
          'console.log(Number.MIN_SAFE_INTEGER);',
          'console.log(Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 2);',
          'console.log(BigInt(Number.MAX_SAFE_INTEGER) + 2n);',
        ].join('\n'),
        output: '9007199254740991\n-9007199254740991\ntrue\n9007199254740993n',
        caption: 'Past the safe limit, adding 1 and adding 2 give the same answer.',
      },
    ],
    caveats: ['`Number.MAX_VALUE` is a different, much larger constant about magnitude rather than integer precision.'],
    commonMistakes: ['Assuming any integer below `Number.MAX_VALUE` is exact.'],
    relatedEntries: ['ref-number-issafeinteger'],
    lessonId: 'l-m06-01',
  },

  {
    ...N,
    id: 'ref-number-epsilon',
    slug: 'number-epsilon',
    name: 'Number.EPSILON',
    aliases: ['EPSILON', 'float comparison', 'floating point tolerance'],
    topicIds: ['numbers'],
    syntax: 'Number.EPSILON',
    summary: 'The difference between 1 and the next representable number — the standard tolerance for comparing floats near 1.',
    parameters: [],
    returns: 'A number, approximately 2.22 × 10⁻¹⁶.',
    description: [
      'Because `0.1 + 0.2` is not exactly `0.3`, floating-point values should be compared with a tolerance rather than with `===`. `Math.abs(a - b) < Number.EPSILON` is the conventional form.',
      'The important limitation: `EPSILON` is the gap at magnitude 1. For large values the gap between representable doubles is much bigger, so an absolute `EPSILON` comparison becomes equivalent to `===` and fails. Use a **relative** tolerance there: `Math.abs(a - b) <= Number.EPSILON * Math.max(Math.abs(a), Math.abs(b))`.',
      'For money, tolerance comparison is the wrong tool entirely — store integer minor units (cents) so the arithmetic is exact.',
    ],
    examples: [
      {
        code: [
          'console.log(0.1 + 0.2 === 0.3);',
          'console.log(Math.abs(0.1 + 0.2 - 0.3) < Number.EPSILON);',
          '',
          'const a = 1e16;',
          'console.log(Math.abs(a - (a + 1)) < Number.EPSILON);',
        ].join('\n'),
        output: 'false\ntrue\ntrue',
        caption: 'At 1e16 the values differ, yet an absolute EPSILON test calls them equal.',
      },
    ],
    caveats: ['An absolute `EPSILON` comparison is only valid near magnitude 1 — scale the tolerance for larger values.'],
    commonMistakes: ['Using tolerance comparison for currency instead of integer cents.'],
    relatedEntries: ['ref-number-tofixed', 'ref-number-issafeinteger'],
    lessonId: 'l-m06-01',
  },

  {
    ...N,
    id: 'ref-number-tofixed',
    slug: 'number-prototype-tofixed',
    name: 'Number.prototype.toFixed()',
    aliases: ['toFixed', 'round to decimals', 'format decimals'],
    topicIds: ['numbers', 'strings'],
    syntax: 'num.toFixed()\nnum.toFixed(digits)',
    summary: 'Formats a number with a fixed number of decimal places, returning a **string**.',
    parameters: [{ name: 'digits', optional: true, description: 'Decimal places to show, 0–100, defaulting to `0`. Values outside that range throw.' }],
    returns: 'A string — never a number.',
    throws: '`RangeError` if `digits` is outside 0–100.',
    description: [
      'The return type is the detail that causes bugs: `(1.5).toFixed(2) + 1` is `"1.501"`, because `+` concatenates. Convert back with `Number()` if you need arithmetic.',
      'Rounding operates on the stored binary value, not the decimal you wrote. `(1.005).toFixed(2)` is `"1.00"` because the double nearest to 1.005 is slightly below it. This is not a rounding bug in `toFixed`; it is the value that was already stored.',
      'It pads with zeros to the requested width, which is what makes it useful for display: `(5).toFixed(2)` is `"5.00"`.',
      'For user-facing numbers, `Intl.NumberFormat` (or `toLocaleString`) is better — it handles thousands separators, currency symbols and locale decimal marks, none of which `toFixed` does.',
    ],
    examples: [
      {
        code: [
          'console.log((3.14159).toFixed(2));',
          'console.log((5).toFixed(2));',
          'console.log(typeof (5).toFixed(2));',
          'console.log((1.005).toFixed(2));',
          'console.log((1.5).toFixed(2) + 1);',
          'console.log(Number((1.5).toFixed(2)) + 1);',
        ].join('\n'),
        output: '3.14\n5.00\nstring\n1.00\n1.501\n2.5',
        caption: 'It returns a string, and it rounds the stored binary value.',
      },
    ],
    caveats: [
      'Returns a string — arithmetic on the result concatenates.',
      '`(1.005).toFixed(2)` is `"1.00"`, because of how the value is stored.',
      'No thousands separators or locale awareness.',
    ],
    commonMistakes: ['Using the result in arithmetic without converting back.'],
    relatedEntries: ['ref-number-tolocalestring', 'ref-number-toprecision', 'ref-math-round'],
    lessonId: 'l-m06-02',
  },

  {
    ...N,
    id: 'ref-number-toprecision',
    slug: 'number-prototype-toprecision',
    name: 'Number.prototype.toPrecision()',
    aliases: ['toPrecision', 'significant figures'],
    topicIds: ['numbers'],
    syntax: 'num.toPrecision()\nnum.toPrecision(precision)',
    summary: 'Formats a number to a given number of **significant digits**, returning a string.',
    parameters: [{ name: 'precision', optional: true, description: 'Significant digits, 1–100. Omitted, the result is the same as `String(num)`.' }],
    returns: 'A string, in exponential notation when the exponent is large or small enough to require it.',
    throws: '`RangeError` if `precision` is outside 1–100.',
    description: [
      'Where `toFixed` counts digits after the decimal point, `toPrecision` counts significant digits across the whole number. `(1234).toPrecision(2)` is `"1.2e+3"`, not `"1234"`.',
      'It switches to exponential notation automatically when the requested precision cannot represent the number positionally, which makes its output shape harder to predict than `toFixed`.',
      'Useful for scientific and measurement display where significant figures are the meaningful unit. For currency and general UI formatting, `toFixed` or `Intl.NumberFormat` is the right tool.',
    ],
    examples: [
      {
        code: [
          'console.log((123.456).toPrecision(4));',
          'console.log((123.456).toPrecision(2));',
          'console.log((0.000123).toPrecision(2));',
          'console.log((1234).toPrecision(2));',
        ].join('\n'),
        output: '123.5\n1.2e+2\n0.00012\n1.2e+3',
        caption: 'It falls back to exponential notation when precision demands it.',
      },
    ],
    caveats: ['Returns exponential notation unpredictably compared with `toFixed`.'],
    commonMistakes: ['Reaching for it when fixed decimal places, not significant figures, were wanted.'],
    relatedEntries: ['ref-number-tofixed'],
    lessonId: 'l-m06-02',
  },

  {
    ...N,
    id: 'ref-number-tolocalestring',
    slug: 'number-prototype-tolocalestring',
    name: 'Number.prototype.toLocaleString()',
    aliases: ['toLocaleString', 'format currency', 'thousands separator', 'Intl.NumberFormat'],
    topicIds: ['numbers', 'strings'],
    syntax: 'num.toLocaleString()\nnum.toLocaleString(locales, options)',
    summary: 'Formats a number for human display — thousands separators, currency, percentages and units — according to a locale.',
    parameters: [
      { name: 'locales', optional: true, description: 'A BCP 47 tag such as `"de-DE"`, or an array. Omitted, the environment default is used.' },
      { name: 'options', optional: true, description: 'An `Intl.NumberFormat` options object: `style`, `currency`, `minimumFractionDigits`, `maximumFractionDigits`, `notation`.' },
    ],
    returns: 'A locale-formatted string.',
    description: [
      'This is the correct way to show a number to a person. `toFixed` produces `"1234.50"`; this produces `"1,234.50"` in `en-US` and `"1.234,50"` in `de-DE`.',
      '`{ style: "currency", currency: "USD" }` adds the symbol and applies the currency\'s own decimal rules — Japanese yen shows no decimals, for instance, without you having to special-case it.',
      'For formatting many numbers, construct an `Intl.NumberFormat` once and reuse its `format` method; building the formatter is the expensive part.',
      'Because output depends on locale and on the engine\'s ICU data, never assert on the exact string in a test unless the locale is pinned.',
    ],
    examples: [
      {
        code: [
          'const n = 1234567.891;',
          '',
          'console.log(n.toLocaleString("en-US"));',
          'console.log(n.toLocaleString("de-DE"));',
          'console.log((0.256).toLocaleString("en-US", { style: "percent", maximumFractionDigits: 1 }));',
          'console.log((42).toLocaleString("en-US", { style: "currency", currency: "USD" }));',
        ].join('\n'),
        output: '1,234,567.891\n1.234.567,891\n25.6%\n$42.00',
        caption: 'Locale decides separators; style handles percent and currency.',
      },
    ],
    caveats: [
      'Output varies by locale and engine — do not snapshot-test it without pinning the locale.',
      'Formatting is for display only. Never parse a formatted string back into a number.',
    ],
    commonMistakes: ['Building currency strings by concatenating a symbol onto `toFixed(2)`.'],
    relatedEntries: ['ref-number-tofixed'],
    lessonId: 'l-m16-04',
  },

  /* ------------------------------------------------------------------ Math */
  {
    ...N,
    id: 'ref-math-abs',
    slug: 'math-abs',
    name: 'Math.abs()',
    aliases: ['abs', 'absolute value'],
    topicIds: ['numbers'],
    syntax: 'Math.abs(x)',
    summary: 'Returns the absolute value of a number — its magnitude, without a sign.',
    parameters: [{ name: 'x', description: 'A number. Non-numbers are coerced; values that cannot convert give `NaN`.' }],
    returns: 'A non-negative number, or `NaN`.',
    description: [
      'The most common real use is distance or difference: `Math.abs(a - b)` gives how far apart two values are regardless of order.',
      'It is also half of every floating-point tolerance comparison, paired with `Number.EPSILON`.',
      '`Math.abs(-0)` is `0`, and `Math.abs("-5")` is `5` because the argument is coerced.',
    ],
    examples: [
      {
        code: [
          'console.log(Math.abs(-7));',
          'console.log(Math.abs(7));',
          'console.log(Math.abs(-0));',
          'console.log(Math.abs("-5"));',
          'console.log(Math.abs("abc"));',
        ].join('\n'),
        output: '7\n7\n0\n5\nNaN',
        caption: 'Arguments are coerced, so non-numeric input yields NaN rather than throwing.',
      },
    ],
    caveats: ['Coerces its argument rather than throwing, so a bad value becomes `NaN` and propagates silently.'],
    commonMistakes: ['Not checking the result when the input may be non-numeric.'],
    relatedEntries: ['ref-math-sign', 'ref-number-epsilon'],
    lessonId: 'l-m06-03',
  },

  {
    ...N,
    id: 'ref-math-round',
    slug: 'math-round',
    name: 'Math.round()',
    aliases: ['round', 'rounding'],
    topicIds: ['numbers'],
    syntax: 'Math.round(x)',
    summary: 'Rounds to the nearest integer, with halves rounding **towards positive infinity**.',
    parameters: [{ name: 'x', description: 'A number. Coerced if it is not one.' }],
    returns: 'An integer, or `NaN`.',
    description: [
      'The half-way rule is asymmetric and catches people out: `Math.round(2.5)` is `3`, but `Math.round(-2.5)` is `-2`, not `-3`. Halves always go up in the numeric sense, not away from zero.',
      'To round to decimal places, scale first: `Math.round(x * 100) / 100`. Be aware this inherits floating-point error — for money, work in integer cents instead.',
      'For rounding that always goes away from zero, combine `Math.sign` with `Math.round(Math.abs(x))`.',
    ],
    examples: [
      {
        code: [
          'console.log(Math.round(2.5));',
          'console.log(Math.round(2.4));',
          'console.log(Math.round(-2.5));',
          'console.log(Math.round(-2.6));',
          'console.log(Math.round(1.2345 * 100) / 100);',
        ].join('\n'),
        output: '3\n2\n-2\n-3\n1.23',
        caption: 'Negative halves round towards zero, not away from it.',
      },
    ],
    caveats: ['`Math.round(-2.5)` is `-2`. Half-way values round up, not away from zero.'],
    commonMistakes: ['Assuming symmetric rounding for negative numbers.'],
    relatedEntries: ['ref-math-floor', 'ref-math-ceil', 'ref-math-trunc', 'ref-number-tofixed'],
    lessonId: 'l-m06-03',
  },

  {
    ...N,
    id: 'ref-math-floor',
    slug: 'math-floor',
    name: 'Math.floor()',
    aliases: ['floor', 'round down'],
    topicIds: ['numbers'],
    syntax: 'Math.floor(x)',
    summary: 'Returns the largest integer less than or equal to the number — always rounding **down**, towards negative infinity.',
    parameters: [{ name: 'x', description: 'A number. Coerced if it is not one.' }],
    returns: 'An integer, or `NaN`.',
    description: [
      'For positive numbers `floor` and `trunc` agree. For negative numbers they differ: `Math.floor(-1.5)` is `-2` while `Math.trunc(-1.5)` is `-1`.',
      'The standard idiom for a random integer in a range is `Math.floor(Math.random() * n)`, which maps the half-open interval `[0, 1)` onto the integers `0 … n − 1` evenly.',
      'It is also the correct operator for pagination: `Math.floor(index / pageSize)` gives the page containing an item.',
    ],
    examples: [
      {
        code: [
          'console.log(Math.floor(1.9));',
          'console.log(Math.floor(-1.1));',
          'console.log(Math.trunc(-1.1));',
          'console.log(Math.floor(7 / 2));',
        ].join('\n'),
        output: '1\n-2\n-1\n3',
        caption: 'floor goes towards negative infinity; trunc goes towards zero.',
      },
    ],
    caveats: ['Rounds negatives away from zero, which is often not what "round down" is assumed to mean.'],
    commonMistakes: ['Using `floor` where `trunc` was intended, on values that can be negative.'],
    relatedEntries: ['ref-math-ceil', 'ref-math-trunc', 'ref-math-random'],
    lessonId: 'l-m06-03',
  },

  {
    ...N,
    id: 'ref-math-ceil',
    slug: 'math-ceil',
    name: 'Math.ceil()',
    aliases: ['ceil', 'ceiling', 'round up'],
    topicIds: ['numbers'],
    syntax: 'Math.ceil(x)',
    summary: 'Returns the smallest integer greater than or equal to the number — always rounding **up**, towards positive infinity.',
    parameters: [{ name: 'x', description: 'A number. Coerced if it is not one.' }],
    returns: 'An integer, or `NaN`.',
    description: [
      'The canonical use is counting containers: `Math.ceil(total / perPage)` gives the number of pages needed, because a partial page still needs a whole page.',
      'For negative numbers it rounds towards zero: `Math.ceil(-1.5)` is `-1`.',
      '`Math.ceil(-0.5)` is `-0`, which is `===` to `0` but stringifies as `"0"` — visible only if you use `Object.is` or divide by it.',
    ],
    examples: [
      {
        code: [
          'console.log(Math.ceil(1.1));',
          'console.log(Math.ceil(-1.5));',
          'console.log(Math.ceil(4));',
          'console.log(Math.ceil(23 / 10));',
        ].join('\n'),
        output: '2\n-1\n4\n3',
        caption: '23 items at 10 per page needs 3 pages.',
      },
    ],
    caveats: ['Returns `-0` for inputs in `(-1, 0)`.'],
    commonMistakes: ['Using `Math.round` for page counts, which under-counts a partial final page.'],
    relatedEntries: ['ref-math-floor', 'ref-math-round', 'ref-math-trunc'],
    lessonId: 'l-m06-03',
  },

  {
    ...N,
    id: 'ref-math-trunc',
    slug: 'math-trunc',
    name: 'Math.trunc()',
    aliases: ['trunc', 'truncate', 'remove decimal'],
    topicIds: ['numbers'],
    syntax: 'Math.trunc(x)',
    summary: 'Removes the fractional part, rounding towards zero in both directions.',
    parameters: [{ name: 'x', description: 'A number. Coerced if it is not one.' }],
    returns: 'An integer, or `NaN`.',
    description: [
      'This is "drop the decimals" in the plain sense, and it is the only one of the four rounding functions that treats positive and negative symmetrically.',
      'It is what most people mean by integer division when combined with `/`: `Math.trunc(-7 / 2)` is `-3`, whereas `Math.floor(-7 / 2)` is `-4`.',
      'The older bit-wise tricks (`~~x`, `x | 0`) truncate too, but they coerce to a 32-bit signed integer and therefore break silently above about 2.1 billion. `Math.trunc` has no such limit.',
    ],
    examples: [
      {
        code: [
          'console.log(Math.trunc(4.9));',
          'console.log(Math.trunc(-4.9));',
          'console.log(Math.floor(-4.9));',
          'console.log(Math.trunc(3e9));',
          'console.log(~~3e9);',
        ].join('\n'),
        output: '4\n-4\n-5\n3000000000\n-1294967296',
        caption: 'The ~~ trick silently overflows at 32 bits; Math.trunc does not.',
      },
    ],
    caveats: ['Not a substitute for rounding — it always discards, never rounds up.'],
    commonMistakes: ['Using `~~x` or `x | 0` on values that can exceed 32-bit range.'],
    relatedEntries: ['ref-math-floor', 'ref-math-round', 'ref-number-isinteger'],
    lessonId: 'l-m06-03',
  },

  {
    ...N,
    id: 'ref-math-max',
    slug: 'math-max',
    name: 'Math.max()',
    aliases: ['max', 'largest value', 'Math.min'],
    topicIds: ['numbers', 'arrays'],
    syntax: 'Math.max(value1, value2, /* … */)\nMath.max(...array)',
    summary: 'Returns the largest of its arguments. `Math.min()` is the mirror image.',
    parameters: [{ name: 'value1, value2, …', description: 'Numbers. Non-numeric values that cannot be coerced make the whole result `NaN`.' }],
    returns: 'The largest argument, `-Infinity` when called with none, or `NaN` if any argument is `NaN`.',
    description: [
      'It takes a variable number of **arguments**, not an array. Use spread — `Math.max(...values)` — or `values.reduce((a, b) => Math.max(a, b))` for large arrays.',
      'The empty case is deliberately chosen so the identity works: `Math.max()` is `-Infinity` and `Math.min()` is `+Infinity`. That means `Math.max(...[])` returns `-Infinity`, not `undefined` — check for an empty array first.',
      'A single `NaN` anywhere poisons the result, which is a useful signal if your data may contain unparsed values.',
      'Spreading a very large array can exceed the engine argument limit — around 100,000 elements — and throw a `RangeError`. Use `reduce` for big data sets.',
    ],
    examples: [
      {
        code: [
          'const scores = [12, 5, 30, 8];',
          '',
          'console.log(Math.max(...scores));',
          'console.log(Math.min(...scores));',
          'console.log(Math.max());',
          'console.log(Math.max(1, NaN));',
          'console.log(scores.reduce((a, b) => Math.max(a, b), -Infinity));',
        ].join('\n'),
        output: '30\n5\n-Infinity\nNaN\n30',
        caption: 'Math.max() with no arguments is -Infinity, which an empty spread hits.',
      },
    ],
    caveats: [
      '`Math.max(...[])` is `-Infinity` — guard against empty arrays.',
      'Spreading a huge array can throw `RangeError`.',
    ],
    commonMistakes: ['Passing an array directly instead of spreading it, which gives `NaN`.'],
    relatedEntries: ['ref-math-abs'],
    lessonId: 'l-m06-03',
  },

  {
    ...N,
    id: 'ref-math-pow',
    slug: 'math-pow',
    name: 'Math.pow()',
    aliases: ['pow', 'power', 'exponent', 'exponentiation operator'],
    topicIds: ['numbers', 'operators'],
    syntax: 'Math.pow(base, exponent)\nbase ** exponent',
    summary: 'Raises a base to an exponent. The `**` operator is the modern equivalent.',
    parameters: [
      { name: 'base', description: 'The base number.' },
      { name: 'exponent', description: 'The power to raise it to. May be fractional or negative.' },
    ],
    returns: 'A number, or `NaN` for undefined results such as a negative base with a fractional exponent.',
    description: [
      '`**` was added in ES2016 and reads better in expressions: `2 ** 10`. It is right-associative, so `2 ** 3 ** 2` is `2 ** 9`, not `8 ** 2`.',
      'A unary minus directly before `**` is a **SyntaxError** — `-2 ** 2` does not parse. Write `(-2) ** 2` or `-(2 ** 2)` to say which you mean. This was made an error deliberately, because the precedence is genuinely ambiguous to readers.',
      'A fractional exponent gives roots: `x ** 0.5` is the square root, though `Math.sqrt` is clearer and slightly more accurate.',
      'For very large integer powers, results exceed the safe integer range and lose precision — `BigInt` supports `**` too.',
    ],
    examples: [
      {
        code: [
          'console.log(Math.pow(2, 10));',
          'console.log(2 ** 10);',
          'console.log(2 ** 3 ** 2);',
          'console.log((-2) ** 2);',
          'console.log(8 ** (1 / 3));',
          'console.log(2n ** 64n);',
        ].join('\n'),
        output: '1024\n1024\n512\n4\n2\n18446744073709551616n',
        caption: '** is right-associative, and BigInt supports it exactly.',
      },
    ],
    caveats: ['`-2 ** 2` is a `SyntaxError` — parenthesise explicitly.', '`**` is right-associative.'],
    commonMistakes: ['Assuming `2 ** 3 ** 2` evaluates left to right.'],
    relatedEntries: ['ref-math-sqrt', 'ref-number-maxsafeinteger'],
    lessonId: 'l-m06-03',
  },

  {
    ...N,
    id: 'ref-math-sqrt',
    slug: 'math-sqrt',
    name: 'Math.sqrt()',
    aliases: ['sqrt', 'square root'],
    topicIds: ['numbers'],
    syntax: 'Math.sqrt(x)',
    summary: 'Returns the square root of a number, or `NaN` for a negative input.',
    parameters: [{ name: 'x', description: 'A non-negative number. Negative values give `NaN`.' }],
    returns: 'A non-negative number, or `NaN`.',
    description: [
      'A negative argument returns `NaN` rather than throwing, because JavaScript has no complex numbers. Guard the input if it is computed.',
      '`Math.hypot(a, b)` computes `Math.sqrt(a**a + b**b)` without the intermediate overflow that squaring large values can cause — the better choice for distance calculations.',
      'For comparing distances, compare the **squared** distances and skip the square root entirely; it is both faster and exact for integers.',
    ],
    examples: [
      {
        code: [
          'console.log(Math.sqrt(16));',
          'console.log(Math.sqrt(2));',
          'console.log(Math.sqrt(-1));',
          'console.log(Math.hypot(3, 4));',
        ].join('\n'),
        output: '4\n1.4142135623730951\nNaN\n5',
        caption: 'A negative input gives NaN; hypot avoids intermediate overflow.',
      },
    ],
    caveats: ['Returns `NaN` for negative input instead of throwing.'],
    commonMistakes: ['Taking a square root to compare distances when comparing squares would do.'],
    relatedEntries: ['ref-math-pow', 'ref-math-abs'],
    lessonId: 'l-m06-03',
  },

  {
    ...N,
    id: 'ref-math-random',
    slug: 'math-random',
    name: 'Math.random()',
    aliases: ['random', 'random number'],
    topicIds: ['numbers'],
    syntax: 'Math.random()',
    summary: 'Returns a pseudo-random number in the half-open interval `[0, 1)` — zero is possible, one is not.',
    parameters: [],
    returns: 'A number `n` where `0 <= n < 1`.',
    description: [
      'To get an integer from `min` to `max` **inclusive**, the correct formula is `Math.floor(Math.random() * (max - min + 1)) + min`. The `+ 1` is what makes `max` reachable; omitting it is the standard off-by-one here.',
      'It takes no seed and cannot be seeded, so output is not reproducible. Code that needs deterministic tests should accept an injected random source rather than calling `Math.random()` directly.',
      'It is **not cryptographically secure** and must never be used for tokens, passwords, session identifiers or anything else an attacker should not predict. `crypto.getRandomValues()` is the correct API for that, and `crypto.randomUUID()` for identifiers.',
      'The distribution is uniform, so "shuffle by sorting with a random comparator" is still wrong — a random comparator is inconsistent and produces a biased order. Use a Fisher–Yates shuffle.',
    ],
    examples: [
      {
        code: [
          'function randomInt(min, max) {',
          '  return Math.floor(Math.random() * (max - min + 1)) + min;',
          '}',
          '',
          'const rolls = Array.from({ length: 200 }, () => randomInt(1, 6));',
          '',
          'console.log(rolls.every((n) => n >= 1 && n <= 6));',
          'console.log(new Set(rolls).size <= 6);',
          'console.log(rolls.length);',
        ].join('\n'),
        output: 'true\ntrue\n200',
        caption: 'Assert the range rather than the values — the output is not reproducible.',
      },
    ],
    caveats: [
      'Not cryptographically secure — use `crypto.getRandomValues()` for anything security-related.',
      'Cannot be seeded; inject a random source if you need deterministic tests.',
      'Never shuffle with `sort(() => Math.random() - 0.5)` — the comparator is inconsistent and the result is biased.',
    ],
    commonMistakes: ['Omitting `+ 1` and never generating the maximum value.'],
    relatedEntries: ['ref-math-floor'],
    lessonId: 'l-m06-03',
  },

  {
    ...N,
    id: 'ref-math-sign',
    slug: 'math-sign',
    name: 'Math.sign()',
    aliases: ['sign', 'signum', 'positive or negative'],
    topicIds: ['numbers'],
    syntax: 'Math.sign(x)',
    summary: 'Returns `1`, `-1`, `0`, `-0` or `NaN`, indicating the sign of a number.',
    parameters: [{ name: 'x', description: 'A number. Coerced if it is not one.' }],
    returns: '`1` for positive, `-1` for negative, `0` or `-0` for zero, `NaN` for `NaN`.',
    description: [
      'Five possible return values, not three — `-0` is distinct from `0` here, though the two compare `===` equal. Use `Object.is` if the difference matters.',
      'Useful for direction: `Math.sign(target - current)` gives which way to step, and multiplying by it applies a sign to a magnitude.',
      'It is not a comparator. A `sort` comparator can return any negative or positive number, so `(a, b) => a - b` is simpler and avoids the extra call.',
    ],
    examples: [
      {
        code: [
          'console.log(Math.sign(3));',
          'console.log(Math.sign(-3));',
          'console.log(Math.sign(0));',
          'console.log(Object.is(Math.sign(-0), -0));',
          'console.log(Math.sign("abc"));',
        ].join('\n'),
        output: '1\n-1\n0\ntrue\nNaN',
        caption: 'Math.sign(-0) is -0, which only Object.is distinguishes from 0.',
      },
    ],
    caveats: ['Returns `-0` for negative zero, which `===` cannot distinguish from `0`.'],
    commonMistakes: ['Treating the result as strictly `1`, `-1` or `0`.'],
    relatedEntries: ['ref-math-abs'],
    lessonId: 'l-m06-03',
  },

  {
    ...N,
    id: 'ref-math-pi',
    slug: 'math-pi',
    name: 'Math.PI',
    aliases: ['PI', 'pi', 'Math.E', 'math constants'],
    topicIds: ['numbers'],
    syntax: 'Math.PI',
    summary: 'The ratio of a circle\'s circumference to its diameter, as the closest representable double.',
    parameters: [],
    returns: 'A number, approximately 3.141592653589793.',
    description: [
      'Like every irrational constant it is stored as the nearest double, so `Math.sin(Math.PI)` is not exactly `0` but about 1.22 × 10⁻¹⁶. Comparisons involving it need a tolerance.',
      '`Math` also carries `E`, `LN2`, `LN10`, `LOG2E`, `LOG10E`, `SQRT2` and `SQRT1_2`. All are read-only and non-writable.',
      'Degrees-to-radians conversion is `deg * Math.PI / 180`; the trigonometric functions all take radians.',
    ],
    examples: [
      {
        code: [
          'console.log(Math.PI);',
          'console.log(Math.sin(Math.PI) === 0);',
          'console.log(Math.abs(Math.sin(Math.PI)) < 1e-15);',
          'console.log(Math.round((90 * Math.PI / 180) * 1e6) / 1e6);',
        ].join('\n'),
        output: '3.141592653589793\nfalse\ntrue\n1.570796',
        caption: 'sin(PI) is not exactly zero, because PI is not exactly pi.',
      },
    ],
    caveats: ['Trigonometric identities do not hold exactly in floating point — compare with a tolerance.'],
    commonMistakes: ['Passing degrees to `Math.sin` and friends, which expect radians.'],
    relatedEntries: ['ref-number-epsilon', 'ref-math-abs'],
    lessonId: 'l-m06-03',
  },
];
