import { REFERENCE_CATEGORY as C, REFERENCE_ENV as E } from '../schema/types.js';

/**
 * Promise and Error reference.
 *
 * Every ordering claim in these examples is executed by `content:examples` and
 * compared against real output, so the microtask sequencing documented here is
 * verified rather than remembered.
 */

const P = { category: C.PROMISE, environment: E.ECMASCRIPT, mutates: false };
const X = { category: C.ERROR, environment: E.ECMASCRIPT, mutates: false };

export default [
  {
    ...P,
    id: 'ref-promise-ctor',
    slug: 'promise-constructor',
    name: 'Promise()',
    aliases: ['new Promise', 'promise constructor', 'promise states', 'executor'],
    topicIds: ['promises', 'async-foundations'],
    syntax: 'new Promise(executor)',
    summary: 'Creates a promise from an executor function that receives `resolve` and `reject`. The executor body runs **synchronously**, immediately.',
    parameters: [
      { name: 'executor', description: 'Called at once as `(resolve, reject)`. Call `resolve(value)` to fulfil or `reject(reason)` to reject. A synchronous throw inside it rejects the promise.' },
    ],
    returns: 'A new `Promise` in the **pending** state.',
    description: [
      'A promise has exactly three states: **pending**, **fulfilled** or **rejected**. Once it leaves pending it is **settled**, and settling is permanent — later `resolve` or `reject` calls are ignored, not errors.',
      'The executor runs **synchronously** during construction. It is only the **reactions** — the callbacks passed to `then`, `catch` and `finally` — that are deferred, and they are scheduled as microtasks, which run after the current synchronous work finishes and before any timer callback.',
      'Use `new Promise` only to **adapt a non-promise API**: an event, a callback-style function, a timer. Wrapping something that already returns a promise in `new Promise` is the "explicit promise construction antipattern" — it adds a layer that can swallow errors.',
      'A `throw` inside the executor rejects the promise. A `throw` inside an **asynchronous** callback within the executor does not — nothing is there to catch it, so it becomes an uncaught error. Call `reject` explicitly from asynchronous code.',
      'Rejection reasons should be `Error` objects. Rejecting with a string loses the stack trace and forces every consumer to guess at the shape.',
    ],
    examples: [
      {
        code: [
          'console.log("1 before");',
          '',
          'const p = new Promise((resolve) => {',
          '  console.log("2 executor runs now");',
          '  resolve("value");',
          '  resolve("ignored");',
          '});',
          '',
          'p.then((v) => console.log("4 reaction:", v));',
          '',
          'console.log("3 after");',
        ].join('\n'),
        output: '1 before\n2 executor runs now\n3 after\n4 reaction: value',
        caption: 'The executor is synchronous; only the reaction is deferred.',
      },
    ],
    caveats: [
      'The executor body is synchronous — it does not defer anything on its own.',
      'A settled promise cannot change state; extra `resolve`/`reject` calls are silently ignored.',
      'Do not wrap an existing promise in `new Promise`.',
    ],
    commonMistakes: ['Saying "promises run asynchronously" — the executor does not.', 'Rejecting with a string instead of an `Error`.'],
    relatedEntries: ['ref-promise-then', 'ref-promise-resolve', 'ref-promise-all'],
    lessonId: 'l-m24-01',
  },

  {
    ...P,
    id: 'ref-promise-then',
    slug: 'promise-prototype-then',
    name: 'Promise.prototype.then()',
    aliases: ['then', 'promise then', 'chain promises'],
    topicIds: ['promises'],
    syntax: 'promise.then(onFulfilled)\npromise.then(onFulfilled, onRejected)',
    summary: 'Registers reactions and returns a **new promise** representing the result of the reaction — which is what makes chaining work.',
    parameters: [
      { name: 'onFulfilled', optional: true, description: 'Called with the fulfilment value when the promise fulfils.' },
      { name: 'onRejected', optional: true, description: 'Called with the reason when it rejects. Handles only rejections from **before** this call, not from `onFulfilled`.' },
    ],
    returns: 'A **new** promise, fulfilled with the handler\'s return value — or rejected if the handler throws.',
    description: [
      'The return value is a new promise, not the original. Returning a value from a handler fulfils that new promise with it; returning a **promise** adopts it, which is what lets a chain flatten instead of nesting.',
      'Forgetting to `return` inside a handler is the classic chain bug: the next `then` receives `undefined` and does not wait for anything the handler started.',
      'The two-argument form differs from `.then().catch()` in a way that matters: `onRejected` cannot catch an error thrown by `onFulfilled` in the **same** call, because both are registered at the same point. A trailing `.catch()` can, because it is downstream.',
      'Reactions always run asynchronously as **microtasks**, even on an already-settled promise — so `.then` never runs before the current synchronous block finishes.',
      'A non-function argument is ignored and the value passes through, which is why `.then(null, fn)` works as a rejection-only handler.',
    ],
    examples: [
      {
        code: [
          'Promise.resolve(1)',
          '  .then((v) => v + 1)',
          '  .then((v) => Promise.resolve(v * 10))',
          '  .then((v) => console.log("chained:", v));',
          '',
          'Promise.resolve("x")',
          '  .then(() => { throw new Error("boom"); }, () => console.log("not reached"))',
          '  .catch((e) => console.log("caught:", e.message));',
          '',
          'console.log("sync first");',
        ].join('\n'),
        output: 'sync first\ncaught: boom\nchained: 20',
        caption: 'The shorter chain finishes first — each link costs one microtask tick.',
      },
    ],
    caveats: [
      'Always returns a new promise — the original is unchanged.',
      'A handler that forgets to `return` breaks the chain silently.',
      'The second argument cannot catch errors from the first.',
    ],
    commonMistakes: ['Nesting `then` calls instead of returning a promise and chaining.'],
    relatedEntries: ['ref-promise-catch', 'ref-promise-finally', 'ref-promise-ctor'],
    lessonId: 'l-m24-02',
  },

  {
    ...P,
    id: 'ref-promise-catch',
    slug: 'promise-prototype-catch',
    name: 'Promise.prototype.catch()',
    aliases: ['catch', 'promise catch', 'handle rejection'],
    topicIds: ['promises', 'errors'],
    syntax: 'promise.catch(onRejected)',
    summary: 'Registers a rejection handler. Exactly equivalent to `.then(undefined, onRejected)`, and returns a new promise.',
    parameters: [{ name: 'onRejected', description: 'Called with the rejection reason.' }],
    returns: 'A **new** promise. If the handler returns normally, that promise **fulfils** — the chain recovers.',
    description: [
      'A `catch` handler that returns normally **converts the rejection into a fulfilment**. Anything chained after it runs as if nothing had failed. To keep the chain rejected, rethrow.',
      'Its position matters: it handles rejections from everything **above** it in the chain. A `catch` in the middle recovers, and later steps still run; a `catch` at the end handles everything.',
      'A chain with no `catch` anywhere produces an unhandled rejection — reported on `window.onunhandledrejection` in browsers, and fatal by default in Node.',
      'It does not catch errors thrown inside a `setTimeout` callback started by the chain, because that callback runs on a different task with its own stack.',
    ],
    examples: [
      {
        code: [
          'Promise.reject(new Error("fail"))',
          '  .catch((e) => "recovered from " + e.message)',
          '  .then((v) => console.log("A:", v));',
          '',
          'Promise.reject(new Error("fail"))',
          '  .catch((e) => { throw e; })',
          '  .then(() => console.log("not reached"))',
          '  .catch((e) => console.log("B: still rejected:", e.message));',
        ].join('\n'),
        output: 'A: recovered from fail\nB: still rejected: fail',
        caption: 'Returning from catch recovers; rethrowing keeps the chain rejected.',
      },
    ],
    caveats: [
      'Returning normally from `catch` fulfils the chain — rethrow to keep it failing.',
      'Cannot catch errors thrown inside timer callbacks.',
    ],
    commonMistakes: ['Adding a `catch` that logs and returns, accidentally marking a failure as success.'],
    relatedEntries: ['ref-promise-then', 'ref-promise-finally', 'ref-error-ctor'],
    lessonId: 'l-m24-03',
  },

  {
    ...P,
    id: 'ref-promise-finally',
    slug: 'promise-prototype-finally',
    name: 'Promise.prototype.finally()',
    aliases: ['finally', 'promise finally', 'cleanup'],
    topicIds: ['promises'],
    syntax: 'promise.finally(onFinally)',
    summary: 'Runs a callback when the promise settles either way, and **passes the original outcome through** unchanged.',
    parameters: [{ name: 'onFinally', description: 'Called with **no arguments** when the promise settles. It cannot see the value or the reason.' }],
    returns: 'A new promise that settles the same way as the original — unless `onFinally` throws or returns a rejected promise.',
    description: [
      'The callback receives no arguments, deliberately: `finally` is for cleanup that does not depend on the outcome — hiding a spinner, closing a handle, clearing a loading flag.',
      'The original value or rejection **passes through**. Returning a value from `onFinally` does not change it, which is the opposite of how `then` behaves and is the whole point.',
      'The exception: if `onFinally` **throws** or returns a rejected promise, that failure replaces the original outcome. Cleanup code that can fail should handle its own errors.',
      'If `onFinally` returns a promise, the chain waits for it to settle before continuing.',
      'Note the contrast with a `finally` **block**, where a `return` overrides the pending return. Here a return is ignored.',
    ],
    examples: [
      {
        code: [
          'Promise.resolve("value")',
          '  .finally(() => "ignored")',
          '  .then((v) => console.log("A:", v));',
          '',
          'Promise.reject(new Error("fail"))',
          '  .finally(() => console.log("B: cleanup runs"))',
          '  .catch((e) => console.log("C:", e.message));',
        ].join('\n'),
        output: 'B: cleanup runs\nA: value\nC: fail',
        caption: 'The return value of onFinally is discarded; the outcome passes through.',
      },
    ],
    caveats: [
      'The callback receives no arguments.',
      'A throw inside it does replace the original outcome.',
    ],
    commonMistakes: ['Expecting to transform the value from inside `finally`.'],
    relatedEntries: ['ref-promise-catch', 'ref-promise-then'],
    lessonId: 'l-m24-03',
  },

  {
    ...P,
    id: 'ref-promise-resolve',
    slug: 'promise-resolve',
    name: 'Promise.resolve()',
    aliases: ['Promise.resolve', 'Promise.reject', 'resolved promise'],
    topicIds: ['promises'],
    syntax: 'Promise.resolve(value)\nPromise.reject(reason)',
    summary: 'Creates an already-settled promise. `resolve` fulfils with a value; `reject` rejects with a reason.',
    parameters: [
      { name: 'value', description: 'The fulfilment value. If it is already a promise it is returned **as-is**; if it is a thenable it is adopted.' },
      { name: 'reason', description: 'For `Promise.reject`. Should be an `Error`.' },
    ],
    returns: 'A settled promise.',
    description: [
      '`Promise.resolve(p)` where `p` is already a native promise returns **that same promise object**, not a wrapper. This makes it a cheap way to normalise a value that may or may not be a promise.',
      'For a **thenable** — any object with a callable `then` — it adopts the thenable\'s eventual state, which is how promises from other libraries interoperate.',
      '`Promise.reject(x)` never unwraps: passing a promise gives you a promise rejected **with a promise as its reason**, which is almost never intended.',
      'They are the standard way to start a chain, to stub an async function in a test, or to return early from a function that must always return a promise.',
      'A `Promise.reject()` with no handler attached in the same turn produces an unhandled rejection, even if you attach a `catch` later.',
    ],
    examples: [
      {
        code: [
          'const p = Promise.resolve(1);',
          'console.log(Promise.resolve(p) === p);',
          '',
          'const thenable = { then(res) { res("adopted"); } };',
          'Promise.resolve(thenable).then((v) => console.log("A:", v));',
          '',
          'Promise.reject(new Error("nope")).catch((e) => console.log("B:", e.message));',
          '',
          'console.log("sync");',
        ].join('\n'),
        output: 'true\nsync\nB: nope\nA: adopted',
        caption: 'Adopting a thenable costs an extra tick, so it settles after the plain rejection.',
      },
    ],
    caveats: ['`Promise.reject` does not unwrap a promise passed as the reason.'],
    commonMistakes: ['Wrapping an existing promise in `new Promise` instead of using `Promise.resolve`.'],
    relatedEntries: ['ref-promise-ctor', 'ref-promise-all'],
    lessonId: 'l-m24-01',
  },

  {
    ...P,
    id: 'ref-promise-all',
    slug: 'promise-all',
    name: 'Promise.all()',
    aliases: ['Promise.all', 'wait for all promises', 'parallel requests'],
    topicIds: ['promises', 'async-await'],
    syntax: 'Promise.all(iterable)',
    summary: 'Takes an iterable of values, and fulfils with an array of their results **in input order** once every one has fulfilled. Rejects as soon as any one rejects.',
    parameters: [{ name: 'iterable', description: 'Any iterable — usually an array. Non-promise values are accepted and passed through via `Promise.resolve`.' }],
    returns: 'A promise fulfilling with an array of results **ordered to match the input**, regardless of which settled first. Rejects with the **first** rejection reason.',
    description: [
      'The output order follows the **input** order, not completion order. That guarantee is what makes destructuring the result safe: `const [user, posts] = await Promise.all([getUser(), getPosts()])`.',
      'Non-promise values in the iterable are fine — each element is passed through `Promise.resolve` — so a mixed array works.',
      'It **rejects on the first rejection**, and the rejection reason is that single error, not an array. Any results that had already arrived are discarded.',
      'It does **not cancel** the remaining operations. They keep running to completion, their side effects still happen, and their results are simply ignored. If a later one also rejects, that rejection is not reported and may surface as unhandled.',
      'An **empty iterable fulfils immediately** with `[]`.',
      'It does not by itself create concurrency — it observes work that has already started. `Promise.all([a(), b()])` is concurrent because both calls were made before `all` was reached; `await a(); await b();` is sequential for the same reason.',
    ],
    examples: [
      {
        code: [
          'const slow = new Promise((r) => setTimeout(() => r("slow"), 20));',
          'const fast = Promise.resolve("fast");',
          '',
          'Promise.all([slow, fast, "plain"]).then((values) => {',
          '  console.log("order follows input:", values);',
          '});',
          '',
          'Promise.all([Promise.resolve(1), Promise.reject(new Error("bad"))])',
          '  .catch((e) => console.log("rejects with one reason:", e.message));',
          '',
          'Promise.all([]).then((v) => console.log("empty:", v));',
        ].join('\n'),
        output: 'empty: []\nrejects with one reason: bad\norder follows input: ["slow", "fast", "plain"]',
        caption: 'The slow promise is still first in the output, because it was first in the input.',
      },
    ],
    caveats: [
      'Rejects with a single reason, not an array of errors.',
      'Does not cancel the other operations.',
      'An empty input fulfils with `[]` immediately.',
    ],
    commonMistakes: ['Describing it as "running promises in parallel" — it awaits work that is already running.'],
    relatedEntries: ['ref-promise-allsettled', 'ref-promise-race', 'ref-promise-any'],
    lessonId: 'l-m24-04',
  },

  {
    ...P,
    id: 'ref-promise-allsettled',
    slug: 'promise-allsettled',
    name: 'Promise.allSettled()',
    aliases: ['Promise.allSettled', 'wait for all outcomes', 'partial failure'],
    topicIds: ['promises'],
    syntax: 'Promise.allSettled(iterable)',
    summary: 'Waits for every input to settle and fulfils with a status descriptor for each. It never rejects because an input rejected.',
    parameters: [{ name: 'iterable', description: 'Any iterable of promises or plain values.' }],
    returns: 'A promise fulfilling with an array of `{ status: "fulfilled", value }` or `{ status: "rejected", reason }` objects, in input order.',
    description: [
      'Use it when **partial success is useful**: a dashboard of independent widgets, a batch upload where you want to report which items failed. `Promise.all` would discard every success as soon as one failed.',
      'It only rejects if the argument is not iterable — never because an element rejected.',
      'Because every outcome is captured, no rejection goes unhandled, which also makes it a way to avoid unhandled-rejection warnings for fire-and-forget batches.',
      'Each result must be inspected before use; the value is on `.value` only for the fulfilled ones.',
    ],
    examples: [
      {
        code: [
          'Promise.allSettled([',
          '  Promise.resolve("ok"),',
          '  Promise.reject(new Error("bad")),',
          ']).then((results) => {',
          '  console.log(results.map((r) => r.status));',
          '  console.log(results[0].value, results[1].reason.message);',
          '',
          '  const ok = results.filter((r) => r.status === "fulfilled").map((r) => r.value);',
          '  console.log("succeeded:", ok);',
          '});',
        ].join('\n'),
        output: '["fulfilled", "rejected"]\nok bad\nsucceeded: ["ok"]',
        caption: 'Every outcome is reported rather than the first failure winning.',
      },
    ],
    caveats: ['Always fulfils — a `catch` on it will almost never run.'],
    commonMistakes: ['Reading `.value` without checking `.status` first.'],
    relatedEntries: ['ref-promise-all', 'ref-promise-any'],
    lessonId: 'l-m24-04',
  },

  {
    ...P,
    id: 'ref-promise-race',
    slug: 'promise-race',
    name: 'Promise.race()',
    aliases: ['Promise.race', 'first to settle', 'promise timeout'],
    topicIds: ['promises'],
    syntax: 'Promise.race(iterable)',
    summary: 'Settles as soon as the **first** input settles — with that result, whether it fulfilled or rejected.',
    parameters: [{ name: 'iterable', description: 'Any iterable of promises or plain values.' }],
    returns: 'A promise settling with the outcome of whichever input settled first.',
    description: [
      'The distinction from `Promise.any` is the whole entry: `race` takes the first **settlement** of either kind, so a fast rejection wins. `any` takes the first **fulfilment** and ignores rejections until every input has failed.',
      'Its canonical use is a timeout: race the real work against a promise that rejects after N milliseconds.',
      'The losing operations are **not cancelled** — they run to completion and their results are discarded. A timeout implemented this way stops you waiting but does not stop the request; pair it with `AbortController` to actually free the connection.',
      'An **empty iterable produces a promise that never settles**, which is a silent hang rather than an error.',
      'If any input is a non-promise value, it settles immediately and wins outright.',
    ],
    examples: [
      {
        code: [
          'const slow = new Promise((r) => setTimeout(() => r("slow"), 50));',
          'const quickFail = new Promise((_, rej) =>',
          '  setTimeout(() => rej(new Error("timeout")), 10),',
          ');',
          '',
          'Promise.race([slow, quickFail])',
          '  .then((v) => console.log("won:", v))',
          '  .catch((e) => console.log("lost:", e.message));',
          '',
          'Promise.race([Promise.resolve("instant"), slow])',
          '  .then((v) => console.log("instant wins:", v));',
        ].join('\n'),
        output: 'instant wins: instant\nlost: timeout',
        caption: 'A rejection can win the race — that is how the timeout pattern works.',
      },
    ],
    caveats: [
      'An empty iterable never settles.',
      'Losers keep running — combine with `AbortController` to truly cancel.',
    ],
    commonMistakes: ['Using `race` where `any` was meant, so one fast failure wins.'],
    relatedEntries: ['ref-promise-any', 'ref-promise-all'],
    lessonId: 'l-m24-04',
  },

  {
    ...P,
    id: 'ref-promise-any',
    slug: 'promise-any',
    name: 'Promise.any()',
    aliases: ['Promise.any', 'first success', 'first fulfilment'],
    topicIds: ['promises'],
    syntax: 'Promise.any(iterable)',
    summary: 'Fulfils with the first input to **fulfil**, ignoring rejections. Rejects only if every input rejects.',
    parameters: [{ name: 'iterable', description: 'Any iterable of promises or plain values.' }],
    returns: 'A promise fulfilling with the first fulfilment value, or rejecting with an `AggregateError` whose `errors` array holds every reason.',
    description: [
      'This is "first success wins", which is what you want for redundant sources — several mirrors of the same resource, or a cache and a network fetch racing.',
      'Rejections are tolerated until they are all that is left. Only when **every** input has rejected does it reject, and the reason is an `AggregateError` with an `errors` array in input order.',
      'An **empty iterable rejects immediately** with an `AggregateError` — unlike `race`, which hangs, and `all`, which fulfils.',
      'Contrast with `race`: if the first thing to settle is a rejection, `race` rejects and `any` keeps waiting.',
    ],
    examples: [
      {
        code: [
          'Promise.any([',
          '  Promise.reject(new Error("a")),',
          '  Promise.resolve("winner"),',
          ']).then((v) => console.log("A:", v));',
          '',
          'Promise.any([',
          '  Promise.reject(new Error("x")),',
          '  Promise.reject(new Error("y")),',
          ']).catch((e) => {',
          '  console.log("B:", e.constructor.name);',
          '  console.log("B reasons:", e.errors.map((r) => r.message));',
          '});',
        ].join('\n'),
        output: 'A: winner\nB: AggregateError\nB reasons: ["x", "y"]',
        caption: 'Rejections are ignored until every input has failed.',
      },
    ],
    caveats: [
      'An empty iterable rejects with an `AggregateError`.',
      'ES2021 — check runtime support.',
    ],
    commonMistakes: ['Confusing it with `race`, which settles on the first result of either kind.'],
    relatedEntries: ['ref-promise-race', 'ref-promise-allsettled', 'ref-error-aggregate'],
    lessonId: 'l-m24-04',
  },

  /* ---------------------------------------------------------------- Error */
  {
    ...X,
    id: 'ref-error-ctor',
    slug: 'error-constructor',
    name: 'Error()',
    aliases: ['new Error', 'throw error', 'error cause', 'custom error'],
    topicIds: ['errors'],
    syntax: 'new Error(message)\nnew Error(message, { cause })',
    summary: 'Creates an error object carrying a message, a stack trace and optionally the underlying `cause`.',
    parameters: [
      { name: 'message', optional: true, description: 'A human-readable description. Available as `error.message`.' },
      { name: 'options', optional: true, description: 'An object with a `cause` property holding the original error being wrapped.' },
    ],
    returns: 'An `Error` instance with `name`, `message`, `stack` and optionally `cause`.',
    description: [
      'Always throw an `Error`, never a string. Only an `Error` carries a stack trace, and `catch` blocks throughout the ecosystem assume `err.message` exists.',
      '`cause` is how you add context without destroying the original. `throw new Error("Loading user failed", { cause: err })` keeps the underlying failure inspectable at `err.cause`, and modern consoles print the whole chain.',
      '`stack` is **not standardised** — its format varies by engine, and it should be treated as diagnostic text, never parsed for control flow.',
      'Subclass for domain errors: `class HttpError extends Error { constructor(status, msg) { super(msg); this.name = "HttpError"; this.status = status; } }`. Setting `name` explicitly matters, because it is what appears in the stack trace and in `String(err)`.',
      'A subclass instance is `instanceof` both its own class and `Error`, which is what lets callers branch on error type instead of matching message strings.',
    ],
    examples: [
      {
        code: [
          'class HttpError extends Error {',
          '  constructor(status, message) {',
          '    super(message);',
          '    this.name = "HttpError";',
          '    this.status = status;',
          '  }',
          '}',
          '',
          'try {',
          '  try {',
          '    throw new HttpError(404, "Not found");',
          '  } catch (err) {',
          '    throw new Error("Loading user failed", { cause: err });',
          '  }',
          '} catch (err) {',
          '  console.log(err.message);',
          '  console.log(err.cause.name, err.cause.status);',
          '  console.log(err.cause instanceof Error);',
          '}',
        ].join('\n'),
        output: 'Loading user failed\nHttpError 404\ntrue',
        caption: 'cause preserves the original error while adding context.',
      },
    ],
    caveats: [
      '`stack` format is engine-specific — never parse it.',
      'A subclass must set `this.name` itself; it does not default to the class name.',
      '`cause` needs ES2022.',
    ],
    commonMistakes: ['Throwing a string.', 'Wrapping an error without `cause`, losing the original.'],
    relatedEntries: ['ref-error-types', 'ref-error-aggregate', 'ref-promise-catch'],
    lessonId: 'l-m22-02',
  },

  {
    ...X,
    id: 'ref-error-types',
    slug: 'error-types',
    name: 'TypeError',
    aliases: ['ReferenceError', 'SyntaxError', 'RangeError', 'built-in errors', 'error types'],
    topicIds: ['errors', 'debugging'],
    syntax: 'new TypeError(message)\nnew ReferenceError(message)\nnew RangeError(message)',
    summary: 'The built-in error subclasses. Which one an engine throws is a strong hint about what actually went wrong.',
    parameters: [{ name: 'message', optional: true, description: 'A human-readable description.' }],
    returns: 'An error instance of that subclass. All are `instanceof Error`.',
    description: [
      '**`TypeError`** — a value is not of the expected type, or an operation is not allowed on it. `undefined.x`, calling a non-function, writing to a frozen object in strict mode, `Object.keys(null)`. By far the most common at runtime.',
      '**`ReferenceError`** — the identifier does not resolve. An undeclared variable, or accessing a `let`/`const` binding in its temporal dead zone.',
      '**`SyntaxError`** — the code could not be parsed. Thrown at parse time, so it cannot be caught by a `try` in the same file — but `JSON.parse` throws one at runtime, which can be caught.',
      '**`RangeError`** — a value is outside its allowed range. `arr.length = -1`, `(1).toFixed(101)`, `"x".repeat(-1)`, and stack overflow from infinite recursion.',
      'They are the right classes to throw from your own validation too: a wrong type is a `TypeError`, an out-of-range number is a `RangeError`. Using the accurate class communicates more than a generic `Error`.',
      '`URIError` and `EvalError` also exist but are rarely encountered.',
    ],
    examples: [
      {
        code: [
          'const show = (fn) => {',
          '  try { fn(); } catch (err) { console.log(err.constructor.name); }',
          '};',
          '',
          'show(() => undefined.x);',
          'show(() => notDeclared);',
          'show(() => JSON.parse("{"));',
          'show(() => "x".repeat(-1));',
          'show(() => { const a = []; a.length = -1; });',
          '',
          'console.log(new TypeError("x") instanceof Error);',
        ].join('\n'),
        output: 'TypeError\nReferenceError\nSyntaxError\nRangeError\nRangeError\ntrue',
        caption: 'The class an engine chooses tells you which kind of mistake it was.',
      },
    ],
    caveats: ['A parse-time `SyntaxError` cannot be caught by code in the same file.'],
    commonMistakes: ['Throwing a generic `Error` where a `TypeError` or `RangeError` would communicate the problem.'],
    relatedEntries: ['ref-error-ctor', 'ref-json-parse'],
    lessonId: 'l-m22-01',
  },

  {
    ...X,
    id: 'ref-error-aggregate',
    slug: 'aggregate-error',
    name: 'AggregateError',
    aliases: ['AggregateError', 'multiple errors'],
    topicIds: ['errors', 'promises'],
    syntax: 'new AggregateError(errors)\nnew AggregateError(errors, message)',
    summary: 'An error that carries **several** errors at once, in an `errors` array. Produced by `Promise.any()` when every input rejects.',
    parameters: [
      { name: 'errors', description: 'An iterable of the individual errors. Exposed as the `errors` array property.' },
      { name: 'message', optional: true, description: 'A description of the combined failure.' },
    ],
    returns: 'An `AggregateError` instance, which is `instanceof Error`.',
    description: [
      'You will most often meet it as the rejection reason from `Promise.any()`, where the `errors` array holds one reason per input in the original order.',
      'It is also the right thing to throw from your own code when several independent operations failed and reporting only the first would lose information — validating many fields, or a batch operation.',
      'The individual errors are on `.errors`, not on `.cause`. `cause` is for a single underlying error; `AggregateError` is for a set of siblings.',
      'Available from ES2021.',
    ],
    examples: [
      {
        code: [
          'const failures = [new Error("name required"), new Error("email invalid")];',
          'const agg = new AggregateError(failures, "Validation failed");',
          '',
          'console.log(agg.name, agg.message);',
          'console.log(agg.errors.length);',
          'console.log(agg.errors.map((e) => e.message));',
          'console.log(agg instanceof Error);',
        ].join('\n'),
        output: 'AggregateError Validation failed\n2\n["name required", "email invalid"]\ntrue',
        caption: 'Siblings go on .errors; a single underlying error goes on .cause.',
      },
    ],
    caveats: ['ES2021 — check runtime support.'],
    commonMistakes: ['Looking for the individual reasons on `.cause`.'],
    relatedEntries: ['ref-promise-any', 'ref-error-ctor'],
    lessonId: 'l-m22-04',
  },
];
