import { REFERENCE_CATEGORY as C, REFERENCE_ENV as E } from '../schema/types.js';

/**
 * String reference.
 *
 * Strings are immutable in JavaScript, so **every** method here returns a new
 * string and none of them modify the receiver. That single fact is repeated in
 * the `mutates` flag rather than in prose, which is exactly what the flag is for.
 *
 * All of these are ECMAScript, available in every runtime.
 */

const S = { category: C.STRING, environment: E.ECMASCRIPT, mutates: false };

export default [
  {
    ...S,
    id: 'ref-string-ctor',
    slug: 'string-function',
    name: 'String()',
    aliases: ['String conversion', 'to string'],
    topicIds: ['strings', 'coercion', 'types'],
    syntax: 'String(value)',
    summary: 'Converts any value to its string representation. Called without `new`, it is the explicit, safe way to stringify a value.',
    parameters: [{ name: 'value', description: 'Any value. `null` and `undefined` are handled, unlike `value.toString()`.' }],
    returns: 'A primitive string.',
    description: [
      'Prefer `String(value)` over `value.toString()` and over `"" + value`. `toString()` throws on `null` and `undefined`, and `"" + value` is the same conversion written less clearly.',
      'For objects, `String()` runs the `ToPrimitive` algorithm with a string hint: it tries `Symbol.toPrimitive`, then `toString()`, then `valueOf()`. A plain object has no useful `toString`, so it becomes `"[object Object]"`.',
      'Called with `new`, `new String("a")` creates a **String object** wrapper rather than a primitive. That object is truthy even when empty and is not `===` to the primitive, which is why the wrapper form should never be used.',
    ],
    examples: [
      {
        code: [
          'console.log(String(42));',
          'console.log(String(null));',
          'console.log(String(undefined));',
          'console.log(String([1, 2]));',
          'console.log(String({}));',
          'console.log(String(Symbol("id")));',
        ].join('\n'),
        output: '42\nnull\nundefined\n1,2\n[object Object]\nSymbol(id)',
        caption: 'String() handles every value, including the ones that break toString().',
      },
    ],
    caveats: [
      'A symbol can only be converted with `String(sym)`; `"" + sym` throws a `TypeError`.',
      '`String([1, 2])` is `"1,2"` — arrays join with commas and no spaces.',
      'Never use `new String()`. The wrapper object is truthy even for `""` and fails `===` against the primitive.',
    ],
    commonMistakes: ['Calling `value.toString()` on something that might be `null` or `undefined`.'],
    relatedEntries: ['ref-string-tostring-tag'],
    lessonId: 'l-m03-01',
  },

  {
    ...S,
    id: 'ref-string-length',
    slug: 'string-length',
    name: 'String.prototype.length',
    aliases: ['string length', 'str.length'],
    topicIds: ['strings'],
    syntax: 'str.length',
    summary: 'The number of UTF-16 code units in the string — not necessarily the number of characters a reader would count.',
    parameters: [],
    returns: 'A non-negative integer.',
    description: [
      '`length` counts UTF-16 code units. For ASCII and most Latin text that equals the visible character count, so the distinction rarely surfaces.',
      'Characters outside the Basic Multilingual Plane — most emoji, many CJK extensions, mathematical symbols — are stored as a **surrogate pair** of two code units, so they count as 2. Combining marks (an "e" plus a combining accent) count separately again.',
      'For a count that matches what a person sees, iterate with `[...str]`, which yields code points, or use `Intl.Segmenter` with `granularity: "grapheme"` for full correctness including emoji sequences.',
      '`length` is a read-only own property of the string; assigning to it silently does nothing in sloppy mode and throws in strict mode.',
    ],
    examples: [
      {
        code: [
          'console.log("hello".length);',
          'console.log("café".length);',
          'console.log("🙂".length);',
          'console.log([..."🙂"].length);',
        ].join('\n'),
        output: '5\n4\n2\n1',
        caption: 'An emoji is one character to a reader and two code units to length.',
      },
    ],
    caveats: [
      'Emoji and other astral characters have a `length` of 2 or more.',
      'Slicing at an arbitrary index can split a surrogate pair and produce a broken character.',
    ],
    commonMistakes: ['Using `length` to validate a maximum character count on user input that may contain emoji.'],
    relatedEntries: ['ref-string-at', 'ref-string-slice'],
    lessonId: 'l-m05-03',
  },

  {
    ...S,
    id: 'ref-string-at',
    slug: 'string-prototype-at',
    name: 'String.prototype.at()',
    aliases: ['String.at', 'string at'],
    topicIds: ['strings'],
    syntax: 'str.at(index)',
    summary: 'Returns the character at an index, accepting negative indices that count back from the end.',
    parameters: [{ name: 'index', description: 'Integer position. Negative values count from the end, so `-1` is the last character.' }],
    returns: 'A one-code-unit string, or `undefined` if the index is out of range.',
    description: [
      '`at()` exists because neither older option does the intuitive thing with a negative index: `str[-1]` is `undefined` (there is no such property) and `str.charAt(-1)` is `""`.',
      'Like bracket access, it operates on UTF-16 code units, so `at(-1)` on a string ending in an emoji returns the trailing surrogate half rather than the emoji.',
      'It returns `undefined` — not `""` — for an out-of-range index, which makes a missing character distinguishable from an empty result.',
    ],
    examples: [
      {
        code: [
          'const word = "reference";',
          '',
          'console.log(word.at(0));',
          'console.log(word.at(-1));',
          'console.log(word.at(99));',
          'console.log(word[-1]);',
        ].join('\n'),
        output: 'r\ne\nundefined\nundefined',
        caption: 'at() supports negative indices; bracket access does not.',
      },
    ],
    caveats: ['Indexes code units, so `at(-1)` can return half of an emoji.'],
    commonMistakes: ['Expecting `str[-1]` to return the last character.'],
    relatedEntries: ['ref-string-charat', 'ref-string-length'],
    lessonId: 'l-m05-03',
  },

  {
    ...S,
    id: 'ref-string-charat',
    slug: 'string-prototype-charat',
    name: 'String.prototype.charAt()',
    aliases: ['String.charAt', 'charAt'],
    topicIds: ['strings'],
    syntax: 'str.charAt(index)',
    summary: 'Returns the character at a non-negative index, or an empty string when the index is out of range.',
    parameters: [{ name: 'index', optional: true, description: 'Integer position, defaulting to `0`. Negative and out-of-range values yield `""`.' }],
    returns: 'A one-code-unit string, or `""` if the index is out of range.',
    description: [
      'Functionally equivalent to bracket access for valid indices. The difference is the out-of-range result: `charAt` gives `""` while `str[i]` gives `undefined`.',
      'It has no negative-index support, which is what `at()` was added for. In new code `at()` or bracket access is clearer; `charAt` mostly survives in older codebases.',
    ],
    examples: [
      {
        code: [
          'const s = "abc";',
          '',
          'console.log(s.charAt(1));',
          'console.log(s.charAt(9));',
          'console.log(s[9]);',
          'console.log(s.charAt(-1));',
        ].join('\n'),
        output: 'b\n\nundefined\n',
        caption: 'Out of range gives "" from charAt and undefined from bracket access.',
      },
    ],
    caveats: ['The empty-string result for a missing index is easy to miss, because `""` is falsy just like `undefined`.'],
    commonMistakes: ['Expecting `charAt(-1)` to read from the end.'],
    relatedEntries: ['ref-string-at', 'ref-string-codepointat'],
    lessonId: 'l-m05-03',
  },

  {
    ...S,
    id: 'ref-string-codepointat',
    slug: 'string-prototype-codepointat',
    name: 'String.prototype.codePointAt()',
    aliases: ['String.codePointAt', 'codePointAt', 'charCodeAt'],
    topicIds: ['strings'],
    syntax: 'str.codePointAt(index)',
    summary: 'Returns the full Unicode code point starting at an index, correctly handling surrogate pairs.',
    parameters: [{ name: 'index', optional: true, description: 'Position of the code unit to read, defaulting to `0`.' }],
    returns: 'A number — the code point — or `undefined` if the index is out of range.',
    description: [
      '`codePointAt()` differs from the older `charCodeAt()` in exactly one way that matters: when the index points at the first half of a surrogate pair, it returns the combined code point rather than the lone surrogate value.',
      'For characters in the Basic Multilingual Plane the two are identical, which is why the difference only appears with emoji and other astral characters.',
      '`String.fromCodePoint()` is the inverse, and is the counterpart to the older `String.fromCharCode()`.',
    ],
    examples: [
      {
        code: [
          'console.log("A".codePointAt(0));',
          'console.log("🙂".codePointAt(0));',
          'console.log("🙂".charCodeAt(0));',
          'console.log(String.fromCodePoint(128578));',
        ].join('\n'),
        output: '65\n128578\n55357\n🙂',
        caption: 'charCodeAt sees half a surrogate pair; codePointAt sees the character.',
      },
    ],
    caveats: ['The index is still a code-unit index, so reading the second half of a pair returns that lone surrogate.'],
    commonMistakes: ['Using `charCodeAt` on text that may contain emoji.'],
    relatedEntries: ['ref-string-charat', 'ref-string-length'],
    lessonId: 'l-m05-06',
  },

  {
    ...S,
    id: 'ref-string-includes',
    slug: 'string-prototype-includes',
    name: 'String.prototype.includes()',
    aliases: ['String.includes', 'string includes', 'contains'],
    topicIds: ['strings'],
    syntax: 'str.includes(searchString)\nstr.includes(searchString, position)',
    summary: 'Reports whether the string contains another string, as a boolean.',
    parameters: [
      { name: 'searchString', description: 'The substring to look for. Must be a string — a regular expression throws.' },
      { name: 'position', optional: true, description: 'Index to start searching from, defaulting to `0`.' },
    ],
    returns: '`true` if the substring is found, otherwise `false`.',
    description: [
      'This is the direct replacement for the older `str.indexOf(x) !== -1` idiom, which is easy to write as the buggy `> 0` and then miss matches at index 0.',
      'The comparison is case-sensitive and does no Unicode normalisation. To compare case-insensitively, lowercase both sides first; for accented text that may be composed differently, normalise with `str.normalize()` before comparing.',
      'Passing a regular expression throws a `TypeError` — deliberately, so that `includes` cannot be confused with `search` or `match`.',
    ],
    examples: [
      {
        code: [
          'const title = "Reference Guide";',
          '',
          'console.log(title.includes("Guide"));',
          'console.log(title.includes("guide"));',
          'console.log(title.toLowerCase().includes("guide"));',
          'console.log(title.includes("Reference", 1));',
        ].join('\n'),
        output: 'true\nfalse\ntrue\nfalse',
        caption: 'Case-sensitive; the position argument shifts where the search starts.',
      },
    ],
    caveats: [
      'Case-sensitive and normalisation-sensitive.',
      'Throws `TypeError` if given a regular expression.',
    ],
    commonMistakes: ['Writing `indexOf(x) > 0`, which misses a match at index 0.'],
    relatedEntries: ['ref-string-indexof', 'ref-string-startswith', 'ref-string-search'],
    lessonId: 'l-m05-04',
  },

  {
    ...S,
    id: 'ref-string-startswith',
    slug: 'string-prototype-startswith',
    name: 'String.prototype.startsWith()',
    aliases: ['String.startsWith', 'startsWith'],
    topicIds: ['strings'],
    syntax: 'str.startsWith(searchString)\nstr.startsWith(searchString, position)',
    summary: 'Reports whether the string begins with another string.',
    parameters: [
      { name: 'searchString', description: 'The prefix to test for. A regular expression throws.' },
      { name: 'position', optional: true, description: 'Index to treat as the start of the string, defaulting to `0`.' },
    ],
    returns: '`true` if the string starts with the prefix, otherwise `false`.',
    description: [
      'Clearer and cheaper than `str.slice(0, n) === prefix`, because no substring is allocated.',
      'The `position` argument makes it usable inside a scan: `str.startsWith("--", i)` tests at an arbitrary offset without slicing.',
    ],
    examples: [
      {
        code: [
          'const path = "/api/users/1";',
          '',
          'console.log(path.startsWith("/api"));',
          'console.log(path.startsWith("users"));',
          'console.log(path.startsWith("users", 5));',
        ].join('\n'),
        output: 'true\nfalse\ntrue',
        caption: 'position shifts where "the start" is considered to be.',
      },
    ],
    caveats: ['Case-sensitive.', 'Throws `TypeError` if given a regular expression.'],
    commonMistakes: ['Using it to validate a URL origin — `"https://evil.com/?x=https://good.com"` starts with neither, but prefix checks on URLs are generally unsafe. Parse with `new URL()` instead.'],
    relatedEntries: ['ref-string-endswith', 'ref-string-includes'],
    lessonId: 'l-m05-04',
  },

  {
    ...S,
    id: 'ref-string-endswith',
    slug: 'string-prototype-endswith',
    name: 'String.prototype.endsWith()',
    aliases: ['String.endsWith', 'endsWith'],
    topicIds: ['strings'],
    syntax: 'str.endsWith(searchString)\nstr.endsWith(searchString, endPosition)',
    summary: 'Reports whether the string ends with another string.',
    parameters: [
      { name: 'searchString', description: 'The suffix to test for. A regular expression throws.' },
      { name: 'endPosition', optional: true, description: 'Treat the string as if it were this long, defaulting to `str.length`.' },
    ],
    returns: '`true` if the string ends with the suffix, otherwise `false`.',
    description: [
      'The second argument is an **end** position, not a start position — the opposite of `startsWith`. `str.endsWith("b", 2)` asks whether the first two characters end with `"b"`.',
      'Commonly used for file extensions, though a filename check should be case-insensitive since `.PNG` is as valid as `.png`.',
    ],
    examples: [
      {
        code: [
          'const file = "report.PDF";',
          '',
          'console.log(file.endsWith(".pdf"));',
          'console.log(file.toLowerCase().endsWith(".pdf"));',
          'console.log("abc".endsWith("b", 2));',
        ].join('\n'),
        output: 'false\ntrue\ntrue',
        caption: 'The second argument truncates the string before testing.',
      },
    ],
    caveats: ['The second argument is an end index, unlike `startsWith`, where it is a start index.'],
    commonMistakes: ['Trusting a file extension as a security check — the extension does not determine the content.'],
    relatedEntries: ['ref-string-startswith', 'ref-string-includes'],
    lessonId: 'l-m05-04',
  },

  {
    ...S,
    id: 'ref-string-indexof',
    slug: 'string-prototype-indexof',
    name: 'String.prototype.indexOf()',
    aliases: ['String.indexOf', 'indexOf string'],
    topicIds: ['strings'],
    syntax: 'str.indexOf(searchString)\nstr.indexOf(searchString, position)',
    summary: 'Returns the index of the first occurrence of a substring, or `-1` when it is absent.',
    parameters: [
      { name: 'searchString', description: 'The substring to find. Non-strings are converted, so `indexOf(1)` searches for `"1"`.' },
      { name: 'position', optional: true, description: 'Index to start from, defaulting to `0`.' },
    ],
    returns: 'The zero-based index of the first match, or `-1`.',
    description: [
      'Use `includes()` when you only need to know whether the substring is present. `indexOf` is for when you need the **position**, typically to slice around it.',
      'The `-1` sentinel is the source of a classic bug: `if (str.indexOf(x))` is truthy for every index except `0`, and falsy exactly when the match is at the start. The correct test is `!== -1`.',
      'Repeatedly calling it with an advancing `position` is the standard way to find every occurrence without a regular expression.',
    ],
    examples: [
      {
        code: [
          'const line = "key=value=extra";',
          'const i = line.indexOf("=");',
          '',
          'console.log(i);',
          'console.log(line.slice(0, i));',
          'console.log(line.slice(i + 1));',
          'console.log(line.indexOf("=", i + 1));',
          'console.log(line.indexOf("missing"));',
        ].join('\n'),
        output: '3\nkey\nvalue=extra\n9\n-1',
        caption: 'Splitting on only the first separator — something split() cannot do directly.',
      },
    ],
    caveats: ['`-1` is truthy, so never test the result for truthiness.'],
    commonMistakes: ['Writing `if (str.indexOf(x))` instead of `if (str.indexOf(x) !== -1)`.'],
    relatedEntries: ['ref-string-lastindexof', 'ref-string-includes', 'ref-string-slice'],
    lessonId: 'l-m05-04',
  },

  {
    ...S,
    id: 'ref-string-lastindexof',
    slug: 'string-prototype-lastindexof',
    name: 'String.prototype.lastIndexOf()',
    aliases: ['String.lastIndexOf', 'lastIndexOf'],
    topicIds: ['strings'],
    syntax: 'str.lastIndexOf(searchString)\nstr.lastIndexOf(searchString, position)',
    summary: 'Returns the index of the last occurrence of a substring, or `-1` when it is absent.',
    parameters: [
      { name: 'searchString', description: 'The substring to find.' },
      { name: 'position', optional: true, description: 'The search starts at this index and moves backwards, defaulting to `+Infinity`.' },
    ],
    returns: 'The zero-based index of the last match, or `-1`.',
    description: [
      'The returned index is still counted from the **start** of the string; only the direction of the search differs.',
      'The `position` argument means "the match must begin at or before this index", which is the mirror image of how `indexOf` treats it.',
      'The typical use is splitting on the final separator — a file extension, or the last path segment.',
    ],
    examples: [
      {
        code: [
          'const file = "archive.tar.gz";',
          'const dot = file.lastIndexOf(".");',
          '',
          'console.log(dot);',
          'console.log(file.slice(0, dot));',
          'console.log(file.slice(dot + 1));',
        ].join('\n'),
        output: '11\narchive.tar\ngz',
        caption: 'lastIndexOf finds the final separator, which is what an extension needs.',
      },
    ],
    caveats: ['A file with no dot returns `-1`, and `slice(0, -1)` then silently drops the last character — check for `-1` first.'],
    commonMistakes: ['Not handling `-1`, producing a mangled string instead of an error.'],
    relatedEntries: ['ref-string-indexof', 'ref-string-slice'],
    lessonId: 'l-m05-04',
  },

  {
    ...S,
    id: 'ref-string-slice',
    slug: 'string-prototype-slice',
    name: 'String.prototype.slice()',
    aliases: ['String.slice', 'string slice'],
    topicIds: ['strings'],
    syntax: 'str.slice(start)\nstr.slice(start, end)',
    summary: 'Extracts a section of the string between two indices, supporting negative indices that count from the end.',
    parameters: [
      { name: 'start', optional: true, description: 'Index to begin at, defaulting to `0`. Negative counts from the end.' },
      { name: 'end', optional: true, description: 'Index to stop **before**, defaulting to the end. Negative counts from the end.' },
    ],
    returns: 'A new string. The original is unchanged.',
    description: [
      '`slice` is the one to reach for by default. Its negative-index support makes "everything except the last character" a natural `slice(0, -1)`.',
      'When `start` is greater than `end`, `slice` returns `""` rather than silently swapping them — which is exactly where it differs from `substring`.',
      'The end index is exclusive, so `slice(a, b)` has a length of `b - a` for non-negative in-range arguments.',
    ],
    examples: [
      {
        code: [
          'const s = "javascript";',
          '',
          'console.log(s.slice(0, 4));',
          'console.log(s.slice(4));',
          'console.log(s.slice(-6));',
          'console.log(s.slice(0, -6));',
          'console.log(s.slice(4, 1));',
        ].join('\n'),
        output: 'java\nscript\nscript\njava\n',
        caption: 'Negative indices count from the end; a reversed range gives "".',
      },
    ],
    caveats: [
      'Returns `""` for a reversed range — `substring` would swap the arguments instead.',
      'Cutting between the halves of a surrogate pair produces an invalid lone surrogate.',
    ],
    commonMistakes: ['Assuming `slice` and `substring` behave identically — they differ on negative and reversed arguments.'],
    relatedEntries: ['ref-string-substring', 'ref-string-at', 'ref-string-split'],
    lessonId: 'l-m05-05',
  },

  {
    ...S,
    id: 'ref-string-substring',
    slug: 'string-prototype-substring',
    name: 'String.prototype.substring()',
    aliases: ['String.substring', 'substring'],
    topicIds: ['strings'],
    syntax: 'str.substring(start)\nstr.substring(start, end)',
    summary: 'Extracts a section of the string between two indices, clamping negatives to `0` and swapping reversed arguments.',
    parameters: [
      { name: 'start', description: 'Index to begin at. Negative values and `NaN` are treated as `0`.' },
      { name: 'end', optional: true, description: 'Index to stop before, defaulting to the end. Negative values are treated as `0`.' },
    ],
    returns: 'A new string. The original is unchanged.',
    description: [
      'The two behaviours that distinguish it from `slice`: negative arguments are clamped to `0` instead of counting from the end, and if `start > end` the two are **swapped** rather than producing `""`.',
      'That swapping is occasionally convenient when the two indices come from a selection whose direction is unknown, but it more often hides an off-by-one or a sign error that `slice` would have made obvious.',
      'Prefer `slice` unless the clamping behaviour is specifically what you want.',
    ],
    examples: [
      {
        code: [
          'const s = "javascript";',
          '',
          'console.log(s.substring(0, 4));',
          'console.log(s.substring(4, 1));',
          'console.log(s.slice(4, 1));',
          'console.log(s.substring(-6));',
          'console.log(s.slice(-6));',
        ].join('\n'),
        output: 'java\nava\n\njavascript\nscript',
        caption: 'substring swaps reversed arguments and clamps negatives; slice does neither.',
      },
    ],
    caveats: ['Silently swaps `start` and `end` when they are the wrong way round, which can mask a bug.'],
    commonMistakes: ['Passing a negative index expecting it to count from the end.'],
    relatedEntries: ['ref-string-slice'],
    lessonId: 'l-m05-05',
  },

  {
    ...S,
    id: 'ref-string-split',
    slug: 'string-prototype-split',
    name: 'String.prototype.split()',
    aliases: ['String.split', 'string split'],
    topicIds: ['strings'],
    syntax: 'str.split(separator)\nstr.split(separator, limit)',
    summary: 'Splits the string into an array of substrings around a separator.',
    parameters: [
      { name: 'separator', optional: true, description: 'A string or regular expression to split on. Omitted, the whole string is returned as a single element.' },
      { name: 'limit', optional: true, description: 'Maximum number of elements to return. Extra pieces are discarded, not appended.' },
    ],
    returns: 'A new array of strings.',
    mutates: false,
    description: [
      'Splitting on `""` produces an array of UTF-16 code units, which breaks emoji apart. `[...str]` or `Array.from(str)` splits by code point instead and is almost always what was wanted.',
      'A regular expression separator with a capture group **includes** the captured text in the output, which is a useful way to keep the delimiters.',
      '`limit` truncates rather than merging: `"a,b,c".split(",", 2)` gives `["a", "b"]` and `"c"` is lost. To split on only the first separator, use `indexOf` and two `slice` calls.',
      'Splitting an empty string on a non-empty separator gives `[""]` — an array of length 1, not an empty array. This is the usual reason a "count the items" calculation is off by one for empty input.',
    ],
    examples: [
      {
        code: [
          'console.log("a,b,c".split(","));',
          'console.log("a,b,c".split(",", 2));',
          'console.log("".split(","));',
          'console.log("a1b2c".split(/(\\d)/));',
          'console.log([..."ab🙂"].length);',
          'console.log("ab🙂".split("").length);',
        ].join('\n'),
        output: '["a", "b", "c"]\n["a", "b"]\n[""]\n["a", "1", "b", "2", "c"]\n3\n4',
        caption: 'A capture group keeps the separators; split("") breaks emoji.',
      },
    ],
    caveats: [
      '`"".split(",")` returns `[""]`, not `[]`.',
      '`split("")` splits by code unit and destroys astral characters.',
      '`limit` discards the remainder rather than keeping it as a final element.',
    ],
    commonMistakes: ['Using `split(",", 2)` expecting the rest of the string in the second element.'],
    relatedEntries: ['ref-string-slice', 'ref-string-indexof'],
    lessonId: 'l-m05-06',
  },

  {
    ...S,
    id: 'ref-string-replace',
    slug: 'string-prototype-replace',
    name: 'String.prototype.replace()',
    aliases: ['String.replace', 'string replace'],
    topicIds: ['strings', 'regex'],
    syntax: 'str.replace(pattern, replacement)\nstr.replace(pattern, replacerFn)',
    summary: 'Replaces the **first** match of a string pattern, or every match of a global regular expression, returning a new string.',
    parameters: [
      { name: 'pattern', description: 'A string (matches once, literally) or a `RegExp` (matches once, or every time with the `g` flag).' },
      { name: 'replacement', description: 'A replacement string, where `$&`, `$1`, `$<name>` and `$$` have special meaning — or a function called for each match.' },
    ],
    returns: 'A new string. The original is unchanged.',
    description: [
      'With a **string** pattern only the first occurrence is replaced. This surprises people constantly; `replaceAll` or a `/g` regex is needed for the rest.',
      'Dollar signs in the replacement are special: `$&` is the whole match, `$1`…`$9` are capture groups, `$<name>` is a named group, and `$$` is a literal `$`. When inserting arbitrary user text, use a **replacer function** instead, so a `$&` in the data cannot be interpreted.',
      'A replacer function receives `(match, ...captures, offset, wholeString)` and its return value is used literally, with no dollar-sign processing.',
    ],
    examples: [
      {
        code: [
          'const s = "a-b-c";',
          '',
          'console.log(s.replace("-", "+"));',
          'console.log(s.replace(/-/g, "+"));',
          'console.log("john smith".replace(/(\\w+) (\\w+)/, "$2, $1"));',
          'console.log("a1b2".replace(/\\d/g, (d) => d * 2));',
        ].join('\n'),
        output: 'a+b-c\na+b+c\nsmith, john\na2b4',
        caption: 'A string pattern replaces once; a /g regex replaces every match.',
      },
    ],
    caveats: [
      'A string pattern replaces only the first occurrence.',
      '`$` in the replacement string is interpreted — use a function for untrusted replacement text.',
    ],
    commonMistakes: ['Expecting `replace("a", "b")` to replace every `"a"`.'],
    relatedEntries: ['ref-string-replaceall', 'ref-string-match'],
    lessonId: 'l-m05-06',
  },

  {
    ...S,
    id: 'ref-string-replaceall',
    slug: 'string-prototype-replaceall',
    name: 'String.prototype.replaceAll()',
    aliases: ['String.replaceAll', 'replaceAll'],
    topicIds: ['strings', 'regex'],
    syntax: 'str.replaceAll(pattern, replacement)\nstr.replaceAll(pattern, replacerFn)',
    summary: 'Replaces every occurrence of a pattern, returning a new string.',
    parameters: [
      { name: 'pattern', description: 'A string, or a **global** `RegExp`. A non-global regex throws a `TypeError`.' },
      { name: 'replacement', description: 'A replacement string with the same `$` substitutions as `replace`, or a replacer function.' },
    ],
    returns: 'A new string. The original is unchanged.',
    description: [
      'Added specifically because the string form of `replace` replacing only the first match was such a persistent source of bugs.',
      'It deliberately throws when handed a non-global regular expression rather than silently replacing once — the mirror of the confusion it was designed to remove.',
      'For a plain string pattern this is simpler and safer than building a regex, which would require escaping any regex metacharacters in the pattern.',
    ],
    examples: [
      {
        code: [
          'console.log("a-b-c".replaceAll("-", "+"));',
          'console.log("1.2.3".replaceAll(".", "_"));',
          'try {',
          '  "abc".replaceAll(/b/, "x");',
          '} catch (err) {',
          '  console.log(err.constructor.name);',
          '}',
        ].join('\n'),
        output: 'a+b+c\n1_2_3\nTypeError',
        caption: 'A string pattern needs no escaping; a non-global regex is rejected.',
      },
    ],
    caveats: ['Throws `TypeError` for a regular expression without the `g` flag.'],
    commonMistakes: ['Building a regex from user input without escaping metacharacters — pass the string directly instead.'],
    relatedEntries: ['ref-string-replace'],
    lessonId: 'l-m05-06',
  },

  {
    ...S,
    id: 'ref-string-match',
    slug: 'string-prototype-match',
    name: 'String.prototype.match()',
    aliases: ['String.match', 'string match'],
    topicIds: ['strings', 'regex'],
    syntax: 'str.match(regexp)',
    summary: 'Matches a regular expression against the string. The shape of the result changes completely depending on the `g` flag.',
    parameters: [{ name: 'regexp', description: 'A `RegExp`. A string is converted to one, so metacharacters are interpreted.' }],
    returns: 'Without `g`: a match array with `index`, `input` and `groups`, or `null`. With `g`: a flat array of matched strings, or `null`.',
    description: [
      'This dual return type is the main hazard. Without `g` you get a rich single match whose element `0` is the whole match and `1`… are the capture groups. With `g` you get only the matched strings — **capture groups are discarded entirely**.',
      'It returns `null` rather than `[]` when nothing matches, so the result must be checked before it is indexed or iterated.',
      'When you need every match **and** its groups, use `matchAll()`, which is unambiguous and returns an empty iterator instead of `null`.',
    ],
    examples: [
      {
        code: [
          'const s = "a1b22c";',
          '',
          'const one = s.match(/([a-z])(\\d+)/);',
          'console.log(one[0], one[1], one[2], one.index);',
          '',
          'console.log(s.match(/\\d+/g));',
          'console.log(s.match(/z/));',
        ].join('\n'),
        output: 'a1 a 1 0\n["1", "22"]\nnull',
        caption: 'Without /g: one rich match. With /g: strings only, groups lost.',
      },
    ],
    caveats: [
      'Returns `null`, not an empty array, when there is no match.',
      'With `g`, capture groups are not returned at all.',
    ],
    commonMistakes: ['Iterating the result without checking for `null` first.'],
    relatedEntries: ['ref-string-matchall', 'ref-string-search'],
    lessonId: 'l-m16-07',
  },

  {
    ...S,
    id: 'ref-string-matchall',
    slug: 'string-prototype-matchall',
    name: 'String.prototype.matchAll()',
    aliases: ['String.matchAll', 'matchAll'],
    topicIds: ['strings', 'regex'],
    syntax: 'str.matchAll(regexp)',
    summary: 'Returns an iterator of every match, each a full match array with capture groups, index and named groups.',
    parameters: [{ name: 'regexp', description: 'A **global** `RegExp`. A non-global regex throws a `TypeError`.' }],
    returns: 'An iterator of match arrays. Empty when nothing matches — never `null`.',
    description: [
      'This is the method to use when you need every match together with its capture groups, which `match(/…/g)` cannot give you.',
      'It returns a lazy iterator, so spread it or use `for...of`. Because it is an iterator it can only be consumed once; a second iteration yields nothing.',
      'Unlike a `while` loop over `regexp.exec()`, it does not depend on the shared `lastIndex` of the regex object, which removes a well-known source of infinite loops and cross-call interference.',
    ],
    examples: [
      {
        code: [
          'const s = "a1 b22 c333";',
          '',
          'for (const m of s.matchAll(/([a-z])(\\d+)/g)) {',
          '  console.log(m[1], m[2], m.index);',
          '}',
          '',
          'console.log([..."x".matchAll(/\\d/g)].length);',
        ].join('\n'),
        output: 'a 1 0\nb 22 3\nc 333 7\n0',
        caption: 'Every match with its groups, and an empty result instead of null.',
      },
    ],
    caveats: [
      'Requires the `g` flag; throws `TypeError` without it.',
      'The iterator is single-use — spread it into an array if you need it twice.',
    ],
    commonMistakes: ['Reusing the returned iterator after already consuming it.'],
    relatedEntries: ['ref-string-match'],
    lessonId: 'l-m16-07',
  },

  {
    ...S,
    id: 'ref-string-search',
    slug: 'string-prototype-search',
    name: 'String.prototype.search()',
    aliases: ['String.search', 'string search'],
    topicIds: ['strings', 'regex'],
    syntax: 'str.search(regexp)',
    summary: 'Returns the index of the first regular-expression match, or `-1`.',
    parameters: [{ name: 'regexp', description: 'A `RegExp`. A string is converted to one, so metacharacters are interpreted.' }],
    returns: 'The index of the first match, or `-1`.',
    description: [
      'Think of it as `indexOf` for patterns: same `-1` sentinel, same "position only" result.',
      'The `g` flag is ignored — it always reports the first match and never consults or updates `lastIndex`.',
      'If you need the matched text and not just its position, use `match` or `exec`.',
    ],
    examples: [
      {
        code: [
          'const s = "order #4821 shipped";',
          '',
          'console.log(s.search(/\\d/));',
          'console.log(s.search(/z\\d/));',
          'console.log(s.slice(s.search(/\\d/)));',
        ].join('\n'),
        output: '7\n-1\n4821 shipped',
        caption: 'search gives a position; slice turns it into the text.',
      },
    ],
    caveats: ['A string argument is converted to a regex, so `search(".")` matches the first character, not a literal dot.'],
    commonMistakes: ['Passing a string containing regex metacharacters and expecting a literal search — use `indexOf` for that.'],
    relatedEntries: ['ref-string-indexof', 'ref-string-match'],
    lessonId: 'l-m16-07',
  },

  {
    ...S,
    id: 'ref-string-touppercase',
    slug: 'string-prototype-touppercase',
    name: 'String.prototype.toUpperCase()',
    aliases: ['String.toUpperCase', 'toUpperCase', 'uppercase'],
    topicIds: ['strings'],
    syntax: 'str.toUpperCase()',
    summary: 'Returns a new string with every character converted to upper case.',
    parameters: [],
    returns: 'A new upper-cased string. The original is unchanged.',
    description: [
      'Uses locale-independent Unicode case mapping. `toLocaleUpperCase()` is the variant that respects locale rules — the standard example being Turkish, where dotless `ı` uppercases differently.',
      'Case conversion is not always length-preserving: the German `ß` uppercases to `SS`, so the result can be longer than the input.',
      'For case-insensitive comparison, lowercasing both sides is the conventional choice, and `localeCompare` with `sensitivity: "base"` is the correct one for user-facing sorting.',
    ],
    examples: [
      {
        code: [
          'const name = "ada";',
          '',
          'console.log(name.toUpperCase());',
          'console.log(name);',
          'console.log("straße".toUpperCase());',
          'console.log("straße".toUpperCase().length);',
        ].join('\n'),
        output: 'ADA\nada\nSTRASSE\n7',
        caption: 'Strings are immutable, and case conversion can change the length.',
      },
    ],
    caveats: ['Not length-preserving for every language.', 'Locale-independent — use `toLocaleUpperCase` where locale rules matter.'],
    commonMistakes: ['Calling it without using the return value, expecting the original to change.'],
    relatedEntries: ['ref-string-tolowercase', 'ref-string-localecompare'],
    lessonId: 'l-m05-05',
  },

  {
    ...S,
    id: 'ref-string-tolowercase',
    slug: 'string-prototype-tolowercase',
    name: 'String.prototype.toLowerCase()',
    aliases: ['String.toLowerCase', 'toLowerCase', 'lowercase'],
    topicIds: ['strings'],
    syntax: 'str.toLowerCase()',
    summary: 'Returns a new string with every character converted to lower case.',
    parameters: [],
    returns: 'A new lower-cased string. The original is unchanged.',
    description: [
      'The standard tool for case-insensitive comparison and for normalising keys, email addresses and search terms.',
      'Like `toUpperCase`, it applies locale-independent Unicode rules; `toLocaleLowerCase()` applies locale-specific ones.',
      'Lowercasing is not a substitute for normalisation. `"café"` written with a combining accent and `"café"` written precomposed lowercase to different strings — call `normalize("NFC")` first when comparing text from different sources.',
    ],
    examples: [
      {
        code: [
          'const input = "  Ada@Example.COM ";',
          'const email = input.trim().toLowerCase();',
          '',
          'console.log(email);',
          'console.log("HELLO".toLowerCase() === "hello");',
        ].join('\n'),
        output: 'ada@example.com\ntrue',
        caption: 'Trim then lowercase is the usual normalisation for identifiers.',
      },
    ],
    caveats: ['Does not perform Unicode normalisation — combining and precomposed forms stay different.'],
    commonMistakes: ['Comparing user text case-insensitively without also normalising accents.'],
    relatedEntries: ['ref-string-touppercase', 'ref-string-trim'],
    lessonId: 'l-m05-05',
  },

  {
    ...S,
    id: 'ref-string-trim',
    slug: 'string-prototype-trim',
    name: 'String.prototype.trim()',
    aliases: ['String.trim', 'trim'],
    topicIds: ['strings'],
    syntax: 'str.trim()',
    summary: 'Returns a new string with whitespace removed from both ends.',
    parameters: [],
    returns: 'A new trimmed string. The original is unchanged.',
    description: [
      'Whitespace here means spaces, tabs, line terminators and other Unicode whitespace — including the non-breaking space `\\u00A0` that a copy-paste from a web page often carries.',
      'Trimming user input before validating it is standard practice: an input of `"   "` is visually empty but has a non-zero `length`, so a `value.length > 0` check passes.',
      '`trimStart()` and `trimEnd()` trim only one side.',
    ],
    examples: [
      {
        code: [
          'const raw = "  hello  ";',
          '',
          'console.log(JSON.stringify(raw.trim()));',
          'console.log(JSON.stringify(raw.trimStart()));',
          'console.log(JSON.stringify(raw.trimEnd()));',
          'console.log("   ".length, "   ".trim().length);',
        ].join('\n'),
        output: '"hello"\n"hello  "\n"  hello"\n3 0',
        caption: 'A visually empty field is only empty after trimming.',
      },
    ],
    caveats: ['Trims only the ends — internal whitespace is untouched. Collapse it with `.replace(/\\s+/g, " ")`.'],
    commonMistakes: ['Validating required fields without trimming, so a space-only value counts as filled.'],
    relatedEntries: ['ref-string-tolowercase', 'ref-string-padstart'],
    lessonId: 'l-m05-05',
  },

  {
    ...S,
    id: 'ref-string-concat',
    slug: 'string-prototype-concat',
    name: 'String.prototype.concat()',
    aliases: ['String.concat', 'string concat'],
    topicIds: ['strings'],
    syntax: 'str.concat(str1)\nstr.concat(str1, str2, /* … */)',
    summary: 'Joins one or more strings onto the end of this one, returning a new string.',
    parameters: [{ name: 'str1, str2, …', description: 'Values to append. Non-strings are converted with `String()`.' }],
    returns: 'A new combined string. The original is unchanged.',
    description: [
      'Rarely used in modern code. Template literals read better for interpolation and `+` reads better for simple joins; `concat` mainly appears in older codebases.',
      'It is not faster than `+` — engines optimise string building heavily, and the difference is not something to design around.',
      'To join a list, `array.join("")` is clearer and does not require spreading into arguments.',
    ],
    examples: [
      {
        code: [
          'const greet = "Hello";',
          '',
          'console.log(greet.concat(", ", "world"));',
          'console.log(`${greet}, world`);',
          'console.log(["a", "b", "c"].join(""));',
        ].join('\n'),
        output: 'Hello, world\nHello, world\nabc',
        caption: 'Template literals are the modern equivalent.',
      },
    ],
    caveats: ['Not to be confused with `Array.prototype.concat()`, which joins arrays.'],
    commonMistakes: ['Choosing it for performance reasons that do not exist.'],
    relatedEntries: ['ref-string-template-literal'],
    lessonId: 'l-m05-02',
  },

  {
    ...S,
    id: 'ref-string-repeat',
    slug: 'string-prototype-repeat',
    name: 'String.prototype.repeat()',
    aliases: ['String.repeat', 'repeat'],
    topicIds: ['strings'],
    syntax: 'str.repeat(count)',
    summary: 'Returns a new string consisting of this string repeated a given number of times.',
    parameters: [{ name: 'count', description: 'How many times to repeat. Must be a non-negative, finite number; fractions are truncated.' }],
    returns: 'A new repeated string. `""` when `count` is `0`.',
    throws: '`RangeError` if `count` is negative or infinite.',
    description: [
      'Useful for building separators, indentation and simple text-mode output.',
      '`count` is truncated to an integer, so `repeat(2.9)` repeats twice.',
      'A negative or infinite count is a `RangeError` rather than a silent empty string, which makes an arithmetic mistake visible.',
    ],
    examples: [
      {
        code: [
          'console.log("-".repeat(10));',
          'console.log("ab".repeat(0) === "");',
          'console.log("ab".repeat(2.9));',
          'try {',
          '  "x".repeat(-1);',
          '} catch (err) {',
          '  console.log(err.constructor.name);',
          '}',
        ].join('\n'),
        output: '----------\ntrue\nabab\nRangeError',
        caption: 'Fractional counts truncate; negative counts throw.',
      },
    ],
    caveats: ['Very large counts can exceed the maximum string length and throw a `RangeError`.'],
    commonMistakes: ['Passing a computed count without guarding against a negative result.'],
    relatedEntries: ['ref-string-padstart'],
    lessonId: 'l-m05-05',
  },

  {
    ...S,
    id: 'ref-string-padstart',
    slug: 'string-prototype-padstart',
    name: 'String.prototype.padStart()',
    aliases: ['String.padStart', 'padStart', 'padEnd'],
    topicIds: ['strings'],
    syntax: 'str.padStart(targetLength)\nstr.padStart(targetLength, padString)',
    summary: 'Pads the start of the string until it reaches a target length, returning a new string.',
    parameters: [
      { name: 'targetLength', description: 'The length to reach. If it is not greater than the current length, the string is returned unchanged.' },
      { name: 'padString', optional: true, description: 'The text to pad with, defaulting to a space. It is repeated and truncated to fit exactly.' },
    ],
    returns: 'A new padded string. The original is unchanged.',
    description: [
      'The canonical use is zero-padding numbers for display: `String(minutes).padStart(2, "0")`.',
      '`padEnd()` is identical but pads the other end — useful for aligning columns in fixed-width text output.',
      'Padding never truncates. If the string is already at or over the target length it is returned as-is, so this cannot be used to enforce a maximum width.',
    ],
    examples: [
      {
        code: [
          'console.log("7".padStart(3, "0"));',
          'console.log("abc".padStart(2, "0"));',
          'console.log("5".padEnd(4, "."));',
          'console.log("ab".padStart(7, "123"));',
        ].join('\n'),
        output: '007\nabc\n5...\n12312ab',
        caption: 'Padding repeats and truncates the pad string, and never shortens the input.',
      },
    ],
    caveats: [
      'Does not truncate an over-long string — combine with `slice` if you need a fixed width.',
      'Counts UTF-16 code units, so padding text containing emoji misaligns.',
    ],
    commonMistakes: ['Expecting it to enforce an exact width in both directions.'],
    relatedEntries: ['ref-string-repeat', 'ref-string-length'],
    lessonId: 'l-m05-05',
  },

  {
    ...S,
    id: 'ref-string-localecompare',
    slug: 'string-prototype-localecompare',
    name: 'String.prototype.localeCompare()',
    aliases: ['String.localeCompare', 'localeCompare', 'string sort compare'],
    topicIds: ['strings', 'arrays'],
    syntax: 'str.localeCompare(other)\nstr.localeCompare(other, locales, options)',
    summary: 'Compares two strings in a locale-aware way, returning a negative number, zero or a positive number — exactly the shape `sort()` needs.',
    parameters: [
      { name: 'other', description: 'The string to compare against.' },
      { name: 'locales', optional: true, description: 'A BCP 47 locale tag or array of them, such as `"de"` or `"tr"`.' },
      { name: 'options', optional: true, description: 'An `Intl.Collator` options object — `sensitivity`, `numeric`, `caseFirst`.' },
    ],
    returns: 'A negative number if `str` sorts first, `0` if they are equivalent, a positive number otherwise.',
    description: [
      'This is the correct comparator for sorting human-readable text. The default `sort()` compares UTF-16 code units, which places every uppercase letter before every lowercase one and orders accented characters after `z`.',
      '`{ numeric: true }` makes embedded numbers sort naturally, so `"item10"` comes after `"item9"` instead of before it.',
      '`{ sensitivity: "base" }` treats case and accents as equivalent, which is what a case-insensitive comparison should use rather than lowercasing both sides.',
      'For sorting a large list, construct an `Intl.Collator` once and pass its `compare` method — creating the collator is the expensive part, and `localeCompare` may recreate it per call.',
    ],
    examples: [
      {
        code: [
          'const names = ["Zoe", "adam", "Bob"];',
          '',
          'console.log([...names].sort());',
          'console.log([...names].sort((a, b) => a.localeCompare(b)));',
          'console.log("item9".localeCompare("item10", undefined, { numeric: true }));',
          'console.log("a".localeCompare("A", undefined, { sensitivity: "base" }));',
        ].join('\n'),
        output: '["Bob", "Zoe", "adam"]\n["adam", "Bob", "Zoe"]\n-1\n0',
        caption: 'Default sort puts uppercase first; localeCompare sorts the way a reader expects.',
      },
    ],
    caveats: [
      'The exact return value is implementation-defined — only its sign is specified. Never test for `=== 1`.',
      'Results vary by locale and engine, so do not snapshot-test sorted output across environments.',
    ],
    commonMistakes: ['Sorting user-visible names with the default comparator.'],
    relatedEntries: ['ref-string-tolowercase'],
    lessonId: 'l-m16-04',
  },

  {
    ...S,
    id: 'ref-string-template-literal',
    slug: 'template-literals',
    name: 'Template literals',
    aliases: ['template literal', 'template string', 'backtick string', 'string interpolation', 'tagged template'],
    category: C.SYNTAX,
    topicIds: ['strings', 'modern-js'],
    syntax: '`text ${expression} text`\ntag`text ${expression} text`',
    summary: 'String literals delimited by backticks that support embedded expressions and real line breaks.',
    parameters: [],
    returns: 'A string — or, with a tag function, whatever the tag returns.',
    description: [
      'Any expression can appear inside `${}`, and its value is converted with `String()`. Nesting template literals inside the placeholders is legal, which is how conditional fragments are usually built.',
      'Line breaks inside the literal are preserved verbatim, so multi-line text needs no `\\n` escapes. That also means indentation inside the literal becomes part of the string.',
      'A **tagged template** — `tag`…`` — calls `tag` with the literal string parts as the first argument and the interpolated values as the rest. Because the tag receives the static and dynamic parts separately, it can escape only the dynamic ones, which is the basis of safe HTML and SQL builders.',
      'A plain template literal escapes nothing. Interpolating untrusted text and assigning the result to `innerHTML` is exactly as unsafe as string concatenation.',
    ],
    examples: [
      {
        code: [
          'const user = { name: "Ada", count: 3 };',
          '',
          'console.log(`${user.name} has ${user.count} item${user.count === 1 ? "" : "s"}`);',
          '',
          'function tag(parts, ...values) {',
          '  return parts.length + ":" + values.join("|");',
          '}',
          'console.log(tag`a${1}b${2}c`);',
        ].join('\n'),
        output: 'Ada has 3 items\n3:1|2',
        caption: 'A tag function receives literal parts and values as separate arguments.',
      },
    ],
    caveats: [
      'Provides no escaping — unsafe for `innerHTML` with untrusted values.',
      'Leading indentation inside the literal is part of the string.',
    ],
    commonMistakes: ['Assuming interpolation sanitises the values it inserts.'],
    relatedEntries: ['ref-string-concat', 'ref-string-ctor'],
    lessonId: 'l-m05-02',
  },

  {
    ...S,
    id: 'ref-string-tostring-tag',
    slug: 'object-prototype-tostring-call',
    name: 'Object.prototype.toString.call()',
    aliases: ['toString.call', 'type tag', 'object tag'],
    category: C.OBJECT,
    topicIds: ['types', 'objects'],
    syntax: 'Object.prototype.toString.call(value)',
    summary: 'Reads a value\'s internal type tag, returning strings like `"[object Array]"` — the classic precise type check.',
    parameters: [{ name: 'value', description: 'Any value, including `null` and `undefined`.' }],
    returns: 'A string of the form `"[object Type]"`.',
    description: [
      'It exists because `typeof` cannot distinguish objects: arrays, dates, regexes, `null` and plain objects all report `"object"`.',
      'It must be called with `.call()`, because most objects override `toString` with something more useful to a reader. Calling it directly on the prototype is what reaches the original.',
      'It works across realms — an array from an `<iframe>` still reports `"[object Array]"`, where `instanceof Array` would fail because each realm has its own constructors.',
      'Since ES6 a class can change the result by defining `Symbol.toStringTag`, so it is a strong convention rather than an unforgeable brand. For arrays specifically, `Array.isArray()` is the purpose-built and faster check.',
    ],
    examples: [
      {
        code: [
          'const tag = (v) => Object.prototype.toString.call(v);',
          '',
          'console.log(tag([]));',
          'console.log(tag(null));',
          'console.log(tag(new Date(0)));',
          'console.log(tag(/x/));',
          'console.log(tag({}));',
          'console.log(typeof []);',
        ].join('\n'),
        output: '[object Array]\n[object Null]\n[object Date]\n[object RegExp]\n[object Object]\nobject',
        caption: 'The type tag distinguishes what typeof flattens into "object".',
      },
    ],
    caveats: ['`Symbol.toStringTag` lets any object choose its own tag, so this is not a security boundary.'],
    commonMistakes: ['Calling `value.toString()` and expecting a type tag — most objects override it.'],
    relatedEntries: ['ref-string-ctor'],
    lessonId: 'l-m02-02',
  },
];
