import { REFERENCE_CATEGORY as C, REFERENCE_ENV as E } from '../schema/types.js';

/**
 * Modern language syntax and the module system.
 *
 * These are syntax entries rather than methods, so the `syntax` field shows the
 * grammar rather than a call signature and `parameters` is usually empty.
 *
 * `import`/`export` cannot execute under `new Function`, so those examples are
 * marked illustrative rather than pretending to run.
 */

const S = { category: C.SYNTAX, environment: E.ECMASCRIPT, mutates: false, parameters: [] };
const M = { category: C.MODULES, environment: E.ECMASCRIPT, mutates: false, parameters: [] };

export default [
  {
    ...S,
    id: 'ref-syntax-destructuring',
    slug: 'destructuring',
    name: 'Destructuring assignment',
    aliases: ['destructuring', 'destructure', 'unpack object', 'unpack array', 'swap variables'],
    topicIds: ['destructuring', 'modern-js'],
    syntax: 'const { a, b: renamed, c = 1 } = obj\nconst [first, , third = 0, ...rest] = arr\nfunction f({ a, b } = {}) {}',
    summary: 'Unpacks values from arrays and properties from objects into distinct variables, with renaming, defaults and rest collection.',
    returns: 'Binds variables. As an expression, the assignment evaluates to the right-hand side.',
    throws: '`TypeError` when destructuring `null` or `undefined`.',
    description: [
      '**Array** destructuring is positional and works on any **iterable** — arrays, strings, `Set`s, generators. An elision (`[a, , c]`) skips a position; `...rest` collects the remainder into a real array and must come last.',
      '**Object** destructuring is by property name. `{ b: renamed }` renames, and nested patterns (`{ a: { b } }`) reach deeper — but note that binds only `b`, not `a`.',
      '**Defaults apply only for `undefined`**, never for `null` or any other falsy value. A property that is `null` stays `null`, which is the case that bites when destructuring JSON, since JSON has `null` but no `undefined`.',
      'Destructuring `null` or `undefined` **throws**. `const { a } = maybeNull` needs a `?? {}` guard.',
      'Swapping needs no temporary: `[a, b] = [b, a]` builds the array first, then assigns.',
      'A destructuring **assignment** to existing variables — as opposed to a declaration — must be parenthesised for objects (`({ a } = obj)`), because a leading `{` starts a block. And a statement starting with `[` needs the previous line terminated, since ASI will not insert a semicolon before it.',
      'The `function f({ a, b } = {})` pattern gives named parameters with a default empty object, so calling `f()` with no arguments does not throw.',
    ],
    examples: [
      {
        code: [
          'const user = { name: "Ada", address: { city: "London" }, tags: null };',
          '',
          'const { name, address: { city }, tags = [], missing = "fallback" } = user;',
          'console.log(name, city, tags, missing);',
          '',
          'const [first, , third = 99, ...rest] = [10, 20];',
          'console.log(first, third, rest);',
          '',
          'let a = 1, b = 2;',
          '[a, b] = [b, a];',
          'console.log(a, b);',
          '',
          'const [head, ...tail] = "hey";',
          'console.log(head, tail);',
          '',
          'try {',
          '  const { x } = null;',
          '} catch (err) {',
          '  console.log(err.constructor.name);',
          '}',
        ].join('\n'),
        output: 'Ada London null fallback\n10 99 []\n2 1\nh ["e", "y"]\nTypeError',
        caption: 'The default did not apply to tags, because null is not undefined.',
      },
    ],
    caveats: [
      'Defaults fire only for `undefined`, not `null`.',
      'Destructuring `null`/`undefined` throws.',
      'A nested pattern binds only the innermost name.',
      'An assignment (not declaration) to an object pattern needs parentheses.',
    ],
    commonMistakes: ['Expecting a default to replace `null` from an API response.'],
    relatedEntries: ['ref-syntax-spread', 'ref-syntax-nullish', 'ref-object-entries'],
    lessonId: 'l-m21-02',
  },

  {
    ...S,
    id: 'ref-syntax-spread',
    slug: 'spread-syntax',
    name: 'Spread syntax (...)',
    aliases: ['spread', 'spread operator', '...', 'copy array', 'merge objects', 'shallow copy'],
    topicIds: ['modern-js', 'copying'],
    syntax: '[...iterable]\n{ ...object }\nfn(...args)',
    summary: 'Expands an iterable into individual elements, or an object\'s own enumerable properties into another object literal.',
    returns: 'A new array, object, or argument list — the source is never modified.',
    throws: '`TypeError` when spreading a non-iterable into an array or an argument list.',
    description: [
      'In an **array or call**, it consumes the iterable protocol, so arrays, strings, `Set`s, `Map`s and generators all work. A plain object is **not** iterable, so `[...obj]` throws — `Object.entries(obj)` is what you want there.',
      'In an **object literal** it copies own enumerable properties, including symbol keys. This form is not iteration, which is why `{ ...anyObject }` works even though `[...anyObject]` does not.',
      'It is always a **shallow** copy. `{ ...original }` gives a new top-level object whose nested objects are the **same references**, so mutating one is visible through both. This is the single most common misunderstanding about it.',
      'Later properties win in an object literal, which is what makes `{ ...defaults, ...overrides }` the idiomatic merge — and unlike `Object.assign(defaults, overrides)`, it does not mutate anything.',
      'Object spread copies **values**, invoking getters and storing the result as a plain data property. It also always creates data properties, so it never triggers a setter on the target.',
      'Spreading a very large array into a call — `fn(...huge)` or `arr.push(...huge)` — can exceed the engine argument limit and throw a `RangeError`. Use `reduce` or a loop for big data.',
      'Do not confuse it with **rest**, which uses the same `...` token in the opposite direction: rest collects into an array, spread expands out of one.',
    ],
    examples: [
      {
        code: [
          'const original = { name: "a", tags: ["x"] };',
          'const copy = { ...original, name: "b" };',
          '',
          'console.log(copy.name, original.name);',
          'console.log(copy.tags === original.tags);',
          '',
          'console.log([...new Set([1, 1, 2])]);',
          'console.log([..."ab"]);',
          'console.log(Math.max(...[3, 1, 4]));',
          '',
          'console.log({ ...{ a: 1 }, ...{ a: 2, b: 3 } });',
          '',
          'try {',
          '  console.log([...{ a: 1 }]);',
          '} catch (err) {',
          '  console.log(err.constructor.name);',
          '}',
        ].join('\n'),
        output: 'b a\ntrue\n[1, 2]\n["a", "b"]\n4\n{a: 2, b: 3}\nTypeError',
        caption: 'The nested array is shared, and a plain object cannot be array-spread.',
      },
    ],
    caveats: [
      'Shallow — nested objects are shared with the source.',
      '`[...obj]` throws for a plain object; only `{ ...obj }` works.',
      'Spreading a huge array into a call can throw `RangeError`.',
      'Getters are invoked and flattened into data properties.',
    ],
    commonMistakes: ['Treating it as a deep copy.', 'Confusing it with rest parameters.'],
    relatedEntries: ['ref-syntax-rest', 'ref-object-assign', 'ref-structuredclone', 'ref-syntax-destructuring'],
    lessonId: 'l-m21-03',
  },

  {
    ...S,
    id: 'ref-syntax-rest',
    slug: 'rest-parameters',
    name: 'Rest parameters (...)',
    aliases: ['rest parameters', 'rest', 'variadic function', 'arguments object', 'collect arguments'],
    topicIds: ['functions', 'modern-js'],
    syntax: 'function f(first, ...rest) {}\nconst { a, ...others } = obj\nconst [x, ...tail] = arr',
    summary: 'Collects remaining arguments, array elements or object properties into a single value. The mirror image of spread.',
    returns: 'A **real array** for parameters and array patterns; a new object for object rest.',
    description: [
      'Rest **collects**, spread **expands**. Same three dots, opposite directions — rest appears on the left of an assignment or in a parameter list; spread appears on the right or in a call.',
      'A rest parameter is a **genuine array**, unlike the legacy `arguments` object, which is array-like and has no `map` or `filter`. It also works in arrow functions, where `arguments` does not exist at all.',
      'It must be the **last** parameter, and only one is allowed — anything else is a `SyntaxError`.',
      'It does not count towards `fn.length`, which reports only the parameters before the first default or rest. That matters for any library that inspects arity, including a hand-written `curry`.',
      '**Object rest** collects the remaining own enumerable properties into a new object, which is the idiomatic way to omit a key: `const { password, ...safe } = user`.',
      'Unlike `arguments`, a rest parameter never aliases the named parameters, so it behaves predictably in both strict and sloppy mode.',
    ],
    examples: [
      {
        code: [
          'function sum(label, ...numbers) {',
          '  return `${label}: ${numbers.reduce((a, b) => a + b, 0)}`;',
          '}',
          '',
          'console.log(sum("total", 1, 2, 3));',
          'console.log(sum("empty"));',
          'console.log(sum.length);',
          '',
          'const user = { id: 1, name: "Ada", password: "secret" };',
          'const { password, ...safe } = user;',
          'console.log(safe);',
          '',
          'const collect = (...args) => Array.isArray(args);',
          'console.log(collect(1, 2));',
        ].join('\n'),
        output: 'total: 6\nempty: 0\n1\n{id: 1, name: "Ada"}\ntrue',
        caption: 'A rest parameter is a real array and does not count towards fn.length.',
      },
    ],
    caveats: [
      'Must be last, and only one is permitted.',
      'Excluded from `fn.length`.',
      'Object rest is shallow, like spread.',
    ],
    commonMistakes: ['Confusing it with spread.', 'Relying on `fn.length` to include it.'],
    relatedEntries: ['ref-syntax-spread', 'ref-syntax-defaultparams', 'ref-syntax-destructuring'],
    lessonId: 'l-m21-03',
  },

  {
    ...S,
    id: 'ref-syntax-defaultparams',
    slug: 'default-parameters',
    name: 'Default parameters',
    aliases: ['default parameters', 'default arguments', 'optional parameter'],
    topicIds: ['functions', 'modern-js'],
    syntax: 'function f(a, b = expression) {}\nconst g = ({ x = 1, y = 2 } = {}) => {}',
    summary: 'Supplies a value for a parameter that is `undefined` at call time. The expression is evaluated **on every such call**.',
    returns: 'Binds the parameter to the default when the argument is `undefined`.',
    description: [
      'The default fires **only for `undefined`** — including a missing argument and an explicit `undefined`. Passing `null`, `0`, `""` or `false` uses that value. This is the same rule as destructuring defaults, and the same trap when handling JSON.',
      'The expression is evaluated **per call**, not once at definition. `function f(list = [])` therefore creates a fresh array each time — the opposite of Python, where a mutable default is created once and becomes a notorious shared-state bug.',
      'Defaults are evaluated left to right, and a later default can reference an **earlier** parameter: `function f(a, b = a * 2)`. Referencing a later one hits its temporal dead zone and throws.',
      'A parameter with a default does not count towards `fn.length`, which stops at the first defaulted or rest parameter.',
      'The `({ x = 1 } = {})` combination gives named options with per-key defaults **and** tolerates the whole argument being omitted — without the trailing `= {}`, calling with no arguments throws.',
      'Because the default is an arbitrary expression, it can call a function — which is how a required-argument guard is written: `function f(a = required("a"))`.',
    ],
    examples: [
      {
        code: [
          'function push(item, list = []) {',
          '  list.push(item);',
          '  return list.length;',
          '}',
          'console.log(push("a"), push("b"));',
          '',
          'function show(value = "default") { return value; }',
          'console.log(show(), show(undefined), JSON.stringify(show(null)), show(0));',
          '',
          'function area(w, h = w) { return w * h; }',
          'console.log(area(3), area(3, 4), area.length);',
          '',
          'const opts = ({ retries = 3, debug = false } = {}) => `${retries}/${debug}`;',
          'console.log(opts(), opts({ retries: 0 }));',
        ].join('\n'),
        output: '1 1\ndefault default null 0\n9 12 1\n3/false 0/false',
        caption: 'A fresh array per call, and null is kept while undefined is replaced.',
      },
    ],
    caveats: [
      'Applies only to `undefined`, never `null`.',
      'Excluded from `fn.length`.',
      'A default cannot reference a later parameter.',
    ],
    commonMistakes: ['Importing Python\'s mutable-default rule.', 'Omitting the trailing `= {}` on a destructured options parameter.'],
    relatedEntries: ['ref-syntax-rest', 'ref-syntax-destructuring', 'ref-syntax-nullish'],
    lessonId: 'l-m08-05',
  },

  {
    ...S,
    id: 'ref-syntax-optional-chaining',
    slug: 'optional-chaining',
    name: 'Optional chaining (?.)',
    aliases: ['optional chaining', '?.', 'safe navigation', 'null check property'],
    topicIds: ['operators', 'modern-js'],
    syntax: 'obj?.prop\nobj?.[expr]\nfn?.()\nobj?.method?.()',
    summary: 'Reads a property, index or call only when the value before it is not `null` or `undefined`; otherwise the whole chain short-circuits to `undefined`.',
    returns: 'The value, or **`undefined`** if any link in the chain was nullish.',
    description: [
      'It short-circuits on exactly two values: `null` and `undefined`. Everything else — `0`, `""`, `false`, `NaN` — proceeds normally.',
      'The result of a short-circuit is always **`undefined`**, never `null`, whichever nullish value triggered it.',
      'Short-circuiting stops the **entire rest of the chain**, not just one link: in `a?.b.c.d`, if `a` is nullish then `b.c.d` is never evaluated, so no `TypeError` is thrown further along.',
      'The call form is `fn?.()` — the dot is required, and `obj.method?.()` calls the method only if it exists. It throws a `TypeError` if the value is present but not callable, which is correct: the guard is for absence, not for wrong types.',
      'Index access is `obj?.[key]`, again with the dot.',
      'It protects only against nullish **values**. It does not catch a thrown error, a missing variable (that is still a `ReferenceError`), or a wrong type.',
      'The judgement worth applying: `?.` is right where absence is genuinely expected, and wrong where it silently absorbs a broken invariant. A chain that hides a data bug behind a plausible `undefined` is worse than a loud error — an error names the exact property, while a silently-missing value becomes a support ticket weeks later.',
    ],
    examples: [
      {
        code: [
          'const config = { retries: 0, nested: null, cb: () => "called" };',
          '',
          'console.log(config?.retries);',
          'console.log(config.nested?.deep?.value);',
          'console.log(config.missing?.());',
          'console.log(config.cb?.());',
          'console.log(config?.["retries"]);',
          '',
          'try {',
          '  config.retries?.();',
          '} catch (err) {',
          '  console.log(err.constructor.name);',
          '}',
        ].join('\n'),
        output: '0\nundefined\nundefined\ncalled\n0\nTypeError',
        caption: 'It guards absence, not wrong types — a non-callable value still throws.',
      },
    ],
    caveats: [
      'Short-circuits to `undefined`, never to `null`.',
      'Does not protect against a present-but-wrong-type value.',
      'A missing variable is still a `ReferenceError`.',
      'Overuse hides broken invariants behind plausible `undefined`s.',
    ],
    commonMistakes: ['Writing `fn?()` instead of `fn?.()`.', 'Using it to silence errors rather than to express genuine optionality.'],
    relatedEntries: ['ref-syntax-nullish', 'ref-syntax-destructuring'],
    lessonId: 'l-m21-04',
  },

  {
    ...S,
    id: 'ref-syntax-nullish',
    slug: 'nullish-coalescing',
    name: 'Nullish coalescing (??)',
    aliases: ['nullish coalescing', '??', 'default value', 'null or undefined fallback'],
    topicIds: ['operators', 'modern-js'],
    syntax: 'value ?? fallback',
    summary: 'Returns the right side only when the left is `null` or `undefined` — unlike `||`, which falls back on every falsy value.',
    returns: 'The left operand unless it is nullish, otherwise the right operand.',
    throws: '`SyntaxError` if combined with `&&` or `||` without parentheses.',
    description: [
      'The difference from `||` is exactly the set of values that trigger the fallback. `||` falls back on **every falsy value** — `0`, `""`, `false`, `NaN`, `null`, `undefined`. `??` falls back only on `null` and `undefined`.',
      'That difference is a real bug source. `config.retries || 3` turns a deliberate "retry zero times" into three retries; `config.label || "none"` replaces an intentionally blank label; `options.enabled || true` can never be `false`. For configuration and API values, `??` should be the default choice.',
      'It **short-circuits**: the right side is not evaluated when the left is non-nullish, so an expensive fallback costs nothing in the common case.',
      'Mixing it with `&&` or `||` without parentheses is a **`SyntaxError`**, deliberately — the precedence would otherwise be guessed. Write `(a ?? b) || c` explicitly.',
      '`||` is still right when you genuinely want any falsy value replaced — for example normalising a possibly-empty string to a placeholder.',
      '`??=` is the assignment form: it assigns only when the target is nullish.',
    ],
    examples: [
      {
        code: [
          'const config = { retries: 0, label: "", missing: undefined, nulled: null };',
          '',
          'console.log(config.retries ?? 3, config.retries || 3);',
          'console.log(JSON.stringify(config.label ?? "none"), config.label || "none");',
          'console.log(config.missing ?? "d", config.nulled ?? "d");',
          '',
          'let called = 0;',
          'const cost = () => { called += 1; return "expensive"; };',
          'console.log("ok" ?? cost(), called);',
        ].join('\n'),
        output: '0 3\n"" none\nd d\nok 0',
        caption: '?? preserved the 0 and the empty string; || replaced both.',
      },
    ],
    caveats: [
      'Cannot be mixed with `&&`/`||` unparenthesised — that is a `SyntaxError`.',
      'Does not fall back on `NaN`, which is falsy but not nullish.',
    ],
    commonMistakes: ['Using `||` for numeric or boolean defaults.'],
    relatedEntries: ['ref-syntax-optional-chaining', 'ref-syntax-logical-assignment', 'ref-syntax-defaultparams'],
    lessonId: 'l-m04-05',
  },

  {
    ...S,
    id: 'ref-syntax-logical-assignment',
    slug: 'logical-assignment',
    name: 'Logical assignment (??=, ||=, &&=)',
    aliases: ['logical assignment', '??=', '||=', '&&=', 'assign if null'],
    topicIds: ['operators', 'modern-js'],
    syntax: 'a ??= value\na ||= value\na &&= value',
    summary: 'Assigns only when the corresponding logical test passes, and **short-circuits the assignment itself** when it does not.',
    returns: 'The resulting value of the target.',
    description: [
      '`a ??= b` assigns when `a` is nullish. `a ||= b` assigns when `a` is falsy. `a &&= b` assigns when `a` is truthy.',
      'The important detail is that they short-circuit the **assignment**, not merely the value. `a ??= b` is `a ?? (a = b)`, **not** `a = a ?? b`. When no assignment is needed, no write happens at all — which matters for setters, for `Proxy` traps, and for frameworks that track writes for reactivity.',
      '`??=` is the natural "initialise if absent" for a lazily-populated cache: `map[key] ??= []` then push.',
      '`&&=` is the least used and the easiest to misread — it clears or transforms a value only when one is already present.',
      'They inherit the falsy-versus-nullish distinction exactly: `||=` overwrites a legitimate `0` or `""`, while `??=` does not.',
      'Like `??` itself, they cannot be mixed with other logical operators without parentheses.',
    ],
    examples: [
      {
        code: [
          'const settings = { retries: 0, name: "", missing: undefined };',
          '',
          'settings.retries ??= 5;',
          'settings.name ||= "anonymous";',
          'settings.missing ??= "filled";',
          'console.log(settings);',
          '',
          'const groups = {};',
          'for (const word of ["ant", "ape", "bee"]) {',
          '  (groups[word[0]] ??= []).push(word);',
          '}',
          'console.log(groups);',
          '',
          'let writes = 0;',
          'const target = {',
          '  _v: "present",',
          '  get v() { return this._v; },',
          '  set v(next) { writes += 1; this._v = next; },',
          '};',
          'target.v ??= "new";',
          'console.log(writes);',
        ].join('\n'),
        output: '{retries: 0, name: "anonymous", missing: "filled"}\n{a: ["ant", "ape"], b: ["bee"]}\n0',
        caption: 'No assignment happened, so the setter never ran.',
      },
    ],
    caveats: [
      '`||=` overwrites `0` and `""`.',
      'The assignment is skipped entirely, so setters and proxy traps do not fire.',
      'Cannot be mixed with other logical operators unparenthesised.',
    ],
    commonMistakes: ['Assuming `a ??= b` always performs a write.'],
    relatedEntries: ['ref-syntax-nullish', 'ref-syntax-optional-chaining'],
    lessonId: 'l-m21-04',
  },

  {
    ...S,
    id: 'ref-syntax-arrow',
    slug: 'arrow-functions',
    name: 'Arrow functions (=>)',
    aliases: ['arrow function', '=>', 'fat arrow', 'lambda', 'lexical this'],
    topicIds: ['arrow-functions', 'functions', 'this'],
    syntax: '(a, b) => a + b\na => a * 2\n() => { return value; }\n() => ({ key: value })',
    summary: 'A compact function expression with **no `this` of its own** — it inherits `this` from the enclosing scope, permanently.',
    returns: 'A function. A concise body returns its expression implicitly; a block body needs `return`.',
    description: [
      'The `this` behaviour is the real difference, not the brevity. An arrow has no `this` binding, so `this` resolves lexically to the enclosing scope — and `call`, `apply` and `bind` **cannot override it**. A function that appears to ignore `bind` is almost always an arrow.',
      'That makes arrows correct for callbacks inside a method (`setTimeout(() => this.tick(), 1000)`) and **wrong** for object methods and prototype methods, where the caller is supposed to supply `this`.',
      'A concise body returns implicitly. Adding braces makes it a block, which returns `undefined` without an explicit `return` — the single most common mistake with `map`.',
      'Returning an object literal from a concise body needs parentheses: `() => ({ a: 1 })`. Without them the braces are parsed as a block and the result is `undefined`.',
      'Arrows also have **no `arguments`**, no `prototype`, and cannot be called with `new` — `new (() => {})` throws a `TypeError`. Use rest parameters instead of `arguments`.',
      'They cannot be generators, and a named function declaration still hoists where an arrow assigned to a `const` does not.',
    ],
    examples: [
      {
        code: [
          'const double = (n) => n * 2;',
          'const blockBody = (n) => { n * 2; };',
          'const makeObj = (n) => ({ value: n });',
          '',
          'console.log(double(4), blockBody(4), makeObj(4));',
          '',
          'const obj = {',
          '  label: "instance",',
          '  arrow: () => typeof this,',
          '  method() { return this.label; },',
          '};',
          'console.log(obj.method(), obj.arrow());',
          '',
          'const fn = () => this;',
          'console.log(fn.call({ label: "ignored" }) === fn());',
          '',
          'try { new (() => {})(); } catch (err) { console.log(err.constructor.name); }',
        ].join('\n'),
        output: '8 undefined {value: 4}\ninstance undefined\ntrue\nTypeError',
        caption: 'call could not change the arrow\'s this, and it cannot be constructed.',
      },
    ],
    caveats: [
      'No own `this` — `call`/`apply`/`bind` have no effect.',
      'A block body needs an explicit `return`.',
      'Returning an object literal needs parentheses.',
      'No `arguments`, no `prototype`, cannot be `new`ed.',
    ],
    commonMistakes: ['Using an arrow for an object or prototype method.', 'Forgetting `return` in a block body.'],
    relatedEntries: ['ref-function-bind', 'ref-array-map', 'ref-syntax-rest'],
    lessonId: 'l-m09-02',
  },

  {
    ...S,
    id: 'ref-syntax-async-function',
    slug: 'async-function',
    name: 'async function',
    aliases: ['async', 'async function', 'async arrow', 'async method'],
    topicIds: ['async-await', 'promises'],
    syntax: 'async function f() {}\nconst g = async () => {}\nasync method() {}',
    summary: 'Declares a function that **always returns a promise** and may use `await` inside. A `return` fulfils it; a `throw` rejects it.',
    returns: 'Always a `Promise`, whatever the body returns.',
    description: [
      'The return value is wrapped automatically: `return 1` fulfils with `1`, and returning a promise adopts it rather than double-wrapping.',
      'A `throw` inside becomes a **rejection**, not a synchronous exception. `try { doAsync(); } catch {}` around a bare call therefore catches nothing — only `await doAsync()` inside `try`, or a `.catch()`, handles it.',
      'The body runs **synchronously up to the first `await`**. Calling an `async` function does not defer its start, so expensive work before the first `await` blocks the caller just as it would in a normal function.',
      'It composes with everything promise-based: `await` accepts what it returns, `Promise.all` accepts an array of its results, and `.then` works on it.',
      'Marking a function `async` when its body contains no `await` adds a promise wrapper for nothing — and a function that is `async` yet awaits nothing is usually a sign of a forgotten `await`.',
      '`return await x` inside a `try` is **not** redundant: it makes a rejection catchable there, whereas a bare `return x` hands the promise to the caller and skips your `catch`.',
      'Every promise an `async` function starts needs an owner. An unawaited, uncaught call produces an unhandled rejection — fatal by default in Node.',
    ],
    examples: [
      {
        code: [
          'async function ok() { return 1; }',
          'async function bad() { throw new Error("x"); }',
          '',
          'console.log(ok() instanceof Promise);',
          '',
          'async function run() {',
          '  console.log("1 sync part");',
          '  await null;',
          '  console.log("3 after await");',
          '}',
          '',
          'run();',
          'console.log("2 caller continues");',
          '',
          'try {',
          '  const pending = bad();',
          '  console.log("no synchronous throw to catch");',
          '  pending.catch((e) => console.log("4 caught:", e.message));',
          '} catch {',
          '  console.log("never reached");',
          '}',
        ].join('\n'),
        output: 'true\n1 sync part\n2 caller continues\nno synchronous throw to catch\n3 after await\n4 caught: x',
        caption: 'The synchronous try/catch missed it entirely — a throw becomes a rejection.',
      },
    ],
    caveats: [
      'A bare call cannot be wrapped in `try`/`catch` usefully.',
      'Work before the first `await` blocks the caller.',
      '`return await` inside `try` differs from `return`.',
      'Unowned rejections become unhandled rejections.',
    ],
    commonMistakes: ['Wrapping a non-awaited async call in `try`/`catch`.', 'Marking a function `async` with no `await` in it.'],
    relatedEntries: ['ref-syntax-await', 'ref-promise-ctor', 'ref-promise-all'],
    lessonId: 'l-m25-01',
  },

  {
    ...S,
    id: 'ref-syntax-await',
    slug: 'await',
    name: 'await',
    aliases: ['await', 'await keyword', 'top level await', 'for await'],
    topicIds: ['async-await', 'event-loop'],
    syntax: 'const value = await promise\nfor await (const x of asyncIterable) {}',
    summary: 'Suspends an `async` function until a promise settles, then resumes with its value — or throws its rejection reason at that line.',
    returns: 'The fulfilment value. A rejection is thrown at the `await`, so ordinary `try`/`catch` works.',
    description: [
      'It works on **any value**, not just promises. `await 42` yields `42` — but it still suspends and schedules the continuation as a microtask, so it is never a no-op. Anything with a callable `then` is treated as a promise, which is how library and cross-realm promises interoperate.',
      'A rejection is **thrown at the `await` line**, which is what makes `try`/`catch`/`finally` work around asynchronous code exactly as they do around synchronous code.',
      'Sequential `await`s **serialise** the work. Two independent requests written as `await a(); await b();` take the sum of their times; `await Promise.all([a(), b()])` takes the longer of the two. This is the most common performance regression when converting promise chains to `await`.',
      '`await` inside `map` does not sequence anything: `items.map(async (x) => await f(x))` starts every call at once and returns an array of promises. `for...of` with `await` inside is the sequential form.',
      '**Top-level `await`** is legal only in an ES module, where it delays that module\'s evaluation and, transitively, everything importing it. It is a `SyntaxError` in a classic script and impossible in CommonJS, whose `require` is synchronous.',
      '`for await...of` consumes an async iterable, which is how paginated APIs and streaming responses are consumed lazily.',
    ],
    examples: [
      {
        code: [
          'const delay = (ms, v) => new Promise((r) => setTimeout(() => r(v), ms));',
          '',
          'async function sequential() {',
          '  const a = await delay(10, "a");',
          '  const b = await delay(10, "b");',
          '  return [a, b];',
          '}',
          '',
          'async function concurrent() {',
          '  return Promise.all([delay(10, "a"), delay(10, "b")]);',
          '}',
          '',
          'async function main() {',
          '  console.log(await sequential());',
          '  console.log(await concurrent());',
          '',
          '  console.log(await 42);',
          '',
          '  try {',
          '    await Promise.reject(new Error("boom"));',
          '  } catch (err) {',
          '    console.log("caught at the await:", err.message);',
          '  }',
          '}',
          '',
          'main();',
        ].join('\n'),
        output: '["a", "b"]\n["a", "b"]\n42\ncaught at the await: boom',
        caption: 'Same results — but sequential took twice as long as concurrent.',
      },
    ],
    caveats: [
      'Sequential `await`s serialise independent work.',
      '`await` on a non-promise still defers to a microtask.',
      'Top-level `await` requires an ES module.',
      '`map` with an async callback does not sequence.',
    ],
    commonMistakes: ['Awaiting independent requests one after another.', 'Using `forEach` with `async` and expecting it to wait.'],
    relatedEntries: ['ref-syntax-async-function', 'ref-promise-all', 'ref-syntax-import'],
    lessonId: 'l-m25-03',
  },

  {
    ...S,
    id: 'ref-syntax-class',
    slug: 'class',
    name: 'class',
    aliases: ['class', 'class syntax', 'extends', 'super', 'constructor', 'static'],
    topicIds: ['classes', 'prototypes'],
    syntax: 'class Name extends Base {\n  field = value;\n  constructor() { super(); }\n  method() {}\n  static create() {}\n  get prop() {}\n}',
    summary: 'Declarative syntax over the prototype system. Methods live on the prototype; fields are created per instance.',
    returns: 'A constructor function. `typeof MyClass` is `"function"`.',
    throws: '`TypeError` if called without `new`, or if `this` is used before `super()` in a derived constructor.',
    description: [
      'It is **syntax over prototypes**, not a separate object model. Methods are installed on `Class.prototype` and shared by every instance; `extends` sets up the prototype chain.',
      'Class bodies are **always strict mode**, and unlike function declarations a class declaration is **not hoisted** in a usable way — it is in a temporal dead zone until evaluated.',
      'It cannot be called without `new`, which is a genuine improvement over constructor functions, where forgetting `new` silently assigned to the global object.',
      'In a derived constructor, `super()` must be called **before** any use of `this`, because the base constructor is what creates the instance.',
      '**Field versus method** is the choice that matters. A field holding an arrow (`handler = () => {}`) is created per instance and captures `this` lexically, so it survives being passed as a callback — but it costs one function object per instance, cannot be overridden through `super`, and is invisible on the prototype to test spies. A prototype method is shared and subclassable but loses `this` when detached. Default to methods; use a bound field for handlers passed to `addEventListener` or a framework.',
      'Field initialisers run in order **before** the constructor body, so a field cannot read a value the constructor sets later.',
      '`static` members live on the constructor itself, and `static` blocks run once at class definition.',
    ],
    examples: [
      {
        code: [
          'class Shape {',
          '  static count = 0;',
          '  name = "shape";',
          '',
          '  constructor(name) {',
          '    this.name = name;',
          '    Shape.count += 1;',
          '  }',
          '',
          '  describe() { return `a ${this.name}`; }',
          '  get upper() { return this.name.toUpperCase(); }',
          '}',
          '',
          'class Circle extends Shape {',
          '  constructor() { super("circle"); }',
          '  describe() { return `${super.describe()} (round)`; }',
          '}',
          '',
          'const c = new Circle();',
          'console.log(c.describe(), c.upper, Shape.count);',
          'console.log(c instanceof Circle, c instanceof Shape);',
          'console.log(Object.hasOwn(c, "describe"), typeof Circle);',
          '',
          'try { Shape("x"); } catch (err) { console.log(err.constructor.name); }',
        ].join('\n'),
        output: 'a circle (round) CIRCLE 1\ntrue true\nfalse function\nTypeError',
        caption: 'The method is on the prototype, not the instance — and new is mandatory.',
      },
    ],
    caveats: [
      'Not hoisted usably — a class is in a TDZ until evaluated.',
      'Cannot be called without `new`.',
      '`super()` must precede any `this` in a derived constructor.',
      'Field initialisers run before the constructor body.',
      'Arrow fields cost memory per instance and break `super` overriding.',
    ],
    commonMistakes: ['Using arrow fields for every method without noting the cost.', 'Reading `this` before `super()`.'],
    relatedEntries: ['ref-syntax-private-fields', 'ref-object-getprototypeof', 'ref-function-bind'],
    lessonId: 'l-m31-01',
  },

  {
    ...S,
    id: 'ref-syntax-private-fields',
    slug: 'private-class-fields',
    name: 'Private class fields (#)',
    aliases: ['private fields', '#private', 'private methods', 'encapsulation', 'hash field'],
    topicIds: ['classes'],
    syntax: 'class C {\n  #secret = 1;\n  #method() {}\n  static #count = 0;\n  has(o) { return #secret in o; }\n}',
    summary: 'Truly private class members, enforced by the language. They are inaccessible from outside the class body — not by convention, but by syntax.',
    returns: 'Nothing on its own; declares a private member.',
    throws: '`SyntaxError` when accessed outside the class body. `TypeError` when accessed on an object that does not carry the field.',
    description: [
      'This is **hard privacy**, unlike a `_name` convention. Access from outside is a **`SyntaxError` at parse time**, not a runtime error, so it cannot be reached by any means — not bracket access, not `Object.keys`, not `JSON.stringify`, not a `Proxy`.',
      'The `#` is part of the name, so `this.#count` is required — `this["#count"]` reads an ordinary, unrelated property.',
      'Private members are **not inherited**: a subclass cannot see the parent\'s private fields. Use `protected`-style conventions or a `WeakMap` if a subclass genuinely needs access.',
      'They are invisible to serialisation, which is usually what you want — a private cache or an internal counter will not leak into `JSON.stringify` output.',
      'The `#field in obj` **brand check** is the safe way to test whether an object is a genuine instance carrying the field. Accessing a private field on an unrelated object throws a `TypeError`, so this test avoids a `try`/`catch`.',
      'Private methods and static private members work the same way.',
      'Compare with closure-based privacy, which is also genuine but creates one function per method per instance. Private fields keep methods on the prototype, so they give hard privacy at prototype cost.',
    ],
    examples: [
      {
        code: [
          'class Counter {',
          '  #count = 0;',
          '  static #instances = 0;',
          '',
          '  constructor() { Counter.#instances += 1; }',
          '',
          '  #bump(by) { this.#count += by; }',
          '',
          '  increment() { this.#bump(1); return this.#count; }',
          '',
          '  static isCounter(obj) { return #count in obj; }',
          '  static get instances() { return Counter.#instances; }',
          '}',
          '',
          'const c = new Counter();',
          'console.log(c.increment(), c.increment());',
          '',
          'console.log(Object.keys(c), JSON.stringify(c));',
          'console.log(Counter.isCounter(c), Counter.isCounter({}));',
          'console.log(Counter.instances);',
          'console.log(c["#count"]);',
        ].join('\n'),
        output: '1 2\n[] {}\ntrue false\n1\nundefined',
        caption: 'Invisible to keys and JSON — and "#count" is a different property entirely.',
      },
    ],
    caveats: [
      'Outside access is a `SyntaxError`, not a catchable runtime error.',
      'Not inherited by subclasses.',
      '`this["#x"]` is a different, ordinary property.',
      'Accessing one on a foreign object throws `TypeError` — use `#x in obj`.',
    ],
    commonMistakes: ['Expecting a subclass to reach a parent\'s private field.', 'Confusing `#x` with a `_x` naming convention.'],
    relatedEntries: ['ref-syntax-class', 'ref-weakmap'],
    lessonId: 'l-m31-02',
  },

  {
    ...M,
    id: 'ref-syntax-import',
    slug: 'import',
    name: 'import',
    aliases: ['import', 'es modules', 'esm', 'import statement', 'named import', 'default import'],
    topicIds: ['modules'],
    syntax: 'import defaultExport from "./mod.js"\nimport { named, other as alias } from "./mod.js"\nimport * as ns from "./mod.js"\nimport "./side-effect.js"',
    summary: 'Statically imports bindings from another module. Declarations are **hoisted** and resolved before any code runs.',
    returns: 'Binds names in the current module scope.',
    throws: '`SyntaxError` outside a module, or for a name the target does not export.',
    description: [
      'Imports are **static**: the specifier must be a string literal, and the whole dependency graph is known before execution. That is what makes **tree shaking** possible — a bundler can prove which exports are unused. A dynamic `require()` offers no such guarantee.',
      'Bindings are **live views**, not copies. If the exporting module reassigns an exported variable, importers see the new value. This differs from CommonJS, where `require` captures whatever the object held at that moment.',
      'Import declarations are **hoisted** and evaluated before the rest of the module body, so an `import` written at the bottom of a file still runs first.',
      'Imported bindings are **read-only**. Assigning to one is a `TypeError` in strict mode — which every module is.',
      'A module is evaluated **once** per specifier, no matter how many modules import it. That is what makes a module-level `const` a singleton.',
      'In the browser, specifiers must be full URLs or relative paths **including the file extension** — bare specifiers like `"lodash"` need a bundler or an import map.',
      'Circular imports do not fail outright, but a module can observe a partially-initialised binding from a cycle and see `undefined` where it expected a value. A cycle combined with top-level `await` can deadlock.',
      'It cannot execute under `new Function`, so this example is illustrative.',
    ],
    examples: [
      {
        code: [
          '// Illustrative: module syntax cannot run in this sandbox.',
          '// math.js',
          '// export const PI = 3.14159;',
          '// export function area(r) { return PI * r * r; }',
          '// export default function circumference(r) { return 2 * PI * r; }',
          '',
          '// main.js',
          'import circumference, { area, PI as ratio } from "./math.js";',
          'import * as math from "./math.js";',
          'import "./analytics.js"; // run for side effects only',
          '',
          'console.log(area(2), ratio, circumference(1));',
          'console.log(math.PI, math.default === circumference);',
          '',
          '// ratio = 3; // TypeError: imported bindings are read-only',
        ].join('\n'),
        caption: 'Default, named, aliased, namespace and side-effect-only forms.',
        runnable: false,
      },
    ],
    caveats: [
      'Only in ES modules — a `SyntaxError` in a classic script.',
      'Specifiers must be static string literals.',
      'Bindings are read-only and live.',
      'Browsers need full paths with extensions unless an import map is present.',
      'Circular imports can expose partially-initialised bindings.',
    ],
    commonMistakes: ['Omitting the `.js` extension in a browser-native module.', 'Assigning to an imported binding.'],
    relatedEntries: ['ref-syntax-export', 'ref-syntax-dynamic-import', 'ref-syntax-await'],
    lessonId: 'l-m28-02',
  },

  {
    ...M,
    id: 'ref-syntax-export',
    slug: 'export',
    name: 'export',
    aliases: ['export', 'export default', 'named export', 're-export', 'module exports'],
    topicIds: ['modules'],
    syntax: 'export const x = 1\nexport function f() {}\nexport { a, b as c }\nexport default value\nexport * from "./other.js"',
    summary: 'Declares what a module makes available to importers. Named exports are the default choice; `export default` provides exactly one unnamed value.',
    returns: 'Nothing at runtime; it declares the module\'s public surface.',
    throws: '`SyntaxError` for a duplicate export name, or for more than one default.',
    description: [
      '**Named exports** are refactor-friendly and tree-shakeable: the importer must use the exact name, so a rename is a visible error rather than a silent `undefined`.',
      '**`export default`** allows exactly one per module and the importer chooses any name for it. That flexibility is also its weakness — two files can import the same default under different names, which makes a codebase harder to search. Many style guides prefer named exports for that reason.',
      'Exports are **live bindings**, so a later reassignment inside the module is visible to importers. Exporting a `let` that changes is legal but usually a design smell; export a getter or a function instead.',
      'What is exported is the **binding, not a snapshot**, which is exactly why circular imports can work at all — and why they can also expose an uninitialised value.',
      'Re-exporting (`export * from`, `export { x } from`) is how an `index.js` presents a curated public surface for a feature folder without importing anything into itself.',
      '`"sideEffects": false` in `package.json` tells a bundler that dropping unused modules is safe. Without it, a bundler must conservatively keep modules that might do work at import time — a common reason tree shaking silently fails.',
      'It cannot execute under `new Function`, so this example is illustrative.',
    ],
    examples: [
      {
        code: [
          '// Illustrative: module syntax cannot run in this sandbox.',
          '// utils.js',
          'export const VERSION = "1.0";',
          'export function slugify(s) { return s.toLowerCase().replaceAll(" ", "-"); }',
          '',
          'function internal() { return "not exported"; }',
          '',
          'const a = 1;',
          'const b = 2;',
          'export { a, b as renamed };',
          '',
          'export default { VERSION, slugify };',
          '',
          '// index.js — a curated public surface',
          '// export { slugify } from "./utils.js";',
          '// export * from "./format.js";',
        ].join('\n'),
        caption: 'Inline, list, renamed, default and re-export forms.',
        runnable: false,
      },
    ],
    caveats: [
      'Only one `export default` per module.',
      'Export names must be unique.',
      'Exports are live bindings, not snapshots.',
      'Missing `"sideEffects": false` can defeat tree shaking.',
    ],
    commonMistakes: ['Mixing default and named exports inconsistently across a codebase.', 'Exporting a mutable `let` as shared state.'],
    relatedEntries: ['ref-syntax-import', 'ref-syntax-dynamic-import'],
    lessonId: 'l-m28-02',
  },

  {
    ...M,
    id: 'ref-syntax-dynamic-import',
    slug: 'dynamic-import',
    name: 'Dynamic import()',
    aliases: ['dynamic import', 'code splitting', 'lazy load module', 'conditional import', 'import expression'],
    topicIds: ['modules', 'performance'],
    syntax: 'const module = await import("./mod.js")\nimport("./mod.js").then((m) => m.default)',
    summary: 'Loads a module at runtime and returns a promise for its namespace object. The specifier may be computed, which static `import` forbids.',
    returns: 'A promise resolving to the **module namespace object** — named exports as properties, and the default export as `.default`.',
    throws: 'Rejects if the module cannot be loaded or throws during evaluation.',
    description: [
      'The result is the **namespace object**, so a default export is at `module.default`, not the resolved value itself. Forgetting that is the most common mistake here.',
      'It is the mechanism behind **code splitting**: a bundler turns each dynamic import into a separate chunk fetched only when the call runs. Route-level splitting and heavy conditional features — an editor, a chart library, a PDF viewer — are the standard uses.',
      'Unlike static `import`, the specifier can be an **expression**, which allows loading a module chosen at runtime. Bundlers can only analyse patterns they can see statically, so a fully arbitrary specifier may not be bundled correctly — keep a literal prefix.',
      'It works in classic scripts as well as modules, since it is an expression rather than a declaration.',
      'A module is still evaluated **once**: calling `import()` repeatedly for the same specifier returns the same already-resolved module.',
      'It returns a promise, so failures need handling. A chunk can fail to load after a deployment replaces the old files — a common production error worth catching with a reload prompt.',
      'It cannot execute under `new Function`, so this example is illustrative.',
    ],
    examples: [
      {
        code: [
          '// Illustrative: module loading is unavailable in this sandbox.',
          'async function openEditor(container) {',
          '  try {',
          '    // Only fetched when the user actually opens the editor.',
          '    const { createEditor } = await import("./editor.js");',
          '    return createEditor(container);',
          '  } catch (err) {',
          '    // A stale chunk after a deploy lands here.',
          '    console.error("Failed to load editor", err);',
          '    return null;',
          '  }',
          '}',
          '',
          'async function loadDriver(name) {',
          '  // Keep a literal prefix so the bundler can find the candidates.',
          '  const module = await import(`./drivers/${name}.js`);',
          '  return module.default; // default lives on .default',
          '}',
        ].join('\n'),
        caption: 'The default export is on .default, and a literal prefix keeps bundling analysable.',
        runnable: false,
      },
    ],
    caveats: [
      'Resolves to the namespace object — the default is on `.default`.',
      'A fully computed specifier may defeat bundler analysis.',
      'Chunk loading can fail after a deployment; handle the rejection.',
      'Overusing it fragments the bundle into too many small requests.',
    ],
    commonMistakes: ['Using the resolved module as though it were the default export.'],
    relatedEntries: ['ref-syntax-import', 'ref-syntax-export', 'ref-syntax-await'],
    lessonId: 'l-m28-04',
  },
];
