import { REFERENCE_CATEGORY as C, REFERENCE_ENV as E } from '../schema/types.js';

/**
 * Browser APIs: timers, observers, history, and the permission-gated APIs.
 *
 * Timers and `MutationObserver` execute here and are verified. The observers
 * that depend on layout, and every permission-gated API, cannot run in this
 * project's sandbox — those examples are marked `runnable: false` rather than
 * faked.
 */

const W = { category: C.WEB_APIS, environment: E.WEB_API };

export default [
  {
    ...W,
    id: 'ref-settimeout',
    slug: 'settimeout',
    name: 'setTimeout()',
    aliases: ['setTimeout', 'clearTimeout', 'delay', 'wait', 'schedule'],
    topicIds: ['async-foundations', 'event-loop'],
    mutates: false,
    syntax: 'setTimeout(callback, delay)\nsetTimeout(callback, delay, ...args)\nclearTimeout(id)',
    summary: 'Schedules a callback to run after **at least** the given delay. The delay is a minimum, never a guarantee.',
    parameters: [
      { name: 'callback', description: 'The function to run. Passing a **string** makes it behave like `eval` — never do that.' },
      { name: 'delay', optional: true, description: 'Minimum milliseconds, defaulting to `0`. Values above 2147483647 overflow and fire almost immediately.' },
      { name: 'args', optional: true, description: 'Extra arguments passed to the callback when it runs.' },
    ],
    returns: 'A numeric id in browsers (an object in Node), for `clearTimeout`.',
    description: [
      '`setTimeout` **schedules**; it does not pause. The callback becomes a macrotask that runs only when the call stack is empty and the event loop reaches it, so any long synchronous work delays it further.',
      'The whole **microtask queue drains first**, so a burst of promise reactions runs before any timer callback, even one with a delay of `0`.',
      'Browsers **clamp** nested timers to about 4ms after roughly five levels of nesting, and throttle background tabs much harder — often to once per second or less. A timer-driven counter in a background tab drifts badly.',
      'Never accumulate elapsed time by counting timer fires. Store a target timestamp and compute the remainder from `Date.now()` on each tick, so the display stays correct regardless of drift.',
      'Passing a string instead of a function invokes the same machinery as `eval` and is a code-injection risk. Always pass a function.',
      '`clearTimeout(id)` cancels a pending timer and is a harmless no-op for an id that has already fired or does not exist.',
    ],
    examples: [
      {
        code: [
          'const order = [];',
          '',
          'setTimeout(() => order.push("timeout 0"), 0);',
          'Promise.resolve().then(() => order.push("microtask"));',
          'order.push("sync");',
          '',
          'const cancelled = setTimeout(() => order.push("never"), 0);',
          'clearTimeout(cancelled);',
          '',
          'setTimeout((a, b) => {',
          '  order.push(`args ${a}${b}`);',
          '  console.log(order);',
          '}, 5, "x", "y");',
        ].join('\n'),
        output: '["sync", "microtask", "timeout 0", "args xy"]',
        caption: 'Microtasks always drain before any timer, even one with delay 0.',
      },
    ],
    caveats: [
      'The delay is a minimum, not a guarantee.',
      'Nested timers are clamped to ~4ms; background tabs are throttled hard.',
      'A delay above 2147483647 overflows and fires immediately.',
      'Passing a string behaves like `eval`.',
    ],
    commonMistakes: ['Counting timer fires to measure elapsed time.', 'Expecting `setTimeout(fn, 0)` to beat a promise callback.'],
    relatedEntries: ['ref-setinterval', 'ref-requestanimationframe', 'ref-date-now'],
    lessonId: 'l-m23-02',
  },

  {
    ...W,
    id: 'ref-setinterval',
    slug: 'setinterval',
    name: 'setInterval()',
    aliases: ['setInterval', 'clearInterval', 'repeat', 'polling', 'timer loop'],
    topicIds: ['async-foundations', 'event-loop'],
    mutates: false,
    syntax: 'setInterval(callback, delay)\nclearInterval(id)',
    summary: 'Runs a callback repeatedly at an interval. Because it schedules by wall clock rather than by completion, slow callbacks can queue up back to back.',
    parameters: [
      { name: 'callback', description: 'The function to run repeatedly.' },
      { name: 'delay', optional: true, description: 'Milliseconds between scheduled runs, defaulting to `0`.' },
    ],
    returns: 'An id for `clearInterval`.',
    description: [
      'It schedules by the clock regardless of how long the callback takes. If the work takes longer than the interval, callbacks queue and can run one immediately after another with no gap — "every second" quietly becomes "constantly".',
      'That is much worse for **asynchronous** work. `setInterval(() => fetch(url), 1000)` starts a request every second whether or not the previous one has returned, so a slow connection accumulates overlapping requests whose responses can arrive out of order.',
      'The fix is a **recursive `setTimeout`** that schedules the next run only after the current one finishes, guaranteeing a real gap and never more than one in flight. Put the rescheduling in a `finally` so a failure does not silently stop the loop.',
      '`setInterval` remains fine for cheap synchronous work — a clock display, a progress animation — where the callback cannot outrun its period.',
      'Always keep the id and clear it on teardown. An interval that outlives its component is one of the most common leaks in a single-page application, and it keeps everything its closure captured alive too.',
      'For polling, back off when the tab is hidden (`document.visibilityState`) and after repeated failures — and consider whether server-sent events or a WebSocket would remove the need to poll at all.',
    ],
    examples: [
      {
        code: [
          'let ticks = 0;',
          'const id = setInterval(() => {',
          '  ticks += 1;',
          '  if (ticks === 3) {',
          '    clearInterval(id);',
          '    console.log("interval ran", ticks, "times");',
          '  }',
          '}, 1);',
          '',
          'let polls = 0;',
          'function poll() {',
          '  polls += 1;',
          '  try {',
          '    if (polls === 2) console.log("recursive poll ran", polls, "times");',
          '  } finally {',
          '    if (polls < 2) setTimeout(poll, 1);',
          '  }',
          '}',
          'poll();',
        ].join('\n'),
        output: 'recursive poll ran 2 times\ninterval ran 3 times',
        caption: 'The recursive form schedules the next run only after the current one finishes.',
      },
    ],
    caveats: [
      'Schedules by clock, so slow callbacks queue with no gap.',
      'Overlaps asynchronous work — use a recursive `setTimeout` instead.',
      'Throttled in background tabs.',
      'An uncleared interval is a memory leak.',
    ],
    commonMistakes: ['Polling an API with `setInterval` and creating overlapping requests.', 'Losing the id so the interval can never be cleared.'],
    relatedEntries: ['ref-settimeout', 'ref-requestanimationframe'],
    lessonId: 'l-m23-02',
  },

  {
    ...W,
    id: 'ref-requestanimationframe',
    slug: 'requestanimationframe',
    name: 'requestAnimationFrame()',
    aliases: ['requestAnimationFrame', 'rAF', 'cancelAnimationFrame', 'animation loop', 'smooth animation'],
    topicIds: ['web-apis', 'performance', 'event-loop'],
    mutates: false,
    syntax: 'requestAnimationFrame(callback)\ncancelAnimationFrame(id)',
    summary: 'Schedules a callback to run just **before the next repaint**, synchronised with the display refresh rate.',
    parameters: [{ name: 'callback', description: 'Called with a `DOMHighResTimeStamp` — the frame\'s start time, equivalent to `performance.now()`.' }],
    returns: 'An id for `cancelAnimationFrame`.',
    description: [
      'It runs as part of the browser\'s rendering step, **after** all microtasks and immediately before style, layout and paint. DOM changes made inside it are painted in the same frame, with no intermediate visual state.',
      'It fires at the display refresh rate — 60Hz commonly, but 120Hz or higher on many devices. Animation must therefore be driven by the **elapsed time** passed to the callback, not by a fixed per-frame increment, or it runs at different speeds on different screens.',
      'It **pauses entirely in a background tab**, which saves battery and stops animations racing ahead invisibly. A `setInterval`-driven animation keeps firing at a throttled rate and produces uneven motion when the tab returns.',
      'It runs **once** per call. A continuous animation re-registers from inside the callback, and stops simply by not re-registering.',
      'Beyond animation, it is the right place to **batch DOM writes**: grouping them into one callback means a single layout pass. Reading a geometry property inside it still forces layout, so the read/write separation still matters.',
      '`requestIdleCallback` is the opposite end — it runs only when the browser has spare time, which suits prefetching and analytics but never work the user is waiting on.',
      'This project\'s sandbox has no rendering loop, so the example is illustrative.',
    ],
    examples: [
      {
        code: [
          '// Illustrative: no rendering loop in this sandbox.',
          'let rafId = null;',
          '',
          'function animate(startTime, duration, el) {',
          '  function frame(now) {',
          '    const elapsed = now - startTime;',
          '    const progress = Math.min(elapsed / duration, 1);',
          '',
          '    // Time-based, so it runs at the same speed on 60Hz and 120Hz.',
          '    el.style.transform = `translateX(${progress * 200}px)`;',
          '',
          '    if (progress < 1) rafId = requestAnimationFrame(frame);',
          '  }',
          '  rafId = requestAnimationFrame(frame);',
          '}',
          '',
          '// Stop it:',
          '// cancelAnimationFrame(rafId);',
        ].join('\n'),
        caption: 'Drive by elapsed time, not by a per-frame increment.',
        runnable: false,
      },
    ],
    caveats: [
      'Fires once per call — re-register for a continuous loop.',
      'Paused in background tabs, so it cannot drive background work.',
      'Refresh rate varies — never assume 60fps.',
      'Reading geometry inside it still forces layout.',
    ],
    commonMistakes: ['Using a fixed per-frame step, making animations faster on high-refresh displays.'],
    relatedEntries: ['ref-settimeout', 'ref-setinterval'],
    lessonId: 'l-m43-01',
  },

  {
    ...W,
    id: 'ref-intersectionobserver',
    slug: 'intersectionobserver',
    name: 'IntersectionObserver',
    aliases: ['IntersectionObserver', 'lazy loading', 'infinite scroll', 'is element visible', 'ResizeObserver'],
    topicIds: ['web-apis', 'performance', 'dom'],
    mutates: false,
    syntax: 'new IntersectionObserver(callback, options)\nobserver.observe(el)\nobserver.unobserve(el)\nobserver.disconnect()',
    summary: 'Reports asynchronously when an element enters or leaves the viewport — without a scroll listener and without forcing layout.',
    parameters: [
      { name: 'callback', description: 'Called as `(entries, observer)` with an array of `IntersectionObserverEntry` objects — one per change, batched.' },
      { name: 'options', optional: true, description: '`root` (defaults to the viewport), `rootMargin` to grow or shrink the detection box, and `threshold` — how much of the element must be visible.' },
    ],
    returns: 'An `IntersectionObserver`.',
    description: [
      'It replaces the scroll-listener-plus-`getBoundingClientRect()` pattern, which forced a synchronous layout on every scroll event. The observer does its work inside the browser\'s own layout pass and delivers results asynchronously.',
      '**`rootMargin`** is what makes lazy loading feel instant: `"200px"` starts loading before the element is actually visible. Without it, images visibly pop in late.',
      '**`threshold`** distinguishes the question being asked. `0` means "any pixel visible" — right for lazy loading. `0.5` means "half visible" — closer to what an impression counter should require.',
      'The callback fires **once immediately** on `observe()` with the current state, so an already-visible element triggers without any scrolling.',
      'For a one-shot effect, call `observer.unobserve(entry.target)` **before** running the work, so a callback that throws or causes a re-intersection cannot fire twice.',
      'Always `disconnect()` on teardown. An observer holds references to its targets, so an undisconnected one keeps removed elements alive — the same leak shape as an unremoved listener.',
      '`ResizeObserver` is the sibling for element **size** changes, and it catches changes a `window.resize` listener misses entirely — content growing, a sibling collapsing, a container query firing.',
      'Neither observer exists in this project\'s jsdom-based verifier, so this example is illustrative.',
    ],
    examples: [
      {
        code: [
          '// Illustrative: IntersectionObserver is unavailable in this sandbox.',
          'function onVisible(element, callback, { rootMargin = "200px" } = {}) {',
          '  const observer = new IntersectionObserver((entries) => {',
          '    for (const entry of entries) {',
          '      if (!entry.isIntersecting) continue;',
          '      observer.unobserve(entry.target); // before the callback, so it fires once',
          '      callback(entry.target, entry);',
          '    }',
          '  }, { rootMargin, threshold: 0 });',
          '',
          '  observer.observe(element);',
          '  return () => observer.disconnect();',
          '}',
          '',
          '// const stop = onVisible(img, (el) => { el.src = el.dataset.src; });',
        ].join('\n'),
        caption: 'Unobserve before the callback so it cannot fire twice.',
        runnable: false,
      },
    ],
    caveats: [
      'Fires once immediately on `observe()` with the current state.',
      'Callbacks are asynchronous and batched, not synchronous with scrolling.',
      'Must be disconnected, or it retains its targets.',
      'Unavailable in this project\'s example verifier.',
    ],
    commonMistakes: ['Omitting `rootMargin` and making lazy loading visibly late.', 'Forgetting `<img loading="lazy">` exists and needs no JavaScript at all.'],
    relatedEntries: ['ref-mutationobserver', 'ref-dom-queryselector'],
    lessonId: 'l-m27-04',
  },

  {
    ...W,
    id: 'ref-mutationobserver',
    slug: 'mutationobserver',
    name: 'MutationObserver',
    aliases: ['MutationObserver', 'watch dom changes', 'observe dom', 'detect dom mutation'],
    topicIds: ['web-apis', 'dom'],
    mutates: false,
    syntax: 'new MutationObserver(callback)\nobserver.observe(target, options)\nobserver.disconnect()\nobserver.takeRecords()',
    summary: 'Watches an element for DOM changes — child insertions and removals, attribute changes, text changes — and reports them in asynchronous batches.',
    parameters: [
      { name: 'callback', description: 'Called as `(mutations, observer)` with an array of `MutationRecord` objects.' },
      { name: 'options', description: 'At least one of `childList`, `attributes` or `characterData` must be `true`, or it throws. `subtree` extends the watch to all descendants.' },
    ],
    returns: 'A `MutationObserver`.',
    throws: '`TypeError` if none of `childList`, `attributes` or `characterData` is set.',
    description: [
      'Records are delivered **asynchronously as a microtask**, batched. Several changes in the same synchronous block produce one callback with several records, so the DOM has already settled by the time you see them.',
      'It replaced the deprecated mutation events, which fired synchronously on every change and were catastrophically slow.',
      'Inside your own application this is usually a **smell**: you already know when you changed the DOM. Its legitimate uses are reacting to markup you do not control — a third-party widget injecting content, a CMS-rendered region, or an integration with code you cannot modify.',
      'Watching a large subtree with `subtree: true` and `attributes: true` can produce a very high record volume. Scope the target and the option set as narrowly as possible.',
      'Mutating the DOM inside the callback can trigger the observer again — guard against loops by disconnecting first or filtering the records.',
      '`takeRecords()` drains any pending records without waiting for the callback, which is how you flush before disconnecting.',
      'A `MutationRecord` describes what changed: `type`, `target`, `addedNodes`, `removedNodes`, `attributeName` and `oldValue` when the corresponding `*OldValue` option was set.',
    ],
    examples: [
      {
        code: [
          'const host = document.createElement("div");',
          'document.body.append(host);',
          '',
          'const observer = new MutationObserver((records) => {',
          '  console.log("batched into", records.length, "record(s)");',
          '  for (const r of records) {',
          '    console.log(r.type, r.addedNodes.length, r.attributeName);',
          '  }',
          '  observer.disconnect();',
          '});',
          '',
          'observer.observe(host, { childList: true, attributes: true });',
          '',
          'host.append(document.createElement("span"));',
          'host.setAttribute("data-state", "ready");',
          'console.log("synchronous code finished first");',
        ].join('\n'),
        output: 'synchronous code finished first\nbatched into 2 record(s)\nchildList 1 null\nattributes 0 data-state',
        caption: 'Two changes, one asynchronous callback — the DOM has already settled.',
        needsDom: true,
      },
    ],
    caveats: [
      'Throws if none of `childList`, `attributes` or `characterData` is set.',
      'Callbacks are asynchronous — the DOM has already changed when you see them.',
      'Mutating inside the callback can retrigger the observer.',
      'Must be disconnected on teardown.',
    ],
    commonMistakes: ['Using it to react to your own DOM updates.', 'Watching an entire subtree when a single element would do.'],
    relatedEntries: ['ref-intersectionobserver', 'ref-dom-append'],
    lessonId: 'l-m27-04',
  },

  {
    ...W,
    id: 'ref-history-pushstate',
    slug: 'history-pushstate',
    name: 'History.pushState()',
    aliases: ['pushState', 'replaceState', 'history API', 'client side routing', 'popstate'],
    topicIds: ['web-apis', 'dom'],
    mutates: true,
    syntax: 'history.pushState(state, unused, url)\nhistory.replaceState(state, unused, url)',
    summary: 'Changes the URL and adds (or replaces) a history entry **without reloading the page** — the basis of client-side routing.',
    parameters: [
      { name: 'state', description: 'A structured-cloneable object stored with the entry and available later as `event.state`. It must not hold functions or DOM nodes.' },
      { name: 'unused', description: 'A legacy title parameter that every browser ignores. Pass `""`.' },
      { name: 'url', optional: true, description: 'The new URL. It **must be same-origin** or the call throws.' },
    ],
    returns: '`undefined`.',
    throws: '`SecurityError` for a cross-origin URL; `DataCloneError` if the state is not cloneable.',
    description: [
      '`pushState` adds a new entry, so Back returns to the previous one. `replaceState` overwrites the current entry, which is what you want for a redirect or a filter change that should not create a Back step.',
      'Neither fires a `popstate` event. Your own navigation must call the render function directly — only the user pressing Back or Forward fires `popstate`. That asymmetry catches out everyone writing their first router.',
      'The `state` object is stored with the entry and comes back as `event.state` on `popstate`. It is cloned with the structured clone algorithm, so functions and DOM nodes throw.',
      'The URL must be **same-origin**; a cross-origin URL throws a `SecurityError`. Paths, queries and hashes are all fine.',
      'Server configuration is a requirement, not an optional extra: with path-based routing the server must serve the application shell for **any** path, or a refresh on a deep URL is a genuine 404. Hash-based routing avoids that entirely and is the pragmatic choice on static hosting.',
      'Accessibility is easy to lose here. A real navigation moves focus and announces the new page; a `pushState` does neither. Move focus to the new heading and consider a live-region announcement.',
      'The Navigation API is the emerging replacement, unifying all of this behind a single `navigate` event — support is still uneven.',
    ],
    examples: [
      {
        code: [
          '// Illustrative: navigation is not available in this sandbox.',
          'function navigate(path, state = {}) {',
          '  history.pushState(state, "", path);',
          '  render(path); // pushState does NOT fire popstate — render explicitly',
          '}',
          '',
          '// Only Back/Forward fires this.',
          'window.addEventListener("popstate", (event) => {',
          '  render(location.pathname, event.state);',
          '});',
          '',
          '// A redirect should not add a Back step:',
          '// history.replaceState({}, "", "/login");',
          '',
          'function render(path, state) {',
          '  console.log("render", path, state);',
          '}',
        ].join('\n'),
        caption: 'pushState never fires popstate — call the renderer yourself.',
        runnable: false,
      },
    ],
    caveats: [
      'Does not fire `popstate` — only Back/Forward does.',
      'The URL must be same-origin.',
      'The state object must be structured-cloneable.',
      'Path routing requires the server to serve the shell for every path.',
      'Focus and announcements are not handled for you.',
    ],
    commonMistakes: ['Expecting `popstate` after your own `pushState`.', 'Forgetting the server rewrite and breaking refresh on deep links.'],
    relatedEntries: ['ref-url', 'ref-events-addeventlistener'],
    lessonId: 'l-m27-03',
  },

  {
    ...W,
    id: 'ref-navigator-clipboard',
    slug: 'navigator-clipboard',
    name: 'Navigator.clipboard',
    aliases: ['clipboard', 'navigator.clipboard', 'copy to clipboard', 'writeText', 'readText'],
    topicIds: ['web-apis', 'security'],
    mutates: false,
    syntax: 'navigator.clipboard.writeText(text)\nnavigator.clipboard.readText()',
    summary: 'The asynchronous Clipboard API. Writing usually requires a user gesture; reading always requires explicit permission.',
    parameters: [{ name: 'text', description: 'For `writeText`: the string to place on the clipboard.' }],
    returns: 'A promise. `writeText` resolves with `undefined`; `readText` resolves with the clipboard text.',
    throws: 'Rejects with `NotAllowedError` when there is no user gesture, when permission is denied, or when the document is not focused.',
    description: [
      '**Writing** must normally happen inside a user gesture — a click handler. Calling it on page load or after an `await` that outlives the gesture rejects with `NotAllowedError`.',
      '**Reading** is far more restricted: it requires explicit permission and is unavailable in many contexts, because a page that could silently read the clipboard could steal whatever the user last copied — often a password.',
      'The whole API requires a **secure context** (HTTPS or localhost) and a focused document. A rejection in a background tab is normal, not a bug.',
      'Every method is promise-based, so failures must be handled. There is no synchronous fallback worth writing today — the old `document.execCommand("copy")` is deprecated and unreliable.',
      'Always give visible feedback after a copy. The clipboard changes invisibly, so without confirmation the user cannot tell whether it worked.',
      'This project\'s sandbox has no clipboard access, so the example is illustrative.',
    ],
    examples: [
      {
        code: [
          '// Illustrative: no clipboard access in this sandbox.',
          'async function copy(text, button) {',
          '  try {',
          '    await navigator.clipboard.writeText(text);',
          '    button.textContent = "Copied";',
          '  } catch (err) {',
          '    // No gesture, denied permission, or an unfocused document.',
          '    button.textContent = "Press Ctrl+C to copy";',
          '  }',
          '}',
          '',
          '// Must be called from within a user gesture:',
          '// button.addEventListener("click", () => copy(code, button));',
        ].join('\n'),
        caption: 'Always handle the rejection and confirm the copy visibly.',
        runnable: false,
      },
    ],
    caveats: [
      'Requires a secure context and a focused document.',
      'Writing needs a user gesture; reading needs explicit permission.',
      'Rejects with `NotAllowedError` rather than failing silently.',
      'Unavailable in this project\'s sandbox.',
    ],
    commonMistakes: ['Calling it outside a user gesture.', 'Not handling the rejection, leaving the user with no feedback.'],
    relatedEntries: ['ref-navigator-geolocation'],
    lessonId: 'l-m27-05',
  },

  {
    ...W,
    id: 'ref-navigator-geolocation',
    slug: 'navigator-geolocation',
    name: 'Navigator.geolocation',
    aliases: ['geolocation', 'getCurrentPosition', 'watchPosition', 'user location', 'gps'],
    topicIds: ['web-apis', 'security'],
    mutates: false,
    syntax: 'navigator.geolocation.getCurrentPosition(success, error, options)\nnavigator.geolocation.watchPosition(success, error, options)\nnavigator.geolocation.clearWatch(id)',
    summary: 'Requests the device\'s location, subject to explicit user permission. It is **callback-based**, not promise-based.',
    parameters: [
      { name: 'success', description: 'Called with a `GeolocationPosition` whose `coords` carries `latitude`, `longitude` and `accuracy` in metres.' },
      { name: 'error', optional: true, description: 'Called with a `GeolocationPositionError`: `PERMISSION_DENIED`, `POSITION_UNAVAILABLE` or `TIMEOUT`.' },
      { name: 'options', optional: true, description: '`enableHighAccuracy`, `timeout`, and `maximumAge` for accepting a cached position.' },
    ],
    returns: '`undefined` from `getCurrentPosition`; a watch id from `watchPosition`.',
    description: [
      'It predates promises and takes **callbacks**, so wrapping it in a promise is the usual first step — a textbook use of the `new Promise` constructor, since it is adapting a genuinely non-promise API.',
      'It requires a **secure context** and explicit user permission. The permission prompt appears on first use, and a denial is permanent for that origin until the user changes it in browser settings.',
      'The `error` callback is not optional in practice. Denial, an unavailable position and a timeout are all normal outcomes, and without a handler the request simply appears to hang.',
      'Always pass a `timeout`. Without one the request can wait indefinitely, particularly with `enableHighAccuracy: true` indoors.',
      '`accuracy` is in metres and is often poor — hundreds of metres on desktop, where the position comes from IP or wifi rather than GPS. Design for imprecision rather than assuming a street address.',
      '`watchPosition` fires repeatedly as the device moves and **must** be cleared with `clearWatch`, or it keeps the GPS active and drains battery.',
      'Location is personal data. Request it only when the feature needs it, explain why before triggering the prompt, and do not store it without a reason.',
    ],
    examples: [
      {
        code: [
          '// Illustrative: no geolocation in this sandbox.',
          'function getPosition({ timeout = 10000 } = {}) {',
          '  return new Promise((resolve, reject) => {',
          '    if (!("geolocation" in navigator)) {',
          '      reject(new Error("Geolocation unsupported"));',
          '      return;',
          '    }',
          '    navigator.geolocation.getCurrentPosition(',
          '      (position) => resolve({',
          '        lat: position.coords.latitude,',
          '        lon: position.coords.longitude,',
          '        accuracyMetres: position.coords.accuracy,',
          '      }),',
          '      (err) => reject(err),',
          '      { timeout, maximumAge: 60000 },',
          '    );',
          '  });',
          '}',
        ].join('\n'),
        caption: 'Wrapping a callback API in a promise — and always passing a timeout.',
        runnable: false,
      },
    ],
    caveats: [
      'Callback-based, not promise-based.',
      'Requires a secure context and explicit permission; denial is sticky.',
      'Without a `timeout` the request can hang indefinitely.',
      '`accuracy` can be hundreds of metres.',
      '`watchPosition` must be cleared or it drains battery.',
    ],
    commonMistakes: ['Omitting the error callback.', 'Assuming the coordinates are precise.'],
    relatedEntries: ['ref-navigator-clipboard', 'ref-promise-ctor'],
    lessonId: 'l-m27-05',
  },

  {
    ...W,
    id: 'ref-worker',
    slug: 'web-worker',
    name: 'Worker',
    aliases: ['Web Worker', 'new Worker', 'postMessage', 'background thread', 'parallelism'],
    topicIds: ['web-apis', 'performance'],
    mutates: false,
    syntax: 'new Worker(scriptURL, options)\nworker.postMessage(data)\nworker.terminate()',
    summary: 'Runs a script on a **separate thread** with its own event loop, communicating only by message passing. The one route to real parallelism in the browser.',
    parameters: [
      { name: 'scriptURL', description: 'A same-origin script URL. Pass `{ type: "module" }` to use `import` inside the worker.' },
      { name: 'data', description: 'For `postMessage`: any structured-cloneable value. Functions and DOM nodes throw.' },
    ],
    returns: 'A `Worker` object that is an `EventTarget` — listen for `message` and `error`.',
    throws: '`DataCloneError` when the message is not structured-cloneable.',
    description: [
      'A worker has **no DOM access**: no `document`, no `window`, no direct rendering. That restriction is what makes it safe — there is no shared mutable state, so none of the data races that make threaded programming hard can occur.',
      'It is the right answer for genuinely expensive **pure computation**: parsing a large file, image processing, running a search index. It is the wrong answer for I/O, which is already off the main thread.',
      'Messages are copied with the **structured clone** algorithm, so there is a serialisation cost proportional to the data size. That makes workers pay off for chunky work and not for many tiny calls. **Transferable** objects — `ArrayBuffer`, `MessagePort` — can be moved instead of copied, becoming unusable in the sender.',
      '`terminate()` stops the worker immediately, without letting it finish. Workers are not free — each has its own JavaScript context — so a pool is better than one per task.',
      '`SharedArrayBuffer` with `Atomics` does allow genuinely shared memory between workers, and with it come real race conditions. It is gated behind cross-origin isolation headers because of speculative-execution attacks, and is the exception rather than the model.',
      'Errors inside a worker surface on its `error` event, not as an exception at the call site. Without a handler, a worker can fail silently.',
      'This project\'s sandbox cannot spawn workers, so the example is illustrative.',
    ],
    examples: [
      {
        code: [
          '// Illustrative: workers cannot be spawned in this sandbox.',
          '// main.js',
          'const worker = new Worker("./heavy.js", { type: "module" });',
          '',
          'worker.addEventListener("message", (event) => {',
          '  console.log("result:", event.data);',
          '  worker.terminate();',
          '});',
          '',
          '// Errors surface here, not as a thrown exception.',
          'worker.addEventListener("error", (event) => {',
          '  console.error("worker failed:", event.message);',
          '});',
          '',
          'worker.postMessage({ rows: 100000 });',
          '',
          '// heavy.js',
          '// self.addEventListener("message", (event) => {',
          '//   self.postMessage(compute(event.data.rows));',
          '// });',
        ].join('\n'),
        caption: 'Message passing only — and a worker error never throws at the call site.',
        runnable: false,
      },
    ],
    caveats: [
      'No DOM access at all.',
      'Messages are copied, so large payloads cost serialisation time.',
      'Errors surface on the `error` event, not as exceptions.',
      'Each worker has real memory cost — pool them.',
      'Cannot be spawned in this project\'s sandbox.',
    ],
    commonMistakes: ['Using a worker for I/O, which is already asynchronous.', 'Sending large objects repeatedly and paying more in cloning than the work saved.'],
    relatedEntries: ['ref-structuredclone', 'ref-requestanimationframe'],
    lessonId: 'l-m43-01',
  },
];
