import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm45';

export default [
  /* ================================================================== */
  {
    id: 'l-m45-01',
    slug: 'npm-versioning-and-tooling',
    moduleId: M,
    order: 1,
    title: 'npm, Versioning and Tooling',
    description: 'Packages, semver ranges, lockfiles, and what linters, formatters and bundlers each do.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 18,
    xp: 45,
    topicIds: ['tooling'],
    prerequisites: ['l-m44-02'],
    learningObjectives: [
      'Read package.json and explain its key fields',
      'Interpret semver ranges and explain what a lockfile adds',
      'Distinguish dependencies from devDependencies',
      'Explain what a linter, formatter and bundler each do',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'package.json',
      },
      {
        kind: SECTION.CODE,
        language: 'json',
        caption: 'The fields that matter day to day.',
        code: [
          '{',
          '  "name": "my-app",',
          '  "version": "1.4.2",',
          '  "type": "module",',
          '',
          '  "scripts": {',
          '    "dev": "vite",',
          '    "build": "vite build",',
          '    "test": "vitest run",',
          '    "lint": "eslint . --max-warnings=0"',
          '  },',
          '',
          '  "dependencies": {',
          '    "date-fns": "^3.6.0"',
          '  },',
          '',
          '  "devDependencies": {',
          '    "vite": "^5.2.0",',
          '    "vitest": "^1.6.0",',
          '    "eslint": "^9.0.0"',
          '  }',
          '}',
        ].join('\n'),
      },
      {
        kind: SECTION.TERMS,
        terms: [
          { term: 'name / version', definition: 'Identify the package. Required if you publish; conventional otherwise.' },
          { term: 'type', definition: '`"module"` makes `.js` files ES modules (Module 28). Without it they are treated as CommonJS.' },
          { term: 'scripts', definition: 'Named commands run with `npm run <name>`. `test` and `start` can be run without `run`.' },
          { term: 'dependencies', definition: 'Needed by the code that **ships**.' },
          { term: 'devDependencies', definition: 'Needed only to build, test or lint — not at runtime.' },
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'bash',
        caption: 'The commands you will actually use.',
        code: [
          '# Create a package.json (-y accepts the defaults)',
          'npm init -y',
          '',
          '# Install everything listed in package.json',
          'npm install',
          '',
          '# Add a runtime dependency',
          'npm install date-fns',
          '',
          '# Add a build-time-only dependency',
          'npm install --save-dev vitest',
          '',
          '# Run a script',
          'npm run build',
          '',
          '# Report known vulnerabilities in the dependency tree',
          'npm audit',
          '',
          '# Install exactly what the lockfile specifies — use this in CI',
          'npm ci',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: '`npm install` versus `npm ci`',
        body: [
          '`npm install` may **update** the lockfile if `package.json` allows a newer version within its range. That is what you want while developing.',
          '`npm ci` deletes `node_modules` and installs **exactly** what the lockfile records, failing if the lockfile and `package.json` disagree. That is what you want in CI and deployment, because it makes the install reproducible.',
          'Using `npm install` in CI is a common cause of "it worked yesterday" — a dependency released a patch overnight and the build picked it up.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'The dependencies / devDependencies split is a convention, not enforcement',
        body: [
          'Nothing stops your shipped code importing a `devDependency` — it will work locally and fail in a production install that omits them.',
          'The split matters for **server** deployments (`npm install --omit=dev` skips devDependencies) and for **published packages**, where consumers install your `dependencies` but not your dev tooling.',
          'For a **bundled front end** the distinction is looser: the bundler includes whatever your code imports regardless of which list it came from. Treat it as documentation of intent, and put anything the shipped code imports in `dependencies`.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Semantic versioning',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'What a version number promises, and what a range allows.',
        code: [
          '"use strict";',
          '',
          'function describe(version) {',
          '  const [major, minor, patch] = version.split(".").map(Number);',
          '  return { major, minor, patch };',
          '}',
          '',
          'console.log("3.6.1 ->", describe("3.6.1"));',
          '',
          '// What each position signals about a release',
          'const meaning = {',
          '  major: "breaking change — your code may need updating",',
          '  minor: "new feature, backwards compatible",',
          '  patch: "bug fix, backwards compatible",',
          '};',
          '',
          'for (const [part, note] of Object.entries(meaning)) {',
          '  console.log(`${part.padEnd(6)} ${note}`);',
          '}',
          '',
          '// Does a version satisfy a caret or tilde range?',
          'function satisfies(range, version) {',
          '  const operator = range[0];',
          '  const base = describe(range.slice(1));',
          '  const v = describe(version);',
          '',
          '  if (v.major !== base.major) return false;',
          '',
          '  // ~ allows patch updates only; ^ allows minor and patch',
          '  if (operator === "~" && v.minor !== base.minor) return false;',
          '',
          '  // Must not be older than the base',
          '  if (v.minor < base.minor) return false;',
          '  if (v.minor === base.minor && v.patch < base.patch) return false;',
          '',
          '  return true;',
          '}',
          '',
          'for (const candidate of ["3.6.0", "3.6.5", "3.9.0", "4.0.0", "3.5.9"]) {',
          '  console.log(`${candidate}: ^3.6.0 ${satisfies("^3.6.0", candidate)}, ~3.6.0 ${satisfies("~3.6.0", candidate)}`);',
          '}',
        ].join('\n'),
        output: [
          '3.6.1 -> {major: 3, minor: 6, patch: 1}',
          'major  breaking change — your code may need updating',
          'minor  new feature, backwards compatible',
          'patch  bug fix, backwards compatible',
          '3.6.0: ^3.6.0 true, ~3.6.0 true',
          '3.6.5: ^3.6.0 true, ~3.6.0 true',
          '3.9.0: ^3.6.0 true, ~3.6.0 false',
          '4.0.0: ^3.6.0 false, ~3.6.0 false',
          '3.5.9: ^3.6.0 false, ~3.6.0 false',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'Semver is a promise, not a guarantee',
        body: [
          '`^3.6.0` means "at least 3.6.0, below 4.0.0" and `~3.6.0` means "at least 3.6.0, below 3.7.0". Those are the mechanics.',
          'What the mechanics cannot enforce is that the **maintainer classified the change correctly**. A "patch" release can break you — through an unintended behaviour change, or because you depended on something the author considered an implementation detail.',
          'Two further caveats: versions **below `1.0.0`** are conventionally unstable, and `^0.5.2` allows only patch updates rather than minor ones. And a range applies to your **whole tree**, including dependencies of dependencies you never chose.',
          'This is precisely why the lockfile exists.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The lockfile',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Commit the lockfile',
        body: [
          '`package.json` records **ranges**; `package-lock.json` records the **exact resolved version of every package in the tree**, including transitive ones, with an integrity hash for each.',
          'Without it, two developers installing on different days get different trees, and a build that passes locally can fail in CI for reasons nothing in your code explains.',
          'So: **commit it**, and do not delete it to "fix" an install problem. If the tree genuinely needs updating, use `npm update` or install a specific version — both of which record their result in the lockfile deliberately.',
          'The integrity hashes matter for security too: they mean a republished package with different contents is detected rather than silently installed (Module 44).',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Linting and formatting',
      },
      {
        kind: SECTION.TABLE,
        headers: ['', 'Linter (ESLint)', 'Formatter (Prettier)'],
        rows: [
          ['Question it answers', '**Is this likely to be a bug?**', '**How should this look?**'],
          ['Typical finding', 'Unused variable, `await` in a loop, missing dependency', 'Indentation, quote style, line width'],
          ['Can it be wrong?', 'Yes — rules need judgement and configuration', 'Rarely — it is deterministic'],
          ['Worth arguing about', 'Sometimes', '**No** — pick a config and stop'],
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The kinds of problem a linter catches that a formatter cannot.',
        code: [
          '"use strict";',
          '',
          '// A tiny model of the categories a linter reports',
          'function analyse(code) {',
          '  const findings = [];',
          '',
          '  if (/\\bvar\\b/.test(code)) findings.push("prefer const/let over var");',
          '  if (/(^|[^=!<>])==(?!=)/.test(code)) findings.push("prefer === over ==");',
          '  if (/console\\.log/.test(code)) findings.push("unexpected console statement");',
          '  if (/catch\\s*\\([^)]*\\)\\s*\\{\\s*\\}/.test(code)) findings.push("empty catch block swallows errors");',
          '',
          '  return findings;',
          '}',
          '',
          'console.log("clean :", analyse("const total = a === b ? 1 : 2;"));',
          'console.log("var   :", analyse("var x = 1;"));',
          'console.log("loose :", analyse("if (a == b) {}"));',
          'console.log("empty :", analyse("try { risky(); } catch (e) {}"));',
          '',
          '// None of these is a FORMATTING issue — reindenting fixes none of them.',
          'console.log("multiple:", analyse("var a = 1; if (a == 2) { console.log(a); }"));',
        ].join('\n'),
        output: [
          'clean : []',
          'var   : ["prefer const/let over var"]',
          'loose : ["prefer === over =="]',
          'empty : ["empty catch block swallows errors"]',
          'multiple: ["prefer const/let over var", "prefer === over ==", "unexpected console statement"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Two different jobs',
        body: [
          'A **formatter** rewrites your code to a consistent shape. It has no opinion about correctness, and its value is ending style discussions — the output is deterministic, so there is nothing to debate in review.',
          'A **linter** finds patterns that are likely bugs or that violate agreed practice: an unused variable, a promise never awaited, a `useEffect` missing a dependency, an empty `catch` that swallows errors (Module 22).',
          'Run both automatically — in the editor while writing, and in CI so nothing merges without passing. Note this project runs `eslint . --max-warnings=0`, which treats warnings as failures, precisely so the count cannot creep upward.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Build tools',
      },
      {
        kind: SECTION.LIST,
        items: [
          '**A dev server** serves your source with fast reloads, so a change appears in the browser immediately without a full rebuild.',
          '**Module resolution** lets you write `import { x } from "some-package"` — a bare specifier browsers cannot resolve on their own (Module 28).',
          '**A production build** bundles, minifies, tree-shakes unused exports, and splits code at dynamic `import()` boundaries.',
          '**Asset handling** turns imported CSS, images and fonts into build outputs with hashed filenames for caching.',
          '**Environment variables** are substituted at build time — which, as Module 44 established, means they are **not secrets**.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'bash',
        caption: 'The everyday build workflow.',
        code: [
          '# Start the dev server with hot reloading',
          'npm run dev',
          '',
          '# Produce an optimised build in dist/',
          'npm run build',
          '',
          '# Serve the built output locally, to check it before deploying',
          'npm run preview',
          '',
          '# A production build differs from dev in ways that matter:',
          '#   - minified, so error messages and stack traces differ',
          '#   - tree-shaken, so unused code is gone',
          '#   - environment variables are baked in',
          '# Always test the BUILT output before deploying, not just dev.',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'The dev server is not what you ship',
        body: [
          'Dev and production builds differ enough that "it works in dev" is not evidence. Minification changes stack traces, tree-shaking removes code that was reachable in dev, and a missing extension in an import may resolve in dev and fail when loaded natively (Module 28).',
          'Source maps bridge the gap for debugging: they map minified positions back to your original source, so DevTools can show you the code you wrote. Generate them, and be deliberate about whether you serve them publicly.',
          'The habit worth forming: run the production build and preview it before deploying anything non-trivial.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// package.json says:  "date-fns": "^3.6.0"',
          '// The lockfile records: date-fns 3.6.0',
          '//',
          '// date-fns 3.9.1 is released. A colleague runs `npm ci`',
          '// and you run `npm install`. What does each get?',
        ].join('\n'),
        options: [
          'npm ci installs exactly 3.6.0 from the lockfile; npm install may resolve 3.9.1 and update the lockfile',
          'Both get 3.9.1',
          'Both get 3.6.0',
          'npm ci fails because a newer version exists',
        ],
        correct: 0,
        explanation:
          '`npm ci` installs **exactly** what the lockfile records, ignoring that a newer version satisfies the range — which is what makes it reproducible and why it belongs in CI. `npm install` is allowed to resolve a newer version within `^3.6.0` (anything below `4.0.0`) and will **write that into the lockfile**, producing a diff you should review rather than commit blindly. This is exactly why lockfiles exist and why they must be committed: without one, every install is a fresh resolution and "it worked yesterday" becomes a real failure mode.',
      },
    ],
    exercises: [
      {
        id: 'ex-m45-01-a',
        title: 'Interpret a semver range',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['tooling'],
        instructions:
          'Write `allows(range, version)` returning whether a version satisfies a `^` or `~` range. `^` permits minor and patch updates within the same major; `~` permits patch updates only. Neither permits going backwards.',
        starterCode: [
          'function allows(range, version) {',
          '  // Compare major, minor and patch numerically.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'caret allows the exact version', body: 'expect(allows("^3.6.0", "3.6.0")).toBe(true);' },
          { name: 'caret allows a patch update', body: 'expect(allows("^3.6.0", "3.6.9")).toBe(true);' },
          { name: 'caret allows a minor update', body: 'expect(allows("^3.6.0", "3.9.0")).toBe(true);' },
          { name: 'caret rejects a major update', body: 'expect(allows("^3.6.0", "4.0.0")).toBe(false);' },
          { name: 'tilde allows a patch update', body: 'expect(allows("~3.6.0", "3.6.9")).toBe(true);' },
          { name: 'tilde rejects a minor update', body: 'expect(allows("~3.6.0", "3.7.0")).toBe(false);' },
          { name: 'rejects an older version', body: 'expect(allows("^3.6.0", "3.5.9")).toBe(false);' },
          { name: 'rejects an older patch', body: 'expect(allows("^3.6.2", "3.6.1")).toBe(false);', hidden: true },
        ],
        hints: [
          'Split both on "." after removing the leading operator.',
          'A different major is always false.',
          'For `~`, a different minor is false; then check it is not older.',
        ],
        solution: [
          'function allows(range, version) {',
          '  const operator = range[0];',
          '  const [rMajor, rMinor, rPatch] = range.slice(1).split(".").map(Number);',
          '  const [vMajor, vMinor, vPatch] = version.split(".").map(Number);',
          '',
          '  if (vMajor !== rMajor) return false;',
          '  if (operator === "~" && vMinor !== rMinor) return false;',
          '',
          '  if (vMinor < rMinor) return false;',
          '  if (vMinor === rMinor && vPatch < rPatch) return false;',
          '',
          '  return true;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The major check comes first because neither operator ever crosses a major boundary — that is the whole point of semver signalling breaking changes. The `~` check then additionally pins the minor. The final two comparisons enforce "not older", which is what makes the seventh test and the hidden test pass: a range is a **floor** as well as a ceiling, so `^3.6.2` rejects `3.6.1`. Note real semver supports far more syntax (`>=`, `||`, pre-release tags); this covers the two operators you will actually see in `package.json`.',
      },
      {
        id: 'ex-m45-01-b',
        title: 'Why commit the lockfile?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['tooling'],
        instructions:
          'What does `package-lock.json` provide that `package.json` cannot?',
        options: [
          'A list of which packages are used',
          'The exact resolved version of every package in the tree, including transitive ones, with integrity hashes — making installs reproducible',
          'Faster installs only',
          'Automatic security patches',
        ],
        correct: 1,
        hints: [
          'What does package.json actually record — a version, or a range?',
        ],
        solution: 'The exact resolved version of every package in the tree, including transitive ones, with integrity hashes — making installs reproducible',
        solutionExplanation:
          '`package.json` records **ranges** such as `^3.6.0`, so two installs on different days can legitimately produce different trees — including different versions of transitive dependencies you never chose. The lockfile pins every resolved version, which is what makes a build reproducible and stops "it worked yesterday". The integrity hashes add a security property too: a package republished with different contents is detected rather than installed silently. It does speed installs up, but that is a side effect rather than the purpose.',
      },
      {
        id: 'ex-m45-01-c',
        title: 'Classify the dependencies',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['tooling'],
        instructions:
          'Write `classify(packages)` splitting a list of `{ name, usedAtRuntime }` into `{ dependencies, devDependencies }` arrays of names, preserving order.',
        starterCode: [
          'function classify(packages) {',
          '  // Shipped code needs it? dependencies. Otherwise devDependencies.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'classifies a runtime package', body: 'expect(classify([{ name: "date-fns", usedAtRuntime: true }])).toEqual({ dependencies: ["date-fns"], devDependencies: [] });' },
          { name: 'classifies a build tool', body: 'expect(classify([{ name: "vite", usedAtRuntime: false }])).toEqual({ dependencies: [], devDependencies: ["vite"] });' },
          { name: 'splits a mixed list', body: 'expect(classify([{ name: "a", usedAtRuntime: true }, { name: "b", usedAtRuntime: false }])).toEqual({ dependencies: ["a"], devDependencies: ["b"] });' },
          { name: 'handles an empty list', body: 'expect(classify([])).toEqual({ dependencies: [], devDependencies: [] });' },
          { name: 'preserves order', body: 'expect(classify([{ name: "z", usedAtRuntime: true }, { name: "a", usedAtRuntime: true }]).dependencies).toEqual(["z", "a"]);' },
          { name: 'returns names, not objects', body: 'expect(typeof classify([{ name: "x", usedAtRuntime: true }]).dependencies[0]).toBe("string");' },
          { name: 'does not mutate the input', body: 'const p = [{ name: "x", usedAtRuntime: true }]; classify(p); expect(p.length).toBe(1);', hidden: true },
        ],
        hints: [
          '`filter` then `map` to names, twice.',
          'Or one loop pushing into two arrays.',
        ],
        solution: [
          'function classify(packages) {',
          '  const dependencies = [];',
          '  const devDependencies = [];',
          '',
          '  for (const pkg of packages) {',
          '    if (pkg.usedAtRuntime) {',
          '      dependencies.push(pkg.name);',
          '    } else {',
          '      devDependencies.push(pkg.name);',
          '    }',
          '  }',
          '',
          '  return { dependencies, devDependencies };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'One pass pushing into two arrays preserves order in both and builds new arrays, so the input is untouched. The rule it encodes is the real one: **does the shipped code import it?** A date library does; Vite, Vitest and ESLint do not. Remember the split is a **convention** rather than enforcement — nothing stops shipped code importing a devDependency, and it will then work locally and fail in a production install that omits them.',
      },
      {
        id: 'ex-m45-01-d',
        title: 'Linter or formatter?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['tooling'],
        instructions:
          'Which finding comes from a linter rather than a formatter?',
        options: [
          'Inconsistent indentation',
          'A promise created but never awaited',
          'Single quotes where the project uses double',
          'A line longer than 100 characters',
        ],
        correct: 1,
        hints: [
          'Which one is about likely incorrect behaviour?',
        ],
        solution: 'A promise created but never awaited',
        solutionExplanation:
          'A floating promise is a likely **bug** — the code continues before the work completes, and a rejection may go unhandled (Module 42 showed this silently passing a test). Only a linter, which understands the code\'s meaning, can report that. The other three are purely **presentational**: a formatter rewrites them deterministically, which is exactly why they are not worth discussing in review. Run both automatically, in the editor and in CI.',
      },
    ],
    quiz: {
      id: 'qz-m45-01',
      questions: [
        {
          id: 'q-m45-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['tooling'],
          prompt: 'What does ^3.6.0 allow?',
          options: [
            'Only 3.6.0',
            'Anything from 3.6.0 up to but not including 4.0.0',
            'Anything from 3.6.0 to 3.6.9',
            'Any version 3 or higher',
          ],
          correct: 1,
          optionExplanations: [
            'That would be an exact pin.',
            'Correct — minor and patch, same major.',
            'That is the tilde range.',
            'It stops below the next major.',
          ],
          explanation:
            'The caret permits minor and patch updates within the same major, since semver says those should be backwards compatible. Note versions below 1.0.0 behave differently.',
        },
        {
          id: 'q-m45-01-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['tooling'],
          prompt: 'When should you use npm ci instead of npm install?',
          options: [
            'Never — they are the same',
            'In CI and deployment, where installing exactly what the lockfile records makes the build reproducible',
            'Only when adding a package',
            'Only on Windows',
          ],
          correct: 1,
          optionExplanations: [
            'They differ in whether the lockfile can change.',
            'Correct — reproducible installs.',
            'That is npm install.',
            'Platform is irrelevant.',
          ],
          explanation:
            '`npm ci` installs exactly the locked tree and fails if the lockfile disagrees with `package.json`. `npm install` may resolve newer versions and rewrite the lockfile.',
        },
        {
          id: 'q-m45-01-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['tooling'],
          prompt: 'A patch release can never break your code.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Semver is a promise the maintainer may misjudge.',
            'Correct — which is why lockfiles matter.',
          ],
          explanation:
            'Semver expresses intent, not a guarantee. A maintainer can classify a change wrongly, or you may depend on something they considered an implementation detail.',
        },
        {
          id: 'q-m45-01-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['tooling'],
          prompt: 'Why test the production build rather than only the dev server?',
          options: [
            'The dev server is slower',
            'They differ — minification, tree-shaking and inlined environment variables can change behaviour',
            'Production has more features',
            'It is not necessary',
          ],
          correct: 1,
          optionExplanations: [
            'Dev is usually faster to iterate on.',
            'Correct — "works in dev" is not evidence.',
            'The code is the same, transformed differently.',
            'It catches real failures.',
          ],
          explanation:
            'Minification changes stack traces, tree-shaking removes code reachable in dev, and an import missing an extension may resolve in dev and fail natively.',
        },
      ],
    },
    summary:
      '**`package.json`** records `name`, `version`, `type` (`"module"` makes `.js` files ES modules), **`scripts`** run with `npm run`, and the **`dependencies`** / **`devDependencies`** split — shipped code versus build tooling. That split is a **convention, not enforcement**: nothing stops shipped code importing a devDependency, and for a bundled front end the bundler includes whatever you import regardless. **Semver** signals intent — major means breaking, minor means a compatible feature, patch means a compatible fix — with **`^3.6.0`** allowing minor and patch below `4.0.0` and **`~3.6.0`** allowing patch only. But semver is **a promise, not a guarantee**: a maintainer can misclassify a change, versions below `1.0.0` behave differently, and a range applies to your **whole tree** including transitive packages you never chose. That is exactly why the **lockfile** exists: it pins the exact resolved version of every package with an integrity hash, making installs reproducible and detecting republished contents. **Commit it**, and use **`npm ci`** in CI (exact, reproducible) rather than `npm install` (may resolve newer versions and rewrite the lockfile). A **formatter** answers *how should this look* deterministically and ends style debates; a **linter** answers *is this likely a bug* and needs judgement — run both automatically. Finally, the **dev server is not what you ship**: minification, tree-shaking and inlined environment variables all differ, so preview the production build before deploying.',
    keyTakeaways: [
      'dependencies ship; devDependencies build and test — a convention, not enforcement',
      '^ allows minor and patch; ~ allows patch only; neither crosses a major',
      'Semver expresses intent — a patch release can still break you',
      'Commit the lockfile; use npm ci for reproducible installs',
      'A formatter settles appearance; a linter finds likely bugs',
      '"Works in dev" is not evidence — test the production build',
    ],
    relatedLessons: ['l-m45-02', 'l-m28-02'],
    interviewConnections: [
      'What is the difference between dependencies and devDependencies?',
      'What does the caret in ^3.6.0 mean?',
      'Why should a lockfile be committed?',
      'What is the difference between a linter and a formatter?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m45-02',
    slug: 'debugging-docs-and-review',
    moduleId: M,
    order: 2,
    title: 'Debugging, Documentation and Review',
    description: 'A repeatable debugging method, reading API docs properly, and reviewing code usefully.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 18,
    xp: 45,
    topicIds: ['debugging', 'tooling'],
    prerequisites: ['l-m45-01'],
    learningObjectives: [
      'Apply a repeatable process to an unfamiliar bug',
      'Use DevTools beyond console.log',
      'Read reference documentation for an unfamiliar API',
      'Review code and communicate about it usefully',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'A debugging method',
      },
      {
        kind: SECTION.LIST,
        ordered: true,
        items: [
          '**Read the error.** All of it — the type, the message, and the first few stack frames. Module 33 established that the **top frame is where it threw** and each line below is the caller.',
          '**Reproduce it reliably.** A bug you cannot trigger on demand cannot be verified as fixed. Find the exact steps or input.',
          '**Reduce it.** Cut away everything that still leaves the bug present. A ten-line reproduction is usually solvable by inspection.',
          '**Check your assumptions with data.** Not "this should be an array" — log it, or set a breakpoint and look. Most bugs live in an assumption that was never checked.',
          '**Change one thing.** Then re-test. Changing several at once means you learn nothing from the result.',
          '**Confirm the fix addresses the cause.** If you cannot explain *why* it works, it may be a coincidence — and it will return.',
          '**Add a test that would have caught it** (Module 42). That is what stops the same bug arriving twice.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Reduction in practice.',
        code: [
          '"use strict";',
          '',
          '// REPORTED: "the totals page shows NaN sometimes"',
          '// Full pipeline — too large to reason about directly',
          'function buildReport(orders, rates) {',
          '  return orders.map((order) => ({',
          '    id: order.id,',
          '    total: convert(order.amount, order.currency, rates),',
          '  }));',
          '}',
          '',
          'function convert(amount, currency, rates) {',
          '  return amount * rates[currency];',
          '}',
          '',
          'const rates = { USD: 1, EUR: 1.1 };',
          '',
          'const orders = [',
          '  { id: 1, amount: 100, currency: "USD" },',
          '  { id: 2, amount: 50, currency: "GBP" },   // <- not in rates',
          '];',
          '',
          'console.log("full pipeline:", buildReport(orders, rates));',
          '',
          '// REDUCED: one call, one assumption checked',
          'console.log("known rate   :", convert(100, "USD", rates));',
          'console.log("unknown rate :", convert(50, "GBP", rates));',
          'console.log("the lookup   :", rates.GBP);',
          '',
          '// Cause found: a missing key gives undefined, and 50 * undefined is NaN.',
          '// Now decide the CORRECT behaviour rather than patching the symptom.',
          'function convertSafely(amount, currency, rates) {',
          '  const rate = rates[currency];',
          '',
          '  if (rate === undefined) {',
          '    throw new RangeError(`no exchange rate for ${currency}`);',
          '  }',
          '',
          '  return amount * rate;',
          '}',
          '',
          'try {',
          '  convertSafely(50, "GBP", rates);',
          '} catch (error) {',
          '  console.log("now explicit :", error.message);',
          '}',
        ].join('\n'),
        output: [
          'full pipeline: [{id: 1, total: 100}, {id: 2, total: NaN}]',
          'known rate   : 100',
          'unknown rate : NaN',
          'the lookup   : undefined',
          'now explicit : no exchange rate for GBP',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Fix the cause, not the symptom',
        body: [
          'The tempting patch is `total: isNaN(total) ? 0 : total`. That removes the visible `NaN` and **silently reports a wrong total** — arguably worse than the bug, because now nobody notices.',
          'Throwing a clear `RangeError` says exactly what is wrong and where, which is Module 22\'s principle: fail loudly at the point of the problem rather than propagating a bad value.',
          'Note `NaN` is a particularly good example of why: it **propagates silently** through arithmetic, so the symptom appears far from the cause. Tracing it back to a missing lookup key is the whole job.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'DevTools beyond console.log',
      },
      {
        kind: SECTION.LIST,
        items: [
          '**Breakpoints** pause execution so you can inspect **every** variable in scope, not only the ones you thought to log. A **conditional** breakpoint (`i === 42`) is invaluable inside a loop.',
          '**Step over / into / out** walk the code one call at a time, with the call stack visible — the model from Module 33, made concrete.',
          '**The Network panel** shows the real request and response: headers, status, timing, and the actual body. Most "the API is broken" reports are answered here.',
          '**The Elements panel** shows the **live** DOM, which differs from the served HTML once JavaScript has run — and lets you inspect computed styles and event listeners.',
          '**The Performance panel** records where time actually goes, and flags forced synchronous layout (Module 43).',
          '**`console.table`, `console.group` and `console.dir`** are often clearer than `console.log` for arrays of objects, related sequences and DOM nodes.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        caption: 'Console methods worth knowing — illustrative, since output depends on the console.',
        code: [
          '"use strict";',
          '',
          'const orders = [',
          '  { id: 1, customer: "ada", total: 120 },',
          '  { id: 2, customer: "bo", total: 90 },',
          '];',
          '',
          '// A table is far more readable than a logged array of objects',
          'console.table(orders);',
          '',
          '// Grouping keeps related output together',
          'console.group("validation");',
          'console.log("checked 2 orders");',
          'console.warn("1 missing currency");',
          'console.groupEnd();',
          '',
          '// An assertion logs only when the condition fails',
          'console.assert(orders.length > 0, "no orders to process");',
          'console.assert(orders.length > 5, "expected more than 5 orders");',
          '',
          '// Counting occurrences without maintaining a variable',
          'for (const order of orders) console.count("order processed");',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: '`console.log` is fine — it is just not the only tool',
        body: [
          'Logging is genuinely effective and there is no need to feel bad about it. What it cannot do is show you the variables you did not think to log, which is exactly where a stubborn bug usually hides — that is when a breakpoint pays for itself.',
          '`debugger;` in your code pauses execution when DevTools is open, which is a quick way to reach a breakpoint in code that is hard to locate in the sources panel. Remember to remove it — most linters will flag it for you.',
          '**Why that block is not runnable here.** The value of `console.table` and `console.group` is entirely in how a *browser* renders them — a sorted grid, a collapsible section. This curriculum\'s console is a plain log stream, so running it would show a flat array and unindented lines, teaching the opposite of the point. Try it in your own browser console, where `table` produces a real table you can sort by column.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Reading documentation',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The questions to answer about an unfamiliar API.',
        code: [
          '"use strict";',
          '',
          '// Meeting Array.prototype.flat for the first time.',
          '// The documentation answers five questions:',
          '',
          '// 1. SIGNATURE — what does it take?',
          'console.log("default depth :", [1, [2, [3, [4]]]].flat());',
          '',
          '// 2. PARAMETERS — what do they mean, and what are the defaults?',
          'console.log("depth 2       :", [1, [2, [3, [4]]]].flat(2));',
          'console.log("depth Infinity:", [1, [2, [3, [4]]]].flat(Infinity));',
          '',
          '// 3. RETURN VALUE — what comes back, and is the input changed?',
          'const original = [1, [2]];',
          'const flattened = original.flat();',
          'console.log("returns new   :", flattened !== original);',
          'console.log("input intact  :", original);',
          '',
          '// 4. EDGE CASES — empty input, holes, non-arrays',
          'console.log("empty         :", [].flat());',
          'console.log("already flat  :", [1, 2].flat());',
          'console.log("removes holes :", [1, , 3].flat());',
          '',
          '// 5. EXCEPTIONS — what makes it throw?',
          'try {',
          '  [1, 2].flat(-1);',
          '  console.log("negative depth: no error");',
          '} catch (error) {',
          '  console.log("negative depth:", error.name);',
          '}',
        ].join('\n'),
        output: [
          'default depth : [1, 2, [3, [4]]]',
          'depth 2       : [1, 2, 3, [4]]',
          'depth Infinity: [1, 2, 3, 4]',
          'returns new   : true',
          'input intact  : [1, [2]]',
          'empty         : []',
          'already flat  : [1, 2]',
          'removes holes : [1, 3]',
          'negative depth: no error',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Five questions, and a habit',
        body: [
          'For any unfamiliar API, read for: the **signature**, what each **parameter** means and defaults to, the **return value** (especially whether the input is mutated), the **edge cases**, and what **exceptions** it can raise.',
          'Two answers above are worth noticing. `flat()` defaults to depth **1**, not infinite — a common surprise. And it **removes holes** in sparse arrays, which is documented behaviour that would be very hard to guess.',
          'Prefer **MDN** for web platform and JavaScript APIs; it is accurate, includes browser compatibility tables, and is kept current. Then **verify in the console** — a thirty-second experiment beats an assumption, and it is how you would have discovered the default depth above.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Code review',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'What to look for, applied to a small change.',
        code: [
          '"use strict";',
          '',
          '// The change under review',
          'function applyCoupon(order, coupon) {',
          '  const discount = order.total * (coupon.percent / 100);',
          '  return { ...order, total: order.total - discount };',
          '}',
          '',
          '// Review by asking questions the tests should answer',
          'const findings = [];',
          '',
          '// CORRECTNESS: what about an absent coupon?',
          'try {',
          '  applyCoupon({ total: 100 }, undefined);',
          '} catch (error) {',
          '  findings.push(`throws on a missing coupon: ${error.name}`);',
          '}',
          '',
          '// EDGE CASES: is the percentage bounded?',
          'const over = applyCoupon({ total: 100 }, { percent: 150 });',
          'findings.push(`percent 150 gives total ${over.total}`);',
          '',
          '// EDGE CASES: negative percent increases the total',
          'const negative = applyCoupon({ total: 100 }, { percent: -50 });',
          'findings.push(`percent -50 gives total ${negative.total}`);',
          '',
          '// GOOD: it does not mutate the caller\'s order',
          'const order = { total: 100 };',
          'applyCoupon(order, { percent: 10 });',
          'findings.push(`input unchanged: ${order.total === 100}`);',
          '',
          'findings.forEach((line) => console.log(line));',
        ].join('\n'),
        output: [
          'throws on a missing coupon: TypeError',
          'percent 150 gives total -50',
          'percent -50 gives total 150',
          'input unchanged: true',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'A negative total is a real finding, not a nitpick',
        body: [
          'The review found three things worth raising: an unhandled missing coupon, a percentage over 100 producing a **negative total**, and a negative percentage **increasing** the price. Any of those could reach production as a genuine incident.',
          'It also found something to say positively — the function does not mutate its argument. Naming what is right is not politeness; it tells the author which decisions to keep.',
          'Note how the review was conducted: by **running the code with awkward inputs**, not by reading it and imagining. That is the fastest way to find edge cases, and each finding converts directly into a test.',
        ],
      },
      {
        kind: SECTION.TABLE,
        headers: ['Look for', 'Ask'],
        rows: [
          ['**Correctness**', 'Does it do what the description claims? What about empty, missing or extreme input?'],
          ['**Clarity**', 'Could I maintain this in six months? Do the names say what things mean (Module 40)?'],
          ['**Tests**', 'Is the new behaviour tested? Would a test have caught the bug this fixes?'],
          ['**Security**', 'Is user input rendered as text? Is authorisation enforced server-side (Module 44)?'],
          ['**Scope**', 'Does the change do what it says, and only that?'],
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Communicating about code',
        body: [
          '**Review the code, not the author.** "This mutates the caller\'s array" is a fact; "you always forget this" is an attack, and it makes the next review worse.',
          '**Separate blocking from optional.** Say which comments must be addressed and which are preferences — a reviewer who does not distinguish them wastes everyone\'s time.',
          '**Ask when you are unsure.** "What happens if `items` is empty?" is better than asserting a bug that may not exist, and it is how you learn the context you were missing.',
          '**Express uncertainty honestly, and say how you would check.** "I believe this is a race because the two writes are not ordered — I would confirm by logging the sequence." That is stronger than either bluffing or staying silent, and it is exactly how to answer a question you are unsure of in an interview.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// A colleague reports: "the app crashes sometimes".',
          '// You cannot reproduce it.',
          '',
          '// What is the most useful next step?',
        ].join('\n'),
        options: [
          'Establish reliable reproduction steps — exact input, browser, sequence — since an unreproducible bug cannot be verified as fixed',
          'Add try/catch around the suspect area so it stops crashing',
          'Rewrite the module more defensively',
          'Ask the user to clear their cache',
        ],
        correct: 0,
        explanation:
          'Everything else depends on this. Without reproduction you cannot reduce the problem, cannot check assumptions against real data, and — critically — **cannot confirm a fix**, so you would be guessing and then hoping. Wrapping the area in `try`/`catch` is worse than doing nothing: it converts a visible crash into silent wrong behaviour (Module 22), so the bug survives and stops reporting itself. Rewriting defensively without knowing the cause is a large change with no evidence behind it. Get the exact input, browser, sequence and any error text first; if it is intermittent, that itself is a clue pointing at timing, ordering or state left over from a previous action.',
      },
    ],
    exercises: [
      {
        id: 'ex-m45-02-a',
        title: 'Diagnose the NaN',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['debugging'],
        instructions:
          'Write `convert(amount, currency, rates)` that multiplies by the rate, but throws a `RangeError` naming the currency when no rate exists — rather than returning `NaN`.',
        starterCode: [
          '// Buggy version: return amount * rates[currency];',
          '',
          'function convert(amount, currency, rates) {',
          '  // Fail loudly at the cause, not silently at the symptom.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'converts a known currency', body: 'expect(convert(100, "USD", { USD: 1 })).toBe(100);' },
          { name: 'applies the rate', body: 'expect(convert(100, "EUR", { EUR: 1.1 })).toBe(110.00000000000001);' },
          { name: 'throws for an unknown currency', body: 'expect(() => convert(50, "GBP", { USD: 1 })).toThrow();' },
          { name: 'throws a RangeError', body: 'let e = null; try { convert(50, "GBP", { USD: 1 }); } catch (err) { e = err; } expect(e instanceof RangeError).toBe(true);' },
          { name: 'names the currency in the message', body: 'let m = ""; try { convert(50, "GBP", { USD: 1 }); } catch (err) { m = err.message; } expect(m.includes("GBP")).toBe(true);' },
          { name: 'never returns NaN', body: 'let result = null; try { result = convert(50, "GBP", {}); } catch { result = "threw"; } expect(result).toBe("threw");' },
          { name: 'handles a rate of zero', body: 'expect(convert(100, "ZERO", { ZERO: 0 })).toBe(0);', hidden: true },
        ],
        hints: [
          'Read the rate into a variable first.',
          'Check `rate === undefined` rather than falsiness.',
          'Include the currency in the thrown message.',
        ],
        solution: [
          'function convert(amount, currency, rates) {',
          '  const rate = rates[currency];',
          '',
          '  if (rate === undefined) {',
          '    throw new RangeError(`no exchange rate for ${currency}`);',
          '  }',
          '',
          '  return amount * rate;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Checking `rate === undefined` rather than `!rate` is what makes the hidden test pass: a legitimate rate of `0` is falsy, and a truthiness check would reject it as missing. Throwing at the point the rate is looked up means the error names the actual cause, where `NaN` would propagate silently through arithmetic and surface somewhere unrelated. Naming the currency in the message is what turns "something is NaN" into an immediately actionable report — that is the difference between a symptom and a diagnosis.',
      },
      {
        id: 'ex-m45-02-b',
        title: 'Read the documentation',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['debugging'],
        instructions:
          'What does `[1, [2, [3, [4]]]].flat()` return?',
        options: [
          '[1, 2, 3, 4]',
          '[1, 2, [3, [4]]] — flat defaults to a depth of 1',
          '[1, [2, [3, [4]]]]',
          'It throws',
        ],
        correct: 1,
        hints: [
          'What is the default value of the depth parameter?',
        ],
        solution: '[1, 2, [3, [4]]] — flat defaults to a depth of 1',
        solutionExplanation:
          '`flat()` flattens **one** level by default, not all of them — a genuinely common surprise, and exactly the kind of thing reading the parameter defaults answers in seconds. Use `flat(Infinity)` for a full flatten, or `flat(2)` for two levels. Two more documented behaviours worth knowing: it returns a **new** array rather than mutating, and it **removes holes** from sparse arrays. All five questions — signature, parameters, return value, edge cases, exceptions — are answered on the MDN page, and verifying in the console takes half a minute.',
      },
      {
        id: 'ex-m45-02-c',
        title: 'Review the change',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['debugging', 'clean-code'],
        instructions:
          'Write `applyCoupon(order, coupon)` addressing the review findings: a missing coupon leaves the order unchanged, the percentage is clamped to 0–100, and the caller\'s order is never mutated.',
        starterCode: [
          '// Original: order.total - order.total * (coupon.percent / 100)',
          '// Review found: crashes on a missing coupon; allows > 100 and negatives.',
          '',
          'function applyCoupon(order, coupon) {',
          '}',
        ].join('\n'),
        tests: [
          { name: 'applies a normal discount', body: 'expect(applyCoupon({ total: 100 }, { percent: 10 }).total).toBe(90);' },
          { name: 'handles a missing coupon', body: 'expect(applyCoupon({ total: 100 }, undefined).total).toBe(100);' },
          { name: 'handles a null coupon', body: 'expect(applyCoupon({ total: 100 }, null).total).toBe(100);' },
          { name: 'clamps above 100', body: 'expect(applyCoupon({ total: 100 }, { percent: 150 }).total).toBe(0);' },
          { name: 'clamps below 0', body: 'expect(applyCoupon({ total: 100 }, { percent: -50 }).total).toBe(100);' },
          { name: 'does not mutate the order', body: 'const o = { total: 100 }; applyCoupon(o, { percent: 10 }); expect(o.total).toBe(100);' },
          { name: 'preserves other fields', body: 'expect(applyCoupon({ total: 100, id: 7 }, { percent: 10 }).id).toBe(7);' },
          { name: 'handles a percent of 0', body: 'expect(applyCoupon({ total: 100 }, { percent: 0 }).total).toBe(100);', hidden: true },
        ],
        hints: [
          'Return a copy of the order when there is no coupon.',
          '`Math.min(100, Math.max(0, percent))` clamps the range.',
          'Spread the order so other fields survive.',
        ],
        solution: [
          'function applyCoupon(order, coupon) {',
          '  if (!coupon) return { ...order };',
          '',
          '  const percent = Math.min(100, Math.max(0, coupon.percent));',
          '  const discount = order.total * (percent / 100);',
          '',
          '  return { ...order, total: order.total - discount };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Each change answers one review finding. The `!coupon` guard covers both `undefined` and `null` and returns a **copy**, so the return type is consistent whether or not a coupon applied. Clamping turns two real incidents — a negative total from `percent: 150`, and a price **increase** from a negative percent — into sensible bounds. Spreading preserves sibling fields and leaves the caller\'s order untouched, which the sixth test checks. Note a `percent` of `0` works without a special case, which the hidden test confirms — a truthiness guard on `coupon.percent` would have broken it.',
      },
      {
        id: 'ex-m45-02-d',
        title: 'Give useful review feedback',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['debugging'],
        instructions:
          'Which review comment is most useful?',
        options: [
          '"This is wrong."',
          '"This mutates the caller\'s array — `sort` is in place. Was that intended? A copy would avoid surprising callers."',
          '"You always forget to copy arrays."',
          '"Looks good to me."',
          ],
        correct: 1,
        hints: [
          'Which one states a fact and gives the author something to act on?',
        ],
        solution: '"This mutates the caller\'s array — `sort` is in place. Was that intended? A copy would avoid surprising callers."',
        solutionExplanation:
          'It states a **specific fact** about the code, explains **why** it matters, **asks** rather than assuming the author did not know, and suggests a concrete fix — so the author can act on it immediately. "This is wrong" gives nothing to act on. "You always forget" reviews the **author** rather than the code and makes the next review worse. "Looks good to me" on a change with a real defect is the failure mode reviews exist to prevent — and if the code genuinely is good, saying **what** is good is more useful, because it tells the author which decisions to keep.',
      },
    ],
    quiz: {
      id: 'qz-m45-02',
      questions: [
        {
          id: 'q-m45-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['debugging'],
          prompt: 'What is the first step with an unreproducible bug?',
          options: [
            'Add defensive try/catch',
            'Establish reliable reproduction — without it you cannot confirm a fix',
            'Rewrite the module',
            'Ask the user to clear their cache',
          ],
          correct: 1,
          optionExplanations: [
            'That hides the symptom.',
            'Correct — everything else depends on it.',
            'A large change with no evidence.',
            'Rarely the cause.',
          ],
          explanation:
            'Without reproduction you cannot reduce the problem or verify a fix. A `try`/`catch` turns a visible crash into silent wrong behaviour, so the bug survives and stops reporting itself.',
        },
        {
          id: 'q-m45-02-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['debugging'],
          prompt: 'What can a breakpoint do that console.log cannot?',
          options: [
            'Run faster',
            'Show every variable in scope, including ones you did not think to log',
            'Work in production',
            'Modify the source',
          ],
          correct: 1,
          optionExplanations: [
            'Speed is irrelevant.',
            'Correct — which is where stubborn bugs hide.',
            'Both work wherever DevTools is open.',
            'Neither edits source.',
          ],
          explanation:
            'Logging shows what you anticipated. A breakpoint pauses and lets you inspect everything in scope plus the call stack — and a conditional breakpoint targets one iteration of a loop.',
        },
        {
          id: 'q-m45-02-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['debugging'],
          prompt: 'array.flat() flattens all levels of nesting by default.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'The default depth is 1.',
            'Correct — use flat(Infinity) for all levels.',
          ],
          explanation:
            'The `depth` parameter defaults to `1`. Reading parameter defaults is one of the five questions to answer about any unfamiliar API.',
        },
        {
          id: 'q-m45-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['debugging'],
          prompt: 'How should you express uncertainty in a review or interview?',
          options: [
            'Assert confidently and hope',
            'State your reasoning and how you would verify it',
            'Say nothing',
            'Defer entirely to others',
          ],
          correct: 1,
          optionExplanations: [
            'Bluffing is quickly detected.',
            'Correct — it shows method as well as knowledge.',
            'Silence hides a possible real issue.',
            'Your reasoning has value.',
          ],
          explanation:
            '"I believe this is a race because the writes are not ordered — I would confirm by logging the sequence" demonstrates reasoning and a verification plan, which is more valuable than a confident guess.',
        },
      ],
    },
    summary:
      'A repeatable **debugging method**: read the whole error (the top stack frame is where it threw), **reproduce reliably**, **reduce** to the smallest failing case, **check assumptions against data** rather than reasoning about what should be true, change **one thing** at a time, confirm the fix addresses the **cause** — and add a test that would have caught it. Critically, **fix the cause, not the symptom**: patching a `NaN` to `0` silently reports a wrong total, which is worse than the bug because nobody notices; `NaN` propagates silently through arithmetic, so the symptom always appears far from the cause. **DevTools beyond `console.log`**: breakpoints show every variable in scope (conditional ones target a single loop iteration), the Network panel answers most "the API is broken" reports, the Elements panel shows the **live** DOM, and `console.table`, `group`, `assert` and `count` are often clearer than a plain log. For an **unfamiliar API**, read for five things — signature, parameter meanings and **defaults**, return value (and whether the input is mutated), edge cases, and exceptions — then verify in the console; `flat()` defaulting to depth **1** is the classic example. In **review**, look for correctness, clarity, tests, security and scope, and find edge cases by **running the code with awkward inputs**. Review the **code, not the author**, separate blocking from optional, ask when unsure, and **express uncertainty with a verification plan** rather than bluffing.',
    keyTakeaways: [
      'Reproduce before anything else — you cannot verify an unverifiable fix',
      'Fix the cause; patching a symptom converts a crash into silent wrong data',
      'Breakpoints reveal the variables you did not think to log',
      'Read signature, defaults, return value, edge cases and exceptions',
      'Find review findings by running the code with awkward inputs',
      'Review the code not the author, and state uncertainty with a way to check it',
    ],
    relatedLessons: ['l-m45-01', 'l-m22-05'],
    interviewConnections: [
      'Walk me through how you debug an unfamiliar problem.',
      'How do you approach an API you have never used?',
      'What do you look for in a code review?',
      'How do you handle a question you are not sure about?',
    ],
  },
  /* ================================================================== */
  {
    id: 'l-m45-03',
    slug: 'git-workflow-and-project-structure',
    moduleId: M,
    order: 3,
    title: 'Git Workflow and Project Structure',
    description: 'Enough Git for professional JavaScript work, and how to organise a project that grows.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 17,
    xp: 45,
    topicIds: ['tooling'],
    prerequisites: ['l-m45-02'],
    learningObjectives: [
      'Use a branch-and-pull-request workflow',
      'Write commits that are useful to read later',
      'Explain merge and rebase without dogma',
      'Organise a project by principles rather than a fixed template',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'The everyday workflow',
      },
      {
        kind: SECTION.CODE,
        language: 'bash',
        caption: 'The commands that cover most days.',
        code: [
          '# Start from an up-to-date main branch',
          'git switch main',
          'git pull',
            '',
          '# Work on a branch, never directly on main',
          'git switch -c fix/cart-total-rounding',
          '',
          '# See what changed before staging anything',
          'git status',
          'git diff',
          '',
          '# Stage deliberately — -p lets you stage parts of a file',
          'git add src/cart.js',
          'git add -p src/format.js',
          '',
          '# Review what is staged, then commit',
          'git diff --staged',
          'git commit -m "Fix cart total rounding to two decimal places"',
          '',
          '# Push and open a pull request',
          'git push -u origin fix/cart-total-rounding',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Why a branch per change',
        body: [
          'A branch isolates work in progress, so `main` stays deployable and several people can work without blocking each other. It also gives a **pull request** something to review — a coherent set of changes with a description.',
          'Name the branch after the change, not yourself: `fix/cart-total-rounding` tells a colleague what it is; `johns-branch` does not.',
          '`git diff --staged` before committing is a habit worth forming. It catches the debug statement, the commented-out block, and the unrelated file you staged without noticing — all of which are much cheaper to remove now than in review.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'What makes a commit message useful.',
        code: [
          '"use strict";',
          '',
          'function assess(message) {',
          '  const problems = [];',
          '  const [subject] = message.split("\\n");',
          '',
          '  if (subject.length === 0) problems.push("empty subject");',
          '  if (subject.length > 72) problems.push("subject too long to read in a log");',
          '  if (/^(fix|update|changes?|stuff|wip)$/i.test(subject.trim())) {',
          '    problems.push("says nothing about what changed");',
          '  }',
          '  if (/^\\s/.test(subject)) problems.push("leading whitespace");',
          '',
          '  return problems.length === 0 ? ["ok"] : problems;',
          '}',
          '',
          'const messages = [',
          '  "Fix cart total rounding to two decimal places",',
          '  "fix",',
          '  "stuff",',
          '  "Update",',
          '  "Prevent duplicate submissions by disabling the button while the request is in flight",',
          '];',
          '',
          'for (const message of messages) {',
          '  console.log(`${JSON.stringify(message.slice(0, 40))} -> ${assess(message).join(", ")}`);',
          '}',
        ].join('\n'),
        output: [
          '"Fix cart total rounding to two decimal p" -> ok',
          '"fix" -> says nothing about what changed',
          '"stuff" -> says nothing about what changed',
          '"Update" -> says nothing about what changed',
          '"Prevent duplicate submissions by disabli" -> subject too long to read in a log',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Write the subject for someone reading the log in a year',
        body: [
          'A commit message is read most often by someone asking **"why does this line exist?"** — usually via `git blame`, usually long after you have forgotten. "fix" answers nothing.',
          'A workable shape: a **short imperative subject** ("Fix cart total rounding"), then a blank line, then a body explaining **why** if it is not obvious. The what is already in the diff; the why is not.',
          'Note the last message above: it is perfectly **descriptive** and still flagged, at 83 characters. A subject that long is truncated in `git log --oneline` and in most review interfaces, so the detail belongs in the body — descriptive and short are both required, not alternatives.',
          'Keep commits **coherent**. A commit mixing a bug fix, a rename and a new feature cannot be reverted, cherry-picked or understood independently. This is Module 40\'s point about refactoring being a separate change, expressed in history.',
          'Many teams use a convention such as `fix:` / `feat:` prefixes. Follow whatever your team uses — the consistency matters more than the particular scheme.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Merge and rebase',
      },
      {
        kind: SECTION.CODE,
        language: 'text',
        caption: 'The same work, integrated two ways.',
        code: [
          '  MERGE — history shows what actually happened',
          '',
          '    main     A---B---------M',
          '                  \\       /',
          '    branch         C---D',
          '',
          '    M is a merge commit with two parents.',
          '    The branch context is preserved.',
          '',
          '',
          '  REBASE — history is rewritten to look linear',
          '',
          '    main     A---B---C\'---D\'',
          '',
          '    C and D are REPLAYED on top of B as new commits.',
          '    The original C and D no longer exist.',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Never rebase a branch other people have pulled',
        body: [
          'Rebasing **creates new commits** with new identities and discards the originals. If a colleague has already based work on the old commits, their history and yours have diverged in a way that is genuinely painful to reconcile.',
          'The safe rule: rebase **your own unpushed or unshared** branch freely — it is excellent for tidying a messy sequence before review. Do not rebase `main`, or any branch someone else is working from.',
          'Neither approach is universally correct. **Merge** preserves what actually happened, which is honest and can make history noisy. **Rebase** produces a linear history that is easier to read, at the cost of rewriting it. Teams pick one and stay consistent; both are defensible.',
          'A related habit: `git pull --rebase` replays your local commits on top of the fetched ones instead of creating a merge commit for a routine update. Many teams default to it.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'bash',
        caption: 'Recovering from common situations.',
        code: [
          '# Committed to main by mistake, not yet pushed',
          'git switch -c fix/my-change     # take the commits onto a branch',
          'git switch main',
          'git reset --hard origin/main    # reset main to the remote',
          '',
          '# Wrong message on the most recent commit (not yet pushed)',
          'git commit --amend -m "Fix cart total rounding to two decimal places"',
          '',
          '# Staged something by accident',
          'git restore --staged src/unrelated.js',
          '',
          '# Need to switch branches with work in progress',
          'git stash',
          'git switch main',
          'git stash pop',
          '',
          '# Find which commit introduced a line',
          'git blame src/cart.js',
          '',
          '# See what a branch changed relative to main',
          'git diff main...HEAD',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: '`reset --hard` discards work permanently',
        body: [
          'It throws away uncommitted changes with no confirmation and no undo. Before running it, check `git status` and consider `git stash` instead — stashing keeps the work retrievable.',
          'The general safety rule: commands that only **add** history (`commit`, `merge`, `revert`) are safe; commands that **rewrite or discard** it (`reset --hard`, `rebase`, `push --force`) deserve a pause.',
          '`git revert` is the safe counterpart to undoing a **pushed** commit — it adds a new commit that reverses the change, rather than rewriting history others have pulled.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Project structure',
      },
      {
        kind: SECTION.CODE,
        language: 'text',
        caption: 'A realistic vanilla JavaScript application.',
        code: [
          '  src/',
          '    features/',
          '      cart/',
          '        cart.js            business rules — pure, testable',
          '        cart.test.js       tests beside the code they test',
          '        cartView.js        rendering only',
          '        cartApi.js         requests for this feature',
          '      checkout/',
          '        checkout.js',
          '        checkoutView.js',
          '',
          '    shared/',
          '      format.js          used by several features',
          '      request.js         the single place fetch is configured',
          '      dom.js',
          '',
          '    main.js              the entry point: wires things together',
          '',
          '  public/                static assets served as-is',
          '  index.html',
          '  package.json',
          '  vite.config.js',
        ].join('\n'),
      },
      {
        kind: SECTION.LIST,
        items: [
          '**Group by feature, not by type.** Module 28 argued this: things that change together should live together, and a cancelled feature should be one folder to delete.',
          '**`shared/` holds only what genuinely serves several features.** A file used by one feature belongs in that feature.',
          '**Dependencies point one way** — features may use `shared`, `shared` never imports a feature. That keeps utilities reusable and makes cycles nearly impossible.',
          '**One entry point wires things up.** `main.js` constructs dependencies and passes them down, so everything below is testable in isolation.',
          '**Tests live beside the code** they test. A test three directories away is a test nobody updates.',
          '**Separate rules, rendering and requests** within a feature — the three-layer split from Module 40, which is what makes two of the three testable without a DOM.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'There is no universal folder structure',
        body: [
          'The layout above is one reasonable arrangement, not a standard. Frameworks impose their own conventions, teams have preferences, and a five-file project needs none of this.',
          'What transfers between projects is the **principles**: group by what changes together, keep dependency direction one-way, put shared code in one place, and wire dependencies at a single entry point.',
          'Structure should also **follow** the project rather than anticipate it. Starting a small project with twelve empty folders is Module 40\'s YAGNI in directory form — let the folders appear when there is something to put in them.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Checking dependency direction — a rule worth enforcing.',
        code: [
          '"use strict";',
          '',
          '// Layer of a file, derived from its path',
          'function layerOf(path) {',
          '  if (path.startsWith("src/shared/")) return "shared";',
          '  if (path.startsWith("src/features/")) return "feature";',
          '  if (path === "src/main.js") return "entry";',
          '',
          '  return "other";',
          '}',
          '',
          '// Allowed: entry -> anything, feature -> shared, shared -> shared',
          'const ALLOWED = {',
          '  entry: ["entry", "feature", "shared", "other"],',
          '  feature: ["feature", "shared", "other"],',
          '  shared: ["shared", "other"],',
          '  other: ["other"],',
          '};',
          '',
          'function checkImport(from, to) {',
          '  const fromLayer = layerOf(from);',
          '  const toLayer = layerOf(to);',
          '',
          '  return ALLOWED[fromLayer].includes(toLayer)',
          '    ? null',
          '    : `${fromLayer} must not import ${toLayer}: ${from} -> ${to}`;',
          '}',
          '',
          'const imports = [',
          '  ["src/features/cart/cart.js", "src/shared/format.js"],',
          '  ["src/main.js", "src/features/cart/cart.js"],',
          '  ["src/shared/format.js", "src/features/cart/cart.js"],',
          '  ["src/features/cart/cartView.js", "src/features/cart/cart.js"],',
          '];',
          '',
          'for (const [from, to] of imports) {',
          '  const problem = checkImport(from, to);',
          '  console.log(problem ?? `ok: ${from.split("/").pop()} -> ${to.split("/").pop()}`);',
          '}',
        ].join('\n'),
        output: [
          'ok: cart.js -> format.js',
          'ok: main.js -> cart.js',
          'shared must not import feature: src/shared/format.js -> src/features/cart/cart.js',
          'ok: cartView.js -> cart.js',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The one rule worth enforcing automatically',
        body: [
          'The violation above is the one that matters: a **shared utility importing a feature**. It makes the utility unusable elsewhere, untestable without that feature, and creates the upward arrow that lets a cycle form (Module 28).',
          'ESLint plugins can enforce import boundaries like this, so the rule is checked in CI rather than remembered. That is worth setting up on any project large enough to have layers.',
          'Note the third check caught it while the others passed — including a view importing its own feature\'s rules, which is correct: within a feature, importing downward is exactly the intended direction.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// You committed three things in one commit:',
          '//   - a bug fix in cart.js',
          '//   - a variable rename across six files',
          '//   - a new feature in checkout.js',
          '//',
          '// The bug fix turns out to be wrong and must be reverted.',
        ].join('\n'),
        options: [
          'Reverting undoes all three, so the rename and the feature are lost too — which is why commits should be coherent',
          'Git reverts only the cart.js part automatically',
          'You can revert a single file from the commit with git revert',
          'It makes no difference',
        ],
        correct: 0,
        explanation:
          'A commit is the **unit** of revert, cherry-pick and blame, so anything bundled together moves together — reverting takes the rename and the feature with it, and you must then manually reapply them. The same problem appears in `git blame`: every one of those six renamed files now points at a commit whose message is about a cart bug, telling a future reader nothing. Splitting the work into three commits keeps each independently revertible and reviewable, and makes the history readable — which is the same reason Module 40 insists a refactor and a behaviour change belong in separate commits. Note the third option is misleading: you can manually restore one file\'s prior state, but `git revert` operates on whole commits.',
      },
    ],
    exercises: [
      {
        id: 'ex-m45-03-a',
        title: 'Assess a commit message',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['tooling'],
        instructions:
          'Write `assessCommit(message)` returning an array of problems, or `["ok"]`. Flag an empty subject, a subject over 72 characters, and a subject that is only a generic word (`fix`, `update`, `changes`, `change`, `stuff`, `wip`), case-insensitively.',
        starterCode: [
          'function assessCommit(message) {',
          '  // The subject is everything before the first newline.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'accepts a descriptive subject', body: 'expect(assessCommit("Fix cart total rounding")).toEqual(["ok"]);' },
          { name: 'flags an empty message', body: 'expect(assessCommit("")).toEqual(["empty subject"]);' },
          { name: 'flags a generic word', body: 'expect(assessCommit("fix")).toEqual(["says nothing about what changed"]);' },
          { name: 'is case-insensitive', body: 'expect(assessCommit("WIP")).toEqual(["says nothing about what changed"]);' },
          { name: 'flags an over-long subject', body: 'expect(assessCommit("x".repeat(80))).toEqual(["subject too long"]);' },
          { name: 'only checks the subject line', body: 'expect(assessCommit("Fix rounding\\n\\n" + "x".repeat(200))).toEqual(["ok"]);' },
          { name: 'accepts a subject containing a generic word', body: 'expect(assessCommit("Fix rounding in the cart")).toEqual(["ok"]);' },
          { name: 'accepts exactly 72 characters', body: 'expect(assessCommit("x".repeat(72))).toEqual(["ok"]);', hidden: true },
        ],
        hints: [
          'Split on `"\\n"` and take the first element.',
          'Anchor the generic-word check with `^...$` so it matches the whole subject.',
          'Collect problems in an array; return `["ok"]` if it is empty.',
        ],
        solution: [
          'const GENERIC = /^(fix|update|changes?|stuff|wip)$/i;',
          '',
          'function assessCommit(message) {',
          '  const subject = message.split("\\n")[0].trim();',
          '  const problems = [];',
          '',
          '  if (subject.length === 0) problems.push("empty subject");',
          '  if (subject.length > 72) problems.push("subject too long");',
          '  if (GENERIC.test(subject)) problems.push("says nothing about what changed");',
          '',
          '  return problems.length === 0 ? ["ok"] : problems;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Anchoring the generic pattern with `^` and `$` is what makes the seventh test pass — "Fix rounding in the cart" **contains** a generic word but is not one, and an unanchored pattern would wrongly reject every message starting with "Fix". Taking only the first line means a long explanatory body is fine (sixth test), which is exactly the shape recommended: short imperative subject, blank line, then the **why**. The `> 72` boundary means exactly 72 passes, which the hidden test pins down.',
      },
      {
        id: 'ex-m45-03-b',
        title: 'Enforce dependency direction',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['tooling', 'clean-code'],
        instructions:
          'Write `checkImports(imports)` returning an array of violation messages. A file under `src/shared/` must never import from `src/features/`. Every other direction is allowed. Each message is `"<from> -> <to>"`.',
        starterCode: [
          'function checkImports(imports) {',
          '  // Each entry is [fromPath, toPath].',
          '}',
        ].join('\n'),
        tests: [
          { name: 'allows feature to shared', body: 'expect(checkImports([["src/features/cart/cart.js", "src/shared/format.js"]])).toEqual([]);' },
          { name: 'flags shared to feature', body: 'expect(checkImports([["src/shared/format.js", "src/features/cart/cart.js"]])).toEqual(["src/shared/format.js -> src/features/cart/cart.js"]);' },
          { name: 'allows feature to feature', body: 'expect(checkImports([["src/features/cart/cartView.js", "src/features/cart/cart.js"]])).toEqual([]);' },
          { name: 'allows the entry point to import anything', body: 'expect(checkImports([["src/main.js", "src/features/cart/cart.js"]])).toEqual([]);' },
          { name: 'allows shared to shared', body: 'expect(checkImports([["src/shared/a.js", "src/shared/b.js"]])).toEqual([]);' },
          { name: 'reports several violations', body: 'expect(checkImports([["src/shared/a.js", "src/features/x/y.js"], ["src/shared/b.js", "src/features/p/q.js"]]).length).toBe(2);' },
          { name: 'handles an empty list', body: 'expect(checkImports([])).toEqual([]);' },
          { name: 'does not flag a path merely containing the words', body: 'expect(checkImports([["src/app/shared-utils.js", "src/features/x/y.js"]])).toEqual([]);', hidden: true },
        ],
        hints: [
          '`startsWith("src/shared/")` identifies the shared layer.',
          '`startsWith("src/features/")` identifies a feature.',
          'A violation is shared-importing-feature; everything else passes.',
        ],
        solution: [
          'function checkImports(imports) {',
          '  const violations = [];',
          '',
          '  for (const [from, to] of imports) {',
          '    const fromShared = from.startsWith("src/shared/");',
          '    const toFeature = to.startsWith("src/features/");',
          '',
          '    if (fromShared && toFeature) {',
          '      violations.push(`${from} -> ${to}`);',
          '    }',
          '  }',
          '',
          '  return violations;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Using `startsWith` on the full path prefix rather than `includes` is what makes the hidden test pass: `src/app/shared-utils.js` contains the word "shared" but is not in the shared **layer**, and an `includes` check would wrongly flag it. The single rule enforced is the one that matters — a shared utility importing a feature becomes unusable elsewhere, untestable without that feature, and creates the upward arrow that permits a dependency cycle (Module 28). An ESLint import-boundary plugin enforces exactly this in CI.',
      },
      {
        id: 'ex-m45-03-c',
        title: 'Merge or rebase?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['tooling'],
        instructions:
          'A colleague has already pulled your feature branch. You want to tidy its commit history. What should you do?',
        options: [
          'Rebase and force-push — it produces a cleaner history',
          'Do not rebase: it rewrites commits your colleague has already based work on. Tidy history only on branches nobody else has pulled',
          'Delete the branch and start again',
          'Rebase, but do not force-push',
        ],
        correct: 1,
        hints: [
          'What happens to commits someone else already has?',
        ],
        solution: 'Do not rebase: it rewrites commits your colleague has already based work on. Tidy history only on branches nobody else has pulled',
        solutionExplanation:
          'Rebasing **creates new commits** with new identities and discards the originals, so a colleague whose work sits on the old commits now has a diverged history that is genuinely painful to reconcile. The safe rule is to rebase freely on **your own unshared** branch — it is excellent for tidying before review — and never on a shared branch or `main`. The last option is not a real alternative: without a force-push the rewritten history cannot reach the remote, so the rebase achieves nothing there. Neither merge nor rebase is universally correct; teams pick one and stay consistent.',
      },
      {
        id: 'ex-m45-03-d',
        title: 'Why coherent commits matter',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['tooling'],
        instructions:
          'Why should a bug fix, a rename and a new feature be three commits rather than one?',
        options: [
          'It looks more professional',
          'A commit is the unit of revert, cherry-pick and blame — bundling means they cannot be undone or understood independently',
          'Git performs better with smaller commits',
          'It is required by most tools',
        ],
        correct: 1,
        hints: [
          'What happens when you need to revert just one of the three?',
        ],
        solution: 'A commit is the unit of revert, cherry-pick and blame — bundling means they cannot be undone or understood independently',
        solutionExplanation:
          'Reverting a bundled commit takes the rename and the feature with it, so you must manually reapply them. `git blame` suffers too: every renamed file now points at a commit whose message describes a cart bug, which tells a future reader nothing about why that line looks the way it does. Cherry-picking one change onto a release branch becomes impossible. This is the same principle as Module 40\'s rule that a refactor and a behaviour change belong in separate commits — each should be independently understandable, revertible and reviewable.',
      },
    ],
    quiz: {
      id: 'qz-m45-03',
      questions: [
        {
          id: 'q-m45-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['tooling'],
          prompt: 'What should a commit subject line communicate?',
          options: [
            'Which files changed',
            'What the change does, briefly — with the why in the body if it is not obvious',
            'Who made the change',
            'The ticket number only',
          ],
          correct: 1,
          optionExplanations: [
            'The diff already shows that.',
            'Correct — written for someone reading blame in a year.',
            'Git records the author.',
            'Useful, but not a description.',
          ],
          explanation:
            'The what is in the diff; the why is not. A short imperative subject plus an explanatory body answers the question `git blame` is usually asked.',
        },
        {
          id: 'q-m45-03-2',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['tooling'],
          prompt: 'Rebasing a branch that colleagues have already pulled is safe.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It rewrites commits they already have.',
            'Correct — rebase only unshared branches.',
          ],
          explanation:
            'Rebase creates new commits and discards the originals, so anyone with the old history diverges. Rebase your own unshared branch freely; never a shared one.',
        },
        {
          id: 'q-m45-03-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['tooling'],
          prompt: 'Which Git commands deserve extra caution?',
          options: [
            'commit and merge',
            'reset --hard, rebase and push --force — they rewrite or discard history',
            'status and diff',
            'switch and pull',
          ],
          correct: 1,
          optionExplanations: [
            'These only add history.',
            'Correct — destructive or history-rewriting.',
            'Read-only.',
            'Ordinary navigation.',
          ],
          explanation:
            'Commands that only add history are recoverable. `reset --hard` discards uncommitted work with no undo — prefer `git stash`, and use `git revert` to undo something already pushed.',
        },
        {
          id: 'q-m45-03-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['tooling', 'clean-code'],
          prompt: 'Which project-structure rule transfers between projects?',
          options: [
            'Always use a components folder',
            'Dependencies point one way — features may import shared code, shared code never imports a feature',
            'Always separate by file type',
            'Every project needs the same folders',
          ],
          correct: 1,
          optionExplanations: [
            'Framework-specific.',
            'Correct — it keeps utilities reusable and prevents cycles.',
            'That scatters each feature.',
            'Structure should follow the project.',
          ],
          explanation:
            'A shared utility importing a feature becomes unusable elsewhere and creates the upward arrow that allows a cycle. Layouts vary; the direction rule does not.',
        },
      ],
    },
    summary:
      'The everyday Git workflow is: update `main`, **branch** per change (named after the change, not yourself), review with `git diff` and `git diff --staged` before committing, push, and open a **pull request**. A commit message is read most often by someone asking *why does this line exist* — so write a **short imperative subject**, a blank line, then the **why**, since the what is already in the diff. Keep commits **coherent**: a commit is the unit of **revert, cherry-pick and blame**, so bundling a fix, a rename and a feature means none can be undone or understood independently, and `git blame` on the renamed files points at an unrelated message. **Merge** preserves what actually happened; **rebase** rewrites history to look linear. Neither is universally right, but the safety rule is absolute: **never rebase a branch others have pulled**, because rebase creates new commits and discards the originals. In general, commands that only **add** history are safe, while those that **rewrite or discard** it — `reset --hard`, `rebase`, `push --force` — deserve a pause; prefer `git stash` over discarding, and `git revert` for undoing something already pushed. For **project structure**, group by **feature** rather than type, keep `shared/` for what genuinely serves several features, wire dependencies at **one entry point**, and put tests beside the code. There is no universal folder layout — what transfers is the **principles**, especially that **dependencies point one way**: a shared utility importing a feature becomes unusable elsewhere and opens the door to a cycle.',
    keyTakeaways: [
      'Branch per change, named after the change; review the diff before committing',
      'Write the subject for someone reading blame in a year — and explain why',
      'A commit is the unit of revert and blame, so keep each one coherent',
      'Never rebase a branch someone else has pulled',
      'Commands that rewrite or discard history deserve a pause',
      'Group by feature, and never let shared code import a feature',
    ],
    relatedLessons: ['l-m45-02', 'l-m28-05'],
    interviewConnections: [
      'Describe your Git workflow for a typical change.',
      'What is the difference between merge and rebase, and when is rebase unsafe?',
      'Why should commits be small and coherent?',
      'How would you structure a growing JavaScript project?',
    ],
  },
];
