import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm44';

export default [
  /* ================================================================== */
  {
    id: 'l-m44-01',
    slug: 'trust-boundaries-and-xss',
    moduleId: M,
    order: 1,
    title: 'Trust Boundaries and XSS',
    description: 'What the client can never enforce, and how untrusted data becomes executable code.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 18,
    xp: 50,
    topicIds: ['security'],
    prerequisites: ['l-m43-02'],
    learningObjectives: [
      'Identify trust boundaries and what the client can enforce',
      'Explain how untrusted data becomes executable HTML',
      'Choose safe DOM APIs for rendering user content',
      'Explain why homemade sanitisation fails',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'The client is not a trust boundary',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Everything you ship to a browser is under the user\'s control',
        body: [
          'Your JavaScript, your HTML, your configuration and every request your code makes are all visible and modifiable. A user can open devtools, edit variables, replay requests with different values, or skip your code entirely and call your API directly with `curl`.',
          'So **client-side checks are a user-experience feature, not a security control**. Validating an email format in the browser saves a round trip and gives immediate feedback — it does not prevent anyone from submitting whatever they like.',
          'The security rule that follows: **every rule that matters must be enforced on the server**. The client may duplicate a check for convenience; the server must own it.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Client validation is convenience; the server decides.',
        code: [
          '"use strict";',
          '',
          '// CLIENT: fast feedback, trivially bypassed',
          'function validateOrder(order) {',
          '  const problems = [];',
          '',
          '  if (order.quantity < 1) problems.push("quantity must be at least 1");',
          '  if (order.quantity > 10) problems.push("maximum 10 per order");',
          '',
          '  return problems;',
          '}',
          '',
          'console.log("valid   :", validateOrder({ quantity: 3 }));',
          'console.log("invalid :", validateOrder({ quantity: 99 }));',
          '',
          '// An attacker simply does not run that function.',
          '// They send the request directly:',
          '//   curl -X POST /api/orders -d \'{"quantity": 99999, "price": 0}\'',
          '',
          '// SERVER: the same rules, plus the ones the client must never own',
          'function serverValidateOrder(order, session, catalogue) {',
          '  const problems = [];',
          '',
          '  if (!Number.isInteger(order.quantity) || order.quantity < 1) problems.push("bad quantity");',
          '  if (order.quantity > 10) problems.push("over limit");',
          '',
          '  // The client sent a price. Ignore it — look it up.',
          '  const product = catalogue[order.productId];',
          '  if (!product) problems.push("unknown product");',
          '',
          '  // Authorisation belongs here, never in the UI',
          '  if (!session.userId) problems.push("not signed in");',
          '',
          '  return { problems, total: product ? product.price * order.quantity : 0 };',
          '}',
          '',
          'const catalogue = { abc: { price: 25 } };',
          '',
          'console.log("server ok  :", serverValidateOrder(',
          '  { productId: "abc", quantity: 2, price: 0 },',
          '  { userId: 7 }, catalogue,',
          '));',
          '',
          'console.log("server bad :", serverValidateOrder(',
          '  { productId: "abc", quantity: 99999, price: 0 },',
          '  { userId: 7 }, catalogue,',
          ').problems);',
        ].join('\n'),
        output: [
          'valid   : []',
          'invalid : ["maximum 10 per order"]',
          'server ok  : {problems: [], total: 50}',
          'server bad : ["over limit"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'Never trust a price the client sent',
        body: [
          'The server example deliberately **ignores** `order.price` and looks the price up from its own catalogue. Accepting a client-supplied price is a classic, genuinely exploited vulnerability — a user edits it to `0` and checks out.',
          'The general form: any value the client sends is **input**, including values your own code put there. Identifiers, quantities, roles, discount codes and prices must all be validated or re-derived server-side.',
          'This is Module 26\'s point about `fetch` bodies, restated as a security rule.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Cross-site scripting',
      },
      {
        kind: SECTION.PROSE,
        body: [
          '**XSS** is what happens when untrusted data is inserted into a page in a way that makes the browser treat it as **code** rather than as **content**.',
          'The consequence is that an attacker\'s JavaScript runs **in another user\'s browser, on your origin** — so it can read anything that user\'s session can reach: their data, their `localStorage` (Module 27), and their ability to act as themselves.',
          'This lesson covers **prevention**. It does not provide attack payloads, because the defence does not require them: the rule is about how data enters the page, not about what a particular attack string looks like.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        needsDom: true,
        html: '<div id="app"><div id="unsafe"></div><div id="safe"></div></div>',
        caption: 'The same input, treated as code and as text.',
        code: [
          '// A comment from an untrusted user, containing markup',
          'const userComment = \'Nice article <img src="x" onerror="ATTACK()"> thanks\';',
          '',
          'const unsafe = document.getElementById("unsafe");',
          'const safe = document.getElementById("safe");',
          '',
          '// UNSAFE: the string is PARSED AS HTML, creating a real element',
          'unsafe.innerHTML = userComment;',
          '',
          '// SAFE: the string is inserted as TEXT, creating no elements',
          'safe.textContent = userComment;',
          '',
          'console.log("unsafe elements:", unsafe.querySelectorAll("*").length);',
          'console.log("safe elements  :", safe.querySelectorAll("*").length);',
          '',
          '// The unsafe version built an element carrying an event handler',
          'const injected = unsafe.querySelector("img");',
          'console.log("injected tag   :", injected ? injected.tagName : "none");',
          'console.log("has handler    :", injected ? injected.hasAttribute("onerror") : false);',
          '',
          '// The safe version shows the markup to the user as literal text',
          'console.log("safe text      :", safe.textContent);',
          'console.log("safe html      :", safe.innerHTML.includes("&lt;img"));',
        ].join('\n'),
        output: [
          'unsafe elements: 1',
          'safe elements  : 0',
          'injected tag   : IMG',
          'has handler    : true',
          'safe text      : Nice article <img src="x" onerror="ATTACK()"> thanks',
          'safe html      : true',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: '`innerHTML` parses; `textContent` does not',
        body: [
          'That is the entire mechanism. Assigning to `innerHTML` runs the **HTML parser** over the string, so anything that looks like markup becomes markup — including elements carrying event handlers.',
          '`textContent` inserts the string as a text node. The angle brackets are escaped on the way out (`&lt;img`), so the user sees the characters they typed and no element is created.',
          'Note the injected element above carries an `onerror` attribute. Handlers on **freshly parsed** elements are exactly how markup injection becomes script execution, which is why "it is only an image tag" is not reassuring.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        needsDom: true,
        html: '<div id="app"><ul id="list"></ul></div>',
        caption: 'Building content safely with the DOM API.',
        code: [
          'const comments = [',
          '  { author: "Ada", body: "Great post" },',
          '  { author: "<b>Bo</b>", body: \'<img src=x onerror="ATTACK()">\' },',
          '];',
          '',
          'const list = document.getElementById("list");',
          '',
          'function renderComment(comment) {',
          '  const li = document.createElement("li");',
          '',
          '  const author = document.createElement("strong");',
          '  author.textContent = comment.author;      // text, not markup',
          '',
          '  const body = document.createElement("span");',
          '  body.textContent = comment.body;',
          '',
          '  li.append(author, " ", body);',
          '  return li;',
          '}',
          '',
          'list.replaceChildren(...comments.map(renderComment));',
          '',
          'console.log("rendered   :", list.children.length);',
          'console.log("no images  :", list.querySelectorAll("img").length);',
          'console.log("no injected b:", list.querySelectorAll("b").length);',
          '',
          '// The malicious author name is displayed literally',
          'console.log("shown as   :", list.children[1].querySelector("strong").textContent);',
        ].join('\n'),
        output: [
          'rendered   : 2',
          'no images  : 0',
          'no injected b: 0',
          'shown as   : <b>Bo</b>',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Build structure with the DOM, insert data as text',
        body: [
          'The pattern that scales: create elements with `createElement`, set **your** structure in code, and put **user data** in with `textContent`. The distinction between structure and data is then enforced by the API rather than by remembering to escape.',
          'Note `createElement("strong")` produced a real `<strong>` while the author\'s literal `<b>Bo</b>` did not become an element. The structure you wrote is markup; the data is text.',
          'For attributes, use `setAttribute` or the property — and be aware that some attributes are **special**: a `href` or `src` accepting a `javascript:` URL executes, so URLs from users need their scheme checked, not just escaping.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Context matters',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        needsDom: true,
        html: '<div id="app"><a id="link">Visit</a><div id="text"></div></div>',
        caption: '`textContent` is right for text — and not a universal answer.',
        code: [
          'const link = document.getElementById("link");',
          'const text = document.getElementById("text");',
          '',
          '// Safe for TEXT content',
          'text.textContent = \'<script>ATTACK()</script>\';',
          'console.log("text safe  :", text.querySelectorAll("*").length === 0);',
          '',
          '// A URL is a DIFFERENT context — textContent does not apply,',
          '// and a javascript: scheme is executable.',
          'function safeUrl(candidate) {',
          '  try {',
          '    const url = new URL(candidate, "https://example.com");',
          '',
          '    // Allowlist the schemes you intend to support',
          '    return ["http:", "https:", "mailto:"].includes(url.protocol) ? url.href : "#";',
          '  } catch {',
          '    return "#";',
          '  }',
          '}',
          '',
          'console.log("https ok   :", safeUrl("https://example.com/page"));',
          'console.log("relative   :", safeUrl("/about"));',
          'console.log("javascript :", safeUrl("javascript:ATTACK()"));',
          'console.log("data uri   :", safeUrl("data:text/html,hi"));',
          'console.log("odd input  :", safeUrl(":::"));',
          '',
          'link.setAttribute("href", safeUrl("javascript:ATTACK()"));',
          'console.log("link href  :", link.getAttribute("href"));',
        ].join('\n'),
        output: [
          'text safe  : true',
          'https ok   : https://example.com/page',
          'relative   : https://example.com/about',
          'javascript : #',
          'data uri   : #',
          'odd input  : https://example.com/:::',
          'link href  : #',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Escaping is context-sensitive',
        body: [
          '`textContent` is the correct tool for **text content**, and it is not a universal solution. Different positions in a document have different rules: an HTML attribute, a URL, a CSS value and a `<script>` block each require different handling, and a value safe in one is dangerous in another.',
          'A **URL** is the case most likely to catch you: `textContent` has nothing to do with it, and a `javascript:` or `data:` scheme in an `href` executes. **Allowlist** the schemes you support rather than trying to block bad ones. Note the `":::"` result — because a **base** was supplied, unrecognised input is resolved as a *relative path* rather than throwing, so it comes back as a harmless `https:` URL on your own origin. That is the desired outcome, but it means the `catch` fires far less often than you might expect: the allowlist, not the parse failure, is what does the work.',
          'Never place user data into a `<script>` block or pass it to `eval`. That is not an escaping problem to solve — it is a design to avoid.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'When you must render user HTML',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Do not write your own sanitiser',
        body: [
          'Some applications genuinely need user-authored HTML — a rich text editor, a markdown comment system. In that case the answer is a **well-maintained sanitiser library** such as DOMPurify, run on the HTML before it is inserted.',
          'A homemade regex sanitiser will fail. HTML parsing has an enormous surface: case variations, encoded characters, nested and malformed constructs, attributes that execute, and parser quirks that differ between browsers. Stripping `<script>` tags with a regular expression addresses one entry point out of many.',
          'This is genuinely a case where "do not implement it yourself" is correct advice rather than laziness — the library exists because the problem takes sustained expert attention to get right, and it is updated as new bypasses are discovered.',
          'Note a sanitiser is used at the point of **rendering**, and the safest architecture stores the original input and sanitises on output, so a later improvement to the sanitiser protects existing content.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        caption: 'The shape of safe rich-text rendering — illustrative.',
        code: [
          'import DOMPurify from "dompurify";',
          '',
          '// Sanitise at RENDER time, with an explicit allowlist',
          'function renderRichText(container, untrustedHtml) {',
          '  const clean = DOMPurify.sanitize(untrustedHtml, {',
          '    ALLOWED_TAGS: ["p", "strong", "em", "a", "ul", "ol", "li"],',
          '    ALLOWED_ATTR: ["href"],',
          '  });',
          '',
          '  container.innerHTML = clean;',
          '}',
          '',
          '// Also worth having: a Content Security Policy, set by the SERVER,',
          '// which limits the damage if something does get through.',
          '//   Content-Security-Policy: default-src \'self\'; script-src \'self\'',
          '//',
          '// A CSP is defence in depth — it does not replace correct escaping,',
          '// and it is a response header, not something the page can set for itself.',
        ].join('\n'),
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const username = getUserInput();   // e.g. from a profile field',
          '',
          'greeting.innerHTML = `Welcome back, ${username}!`;',
          '',
          '// The team argues this is safe because usernames are',
          '// validated to be alphanumeric on the signup form.',
        ].join('\n'),
        options: [
          'Unsafe — the signup validation is client-side and bypassable, and old or API-created records may never have passed it',
          'Safe — the validation guarantees the value is alphanumeric',
          'Safe, because template literals escape values',
          'Unsafe only if the username contains a script tag',
        ],
        correct: 0,
        explanation:
          'Three separate problems. The signup validation runs **in the browser**, so an attacker simply posts to the API without it. Even a server-side rule only governs records created **after** it existed — data from an import, an admin tool, or an older version of the app never passed it. And template literals perform **no escaping**: they interpolate the raw string straight into HTML that `innerHTML` then parses. The fix is not better validation but the right API: `greeting.textContent = \\`Welcome back, ${username}!\\`` cannot create an element whatever the value contains. Note the last option\'s reasoning is also wrong — injection does not require a `<script>` tag, since an event-handler attribute on any element is enough.',
      },
    ],
    exercises: [
      {
        id: 'ex-m44-01-a',
        title: 'Why is client validation not security?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['security'],
        instructions:
          'Your form checks that quantity is between 1 and 10 before submitting. Why is that not a security control?',
        options: [
          'Because JavaScript can be disabled',
          'Because the client is fully under the user\'s control — they can edit the code or call the API directly, bypassing the check entirely',
          'Because numbers are not validated properly',
          'It is a security control',
        ],
        correct: 1,
        hints: [
          'What stops someone sending the request without running your page?',
        ],
        solution: 'Because the client is fully under the user\'s control — they can edit the code or call the API directly, bypassing the check entirely',
        solutionExplanation:
          'Everything shipped to a browser is visible and modifiable: an attacker can edit variables in devtools, replay a request with different values, or skip the page entirely and `curl` the endpoint. Disabling JavaScript is one route among many, not the core reason. Client checks are genuinely valuable as **user experience** — instant feedback, fewer round trips — but every rule that matters must be enforced **server-side**, including quantities, prices, identifiers and permissions.',
      },
      {
        id: 'ex-m44-01-b',
        title: 'Render user content safely',
        kind: EXERCISE_KIND.DOM_TASK,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['security'],
        instructions:
          'Write `renderMessages(container, messages)` rendering each `{ author, text }` as `<li><strong>author</strong><span>text</span></li>`, so that markup in the data is displayed as literal text rather than parsed.',
        html: '<div id="app"><ul id="messages"></ul></div>',
        starterCode: [
          'function renderMessages(container, messages) {',
          '  // Structure with createElement; data with textContent.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'renders one item per message', body: 'const c = document.createElement("ul"); renderMessages(c, [{ author: "a", text: "b" }, { author: "c", text: "d" }]); expect(c.children.length).toBe(2);' },
          { name: 'shows the author', body: 'const c = document.createElement("ul"); renderMessages(c, [{ author: "Ada", text: "hi" }]); expect(c.querySelector("strong").textContent).toBe("Ada");' },
          { name: 'shows the text', body: 'const c = document.createElement("ul"); renderMessages(c, [{ author: "Ada", text: "hi" }]); expect(c.querySelector("span").textContent).toBe("hi");' },
          { name: 'does not parse markup in the text', body: 'const c = document.createElement("ul"); renderMessages(c, [{ author: "a", text: "<img src=x onerror=1>" }]); expect(c.querySelectorAll("img").length).toBe(0);' },
          { name: 'does not parse markup in the author', body: 'const c = document.createElement("ul"); renderMessages(c, [{ author: "<b>x</b>", text: "t" }]); expect(c.querySelectorAll("b").length).toBe(0);' },
          { name: 'displays the markup literally', body: 'const c = document.createElement("ul"); renderMessages(c, [{ author: "<b>x</b>", text: "t" }]); expect(c.querySelector("strong").textContent).toBe("<b>x</b>");' },
          { name: 'replaces previous content', body: 'const c = document.createElement("ul"); renderMessages(c, [{ author: "a", text: "b" }]); renderMessages(c, [{ author: "c", text: "d" }]); expect(c.children.length).toBe(1);' },
          { name: 'handles an empty list', body: 'const c = document.createElement("ul"); renderMessages(c, []); expect(c.children.length).toBe(0);', hidden: true },
        ],
        hints: [
          '`document.createElement` for every element you create.',
          '`textContent` for both the author and the text.',
          '`replaceChildren` swaps the contents in one operation.',
        ],
        solution: [
          'function renderMessages(container, messages) {',
          '  const items = messages.map((message) => {',
          '    const li = document.createElement("li");',
          '',
          '    const author = document.createElement("strong");',
          '    author.textContent = message.author;',
          '',
          '    const text = document.createElement("span");',
          '    text.textContent = message.text;',
          '',
          '    li.append(author, text);',
          '    return li;',
          '  });',
          '',
          '  container.replaceChildren(...items);',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The **structure** comes from `createElement`, so `<strong>` and `<span>` are real elements you intended; the **data** goes in via `textContent`, so nothing in it can become an element — which is what the fourth and fifth tests verify. The sixth test confirms the user still sees exactly what they typed, displayed as literal characters. `replaceChildren` clears and inserts in one operation, which handles re-rendering (seventh test) and avoids `innerHTML = ""` entirely.',
      },
      {
        id: 'ex-m44-01-c',
        title: 'Validate a URL',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['security'],
        instructions:
          'Write `safeHref(candidate)` returning the resolved URL when its scheme is `http:`, `https:` or `mailto:`, and `"#"` otherwise. Resolve relative URLs against `https://example.com`. Anything unparseable returns `"#"`.',
        starterCode: [
          'function safeHref(candidate) {',
          '  // Allowlist the schemes you support. Do not blocklist bad ones.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'allows https', body: 'expect(safeHref("https://example.com/a")).toBe("https://example.com/a");' },
          { name: 'allows http', body: 'expect(safeHref("http://example.com/a")).toBe("http://example.com/a");' },
          { name: 'resolves a relative path', body: 'expect(safeHref("/about")).toBe("https://example.com/about");' },
          { name: 'rejects javascript:', body: 'expect(safeHref("javascript:alert(1)")).toBe("#");' },
          { name: 'rejects data:', body: 'expect(safeHref("data:text/html,x")).toBe("#");' },
          { name: 'resolves odd input as a relative path', body: 'expect(safeHref(":::")).toBe("https://example.com/:::");' },
          { name: 'rejects genuinely unparseable input', body: 'expect(safeHref("http://[")).toBe("#");' },
          { name: 'rejects an unlisted scheme', body: 'expect(safeHref("ftp://example.com/f")).toBe("#");' },
          { name: 'allows mailto', body: 'expect(safeHref("mailto:a@example.com")).toBe("mailto:a@example.com");' },
          { name: 'rejects a mixed-case javascript scheme', body: 'expect(safeHref("JaVaScRiPt:alert(1)")).toBe("#");', hidden: true },
        ],
        hints: [
          '`new URL(candidate, base)` throws on invalid input — wrap it.',
          '`url.protocol` includes the trailing colon.',
          'Check membership in an allowed list, not absence from a blocked one.',
        ],
        solution: [
          'const ALLOWED_PROTOCOLS = ["http:", "https:", "mailto:"];',
          '',
          'function safeHref(candidate) {',
          '  try {',
          '    const url = new URL(candidate, "https://example.com");',
          '',
          '    return ALLOWED_PROTOCOLS.includes(url.protocol) ? url.href : "#";',
          '  } catch {',
          '    return "#";',
          '  }',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Using `new URL` to **parse** rather than pattern-matching the string is what makes the hidden test pass: the parser normalises the scheme, so `JaVaScRiPt:` is recognised as `javascript:` and rejected, where a naive `startsWith("javascript:")` check would let it through. Allowlisting is the essential choice — a blocklist must anticipate every dangerous scheme, while an allowlist rejects anything unanticipated by default. The `try`/`catch` turns genuinely unparseable input such as `"http://["` into a safe `"#"` rather than an exception. Note what `":::"` does, though: because a **base** is supplied, it resolves as a *relative path* on your own origin rather than throwing — safe, but a reminder that the `catch` fires rarely and the **allowlist** is what actually does the work. An unlisted scheme like `ftp:` parses perfectly and is rejected by the allowlist alone.',
      },
      {
        id: 'ex-m44-01-d',
        title: 'Why not write your own sanitiser?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['security'],
        instructions:
          'Your application must render user-authored HTML. Why not strip dangerous tags with a regular expression?',
        options: [
          'Regular expressions are slow',
          'HTML parsing has a vast surface — encodings, case variants, malformed markup, executable attributes and browser quirks — so a homemade filter addresses one entry point among many',
          'Regular expressions cannot match tags',
          'It is fine if you strip script tags',
        ],
        correct: 1,
        hints: [
          'Is a script tag the only way markup can execute?',
        ],
        solution: 'HTML parsing has a vast surface — encodings, case variants, malformed markup, executable attributes and browser quirks — so a homemade filter addresses one entry point among many',
        solutionExplanation:
          'Removing `<script>` handles one route while leaving event-handler attributes, `javascript:` URLs, encoded characters, malformed markup that browsers recover from differently, and constructs that change meaning during parsing. Use a **well-maintained sanitiser** such as DOMPurify with an explicit tag and attribute allowlist — it exists because the problem needs sustained expert attention and is updated as new bypasses are found. Sanitise at **render** time and store the original, so a later library update protects existing content too.',
      },
    ],
    quiz: {
      id: 'qz-m44-01',
      questions: [
        {
          id: 'q-m44-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['security'],
          prompt: 'What is the security value of client-side validation?',
          options: [
            'It prevents invalid data reaching the server',
            'None — it is a user-experience feature; the server must enforce every rule that matters',
            'It protects against XSS',
            'It replaces server checks when the code is minified',
          ],
          correct: 1,
          optionExplanations: [
            'The client can be bypassed entirely.',
            'Correct — convenience, not enforcement.',
            'A separate concern.',
            'Minification is not security.',
          ],
          explanation:
            'An attacker can edit the code or call the API directly. Client checks give fast feedback; the server owns the rules.',
        },
        {
          id: 'q-m44-01-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['security'],
          prompt: 'Why is innerHTML dangerous with user data?',
          options: [
            'It is slow',
            'It runs the HTML parser over the string, so anything resembling markup becomes real elements',
            'It only works on divs',
            'It escapes too aggressively',
          ],
          correct: 1,
          optionExplanations: [
            'Speed is a separate issue.',
            'Correct — content becomes code.',
            'It works on any element.',
            'It does not escape at all.',
          ],
          explanation:
            '`textContent` inserts a text node and escapes on output; `innerHTML` parses, so an element carrying an event-handler attribute can be created from user data.',
        },
        {
          id: 'q-m44-01-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['security'],
          prompt: 'Using textContent everywhere solves all injection problems.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Escaping is context-sensitive.',
            'Correct — a URL is a different context entirely.',
          ],
          explanation:
            '`textContent` is right for text content. A URL in an `href` can carry a `javascript:` scheme, which `textContent` has nothing to do with — allowlist schemes instead.',
        },
        {
          id: 'q-m44-01-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['security'],
          prompt: 'Where should a price be determined?',
          options: [
            'On the client, then sent with the order',
            'On the server, looked up from its own catalogue and never taken from the request',
            'Either is fine if the client validates it',
            'In localStorage',
          ],
          correct: 1,
          optionExplanations: [
            'A user can edit it to zero.',
            'Correct — re-derive server-side.',
            'Client validation is bypassable.',
            'Also client-controlled.',
          ],
          explanation:
            'Any value the client sends is input, including values your own code put there. Prices, roles and permissions must be re-derived or validated server-side.',
        },
      ],
    },
    summary:
      '**The client is not a trust boundary.** Everything shipped to a browser is visible and modifiable, so client-side checks are a **user-experience feature, not a security control** — an attacker edits variables, replays requests, or calls the API directly. Every rule that matters must be enforced **server-side**, and any value the client sends is **input**, including values your own code put there: never trust a client-supplied **price**, role or identifier — re-derive it. **XSS** occurs when untrusted data enters a page as **code** rather than **content**, letting an attacker\'s JavaScript run in another user\'s browser on your origin, with access to everything that session can reach. The mechanism is precise: **`innerHTML` runs the HTML parser**, so anything resembling markup becomes real elements — including ones carrying event-handler attributes, which is why "it is only an image tag" is no comfort. **`textContent` inserts a text node** and escapes on output. The pattern that scales is **structure with `createElement`, data with `textContent`**, so the API enforces the distinction rather than your memory. But **escaping is context-sensitive**: a **URL** is a different context where `textContent` does not apply and a `javascript:` scheme executes — **allowlist** schemes by parsing with `new URL`, never blocklist strings. When user-authored HTML is genuinely required, use a **maintained sanitiser** with an explicit allowlist; a homemade regex filter addresses one entry point among many.',
    keyTakeaways: [
      'Client checks are UX; the server enforces every rule that matters',
      'Never trust a client-supplied price, role or identifier — re-derive it',
      'innerHTML parses markup into elements; textContent inserts a text node',
      'Build structure with createElement and insert data with textContent',
      'Escaping is context-sensitive — allowlist URL schemes by parsing them',
      'Use a maintained sanitiser for user HTML; never write your own',
    ],
    relatedLessons: ['l-m44-02', 'l-m27-01'],
    interviewConnections: [
      'What is XSS and how do you prevent it?',
      'Why is innerHTML dangerous with user input?',
      'Is client-side validation a security measure?',
      'How would you safely render a user-supplied link?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m44-02',
    slug: 'auth-secrets-and-dependencies',
    moduleId: M,
    order: 2,
    title: 'Auth, Secrets, CORS and Dependencies',
    description: 'Authentication versus authorisation, where tokens can live, and the risks you inherit.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 19,
    xp: 50,
    topicIds: ['security'],
    prerequisites: ['l-m44-01'],
    learningObjectives: [
      'Distinguish authentication from authorisation',
      'Reason about token storage trade-offs without absolutes',
      'Correct common CORS misconceptions',
      'Assess dependency and prototype-pollution risk',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Authentication versus authorisation',
      },
      {
        kind: SECTION.TERMS,
        terms: [
          { term: 'Authentication', definition: '**Who are you?** Establishing identity — a password, a passkey, a token that proves a prior sign-in.' },
          { term: 'Authorisation', definition: '**Are you allowed to do this?** Deciding whether an identified user may perform a specific action on a specific resource.' },
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The client decides what to *show*; the server decides what is *allowed*.',
        code: [
          '"use strict";',
          '',
          '// CLIENT: hiding a control is a UI decision, nothing more',
          'function visibleActions(user, post) {',
          '  const actions = ["view"];',
          '',
          '  if (user.id === post.authorId) actions.push("edit");',
          '  if (user.role === "admin") actions.push("delete");',
          '',
          '  return actions;',
          '}',
          '',
          '// SERVER: the same question, but this one is enforcement',
          'function authoriseDelete(session, post) {',
          '  if (!session.userId) return { allowed: false, status: 401, reason: "not authenticated" };',
          '',
          '  const isAuthor = session.userId === post.authorId;',
          '  const isAdmin = session.role === "admin";',
          '',
          '  if (!isAuthor && !isAdmin) return { allowed: false, status: 403, reason: "not authorised" };',
          '',
          '  return { allowed: true, status: 200 };',
          '}',
          '',
          'const post = { id: 1, authorId: 7 };',
          '',
          'console.log("author sees  :", visibleActions({ id: 7, role: "user" }, post));',
          'console.log("stranger sees:", visibleActions({ id: 9, role: "user" }, post));',
          '',
          '// A stranger who calls DELETE directly is still refused',
          'console.log("author       :", authoriseDelete({ userId: 7, role: "user" }, post));',
          'console.log("stranger     :", authoriseDelete({ userId: 9, role: "user" }, post));',
          'console.log("signed out   :", authoriseDelete({}, post));',
        ].join('\n'),
        output: [
          'author sees  : ["view", "edit"]',
          'stranger sees: ["view"]',
          'author       : {allowed: true, status: 200}',
          'stranger     : {allowed: false, status: 403, reason: "not authorised"}',
          'signed out   : {allowed: false, status: 401, reason: "not authenticated"}',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Hiding a button is not authorisation',
        body: [
          'A hidden control is invisible, not unreachable. Anyone can find the endpoint in the network tab and call it directly, so the UI check protects nothing.',
          'Both are worth doing, for different reasons: hiding avoids showing users actions that would fail, and the server check is what actually prevents the action. **Never** let the first substitute for the second.',
          'Note the two status codes carry distinct meanings: **401** means "I do not know who you are" (authentication failed), **403** means "I know who you are, and no" (authorisation failed). Using them correctly matters for clients deciding whether to prompt for sign-in.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Where a token can live',
      },
      {
        kind: SECTION.TABLE,
        headers: ['', '`localStorage`', '`HttpOnly` cookie'],
        rows: [
          ['Readable by JavaScript', '**Yes** — so any XSS can steal it', '**No** — invisible to `document.cookie`'],
          ['Sent automatically', 'No — you attach it yourself', '**Yes**, on every matching request'],
          ['Vulnerable to CSRF', 'No — nothing is sent automatically', '**Yes**, unless `SameSite` is set'],
          ['Works cross-origin', 'Easily — just add a header', 'Needs `credentials` and server cooperation'],
          ['Survives a tab close', 'Yes', 'Depends on expiry'],
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'There is no universal rule here — the trade-off is real',
        body: [
          'You will see "always use `localStorage` for JWTs" and "never use `localStorage` for anything". Both are wrong as absolutes, because the two options are vulnerable to **different attacks**.',
          '`localStorage` is readable by any script on the origin, so a single XSS bug exfiltrates the token. An **`HttpOnly` cookie** is not readable by JavaScript, so XSS cannot steal it — but because it is sent **automatically**, it is exposed to CSRF unless `SameSite` is configured (Module 27).',
          'The defensible default for a first-party web application is an **`HttpOnly`, `Secure`, `SameSite` cookie**, because it removes the worst outcome (token theft) and the remaining risk has a well-understood mitigation. Cross-origin APIs, mobile clients and third-party integrations legitimately change the calculation.',
          'What is **not** a trade-off: an XSS bug is severe either way. With a cookie the attacker cannot steal the token, but they can still make requests **as the user** from the page. Preventing XSS is the primary defence; storage choice limits the blast radius.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Reasoning about the exposure of each approach.',
        code: [
          '"use strict";',
          '',
          '// Modelling what an injected script could reach in each design',
          'function exposure(design) {',
          '  const risks = [];',
          '',
          '  if (design.tokenReadableByJs) risks.push("XSS can exfiltrate the token");',
          '  if (design.sentAutomatically && !design.sameSite) risks.push("CSRF possible");',
          '  if (!design.secure) risks.push("token visible over plain HTTP");',
          '',
          '  // True of BOTH designs — XSS can always act as the user',
          '  risks.push("XSS can make requests as the user");',
          '',
          '  return risks;',
          '}',
          '',
          'console.log("web storage :", exposure({',
          '  tokenReadableByJs: true, sentAutomatically: false, sameSite: false, secure: true,',
          '}));',
          '',
          'console.log("cookie, no SameSite:", exposure({',
          '  tokenReadableByJs: false, sentAutomatically: true, sameSite: false, secure: true,',
          '}));',
          '',
          'console.log("cookie, configured :", exposure({',
          '  tokenReadableByJs: false, sentAutomatically: true, sameSite: true, secure: true,',
          '}));',
        ].join('\n'),
        output: [
          'web storage : ["XSS can exfiltrate the token", "XSS can make requests as the user"]',
          'cookie, no SameSite: ["CSRF possible", "XSS can make requests as the user"]',
          'cookie, configured : ["XSS can make requests as the user"]',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'CSRF, briefly',
      },
      {
        kind: SECTION.PROSE,
        body: [
          '**Cross-site request forgery** exploits the fact that cookies are sent **automatically**. A malicious page causes the victim\'s browser to issue a request to your site, and the browser attaches the session cookie — so the request arrives authenticated, even though the user never intended it.',
          'The defences are all server-side or configuration, not application JavaScript: **`SameSite`** cookies (which stop the cookie being sent on cross-site requests), **anti-CSRF tokens** that a forged request cannot know, and checking the **`Origin`** header on state-changing requests.',
          'Note that a `SameSite=Lax` default in modern browsers has substantially reduced this class of attack, but it is not a reason to omit the other defences.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Secrets do not exist in the browser',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'What "environment variable" means in a bundled front end.',
        code: [
          '"use strict";',
          '',
          '// A build tool replaces this at BUILD time with a literal string',
          'const config = {',
          '  apiUrl: "https://api.example.com",',
          '  analyticsId: "UA-PUBLIC-123",',
          '  // If you put a secret here, it is now in the JavaScript bundle',
          '  // that every visitor downloads. It is not hidden by anything.',
          '};',
          '',
          'console.log("shipped to every visitor:", Object.keys(config));',
          '',
          '// Which keys are safe to ship?',
          'function classify(key) {',
          '  const publicByDesign = ["apiUrl", "analyticsId", "publishableKey", "mapsApiKey"];',
          '  const neverShip = ["dbPassword", "secretKey", "privateApiKey", "signingSecret"];',
          '',
          '  if (neverShip.includes(key)) return "SERVER ONLY";',
          '  if (publicByDesign.includes(key)) return "safe to ship";',
          '',
          '  return "assume server only until proven otherwise";',
          '}',
          '',
          'for (const key of ["apiUrl", "publishableKey", "secretKey", "somethingNew"]) {',
          '  console.log(`${key.padEnd(16)} ${classify(key)}`);',
          '}',
        ].join('\n'),
        output: [
          'shipped to every visitor: ["apiUrl", "analyticsId"]',
          'apiUrl           safe to ship',
          'publishableKey   safe to ship',
          'secretKey        SERVER ONLY',
          'somethingNew     assume server only until proven otherwise',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'A front-end `.env` file is not a secret vault',
        body: [
          'Build tools substitute environment variables into the bundle at **build time**. The result is a literal string in JavaScript that every visitor downloads — the `.env` file kept it out of your repository, and did nothing else.',
          'So there is no way to keep a secret in front-end code. A private API key in the browser is a published API key.',
          'The correct architecture: the browser calls **your** server, and your server holds the secret and calls the third party. Some services deliberately issue **publishable** keys designed to be public and restricted by origin — those are safe by design, and are the exception that proves the rule.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'CORS is not what people think',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Four corrections',
        body: [
          '**CORS is not authentication.** It says nothing about who a user is. It governs whether a **browser** lets one origin\'s JavaScript read another origin\'s response.',
          '**CORS does not protect your API.** It is enforced by the browser, so `curl`, a script, or any server-to-server client ignores it entirely. An endpoint reachable without authorisation is unprotected regardless of its CORS headers.',
          '**A CORS error is not a client bug you can patch in JavaScript.** The permission comes from the **server\'s response headers**. Changing your `fetch` call cannot grant it.',
          '**`mode: "no-cors"` does not fix it.** It gives you an opaque response you cannot read — which is not access, it is a silent failure that looks like success.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'What CORS actually governs.',
        code: [
          '"use strict";',
          '',
          'function sameOrigin(a, b) {',
          '  const x = new URL(a);',
          '  const y = new URL(b);',
          '',
          '  return x.protocol === y.protocol && x.hostname === y.hostname && x.port === y.port;',
          '}',
          '',
          'const page = "https://app.example.com";',
          '',
          'console.log("same path  :", sameOrigin(page, "https://app.example.com/api"));',
          'console.log("subdomain  :", sameOrigin(page, "https://api.example.com"));',
          'console.log("http vs https:", sameOrigin(page, "http://app.example.com"));',
          'console.log("other port :", sameOrigin(page, "https://app.example.com:8443"));',
          '',
          '// Only cross-origin requests need CORS permission — and that',
          '// permission is granted by the SERVER, in response headers:',
          '//   Access-Control-Allow-Origin: https://app.example.com',
          '//   Access-Control-Allow-Credentials: true',
          '//',
          '// With credentials, the origin must be explicit — "*" is rejected.',
          'function corsAllows(allowOrigin, withCredentials, requestOrigin) {',
          '  if (withCredentials && allowOrigin === "*") return false;',
          '',
          '  return allowOrigin === "*" || allowOrigin === requestOrigin;',
          '}',
          '',
          'console.log("wildcard    :", corsAllows("*", false, page));',
          'console.log("wildcard+creds:", corsAllows("*", true, page));',
          'console.log("explicit+creds:", corsAllows(page, true, page));',
        ].join('\n'),
        output: [
          'same path  : true',
          'subdomain  : false',
          'http vs https: false',
          'other port : false',
          'wildcard    : true',
          'wildcard+creds: false',
          'explicit+creds: true',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'Dependencies and prototype pollution',
      },
      {
        kind: SECTION.LIST,
        items: [
          '**Every dependency is code you ship.** It runs with the same privileges as yours, and it brings its own dependencies — a small package can pull in dozens.',
          '**Commit the lockfile.** It pins the exact resolved versions so every install and every deploy gets the same tree (Module 45).',
          '**Audit regularly.** `npm audit` reports known vulnerabilities in your tree. Act on the ones that apply to how you actually use the package.',
          '**Check the package before adding it.** Recent releases, real usage, a plausible maintainer. **Typosquatting** — a package one character from a popular name — is a genuine attack.',
          '**Prefer fewer dependencies.** A twenty-line utility you own beats a package you must audit, update and trust indefinitely.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Prototype pollution — why naive merging is dangerous.',
        code: [
          '"use strict";',
          '',
          '// A naive recursive merge, of the kind found in many small utilities',
          'function unsafeMerge(target, source) {',
          '  for (const key of Object.keys(source)) {',
          '    if (typeof source[key] === "object" && source[key] !== null) {',
          '      target[key] = target[key] ?? {};',
          '      unsafeMerge(target[key], source[key]);',
          '    } else {',
          '      target[key] = source[key];',
          '    }',
          '  }',
          '',
          '  return target;',
          '}',
          '',
          '// A SAFE merge: refuse keys that reach the prototype chain',
          'const FORBIDDEN = new Set(["__proto__", "constructor", "prototype"]);',
          '',
          'function safeMerge(target, source) {',
          '  for (const key of Object.keys(source)) {',
          '    if (FORBIDDEN.has(key)) continue;          // allowlist-style refusal',
          '',
          '    if (typeof source[key] === "object" && source[key] !== null) {',
          '      target[key] = target[key] ?? {};',
          '      safeMerge(target[key], source[key]);',
          '    } else {',
          '      target[key] = source[key];',
          '    }',
          '  }',
          '',
          '  return target;',
          '}',
          '',
          '// Untrusted input — e.g. a parsed JSON request body',
          'const untrusted = JSON.parse(\'{"name":"ok","__proto__":{"polluted":"yes"}}\');',
          '',
          'const safeResult = safeMerge({}, untrusted);',
          '',
          'console.log("merged name    :", safeResult.name);',
          'console.log("dangerous key skipped:", !("polluted" in safeResult));',
          'console.log("prototype clean:", {}.polluted === undefined);',
          '',
          '// Object.create(null) has no prototype to pollute at all',
          'const bare = Object.create(null);',
          'console.log("null prototype :", Object.getPrototypeOf(bare));',
        ].join('\n'),
        output: [
          'merged name    : ok',
          'dangerous key skipped: true',
          'prototype clean: true',
          'null prototype : null',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'What prototype pollution is, and how to avoid it',
        body: [
          'If untrusted keys are merged into an object without filtering, a crafted key can reach **`Object.prototype`** — and because every object delegates to it (Module 30), a property added there appears on *every* object in the program. That can flip a security flag, satisfy a check that should have failed, or corrupt unrelated logic.',
          'The defences, in order: **do not write naive recursive merges** over untrusted data; **filter dangerous keys** (`__proto__`, `constructor`, `prototype`) or, better, **allowlist the keys you expect**; use `Object.create(null)` or a **`Map`** for dictionaries keyed by user input (Module 34); and prefer well-maintained libraries for merging.',
          'Note this lesson demonstrates only the **safe** version. The dangerous mechanism is described rather than executed, because the defence does not require reproducing the attack.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'eval and the Function constructor',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Never execute strings that came from outside',
        body: [
          '`eval(userInput)` and `new Function(userInput)` execute arbitrary code with your page\'s full privileges. If any part of that string is influenced by an attacker, they are running code on your origin.',
          'Beyond injection: both defeat a **Content Security Policy** (which typically forbids them), make debugging harder, and prevent engines from optimising the surrounding code.',
          'Almost every use has a better alternative. Parsing data? `JSON.parse`. Dynamic property access? `obj[key]`. Choosing behaviour by name? A lookup object — the strategy pattern from Module 41.',
          'A note on this curriculum: JSPath **does** evaluate your code, deliberately, inside an isolated sandbox designed for it (a worker or a null-origin frame). A controlled educational sandbox is a different situation from executing untrusted strings in your application, and is not a licence for the latter.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// A team fixes a CORS error by changing the front-end call:',
          '',
          'const response = await fetch(url, { mode: "no-cors" });',
          'const data = await response.json();',
          '',
          '// The console error disappeared. Is the problem solved?',
        ].join('\n'),
        options: [
          'No — the response is opaque and unreadable, so this trades a clear error for a silent failure',
          'Yes — no-cors bypasses the restriction',
          'Yes, provided the server is trusted',
          'No, but adding a header to the request would fix it',
        ],
        correct: 0,
        explanation:
          '`mode: "no-cors"` does not grant access — it asks the browser to make the request without requiring CORS permission and to hand back an **opaque** response whose status, headers and body are all unreadable. `response.json()` therefore fails or yields nothing, and the loud console error has been traded for a confusing one further downstream. CORS permission is granted by the **server\'s response headers** (`Access-Control-Allow-Origin`), so no change to the `fetch` call can produce it — nor can adding a request header, which would in fact trigger a preflight and make things stricter. The real fixes are to configure the server, or to proxy the request through your own backend.',
      },
    ],
    exercises: [
      {
        id: 'ex-m44-02-a',
        title: 'Authentication or authorisation?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['security'],
        instructions:
          'A signed-in user requests another user\'s private document and the server returns 403. Which check failed?',
        options: [
          'Authentication — their identity could not be established',
          'Authorisation — they are known, but not permitted to access this resource',
          'Both',
          'Neither; 403 means the resource is missing',
        ],
        correct: 1,
        hints: [
          'What does 403 mean as opposed to 401?',
        ],
        solution: 'Authorisation — they are known, but not permitted to access this resource',
        solutionExplanation:
          'The user is signed in, so **authentication** succeeded — the server knows who they are. What failed is **authorisation**: this identity is not permitted this action on this resource. The status codes encode that distinction precisely: **401** means "I do not know who you are", which tells a client to prompt for sign-in, while **403** means "I know who you are, and no", where prompting again would be pointless. `404` is the missing-resource code, though it is sometimes returned instead of 403 deliberately, to avoid revealing that a resource exists.',
      },
      {
        id: 'ex-m44-02-b',
        title: 'Merge untrusted data safely',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['security'],
        instructions:
          'Write `safeAssign(target, source, allowedKeys)` copying only keys present in `allowedKeys` from `source` to `target`, returning `target`. Anything not explicitly allowed is ignored.',
        starterCode: [
          'function safeAssign(target, source, allowedKeys) {',
          '  // Allowlist. Do not try to blocklist dangerous names.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'copies an allowed key', body: 'expect(safeAssign({}, { a: 1 }, ["a"])).toEqual({ a: 1 });' },
          { name: 'ignores a key not allowed', body: 'expect(safeAssign({}, { a: 1, b: 2 }, ["a"])).toEqual({ a: 1 });' },
          { name: 'returns the target', body: 'const t = {}; expect(safeAssign(t, { a: 1 }, ["a"])).toBe(t);' },
          { name: 'ignores __proto__ when not allowed', body: 'const parsed = JSON.parse(\'{"__proto__":{"x":1},"a":2}\'); safeAssign({}, parsed, ["a"]); expect({}.x).toBe(undefined);' },
          { name: 'ignores constructor when not allowed', body: 'expect(safeAssign({}, { constructor: "bad", a: 1 }, ["a"])).toEqual({ a: 1 });' },
          { name: 'handles an empty allowlist', body: 'expect(safeAssign({}, { a: 1 }, [])).toEqual({});' },
          { name: 'skips keys absent from the source', body: 'expect(safeAssign({}, { a: 1 }, ["a", "b"])).toEqual({ a: 1 });' },
          { name: 'copies a falsy allowed value', body: 'expect(safeAssign({}, { a: 0 }, ["a"])).toEqual({ a: 0 });', hidden: true },
        ],
        hints: [
          'Iterate `allowedKeys`, not the source\'s keys.',
          '`Object.hasOwn(source, key)` checks presence without touching the prototype chain.',
          'That inverts the problem: dangerous keys can never be reached.',
        ],
        solution: [
          'function safeAssign(target, source, allowedKeys) {',
          '  for (const key of allowedKeys) {',
          '    if (Object.hasOwn(source, key)) {',
          '      target[key] = source[key];',
          '    }',
          '  }',
          '',
          '  return target;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Iterating the **allowlist** rather than the source inverts the problem entirely: a key the caller did not explicitly permit is never even looked at, so `__proto__` and `constructor` cannot be reached no matter what the untrusted input contains. That is why the fourth and fifth tests pass without any mention of those names — a blocklist would have to anticipate every dangerous key, while an allowlist rejects the unanticipated by default. `Object.hasOwn` checks the source\'s **own** properties, avoiding inherited values, and assigning directly preserves a falsy `0`.',
      },
      {
        id: 'ex-m44-02-c',
        title: 'Correct the CORS misconception',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.HARD,
        xp: 25,
        topicIds: ['security'],
        instructions:
          'A colleague says "our API is secure because CORS only allows our own domain". What is wrong?',
        options: [
          'Nothing — that is what CORS is for',
          'CORS is enforced by the browser, so any non-browser client ignores it entirely; the API needs real authorisation',
          'CORS should list more domains',
          'CORS only works over HTTPS',
        ],
        correct: 1,
        hints: [
          'What happens when the request comes from curl?',
        ],
        solution: 'CORS is enforced by the browser, so any non-browser client ignores it entirely; the API needs real authorisation',
        solutionExplanation:
          'CORS is a **browser** policy governing whether one origin\'s JavaScript may read another origin\'s response. `curl`, a script, a mobile app or a server-to-server call never consults it, so an endpoint reachable without authorisation is fully exposed regardless of its CORS headers. CORS is also not authentication — it says nothing about who the user is. Real protection comes from authenticating the request and authorising the action server-side; CORS only limits what **other websites** can do with a user\'s browser.',
      },
      {
        id: 'ex-m44-02-d',
        title: 'Where does the API key go?',
        kind: EXERCISE_KIND.CHOOSE_IMPLEMENTATION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['security'],
        instructions:
          'Your app must call a paid third-party API that requires a private key. Where should the key live?',
        options: [
          'In a front-end `.env` file, injected at build time',
          'On your server — the browser calls your backend, which holds the key and calls the third party',
          'In localStorage, set at runtime',
          'Obfuscated in the bundle',
        ],
        correct: 1,
        hints: [
          'What happens to a build-time variable in the shipped bundle?',
        ],
        solution: 'On your server — the browser calls your backend, which holds the key and calls the third party',
        solutionExplanation:
          'A build tool substitutes a front-end environment variable into the bundle as a **literal string**, so every visitor downloads it — the `.env` file kept it out of the repository and achieved nothing else. `localStorage` is equally readable, and obfuscation only delays someone reading the network tab. The only architecture that keeps a secret secret is to keep it **off the client**: the browser calls your server, which holds the key. Note some services issue deliberately **publishable** keys, restricted by origin and safe to ship — those are a different thing from a private key.',
      },
    ],
    quiz: {
      id: 'qz-m44-02',
      questions: [
        {
          id: 'q-m44-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['security'],
          prompt: 'What is the difference between 401 and 403?',
          options: [
            'They are interchangeable',
            '401 means the identity is unknown; 403 means the identity is known but not permitted',
            '401 is for APIs, 403 for pages',
            '403 means the resource is missing',
          ],
          correct: 1,
          optionExplanations: [
            'They signal different failures.',
            'Correct — authentication versus authorisation.',
            'Both apply anywhere.',
            'That is 404.',
          ],
          explanation:
            '401 tells a client to prompt for sign-in; 403 says prompting would not help. Using them correctly matters for how clients respond.',
        },
        {
          id: 'q-m44-02-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['security'],
          prompt: 'What does an HttpOnly cookie protect against that localStorage does not?',
          options: [
            'CSRF',
            'Token theft via XSS — JavaScript cannot read it',
            'Network interception',
            'Brute force attacks',
          ],
          correct: 1,
          optionExplanations: [
            'Cookies are more exposed to CSRF, not less.',
            'Correct — invisible to document.cookie.',
            'That is what Secure and HTTPS address.',
            'Unrelated.',
          ],
          explanation:
            'HttpOnly removes the token from JavaScript\'s reach, so XSS cannot exfiltrate it — at the cost of CSRF exposure, which `SameSite` mitigates.',
        },
        {
          id: 'q-m44-02-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['security'],
          prompt: 'A front-end environment variable can hold an API secret if it is not committed to git.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It is substituted into the bundle.',
            'Correct — every visitor downloads it.',
          ],
          explanation:
            'Build tools inline the value as a literal string in the shipped JavaScript. Keeping it out of the repository does not keep it out of the browser.',
        },
        {
          id: 'q-m44-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['security'],
          prompt: 'How do you avoid prototype pollution when handling untrusted objects?',
          options: [
            'Freeze every object',
            'Allowlist the keys you expect, and use Object.create(null) or a Map for user-keyed dictionaries',
            'Use JSON.parse only',
            'Avoid nested objects',
          ],
          correct: 1,
          optionExplanations: [
            'Freezing does not stop merging into a prototype.',
            'Correct — never reach unanticipated keys.',
            'JSON.parse can produce a __proto__ key.',
            'Depth is not the issue.',
          ],
          explanation:
            'Iterating an allowlist means a dangerous key is never touched. `Object.create(null)` has no prototype to pollute, and a `Map` keeps keys out of the object model entirely.',
        },
      ],
    },
    summary:
      '**Authentication** asks *who are you*; **authorisation** asks *are you allowed*. Hiding a button is a UI convenience — the endpoint is still reachable — so authorisation must be enforced server-side, using **401** for unknown identity and **403** for known-but-refused. For **token storage** there is no universal rule, because the options fail differently: `localStorage` is readable by any script, so **XSS exfiltrates the token**, while an **`HttpOnly` cookie** is unreadable by JavaScript but sent **automatically**, exposing it to **CSRF** unless `SameSite` is set. A first-party web app\'s defensible default is an `HttpOnly`, `Secure`, `SameSite` cookie — but note that **XSS is severe either way**, since an injected script can act as the user regardless; storage choice limits blast radius, it does not replace preventing XSS. **Secrets cannot exist in the browser**: build tools inline environment variables as literal strings that every visitor downloads, so a private key belongs on **your server**, which the browser calls. **CORS** is widely misunderstood — it is **not authentication**, it does **not protect your API** (non-browser clients ignore it), a CORS error is granted or denied by the **server\'s response headers** rather than fixable in your `fetch` call, and **`mode: "no-cors"`** yields an unreadable opaque response, trading a clear error for a silent failure. Finally, **dependencies are code you ship** — commit the lockfile, audit, and prefer fewer — and avoid **prototype pollution** by **allowlisting expected keys** rather than blocklisting dangerous ones, and never `eval` a string from outside.',
    keyTakeaways: [
      'Authentication is identity; authorisation is permission — 401 versus 403',
      'Hiding a control is not authorisation; the server must enforce it',
      'localStorage risks XSS theft; HttpOnly cookies risk CSRF — no universal rule',
      'A front-end env variable is inlined into the bundle and is not a secret',
      'CORS is a browser policy, not authentication, and not API protection',
      'Allowlist keys when merging untrusted data; never eval outside input',
    ],
    relatedLessons: ['l-m44-01', 'l-m27-02'],
    interviewConnections: [
      'What is the difference between authentication and authorisation?',
      'Where should a JWT be stored, and why is it a trade-off?',
      'What does CORS actually do?',
      'What is prototype pollution and how do you prevent it?',
    ],
  },
];
