import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm37';

export default [
  /* ================================================================== */
  {
    id: 'l-m37-01',
    slug: 'purity-and-side-effects',
    moduleId: M,
    order: 1,
    title: 'Purity and Side Effects',
    description: 'What makes a function pure, why side effects are necessary, and how to keep them contained.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 17,
    xp: 45,
    topicIds: ['functional'],
    prerequisites: ['l-m36-03'],
    learningObjectives: [
      'Define purity carefully, including the edge cases',
      'Identify side effects and explain why they are necessary',
      'Separate decisions from effects to make logic testable',
      'Explain referential transparency',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'What "pure" means',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'A function is **pure** when two things hold: the same inputs always produce the same output, and calling it causes no externally observable change.',
          'Both halves matter. A function that returns a consistent value but writes to a database is not pure. A function that changes nothing but returns `Math.random()` is not pure either.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Pure and impure, side by side.',
        code: [
          '"use strict";',
          '',
          '// PURE: output depends only on the arguments',
          'function add(a, b) {',
          '  return a + b;',
          '}',
          '',
          'function totalOf(items) {',
          '  return items.reduce((sum, item) => sum + item.price, 0);',
          '}',
          '',
          'console.log("add     :", add(2, 3), add(2, 3), add(2, 3));',
          '',
          '// IMPURE: mutates something outside itself',
          'const cart = [];',
          'function addToCart(product) {',
          '  cart.push(product);',
          '  return cart.length;',
          '}',
          '',
          'console.log("impure  :", addToCart("a"), addToCart("a"), addToCart("a"));',
          '',
          '// IMPURE: mutates its argument',
          'function markDoneBad(task) {',
          '  task.done = true;',
          '  return task;',
          '}',
          '',
          '// PURE: returns a new object instead',
          'function markDone(task) {',
          '  return { ...task, done: true };',
          '}',
          '',
          'const task = { id: 1, done: false };',
          'const updated = markDone(task);',
          '',
          'console.log("original:", task.done);',
          'console.log("updated :", updated.done);',
        ].join('\n'),
        output: [
          'add     : 5 5 5',
          'impure  : 1 2 3',
          'original: false',
          'updated : true',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Mutating an argument is a side effect',
        body: [
          '`markDoneBad` looks harmless, but the caller\'s object changed — and nothing at the call site suggests it would. `const result = markDoneBad(task)` reads like a transformation and is actually a mutation.',
          'The same identical call also produces a different observable world each time, so it fails both halves of the definition.',
          'Returning a new object costs a shallow copy and buys a function you can call anywhere, in any order, without checking what else holds a reference. This is why Module 34\'s immutable-update patterns matter.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The edge cases that make the definition subtle.',
        code: [
          '"use strict";',
          '',
          '// Impure: same input, different output',
          'function randomId() { return Math.random(); }',
          '',
          '// Impure: depends on the clock',
          'function isExpired(date) { return date < Date.now(); }',
          '',
          '// PURE version — the varying input becomes a parameter',
          'function isExpiredAt(date, now) { return date < now; }',
          '',
          'console.log("pure check:", isExpiredAt(100, 200), isExpiredAt(100, 200));',
          '',
          '// Impure: reads mutable outer state',
          'let taxRate = 0.2;',
          'function withTaxImpure(amount) { return amount * (1 + taxRate); }',
          '',
          'console.log("before:", withTaxImpure(100));',
          'taxRate = 0.5;',
          'console.log("after :", withTaxImpure(100));',
          '',
          '// PURE: the dependency is a parameter',
          'function withTax(amount, rate) { return amount * (1 + rate); }',
          'console.log("pure  :", withTax(100, 0.2), withTax(100, 0.2));',
          '',
          '// Pure ENOUGH: a local mutation nobody outside can observe',
          'function sortedCopy(items) {',
          '  const copy = [...items];',
          '  copy.sort();               // mutates, but only a local array',
          '  return copy;',
          '}',
          '',
          'const original = ["c", "a", "b"];',
          'console.log("sorted:", sortedCopy(original), "| original:", original);',
        ].join('\n'),
        output: [
          'pure check: true true',
          'before: 120',
          'after : 150',
          'pure  : 120 120',
          'sorted: ["a", "b", "c"] | original: ["c", "a", "b"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Local mutation is not a side effect',
        body: [
          '`sortedCopy` mutates an array — but one it created, which nothing outside can observe. Callers see only "same input, same output, nothing changed", so it is pure by the definition that matters.',
          'This is worth stating because "functional" is often mistaken for "never use a loop or reassign a variable". Purity is about **observable** behaviour at the boundary, not about the style inside.',
          'The recurring technique in the impure examples is the same one: **make the hidden dependency a parameter**. The clock, the tax rate, the random source — each becomes an argument, and the function becomes pure and testable.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Referential transparency',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A pure call can be replaced by its result.',
        code: [
          '"use strict";',
          '',
          'function double(n) { return n * 2; }',
          '',
          '// These two lines are interchangeable — that is referential transparency',
          'console.log("call   :", double(5) + double(5));',
          'console.log("inlined:", 10 + 10);',
          '',
          '// An impure call is NOT interchangeable',
          'let calls = 0;',
          'function countedDouble(n) { calls += 1; return n * 2; }',
          '',
          'const a = countedDouble(5) + countedDouble(5);',
          'console.log("impure result:", a, "| calls:", calls);',
          '',
          'calls = 0;',
          'const b = 10 + 10;',
          'console.log("inlined      :", b, "| calls:", calls);',
        ].join('\n'),
        output: [
          'call   : 20',
          'inlined: 20',
          'impure result: 20 | calls: 2',
          'inlined      : 20 | calls: 0',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          '**Referential transparency** is the property that a call can be replaced by its result without changing the program. It is what makes memoisation safe (Module 32), what lets you reorder or skip calls, and what makes a function easy to reason about in isolation.',
          'The impure version produces the same number but a different world — the call count changed — so the substitution is not valid.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Side effects are necessary',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: '"Good code has no side effects" is nonsense',
        body: [
          'A program with no side effects displays nothing, saves nothing, and sends nothing. Every useful application exists **because** of its effects — rendering, requests, storage, logging.',
          'The goal is never elimination. It is to **contain** effects at the edges, so the decisions underneath stay pure and testable.',
          'Purity is also not a moral property. An impure function is not bad code — `addToCart` genuinely must change the cart. What matters is that it is *identifiable* as effectful, and that the calculation of *what* to add is separable from the act of adding.',
        ],
      },
      {
        kind: SECTION.LIST,
        items: [
          '**Network** — `fetch`, WebSockets (Module 26).',
          '**DOM** — reading or writing the page (Modules 17–19).',
          '**Storage** — `localStorage`, cookies, IndexedDB (Module 27).',
          '**Console and logging.**',
          '**Time and randomness** — `Date.now()`, `Math.random()`.',
          '**Mutating anything the caller can see** — arguments, module-level state, globals.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Separating the decision from the effect.',
        code: [
          '"use strict";',
          '',
          '// BEFORE: one function that decides AND acts',
          'const log = [];',
          'let stock = { apple: 2 };',
          '',
          'function checkoutMixed(item, quantity) {',
          '  if (!stock[item] || stock[item] < quantity) {',
          '    log.push(`rejected ${item}`);',
          '    return false;',
          '  }',
          '',
          '  stock[item] -= quantity;',
          '  log.push(`sold ${quantity} ${item}`);',
          '  return true;',
          '}',
          '',
          '// AFTER: a pure decision...',
          'function decideCheckout(stock, item, quantity) {',
          '  if (!stock[item] || stock[item] < quantity) {',
          '    return { ok: false, reason: "insufficient stock" };',
          '  }',
          '',
          '  return {',
          '    ok: true,',
          '    nextStock: { ...stock, [item]: stock[item] - quantity },',
          '    message: `sold ${quantity} ${item}`,',
          '  };',
          '}',
          '',
          '// ...and a thin shell that performs it',
          'function checkout(item, quantity) {',
          '  const decision = decideCheckout(stock, item, quantity);',
          '',
          '  if (!decision.ok) {',
          '    log.push(`rejected ${item}: ${decision.reason}`);',
          '    return false;',
          '  }',
          '',
          '  stock = decision.nextStock;',
          '  log.push(decision.message);',
          '  return true;',
          '}',
          '',
          '// The decision is testable with plain values, no setup at all',
          'console.log("pure ok  :", decideCheckout({ pear: 5 }, "pear", 2));',
          'console.log("pure fail:", decideCheckout({ pear: 1 }, "pear", 2));',
          '',
          'console.log("effect   :", checkout("apple", 1), stock, log);',
        ].join('\n'),
        output: [
          'pure ok  : {ok: true, nextStock: {pear: 3}, message: "sold 2 pear"}',
          'pure fail: {ok: false, reason: "insufficient stock"}',
          'effect   : true {apple: 1} ["sold 1 apple"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The rules moved into a function you can test by calling it',
        body: [
          'Every business rule now lives in `decideCheckout`, which takes values and returns values — no stock module to reset between tests, no log to inspect, no mocking. The two `console.log` lines above **are** its test suite in miniature.',
          '`checkout` still mutates and logs, because something must. But it contains no decisions, so it is short, obviously correct, and rarely changes.',
          'This is Module 28\'s "push effects to the edges" stated in functional terms, and it is the single most valuable idea in this module.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '"use strict";',
          '',
          'function process(items) {',
          '  items.sort();',
          '  return items.length;',
          '}',
          '',
          'const data = ["c", "a"];',
          'const count = process(data);',
          '',
          'console.log(count, data);',
        ].join('\n'),
        options: [
          '2 ["a", "c"] — the caller\'s array was mutated',
          '2 ["c", "a"]',
          '2 undefined',
          'It throws',
        ],
        correct: 0,
        explanation:
          '`Array.prototype.sort` sorts **in place**, so `process` mutated the array its caller passed in — the returned count is correct, but `data` is now reordered and nothing at the call site suggests that. This is the most common accidental impurity in JavaScript, because `sort`, `reverse`, `push`, `splice` and `fill` all mutate while `map`, `filter` and `slice` do not. Copy first — `[...items].sort()` — or use `toSorted()` where available. The tell is that a function taking an object or array and returning something unrelated has an excellent chance of mutating it.',
      },
    ],
    exercises: [
      {
        id: 'ex-m37-01-a',
        title: 'Is this pure?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['functional'],
        instructions:
          'A function creates a local array, sorts it, and returns it. Is it pure?',
        options: [
          'No — it calls a mutating method',
          'Yes — the mutation is of a local value nothing outside can observe',
          'No — sorting is a side effect',
          'Only if it uses toSorted',
        ],
        correct: 1,
        hints: [
          'Can any caller detect that the mutation happened?',
        ],
        solution: 'Yes — the mutation is of a local value nothing outside can observe',
        solutionExplanation:
          'Purity is about **observable** behaviour at the function boundary: same inputs give the same output, and nothing outside changes. Mutating an array the function itself created satisfies both, because no caller holds a reference to it. This is worth being clear about, since "functional" is often mistaken for "never mutate or loop" — the style inside is irrelevant. Sorting an array the **caller** passed in would be a genuine side effect.',
      },
      {
        id: 'ex-m37-01-b',
        title: 'Make it pure',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['functional'],
        instructions:
          'Rewrite `applyDiscount(order)` so it neither mutates its argument nor reads outside state. It should take `(order, rate)` and return a new order with `total` reduced by that rate.',
        starterCode: [
          'const discountRate = 0.1;   // outside state — do not read it',
          '',
          'function applyDiscount(order) {',
          '  // order.total *= (1 - discountRate);  <- mutates and reads outside',
          '}',
        ].join('\n'),
        tests: [
          { name: 'applies the discount', body: 'expect(applyDiscount({ total: 100 }, 0.1).total).toBe(90);' },
          { name: 'does not mutate the input', body: 'const o = { total: 100 }; applyDiscount(o, 0.1); expect(o.total).toBe(100);' },
          { name: 'returns a new object', body: 'const o = { total: 100 }; expect(applyDiscount(o, 0.1) === o).toBe(false);' },
          { name: 'preserves other fields', body: 'expect(applyDiscount({ total: 100, id: 7 }, 0.5).id).toBe(7);' },
          { name: 'uses the supplied rate', body: 'expect(applyDiscount({ total: 100 }, 0.25).total).toBe(75);' },
          { name: 'is repeatable', body: 'const o = { total: 100 }; expect([applyDiscount(o, 0.1).total, applyDiscount(o, 0.1).total]).toEqual([90, 90]);' },
          { name: 'handles a zero rate', body: 'expect(applyDiscount({ total: 100 }, 0).total).toBe(100);', hidden: true },
        ],
        hints: [
          'Take the rate as a second parameter.',
          'Spread the order into a new object.',
          'Override `total` after the spread.',
        ],
        solution: [
          'function applyDiscount(order, rate) {',
          '  return {',
          '    ...order,',
          '    total: order.total * (1 - rate),',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Two changes make it pure. Taking `rate` as a **parameter** removes the hidden dependency on module state, so the result depends only on the arguments — which is what makes the sixth test give the same answer twice regardless of what else the program did. Spreading into a new object leaves the caller\'s order untouched (second test) while preserving sibling fields, since the spread comes before the override. A rate of `0` works without a special case because the arithmetic already handles it.',
      },
      {
        id: 'ex-m37-01-c',
        title: 'Separate decision from effect',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['functional'],
        instructions:
          'Write a **pure** `decideRetry(attempt, maxAttempts, status)` returning `{ retry: true, delay }` when the status is 500 or above and attempts remain (delay is `attempt * 1000`), `{ retry: false, reason }` otherwise. Reasons: `"client error"` for status below 500, `"attempts exhausted"` when none remain.',
        starterCode: [
          'function decideRetry(attempt, maxAttempts, status) {',
          '  // No timers, no logging, no randomness. Values in, values out.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'retries a server error', body: 'expect(decideRetry(1, 3, 500)).toEqual({ retry: true, delay: 1000 });' },
          { name: 'scales the delay', body: 'expect(decideRetry(2, 3, 503).delay).toBe(2000);' },
          { name: 'does not retry a client error', body: 'expect(decideRetry(1, 3, 404)).toEqual({ retry: false, reason: "client error" });' },
          { name: 'stops when attempts are exhausted', body: 'expect(decideRetry(3, 3, 500)).toEqual({ retry: false, reason: "attempts exhausted" });' },
          { name: 'checks the status before the attempt count', body: 'expect(decideRetry(3, 3, 404).reason).toBe("client error");' },
          { name: 'is repeatable', body: 'expect(decideRetry(1, 3, 500)).toEqual(decideRetry(1, 3, 500));' },
          { name: 'treats 200 as a client-side non-retry', body: 'expect(decideRetry(1, 3, 200).retry).toBe(false);', hidden: true },
        ],
        hints: [
          'Check the status first, then the attempt count.',
          'Attempts remain while `attempt < maxAttempts`.',
          'Return plain objects — no side effects anywhere.',
        ],
        solution: [
          'function decideRetry(attempt, maxAttempts, status) {',
          '  if (status < 500) {',
          '    return { retry: false, reason: "client error" };',
          '  }',
          '',
          '  if (attempt >= maxAttempts) {',
          '    return { retry: false, reason: "attempts exhausted" };',
          '  }',
          '',
          '  return { retry: true, delay: attempt * 1000 };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Every input the decision depends on is a **parameter** — no clock, no counter, no configuration read from elsewhere — so the whole retry policy is testable by calling it with numbers, which is exactly what these seven tests do with no setup at all. Checking the status **before** the attempt count is what makes the fifth test pass, and it is the right precedence: a 404 will never succeed however many attempts remain. The real `retry()` function would call this, then perform the waiting and the request — the decision stays pure, the effects stay in the shell.',
      },
      {
        id: 'ex-m37-01-d',
        title: 'Are side effects bad?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['functional'],
        instructions:
          'What is the correct goal regarding side effects in an application?',
        options: [
          'Eliminate them entirely',
          'Contain them at the edges, keeping the decisions underneath pure',
          'Use them freely — purity is academic',
          'Replace them all with promises',
        ],
        correct: 1,
        hints: [
          'What would a program with no side effects actually do?',
        ],
        solution: 'Contain them at the edges, keeping the decisions underneath pure',
        solutionExplanation:
          'A program with no side effects renders nothing, saves nothing and sends nothing — effects are the reason applications exist. The goal is to keep the network, DOM, storage, clock and mutation in a thin outer layer, with the **decisions** in pure functions underneath that can be tested by calling them with values. Purity is also not a moral property: `addToCart` must change the cart. What matters is that the effect is identifiable and that *what* to add is separable from the act of adding.',
      },
    ],
    quiz: {
      id: 'qz-m37-01',
      questions: [
        {
          id: 'q-m37-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functional'],
          prompt: 'What are the two requirements for a function to be pure?',
          options: [
            'It must be short and use arrow syntax',
            'Same inputs always give the same output, and it causes no externally observable change',
            'It must not use loops or reassign variables',
            'It must return an object',
          ],
          correct: 1,
          optionExplanations: [
            'Style is irrelevant.',
            'Correct — both halves are required.',
            'Local mutation is fine.',
            'Return type does not matter.',
          ],
          explanation:
            'Both halves are needed: a consistent function that writes to a database is impure, and so is a side-effect-free function returning `Math.random()`.',
        },
        {
          id: 'q-m37-01-2',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['functional'],
          prompt: 'Mutating a function\'s argument is a side effect.',
          options: ['True', 'False'],
          correct: 0,
          optionExplanations: [
            'Correct — the caller\'s object changed.',
            'The caller can observe it.',
          ],
          explanation:
            'The caller holds that object, so the change is externally observable — and nothing at the call site suggests it. Return a new object instead.',
        },
        {
          id: 'q-m37-01-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functional'],
          prompt: 'What is referential transparency?',
          options: [
            'Being able to see a function\'s source',
            'A call can be replaced by its result without changing the program',
            'Passing arguments by reference',
            'Using const everywhere',
          ],
          correct: 1,
          optionExplanations: [
            'Unrelated to visibility.',
            'Correct — what makes memoisation safe.',
            'A different concept entirely.',
            'Declaration style is unrelated.',
          ],
          explanation:
            'A pure call and its result are interchangeable, which is what makes memoisation safe and lets calls be reordered or skipped.',
        },
        {
          id: 'q-m37-01-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functional'],
          prompt: 'How do you make a function that reads the clock pure?',
          options: [
            'Cache the time',
            'Take the current time as a parameter',
            'Use a Date object',
            'You cannot',
          ],
          correct: 1,
          optionExplanations: [
            'Caching hides the dependency.',
            'Correct — make the hidden dependency an argument.',
            'Still reads the clock.',
            'Parameterising works.',
          ],
          explanation:
            'Turn the hidden dependency into an argument: `isExpiredAt(date, now)` is pure and testable, while the caller supplies `Date.now()` at the edge.',
        },
      ],
    },
    summary:
      'A function is **pure** when the same inputs always produce the same output **and** it causes no externally observable change — both halves are required. **Mutating an argument is a side effect**, since the caller holds that object and nothing at the call site warns them; `sort`, `reverse`, `push` and `splice` mutate in place, which is the most common accidental impurity in JavaScript. But **local mutation is not** a side effect: sorting an array the function created is invisible to callers, so purity is about **observable behaviour at the boundary**, not about avoiding loops or reassignment. The recurring technique for the clock, randomness and configuration is the same — **make the hidden dependency a parameter**, so `isExpiredAt(date, now)` is pure and the caller supplies `Date.now()` at the edge. **Referential transparency** is the resulting property that a call can be replaced by its result, which is what makes memoisation safe and calls reorderable. Crucially, **"good code has no side effects" is nonsense**: a program without them renders, saves and sends nothing. The goal is to **contain effects at the edges** and keep the decisions underneath pure — as `decideCheckout` showed, moving every business rule into a function testable with plain values and leaving a thin shell that only performs. Purity is not a moral property; identifiability and separability are what matter.',
    keyTakeaways: [
      'Pure means same output for same inputs AND no observable change',
      'Mutating an argument is a side effect; mutating a local value is not',
      'sort, reverse, push and splice mutate — copy first',
      'Turn hidden dependencies (clock, config, randomness) into parameters',
      'Referential transparency is what makes memoisation safe',
      'Contain effects at the edges — do not try to eliminate them',
    ],
    relatedLessons: ['l-m37-02', 'l-m37-03'],
    interviewConnections: [
      'What makes a function pure?',
      'Is mutating an argument a side effect?',
      'What is referential transparency?',
      'Should code avoid side effects entirely?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m37-02',
    slug: 'composition-and-pipelines',
    moduleId: M,
    order: 2,
    title: 'Composition and Pipelines',
    description: 'Building behaviour by combining small functions, and when a pipeline beats a loop.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 17,
    xp: 45,
    topicIds: ['functional', 'higher-order'],
    prerequisites: ['l-m37-01'],
    learningObjectives: [
      'Compose functions with compose and pipe',
      'Build readable data pipelines',
      'Compare declarative and imperative styles honestly',
      'Recognise where a pipeline is the wrong choice',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Composition',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Combining two functions into one.',
        code: [
          '"use strict";',
          '',
          'const compose = (f, g) => (value) => f(g(value));',
          '',
          'const trim = (s) => s.trim();',
          'const lower = (s) => s.toLowerCase();',
          '',
          '// compose applies RIGHT to left: trim first, then lower',
          'const normalise = compose(lower, trim);',
          '',
          'console.log("composed:", normalise("  Hello World  "));',
          '',
          '// pipe applies LEFT to right — usually easier to read',
          'const pipe = (...fns) => (value) => fns.reduce((acc, fn) => fn(acc), value);',
          '',
          'const slugify = pipe(',
          '  (s) => s.trim(),',
          '  (s) => s.toLowerCase(),',
          '  (s) => s.replaceAll(" ", "-"),',
          ');',
          '',
          'console.log("piped   :", slugify("  Hello World  "));',
          '',
          '// The order genuinely matters',
          'const wrongOrder = pipe(',
          '  (s) => s.replaceAll(" ", "-"),',
          '  (s) => s.trim(),',
          ');',
          '',
          'console.log("wrong   :", JSON.stringify(wrongOrder("  a b  ")));',
        ].join('\n'),
        output: [
          'composed: hello world',
          'piped   : hello-world',
          'wrong   : "--a-b--"',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: '`compose` reads right to left; `pipe` reads left to right',
        body: [
          '`compose(f, g)(x)` is `f(g(x))` — the mathematical convention, and the reason it runs backwards relative to how it is written. `pipe(f, g)(x)` is `g(f(x))`, matching reading order.',
          'Prefer **`pipe`** unless you have a reason not to. `compose(lower, trim)` requires the reader to work backwards; `pipe(trim, lower)` says what happens in order.',
          'The last example is a reminder that these are not interchangeable steps: trimming after replacing spaces leaves the hyphens the replacement just created.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Composition needs single-argument functions.',
        code: [
          '"use strict";',
          '',
          'const pipe = (...fns) => (value) => fns.reduce((acc, fn) => fn(acc), value);',
          '',
          '// A two-argument function cannot go in a pipeline directly...',
          'const multiply = (a, b) => a * b;',
          '',
          '// ...but a factory returning a one-argument function can (Module 32)',
          'const multiplyBy = (factor) => (n) => n * factor;',
          'const add = (amount) => (n) => n + amount;',
          '',
          'const price = pipe(',
          '  multiplyBy(1.2),   // add tax',
          '  add(5),            // shipping',
          '  Math.round,        // built-ins work too, if unary',
          ');',
          '',
          'console.log("price:", price(100));',
          '',
          '// Each step is independently usable and testable',
          'console.log("tax  :", multiplyBy(1.2)(50));',
          'console.log("mapped:", [10, 20].map(multiplyBy(2)));',
        ].join('\n'),
        output: [
          'price: 125',
          'tax  : 60',
          'mapped: [20, 40]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Beware passing built-in methods into a pipeline',
        body: [
          '`Math.round` works because it is a genuine unary function that ignores `this`. But `pipe(s => s.trim, ...)` or `[1,2].map(obj.method)` lose their receiver — Module 29\'s lost-`this` problem, which pipelines make easy to hit.',
          'Another classic: `["1","2","3"].map(parseInt)` gives `[1, NaN, NaN]`, because `map` passes the index as a second argument and `parseInt` reads it as a radix. Wrap explicitly — `map(s => parseInt(s, 10))` or `map(Number)` — when a function takes more arguments than you are supplying.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Data pipelines',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A realistic transformation.',
        code: [
          '"use strict";',
          '',
          'const orders = [',
          '  { id: 1, status: "paid", total: 120, customer: "ada" },',
          '  { id: 2, status: "pending", total: 90, customer: "bo" },',
          '  { id: 3, status: "paid", total: 40, customer: "ada" },',
          '  { id: 4, status: "paid", total: 200, customer: "cy" },',
          '];',
          '',
          '// Each step names what it does',
          'const paid = orders.filter((o) => o.status === "paid");',
          'const totals = paid.map((o) => ({ customer: o.customer, total: o.total }));',
          '',
          'const byCustomer = totals.reduce((acc, { customer, total }) => {',
          '  acc[customer] = (acc[customer] ?? 0) + total;',
          '  return acc;',
          '}, {});',
          '',
          'console.log("by customer:", byCustomer);',
          '',
          'const ranked = Object.entries(byCustomer)',
          '  .map(([customer, total]) => ({ customer, total }))',
          '  .sort((a, b) => b.total - a.total);',
          '',
          'console.log("ranked     :", ranked);',
          '',
          '// The source is untouched throughout',
          'console.log("original   :", orders.length, orders[0].status);',
        ].join('\n'),
        output: [
          'by customer: {ada: 160, cy: 200}',
          'ranked     : [{customer: "cy", total: 200}, {customer: "ada", total: 160}]',
          'original   : 4 paid',
        ].join('\n'),
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Imperative',
          code: [
            'const totals = {};',
            '',
            'for (const o of orders) {',
            '  if (o.status !== "paid") {',
            '    continue;',
            '  }',
            '',
            '  totals[o.customer] =',
            '    (totals[o.customer] ?? 0)',
            '    + o.total;',
            '}',
          ].join('\n'),
        },
        right: {
          title: 'Declarative',
          code: [
            'const totals = orders',
            '  .filter(o =>',
            '    o.status === "paid")',
            '  .reduce((acc, o) => ({',
            '    ...acc,',
            '    [o.customer]:',
            '      (acc[o.customer] ?? 0)',
            '      + o.total,',
            '  }), {});',
          ].join('\n'),
        },
        note: 'Neither is universally better. The loop is one pass and easy to step through in a debugger; the pipeline names each stage and never mutates. Note the declarative version here spreads on **every iteration**, which is O(n²) — a real cost for large inputs that the loop does not have. Mutating a local accumulator inside `reduce` is both faster and still pure by lesson 1\'s definition.',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Do not spread inside a reduce accumulator',
        body: [
          '`{ ...acc, [key]: value }` copies the whole accumulator on every element, so a 10,000-item reduce performs 10,000 progressively larger copies. It looks purer and is quadratic.',
          'The accumulator is **local to the reduce**, so mutating it is invisible to callers — pure by the definition that matters. Write `acc[key] = value; return acc;` and keep the immutability at the boundary, where it counts.',
          'This is the single most common performance mistake in "functional" JavaScript, and it is usually made in pursuit of a purity the code already had.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'When a pipeline is the wrong choice',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Multiple passes, and early exit.',
        code: [
          '"use strict";',
          '',
          'const numbers = [1, 2, 3, 4, 5, 6, 7, 8];',
          'let inspected = 0;',
          '',
          'const track = (n) => { inspected += 1; return n; };',
          '',
          '// A pipeline processes every element at every stage',
          'const chained = numbers.map(track).filter((n) => n > 6);',
          'console.log("chained  :", chained, "| inspected:", inspected);',
          '',
          '// find stops at the first match',
          'inspected = 0;',
          'const found = numbers.find((n) => { inspected += 1; return n > 6; });',
          'console.log("find     :", found, "| inspected:", inspected);',
          '',
          '// some and every also short-circuit',
          'inspected = 0;',
          'numbers.some((n) => { inspected += 1; return n > 2; });',
          'console.log("some     : inspected:", inspected);',
        ].join('\n'),
        output: [
          'chained  : [7, 8] | inspected: 8',
          'find     : 7 | inspected: 7',
          'some     : inspected: 3',
        ].join('\n'),
      },
      {
        kind: SECTION.LIST,
        items: [
          '**You need to stop early.** `map`/`filter` always process everything; `find`, `some`, `every` and a plain loop can exit. A `for` loop with `break` is the clearest option when the exit condition is complex.',
          '**Each stage allocates a new array.** Three chained stages over a large array build three intermediate arrays. Usually irrelevant, occasionally not — a generator pipeline (Module 35) avoids it entirely.',
          '**The steps are genuinely interdependent.** When each stage needs state from the last, a loop expresses that honestly where a `reduce` carrying a tuple does not.',
          '**Async work is involved.** `array.map(async fn)` gives an array of **promises**, not results — `await Promise.all(array.map(fn))` is the fix, as Module 25 covered.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Choose for the reader',
        body: [
          'The honest case for pipelines is **readability**: each stage is named, nothing mutates, and the shape of the transformation is visible at a glance. That is a real benefit and usually the deciding one.',
          'The dishonest case is that pipelines are inherently better. A three-stage chain to do what one loop does clearly is not an improvement, and a `reduce` that would be a loop with an accumulator is often less readable than the loop.',
          'A useful test: if you must read the chain twice to work out what it produces, write the loop.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const pipe = (...fns) => (x) => fns.reduce((acc, fn) => fn(acc), x);',
          '',
          'const double = (n) => n * 2;',
          'const addOne = (n) => n + 1;',
          '',
          'const compose = (f, g) => (x) => f(g(x));',
          '',
          'console.log(pipe(double, addOne)(5), compose(double, addOne)(5));',
        ].join('\n'),
        options: [
          '11 12',
          '12 11',
          '11 11',
          '12 12',
        ],
        correct: 0,
        explanation:
          '`pipe` applies **left to right**: `double(5)` is `10`, then `addOne(10)` is `11`. `compose(f, g)(x)` is defined as `f(g(x))`, so it applies **right to left**: `addOne(5)` is `6`, then `double(6)` is `12`. Same two functions, same order in the source, different results — which is exactly why mixing the two conventions in one codebase causes bugs. `compose` follows the mathematical convention; `pipe` matches reading order, which is why most JavaScript codebases prefer it.',
      },
    ],
    exercises: [
      {
        id: 'ex-m37-02-a',
        title: 'Implement pipe',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['functional', 'higher-order'],
        instructions:
          'Write `pipe(...fns)` returning a function that applies each function left to right to its argument.',
        starterCode: [
          'function pipe(...fns) {',
          '  // Left to right.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'applies two functions in order', body: 'expect(pipe((n) => n * 2, (n) => n + 1)(5)).toBe(11);' },
          { name: 'applies three', body: 'expect(pipe((n) => n + 1, (n) => n * 2, (n) => n - 3)(4)).toBe(7);' },
          { name: 'works with one function', body: 'expect(pipe((n) => n * 3)(4)).toBe(12);' },
          { name: 'returns the input when given no functions', body: 'expect(pipe()(9)).toBe(9);' },
          { name: 'works with strings', body: 'expect(pipe((s) => s.trim(), (s) => s.toUpperCase())("  hi ")).toBe("HI");' },
          { name: 'is reusable', body: 'const f = pipe((n) => n + 1); expect([f(1), f(2)]).toEqual([2, 3]);' },
          { name: 'preserves a falsy result', body: 'expect(pipe((n) => n - 1)(1)).toBe(0);', hidden: true },
        ],
        hints: [
          'Return a function taking the initial value.',
          '`reduce` over the functions, threading the value through.',
          'The initial accumulator is the input value.',
        ],
        solution: [
          'function pipe(...fns) {',
          '  return (value) => fns.reduce((accumulator, fn) => fn(accumulator), value);',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`reduce` threads the value through each function in turn, with the input as the starting accumulator — which is why the empty case returns the input unchanged with no special handling. Returning the reduced value directly preserves a falsy result such as `0`, which the hidden test checks; a `||` fallback anywhere would have corrupted it. Each call to the returned function starts from its own argument, so the pipeline is reusable rather than stateful.',
      },
      {
        id: 'ex-m37-02-b',
        title: 'Build a data pipeline',
        kind: EXERCISE_KIND.TRANSFORM_DATA,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['functional'],
        instructions:
          'Write `topCustomers(orders, limit)` returning the top `limit` customers by total of their **paid** orders, as `{ customer, total }` sorted descending. Do not mutate the input.',
        starterCode: [
          'function topCustomers(orders, limit) {',
          '  // filter, total per customer, sort, take.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'totals per customer', body: 'expect(topCustomers([{ status: "paid", customer: "a", total: 10 }, { status: "paid", customer: "a", total: 5 }], 1)).toEqual([{ customer: "a", total: 15 }]);' },
          { name: 'ignores unpaid orders', body: 'expect(topCustomers([{ status: "pending", customer: "a", total: 99 }, { status: "paid", customer: "b", total: 1 }], 2)).toEqual([{ customer: "b", total: 1 }]);' },
          { name: 'sorts descending', body: 'expect(topCustomers([{ status: "paid", customer: "a", total: 1 }, { status: "paid", customer: "b", total: 9 }], 2).map((x) => x.customer)).toEqual(["b", "a"]);' },
          { name: 'honours the limit', body: 'expect(topCustomers([{ status: "paid", customer: "a", total: 3 }, { status: "paid", customer: "b", total: 2 }, { status: "paid", customer: "c", total: 1 }], 2).length).toBe(2);' },
          { name: 'handles an empty list', body: 'expect(topCustomers([], 3)).toEqual([]);' },
          { name: 'does not mutate the input', body: 'const o = [{ status: "paid", customer: "a", total: 1 }]; topCustomers(o, 1); expect(o.length).toBe(1);' },
          { name: 'handles a limit larger than the data', body: 'expect(topCustomers([{ status: "paid", customer: "a", total: 1 }], 10).length).toBe(1);', hidden: true },
        ],
        hints: [
          '`filter` for paid, then `reduce` into an object of totals.',
          '`Object.entries` converts that to pairs you can map and sort.',
          '`slice(0, limit)` takes the top — and never overruns.',
        ],
        solution: [
          'function topCustomers(orders, limit) {',
          '  const totals = orders',
          '    .filter((order) => order.status === "paid")',
          '    .reduce((acc, order) => {',
          '      acc[order.customer] = (acc[order.customer] ?? 0) + order.total;',
          '      return acc;',
          '    }, {});',
          '',
          '  return Object.entries(totals)',
          '    .map(([customer, total]) => ({ customer, total }))',
          '    .sort((a, b) => b.total - a.total)',
          '    .slice(0, limit);',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Mutating `acc` inside the `reduce` is deliberate and correct: the accumulator is created by the reduce and never escapes, so it is pure by lesson 1\'s definition — spreading it each iteration would be quadratic for no benefit. `sort` mutates, but it acts on the fresh array `map` just produced, never on the input, which is what the sixth test checks. `slice` handles a limit larger than the data without a guard, and the empty case falls out naturally since every stage handles an empty array.',
      },
      {
        id: 'ex-m37-02-c',
        title: 'Why not spread in reduce?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.HARD,
        xp: 25,
        topicIds: ['functional'],
        instructions:
          'Why is `reduce((acc, x) => ({ ...acc, [x.id]: x }), {})` a poor choice for a large array?',
        options: [
          'It is impure',
          'It copies the entire accumulator on every element, making the reduce quadratic',
          'Spread does not work on objects',
          'reduce cannot return an object',
        ],
        correct: 1,
        hints: [
          'How much work does the spread do on the last element?',
        ],
        solution: 'It copies the entire accumulator on every element, making the reduce quadratic',
        solutionExplanation:
          'Each spread copies everything accumulated so far, so processing `n` items performs roughly `n²/2` property copies — for 10,000 items that is tens of millions. The irony is that it is done in pursuit of purity the code already had: the accumulator is created **by** the reduce and never escapes, so mutating it with `acc[x.id] = x; return acc;` is invisible to callers and pure by the definition that matters. Keep immutability at the **boundary**, where it protects callers, not inside a local loop.',
      },
      {
        id: 'ex-m37-02-d',
        title: 'Pipeline or loop?',
        kind: EXERCISE_KIND.CHOOSE_IMPLEMENTATION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['functional'],
        instructions:
          'You need the first user in a large array matching a complex condition, and you want to stop searching once found. Pipeline or loop?',
        options: [
          'filter then take the first element',
          'find, or a loop with break — both stop at the first match',
          'map then filter',
          'reduce',
        ],
        correct: 1,
        hints: [
          'Which options process the whole array?',
        ],
        solution: 'find, or a loop with break — both stop at the first match',
        solutionExplanation:
          '`filter` always processes **every** element and builds a whole array before you discard all but one — wasteful on a large input, and misleading about intent. `find` short-circuits at the first match, as do `some` and `every`; a `for` loop with `break` does the same and is clearer when the condition is complex enough to need several statements. This is the main honest limitation of pipelines: `map` and `filter` cannot stop early.',
      },
    ],
    quiz: {
      id: 'qz-m37-02',
      questions: [
        {
          id: 'q-m37-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functional'],
          prompt: 'What is compose(f, g)(x)?',
          options: ['g(f(x))', 'f(g(x))', 'f(x) + g(x)', 'An array of results'],
          correct: 1,
          optionExplanations: [
            'That is pipe.',
            'Correct — right to left.',
            'Not a combination of results.',
            'It returns one value.',
          ],
          explanation:
            '`compose` follows the mathematical convention and applies right to left, while `pipe` applies left to right — matching reading order, which is why most JavaScript codebases prefer it.',
        },
        {
          id: 'q-m37-02-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functional'],
          prompt: 'Why do pipeline steps need to be unary?',
          options: [
            'It is a style rule',
            'Each step receives exactly one value — the previous result',
            'Multi-argument functions are slower',
            'reduce only accepts unary functions',
          ],
          correct: 1,
          optionExplanations: [
            'It follows from the mechanism.',
            'Correct — use a factory to pre-fill the rest.',
            'Speed is unrelated.',
            'reduce accepts any function.',
          ],
          explanation:
            'A pipeline threads one value through each stage, so multi-argument functions must be turned into unary ones — usually with a factory such as `multiplyBy(1.2)`.',
        },
        {
          id: 'q-m37-02-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['functional'],
          prompt: 'map and filter can stop early once a result is found.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'They always process every element.',
            'Correct — use find, some, every or a loop.',
          ],
          explanation:
            'They process the whole array by definition. `find`, `some` and `every` short-circuit, as does a `for` loop with `break`.',
        },
        {
          id: 'q-m37-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functional'],
          prompt: 'What does ["1","2","3"].map(parseInt) produce?',
          options: [
            '[1, 2, 3]',
            '[1, NaN, NaN] — map passes the index, which parseInt reads as a radix',
            'A TypeError',
            '["1","2","3"]',
          ],
          correct: 1,
          optionExplanations: [
            'The index interferes.',
            'Correct — wrap explicitly.',
            'No error is thrown.',
            'Conversion is attempted.',
          ],
          explanation:
            '`map` passes `(value, index, array)`, and `parseInt` treats the second argument as a radix — so radix 1 and 2 fail. Use `map(Number)` or `map(s => parseInt(s, 10))`.',
        },
      ],
    },
    summary:
      '**`compose(f, g)(x)`** is `f(g(x))` — right to left, the mathematical convention — while **`pipe(f, g)(x)`** is `g(f(x))`, matching reading order; prefer `pipe`, and never mix the two conventions in one codebase. Pipeline stages must be **unary**, since each receives only the previous result, so multi-argument functions become pipeline-ready through a **factory** like `multiplyBy(1.2)` — a closure, from Module 32. Watch two traps when passing functions directly: a detached method loses its receiver (Module 29), and `map(parseInt)` gives `[1, NaN, NaN]` because `map` supplies the index as a radix. For **data pipelines**, name each stage and never mutate the input — but **do not spread inside a `reduce` accumulator**: it copies everything accumulated so far on every element, making the operation **quadratic**, and it is done in pursuit of a purity the code already had, since the accumulator never escapes the reduce. Mutating it locally is both faster and pure by lesson 1\'s definition; keep immutability at the **boundary**. A pipeline is the wrong choice when you need to **stop early** (`map`/`filter` always process everything — use `find`, `some`, `every` or a loop with `break`), when intermediate allocations matter, when stages are genuinely interdependent, or when async work is involved (`map(async fn)` yields promises, so `await Promise.all(...)`). The honest case for pipelines is **readability** — and if you must read a chain twice to see what it produces, write the loop.',
    keyTakeaways: [
      'compose runs right to left; pipe runs left to right — prefer pipe',
      'Pipeline stages are unary; use a factory to pre-fill other arguments',
      'map(parseInt) fails because map passes the index as a radix',
      'Never spread inside a reduce accumulator — it is quadratic and needless',
      'map and filter cannot stop early; find, some, every and loops can',
      'Choose for the reader — a chain read twice should have been a loop',
    ],
    relatedLessons: ['l-m37-01', 'l-m37-03'],
    interviewConnections: [
      'What is the difference between compose and pipe?',
      'Why is spreading inside reduce a problem?',
      'When is a for loop better than a chain of array methods?',
      'Why does map(parseInt) not work?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m37-03',
    slug: 'currying-and-partial-application',
    moduleId: M,
    order: 3,
    title: 'Currying and Partial Application',
    description: 'Two related but distinct techniques — and honest limits on where they help.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 16,
    xp: 45,
    topicIds: ['functional', 'higher-order'],
    prerequisites: ['l-m37-02'],
    learningObjectives: [
      'Define currying precisely and distinguish it from partial application',
      'Implement a curry helper',
      'Use partial application with closures and bind',
      'Judge when these techniques earn their cost',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Currying',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Transforming f(a, b, c) into f(a)(b)(c).',
        code: [
          '"use strict";',
          '',
          '// An ordinary three-argument function',
          'const volume = (l, w, h) => l * w * h;',
          '',
          '// The curried form: one argument at a time, always',
          'const curriedVolume = (l) => (w) => (h) => l * w * h;',
          '',
          'console.log("normal :", volume(2, 3, 4));',
          'console.log("curried:", curriedVolume(2)(3)(4));',
          '',
          '// Each call returns a function until the last',
          'const withLength = curriedVolume(2);',
          'const withWidth = withLength(3);',
          '',
          'console.log("partial:", typeof withLength, typeof withWidth);',
          'console.log("final  :", withWidth(4), withWidth(10));',
        ].join('\n'),
        output: [
          'normal : 24',
          'curried: 24',
          'partial: function function',
          'final  : 24 60',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Not every nested arrow is currying',
        body: [
          '**Currying** is specifically the transformation of an n-argument function into a chain of n functions each taking **exactly one** argument. `f(a, b, c)` becomes `f(a)(b)(c)`.',
          'A function returning a function is not automatically curried. `createMultiplier(factor)` returning `(n) => n * factor` is a **factory** — a closure that configures behaviour. It looks similar and is a different idea.',
          'The distinction matters mainly because the terms get used loosely. What actually matters in practice is the *result*: a function that takes fewer arguments and is therefore easy to compose or pass to `map`.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A curry helper that accepts arguments flexibly.',
        code: [
          '"use strict";',
          '',
          'function curry(fn) {',
          '  return function curried(...args) {',
          '    // Enough arguments? Call it.',
          '    if (args.length >= fn.length) {',
          '      return fn(...args);',
          '    }',
          '',
          '    // Otherwise return a function collecting more',
          '    return (...rest) => curried(...args, ...rest);',
          '  };',
          '}',
          '',
          'const volume = curry((l, w, h) => l * w * h);',
          '',
          '// Every grouping works',
          'console.log("all at once:", volume(2, 3, 4));',
          'console.log("one by one :", volume(2)(3)(4));',
          'console.log("mixed      :", volume(2, 3)(4));',
          'console.log("mixed      :", volume(2)(3, 4));',
          '',
          '// fn.length is what drives this — it counts declared parameters',
          'console.log("arity      :", ((a, b, c) => 0).length);',
          'console.log("with rest  :", ((a, ...rest) => 0).length);',
          'console.log("with default:", ((a, b = 1) => 0).length);',
        ].join('\n'),
        output: [
          'all at once: 24',
          'one by one : 24',
          'mixed      : 24',
          'mixed      : 24',
          'arity      : 3',
          'with rest  : 1',
          'with default: 1',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: '`fn.length` stops counting at a default or rest parameter',
        body: [
          'A curry helper relies on `fn.length` to know when it has enough arguments — and that property counts only the parameters **before** the first one with a default value or a rest parameter.',
          'So `curry((a, b = 1) => ...)` believes the function takes **one** argument and calls it immediately after the first. Currying and default parameters do not combine, and the failure is silent.',
          'This is one of several reasons generic curry helpers are less useful in JavaScript than in languages designed around them.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Partial application',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Fixing some arguments, without one-at-a-time chaining.',
        code: [
          '"use strict";',
          '',
          'const multiply = (a, b) => a * b;',
          '',
          '// 1. With a closure — the clearest form',
          'const double = (n) => multiply(2, n);',
          '',
          '// 2. With bind (Module 29) — arguments are prepended',
          'const triple = multiply.bind(null, 3);',
          '',
          '// 3. With a general helper',
          'const partial = (fn, ...fixed) => (...rest) => fn(...fixed, ...rest);',
          'const quadruple = partial(multiply, 4);',
          '',
          'console.log("closure:", double(5));',
          'console.log("bind   :", triple(5));',
          'console.log("partial:", quadruple(5));',
          '',
          '// All three produce a unary function, so all compose',
          'console.log("mapped :", [1, 2, 3].map(double));',
        ].join('\n'),
        output: [
          'closure: 10',
          'bind   : 15',
          'partial: 20',
          'mapped : [2, 4, 6]',
        ].join('\n'),
      },
      {
        kind: SECTION.TABLE,
        headers: ['', 'Currying', 'Partial application'],
        rows: [
          ['Transforms', '`f(a,b,c)` → `f(a)(b)(c)`', '`f(a,b,c)` → `g(b,c)` with `a` fixed'],
          ['Arguments per call', 'Exactly **one**', '**Any number**'],
          ['Result of a call', 'Another unary function, until the last', 'A function taking the remaining arguments'],
          ['Typical tool', 'A `curry` helper', 'A closure, `bind`, or a `partial` helper'],
          ['In practice', 'Rare in JavaScript', '**Common** — often without the name'],
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'You have been doing partial application all along',
        body: [
          '`createMultiplier(2)`, `createValidator(1, 10)`, `makeHandler(store)` — every factory from Module 32 fixes some arguments and returns a function taking the rest. That is partial application, whether or not anyone called it that.',
          'It is genuinely useful because it produces **unary** functions, which is what `map`, `filter` and pipelines need. Currying is the stricter, more formal version, and it is much rarer in real JavaScript code.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Argument order matters',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Design the signature for the argument you will fix.',
        code: [
          '"use strict";',
          '',
          'const partial = (fn, ...fixed) => (...rest) => fn(...fixed, ...rest);',
          '',
          '// Data LAST — the configuration can be fixed, leaving a unary function',
          'const filterBy = (predicate, items) => items.filter(predicate);',
          'const onlyEven = partial(filterBy, (n) => n % 2 === 0);',
          '',
          'console.log("data last:", onlyEven([1, 2, 3, 4]));',
          'console.log("reusable :", onlyEven([10, 11]));',
          '',
          '// Data FIRST — you cannot pre-fill the configuration this way,',
          '// because bound arguments are always prepended',
          'const filterByBad = (items, predicate) => items.filter(predicate);',
          'const attempted = partial(filterByBad, (n) => n % 2 === 0);',
          '',
          'console.log("data first:", (() => {',
          '  try { return attempted([1, 2, 3, 4]); } catch (e) { return e.name; }',
          '})());',
        ].join('\n'),
        output: [
          'data last: [2, 4]',
          'reusable : [10]',
          'data first: TypeError',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: '"Data last" is the convention, and it has a cost',
        body: [
          'Because `bind` and every `partial` helper **prepend** fixed arguments (Module 29), you can only pre-fill from the **left**. So functional libraries put configuration first and data last, making partial application natural.',
          'The `data first` attempt above threw because `filterByBad` received the predicate as `items` and tried to call `.filter` on a function.',
          'The cost is that "data last" reads unnaturally against the rest of JavaScript, where methods put data first — `array.filter(fn)`. Adopting it consistently is a real commitment, and adopting it inconsistently is worse than not adopting it.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'When these techniques earn their cost',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A realistic use, and an over-application.',
        code: [
          '"use strict";',
          '',
          '// GOOD: a configured function used many times',
          'const createLogger = (level, source) => (message) =>',
          '  `[${level}] ${source}: ${message}`;',
          '',
          'const authError = createLogger("ERROR", "auth");',
          '',
          'console.log(authError("token expired"));',
          'console.log(authError("bad password"));',
          '',
          '// GOOD: producing a unary function for a pipeline',
          'const clampTo = (max) => (n) => Math.min(n, max);',
          'console.log("clamped:", [5, 15, 25].map(clampTo(10)));',
          '',
          '// OVER-APPLIED: currying something used once',
          'const addCurried = (a) => (b) => a + b;',
          'console.log("curried once:", addCurried(2)(3));',
          '',
          '// The direct version is clearer and shorter',
          'console.log("direct      :", 2 + 3);',
        ].join('\n'),
        output: [
          '[ERROR] auth: token expired',
          '[ERROR] auth: bad password',
          'clamped: [5, 10, 10]',
          'curried once: 5',
          'direct      : 5',
        ].join('\n'),
      },
      {
        kind: SECTION.LIST,
        items: [
          '**Worth it:** a configured function reused across many call sites — a logger, a validator, a formatter.',
          '**Worth it:** producing a unary function for `map`, `filter` or a pipeline, instead of wrapping in an arrow at every call site.',
          '**Not worth it:** currying a function called once. `f(a)(b)` is strictly harder to read than `f(a, b)`.',
          '**Not worth it:** a generic `curry` helper in a codebase that does not otherwise use functional conventions — it will surprise readers, and it breaks on default and rest parameters.',
          '**Usually clearer:** a plain arrow. `(n) => format(n, "USD")` says exactly what `partial(format, "USD")` does, without a helper.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const partial = (fn, ...fixed) => (...rest) => fn(...fixed, ...rest);',
          '',
          'const divide = (a, b) => a / b;',
          '',
          'const half = partial(divide, 2);',
          '',
          'console.log(half(10));',
        ].join('\n'),
        options: [
          '0.2',
          '5',
          '20',
          'NaN',
        ],
        correct: 0,
        explanation:
          'Fixed arguments are **prepended**, so `half(10)` calls `divide(2, 10)` — that is `2 / 10`, or `0.2`, not `10 / 2`. The name `half` describes what the author intended and not what the code does, which is exactly the trap: partial application can only pre-fill from the **left**, and `divide`\'s first parameter is the numerator. To fix it you must either reorder the parameters (`divide(b, a)`), or simply write a plain arrow: `const half = (n) => divide(n, 2)`. That last option is clearer than any helper and is usually the right answer.',
      },
    ],
    exercises: [
      {
        id: 'ex-m37-03-a',
        title: 'Currying versus partial application',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['functional'],
        instructions:
          'What is the difference between currying and partial application?',
        options: [
          'They are the same thing',
          'Currying turns f(a,b,c) into a chain of one-argument functions; partial application fixes some arguments and returns a function taking the rest',
          'Currying only works with two arguments',
          'Partial application requires bind',
        ],
        correct: 1,
        hints: [
          'How many arguments does each call take?',
        ],
        solution: 'Currying turns f(a,b,c) into a chain of one-argument functions; partial application fixes some arguments and returns a function taking the rest',
        solutionExplanation:
          'Currying is the strict transformation into a chain where **every** call takes exactly one argument — `f(a)(b)(c)`. Partial application is looser: fix any number of arguments now, supply the rest later, in one call. Partial application is far more common in real JavaScript, and every factory from Module 32 is an example. It can be written with a closure, `bind`, or a helper — `bind` is one option, not a requirement.',
      },
      {
        id: 'ex-m37-03-b',
        title: 'Implement curry',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['functional', 'higher-order'],
        instructions:
          'Write `curry(fn)` returning a curried version that accepts arguments one at a time, all at once, or in any grouping. Use `fn.length` to know when enough have arrived.',
        starterCode: [
          'function curry(fn) {',
          '  // Collect arguments until there are enough.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'accepts all arguments at once', body: 'expect(curry((a, b, c) => a + b + c)(1, 2, 3)).toBe(6);' },
          { name: 'accepts one at a time', body: 'expect(curry((a, b, c) => a + b + c)(1)(2)(3)).toBe(6);' },
          { name: 'accepts a mixed grouping', body: 'expect(curry((a, b, c) => a + b + c)(1, 2)(3)).toBe(6);' },
          { name: 'accepts the other grouping', body: 'expect(curry((a, b, c) => a + b + c)(1)(2, 3)).toBe(6);' },
          { name: 'works with two arguments', body: 'expect(curry((a, b) => a * b)(3)(4)).toBe(12);' },
          { name: 'partials are reusable', body: 'const add = curry((a, b) => a + b); const add5 = add(5); expect([add5(1), add5(2)]).toEqual([6, 7]);' },
          { name: 'preserves a falsy result', body: 'expect(curry((a, b) => a * b)(0)(5)).toBe(0);', hidden: true },
        ],
        hints: [
          'Return a named function so it can call itself.',
          'Compare `args.length` with `fn.length`.',
          'When there are too few, return a function that recurses with the combined arguments.',
        ],
        solution: [
          'function curry(fn) {',
          '  return function curried(...args) {',
          '    if (args.length >= fn.length) {',
          '      return fn(...args);',
          '    }',
          '',
          '    return (...rest) => curried(...args, ...rest);',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Naming the inner function lets it call itself with the accumulated arguments, which is what allows any grouping — each partial call captures what it has so far and waits for more. `fn.length` supplies the arity, so the check knows when to stop collecting. The sixth test shows partials are independent: `add(5)` captures its own `args` array, so calling it twice does not accumulate. Note the honest limitation — `fn.length` stops counting at the first default or rest parameter, so `curry((a, b = 1) => ...)` would call through after one argument.',
      },
      {
        id: 'ex-m37-03-c',
        title: 'Design for partial application',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['functional'],
        instructions:
          'Write `formatWith(currency, locale)` returning a function that formats a number as `"<amount to 2dp> <currency> (<locale>)"`. Design it so the returned function is unary and usable with `map`.',
        starterCode: [
          'function formatWith(currency, locale) {',
          '  // Return a function taking only the amount.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'formats an amount', body: 'expect(formatWith("USD", "en")(9.5)).toBe("9.50 USD (en)");' },
          { name: 'rounds to two places', body: 'expect(formatWith("EUR", "de")(1)).toBe("1.00 EUR (de)");' },
          { name: 'the result is unary', body: 'expect(formatWith("USD", "en").length).toBe(1);' },
          { name: 'works with map', body: 'expect([1, 2].map(formatWith("USD", "en"))).toEqual(["1.00 USD (en)", "2.00 USD (en)"]);' },
          { name: 'formatters are independent', body: 'const a = formatWith("USD", "en"); const b = formatWith("EUR", "de"); expect([a(1), b(1)]).toEqual(["1.00 USD (en)", "1.00 EUR (de)"]);' },
          { name: 'is reusable', body: 'const f = formatWith("USD", "en"); expect([f(1), f(2)]).toEqual(["1.00 USD (en)", "2.00 USD (en)"]);' },
          { name: 'handles zero', body: 'expect(formatWith("USD", "en")(0)).toBe("0.00 USD (en)");', hidden: true },
        ],
        hints: [
          'Return an arrow taking one parameter.',
          'It closes over `currency` and `locale`.',
          '`amount.toFixed(2)` gives the two decimal places.',
        ],
        solution: [
          'function formatWith(currency, locale) {',
          '  return (amount) => `${amount.toFixed(2)} ${currency} (${locale})`;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Fixing the configuration and returning a **unary** function is what makes the fourth test work: it can be handed straight to `map` with no wrapper arrow, which a three-argument `format(amount, currency, locale)` could not. The third test checks the arity explicitly — `length` is `1` because the returned arrow declares one parameter. Each call to `formatWith` creates a fresh closure, so formatters never interfere, and `toFixed` handles `0` correctly without a special case.',
      },
      {
        id: 'ex-m37-03-d',
        title: 'When is currying not worth it?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['functional'],
        instructions:
          'When should you NOT curry a function?',
        options: [
          'When it has more than two parameters',
          'When it is called once with all its arguments — f(a)(b) is harder to read than f(a, b)',
          'When it is pure',
          'When it returns an object',
        ],
        correct: 1,
        hints: [
          'What does currying actually buy you?',
        ],
        solution: 'When it is called once with all its arguments — f(a)(b) is harder to read than f(a, b)',
        solutionExplanation:
          'Currying pays off when you genuinely reuse a partially applied form — a configured logger, a formatter passed to `map`. Applied to a function called once with every argument, it adds syntax and indirection for nothing. Two further cautions: a generic `curry` helper surprises readers in a codebase that does not otherwise use functional conventions, and it silently breaks on default or rest parameters because `fn.length` stops counting there. A plain arrow such as `(n) => format(n, "USD")` is often clearer than any helper.',
      },
    ],
    quiz: {
      id: 'qz-m37-03',
      questions: [
        {
          id: 'q-m37-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functional'],
          prompt: 'What does currying transform f(a, b, c) into?',
          options: ['f([a, b, c])', 'f(a)(b)(c)', 'f(c, b, a)', 'An object of functions'],
          correct: 1,
          optionExplanations: [
            'That is taking an array.',
            'Correct — a chain of unary functions.',
            'Order is unchanged.',
            'It returns functions, not an object.',
          ],
          explanation:
            'Currying produces a chain where each call takes exactly one argument. Partial application is the looser cousin that fixes any number at once.',
        },
        {
          id: 'q-m37-03-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functional'],
          prompt: 'Why does a curry helper break on default parameters?',
          options: [
            'Defaults are not supported in arrows',
            'fn.length stops counting at the first parameter with a default, so the helper thinks the arity is smaller',
            'Defaults make the function impure',
            'It does not break',
          ],
          correct: 1,
          optionExplanations: [
            'They work fine in arrows.',
            'Correct — and the failure is silent.',
            'Purity is unrelated.',
            'It genuinely does.',
          ],
          explanation:
            '`fn.length` counts only the parameters before the first default or rest parameter, so `curry((a, b = 1) => ...)` calls through after one argument.',
        },
        {
          id: 'q-m37-03-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['functional'],
          prompt: 'Partial application can pre-fill arguments from either end.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Fixed arguments are prepended.',
            'Correct — from the left only, hence "data last".',
          ],
          explanation:
            '`bind` and every `partial` helper prepend fixed arguments, so you can only pre-fill from the left. That is why functional libraries put configuration first and data last.',
        },
        {
          id: 'q-m37-03-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['functional'],
          prompt: 'What is the practical benefit of partial application?',
          options: [
            'It makes functions faster',
            'It produces unary functions that compose and pass directly to map and filter',
            'It removes the need for parameters',
            'It enforces purity',
          ],
          correct: 1,
          optionExplanations: [
            'Performance is unaffected.',
            'Correct — no wrapper arrow at each call site.',
            'Arguments still arrive, just later.',
            'It does not affect purity.',
          ],
          explanation:
            'A configured unary function can be handed straight to `map` or a pipeline, where a multi-argument function needs a wrapper at every call site.',
        },
      ],
    },
    summary:
      '**Currying** is the strict transformation of `f(a, b, c)` into `f(a)(b)(c)` — a chain where every call takes **exactly one** argument. **Partial application** is looser: fix some arguments now, supply the rest in one later call. Not every nested arrow is currying; a factory like `createMultiplier(factor)` is partial application, and that is by far the more common technique in real JavaScript — every factory from Module 32 is an example. A generic `curry` helper uses **`fn.length`** to know when enough arguments have arrived, which carries a real gotcha: `length` stops counting at the first **default or rest parameter**, so `curry((a, b = 1) => ...)` calls through after one argument, silently. Fixed arguments are always **prepended** — by `bind` and by every `partial` helper — so you can pre-fill only **from the left**, which is why functional libraries adopt a **"data last"** signature convention; adopting it inconsistently is worse than not adopting it. The genuine payoff of both techniques is producing **unary** functions that pass straight to `map`, `filter` or a pipeline with no wrapper at each call site, and configured functions reused across many sites. They are **not** worth it for a function called once — `f(a)(b)` is strictly harder to read than `f(a, b)` — and a plain arrow such as `(n) => format(n, "USD")` is often clearer than any helper.',
    keyTakeaways: [
      'Currying is one argument per call; partial application fixes any number',
      'Not every function returning a function is curried',
      'fn.length stops at the first default or rest parameter — curry breaks silently',
      'Fixed arguments are prepended, so you can only pre-fill from the left',
      'The real payoff is unary functions for map, filter and pipelines',
      'A plain arrow is often clearer than a curry or partial helper',
    ],
    relatedLessons: ['l-m37-02', 'l-m32-02'],
    interviewConnections: [
      'What is currying, and how does it differ from partial application?',
      'Implement a curry function.',
      'Why does "data last" argument order matter for partial application?',
      'When would currying be the wrong choice?',
    ],
  },
];
