import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm06';

export default [
  /* ================================================================== */
  {
    id: 'l-m06-01',
    slug: 'how-numbers-work',
    moduleId: M,
    order: 1,
    title: 'How JavaScript Numbers Actually Work',
    description: 'One type for everything, 64 bits of it, and the precision limits that follow.',
    difficulty: DIFFICULTY.EASY,
    estimatedMinutes: 15,
    xp: 30,
    topicIds: ['numbers'],
    prerequisites: ['l-m05-06'],
    learningObjectives: [
      'Explain what IEEE 754 double precision means in practical terms',
      'Identify the safe integer range and why it exists',
      'Explain why `0.1 + 0.2` is not `0.3` in terms of binary fractions',
      'Choose an appropriate strategy for money and for large integers',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          'You met the headline facts in the Data Types module: one `number` type, `NaN`, `Infinity`, and the floating-point surprise. This module goes properly into what follows from them, because numeric bugs are quiet — they do not throw, they just produce a total that is one penny out.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'One type, 64 bits',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Every JavaScript `number` is a **64-bit IEEE 754 double-precision floating-point value** — the same representation used by nearly every modern language for decimals. Those 64 bits are divided into three parts: 1 bit for the sign, 11 bits for the exponent, and 52 bits for the significant digits.',
          'That 52-bit budget for digits is where every limitation in this lesson comes from. It is generous — enough for about 15 to 17 decimal digits — but it is finite.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Integers and decimals are the same type.',
        code: [
          'console.log(typeof 1, typeof 1.0, typeof 1.5);',
          'console.log(1 === 1.0);',
          '',
          '// Which is why division does not truncate',
          'console.log(7 / 2);',
          '',
          '// And why very large and very small both work',
          'console.log(1e21);',
          'console.log(1e-7);',
        ].join('\n'),
        output: ['number number number', 'true', '3.5', '1e+21', '1e-7'].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'The safe integer range',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'With 52 bits of significand, integers are represented **exactly** up to 2⁵³ − 1, which is 9,007,199,254,740,991. Beyond that, not every integer can be stored, so some of them silently round to a neighbour.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Where integers stop being reliable.',
        code: [
          'console.log(Number.MAX_SAFE_INTEGER);',
          'console.log(Number.MIN_SAFE_INTEGER);',
          '',
          '// Just past the limit, distinct integers collide',
          'console.log(9007199254740992 === 9007199254740993);',
          '',
          'console.log(Number.isSafeInteger(9007199254740991));',
          'console.log(Number.isSafeInteger(9007199254740992));',
          '',
          '// The absolute limits of the type',
          'console.log(Number.MAX_VALUE);',
          'console.log(Number.MIN_VALUE);',
        ].join('\n'),
        output: [
          '9007199254740991',
          '-9007199254740991',
          'true',
          'true',
          'false',
          '1.7976931348623157e+308',
          '5e-324',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'This is why IDs arrive as strings',
        body: [
          'Database IDs, Twitter snowflake IDs and similar 64-bit integers routinely exceed the safe range. If such an ID arrives in JSON as a bare number, `JSON.parse` silently rounds it and you now have the wrong record.',
          'Well-designed APIs send large IDs as strings for exactly this reason. If you control the API, do the same. If you do not, treat the ID as opaque text and never convert it to a number.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Why `0.1 + 0.2` is not `0.3`',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The reason is base conversion, and it has a precise analogue you already accept.',
          'In decimal, one third cannot be written exactly: 0.3333… continues forever, so any written form is an approximation. In **binary**, the same thing happens to one tenth. `0.1` in base 2 is `0.0001100110011…` repeating forever, so it must be cut off at 52 bits.',
          '`0.1` and `0.2` are therefore both stored as values very slightly off from the decimal fractions you wrote. Adding two approximations gives a result whose error is now large enough to become visible.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Seeing the stored values.',
        code: [
          'console.log(0.1 + 0.2);',
          'console.log((0.1).toFixed(20));',
          'console.log((0.2).toFixed(20));',
          '',
          '// Numbers whose fractions are powers of two are exact',
          'console.log(0.5 + 0.25 === 0.75);',
          '',
          '// Integers within the safe range are exact',
          'console.log(0.1 * 3 === 0.3);',
          'console.log(1 + 2 === 3);',
        ].join('\n'),
        output: [
          '0.30000000000000004',
          '0.10000000000000000555',
          '0.20000000000000001110',
          'true',
          'false',
          'true',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Notice `0.5 + 0.25 === 0.75` is exactly true. Halves, quarters and eighths are powers of two, so they have exact binary representations. It is tenths, fifths and thirds that cannot be represented — which is unfortunate, because those are precisely the fractions humans use for money.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The two correct strategies',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Strategy 1: compare with a tolerance.',
        code: [
          'function nearlyEqual(a, b, tolerance = 1e-9) {',
          '  return Math.abs(a - b) < tolerance;',
          '}',
          '',
          'console.log(0.1 + 0.2 === 0.3);',
          'console.log(nearlyEqual(0.1 + 0.2, 0.3));',
          '',
          '// Number.EPSILON is the smallest gap representable near 1',
          'console.log(Number.EPSILON);',
        ].join('\n'),
        output: ['false', 'true', '2.220446049250313e-16'].join('\n'),
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Strategy 2: work in integer minor units. This is what you do for money.',
        code: [
          '// Wrong: accumulating decimal cents',
          'let wrong = 0;',
          'for (let i = 0; i < 10; i++) wrong += 0.1;',
          'console.log(wrong);',
          'console.log(wrong === 1);',
          '',
          '// Right: work in integer pennies throughout',
          'let pennies = 0;',
          'for (let i = 0; i < 10; i++) pennies += 10;',
          'console.log(pennies, pennies === 100);',
          '',
          '// Convert to a display string only at the very end',
          'console.log("£" + (pennies / 100).toFixed(2));',
        ].join('\n'),
        output: ['0.9999999999999999', 'false', '100 true', '£1.00'].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The professional rule for money',
        body: [
          'Store and calculate in the smallest indivisible unit — pennies, cents, satoshis — as integers. Integers below 2⁵³ are exact, so no error can accumulate no matter how many operations you perform.',
          'Divide by 100 only at the moment of display, and format with `Intl.NumberFormat` rather than string concatenation. This is what payment systems do, and it is not optional advice.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'BigInt for integers beyond the limit',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'BigInt has no upper bound, but does not mix with Number.',
        code: [
          'const big = 9007199254740993n;',
          'console.log(big);',
          'console.log(big + 1n);',
          'console.log(typeof big);',
          '',
          '// Mixing with Number throws',
          'try {',
          '  console.log(big + 1);',
          '} catch (error) {',
          '  console.log(error.name + ":", error.message);',
          '}',
          '',
          '// Convert explicitly when you must',
          'console.log(Number(big) + 1);',
          '',
          '// BigInt division truncates — there are no fractions',
          'console.log(7n / 2n);',
        ].join('\n'),
        output: [
          '9007199254740993n',
          '9007199254740994n',
          'bigint',
          'TypeError: Cannot mix BigInt and other types, use explicit conversions',
          '9007199254740992',
          '3n',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Note the last two carefully. Converting a BigInt back to a Number puts it right back inside the unsafe range — `Number(9007199254740993n)` gives `9007199254740992`, silently losing the value. And BigInt division truncates, because BigInt represents integers only.',
          'BigInt is the right tool for large integer IDs, cryptographic values and precise counters. It is the wrong tool for money, because money needs a fixed number of decimal places rather than unbounded integers — integer minor units in a normal `number` handle that fine.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'console.log(0.1 + 0.2 === 0.3, 0.5 + 0.25 === 0.75, 0.1 + 0.7);',
        ].join('\n'),
        options: [
          'false true 0.7999999999999999',
          'true true 0.8',
          'false false 0.8',
          'false true 0.8',
        ],
        correct: 0,
        explanation:
          'Tenths cannot be represented exactly in binary, so `0.1 + 0.2` lands slightly off `0.3` and the comparison is false. Halves and quarters are powers of two and therefore exact, so `0.5 + 0.25 === 0.75` is genuinely true — the problem is specific to fractions that are not powers of two. And `0.1 + 0.7` produces `0.7999999999999999`, which is another visible instance of the same rounding.',
      },
    ],
    exercises: [
      {
        id: 'ex-m06-01-a',
        title: 'Predict the accumulated error',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.EASY,
        xp: 10,
        topicIds: ['numbers'],
        instructions: 'What does this print?',
        code: [
          'let total = 0;',
          'for (let i = 0; i < 10; i++) {',
          '  total += 0.1;',
          '}',
          'console.log(total === 1);',
        ].join('\n'),
        options: ['true', 'false', 'NaN', 'undefined'],
        correct: 1,
        hints: [
          '`0.1` has no exact binary representation.',
          'What happens when you add ten approximations together?',
        ],
        solution: 'false',
        solutionExplanation:
          'Each `0.1` is stored as a value very slightly above one tenth, and adding ten of them accumulates the error into something visible: the total is `0.9999999999999999`, not `1`. This is the clearest demonstration of why financial calculations must not accumulate decimal fractions — after enough operations the error becomes large enough to change a rounded result. Work in integer pennies instead, where every value is exact.',
      },
      {
        id: 'ex-m06-01-b',
        title: 'Work in integer pennies',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['numbers'],
        instructions:
          'Write `totalPennies(items)` where each item is `{ pricePennies, quantity }`. Return the exact total in pennies as an integer. All inputs are whole numbers, so the result must be exact regardless of how many items there are.',
        starterCode: [
          'function totalPennies(items) {',
          '  // Every value is already an integer — keep it that way.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'totals a single item', body: 'expect(totalPennies([{ pricePennies: 250, quantity: 2 }])).toBe(500);' },
          { name: 'totals several items', body: 'expect(totalPennies([{ pricePennies: 199, quantity: 3 }, { pricePennies: 1050, quantity: 1 }])).toBe(1647);' },
          { name: 'returns 0 for an empty list', body: 'expect(totalPennies([])).toBe(0);' },
          { name: 'handles a quantity of zero', body: 'expect(totalPennies([{ pricePennies: 500, quantity: 0 }])).toBe(0);' },
          { name: 'stays exact across many items', body: 'const items = Array.from({ length: 100 }, () => ({ pricePennies: 10, quantity: 1 })); expect(totalPennies(items)).toBe(1000);' },
          { name: 'returns an integer', body: 'expect(Number.isInteger(totalPennies([{ pricePennies: 333, quantity: 3 }]))).toBe(true);', hidden: true },
        ],
        hints: [
          'Multiply price by quantity for each item, then add them up.',
          '`reduce` is a natural fit, starting from an accumulator of 0.',
          'Do not divide by 100 anywhere — the function returns pennies.',
        ],
        solution: [
          'function totalPennies(items) {',
          '  return items.reduce((sum, item) => sum + item.pricePennies * item.quantity, 0);',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Because every operand is an integer well within the safe range, every intermediate result is exact and no error can accumulate — which is exactly what the hundred-item test verifies. Had the same calculation been done in pounds as decimals, adding a hundred values of `0.10` would have drifted, as the previous exercise demonstrated. The function deliberately returns pennies rather than pounds: conversion to a display value belongs at the boundary where you format for a human, not in the middle of a calculation.',
      },
      {
        id: 'ex-m06-01-c',
        title: 'Compare decimals within a tolerance',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['numbers'],
        instructions:
          'Write `approxEqual(a, b)` returning `true` when two numbers are equal to within `1e-9`. It must return `false` if either argument is not a finite number.',
        starterCode: [
          'function approxEqual(a, b) {',
          '  // Validate first, then compare the size of the difference.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'handles the classic case', body: 'expect(approxEqual(0.1 + 0.2, 0.3)).toBe(true);' },
          { name: 'identical values are equal', body: 'expect(approxEqual(5, 5)).toBe(true);' },
          { name: 'clearly different values are not', body: 'expect(approxEqual(1, 2)).toBe(false);' },
          { name: 'order does not matter', body: 'expect(approxEqual(0.3, 0.1 + 0.2)).toBe(true);' },
          { name: 'works with negatives', body: 'expect(approxEqual(-0.3, -(0.1 + 0.2))).toBe(true);' },
          { name: 'rejects NaN', body: 'expect(approxEqual(NaN, NaN)).toBe(false);' },
          { name: 'rejects Infinity', body: 'expect(approxEqual(Infinity, Infinity)).toBe(false);' },
          { name: 'rejects non-numbers', body: 'expect(approxEqual("1", 1)).toBe(false);', hidden: true },
        ],
        hints: [
          '`Number.isFinite` on both arguments rejects NaN, the infinities and non-numbers.',
          '`Math.abs(a - b)` gives the distance, making the comparison symmetric.',
          'Compare that distance against the tolerance with `<`.',
        ],
        solution: [
          'function approxEqual(a, b) {',
          '  if (!Number.isFinite(a) || !Number.isFinite(b)) return false;',
          '  return Math.abs(a - b) < 1e-9;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The validation guard is what makes the NaN and Infinity tests pass. Without it, `NaN - NaN` is `NaN`, and `NaN < 1e-9` is `false`, so NaN would accidentally give the right answer — but `Infinity - Infinity` is also `NaN`, which would wrongly report two infinities as unequal in a way that happens to look correct while being unreasoned. Being explicit means the behaviour is intentional rather than coincidental. `Math.abs` makes the comparison symmetric, so argument order cannot change the result.',
      },
    ],
    quiz: {
      id: 'qz-m06-01',
      questions: [
        {
          id: 'q-m06-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['numbers'],
          prompt: 'Why can JavaScript not represent `0.1` exactly?',
          options: [
            'Because JavaScript has a bug in its number implementation',
            'Because one tenth is a repeating fraction in binary, and the significand has only 52 bits',
            'Because `0.1` is too small to store',
            'Because decimals are stored as strings',
          ],
          correct: 1,
          optionExplanations: [
            'Every IEEE 754 language behaves identically.',
            'Correct — the same reason one third repeats in decimal.',
            'Magnitude is not the issue; `0.5` stores exactly.',
            'Numbers are stored in binary floating point.',
          ],
          explanation:
            'In binary, one tenth is `0.0001100110011…` repeating forever, so it must be truncated to fit 52 bits of significand. `0.5`, `0.25` and `0.75` are powers of two and store exactly — the problem is specific to fractions that are not.',
        },
        {
          id: 'q-m06-01-2',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['numbers'],
          prompt: 'Why are these two distinct integers equal?',
          code: ['console.log(9007199254740992 === 9007199254740993);'].join('\n'),
          options: ['true', 'false', 'NaN', 'A SyntaxError'],
          correct: 0,
          optionExplanations: [
            'Correct — both are beyond the safe integer range and round to the same stored value.',
            'They would differ if both could be represented.',
            'Comparison returns a boolean.',
            'Large numeric literals are valid.',
          ],
          explanation:
            'Above `Number.MAX_SAFE_INTEGER` (2⁵³ − 1), not every integer can be represented, so neighbouring values collide. This is why large database IDs should be transmitted as strings and never converted to a `number`.',
        },
        {
          id: 'q-m06-01-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['numbers'],
          prompt: 'What is the correct way to handle currency in JavaScript?',
          options: [
            'Use decimals and round with `toFixed(2)` at each step',
            'Store and calculate in integer minor units such as pennies, converting only for display',
            'Use BigInt for all monetary values',
            'Store amounts as strings and parse them when needed',
          ],
          correct: 1,
          optionExplanations: [
            'Rounding at each step compounds error rather than removing it.',
            'Correct — integers within the safe range are exact.',
            'BigInt handles unbounded integers, but money needs fixed decimal places, which minor units already give.',
            'Strings must be converted to numbers to be combined, reintroducing the problem.',
          ],
          explanation:
            'Integers below 2⁵³ are represented exactly, so calculating in pennies means no error can accumulate however many operations you perform. Divide by 100 and format only at the point of display.',
        },
        {
          id: 'q-m06-01-4',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['numbers'],
          prompt: 'What happens here?',
          code: ['console.log(10n + 5);'].join('\n'),
          options: ['15', '15n', 'A TypeError', '"105"'],
          correct: 2,
          optionExplanations: [
            'BigInt and Number do not combine implicitly.',
            'No implicit conversion happens in either direction.',
            'Correct — mixing the two throws deliberately.',
            'No string coercion occurs.',
          ],
          explanation:
            'Mixing BigInt and Number in arithmetic throws `TypeError: Cannot mix BigInt and other types`. The language refuses rather than guessing which precision to sacrifice. Convert explicitly with `Number(big)` or `BigInt(num)` — and be aware that converting a large BigInt to a Number can silently lose precision.',
        },
      ],
    },
    summary:
      'Every JavaScript number is a 64-bit IEEE 754 double, with 52 bits of significand. That gives exact integers up to 2⁵³ − 1 — beyond which distinct integers silently collide, which is why large IDs should travel as strings. It also means fractions that are not powers of two, including tenths and fifths, cannot be stored exactly, so `0.1 + 0.2` lands slightly off `0.3` while `0.5 + 0.25 === 0.75` is exactly true. Two strategies follow: compare decimals within a tolerance rather than with `===`, and for money calculate in integer minor units so no error can accumulate, converting for display only at the end. BigInt handles integers beyond the safe range but will not mix with Number and truncates on division.',
    keyTakeaways: [
      'One `number` type: 64-bit IEEE 754 double, 52 bits of significand',
      'Integers are exact only up to `Number.MAX_SAFE_INTEGER` (2⁵³ − 1)',
      'Tenths repeat in binary; halves and quarters are exact',
      'Compare decimals with a tolerance, never with `===`',
      'Calculate money in integer minor units; format only for display',
      'BigInt is unbounded but throws when mixed with Number',
    ],
    relatedLessons: ['l-m02-04', 'l-m06-02'],
    interviewConnections: [
      'Why does 0.1 + 0.2 not equal 0.3?',
      'What is Number.MAX_SAFE_INTEGER and why does it matter?',
      'How would you handle currency in JavaScript?',
      'When would you use BigInt?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m06-02',
    slug: 'converting-and-validating',
    moduleId: M,
    order: 2,
    title: 'Converting and Validating Numbers',
    description: 'The Number static methods that replaced the flawed globals, and a validation routine you can trust.',
    difficulty: DIFFICULTY.EASY,
    estimatedMinutes: 14,
    xp: 25,
    topicIds: ['numbers', 'coercion'],
    prerequisites: ['l-m06-01'],
    learningObjectives: [
      'Choose between `Number.isInteger`, `isFinite`, `isNaN` and `isSafeInteger`',
      'Explain why the global `isNaN` and `isFinite` are unreliable',
      'Format numbers for display with `toFixed` and `Intl.NumberFormat`',
      'Write a numeric validator that rejects every invalid case',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          'ES2015 added `Number.isNaN` and `Number.isFinite` as fixed versions of the older global functions. The difference is a single behaviour with wide consequences: **the globals coerce their argument first; the `Number.` versions do not.**',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The globals answer a different question from the one you asked.',
        code: [
          '// Global isNaN really asks "would this fail to convert to a number?"',
          'console.log(isNaN("hello"));          // true  — but "hello" is not NaN',
          'console.log(isNaN(undefined));        // true  — nor is undefined',
          'console.log(isNaN("42"));             // false',
          '',
          '// Number.isNaN asks "is this the value NaN?"',
          'console.log(Number.isNaN("hello"));   // false',
          'console.log(Number.isNaN(undefined)); // false',
          'console.log(Number.isNaN(NaN));       // true',
          '',
          '// Same story for isFinite',
          'console.log(isFinite("42"));          // true  — a string!',
          'console.log(isFinite(null));          // true  — null converts to 0',
          'console.log(Number.isFinite("42"));   // false',
          'console.log(Number.isFinite(null));   // false',
        ].join('\n'),
        output: [
          'true', 'true', 'false',
          'false', 'false', 'true',
          'true', 'true', 'false', 'false',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'A rule with no exceptions',
        body: [
          'Always use the `Number.` prefixed versions. The globals exist only for backwards compatibility, and every case where they differ is a case where they give the wrong answer for a type check.',
          'Most linter configurations have a rule that flags the globals for exactly this reason.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The four `Number` predicates',
      },
      {
        kind: SECTION.TABLE,
        headers: ['Method', 'Returns true for', 'Coerces?'],
        rows: [
          ['`Number.isFinite(v)`', 'A number that is not NaN or Infinity', 'No'],
          ['`Number.isNaN(v)`', 'Exactly the value NaN', 'No'],
          ['`Number.isInteger(v)`', 'A number with no fractional part', 'No'],
          ['`Number.isSafeInteger(v)`', 'An integer within ±(2⁵³ − 1)', 'No'],
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'What each one accepts.',
        code: [
          'const values = [42, 42.5, "42", NaN, Infinity, 1e21, null];',
          '',
          'for (const v of values) {',
          '  console.log(',
          '    String(v).padEnd(10),',
          '    "finite:", String(Number.isFinite(v)).padEnd(6),',
          '    "int:", String(Number.isInteger(v)).padEnd(6),',
          '    "safe:", String(Number.isSafeInteger(v)),',
          '  );',
          '}',
        ].join('\n'),
        output: [
          '42         finite: true   int: true   safe: true',
          '42.5       finite: true   int: false  safe: false',
          '42         finite: false  int: false  safe: false',
          'NaN        finite: false  int: false  safe: false',
          'Infinity   finite: false  int: false  safe: false',
          '1e+21      finite: true   int: true   safe: false',
          'null       finite: false  int: false  safe: false',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The `1e21` row is the interesting one: it is a genuine finite integer, but it is outside the safe range, so `isSafeInteger` correctly rejects it. And the `"42"` row shows that none of these coerce — a numeric string is not a number.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'A validator you can trust',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Converting user input safely, closing every hole.',
        code: [
          'function parseAmount(raw) {',
          '  if (raw == null) return { ok: false, error: "Required" };',
          '',
          '  const text = String(raw).trim();',
          '  if (text === "") return { ok: false, error: "Required" };',
          '',
          '  const value = Number(text);',
          '  if (!Number.isFinite(value)) return { ok: false, error: "Not a number" };',
          '  if (value < 0) return { ok: false, error: "Must not be negative" };',
          '',
          '  return { ok: true, value };',
          '}',
          '',
          'console.log(parseAmount("42"));',
          'console.log(parseAmount("  3.5  "));',
          'console.log(parseAmount(""));',
          'console.log(parseAmount("12 apples"));',
          'console.log(parseAmount("-5"));',
        ].join('\n'),
        output: [
          '{ok: true, value: 42}',
          '{ok: true, value: 3.5}',
          '{ok: false, error: "Required"}',
          '{ok: false, error: "Not a number"}',
          '{ok: false, error: "Must not be negative"}',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Each guard closes a specific hole you met in the coercion module. The `== null` check catches both nullish values. Trimming and testing for an empty string closes the `Number("") === 0` trap. `Number.isFinite` rejects `NaN` from unparseable text as well as both infinities. The order matters — checking emptiness after conversion would report "Not a number" for a blank field, which is confusing feedback.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Formatting for display',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: '`toFixed` returns a string, and rounds.',
        code: [
          'console.log((3.14159).toFixed(2));',
          'console.log((5).toFixed(2));',
          'console.log(typeof (5).toFixed(2));',
          '',
          '// It rounds rather than truncating',
          'console.log((2.567).toFixed(2));',
          '',
          '// And it inherits floating-point surprises',
          'console.log((1.005).toFixed(2));',
          '',
          '// toPrecision counts significant digits instead',
          'console.log((123.456).toPrecision(4));',
        ].join('\n'),
        output: ['3.14', '5.00', 'string', '2.57', '1.00', '123.5'].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: '`(1.005).toFixed(2)` gives `"1.00"`, not `"1.01"`',
        body: [
          'This looks like a rounding bug and is really the precision issue again: `1.005` is actually stored as `1.00499999999999989…`, which correctly rounds down.',
          'It is another argument for working in integer minor units. If you are formatting a value that came from decimal arithmetic, the digits you see may already be slightly wrong before `toFixed` ever runs.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: '`Intl.NumberFormat` is the right tool for anything a user reads.',
        code: [
          'const n = 1234567.891;',
          '',
          'console.log(new Intl.NumberFormat("en-GB").format(n));',
          'console.log(new Intl.NumberFormat("de-DE").format(n));',
          '',
          'console.log(new Intl.NumberFormat("en-GB", {',
          '  style: "currency", currency: "GBP",',
          '}).format(n));',
          '',
          'console.log(new Intl.NumberFormat("en-GB", {',
          '  style: "percent", maximumFractionDigits: 1,',
          '}).format(0.4567));',
          '',
          'console.log(new Intl.NumberFormat("en-GB", {',
          '  minimumFractionDigits: 2, maximumFractionDigits: 2,',
          '}).format(7));',
        ].join('\n'),
        output: [
          '1,234,567.891',
          '1.234.567,891',
          '£1,234,567.89',
          '45.7%',
          '7.00',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Other options worth knowing',
        body: [
          '`notation: "compact"` renders `1234567` as something like `1.2M`, which is useful for dashboards — though the exact casing and suffix depend on the locale data the environment ships, so do not assert on it in tests.',
          '`useGrouping: false` removes the thousands separators, and `signDisplay: "always"` forces a leading `+` on positive values.',
        ],
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`Intl.NumberFormat` handles thousands separators, decimal marks, currency symbols and placement, and percentage conventions — all of which differ by locale. Germany uses a full stop for thousands and a comma for decimals, exactly the reverse of the UK. Hand-rolling this with string manipulation will be wrong for most of the world.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'console.log(isNaN("abc"), Number.isNaN("abc"), Number.isInteger("42"));',
        ].join('\n'),
        options: [
          'true false false',
          'true true false',
          'false false true',
          'true false true',
        ],
        correct: 0,
        explanation:
          'The global `isNaN("abc")` converts first — `Number("abc")` is `NaN` — so it returns `true`, even though the string `"abc"` is obviously not the value `NaN`. `Number.isNaN("abc")` performs no conversion and asks the literal question, so it returns `false`. And `Number.isInteger("42")` also refuses to coerce: a string is not a number, whatever its contents, so it returns `false`.',
      },
    ],
    exercises: [
      {
        id: 'ex-m06-02-a',
        title: 'Predict the global isNaN result',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.EASY,
        xp: 10,
        topicIds: ['numbers', 'coercion'],
        instructions: 'What does this print?',
        code: ['console.log(isNaN(""));'].join('\n'),
        options: ['true', 'false', 'NaN', 'undefined'],
        correct: 1,
        hints: [
          'The global `isNaN` converts its argument first.',
          'What is `Number("")`?',
        ],
        solution: 'false',
        solutionExplanation:
          'The global `isNaN` converts its argument before testing. `Number("")` is `0`, which is a perfectly good number and not `NaN`, so the result is `false`. That happens to be "correct" here in a misleading way — the function is really answering "would this fail to convert?", which is not the question you asked. `Number.isNaN("")` returns `false` too, but for the right reason: an empty string is not the value `NaN`.',
      },
      {
        id: 'ex-m06-02-b',
        title: 'Fix the numeric type check',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['numbers', 'coercion'],
        instructions:
          'This function should return `true` only for genuine, usable numbers. It currently accepts numeric strings, `null`, empty strings and `Infinity`. Fix it.',
        starterCode: [
          'function isUsable(value) {',
          '  return !isNaN(value);',
          '}',
        ].join('\n'),
        tests: [
          { name: 'accepts an integer', body: 'expect(isUsable(42)).toBe(true);' },
          { name: 'accepts a decimal', body: 'expect(isUsable(3.14)).toBe(true);' },
          { name: 'accepts zero', body: 'expect(isUsable(0)).toBe(true);' },
          { name: 'accepts negatives', body: 'expect(isUsable(-7)).toBe(true);' },
          { name: 'rejects a numeric string', body: 'expect(isUsable("42")).toBe(false);' },
          { name: 'rejects an empty string', body: 'expect(isUsable("")).toBe(false);' },
          { name: 'rejects null and undefined', body: 'expect(isUsable(null)).toBe(false); expect(isUsable(undefined)).toBe(false);' },
          { name: 'rejects NaN and Infinity', body: 'expect(isUsable(NaN)).toBe(false); expect(isUsable(Infinity)).toBe(false);' },
          { name: 'rejects arrays', body: 'expect(isUsable([])).toBe(false); expect(isUsable([5])).toBe(false);', hidden: true },
        ],
        hints: [
          'The global `isNaN` coerces, which is why `""`, `null` and `[]` slip through.',
          'One `Number.` method rejects all of these in a single call.',
          'It must reject the infinities as well as NaN.',
        ],
        solution: [
          'function isUsable(value) {',
          '  return Number.isFinite(value);',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`Number.isFinite` does the whole job: it returns `false` for anything that is not of type `number`, so strings, `null`, `undefined` and arrays are rejected without any conversion, and it returns `false` for `NaN`, `Infinity` and `-Infinity`. The original `!isNaN(value)` failed because the global coerces first — `Number("")`, `Number(null)` and `Number([])` are all `0`, and `Number([5])` is `5`, so every one of those looked like a valid number. This single-method fix is why the `Number.` predicates were added.',
      },
      {
        id: 'ex-m06-02-c',
        title: 'Format a price for display',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['numbers'],
        instructions:
          'Write `formatPrice(pennies)` that takes an integer number of pennies and returns a string such as `"£12.50"`. Use `toFixed(2)` so the decimals are always shown. Return `"—"` if the input is not a safe integer.',
        starterCode: [
          'function formatPrice(pennies) {',
          '  // Validate, then divide by 100 only at this display boundary.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'formats a normal price', body: 'expect(formatPrice(1250)).toBe("£12.50");' },
          { name: 'pads whole pounds', body: 'expect(formatPrice(500)).toBe("£5.00");' },
          { name: 'handles zero', body: 'expect(formatPrice(0)).toBe("£0.00");' },
          { name: 'handles single pennies', body: 'expect(formatPrice(7)).toBe("£0.07");' },
          { name: 'handles large amounts', body: 'expect(formatPrice(123456)).toBe("£1234.56");' },
          { name: 'rejects a decimal input', body: 'expect(formatPrice(12.5)).toBe("—");' },
          { name: 'rejects non-numbers', body: 'expect(formatPrice("1250")).toBe("—"); expect(formatPrice(null)).toBe("—");' },
          { name: 'rejects NaN', body: 'expect(formatPrice(NaN)).toBe("—");', hidden: true },
        ],
        hints: [
          '`Number.isSafeInteger` rejects decimals, non-numbers, NaN and unsafe magnitudes at once.',
          'Divide by 100 to convert pennies to pounds.',
          '`toFixed(2)` produces the two decimal places as a string.',
        ],
        solution: [
          'function formatPrice(pennies) {',
          '  if (!Number.isSafeInteger(pennies)) return "—";',
          '  return "£" + (pennies / 100).toFixed(2);',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`Number.isSafeInteger` is exactly the right guard here: it rejects `12.5` because it has a fractional part, rejects `"1250"` and `null` because they are not numbers, and rejects `NaN` — three tests satisfied by one call. The division by 100 happens only at this point, which is the whole discipline of working in minor units: every calculation upstream stayed in exact integers, and the single lossy operation is the last one before display. For a production application `Intl.NumberFormat` would be better still, since it handles locale-specific separators and currency placement that a hard-coded `"£"` cannot.',
      },
    ],
    quiz: {
      id: 'qz-m06-02',
      questions: [
        {
          id: 'q-m06-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['numbers'],
          prompt: 'What is the essential difference between `isNaN` and `Number.isNaN`?',
          options: [
            '`Number.isNaN` is faster',
            'The global coerces its argument first, so it answers "would this fail to convert?" rather than "is this NaN?"',
            'The global only works on strings',
            'They are identical',
          ],
          correct: 1,
          optionExplanations: [
            'Performance is not the distinction.',
            'Correct — which is why `isNaN("hello")` is true.',
            'It accepts any value.',
            'They differ for every non-number argument.',
          ],
          explanation:
            'The global converts before testing, so `isNaN("hello")` is `true` even though the string is not the value `NaN`. `Number.isNaN` performs no conversion and returns `true` only for actual `NaN`. Always prefer the prefixed version.',
        },
        {
          id: 'q-m06-02-2',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['numbers'],
          prompt: 'Why does this rounding look wrong?',
          code: ['console.log((1.005).toFixed(2));'].join('\n'),
          options: ['"1.01"', '"1.00"', '"1.0"', '"1"'],
          correct: 1,
          optionExplanations: [
            'That is what decimal arithmetic would give, but the stored value is slightly lower.',
            'Correct — `1.005` is stored as `1.00499999999999989…`.',
            '`toFixed(2)` always produces two decimal places.',
            'The decimals are not dropped.',
          ],
          explanation:
            '`1.005` cannot be represented exactly in binary and is stored as slightly less than 1.005, so rounding to two places correctly gives `"1.00"`. The rounding is not broken — the input was already imprecise. Another reason to keep money in integer minor units.',
        },
        {
          id: 'q-m06-02-3',
          kind: QUIZ_KIND.MULTIPLE,
          topicIds: ['numbers'],
          prompt: 'Which of these return `false` for `Number.isFinite`? (Select all that apply.)',
          options: ['`"42"`', '`Infinity`', '`0`', '`null`'],
          correct: [0, 1, 3],
          explanation:
            '`Number.isFinite` performs no coercion, so a numeric string is rejected on type alone, as are `null` and `undefined`. `Infinity` is a number but is not finite. `0` is a perfectly ordinary finite number and passes — a reminder that "falsy" and "invalid" are different questions.',
        },
        {
          id: 'q-m06-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['numbers'],
          prompt: 'Why prefer `Intl.NumberFormat` over manual string formatting?',
          options: [
            'It is shorter to write',
            'It handles locale-specific separators, decimal marks and currency conventions that differ between countries',
            'It is the only way to add decimal places',
            'It returns a number rather than a string',
          ],
          correct: 1,
          optionExplanations: [
            'It is usually longer to write.',
            'Correct — Germany reverses the UK separators, for example.',
            '`toFixed` also adds decimal places.',
            'It returns a formatted string.',
          ],
          explanation:
            'Thousands separators, decimal marks, currency symbols and their placement all vary by locale — Germany writes `1.234.567,89` where the UK writes `1,234,567.89`. Hand-rolled formatting will be wrong for most of the world.',
        },
      ],
    },
    summary:
      'The global `isNaN` and `isFinite` coerce their argument before testing, so they answer "would this convert to a number?" rather than the question you asked — always use `Number.isNaN` and `Number.isFinite`, which perform no conversion. `Number.isInteger` and `Number.isSafeInteger` complete the set, the latter also enforcing the 2⁵³ limit. A trustworthy validator guards in order: nullish, then empty after trimming, then `Number.isFinite` after converting, then range — because checking emptiness after conversion would misreport a blank field. For display, `toFixed` returns a string and rounds, though it inherits floating-point imprecision so `(1.005).toFixed(2)` is `"1.00"`. Anything a user reads should go through `Intl.NumberFormat`, which handles the separators and currency conventions that differ by locale.',
    keyTakeaways: [
      'Always use `Number.isNaN` / `Number.isFinite`, never the globals',
      'None of the `Number.` predicates coerce — `"42"` is not a number',
      '`Number.isSafeInteger` rejects decimals, non-numbers and unsafe magnitudes at once',
      'Guard order matters: nullish → empty → convert → finite → range',
      '`toFixed` returns a string and inherits floating-point imprecision',
      'Use `Intl.NumberFormat` for anything a user reads',
    ],
    relatedLessons: ['l-m03-01', 'l-m06-03'],
    interviewConnections: [
      'What is the difference between isNaN and Number.isNaN?',
      'How would you validate that a value is a usable number?',
      'Why does (1.005).toFixed(2) give "1.00"?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m06-03',
    slug: 'math-object',
    moduleId: M,
    order: 3,
    title: 'The Math Object',
    description: 'Rounding that behaves differently for negatives, random numbers in a range, and the methods worth knowing.',
    difficulty: DIFFICULTY.EASY,
    estimatedMinutes: 15,
    xp: 30,
    topicIds: ['numbers'],
    prerequisites: ['l-m06-02'],
    learningObjectives: [
      'Choose correctly between `round`, `floor`, `ceil` and `trunc`',
      'Explain how the four rounding methods differ for negative numbers',
      'Generate a random integer in an inclusive range',
      'Use `Math.min`, `Math.max` and the spread trick for arrays',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          '`Math` is not a constructor or a class — it is a plain object holding static methods and constants. You never write `new Math()`; you just call `Math.round(x)`.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The four rounding methods',
      },
      {
        kind: SECTION.TABLE,
        headers: ['Method', 'Rounds towards'],
        rows: [
          ['`Math.round`', 'The nearest integer; exact halves go **up**'],
          ['`Math.floor`', 'Negative infinity — always down'],
          ['`Math.ceil`', 'Positive infinity — always up'],
          ['`Math.trunc`', 'Zero — simply drops the fraction'],
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'They agree on positives and disagree on negatives.',
        code: [
          'const values = [2.7, 2.5, 2.3, -2.3, -2.5, -2.7];',
          '',
          'for (const v of values) {',
          '  console.log(',
          '    String(v).padStart(5),',
          '    "round:", String(Math.round(v)).padStart(3),',
          '    "floor:", String(Math.floor(v)).padStart(3),',
          '    "ceil:", String(Math.ceil(v)).padStart(3),',
          '    "trunc:", String(Math.trunc(v)).padStart(3),',
          '  );',
          '}',
        ].join('\n'),
        output: [
          '  2.7 round:   3 floor:   2 ceil:   3 trunc:   2',
          '  2.5 round:   3 floor:   2 ceil:   3 trunc:   2',
          '  2.3 round:   2 floor:   2 ceil:   3 trunc:   2',
          ' -2.3 round:  -2 floor:  -3 ceil:  -2 trunc:  -2',
          ' -2.5 round:  -2 floor:  -3 ceil:  -2 trunc:  -2',
          ' -2.7 round:  -3 floor:  -3 ceil:  -2 trunc:  -2',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'Two things that surprise people',
        body: [
          '**`Math.round(-2.5)` is `-2`, not `-3`.** Rounding a half always goes towards positive infinity, not away from zero. So `2.5` rounds to `3` and `-2.5` rounds to `-2`, which is asymmetric.',
          '**`Math.floor` and `Math.trunc` differ for negatives.** `Math.floor(-2.3)` is `-3` because it always rounds down, while `Math.trunc(-2.3)` is `-2` because it just removes the fraction. For positive numbers they are identical, which is why the difference goes unnoticed until a negative appears.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Integer division: which one do you want?',
        code: [
          '// For positive values they agree',
          'console.log(Math.floor(7 / 2), Math.trunc(7 / 2));',
          '',
          '// For negative values they do not',
          'console.log(Math.floor(-7 / 2), Math.trunc(-7 / 2));',
          '',
          '// Rounding to two decimal places',
          'const value = 3.14159;',
          'console.log(Math.round(value * 100) / 100);',
        ].join('\n'),
        output: ['3 3', '-4 -3', '3.14'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The `Math.round(x * 100) / 100` idiom rounds to two decimal places and returns a **number**, whereas `toFixed(2)` returns a string. Use the former when the result feeds further calculation, the latter when it goes straight to display.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Random numbers',
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`Math.random()` returns a decimal in the range 0 (inclusive) to 1 (exclusive). Every other random need is built from it, and the arithmetic is worth deriving rather than memorising.',
        ],
      },
      {
        kind: SECTION.STEPS,
        steps: [
          {
            title: 'Start with 0 ≤ r < 1',
            body: '`Math.random()` gives a decimal that can be 0 but never quite reaches 1.',
          },
          {
            title: 'Scale it to the size of the range',
            body: 'Multiplying by `(max - min + 1)` stretches it to cover exactly that many whole values. The `+ 1` is what makes `max` reachable.',
          },
          {
            title: 'Drop the fraction',
            body: '`Math.floor` turns the decimal into one of the whole numbers `0` to `max - min`.',
          },
          {
            title: 'Shift into position',
            body: 'Adding `min` moves the range so it starts where you want.',
          },
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The standard inclusive random-integer function.',
        code: [
          'function randomInt(min, max) {',
          '  return Math.floor(Math.random() * (max - min + 1)) + min;',
          '}',
          '',
          '// Verify the range holds over many rolls',
          'const rolls = [];',
          'for (let i = 0; i < 1000; i++) rolls.push(randomInt(1, 6));',
          '',
          'console.log("min seen:", Math.min(...rolls));',
          'console.log("max seen:", Math.max(...rolls));',
          'console.log("all in range:", rolls.every((n) => n >= 1 && n <= 6));',
          'console.log("all integers:", rolls.every(Number.isInteger));',
        ].join('\n'),
        output: ['min seen: 1', 'max seen: 6', 'all in range: true', 'all integers: true'].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: '`Math.random` is not secure',
        body: [
          'It is fast and statistically reasonable, but it is predictable and must never be used for anything security-sensitive — password reset tokens, session identifiers, cryptographic keys, shuffling a real card game for money.',
          'Use `crypto.getRandomValues()` in the browser or `crypto.randomBytes()` in Node for those. `crypto.randomUUID()` generates a secure unique identifier in one call.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'min, max and the spread trick',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'These take arguments, not an array — spread bridges the gap.',
        code: [
          'console.log(Math.min(3, 1, 4));',
          'console.log(Math.max(3, 1, 4));',
          '',
          'const numbers = [3, 1, 4, 1, 5];',
          'console.log(Math.min(...numbers), Math.max(...numbers));',
          '',
          '// Without spread you get NaN — an array is not a number',
          'console.log(Math.max(numbers));',
          '',
          '// The identity values, which are how the functions start',
          'console.log(Math.min(), Math.max());',
        ].join('\n'),
        output: ['1', '4', '1 5', 'NaN', 'Infinity -Infinity'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`Math.max()` with no arguments returns `-Infinity`, and `Math.min()` returns `Infinity`. That is not arbitrary: they are the identity values, so that any real number compared against them wins. It also means an **empty array** spread into `Math.max` gives `-Infinity`, which is a real edge case worth guarding.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Spread has an argument limit',
        body: [
          'Spreading a very large array — roughly 100,000 elements or more, depending on the engine — can exceed the maximum argument count and throw a `RangeError`.',
          'For large datasets use `reduce` instead: `numbers.reduce((a, b) => Math.max(a, b), -Infinity)`. For everyday arrays, spread is clearer and perfectly fine.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The rest of Math',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The methods and constants you will actually use.',
        code: [
          'console.log(Math.abs(-5));',
          'console.log(Math.sign(-5), Math.sign(0), Math.sign(5));',
          'console.log(Math.sqrt(16), Math.cbrt(27));',
          'console.log(Math.pow(2, 10), 2 ** 10);',
          'console.log(Math.hypot(3, 4));',
          '',
          'console.log(Math.PI);',
          'console.log(Math.E);',
          '',
          '// Clamping a value into a range',
          'const clamp = (v, lo, hi) => Math.min(Math.max(v, lo), hi);',
          'console.log(clamp(150, 0, 100), clamp(-20, 0, 100), clamp(50, 0, 100));',
        ].join('\n'),
        output: [
          '5',
          '-1 0 1',
          '4 3',
          '1024 1024',
          '5',
          '3.141592653589793',
          '2.718281828459045',
          '100 0 50',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The `clamp` one-liner is worth remembering: `Math.min(Math.max(v, lo), hi)` forces a value into a range and appears constantly in UI code — progress bars, scroll positions, volume controls. `Math.pow` is entirely superseded by the `**` operator.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'console.log(Math.round(-2.5), Math.floor(-2.5), Math.trunc(-2.5));',
        ].join('\n'),
        options: [
          '-2 -3 -2',
          '-3 -3 -3',
          '-3 -2 -2',
          '-2 -2 -2',
        ],
        correct: 0,
        explanation:
          '`Math.round` sends exact halves towards positive infinity, so `-2.5` rounds up to `-2` — not away from zero to `-3`, which is what most people expect. `Math.floor` always rounds down towards negative infinity, giving `-3`. `Math.trunc` simply removes the fractional part, giving `-2`. All three agree for positive numbers, which is why these differences only surface once negatives appear.',
      },
    ],
    exercises: [
      {
        id: 'ex-m06-03-a',
        title: 'Predict the negative rounding',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.EASY,
        xp: 10,
        topicIds: ['numbers'],
        instructions: 'What does this print?',
        code: ['console.log(Math.floor(-2.3), Math.trunc(-2.3));'].join('\n'),
        options: ['-3 -2', '-2 -3', '-3 -3', '-2 -2'],
        correct: 0,
        hints: [
          '`floor` always rounds towards negative infinity.',
          '`trunc` just deletes the fractional part.',
        ],
        solution: '-3 -2',
        solutionExplanation:
          '`Math.floor` always rounds down towards negative infinity, so `-2.3` becomes `-3`. `Math.trunc` simply removes the fraction, leaving `-2`. For positive numbers the two are identical, which is exactly why this difference causes bugs — code tested only with positive values passes, then produces off-by-one results the first time a negative appears. Use `trunc` when you mean "drop the decimals" and `floor` when you mean "round down".',
      },
      {
        id: 'ex-m06-03-b',
        title: 'Write an inclusive random integer',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['numbers'],
        instructions:
          'Write `randomInt(min, max)` returning a random integer between `min` and `max` **inclusive** at both ends. `randomInt(1, 6)` must be able to produce both 1 and 6.',
        starterCode: [
          'function randomInt(min, max) {',
          '  // Math.random() gives 0 <= r < 1. Scale, floor, then shift.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'always returns an integer', body: 'for (let i = 0; i < 200; i++) expect(Number.isInteger(randomInt(1, 6))).toBe(true);' },
          { name: 'stays within the range', body: 'for (let i = 0; i < 200; i++) { const r = randomInt(1, 6); expect(r >= 1 && r <= 6).toBe(true); }' },
          { name: 'can produce the minimum', body: 'const seen = new Set(); for (let i = 0; i < 500; i++) seen.add(randomInt(1, 3)); expect(seen.has(1)).toBe(true);' },
          { name: 'can produce the maximum', body: 'const seen = new Set(); for (let i = 0; i < 500; i++) seen.add(randomInt(1, 3)); expect(seen.has(3)).toBe(true);' },
          { name: 'handles a single-value range', body: 'expect(randomInt(5, 5)).toBe(5);' },
          { name: 'handles negative ranges', body: 'for (let i = 0; i < 200; i++) { const r = randomInt(-5, -1); expect(r >= -5 && r <= -1).toBe(true); }', hidden: true },
        ],
        hints: [
          'The range spans `max - min + 1` distinct whole numbers.',
          'Multiply `Math.random()` by that count, then `Math.floor` the result.',
          'Finally add `min` to shift the range into position.',
        ],
        solution: [
          'function randomInt(min, max) {',
          '  return Math.floor(Math.random() * (max - min + 1)) + min;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The `+ 1` is the part everyone gets wrong. Without it the range spans `max - min` values and the maximum can never be produced, because `Math.random()` never quite reaches 1 — the third and fourth tests exist specifically to catch that off-by-one. `Math.floor` is correct here rather than `Math.round`, which would make the first and last values half as likely as the others by only capturing half a bucket each. The single-value test confirms the arithmetic degrades correctly: `max - min + 1` becomes 1, so the floored product is always 0 and the result is always `min`.',
      },
      {
        id: 'ex-m06-03-c',
        title: 'Find the range of an array',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['numbers'],
        instructions:
          'Write `rangeOf(numbers)` returning `{ min, max, spread }` where `spread` is `max - min`. Return `null` for an empty array, and ignore any element that is not a finite number.',
        starterCode: [
          'function rangeOf(numbers) {',
          '  // Filter to valid numbers first, then use Math.min / Math.max.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'finds the range', body: 'expect(rangeOf([3, 1, 4, 1, 5])).toEqual({ min: 1, max: 5, spread: 4 });' },
          { name: 'handles a single element', body: 'expect(rangeOf([7])).toEqual({ min: 7, max: 7, spread: 0 });' },
          { name: 'handles negatives', body: 'expect(rangeOf([-5, 0, 5])).toEqual({ min: -5, max: 5, spread: 10 });' },
          { name: 'returns null for an empty array', body: 'expect(rangeOf([])).toBe(null);' },
          { name: 'ignores invalid entries', body: 'expect(rangeOf([1, "x", null, 9, NaN])).toEqual({ min: 1, max: 9, spread: 8 });' },
          { name: 'returns null when nothing is valid', body: 'expect(rangeOf(["a", null, NaN])).toBe(null);', hidden: true },
        ],
        hints: [
          'Filter with `Number.isFinite` to drop invalid entries in one step.',
          'Check the filtered length before calling `Math.min` — an empty spread gives `Infinity`.',
          '`Math.min(...arr)` needs spread, since it takes arguments rather than an array.',
        ],
        solution: [
          'function rangeOf(numbers) {',
          '  const valid = numbers.filter(Number.isFinite);',
          '  if (valid.length === 0) return null;',
          '',
          '  const min = Math.min(...valid);',
          '  const max = Math.max(...valid);',
          '  return { min, max, spread: max - min };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Filtering with `Number.isFinite` handles the invalid entries elegantly — passing the function reference directly works because `isFinite` takes one argument, so the extra index and array that `filter` supplies are harmless. The emptiness check after filtering is essential and catches both listed edge cases: `Math.min()` with no arguments returns `Infinity` and `Math.max()` returns `-Infinity`, so without the guard an all-invalid array would produce a nonsensical `{ min: Infinity, max: -Infinity, spread: -Infinity }` instead of `null`. For very large arrays, spread could exceed the argument limit and `reduce` would be the safer choice.',
      },
    ],
    quiz: {
      id: 'qz-m06-03',
      questions: [
        {
          id: 'q-m06-03-1',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['numbers'],
          prompt: 'Why is this not -3?',
          code: ['console.log(Math.round(-2.5));'].join('\n'),
          options: ['-3', '-2', '-2.5', '2'],
          correct: 1,
          optionExplanations: [
            'That would be rounding away from zero, which is not the rule.',
            'Correct — exact halves round towards positive infinity.',
            '`round` returns an integer.',
            'The sign is preserved.',
          ],
          explanation:
            '`Math.round` sends an exact half towards positive infinity, so `2.5` becomes `3` and `-2.5` becomes `-2`. The behaviour is asymmetric about zero, which surprises people expecting "round half away from zero".',
        },
        {
          id: 'q-m06-03-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['numbers'],
          prompt: 'In `Math.floor(Math.random() * (max - min + 1)) + min`, what does the `+ 1` do?',
          options: [
            'Avoids ever returning zero',
            'Makes the range inclusive of `max`, which `Math.random()` could otherwise never reach',
            'Compensates for floating-point error',
            'Nothing; it can be removed',
          ],
          correct: 1,
          optionExplanations: [
            'Zero is returned normally when it is inside the range.',
            'Correct — without it, `max` is unreachable.',
            'No floating-point compensation is involved.',
            'Removing it makes the maximum impossible.',
          ],
          explanation:
            '`Math.random()` returns a value strictly less than 1, so multiplying by `(max - min)` and flooring can never produce the top value. The `+ 1` widens the range by one so `max` becomes reachable, making both ends inclusive.',
        },
        {
          id: 'q-m06-03-3',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['numbers'],
          prompt: 'Why does this give NaN?',
          code: ['console.log(Math.max([1, 2, 3]));'].join('\n'),
          options: ['3', 'NaN', '[1, 2, 3]', '1'],
          correct: 1,
          optionExplanations: [
            'That requires spreading the array into separate arguments.',
            'Correct — the array is converted to a number, which fails.',
            '`Math.max` always returns a number.',
            'No element is selected.',
          ],
          explanation:
            '`Math.max` takes individual arguments, not an array. Passing an array converts it to a number — `Number([1,2,3])` is `NaN` because the string `"1,2,3"` is not numeric. Use `Math.max(...arr)`, or `reduce` for very large arrays where spread could exceed the argument limit.',
        },
        {
          id: 'q-m06-03-4',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['numbers', 'security'],
          prompt: '`Math.random()` is suitable for generating password reset tokens.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Its output is predictable and not cryptographically secure.',
            'Correct — use the crypto APIs for anything security-sensitive.',
          ],
          explanation:
            '`Math.random()` is fast and statistically reasonable but predictable, so it must never be used for tokens, session identifiers or keys. Use `crypto.getRandomValues()` in the browser, `crypto.randomBytes()` in Node, or `crypto.randomUUID()` for a secure unique identifier.',
        },
      ],
    },
    summary:
      '`Math` is a plain object of static methods. The four rounding methods agree on positive numbers and diverge on negatives: `round` sends exact halves towards positive infinity so `-2.5` gives `-2`, `floor` always rounds down, `ceil` always up, and `trunc` simply drops the fraction — so `floor` and `trunc` differ for negatives, which is a classic source of off-by-one bugs. `Math.random()` returns 0 ≤ r < 1, and the inclusive integer formula scales by `(max - min + 1)`, floors, then shifts by `min`; it is fast but predictable and must never be used for security. `Math.min` and `Math.max` take arguments rather than an array, so spread bridges the gap — remembering that with no arguments they return the identity values `Infinity` and `-Infinity`, which an empty array will produce.',
    keyTakeaways: [
      '`Math.round(-2.5)` is `-2` — halves round towards positive infinity',
      '`Math.floor` and `Math.trunc` differ only for negatives',
      'Inclusive random integer: `Math.floor(Math.random() * (max - min + 1)) + min`',
      '`Math.random()` is not cryptographically secure',
      '`Math.max(...arr)` needs spread; an empty array yields `-Infinity`',
      '`clamp` is `Math.min(Math.max(v, lo), hi)`',
    ],
    relatedLessons: ['l-m06-01', 'l-m04-01'],
    interviewConnections: [
      'What is the difference between Math.floor and Math.trunc?',
      'How do you generate a random integer between two values inclusive?',
      'Why can you not pass an array to Math.max?',
      'Is Math.random() safe for generating tokens?',
    ],
  },
];
