import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm07';

export default [
  /* ================================================================== */
  {
    id: 'l-m07-01',
    slug: 'if-else-conditions',
    moduleId: M,
    order: 1,
    title: 'if, else and Building Conditions',
    description: 'Branching on a condition, chaining alternatives, and writing conditions that read as sentences.',
    difficulty: DIFFICULTY.BEGINNER,
    estimatedMinutes: 14,
    xp: 25,
    topicIds: ['control-flow', 'booleans'],
    prerequisites: ['l-m06-03'],
    learningObjectives: [
      'Write `if`, `else if` and `else` branches correctly',
      'Explain why only the first matching branch in a chain runs',
      'Combine conditions with `&&` and `||` readably',
      'Recognise why braces should always be used',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          'Everything so far has run top to bottom, every line, every time. **Control flow** is how a program takes different paths depending on its data — and `if` is the most fundamental form of it.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The three shapes: if, if/else, and a chain.',
        code: [
          'const temperature = 18;',
          '',
          '// Just if',
          'if (temperature > 30) {',
          '  console.log("It is hot");',
          '}',
          '',
          '// if / else — exactly one branch runs',
          'if (temperature > 20) {',
          '  console.log("Warm enough");',
          '} else {',
          '  console.log("Bring a jacket");',
          '}',
          '',
          '// A chain — the first true condition wins',
          'if (temperature > 30) {',
          '  console.log("Hot");',
          '} else if (temperature > 20) {',
          '  console.log("Warm");',
          '} else if (temperature > 10) {',
          '  console.log("Mild");',
          '} else {',
          '  console.log("Cold");',
          '}',
        ].join('\n'),
        output: ['Bring a jacket', 'Mild'].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Only the first match runs',
        body: [
          'In an `if / else if` chain, JavaScript tests each condition in order and stops at the first one that is true. Every later condition is skipped entirely, even if it would also have been true.',
          'That is why the chain above prints only `"Mild"` — the temperature of 18 also fails `> 20`, but had it been 25 it would print `"Warm"` and never reach the `> 10` test.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Order matters in a chain',
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Wrong order — later branches unreachable',
          code: [
            'if (score > 50) {',
            '  return "pass";',
            '} else if (score > 90) {',
            '  return "excellent";',
            '}',
            '',
            '// A score of 95 returns "pass",',
            '// because it matched the first',
            '// condition. "excellent" can',
            '// never be reached.',
          ].join('\n'),
        },
        right: {
          title: 'Correct — most specific first',
          code: [
            'if (score > 90) {',
            '  return "excellent";',
            '} else if (score > 50) {',
            '  return "pass";',
            '}',
            '',
            '// A score of 95 now returns',
            '// "excellent" as intended.',
          ].join('\n'),
        },
        note: 'When conditions overlap, order them from most specific to least. This is one of the most common logic bugs in beginner code, and it produces no error — merely the wrong answer.',
      },
      {
        kind: SECTION.HEADING,
        text: 'Building conditions',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Combining tests with the logical operators.',
        code: [
          'const age = 25;',
          'const hasTicket = true;',
          'const isBanned = false;',
          '',
          '// Both must hold',
          'if (age >= 18 && hasTicket) {',
          '  console.log("Entry allowed");',
          '}',
          '',
          '// Either will do',
          'if (age < 5 || age >= 65) {',
          '  console.log("Discount applies");',
          '} else {',
          '  console.log("Full price");',
          '}',
          '',
          '// Negation',
          'if (!isBanned) {',
          '  console.log("Not on the banned list");',
          '}',
        ].join('\n'),
        output: ['Entry allowed', 'Full price', 'Not on the banned list'].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'You cannot chain a comparison against two values',
        body: [
          'Writing `if (age >= 18 && <= 65)` is a SyntaxError — each side of `&&` must be a complete condition. And as you saw in the operators module, `if (18 <= age <= 65)` parses but is nonsense: it evaluates `(18 <= age)` to a boolean, then compares that boolean against 65.',
          'Write the variable out in full on both sides: `age >= 18 && age <= 65`.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Name your conditions',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'A condition with three or more parts becomes hard to read inline. Extracting it into a well-named boolean turns the `if` into something that reads like a sentence — and makes the logic testable and reusable.',
        ],
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Inline — requires decoding',
          code: [
            'if (',
            '  user.age >= 18 &&',
            '  user.verified &&',
            '  !user.banned &&',
            '  user.credits > 0',
            ') {',
            '  startGame();',
            '}',
          ].join('\n'),
        },
        right: {
          title: 'Named — reads as intent',
          code: [
            'const isEligible =',
            '  user.age >= 18 &&',
            '  user.verified &&',
            '  !user.banned;',
            '',
            'const canAfford = user.credits > 0;',
            '',
            'if (isEligible && canAfford) {',
            '  startGame();',
            '}',
          ].join('\n'),
        },
        note: 'The right-hand version also fails more usefully: when something goes wrong you can log `isEligible` and `canAfford` separately to see which one blocked, rather than re-reading a four-part expression.',
      },
      {
        kind: SECTION.HEADING,
        text: 'Always use braces',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'JavaScript allows a single statement without braces. It is legal, it is shorter, and it has caused real security incidents.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The bug braces prevent.',
        code: [
          'let count = 0;',
          'const ready = false;',
          '',
          '// Someone adds a second line, forgetting the braces are missing',
          'if (ready)',
          '  console.log("starting");',
          '  count = 1;          // NOT part of the if — always runs',
          '',
          'console.log("ready:", ready, "count:", count);',
        ].join('\n'),
        output: ['ready: false count: 1'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The indentation says `count = 1` belongs to the `if`. JavaScript disagrees — only the first statement is conditional, so `count` becomes 1 even though `ready` is false. The code looks correct and behaves otherwise.',
          'Always use braces, even for one line. Every mainstream style guide requires it, and formatters add them automatically.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const score = 95;',
          '',
          'if (score > 50) {',
          '  console.log("pass");',
          '} else if (score > 90) {',
          '  console.log("excellent");',
          '}',
        ].join('\n'),
        options: [
          '"pass" only',
          '"excellent" only',
          'Both "pass" and "excellent"',
          'Nothing',
        ],
        correct: 0,
        explanation:
          'A chain stops at the first true condition. `95 > 50` is true, so `"pass"` prints and the entire rest of the chain is skipped — the `> 90` test is never even evaluated. The `"excellent"` branch is unreachable for every possible score, because any value above 90 is also above 50. Reordering so the most specific condition comes first fixes it. Note this produces no error at all, which is what makes it easy to miss.',
      },
    ],
    exercises: [
      {
        id: 'ex-m07-01-a',
        title: 'Spot the unreachable branch',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.EASY,
        xp: 10,
        topicIds: ['control-flow'],
        instructions:
          'In a chain `if (n > 0) ... else if (n > 100) ...`, why can the second branch never run?',
        options: [
          'Because `else if` is not valid after `if`',
          'Because any number greater than 100 is also greater than 0, so the first condition always matches first',
          'Because the conditions must be in ascending order',
          'Because `n` can only be compared once',
        ],
        correct: 1,
        hints: [
          'What happens to the rest of the chain once a condition is true?',
        ],
        solution: 'Because any number greater than 100 is also greater than 0, so the first condition always matches first',
        solutionExplanation:
          'A chain evaluates conditions in order and stops at the first true one. Since `n > 100` implies `n > 0`, the first branch always catches those values and the second is unreachable. The fix is to order overlapping conditions from most specific to least specific — test `n > 100` first. This produces no error, just silently wrong behaviour, which is why it survives review so easily.',
      },
      {
        id: 'ex-m07-01-b',
        title: 'Fix the branch order',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['control-flow'],
        instructions:
          'This function should return `"large"` for 100 or more, `"medium"` for 10 or more, and `"small"` otherwise. Every input currently returns `"small"` or `"medium"`. Fix the ordering.',
        starterCode: [
          'function sizeOf(n) {',
          '  if (n >= 10) {',
          '    return "medium";',
          '  } else if (n >= 100) {',
          '    return "large";',
          '  } else {',
          '    return "small";',
          '  }',
          '}',
        ].join('\n'),
        tests: [
          { name: 'classifies large values', body: 'expect(sizeOf(500)).toBe("large"); expect(sizeOf(100)).toBe("large");' },
          { name: 'classifies medium values', body: 'expect(sizeOf(50)).toBe("medium"); expect(sizeOf(10)).toBe("medium");' },
          { name: 'classifies small values', body: 'expect(sizeOf(5)).toBe("small"); expect(sizeOf(0)).toBe("small");' },
          { name: 'handles the boundary at 99', body: 'expect(sizeOf(99)).toBe("medium");' },
          { name: 'handles negatives', body: 'expect(sizeOf(-10)).toBe("small");', hidden: true },
        ],
        hints: [
          'Which condition currently catches values it should not?',
          'Order overlapping conditions from most specific to least specific.',
          'Test `n >= 100` before `n >= 10`.',
        ],
        solution: [
          'function sizeOf(n) {',
          '  if (n >= 100) {',
          '    return "large";',
          '  } else if (n >= 10) {',
          '    return "medium";',
          '  } else {',
          '    return "small";',
          '  }',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Swapping the first two branches is the whole fix. Because `n >= 100` implies `n >= 10`, the original chain caught every large value in the `"medium"` branch and never reached `"large"`. Ordering from most specific to least means each later condition only sees values the earlier ones rejected — so `n >= 10` implicitly means "between 10 and 99" by the time it runs. That implicit narrowing is what makes chains readable, and it only works when the order is right.',
      },
      {
        id: 'ex-m07-01-c',
        title: 'Write an eligibility check',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['control-flow', 'booleans'],
        instructions:
          'Write `canVote(person)` returning `true` only when the person is 18 or over, is registered, and is not disqualified. The object has `age`, `registered` and `disqualified` properties.',
        starterCode: [
          'function canVote(person) {',
          '  // Name the parts if it helps readability.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'accepts an eligible person', body: 'expect(canVote({ age: 30, registered: true, disqualified: false })).toBe(true);' },
          { name: 'rejects someone too young', body: 'expect(canVote({ age: 17, registered: true, disqualified: false })).toBe(false);' },
          { name: 'accepts exactly 18', body: 'expect(canVote({ age: 18, registered: true, disqualified: false })).toBe(true);' },
          { name: 'rejects the unregistered', body: 'expect(canVote({ age: 30, registered: false, disqualified: false })).toBe(false);' },
          { name: 'rejects the disqualified', body: 'expect(canVote({ age: 30, registered: true, disqualified: true })).toBe(true === false);' },
          { name: 'returns a real boolean', body: 'expect(typeof canVote({ age: 30, registered: true, disqualified: false })).toBe("boolean");', hidden: true },
        ],
        hints: [
          'Three conditions joined with `&&`.',
          'Use `!person.disqualified` for the negative condition.',
          'You can return the combined expression directly — no `if` is needed.',
        ],
        solution: [
          'function canVote(person) {',
          '  const isOldEnough = person.age >= 18;',
          '  const isAllowed = person.registered && !person.disqualified;',
          '  return isOldEnough && isAllowed;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'No `if` is needed at all here — the condition *is* the answer, so returning it directly is clearer than `if (cond) return true; else return false;`, which is a common redundancy worth learning to spot. Naming the two halves makes the intent readable and gives you something to log when debugging. The hidden test checks the return is a genuine boolean: because `&&` returns an operand rather than a boolean, an expression like `person.age >= 18 && person.registered` would return the raw `registered` value — which happens to be boolean here, but would not be if the property held a string or a number.',
      },
    ],
    quiz: {
      id: 'qz-m07-01',
      questions: [
        {
          id: 'q-m07-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['control-flow'],
          prompt: 'In an `if / else if / else` chain, how many branches run?',
          options: [
            'All whose conditions are true',
            'Exactly one — the first whose condition is true, or the `else`',
            'Always exactly two',
            'None unless an `else` is present',
          ],
          correct: 1,
          optionExplanations: [
            'Evaluation stops at the first match.',
            'Correct — later conditions are never even evaluated.',
            'Only one branch of a chain executes.',
            'A chain without an `else` simply runs nothing when no condition matches.',
          ],
          explanation:
            'A chain tests conditions in order and executes the body of the first true one, skipping everything after it. If none match and there is an `else`, that runs; otherwise nothing does.',
        },
        {
          id: 'q-m07-01-2',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['control-flow'],
          prompt: 'What is the value of `count` afterwards?',
          code: [
            'let count = 0;',
            'if (false)',
            '  count = 1;',
            '  count = 2;',
            'console.log(count);',
          ].join('\n'),
          options: ['0', '1', '2', 'undefined'],
          correct: 2,
          optionExplanations: [
            'The second assignment is not conditional.',
            'That line is inside the `if` and does not run.',
            'Correct — without braces only the first statement is conditional.',
            '`count` was initialised to 0 and then assigned.',
          ],
          explanation:
            'Without braces, only the single statement immediately after `if (...)` is conditional. The second assignment is an ordinary statement that always runs, despite the indentation suggesting otherwise. This is why every style guide requires braces.',
        },
        {
          id: 'q-m07-01-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['control-flow'],
          prompt: 'How do you test that `age` is between 18 and 65 inclusive?',
          options: [
            '`if (18 <= age <= 65)`',
            '`if (age >= 18 && age <= 65)`',
            '`if (age >= 18 && <= 65)`',
            '`if (age between 18, 65)`',
          ],
          correct: 1,
          optionExplanations: [
            'This parses but compares a boolean against 65.',
            'Correct — each side of `&&` is a complete condition.',
            'This is a SyntaxError; the second comparison has no left operand.',
            'There is no `between` operator in JavaScript.',
          ],
          explanation:
            'Each operand of `&&` must be a complete condition, so the variable is written out on both sides. The chained form `18 <= age <= 65` evaluates left to right, producing a boolean that is then compared numerically against 65 — legal, but meaningless.',
        },
      ],
    },
    summary:
      '`if` executes a block only when its condition is truthy; `else if` and `else` provide alternatives, and a chain runs exactly one branch — the first whose condition is true. That "first match wins" rule makes ordering critical: when conditions overlap, the most specific must come first, or later branches become unreachable and the code silently produces wrong answers with no error. Conditions are built with `&&`, `||` and `!`, and each operand must be a complete comparison — the variable is written out on both sides. Extracting a multi-part condition into a well-named boolean makes the `if` read as intent and gives you something to inspect when debugging. Always use braces: without them only the first statement is conditional, regardless of indentation.',
    keyTakeaways: [
      'A chain runs exactly one branch — the first true condition wins',
      'Order overlapping conditions from most specific to least',
      'Each side of `&&` must be a complete condition',
      'Name multi-part conditions to make the `if` read as a sentence',
      'Always use braces; indentation has no meaning to the parser',
    ],
    relatedLessons: ['l-m03-03', 'l-m07-02'],
    interviewConnections: [
      'How does an if/else if chain decide which branch runs?',
      'Why should you always use braces with if?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m07-02',
    slug: 'switch-statements',
    moduleId: M,
    order: 2,
    title: 'switch and Fall-Through',
    description: 'Matching one value against many cases, the missing-break bug, and when a lookup object is better.',
    difficulty: DIFFICULTY.EASY,
    estimatedMinutes: 14,
    xp: 30,
    topicIds: ['control-flow'],
    prerequisites: ['l-m07-01'],
    learningObjectives: [
      'Write a `switch` with correct `break` statements',
      'Explain fall-through and use it deliberately',
      'Explain why `switch` uses strict equality',
      'Choose between `switch`, an `if` chain and a lookup object',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          '`switch` compares one value against several possibilities. It is a specialised tool: it only tests **equality**, so anything involving ranges or compound conditions still needs `if`.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A standard switch with breaks.',
        code: [
          'function describeDay(day) {',
          '  switch (day) {',
          '    case "saturday":',
          '      return "Weekend";',
          '    case "sunday":',
          '      return "Weekend";',
          '    case "friday":',
          '      return "Almost there";',
          '    default:',
          '      return "Weekday";',
          '  }',
          '}',
          '',
          'console.log(describeDay("saturday"));',
          'console.log(describeDay("friday"));',
          'console.log(describeDay("tuesday"));',
          'console.log(describeDay("nonsense"));',
        ].join('\n'),
        output: ['Weekend', 'Almost there', 'Weekday', 'Weekday'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Note there are no `break` statements here — `return` exits the whole function, which makes `break` unnecessary. When a switch assigns to a variable rather than returning, `break` becomes essential.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Fall-through: the classic bug',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Without `break`, execution continues into the following cases.',
        code: [
          'function priceFor(size) {',
          '  let price = 0;',
          '',
          '  switch (size) {',
          '    case "small":',
          '      price = 3;',
          '    case "medium":',
          '      price = 4;',
          '    case "large":',
          '      price = 5;',
          '  }',
          '',
          '  return price;',
          '}',
          '',
          'console.log(priceFor("small"));',
          'console.log(priceFor("medium"));',
          'console.log(priceFor("large"));',
        ].join('\n'),
        output: ['5', '5', '5'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Every call returns 5. Once a case matches, execution continues **through every case below it** until a `break`, a `return`, or the end of the switch. `"small"` sets the price to 3, then falls into `"medium"` and sets 4, then into `"large"` and sets 5.',
          'The case labels are entry points, not self-contained blocks. That is the crucial mental model.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'A missing `break` is silent',
        body: [
          'Nothing warns you. The code parses, runs, and returns a plausible value — just the wrong one. This is why linters have a dedicated `no-fallthrough` rule, and why many teams prefer `return` inside each case so the question cannot arise.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Deliberate fall-through',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Stacking cases is the one legitimate use.',
        code: [
          'function categorise(day) {',
          '  switch (day) {',
          '    case "saturday":',
          '    case "sunday":',
          '      return "weekend";',
          '',
          '    case "monday":',
          '    case "tuesday":',
          '    case "wednesday":',
          '    case "thursday":',
          '    case "friday":',
          '      return "weekday";',
          '',
          '    default:',
          '      return "unknown";',
          '  }',
          '}',
          '',
          'console.log(categorise("sunday"), categorise("wednesday"), categorise("x"));',
        ].join('\n'),
        output: ['weekend weekday unknown'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Empty cases stacked above a shared body are idiomatic and widely understood. If you ever fall through from a case that *has* a body, add a comment saying so deliberately — otherwise the next reader will assume it is a bug and "fix" it.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: '`switch` uses strict equality',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'No coercion happens — `"1"` does not match `1`.',
        code: [
          'function check(value) {',
          '  switch (value) {',
          '    case 1:  return "number one";',
          '    case "1": return "string one";',
          '    default: return "no match";',
          '  }',
          '}',
          '',
          'console.log(check(1));',
          'console.log(check("1"));',
          'console.log(check(true));',
        ].join('\n'),
        output: ['number one', 'string one', 'no match'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`switch` compares with `===`, so there is no coercion. `check(true)` finds no match even though `true == 1` under loose equality. This is generally what you want, but it does mean a value read from a form — always a string — will never match a numeric case.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: '`let` and `const` inside a case need braces',
        body: [
          'All the cases share one block scope, so declaring `const x` in two different cases is a redeclaration SyntaxError — even though only one case can run.',
          'Wrap the case body in its own braces to give it a scope: `case "a": { const x = 1; break; }`. This is a genuine gotcha that produces a confusing error message.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'When to use a lookup object instead',
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'switch',
          code: [
            'function labelFor(status) {',
            '  switch (status) {',
            '    case "active":',
            '      return "Active";',
            '    case "paused":',
            '      return "On hold";',
            '    case "closed":',
            '      return "Closed";',
            '    default:',
            '      return "Unknown";',
            '  }',
            '}',
          ].join('\n'),
        },
        right: {
          title: 'Lookup object',
          code: [
            'const LABELS = {',
            '  active: "Active",',
            '  paused: "On hold",',
            '  closed: "Closed",',
            '};',
            '',
            'function labelFor(status) {',
            '  return LABELS[status] ?? "Unknown";',
            '}',
          ].join('\n'),
        },
        note: 'For a pure value-to-value mapping the object is shorter, has no fall-through risk, and — importantly — the data can be defined elsewhere, reused, iterated, or loaded from a configuration file. Use `switch` when the branches contain real logic rather than just a value.',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A lookup object holding functions handles logic too.',
        code: [
          'const HANDLERS = {',
          '  add: (a, b) => a + b,',
          '  subtract: (a, b) => a - b,',
          '  multiply: (a, b) => a * b,',
          '};',
          '',
          'function calculate(operation, a, b) {',
          '  const handler = HANDLERS[operation];',
          '  if (typeof handler !== "function") return null;',
          '  return handler(a, b);',
          '}',
          '',
          'console.log(calculate("add", 2, 3));',
          'console.log(calculate("multiply", 4, 5));',
          'console.log(calculate("divide", 8, 2));',
        ].join('\n'),
        output: ['5', '20', 'null'].join('\n'),
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'function f(x) {',
          '  let out = "";',
          '  switch (x) {',
          '    case 1:',
          '      out += "a";',
          '    case 2:',
          '      out += "b";',
          '      break;',
          '    case 3:',
          '      out += "c";',
          '  }',
          '  return out;',
          '}',
          '',
          'console.log(f(1), f(2), f(3));',
        ].join('\n'),
        options: [
          '"ab" "b" "c"',
          '"a" "b" "c"',
          '"abc" "bc" "c"',
          '"ab" "bc" "c"',
        ],
        correct: 0,
        explanation:
          '`f(1)` enters at case 1, appends `"a"`, then falls through into case 2 because there is no `break` — appending `"b"` — and stops at the `break`, giving `"ab"`. `f(2)` enters at case 2, appends `"b"`, and hits the `break` immediately, giving `"b"`. `f(3)` enters at case 3, appends `"c"`, and reaches the end of the switch, giving `"c"`. Case labels are entry points, not enclosed blocks.',
      },
    ],
    exercises: [
      {
        id: 'ex-m07-02-a',
        title: 'Predict the fall-through',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.EASY,
        xp: 15,
        topicIds: ['control-flow'],
        instructions: 'What does this print?',
        code: [
          'let result = "";',
          'switch (2) {',
          '  case 1: result += "one";',
          '  case 2: result += "two";',
          '  case 3: result += "three";',
          '}',
          'console.log(result);',
        ].join('\n'),
        options: ['"two"', '"twothree"', '"onetwothree"', '""'],
        correct: 1,
        hints: [
          'Which case does execution enter at?',
          'What stops it continuing into the cases below?',
        ],
        solution: '"twothree"',
        solutionExplanation:
          'Execution enters at `case 2` and appends `"two"`. With no `break`, it continues straight into `case 3` and appends `"three"`, then reaches the end of the switch. `case 1` is skipped entirely because entry happens at the matching label. The result is `"twothree"`. Case labels mark where to start, not a self-contained block — which is why a missing `break` produces plausible but wrong output rather than an error.',
      },
      {
        id: 'ex-m07-02-b',
        title: 'Fix the missing breaks',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['control-flow'],
        instructions:
          'This function should return the number of days in a season. Every input currently returns the same value. Fix it without restructuring the switch.',
        starterCode: [
          'function seasonDays(season) {',
          '  let days = 0;',
          '  switch (season) {',
          '    case "winter":',
          '      days = 90;',
          '    case "spring":',
          '      days = 92;',
          '    case "summer":',
          '      days = 93;',
          '    case "autumn":',
          '      days = 90;',
          '  }',
          '  return days;',
          '}',
        ].join('\n'),
        tests: [
          { name: 'winter is 90', body: 'expect(seasonDays("winter")).toBe(90);' },
          { name: 'spring is 92', body: 'expect(seasonDays("spring")).toBe(92);' },
          { name: 'summer is 93', body: 'expect(seasonDays("summer")).toBe(93);' },
          { name: 'autumn is 90', body: 'expect(seasonDays("autumn")).toBe(90);' },
          { name: 'an unknown season is 0', body: 'expect(seasonDays("monsoon")).toBe(0);', hidden: true },
        ],
        hints: [
          'Execution continues into the cases below the one that matched.',
          'Add a statement that exits the switch after each assignment.',
          '`break` is the keyword.',
        ],
        solution: [
          'function seasonDays(season) {',
          '  let days = 0;',
          '  switch (season) {',
          '    case "winter":',
          '      days = 90;',
          '      break;',
          '    case "spring":',
          '      days = 92;',
          '      break;',
          '    case "summer":',
          '      days = 93;',
          '      break;',
          '    case "autumn":',
          '      days = 90;',
          '      break;',
          '  }',
          '  return days;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Without `break`, every match fell through to the final case and returned 90 regardless of input. Adding `break` after each assignment stops execution leaving the switch at the right point. The `break` on the last case is not strictly required — the switch ends there anyway — but including it is the conventional habit, because it stops a future case being appended below and silently reintroducing the bug. An alternative fix returns directly from each case, removing the need for `break` and for the `days` variable entirely.',
      },
      {
        id: 'ex-m07-02-c',
        title: 'Convert a switch to a lookup',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['control-flow', 'clean-code'],
        instructions:
          'This switch maps a status code to a message and contains no real logic. Rewrite it using a lookup object and `??` for the default. Behaviour must be identical.',
        starterCode: [
          'function statusMessage(code) {',
          '  switch (code) {',
          '    case 200: return "OK";',
          '    case 404: return "Not Found";',
          '    case 500: return "Server Error";',
          '    default: return "Unknown";',
          '  }',
          '}',
        ].join('\n'),
        tests: [
          { name: 'maps 200', body: 'expect(statusMessage(200)).toBe("OK");' },
          { name: 'maps 404', body: 'expect(statusMessage(404)).toBe("Not Found");' },
          { name: 'maps 500', body: 'expect(statusMessage(500)).toBe("Server Error");' },
          { name: 'falls back for an unknown code', body: 'expect(statusMessage(418)).toBe("Unknown");' },
          { name: 'falls back for undefined', body: 'expect(statusMessage(undefined)).toBe("Unknown");' },
          { name: 'contains no switch statement', body: 'expect(/\\bswitch\\b/.test(statusMessage.toString())).toBe(false);', hidden: true },
        ],
        hints: [
          'Numeric keys work in an object literal: `{ 200: "OK" }`.',
          'Look the code up with bracket notation: `MESSAGES[code]`.',
          'Use `??` rather than `||` so a legitimately falsy mapped value would survive.',
        ],
        solution: [
          'const STATUS_MESSAGES = {',
          '  200: "OK",',
          '  404: "Not Found",',
          '  500: "Server Error",',
          '};',
          '',
          'function statusMessage(code) {',
          '  return STATUS_MESSAGES[code] ?? "Unknown";',
          '}',
        ].join('\n'),
        solutionExplanation:
          'For a pure value-to-value mapping the object is shorter, cannot suffer fall-through, and separates the data from the logic — the table could now be exported, iterated to build a documentation page, or loaded from configuration. Object keys are always strings internally, so the numeric key `200` becomes `"200"` and the lookup `STATUS_MESSAGES[200]` converts the number back to `"200"` automatically, which is why this works without any explicit conversion. Using `??` rather than `||` matters as a habit: if a mapped value were ever `""` or `0`, `||` would wrongly replace it with the fallback.',
      },
    ],
    quiz: {
      id: 'qz-m07-02',
      questions: [
        {
          id: 'q-m07-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['control-flow'],
          prompt: 'What happens when a `case` body has no `break`?',
          options: [
            'The switch ends after that case',
            'Execution continues into the following cases until a break, return, or the end of the switch',
            'A SyntaxError is thrown',
            'Only the default case runs',
          ],
          correct: 1,
          optionExplanations: [
            'That is what `break` would cause.',
            'Correct — this is fall-through.',
            'Missing breaks are entirely legal, which is why the bug is silent.',
            '`default` only runs when nothing matches.',
          ],
          explanation:
            'Case labels are entry points rather than enclosed blocks. Once a case matches, execution runs through every subsequent case body until it hits `break`, `return`, or the end of the switch. Nothing warns you, which is why linters provide a `no-fallthrough` rule.',
        },
        {
          id: 'q-m07-02-2',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['control-flow', 'coercion'],
          prompt: 'Does the string match the numeric case?',
          code: [
            'switch ("1") {',
            '  case 1: console.log("number"); break;',
            '  default: console.log("no match");',
            '}',
          ].join('\n'),
          options: ['number', 'no match', 'Both', 'Nothing'],
          correct: 1,
          optionExplanations: [
            'That would require loose equality.',
            'Correct — `switch` compares with `===`, so no coercion occurs.',
            'Only one branch runs.',
            '`default` catches the unmatched value.',
          ],
          explanation:
            '`switch` uses strict equality, so `"1"` never matches `case 1`. This matters in practice because form inputs are always strings — convert before switching, or use string cases.',
        },
        {
          id: 'q-m07-02-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['control-flow', 'clean-code'],
          prompt: 'When is a lookup object a better choice than a `switch`?',
          options: [
            'Always — `switch` is deprecated',
            'When the branches map a value to another value with no real logic',
            'When there are fewer than three cases',
            'When the cases are numbers',
          ],
          correct: 1,
          optionExplanations: [
            '`switch` is entirely current and better when branches contain logic.',
            'Correct — a pure mapping is data, and data belongs in a data structure.',
            'Case count is not the deciding factor.',
            'Both handle numeric keys fine.',
          ],
          explanation:
            'A pure value-to-value mapping is data, so an object expresses it more directly: shorter, no fall-through risk, and reusable or loadable from configuration. Keep `switch` for branches that contain genuine logic — or use an object whose values are functions.',
        },
        {
          id: 'q-m07-02-4',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['control-flow', 'variables'],
          prompt: 'You can declare `const x` in two different cases of the same switch without braces.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'All cases share a single block scope.',
            'Correct — it is a redeclaration SyntaxError.',
          ],
          explanation:
            'Every case shares one block scope, so two `const x` declarations collide even though only one case can execute. Wrap each case body in its own braces — `case "a": { const x = 1; break; }` — to give it a scope of its own.',
        },
      ],
    },
    summary:
      '`switch` compares one value against several cases using **strict equality**, so no coercion happens and a form string will never match a numeric case. Case labels are entry points rather than enclosed blocks: once one matches, execution continues through every case below it until `break`, `return`, or the end of the switch. A missing `break` produces plausible but wrong output with no warning, which is why linters flag it and why returning directly from each case is a popular defence. Stacking empty cases above a shared body is the one idiomatic use of deliberate fall-through. All cases share a single block scope, so `let` and `const` need their own braces. When branches merely map one value to another, a lookup object is shorter, safer and keeps the data separate from the logic.',
    keyTakeaways: [
      '`switch` uses `===` — no coercion, so `"1"` never matches `case 1`',
      'Case labels are entry points; execution falls through without `break`',
      'A missing `break` is silent — no error, just wrong output',
      'Stacked empty cases are the idiomatic deliberate fall-through',
      'All cases share one scope; wrap a case in braces to declare in it',
      'Prefer a lookup object when branches only map values',
    ],
    relatedLessons: ['l-m07-01', 'l-m07-03'],
    interviewConnections: [
      'What is fall-through in a switch statement?',
      'Does switch use == or ===?',
      'When would you use an object lookup instead of a switch?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m07-03',
    slug: 'guard-clauses-and-patterns',
    moduleId: M,
    order: 3,
    title: 'Guard Clauses and Flattening Logic',
    description: 'Early returns, the arrow anti-pattern, and how professionals structure decisions.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 15,
    xp: 35,
    topicIds: ['control-flow', 'clean-code'],
    prerequisites: ['l-m07-02'],
    learningObjectives: [
      'Rewrite nested conditions as guard clauses',
      'Explain why early returns reduce cognitive load',
      'Recognise and remove redundant conditional patterns',
      'Choose between `if`, ternary and short-circuit forms deliberately',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          'Nested conditionals are the most common readability problem in real code. This lesson covers the standard techniques for flattening them — the difference between code a colleague can scan and code they have to decode.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The arrow anti-pattern',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Every check adds a level of indentation.',
        code: [
          'function processOrder(order) {',
          '  if (order) {',
          '    if (order.items) {',
          '      if (order.items.length > 0) {',
          '        if (order.paid) {',
          '          return "Processing " + order.items.length + " items";',
          '        } else {',
          '          return "Not paid";',
          '        }',
          '      } else {',
          '        return "Empty order";',
          '      }',
          '    } else {',
          '      return "No items";',
          '    }',
          '  } else {',
          '    return "No order";',
          '  }',
          '}',
          '',
          'console.log(processOrder({ items: ["a"], paid: true }));',
          'console.log(processOrder({ items: [], paid: true }));',
          'console.log(processOrder(null));',
        ].join('\n'),
        output: ['Processing 1 items', 'Empty order', 'No order'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The indentation forms an arrow shape pointing right, which is where the name comes from. The real problem is that the *success* path — the thing the function actually does — is buried at maximum depth, and each `else` is separated from its `if` by a growing distance.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The same logic as guard clauses',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Handle each failure and leave immediately.',
        code: [
          'function processOrder(order) {',
          '  if (!order) return "No order";',
          '  if (!order.items) return "No items";',
          '  if (order.items.length === 0) return "Empty order";',
          '  if (!order.paid) return "Not paid";',
          '',
          '  return "Processing " + order.items.length + " items";',
          '}',
          '',
          'console.log(processOrder({ items: ["a"], paid: true }));',
          'console.log(processOrder({ items: [], paid: true }));',
          'console.log(processOrder(null));',
        ].join('\n'),
        output: ['Processing 1 items', 'Empty order', 'No order'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Identical behaviour, seventeen lines reduced to seven, and nothing indented beyond one level. Three things improved at once.',
        ],
      },
      {
        kind: SECTION.LIST,
        items: [
          '**Each failure is handled where it is detected.** You never have to scroll to find the matching `else`.',
          '**Reading top to bottom builds up guarantees.** By the final line you know `order` exists, has items, has at least one, and is paid — the reader accumulates certainty rather than tracking possibilities.',
          '**The success path is at the bottom, unindented.** The most important line in the function is the easiest one to find.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Guard clauses are not "multiple returns are bad"',
        body: [
          'You may encounter an old rule that a function should have a single exit point. It comes from languages requiring manual memory cleanup, where every exit needed matching teardown. JavaScript has no such requirement.',
          'In modern JavaScript, early returns are actively preferred. The cognitive cost of tracking one nesting level per condition is far higher than the cost of several return statements.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Inverting a condition to guard',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The mechanical transformation is: take the outermost `if (condition) { ... }` that wraps the whole body, invert it, return early, and unindent everything else.',
        ],
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Wrapping condition',
          code: [
            'function save(user) {',
            '  if (user.isValid) {',
            '    const record = build(user);',
            '    database.write(record);',
            '    return record;',
            '  }',
            '}',
          ].join('\n'),
        },
        right: {
          title: 'Inverted guard',
          code: [
            'function save(user) {',
            '  if (!user.isValid) return;',
            '',
            '  const record = build(user);',
            '  database.write(record);',
            '  return record;',
            '}',
          ].join('\n'),
        },
        note: 'With one level the gain is small. Apply it three times in a nested function and the difference is dramatic — which is exactly what the order example above showed.',
      },
      {
        kind: SECTION.HEADING,
        text: 'Redundant patterns worth removing',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Four things that are always worth simplifying.',
        code: [
          '// 1. Returning booleans from a condition',
          '// if (age >= 18) { return true; } else { return false; }',
          'const isAdult = (age) => age >= 18;',
          'console.log(isAdult(20), isAdult(10));',
          '',
          '// 2. Comparing a boolean to true',
          '// if (isReady === true)',
          'const isReady = true;',
          'console.log(isReady ? "go" : "wait");',
          '',
          '// 3. Assigning in both branches',
          '// let label; if (ok) { label = "yes"; } else { label = "no"; }',
          'const ok = false;',
          'const label = ok ? "yes" : "no";',
          'console.log(label);',
          '',
          '// 4. An else after a return',
          '// if (x) { return 1; } else { return 2; }',
          'const value = (x) => {',
          '  if (x) return 1;',
          '  return 2;',
          '};',
          'console.log(value(true), value(false));',
        ].join('\n'),
        output: ['true false', 'go', 'no', '1 2'].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The fourth is worth dwelling on: after a `return`, an `else` adds nothing, because execution could not have reached that point anyway. Dropping it removes a level of indentation for free, and it is what makes guard clauses read so cleanly.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Choosing a form',
      },
      {
        kind: SECTION.TABLE,
        headers: ['Situation', 'Use'],
        rows: [
          ['Validating inputs at the top of a function', 'Guard clauses with early return'],
          ['Producing one of two values', 'Ternary'],
          ['Two or more branches that do real work', '`if` / `else if`'],
          ['Matching one value against many', '`switch` or a lookup object'],
          ['Running something only if a condition holds', '`if`, or `cond && action()`'],
          ['Supplying a default for a missing value', '`??`'],
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A realistic function combining several of these.',
        code: [
          'function describeUser(user) {',
          '  if (user == null) return "No user";',
          '  if (!user.name) return "Unnamed user";',
          '',
          '  const role = user.role ?? "member";',
          '  const status = user.active ? "active" : "inactive";',
          '  const badge = user.admin ? " (admin)" : "";',
          '',
          '  return `${user.name} — ${role}, ${status}${badge}`;',
          '}',
          '',
          'console.log(describeUser({ name: "Ada", active: true, admin: true }));',
          'console.log(describeUser({ name: "Grace", role: "editor", active: false }));',
          'console.log(describeUser({ active: true }));',
          'console.log(describeUser(null));',
        ].join('\n'),
        output: [
          'Ada — member, active (admin)',
          'Grace — editor, inactive',
          'Unnamed user',
          'No user',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Two guards at the top establish what is true for the rest of the function. Below them, each ternary produces exactly one value, and `??` supplies a default that would survive an empty-string role. Nothing is nested, and the shape of the output is visible in the final line.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'function check(n) {',
          '  if (n > 10) return "big";',
          '  if (n > 5) return "medium";',
          '  return "small";',
          '}',
          '',
          'console.log(check(20), check(7), check(2));',
        ].join('\n'),
        options: [
          '"big" "medium" "small"',
          '"big" "big" "small"',
          '"medium" "medium" "small"',
          '"small" "small" "small"',
        ],
        correct: 0,
        explanation:
          'Each `return` exits the function immediately, so the guards behave exactly like an `if / else if` chain without needing the `else` keywords. `check(20)` matches the first guard. `check(7)` fails `> 10` but matches `> 5`. `check(2)` fails both and falls through to the final return. The ordering rule from lesson 1 still applies — testing `n > 5` first would make `"big"` unreachable.',
      },
    ],
    exercises: [
      {
        id: 'ex-m07-03-a',
        title: 'Simplify the boolean return',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.BEGINNER,
        xp: 15,
        topicIds: ['control-flow', 'clean-code'],
        instructions:
          'Rewrite this function to return the condition directly, without any `if` statement. Behaviour must be identical.',
        starterCode: [
          'function isEven(n) {',
          '  if (n % 2 === 0) {',
          '    return true;',
          '  } else {',
          '    return false;',
          '  }',
          '}',
        ].join('\n'),
        tests: [
          { name: 'identifies even numbers', body: 'expect(isEven(4)).toBe(true); expect(isEven(0)).toBe(true);' },
          { name: 'identifies odd numbers', body: 'expect(isEven(3)).toBe(false);' },
          { name: 'handles negatives', body: 'expect(isEven(-4)).toBe(true); expect(isEven(-3)).toBe(false);' },
          { name: 'returns a real boolean', body: 'expect(typeof isEven(2)).toBe("boolean");' },
          { name: 'contains no if statement', body: 'expect(/\\bif\\b/.test(isEven.toString())).toBe(false);', hidden: true },
        ],
        hints: [
          'The condition already evaluates to `true` or `false`.',
          'Return it directly.',
          'The whole function body becomes one line.',
        ],
        solution: [
          'function isEven(n) {',
          '  return n % 2 === 0;',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`n % 2 === 0` already produces a boolean, so wrapping it in an `if` that returns `true` or `false` is pure ceremony — it restates what the comparison already said. This pattern appears constantly in beginner code and is always worth collapsing. Note the negative case works because `-4 % 2` is `-0`, and `-0 === 0` is `true`; had the check been `n % 2 !== 1` instead, negatives would have broken, since `-3 % 2` is `-1` rather than `1`.',
      },
      {
        id: 'ex-m07-03-b',
        title: 'Flatten the nesting',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['control-flow', 'clean-code'],
        instructions:
          'Rewrite this using guard clauses so nothing is indented more than one level. Behaviour must be identical.',
        starterCode: [
          'function getDiscount(user) {',
          '  if (user) {',
          '    if (user.membership) {',
          '      if (user.membership.active) {',
          '        if (user.membership.tier === "gold") {',
          '          return 20;',
          '        } else {',
          '          return 10;',
          '        }',
          '      } else {',
          '        return 0;',
          '      }',
          '    } else {',
          '      return 0;',
          '    }',
          '  } else {',
          '    return 0;',
          '  }',
          '}',
        ].join('\n'),
        tests: [
          { name: 'gold members get 20', body: 'expect(getDiscount({ membership: { active: true, tier: "gold" } })).toBe(20);' },
          { name: 'other active members get 10', body: 'expect(getDiscount({ membership: { active: true, tier: "silver" } })).toBe(10);' },
          { name: 'inactive members get 0', body: 'expect(getDiscount({ membership: { active: false, tier: "gold" } })).toBe(0);' },
          { name: 'users without membership get 0', body: 'expect(getDiscount({})).toBe(0);' },
          { name: 'null users get 0', body: 'expect(getDiscount(null)).toBe(0);' },
          { name: 'a missing argument gives 0', body: 'expect(getDiscount()).toBe(0);', hidden: true },
        ],
        hints: [
          'Every failure path returns the same value, so they can be combined.',
          'Invert each condition and return early.',
          'Optional chaining can collapse the first three checks into one.',
        ],
        solution: [
          'function getDiscount(user) {',
          '  if (!user?.membership?.active) return 0;',
          '  return user.membership.tier === "gold" ? 20 : 10;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Because all three failure paths return the same `0`, they collapse into a single guard. Optional chaining does the heavy lifting: `user?.membership?.active` short-circuits to `undefined` if `user` or `membership` is missing, and `!undefined` is `true`, so one condition covers a null user, a missing membership and an inactive one. The remaining decision produces one of two values, which is exactly what a ternary is for. Seventeen lines become two, with no behaviour change — the hidden test confirms an omitted argument is handled, since `undefined?.membership` short-circuits safely.',
      },
      {
        id: 'ex-m07-03-c',
        title: 'Write a validator with guards',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['control-flow', 'clean-code'],
        instructions:
          'Write `validatePassword(password)` returning an error string for the first rule broken, or `null` if valid. Rules in order: must not be missing (`"Required"`), at least 8 characters (`"Too short"`), must contain a digit (`"Needs a digit"`), must contain an uppercase letter (`"Needs an uppercase letter"`). Use guard clauses.',
        starterCode: [
          'function validatePassword(password) {',
          '  // One guard per rule, in order. Return null at the end.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'accepts a valid password', body: 'expect(validatePassword("Password1")).toBe(null);' },
          { name: 'rejects a missing password', body: 'expect(validatePassword(null)).toBe("Required"); expect(validatePassword("")).toBe("Required");' },
          { name: 'rejects a short password', body: 'expect(validatePassword("Ab1")).toBe("Too short");' },
          { name: 'rejects one with no digit', body: 'expect(validatePassword("Password")).toBe("Needs a digit");' },
          { name: 'rejects one with no uppercase', body: 'expect(validatePassword("password1")).toBe("Needs an uppercase letter");' },
          { name: 'reports only the first broken rule', body: 'expect(validatePassword("abc")).toBe("Too short");' },
          { name: 'accepts exactly eight characters', body: 'expect(validatePassword("Passwrd1")).toBe(null);', hidden: true },
        ],
        hints: [
          'Guard the nullish and empty cases together — an empty string is falsy.',
          '`/\\d/.test(password)` checks for a digit.',
          '`/[A-Z]/.test(password)` checks for an uppercase letter.',
          'Return `null` only after every guard has passed.',
        ],
        solution: [
          'function validatePassword(password) {',
          '  if (!password) return "Required";',
          '  if (password.length < 8) return "Too short";',
          '  if (!/\\d/.test(password)) return "Needs a digit";',
          '  if (!/[A-Z]/.test(password)) return "Needs an uppercase letter";',
          '',
          '  return null;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The guards run in the order the rules were specified, so the first failure short-circuits and later checks never run — which is what the "reports only the first broken rule" test verifies, and it is also better user experience than dumping four complaints at once. Using `!password` for the first guard deliberately catches `null`, `undefined` and `""` together, since all three are falsy and all three mean "no password supplied". Reaching the final line means every rule passed, so returning `null` needs no condition. Adding a fifth rule is a one-line insertion at the right position, which is the structural benefit of guards over nesting.',
      },
    ],
    quiz: {
      id: 'qz-m07-03',
      questions: [
        {
          id: 'q-m07-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['control-flow', 'clean-code'],
          prompt: 'What is the main benefit of guard clauses?',
          options: [
            'They run faster than nested conditions',
            'They handle each failure where it is detected and keep the main logic unindented',
            'They allow a function to have only one return statement',
            'They eliminate the need for conditions entirely',
          ],
          correct: 1,
          optionExplanations: [
            'Any performance difference is negligible.',
            'Correct — reading top to bottom accumulates guarantees.',
            'They deliberately use several returns.',
            'The conditions are still there, just restructured.',
          ],
          explanation:
            'Guards deal with each failure immediately and exit, so the reader never has to match a distant `else` to its `if`, and the success path sits unindented at the bottom. By the final line you know every guard passed, which is a much lighter mental load than tracking nested possibilities.',
        },
        {
          id: 'q-m07-03-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['control-flow', 'clean-code'],
          prompt: 'Why is `else` unnecessary after a `return`?',
          options: [
            'Because `else` is deprecated',
            'Because execution could not reach the code after a return anyway, so the `else` adds only indentation',
            'Because `return` implies `else`',
            'Because it would cause a SyntaxError',
          ],
          correct: 1,
          optionExplanations: [
            '`else` is entirely current and useful elsewhere.',
            'Correct — dropping it removes a nesting level for free.',
            'Nothing is implied; the code simply becomes unreachable.',
            'It is perfectly valid, just redundant.',
          ],
          explanation:
            'If the `if` branch returns, the code below it can only run when the condition was false — which is exactly what `else` would express. Removing the `else` and unindenting its contents is behaviour-preserving and is what makes guard clauses read cleanly.',
        },
        {
          id: 'q-m07-03-3',
          kind: QUIZ_KIND.MULTIPLE,
          topicIds: ['control-flow', 'clean-code'],
          prompt: 'Which of these are redundant patterns worth simplifying? (Select all that apply.)',
          options: [
            '`if (x > 5) { return true; } else { return false; }`',
            '`if (isReady === true) { ... }`',
            '`let s; if (ok) { s = "y"; } else { s = "n"; }`',
            '`if (a) { doOne(); } else { doTwo(); }`',
          ],
          correct: [0, 1, 2],
          explanation:
            'The first restates a boolean the comparison already produced — return `x > 5` directly. The second compares a boolean to `true`, which adds nothing — write `if (isReady)`. The third assigns in both branches, which a ternary expresses in one line and allows `const`. The fourth is a genuine two-way branch where each side does different work, and `if`/`else` is exactly right for it.',
        },
      ],
    },
    summary:
      'Nested conditionals push the success path to maximum indentation and separate each `else` from its `if`. Guard clauses invert that: handle each failure where it is detected and return immediately, so reading top to bottom accumulates guarantees and the important logic sits unindented at the bottom. The old "single exit point" rule comes from languages needing manual cleanup and does not apply to JavaScript — early returns are actively preferred. Several patterns are always worth collapsing: returning `true`/`false` from a condition that already produces one, comparing a boolean to `true`, assigning in both branches of an `if` where a ternary and `const` would do, and keeping an `else` after a `return`. Choose the form to match the job: guards for validation, ternary for one of two values, `if`/`else if` for branches doing real work, and a lookup for value mapping.',
    keyTakeaways: [
      'Guard clauses flatten nesting and put the success path last, unindented',
      'Reading guards top to bottom builds up guarantees for the reader',
      '"Single exit point" does not apply to JavaScript — early returns are preferred',
      '`else` after `return` is always removable',
      'Return a condition directly instead of `if (c) return true; else return false;`',
      'Match the construct to the job: guard, ternary, if/else, or lookup',
    ],
    relatedLessons: ['l-m07-01', 'l-m04-06'],
    interviewConnections: [
      'What is a guard clause and why use one?',
      'Is it bad practice to have multiple return statements?',
      'How would you refactor deeply nested if statements?',
    ],
  },
];
