import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm36';

export default [
  /* ================================================================== */
  {
    id: 'l-m36-01',
    slug: 'symbols',
    moduleId: M,
    order: 1,
    title: 'Symbols',
    description: 'Guaranteed-unique property keys, and the well-known symbols the language itself looks for.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 16,
    xp: 45,
    topicIds: ['metaprogramming'],
    prerequisites: ['l-m35-03'],
    learningObjectives: [
      'Explain why every Symbol is unique',
      'Use symbols as non-colliding property keys',
      'Distinguish Symbol() from Symbol.for()',
      'Use well-known symbols to hook into language behaviour',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Every symbol is unique',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The description is a label, not an identity.',
        code: [
          '"use strict";',
          '',
          'const a = Symbol("id");',
          'const b = Symbol("id");',
          '',
          'console.log("equal    :", a === b);',
          'console.log("typeof   :", typeof a);',
          'console.log("description:", a.description);',
          '',
          '// Two symbols with the SAME description are still different',
          'console.log("same desc:", a.description === b.description);',
          '',
          '// Symbols are primitives, and are not constructed',
          'try {',
          '  new Symbol("x");',
          '} catch (error) {',
          '  console.log("new      :", error.name);',
          '}',
          '',
          '// They never coerce to a string implicitly',
          'try {',
          '  console.log("concat: " + a);',
          '} catch (error) {',
          '  console.log("implicit :", error.name);',
          '}',
          '',
          'console.log("explicit :", String(a));',
        ].join('\n'),
        output: [
          'equal    : false',
          'typeof   : symbol',
          'description: id',
          'same desc: true',
          'new      : TypeError',
          'implicit : TypeError',
          'explicit : Symbol(id)',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'The description exists only for debugging',
        body: [
          '`Symbol("id")` creates a brand-new value **every time**, and the string you pass is a label that appears in devtools and in `String(sym)`. It plays no part in comparison — two symbols with identical descriptions are still different values.',
          'Symbols are **primitives**, so `new Symbol()` throws. And they deliberately refuse implicit string coercion: `"x" + sym` is a `TypeError` rather than silently producing something meaningless. Use `String(sym)` or `sym.description` when you want text.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Symbols as property keys',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A key that cannot collide with anyone else\'s.',
        code: [
          '"use strict";',
          '',
          'const internalId = Symbol("internalId");',
          '',
          'const user = {',
          '  name: "Ada",',
          '  [internalId]: 12345,',
          '};',
          '',
          'console.log("read      :", user[internalId]);',
          '',
          '// Symbol keys are skipped by the usual enumerations',
          'console.log("keys      :", Object.keys(user));',
          'console.log("entries   :", Object.entries(user));',
          'console.log("JSON      :", JSON.stringify(user));',
          '',
          'const viaForIn = [];',
          'for (const key in user) viaForIn.push(key);',
          'console.log("for...in  :", viaForIn);',
          '',
          '// But they are not secret — there is a dedicated way to find them',
          'console.log("symbols   :", Object.getOwnPropertySymbols(user).length);',
          'console.log("all keys  :", Reflect.ownKeys(user).map(String));',
          '',
          '// A string key with the same text does not collide',
          'user.internalId = "different thing";',
          'console.log("both      :", user[internalId], "|", user.internalId);',
        ].join('\n'),
        output: [
          'read      : 12345',
          'keys      : ["name"]',
          'entries   : [["name", "Ada"]]',
          'JSON      : {"name":"Ada"}',
          'for...in  : ["name"]',
          'symbols   : 1',
          'all keys  : ["name", "Symbol(internalId)"]',
          'both      : 12345 | different thing',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Symbol keys are non-enumerable-ish, not private',
        body: [
          'They are skipped by `Object.keys`, `for...in`, `Object.entries` and `JSON.stringify` — which makes them excellent for **metadata that should not appear in serialised output**.',
          'But `Object.getOwnPropertySymbols` and `Reflect.ownKeys` find them, so this is **not privacy**. Anyone determined can enumerate them. For genuine privacy use a `#private` field (Module 31) or a `WeakMap` (Module 34).',
          'What symbols actually guarantee is **no collision**: two libraries can both attach a symbol-keyed property to the same object and neither can overwrite the other, because their symbols are different values. That is the real use.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The collision problem symbols solve.',
        code: [
          '"use strict";',
          '',
          '// Two independent libraries tagging the same object',
          'function libraryA(object) { object.cache = "A data"; }',
          'function libraryB(object) { object.cache = "B data"; }',
          '',
          'const target = {};',
          'libraryA(target);',
          'libraryB(target);',
          '',
          'console.log("string keys:", target.cache, "<- A was silently lost");',
          '',
          '// The same, with symbols',
          'const keyA = Symbol("cache");',
          'const keyB = Symbol("cache");',
          '',
          'function symbolA(object) { object[keyA] = "A data"; }',
          'function symbolB(object) { object[keyB] = "B data"; }',
          '',
          'const safe = {};',
          'symbolA(safe);',
          'symbolB(safe);',
          '',
          'console.log("symbol keys:", safe[keyA], "|", safe[keyB]);',
        ].join('\n'),
        output: [
          'string keys: B data <- A was silently lost',
          'symbol keys: A data | B data',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'The global symbol registry',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: '`Symbol.for` looks up a shared symbol by key.',
        code: [
          '"use strict";',
          '',
          '// Symbol() is always new; Symbol.for() reuses a registry entry',
          'console.log("Symbol()    :", Symbol("app") === Symbol("app"));',
          'console.log("Symbol.for():", Symbol.for("app") === Symbol.for("app"));',
          '',
          '// The two mechanisms are separate',
          'console.log("mixed       :", Symbol("app") === Symbol.for("app"));',
          '',
          '// keyFor works only for registered symbols',
          'console.log("keyFor reg  :", Symbol.keyFor(Symbol.for("app")));',
          'console.log("keyFor local:", Symbol.keyFor(Symbol("app")));',
        ].join('\n'),
        output: [
          'Symbol()    : false',
          'Symbol.for(): true',
          'mixed       : false',
          'keyFor reg  : app',
          'keyFor local: undefined',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: '`Symbol.for` reintroduces the collision problem',
        body: [
          'The registry is **global across the whole realm**, so `Symbol.for("id")` in your code is the same symbol as `Symbol.for("id")` in any dependency. That is the point when you *want* sharing — and exactly the name-collision risk symbols otherwise avoid.',
          'So use `Symbol.for` sparingly, with namespaced keys such as `Symbol.for("myapp.thing")`, and only when separate pieces of code genuinely need to agree on the same symbol without importing it. `Symbol()` is the right default.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Well-known symbols',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Some symbols are built into the language, and the engine **looks for them** on your objects to decide how built-in operations behave. `Symbol.iterator` from Module 35 is one you have already used.',
          'These are the actual hooks that make metaprogramming possible without a `Proxy`: implement the method, and standard syntax changes behaviour for your type.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Symbol.toPrimitive — controlling coercion.',
        code: [
          '"use strict";',
          '',
          'class Money {',
          '  constructor(amount, currency) {',
          '    this.amount = amount;',
          '    this.currency = currency;',
          '  }',
          '',
          '  // The engine calls this when a primitive is needed',
          '  [Symbol.toPrimitive](hint) {',
          '    if (hint === "number") return this.amount;',
          '    if (hint === "string") return `${this.amount} ${this.currency}`;',
          '    return `${this.amount} ${this.currency}`;   // "default"',
          '  }',
          '}',
          '',
          'const price = new Money(25, "USD");',
          '',
          'console.log("number hint:", +price);',
          'console.log("string hint:", `${price}`);',
          'console.log("default    :", price + "");',
          'console.log("arithmetic :", price * 2);',
          '',
          '// Without it, an object would give "[object Object]" or NaN',
          'const plain = { amount: 25 };',
          'console.log("plain      :", `${plain}`, "|", +plain);',
        ].join('\n'),
        output: [
          'number hint: 25',
          'string hint: 25 USD',
          'default    : 25 USD',
          'arithmetic : 50',
          'plain      : [object Object] | NaN',
        ].join('\n'),
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Two more that appear in real code.',
        code: [
          '"use strict";',
          '',
          '// Symbol.toStringTag — what Object.prototype.toString reports',
          'class Collection {',
          '  get [Symbol.toStringTag]() { return "Collection"; }',
          '}',
          '',
          'console.log("tagged  :", Object.prototype.toString.call(new Collection()));',
          'console.log("untagged:", Object.prototype.toString.call({}));',
          '',
          '// Symbol.hasInstance — customising instanceof',
          'class Iterable {',
          '  static [Symbol.hasInstance](value) {',
          '    return value != null && typeof value[Symbol.iterator] === "function";',
          '  }',
          '}',
          '',
          'console.log("array   :", [] instanceof Iterable);',
          'console.log("string  :", "abc" instanceof Iterable);',
          'console.log("object  :", {} instanceof Iterable);',
          'console.log("number  :", 5 instanceof Iterable);',
        ].join('\n'),
        output: [
          'tagged  : [object Collection]',
          'untagged: [object Object]',
          'array   : true',
          'string  : true',
          'object  : false',
          'number  : false',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'This is how `Object.prototype.toString.call` knows types',
        body: [
          'Module 29 used `Object.prototype.toString.call(value)` as the reliable type check — `"[object Array]"`, `"[object Null]"`. Now you can see the mechanism: built-ins carry a `Symbol.toStringTag`, and the method reads it.',
          'Which also means the check is **spoofable** by any object defining that symbol. It remains the best general-purpose type check, but "reliable" means "reliable across realms", not "unforgeable".',
          'Be sparing with `Symbol.hasInstance`: redefining `instanceof` is legitimate for a genuine capability check like the one above, and confusing if it contradicts what readers expect.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const key = Symbol("data");',
          '',
          'const obj = { name: "x", [key]: 1 };',
          '',
          'console.log(Object.keys(obj).length, JSON.stringify(obj), Reflect.ownKeys(obj).length);',
        ].join('\n'),
        options: [
          '1 {"name":"x"} 2',
          '2 {"name":"x","data":1} 2',
          '1 {"name":"x"} 1',
          '2 {"name":"x"} 2',
        ],
        correct: 0,
        explanation:
          'Symbol keys are skipped by the string-key enumerations: `Object.keys` reports only `["name"]`, and `JSON.stringify` omits the symbol-keyed property entirely — which makes symbols ideal for metadata that must not reach serialised output. But they are **not hidden**: `Reflect.ownKeys` returns both keys, giving `2`, and `Object.getOwnPropertySymbols` would find the symbol too. That is the distinction to hold onto — symbols guarantee **no collision**, not privacy. For real privacy use a `#private` field or a `WeakMap`.',
      },
    ],
    exercises: [
      {
        id: 'ex-m36-01-a',
        title: 'Why are symbols unique?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['metaprogramming'],
        instructions:
          'Is `Symbol("id") === Symbol("id")` true, and what does the description do?',
        options: [
          'True — the description determines identity',
          'False — every Symbol() call creates a new value; the description is only a debugging label',
          'True, but only in the same file',
          'It throws',
        ],
        correct: 1,
        hints: [
          'What is the description used for?',
        ],
        solution: 'False — every Symbol() call creates a new value; the description is only a debugging label',
        solutionExplanation:
          'Each call produces a brand-new unique value, and the string you pass appears in devtools and `String(sym)` while playing no part in comparison. That uniqueness is the entire feature: two libraries can attach symbol-keyed properties to the same object without either overwriting the other. `Symbol.for("id")` is the deliberate exception — it looks up a shared symbol in a realm-wide registry, so those *are* equal.',
      },
      {
        id: 'ex-m36-01-b',
        title: 'Hide metadata from serialisation',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['metaprogramming'],
        instructions:
          'Write `createTagger()` returning `{ tag, read, KEY }`. `tag(obj, value)` attaches metadata under a symbol key so it does not appear in `Object.keys` or `JSON.stringify`; `read(obj)` returns it.',
        starterCode: [
          'function createTagger() {',
          '  // A symbol key, created once per tagger.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'stores and reads', body: 'const t = createTagger(); const o = {}; t.tag(o, "meta"); expect(t.read(o)).toBe("meta");' },
          { name: 'is absent from Object.keys', body: 'const t = createTagger(); const o = { a: 1 }; t.tag(o, "m"); expect(Object.keys(o)).toEqual(["a"]);' },
          { name: 'is absent from JSON', body: 'const t = createTagger(); const o = { a: 1 }; t.tag(o, "m"); expect(JSON.stringify(o)).toBe(\'{"a":1}\');' },
          { name: 'exposes the key as a symbol', body: 'expect(typeof createTagger().KEY).toBe("symbol");' },
          { name: 'returns undefined when untagged', body: 'expect(createTagger().read({})).toBe(undefined);' },
          { name: 'taggers do not collide', body: 'const a = createTagger(); const b = createTagger(); const o = {}; a.tag(o, 1); b.tag(o, 2); expect([a.read(o), b.read(o)]).toEqual([1, 2]);' },
          { name: 'is findable via getOwnPropertySymbols', body: 'const t = createTagger(); const o = {}; t.tag(o, 1); expect(Object.getOwnPropertySymbols(o).includes(t.KEY)).toBe(true);', hidden: true },
        ],
        hints: [
          '`const KEY = Symbol("meta");` inside the factory.',
          '`tag` assigns `object[KEY] = value`.',
          'Return `KEY` alongside the two functions.',
        ],
        solution: [
          'function createTagger() {',
          '  const KEY = Symbol("meta");',
          '',
          '  return {',
          '    KEY,',
          '    tag(object, value) { object[KEY] = value; },',
          '    read(object) { return object[KEY]; },',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'A symbol key is skipped by `Object.keys` and `JSON.stringify`, which is exactly what makes it suitable for metadata that must not reach serialised output. Creating the symbol **inside** the factory gives each tagger its own unique key, so two taggers can annotate the same object without either overwriting the other — the sixth test, and the real reason symbols exist. The hidden test makes the honest limitation explicit: `getOwnPropertySymbols` finds the key, so this is non-enumerability, **not** privacy.',
      },
      {
        id: 'ex-m36-01-c',
        title: 'Control coercion',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['metaprogramming'],
        instructions:
          'Write a class `Duration` storing `minutes`, whose `Symbol.toPrimitive` returns the minutes for the `"number"` hint and `"<n>m"` for `"string"` and `"default"`.',
        starterCode: [
          'class Duration {',
          '  // Implement [Symbol.toPrimitive](hint).',
          '}',
        ].join('\n'),
        tests: [
          { name: 'stores the minutes', body: 'expect(new Duration(30).minutes).toBe(30);' },
          { name: 'coerces to a number', body: 'expect(+new Duration(30)).toBe(30);' },
          { name: 'coerces in a template', body: 'expect(`${new Duration(30)}`).toBe("30m");' },
          { name: 'supports arithmetic', body: 'expect(new Duration(30) * 2).toBe(60);' },
          { name: 'uses the default hint for +', body: 'expect(new Duration(5) + "").toBe("5m");' },
          { name: 'compares numerically', body: 'expect(new Duration(10) < new Duration(20)).toBe(true);' },
          { name: 'works with String()', body: 'expect(String(new Duration(7))).toBe("7m");', hidden: true },
        ],
        hints: [
          '`[Symbol.toPrimitive](hint) { ... }` is a normal method.',
          'Check `hint === "number"` first.',
          'Return the string form for both other hints.',
        ],
        solution: [
          'class Duration {',
          '  constructor(minutes) {',
          '    this.minutes = minutes;',
          '  }',
          '',
          '  [Symbol.toPrimitive](hint) {',
          '    if (hint === "number") return this.minutes;',
          '',
          '    return `${this.minutes}m`;',
          '  }',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The engine passes a **hint** describing what it needs, and handling each one is what makes the tests diverge correctly: `+d` and `d * 2` send `"number"`, a template literal and `String()` send `"string"`, and `d + ""` sends `"default"`. The comparison test is the subtle one — relational operators like `<` request the `"number"` hint, so durations compare by magnitude rather than as strings, where `"10m" < "20m"` would happen to work but `"9m" < "10m"` would not.',
      },
      {
        id: 'ex-m36-01-d',
        title: 'Symbol or Symbol.for?',
        kind: EXERCISE_KIND.CHOOSE_IMPLEMENTATION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['metaprogramming'],
        instructions:
          'Your library attaches an internal marker to user objects. Which should you use?',
        options: [
          'Symbol.for("marker") — so it is easy to find',
          'Symbol("marker") — a unique value nobody else can collide with',
          'A string key "marker"',
          'Either symbol form works identically',
        ],
        correct: 1,
        hints: [
          'Which one is shared across the whole realm?',
        ],
        solution: 'Symbol("marker") — a unique value nobody else can collide with',
        solutionExplanation:
          '`Symbol()` creates a value only your module holds, so no dependency can read or overwrite it by guessing a name — which is the whole point of using a symbol for an internal marker. `Symbol.for` places the symbol in a **realm-wide registry**, so any other code calling `Symbol.for("marker")` gets the identical symbol, reintroducing exactly the collision risk you were avoiding. Reserve `Symbol.for` for cases where separate code genuinely must agree without importing, and namespace the key. A plain string key collides most easily of all.',
      },
    ],
    quiz: {
      id: 'qz-m36-01',
      questions: [
        {
          id: 'q-m36-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['metaprogramming'],
          prompt: 'What is the purpose of a Symbol\'s description?',
          options: [
            'It determines equality',
            'Debugging only — it appears in devtools and String(sym)',
            'It registers the symbol globally',
            'It sets the property name',
          ],
          correct: 1,
          optionExplanations: [
            'Every Symbol() is unique regardless.',
            'Correct — a label, not an identity.',
            'That is Symbol.for.',
            'The symbol itself is the key.',
          ],
          explanation:
            'The description is a debugging label with no effect on identity — two symbols with the same description are still different values.',
        },
        {
          id: 'q-m36-01-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['metaprogramming'],
          prompt: 'Do symbol-keyed properties appear in JSON.stringify?',
          options: [
            'Yes',
            'No — and they are skipped by Object.keys and for...in too',
            'Only if enumerable',
            'Only with a replacer',
          ],
          correct: 1,
          optionExplanations: [
            'They are omitted.',
            'Correct — ideal for non-serialised metadata.',
            'Enumerability does not change this.',
            'A replacer never sees them.',
          ],
          explanation:
            'Symbol keys are skipped by every string-key enumeration, which makes them good for metadata. `Object.getOwnPropertySymbols` and `Reflect.ownKeys` still find them, so this is not privacy.',
        },
        {
          id: 'q-m36-01-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['metaprogramming'],
          prompt: 'Symbol.for("x") === Symbol.for("x") is true.',
          options: ['True', 'False'],
          correct: 0,
          optionExplanations: [
            'Correct — the registry returns the same symbol.',
            'Plain Symbol("x") would be false.',
          ],
          explanation:
            '`Symbol.for` looks up a realm-wide registry, so the same key returns the same symbol. That sharing is also a collision risk, so namespace the keys and prefer plain `Symbol()`.',
        },
        {
          id: 'q-m36-01-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['metaprogramming'],
          prompt: 'What is a well-known symbol?',
          options: [
            'A symbol with a popular description',
            'A built-in symbol the language looks for on your objects to decide how an operation behaves',
            'A symbol in the global registry',
            'Any exported symbol',
          ],
          correct: 1,
          optionExplanations: [
            'Descriptions are irrelevant.',
            'Correct — Symbol.iterator, toPrimitive, toStringTag.',
            'That is Symbol.for.',
            'Exporting is unrelated.',
          ],
          explanation:
            'Implementing `Symbol.iterator`, `Symbol.toPrimitive` or `Symbol.toStringTag` changes how standard syntax treats your object — hooks into the language without a Proxy.',
        },
      ],
    },
    summary:
      'Every `Symbol()` call creates a **brand-new unique value**; the description is a **debugging label** with no role in comparison. Symbols are **primitives** (`new Symbol()` throws) and refuse **implicit** string coercion, so `"x" + sym` is a `TypeError` — use `String(sym)` or `.description`. As property keys they are skipped by `Object.keys`, `for...in`, `Object.entries` and **`JSON.stringify`**, which makes them ideal for metadata that must not reach serialised output — but `Object.getOwnPropertySymbols` and `Reflect.ownKeys` find them, so this is **not privacy**. What symbols actually guarantee is **no collision**: two libraries can tag the same object and neither can overwrite the other, where two string keys named `cache` silently destroy one another. **`Symbol.for(key)`** is the deliberate exception, looking up a **realm-wide registry** so the same key yields the same symbol — useful when separate code must agree without importing, and a reintroduction of exactly the collision risk symbols avoid, so namespace those keys and default to plain `Symbol()`. Finally, **well-known symbols** are hooks the engine itself looks for: `Symbol.iterator` (Module 35), **`Symbol.toPrimitive`** (which receives a `"number"`, `"string"` or `"default"` hint and controls coercion, including relational comparison), **`Symbol.toStringTag`** (which is how `Object.prototype.toString.call` reports a type — and therefore why that check is spoofable), and `Symbol.hasInstance` for customising `instanceof`.',
    keyTakeaways: [
      'Every Symbol() is unique; the description is only a debugging label',
      'Symbols never coerce implicitly to strings — use String(sym)',
      'Symbol keys are skipped by keys/for...in/JSON but are not private',
      'The real guarantee is no collision between independent code',
      'Symbol.for uses a realm-wide registry — powerful and collision-prone',
      'Well-known symbols hook into iteration, coercion, toString and instanceof',
    ],
    relatedLessons: ['l-m36-02', 'l-m35-01'],
    interviewConnections: [
      'What is a Symbol and why is each one unique?',
      'Are symbol-keyed properties private?',
      'What is the difference between Symbol() and Symbol.for()?',
      'What is Symbol.toPrimitive for?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m36-02',
    slug: 'property-descriptors',
    moduleId: M,
    order: 2,
    title: 'Property Descriptors',
    description: 'What a property really is — value, writable, enumerable, configurable — and how defaults differ.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 17,
    xp: 45,
    topicIds: ['metaprogramming'],
    prerequisites: ['l-m36-01'],
    learningObjectives: [
      'Read a property descriptor and explain each flag',
      'State how defineProperty defaults differ from assignment',
      'Define accessor properties programmatically',
      'Explain freeze, seal and their limits',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'A property is more than a value',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Every property carries flags.',
        code: [
          '"use strict";',
          '',
          'const user = { name: "Ada" };',
          '',
          'console.log(Object.getOwnPropertyDescriptor(user, "name"));',
          '',
          '// Built-ins are configured differently',
          'console.log("array length:", Object.getOwnPropertyDescriptor([1, 2], "length"));',
          '',
          'class A { method() {} }',
          'const methodDescriptor = Object.getOwnPropertyDescriptor(A.prototype, "method");',
          '',
          'console.log("class method:", {',
          '  writable: methodDescriptor.writable,',
          '  enumerable: methodDescriptor.enumerable,',
          '  configurable: methodDescriptor.configurable,',
          '});',
        ].join('\n'),
        output: [
          '{value: "Ada", writable: true, enumerable: true, configurable: true}',
          'array length: {value: 2, writable: true, enumerable: false, configurable: false}',
          'class method: {writable: true, enumerable: false, configurable: true}',
        ].join('\n'),
      },
      {
        kind: SECTION.TERMS,
        terms: [
          { term: 'value', definition: 'What the property holds. Present only on **data** properties.' },
          { term: 'writable', definition: 'Whether assignment can change the value. `false` makes it read-only.' },
          { term: 'enumerable', definition: 'Whether it appears in `Object.keys`, `for...in`, `Object.entries`, spread and `JSON.stringify`.' },
          { term: 'configurable', definition: 'Whether the property can be deleted, or its flags changed. **Setting this to `false` is irreversible.**' },
          { term: 'get / set', definition: 'Accessor functions. Present only on **accessor** properties, which have no `value` or `writable`.' },
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'This explains behaviour you have already relied on',
        body: [
          'An array\'s `length` is **non-enumerable**, which is why `Object.keys([1,2])` gives `["0","1"]` and not `["0","1","length"]`.',
          'Class methods are **non-enumerable** (Module 31), which is why `for...in` over an instance shows only its own fields. `Object.prototype`\'s methods are non-enumerable for the same reason, which is why `for...in` does not list `toString`.',
          'And `configurable: false` on `length` is why you cannot delete it.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The defaults differ — and this catches people',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Assignment versus defineProperty.',
        code: [
          '"use strict";',
          '',
          '// Created by assignment or a literal: everything TRUE',
          'const byAssignment = {};',
          'byAssignment.a = 1;',
          'console.log("assignment  :", Object.getOwnPropertyDescriptor(byAssignment, "a"));',
          '',
          '// Created by defineProperty with flags omitted: everything FALSE',
          'const byDefine = {};',
          'Object.defineProperty(byDefine, "b", { value: 2 });',
          'console.log("defineProperty:", Object.getOwnPropertyDescriptor(byDefine, "b"));',
          '',
          '// Which produces surprising behaviour',
          'console.log("keys        :", Object.keys(byDefine));',
          'console.log("JSON        :", JSON.stringify(byDefine));',
          'console.log("spread      :", { ...byDefine });',
          '',
          '// Assignment silently fails... unless strict mode, where it throws',
          'try {',
          '  byDefine.b = 99;',
          '} catch (error) {',
          '  console.log("write       :", error.name);',
          '}',
          '',
          'console.log("value       :", byDefine.b);',
        ].join('\n'),
        output: [
          'assignment  : {value: 1, writable: true, enumerable: true, configurable: true}',
          'defineProperty: {value: 2, writable: false, enumerable: false, configurable: false}',
          'keys        : []',
          'JSON        : {}',
          'spread      : {}',
          'write       : TypeError',
          'value       : 2',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Omitted flags default to `false`, not to "unchanged"',
        body: [
          'This is the single most common `defineProperty` mistake. Writing `Object.defineProperty(obj, "x", { value: 1 })` creates a property that is **read-only, invisible to enumeration, and permanently locked** — almost certainly not what was intended.',
          'Always state the flags explicitly when defining a property you want to behave normally: `{ value: 1, writable: true, enumerable: true, configurable: true }`.',
          'Note the asymmetry is deliberate: `defineProperty` is a low-level tool whose safe default is "no capabilities", while assignment is the everyday path and grants all three.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Making a property behave like a built-in.',
        code: [
          '"use strict";',
          '',
          'const config = { name: "app" };',
          '',
          '// Non-enumerable, like a real built-in method',
          'Object.defineProperty(config, "version", {',
          '  value: "1.0",',
          '  writable: false,',
          '  enumerable: false,',
          '  configurable: true,',
          '});',
          '',
          'console.log("readable :", config.version);',
          'console.log("keys     :", Object.keys(config));',
          'console.log("JSON     :", JSON.stringify(config));',
          'console.log("in       :", "version" in config);',
          'console.log("hasOwn   :", Object.hasOwn(config, "version"));',
          '',
          '// configurable: true means it can still be redefined or deleted',
          'delete config.version;',
          'console.log("deleted  :", config.version);',
        ].join('\n'),
        output: [
          'readable : 1.0',
          'keys     : ["name"]',
          'JSON     : {"name":"app"}',
          'in       : true',
          'hasOwn   : true',
          'deleted  : undefined',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: '`configurable: false` is a one-way door',
        body: [
          'Once a property is non-configurable you cannot delete it, and you cannot change its flags back — including turning `writable` back on. The only exception is that `writable: true` may be flipped to `false`, never the reverse.',
          'So set `configurable: false` deliberately and last. It is the reason Module 30\'s `inherit` helper restored `constructor` with `configurable: true` — matching how the language defines it, so later code can still redefine it.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Accessor properties',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Defining a getter and setter programmatically.',
        code: [
          '"use strict";',
          '',
          'function defineComputed(target, name, compute) {',
          '  Object.defineProperty(target, name, {',
          '    get() { return compute(this); },',
          '    enumerable: true,',
          '    configurable: true,',
          '  });',
          '}',
          '',
          'const rect = { width: 4, height: 3 };',
          '',
          'defineComputed(rect, "area", (r) => r.width * r.height);',
          '',
          'console.log("area   :", rect.area);',
          '',
          'rect.width = 10;',
          'console.log("updated:", rect.area);',
          '',
          '// An accessor descriptor has get/set, never value/writable',
          'const descriptor = Object.getOwnPropertyDescriptor(rect, "area");',
          'console.log("shape  :", Object.keys(descriptor));',
          '',
          '// A getter with no setter: assignment throws in strict mode',
          'try {',
          '  rect.area = 100;',
          '} catch (error) {',
          '  console.log("write  :", error.name);',
          '}',
        ].join('\n'),
        output: [
          'area   : 12',
          'updated: 30',
          'shape  : ["get", "set", "enumerable", "configurable"]',
          'write  : TypeError',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'A descriptor is data **or** accessor, never both',
        body: [
          'Supplying `value` alongside `get` throws a `TypeError`. A data property has `value` and `writable`; an accessor property has `get` and `set`. Both kinds carry `enumerable` and `configurable`.',
          'Note the accessor descriptor above lists `set` even though none was provided — it is present and `undefined`, which is what makes the assignment throw rather than silently doing nothing.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'freeze, seal and preventExtensions',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Three levels of lockdown.',
        code: [
          '"use strict";',
          '',
          'const frozen = Object.freeze({ a: 1, nested: { b: 2 } });',
          'const sealed = Object.seal({ a: 1 });',
          'const closed = Object.preventExtensions({ a: 1 });',
          '',
          '// preventExtensions: no new properties, existing ones still writable',
          'closed.a = 99;',
          'console.log("preventExt write :", closed.a);',
          '',
          '// seal: values still writable, but deletion is refused',
          'sealed.a = 99;',
          'console.log("seal write       :", sealed.a);',
          '',
          'try {',
          '  delete sealed.a;',
          '} catch (error) {',
          '  console.log("seal delete      :", error.name);',
          '}',
          'console.log("still there      :", sealed.a);',
          '',
          '// freeze: cannot write either',
          'try {',
          '  frozen.a = 99;',
          '} catch (error) {',
          '  console.log("freeze write     :", error.name);',
          '}',
          '',
          '// But freeze is SHALLOW — the nested object is untouched',
          'frozen.nested.b = 99;',
          'console.log("nested mutated   :", frozen.nested.b);',
          '',
          'console.log("isFrozen         :", Object.isFrozen(frozen), Object.isFrozen(frozen.nested));',
        ].join('\n'),
        output: [
          'preventExt write : 99',
          'seal write       : 99',
          'seal delete      : TypeError',
          'still there      : 99',
          'freeze write     : TypeError',
          'nested mutated   : 99',
          'isFrozen         : true false',
        ].join('\n'),
      },
      {
        kind: SECTION.TABLE,
        headers: ['', 'Add', 'Delete', 'Modify value', 'Reconfigure'],
        rows: [
          ['`preventExtensions`', '**No**', 'Yes', 'Yes', 'Yes'],
          ['`seal`', '**No**', '**No**', 'Yes', '**No**'],
          ['`freeze`', '**No**', '**No**', '**No**', '**No**'],
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: '`Object.freeze` is shallow — the same trap as spread',
        body: [
          'Freezing sets `writable: false` and `configurable: false` on the object\'s **own** properties. Anything those properties point at is completely unaffected, so `frozen.nested.b = 99` succeeds — exactly the shallow-copy problem from Module 34, in a different guise.',
          'A "deep freeze" means recursing and freezing every nested object yourself. There is no built-in for it.',
          'Also note the failure mode differs by mode. In **strict** mode a write to a frozen property **throws**, and so does `delete` on a non-configurable one — which is why the sealed object above reported a `TypeError` rather than quietly keeping its property. In sloppy mode both fail **silently**, returning `false` from `delete` and simply discarding the write. One more reason modules being always-strict is an improvement: the mistake is reported where it happens.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '"use strict";',
          '',
          'const obj = {};',
          'Object.defineProperty(obj, "x", { value: 1 });',
          '',
          'console.log(obj.x, Object.keys(obj), JSON.stringify(obj));',
        ].join('\n'),
        options: [
          '1 [] {}',
          '1 ["x"] {"x":1}',
          'undefined [] {}',
          'It throws',
        ],
        correct: 0,
        explanation:
          'The property genuinely exists and reads as `1` — but every flag omitted from a `defineProperty` descriptor defaults to **`false`**, not to "normal". So `enumerable: false` means `Object.keys` reports `[]`, `JSON.stringify` gives `{}`, and spread would copy nothing; `writable: false` means assignment throws in strict mode; and `configurable: false` means it can never be deleted or reconfigured. This is the opposite of assignment, where `obj.x = 1` sets all three to `true`. When you want normal behaviour, state the flags explicitly.',
      },
    ],
    exercises: [
      {
        id: 'ex-m36-02-a',
        title: 'What do the flags default to?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['metaprogramming'],
        instructions:
          'How do the descriptor defaults differ between `obj.x = 1` and `Object.defineProperty(obj, "x", { value: 1 })`?',
        options: [
          'They are identical',
          'Assignment sets writable, enumerable and configurable to true; defineProperty defaults each omitted flag to false',
          'defineProperty sets everything to true',
          'Assignment makes the property non-enumerable',
        ],
        correct: 1,
        hints: [
          'Does a defineProperty property show up in Object.keys?',
        ],
        solution: 'Assignment sets writable, enumerable and configurable to true; defineProperty defaults each omitted flag to false',
        solutionExplanation:
          'The asymmetry is deliberate: assignment is the everyday path and grants all three capabilities, while `defineProperty` is a low-level tool whose safe default is "no capabilities". The consequence surprises people — a property defined with only `value` is read-only, invisible to `Object.keys`, spread and `JSON.stringify`, and permanently locked. State the flags explicitly whenever you want normal behaviour.',
      },
      {
        id: 'ex-m36-02-b',
        title: 'Define a hidden property',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['metaprogramming'],
        instructions:
          'Write `defineHidden(target, name, value)` adding a property that is readable and writable but does **not** appear in `Object.keys` or `JSON.stringify`, and can still be reconfigured later.',
        starterCode: [
          'function defineHidden(target, name, value) {',
          '  // Omitted flags default to false — be explicit.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'the property is readable', body: 'const o = {}; defineHidden(o, "x", 1); expect(o.x).toBe(1);' },
          { name: 'it is not enumerable', body: 'const o = { a: 1 }; defineHidden(o, "x", 1); expect(Object.keys(o)).toEqual(["a"]);' },
          { name: 'it is not serialised', body: 'const o = { a: 1 }; defineHidden(o, "x", 1); expect(JSON.stringify(o)).toBe(\'{"a":1}\');' },
          { name: 'it is writable', body: 'const o = {}; defineHidden(o, "x", 1); o.x = 2; expect(o.x).toBe(2);' },
          { name: 'it is configurable', body: 'const o = {}; defineHidden(o, "x", 1); expect(Object.getOwnPropertyDescriptor(o, "x").configurable).toBe(true);' },
          { name: 'it is found by hasOwn', body: 'const o = {}; defineHidden(o, "x", 1); expect(Object.hasOwn(o, "x")).toBe(true);' },
          { name: 'it is skipped by spread', body: 'const o = { a: 1 }; defineHidden(o, "x", 1); expect({ ...o }).toEqual({ a: 1 });', hidden: true },
        ],
        hints: [
          'Pass all four descriptor fields.',
          '`enumerable: false`, but `writable` and `configurable` true.',
          'Return nothing — `defineProperty` mutates the target.',
        ],
        solution: [
          'function defineHidden(target, name, value) {',
          '  Object.defineProperty(target, name, {',
          '    value,',
          '    writable: true,',
          '    enumerable: false,',
          '    configurable: true,',
          '  });',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Stating `writable` and `configurable` explicitly is the point of the exercise — omitting them would default both to `false`, failing the fourth and fifth tests and producing a permanently locked property. `enumerable: false` is what keeps it out of `Object.keys`, `JSON.stringify` and spread (the hidden test) while leaving it fully readable and findable by `Object.hasOwn` and `in`. This is exactly how built-in methods are defined, and it is what a polyfill does when extending a prototype.',
      },
      {
        id: 'ex-m36-02-c',
        title: 'Deep freeze',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['metaprogramming'],
        instructions:
          'Write `deepFreeze(value)` freezing an object and every nested object, returning the value. It must not infinitely recurse on a circular structure.',
        starterCode: [
          'function deepFreeze(value) {',
          '  // Object.freeze is shallow. Recurse — but guard against cycles.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'freezes the top level', body: 'expect(Object.isFrozen(deepFreeze({ a: 1 }))).toBe(true);' },
          { name: 'freezes nested objects', body: 'expect(Object.isFrozen(deepFreeze({ n: { b: 2 } }).n)).toBe(true);' },
          { name: 'freezes deeply', body: 'expect(Object.isFrozen(deepFreeze({ a: { b: { c: 1 } } }).a.b)).toBe(true);' },
          { name: 'freezes arrays', body: 'expect(Object.isFrozen(deepFreeze({ list: [1] }).list)).toBe(true);' },
          { name: 'returns the value', body: 'const o = { a: 1 }; expect(deepFreeze(o)).toBe(o);' },
          { name: 'handles primitives', body: 'expect(deepFreeze(5)).toBe(5);' },
          { name: 'handles null', body: 'expect(deepFreeze(null)).toBe(null);' },
          { name: 'survives a cycle', body: 'const o = { a: 1 }; o.self = o; expect(() => deepFreeze(o)).not.toThrow();', hidden: true },
        ],
        hints: [
          'Freeze the object first, then recurse into its values.',
          'A frozen object is already visited — `Object.isFrozen` is your cycle guard.',
          'Guard against `null`, since `typeof null === "object"`.',
        ],
        solution: [
          'function deepFreeze(value) {',
          '  if (value === null || typeof value !== "object") return value;',
          '',
          '  // Freeze BEFORE recursing, so a cycle back to this object stops here',
          '  if (Object.isFrozen(value)) return value;',
          '',
          '  Object.freeze(value);',
          '',
          '  for (const key of Reflect.ownKeys(value)) {',
          '    deepFreeze(value[key]);',
          '  }',
          '',
          '  return value;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Freezing **before** recursing is what makes the cycle test pass: when the recursion follows `self` back to the same object, `Object.isFrozen` is already `true` and the call returns immediately — the frozen state doubles as the visited set, so no extra bookkeeping is needed. The `null` guard is required because `typeof null === "object"` (Module 02\'s historical bug) would otherwise cause a property read on `null`. `Reflect.ownKeys` covers symbol-keyed properties too, which `Object.keys` would miss.',
      },
      {
        id: 'ex-m36-02-d',
        title: 'What does freeze not do?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['metaprogramming'],
        instructions:
          'After `Object.freeze(obj)` where `obj.nested = { x: 1 }`, what happens to `obj.nested.x = 2`?',
        options: [
          'It throws — the whole structure is frozen',
          'It succeeds — freeze is shallow, so the nested object is untouched',
          'It is silently ignored',
          'The nested object is frozen automatically',
        ],
        correct: 1,
        hints: [
          'Which properties did freeze actually affect?',
        ],
        solution: 'It succeeds — freeze is shallow, so the nested object is untouched',
        solutionExplanation:
          '`Object.freeze` sets `writable: false` and `configurable: false` on the object\'s **own** properties only. `obj.nested` can no longer be *reassigned*, but the object it points at was never touched — so mutating through it works normally, and `Object.isFrozen(obj.nested)` is `false`. This is the same shallow trap as spread copying: the reference is protected, not the target. There is no built-in deep freeze; you must recurse yourself.',
      },
    ],
    quiz: {
      id: 'qz-m36-02',
      questions: [
        {
          id: 'q-m36-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['metaprogramming'],
          prompt: 'What does enumerable: false affect?',
          options: [
            'Whether the property can be read',
            'Whether it appears in Object.keys, for...in, spread and JSON.stringify',
            'Whether it can be deleted',
            'Whether it can be written',
          ],
          correct: 1,
          optionExplanations: [
            'Reading is unaffected.',
            'Correct — visibility to enumeration.',
            'That is configurable.',
            'That is writable.',
          ],
          explanation:
            'It controls visibility to enumeration only. The property is still readable, and still found by `in` and `Object.hasOwn` — which is how built-in methods behave.',
        },
        {
          id: 'q-m36-02-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['metaprogramming'],
          prompt: 'What do omitted flags default to in Object.defineProperty?',
          options: ['true', 'false', 'They keep the existing value', 'It throws'],
          correct: 1,
          optionExplanations: [
            'That is assignment.',
            'Correct — the most common defineProperty surprise.',
            'Only when redefining an existing property.',
            'No error is raised.',
          ],
          explanation:
            'Each omitted flag is `false`, so `{ value: 1 }` alone creates a read-only, non-enumerable, non-configurable property. State them explicitly for normal behaviour.',
        },
        {
          id: 'q-m36-02-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['metaprogramming'],
          prompt: 'Setting configurable: false can be undone later.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It is a one-way door.',
            'Correct — only writable true→false remains possible.',
          ],
          explanation:
            'Non-configurable is irreversible: the property cannot be deleted or reconfigured. The single exception is flipping `writable` from `true` to `false`.',
        },
        {
          id: 'q-m36-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['metaprogramming'],
          prompt: 'What is the difference between seal and freeze?',
          options: [
            'They are identical',
            'seal prevents adding, deleting and reconfiguring but still allows changing values; freeze also prevents writes',
            'freeze is shallow, seal is deep',
            'seal works only on arrays',
          ],
          correct: 1,
          optionExplanations: [
            'Writability differs.',
            'Correct — freeze is seal plus writable: false.',
            'Both are shallow.',
            'Both work on any object.',
          ],
          explanation:
            'A sealed object\'s existing properties remain writable; freezing additionally sets `writable: false`. Both are **shallow**, leaving nested objects mutable.',
        },
      ],
    },
    summary:
      'Every property carries a **descriptor**: a **data** property has `value` and `writable`, an **accessor** property has `get` and `set`, and both have `enumerable` and `configurable`. These flags explain behaviour you already relied on — an array\'s `length` and class methods are **non-enumerable**, which is why they never appear in `Object.keys` or `for...in`. The critical asymmetry: **assignment** sets `writable`, `enumerable` and `configurable` all to **`true`**, while **`Object.defineProperty` defaults every omitted flag to `false`** — so `{ value: 1 }` alone produces a read-only, unenumerable, permanently locked property. That is the most common `defineProperty` mistake; state the flags explicitly. **`configurable: false` is irreversible** (only `writable` true→false remains possible), so set it deliberately and last. A descriptor is data **or** accessor, never both — supplying `value` alongside `get` throws. The lockdown functions form a ladder: **`preventExtensions`** (no additions), **`seal`** (no additions, deletions or reconfiguration), **`freeze`** (also no writes). All three are **shallow** — `Object.freeze(obj)` leaves `obj.nested.x = 2` working, the same trap as a shallow copy — and there is no built-in deep freeze. Note a write to a frozen property **throws in strict mode** and is silently ignored in sloppy mode.',
    keyTakeaways: [
      'A property has flags: writable, enumerable, configurable, plus value or get/set',
      'Assignment defaults all flags to true; defineProperty defaults them to false',
      'enumerable: false hides a property from keys, for...in, spread and JSON',
      'configurable: false cannot be undone',
      'freeze, seal and preventExtensions form a ladder — and all are shallow',
      'Writes to frozen properties throw in strict mode, fail silently in sloppy',
    ],
    relatedLessons: ['l-m36-01', 'l-m36-03'],
    interviewConnections: [
      'What is a property descriptor?',
      'How do defineProperty defaults differ from assignment?',
      'What is the difference between seal and freeze?',
      'Why is Object.freeze not enough for nested data?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m36-03',
    slug: 'proxy-and-reflect',
    moduleId: M,
    order: 3,
    title: 'Proxy and Reflect',
    description: 'Intercepting fundamental operations — and the judgement to use it rarely.',
    difficulty: DIFFICULTY.EXPERT,
    estimatedMinutes: 19,
    xp: 50,
    topicIds: ['metaprogramming'],
    prerequisites: ['l-m36-02'],
    learningObjectives: [
      'Write a Proxy with get, set, has and deleteProperty traps',
      'Explain why traps should delegate to Reflect',
      'Explain the receiver argument and why it matters',
      'Judge when a Proxy is and is not appropriate',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Intercepting operations',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A proxy wraps a target and can intervene on any operation.',
        code: [
          '"use strict";',
          '',
          'const target = { name: "Ada", role: "admin" };',
          '',
          'const log = [];',
          '',
          'const proxy = new Proxy(target, {',
          '  get(target, property, receiver) {',
          '    log.push(`get ${String(property)}`);',
          '    return Reflect.get(target, property, receiver);',
          '  },',
          '',
          '  set(target, property, value, receiver) {',
          '    log.push(`set ${String(property)}=${value}`);',
          '    return Reflect.set(target, property, value, receiver);',
          '  },',
          '',
          '  has(target, property) {',
          '    log.push(`has ${String(property)}`);',
          '    return Reflect.has(target, property);',
          '  },',
          '',
          '  deleteProperty(target, property) {',
          '    log.push(`delete ${String(property)}`);',
          '    return Reflect.deleteProperty(target, property);',
          '  },',
          '});',
          '',
          'proxy.name;',
          'proxy.age = 30;',
          '"role" in proxy;',
          'delete proxy.role;',
          '',
          'log.forEach((line) => console.log(line));',
          '',
          '// The TARGET was really modified — a proxy is a view, not a copy',
          'console.log("target now:", target);',
        ].join('\n'),
        output: [
          'get name',
          'set age=30',
          'has role',
          'delete role',
          'target now: {name: "Ada", age: 30}',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'A proxy is a view onto the target',
        body: [
          'Operations that reach the target really happen to it — the proxy is not a copy. Code holding the original `target` sees every change made through the proxy, and vice versa.',
          'A trap you do **not** define simply passes through to the target with default behaviour, so a `new Proxy(target, {})` is transparent. You only intercept what you write a trap for.',
        ],
      },
      {
        kind: SECTION.TABLE,
        headers: ['Trap', 'Intercepts'],
        rows: [
          ['`get`', '`proxy.x`, `proxy["x"]`'],
          ['`set`', '`proxy.x = 1`'],
          ['`has`', '`"x" in proxy`'],
          ['`deleteProperty`', '`delete proxy.x`'],
          ['`ownKeys`', '`Object.keys`, `for...in`, spread'],
          ['`apply`', 'Calling the proxy, when the target is a function'],
          ['`construct`', '`new proxy()`'],
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Why traps delegate to Reflect',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: '`Reflect` methods mirror the traps exactly.',
        code: [
          '"use strict";',
          '',
          'const target = { a: 1 };',
          '',
          'console.log("get   :", Reflect.get(target, "a"));',
          'console.log("set   :", Reflect.set(target, "b", 2), target.b);',
          'console.log("has   :", Reflect.has(target, "a"));',
          'console.log("delete:", Reflect.deleteProperty(target, "a"));',
          'console.log("keys  :", Reflect.ownKeys(target));',
          '',
          '// They return BOOLEANS where the old operators threw or coerced',
          'const frozen = Object.freeze({ x: 1 });',
          '',
          'console.log("Reflect.set on frozen:", Reflect.set(frozen, "x", 2));',
          '',
          'try {',
          '  frozen.x = 2;',
          '} catch (error) {',
          '  console.log("assignment           :", error.name);',
          '}',
        ].join('\n'),
        output: [
          'get   : 1',
          'set   : true 2',
          'has   : true',
          'delete: true',
          'keys  : ["b"]',
          'Reflect.set on frozen: false',
          'assignment           : TypeError',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Reflect exists to make traps correct',
        body: [
          'Every `Reflect` method corresponds to a trap and has the **same signature**, so `Reflect.get(...arguments)` inside a `get` trap is exactly the default behaviour. Writing `target[property]` instead is *nearly* the same and loses the `receiver`, which the next section shows matters.',
          '`Reflect` methods also return **booleans** where the equivalent operator throws or is awkward — a `set` trap must return `true` or `false` to report success, and `Reflect.set` gives you precisely that value.',
          'The rule: in a trap, do your extra work, then **delegate to the matching `Reflect` method**, passing every argument through.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The receiver argument, and why skipping it breaks getters.',
        code: [
          '"use strict";',
          '',
          'const base = {',
          '  first: "Ada",',
          '  last: "L",',
          '  get full() { return `${this.first} ${this.last}`; },',
          '};',
          '',
          '// A correct trap passes the receiver through',
          'const correct = new Proxy(base, {',
          '  get(target, property, receiver) {',
          '    return Reflect.get(target, property, receiver);',
          '  },',
          '});',
          '',
          '// A careless one drops it',
          'const careless = new Proxy(base, {',
          '  get(target, property) {',
          '    return target[property];',
          '  },',
          '});',
          '',
          '// With the proxy used directly, both look fine',
          'console.log("correct :", correct.full);',
          'console.log("careless:", careless.full);',
          '',
          '// But now inherit from each, overriding the underlying data',
          'const fromCorrect = Object.create(correct);',
          'fromCorrect.first = "Grace";',
          '',
          'const fromCareless = Object.create(careless);',
          'fromCareless.first = "Grace";',
          '',
          'console.log("inherited correct :", fromCorrect.full);',
          'console.log("inherited careless:", fromCareless.full);',
        ].join('\n'),
        output: [
          'correct : Ada L',
          'careless: Ada L',
          'inherited correct : Grace L',
          'inherited careless: Ada L',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'The receiver is the object the operation started on',
        body: [
          'When a getter runs, `this` should be the object the property was **read from**, not necessarily the one holding the getter. That object is the `receiver`.',
          'Passing it to `Reflect.get` makes the `full` getter see `Grace`, because the read started on `fromCorrect` where `first` was overridden. Writing `target[property]` runs the getter with `this` as the **target**, so it reads the original `Ada` — silently wrong, and only when inheritance is involved.',
          'This is why "just use `target[property]`" is bad advice. It works until someone puts the proxy in a prototype chain, and then produces a bug with no error attached to it.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Practical uses',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Validation on write.',
        code: [
          '"use strict";',
          '',
          'function validated(target, rules) {',
          '  return new Proxy(target, {',
          '    set(target, property, value, receiver) {',
          '      const rule = rules[property];',
          '',
          '      if (rule && !rule(value)) {',
          '        throw new TypeError(`invalid value for ${String(property)}`);',
          '      }',
          '',
          '      return Reflect.set(target, property, value, receiver);',
          '    },',
          '  });',
          '}',
          '',
          'const user = validated({}, {',
          '  age: (v) => Number.isInteger(v) && v >= 0,',
          '  name: (v) => typeof v === "string" && v.length > 0,',
          '});',
          '',
          'user.age = 30;',
          'user.name = "Ada";',
          'console.log("valid  :", user.age, user.name);',
          '',
          'try {',
          '  user.age = -5;',
          '} catch (error) {',
          '  console.log("rejected:", error.message);',
          '}',
          '',
          '// Unlisted properties pass through untouched',
          'user.other = true;',
          'console.log("passthrough:", user.other);',
        ].join('\n'),
        output: [
          'valid  : 30 Ada',
          'rejected: invalid value for age',
          'passthrough: true',
        ].join('\n'),
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A default value for missing properties.',
        code: [
          '"use strict";',
          '',
          'function withDefault(target, fallback) {',
          '  return new Proxy(target, {',
          '    get(target, property, receiver) {',
          '      if (Reflect.has(target, property)) {',
          '        return Reflect.get(target, property, receiver);',
          '      }',
          '',
          '      return fallback;',
          '    },',
          '  });',
          '}',
          '',
          'const counts = withDefault({ a: 1 }, 0);',
          '',
          'console.log("present:", counts.a);',
          'console.log("missing:", counts.zzz);',
          '',
          '// Careful: this affects EVERY read, including internal ones',
          'console.log("then   :", typeof counts.then);',
          'console.log("Symbol :", typeof counts[Symbol.iterator]);',
        ].join('\n'),
        output: [
          'present: 1',
          'missing: 0',
          'then   : number',
          'Symbol : number',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'That last output is a real bug waiting to happen',
        body: [
          'A blanket `get` trap intercepts **every** property read, including ones the language and libraries make internally. `counts.then` is now `0` rather than `undefined` — and because `await` and `Promise.resolve` check for a callable `then`, an object like this can behave strangely when awaited. `Symbol.iterator` is similarly affected.',
          'The fix is to exclude symbol keys and known internal names, or better, to narrow the trap so it only handles the properties you meant. This is a concrete example of why blanket interception is risky: you cannot see, from the trap, who is asking or why.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Invariants, and knowing when not to',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A proxy cannot lie about a non-configurable property.',
        code: [
          '"use strict";',
          '',
          'const target = {};',
          '',
          'Object.defineProperty(target, "locked", {',
          '  value: "real",',
          '  writable: false,',
          '  configurable: false,',
          '});',
          '',
          'const liar = new Proxy(target, {',
          '  get() { return "fake"; },',
          '});',
          '',
          'try {',
          '  liar.locked;',
          '} catch (error) {',
          '  console.log("invariant:", error.name);',
          '}',
          '',
          '// A normal property can be reported however the trap likes',
          'target.open = "real";',
          'console.log("normal   :", liar.open);',
        ].join('\n'),
        output: [
          'invariant: TypeError',
          'normal   : fake',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Proxies cannot break every guarantee',
        body: [
          'The specification enforces **invariants**: a trap cannot report a different value for a non-writable, non-configurable data property, cannot claim a non-configurable property does not exist, and cannot hide one from `ownKeys`. Violating one throws a `TypeError`.',
          'That exists so code holding a frozen object can still trust it, even if a proxy is in between. You do not need the full list — the useful takeaway is that proxies are powerful but not unlimited, and a trap that contradicts a locked property fails loudly.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Use a Proxy rarely, and deliberately',
        body: [
          '**Indirection.** Every operation runs your trap, so behaviour is no longer visible at the call site: `obj.x` might validate, log, fetch a default, or throw. Someone reading that line has no way to know.',
          '**Debugging.** Stepping through a proxied object means stepping through traps, and devtools display proxies awkwardly.',
          '**Cost.** Trapped operations are meaningfully slower than plain property access — usually irrelevant, occasionally not, and rarely worth it in a hot loop.',
          '**The alternative is usually better.** Validation belongs in a class with a setter or an explicit `update()` method; defaults belong in `??` at the point of use; logging belongs in the function doing the work. Reach for a `Proxy` when you must intercept **arbitrary, unknown** property names on an object you do not control — which is exactly what reactive frameworks and mocking libraries do, and rarely what application code needs.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '"use strict";',
          '',
          'const target = { a: 1 };',
          '',
          'const proxy = new Proxy(target, {',
          '  get(target, property) {',
          '    return property in target ? target[property] : "missing";',
          '  },',
          '});',
          '',
          'proxy.b = 2;',
          '',
          'console.log(proxy.a, proxy.zzz, target.b);',
        ].join('\n'),
        options: [
          '1 "missing" 2',
          '1 undefined 2',
          '1 "missing" undefined',
          'It throws',
        ],
        correct: 0,
        explanation:
          'The `get` trap returns the real value for `a` and the fallback for `zzz`. The key point is `target.b`: there is **no `set` trap**, so the assignment falls through to default behaviour and genuinely writes to the target — a proxy is a **view**, not a copy, and any operation you do not trap simply passes through. Note this trap also drops the `receiver`, which would silently break inherited getters, and its blanket fallback means `proxy.then` returns `"missing"` — a truthy non-function that can confuse `await`.',
      },
    ],
    exercises: [
      {
        id: 'ex-m36-03-a',
        title: 'Why delegate to Reflect?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.HARD,
        xp: 25,
        topicIds: ['metaprogramming'],
        instructions:
          'Why should a `get` trap call `Reflect.get(target, property, receiver)` rather than `target[property]`?',
        options: [
          'It is faster',
          'It preserves the receiver, so an inherited getter runs with the correct `this`',
          'target[property] does not work in a trap',
          'Reflect is required by the specification',
        ],
        correct: 1,
        hints: [
          'What is `this` inside a getter reached through a prototype chain?',
        ],
        solution: 'It preserves the receiver, so an inherited getter runs with the correct `this`',
        solutionExplanation:
          'The `receiver` is the object the operation **started on**, which is what a getter\'s `this` should be. `target[property]` runs any getter with `this` bound to the target, so an object inheriting from the proxy that overrides an underlying property gets stale values — silently, and only when inheritance is involved. `Reflect` methods mirror the traps exactly in signature and semantics, and return booleans that a `set` trap needs; `target[property]` does work, it is just subtly incorrect.',
      },
      {
        id: 'ex-m36-03-b',
        title: 'Build a validating proxy',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['metaprogramming'],
        instructions:
          'Write `positiveNumbers(target)` returning a proxy that throws a `TypeError` when a property is set to anything other than a positive number, and otherwise behaves normally.',
        starterCode: [
          'function positiveNumbers(target) {',
          '  // A set trap. Remember to delegate and return the result.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'allows a positive number', body: 'const p = positiveNumbers({}); p.a = 5; expect(p.a).toBe(5);' },
          { name: 'rejects a negative number', body: 'const p = positiveNumbers({}); expect(() => { p.a = -1; }).toThrow();' },
          { name: 'rejects zero', body: 'const p = positiveNumbers({}); expect(() => { p.a = 0; }).toThrow();' },
          { name: 'rejects a string', body: 'const p = positiveNumbers({}); expect(() => { p.a = "5"; }).toThrow();' },
          { name: 'rejects NaN', body: 'const p = positiveNumbers({}); expect(() => { p.a = NaN; }).toThrow();' },
          { name: 'writes through to the target', body: 'const t = {}; const p = positiveNumbers(t); p.a = 3; expect(t.a).toBe(3);' },
          { name: 'reads existing properties', body: 'expect(positiveNumbers({ existing: 9 }).existing).toBe(9);' },
          { name: 'leaves the value unchanged after a rejection', body: 'const p = positiveNumbers({}); p.a = 2; try { p.a = -1; } catch {} expect(p.a).toBe(2);', hidden: true },
        ],
        hints: [
          'Only a `set` trap is needed — reads pass through by default.',
          '`typeof value === "number" && value > 0` rejects NaN automatically.',
          'Return `Reflect.set(target, property, value, receiver)`.',
        ],
        solution: [
          'function positiveNumbers(target) {',
          '  return new Proxy(target, {',
          '    set(target, property, value, receiver) {',
          '      if (typeof value !== "number" || !(value > 0)) {',
          '        throw new TypeError(`${String(property)} must be a positive number`);',
          '      }',
          '',
          '      return Reflect.set(target, property, value, receiver);',
          '    },',
          '  });',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Only a `set` trap is defined, so reads pass straight through — the seventh test works with no `get` trap at all, which is the right instinct: trap only what you must. `!(value > 0)` rather than `value <= 0` is what rejects `NaN`, since every comparison with `NaN` is `false`. Throwing **before** delegating is what leaves the previous value intact after a rejection (the hidden test) — the invariant-preservation rule from Module 22. Returning `Reflect.set`\'s boolean correctly reports success to the language.',
      },
      {
        id: 'ex-m36-03-c',
        title: 'Count property reads',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['metaprogramming'],
        instructions:
          'Write `withReadCounts(target)` returning `{ proxy, counts }` where `counts` is a `Map` from property name to how many times it has been read through the proxy. Do not count symbol keys.',
        starterCode: [
          'function withReadCounts(target) {',
          '  // A get trap that records, then delegates.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'returns the value', body: 'const { proxy } = withReadCounts({ a: 1 }); expect(proxy.a).toBe(1);' },
          { name: 'counts one read', body: 'const { proxy, counts } = withReadCounts({ a: 1 }); proxy.a; expect(counts.get("a")).toBe(1);' },
          { name: 'counts repeated reads', body: 'const { proxy, counts } = withReadCounts({ a: 1 }); proxy.a; proxy.a; proxy.a; expect(counts.get("a")).toBe(3);' },
          { name: 'counts per property', body: 'const { proxy, counts } = withReadCounts({ a: 1, b: 2 }); proxy.a; proxy.b; proxy.b; expect([counts.get("a"), counts.get("b")]).toEqual([1, 2]);' },
          { name: 'counts reads of missing properties', body: 'const { proxy, counts } = withReadCounts({}); proxy.zzz; expect(counts.get("zzz")).toBe(1);' },
          { name: 'does not count writes', body: 'const { proxy, counts } = withReadCounts({}); proxy.a = 1; expect(counts.has("a")).toBe(false);' },
          { name: 'ignores symbol keys', body: 'const { proxy, counts } = withReadCounts({}); proxy[Symbol.iterator]; expect(counts.size).toBe(0);', hidden: true },
        ],
        hints: [
          'Create the `Map` outside the proxy so both can share it.',
          '`typeof property === "symbol"` should skip counting.',
          'Always `return Reflect.get(target, property, receiver)`.',
        ],
        solution: [
          'function withReadCounts(target) {',
          '  const counts = new Map();',
          '',
          '  const proxy = new Proxy(target, {',
          '    get(target, property, receiver) {',
          '      if (typeof property !== "symbol") {',
          '        counts.set(property, (counts.get(property) ?? 0) + 1);',
          '      }',
          '',
          '      return Reflect.get(target, property, receiver);',
          '    },',
          '  });',
          '',
          '  return { proxy, counts };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The `Map` lives in the closure and is returned alongside the proxy, so the caller can inspect it without the counts being a property the trap would itself intercept. Skipping symbol keys is the hidden test and a genuine necessity — the language reads `Symbol.iterator`, `Symbol.toPrimitive` and others internally, so counting them would report reads nobody wrote. Delegating with the `receiver` keeps inherited getters correct, and defining no `set` trap means writes pass through uncounted, as the sixth test requires.',
      },
      {
        id: 'ex-m36-03-d',
        title: 'When not to use a Proxy',
        kind: EXERCISE_KIND.CHOOSE_IMPLEMENTATION,
        difficulty: DIFFICULTY.HARD,
        xp: 25,
        topicIds: ['metaprogramming'],
        instructions:
          'You need to validate that a `User` object\'s `age` is a non-negative integer. What is the best approach?',
        options: [
          'A Proxy with a set trap',
          'A class with a setter or an explicit update method that validates',
          'Freeze the object',
          'A Proxy with get and set traps',
        ],
        correct: 1,
        hints: [
          'Do you know the property names in advance?',
        ],
        solution: 'A class with a setter or an explicit update method that validates',
        solutionExplanation:
          'The property is **known in advance**, so ordinary language features handle it: a setter or an `update()` method makes the validation visible at the definition site, is easy to debug and test, and costs nothing. A `Proxy` would work but hides behaviour behind plain-looking property access — a reader of `user.age = -1` has no indication that anything validates it. Freezing prevents all writes rather than validating them. Reserve proxies for intercepting **arbitrary, unknown** property names on objects you do not control, which is what reactive frameworks and mocking libraries do.',
      },
    ],
    quiz: {
      id: 'qz-m36-03',
      questions: [
        {
          id: 'q-m36-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['metaprogramming'],
          prompt: 'What happens to an operation with no matching trap?',
          options: [
            'It throws',
            'It passes through to the target with default behaviour',
            'It returns undefined',
            'The proxy must define every trap',
          ],
          correct: 1,
          optionExplanations: [
            'No error occurs.',
            'Correct — new Proxy(t, {}) is transparent.',
            'The real result is returned.',
            'Traps are all optional.',
          ],
          explanation:
            'Untrapped operations behave normally on the target, so you intercept only what you write a trap for — and a proxy with an empty handler is transparent.',
        },
        {
          id: 'q-m36-03-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['metaprogramming'],
          prompt: 'What is the receiver argument in a get trap?',
          options: [
            'The target object',
            'The object the operation started on — what a getter\'s `this` should be',
            'The proxy handler',
            'The property name',
          ],
          correct: 1,
          optionExplanations: [
            'The target is a separate argument.',
            'Correct — pass it to Reflect.get.',
            'The handler is not passed.',
            'That is `property`.',
          ],
          explanation:
            'It is the object the read began on, which matters when the proxy is in a prototype chain. Dropping it makes inherited getters read from the target instead.',
        },
        {
          id: 'q-m36-03-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['metaprogramming'],
          prompt: 'A proxy can report any value it likes for any property.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Invariants are enforced.',
            'Correct — a locked property cannot be misreported.',
          ],
          explanation:
            'A trap that reports a different value for a non-writable, non-configurable property throws a `TypeError`. Invariants exist so code holding a frozen object can still trust it.',
        },
        {
          id: 'q-m36-03-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['metaprogramming'],
          prompt: 'What is a genuine reason to reach for a Proxy?',
          options: [
            'Validating a known field on a known class',
            'Intercepting arbitrary, unknown property names on an object you do not control',
            'Providing a default value at one call site',
            'Making code shorter',
          ],
          correct: 1,
          optionExplanations: [
            'A setter is clearer.',
            'Correct — reactive systems and mocking libraries.',
            '`??` is clearer.',
            'It adds indirection, not brevity.',
          ],
          explanation:
            'Proxies earn their cost when the property names are not known in advance. Known fields are better served by setters, and defaults by `??` at the point of use.',
        },
      ],
    },
    summary:
      'A **`Proxy`** wraps a target and intercepts fundamental operations through **traps** — `get`, `set`, `has`, `deleteProperty`, `ownKeys`, `apply`, `construct`. An untrapped operation passes through with default behaviour, so an empty handler is transparent, and a proxy is a **view onto the target**, not a copy: writes really reach it. **`Reflect`** exists to make traps correct: every method mirrors a trap with the **same signature**, so `Reflect.get(target, property, receiver)` *is* the default behaviour, and it returns the **boolean** a `set` trap must report. Crucially, the **`receiver`** is the object the operation **started on** — what a getter\'s `this` should be — so writing `target[property]` instead silently breaks inherited getters when the proxy sits in a prototype chain. Proxies cannot break everything: **invariants** prevent a trap from misreporting a non-writable, non-configurable property, so code holding a frozen object can still trust it. The judgement matters more than the mechanics. A blanket `get` trap intercepts **every** read, including internal ones — a fallback that makes `obj.then` truthy can confuse `await`. Proxies add **indirection** invisible at the call site, are awkward to debug, and cost performance. Reach for one only to intercept **arbitrary, unknown** property names on objects you do not control; known fields belong in a setter, and defaults in `??` at the point of use.',
    keyTakeaways: [
      'Untrapped operations pass through; a proxy is a view, not a copy',
      'Delegate from every trap to the matching Reflect method',
      'Pass the receiver through, or inherited getters read the wrong object',
      'A set trap must return a boolean — Reflect.set supplies it',
      'Invariants stop a proxy misreporting a locked property',
      'Use proxies for unknown property names; prefer setters and ?? otherwise',
    ],
    relatedLessons: ['l-m36-02', 'l-m36-01'],
    interviewConnections: [
      'What is a Proxy and what can it intercept?',
      'Why do proxy traps use Reflect?',
      'What is the receiver argument for?',
      'When would a Proxy be the wrong tool?',
    ],
  },
];
