import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm40';

export default [
  /* ================================================================== */
  {
    id: 'l-m40-01',
    slug: 'naming-and-intent',
    moduleId: M,
    order: 1,
    title: 'Naming and Intent',
    description: 'Names that make comments unnecessary — and the magic values that hide meaning.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 16,
    xp: 40,
    topicIds: ['clean-code'],
    prerequisites: ['l-m39-03'],
    learningObjectives: [
      'Choose names that reveal intent rather than mechanics',
      'Name booleans and functions by convention',
      'Replace magic values with meaningful constants',
      'Write comments that explain why, not what',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'A name is the cheapest documentation',
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Before',
          code: [
            'function calc(x, y) {',
            '  const d = 86400000;',
            '  const t = y - x;',
            '',
            '  if (t > d * 30) {',
            '    return 0.2;',
            '  }',
            '',
            '  return 0;',
            '}',
          ].join('\n'),
        },
        right: {
          title: 'After',
          code: [
            'const MS_PER_DAY = 86_400_000;',
            'const LOYALTY_DAYS = 30;',
            'const LOYALTY_DISCOUNT = 0.2;',
            '',
            'function discountFor(',
            '  signupDate, now,',
            ') {',
            '  const days =',
            '    (now - signupDate)',
            '    / MS_PER_DAY;',
            '',
            '  return days > LOYALTY_DAYS',
            '    ? LOYALTY_DISCOUNT',
            '    : 0;',
            '}',
          ].join('\n'),
        },
        note: 'The "after" version is longer and needs no explanation. `calc(x, y)` could be anything; `discountFor(signupDate, now)` states what it does and what it needs. Note the numeric separators in `86_400_000` — a small readability win that costs nothing.',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The same logic, named for intent.',
        code: [
          '"use strict";',
          '',
          'const MS_PER_DAY = 86_400_000;',
          'const LOYALTY_THRESHOLD_DAYS = 30;',
          'const LOYALTY_DISCOUNT = 0.2;',
          '',
          'function daysBetween(earlier, later) {',
          '  return (later - earlier) / MS_PER_DAY;',
          '}',
          '',
          'function discountFor(signupDate, now) {',
          '  const membershipDays = daysBetween(signupDate, now);',
          '',
          '  return membershipDays > LOYALTY_THRESHOLD_DAYS ? LOYALTY_DISCOUNT : 0;',
          '}',
          '',
          '// Fixed dates, so the example is deterministic (Module 37)',
          'const signup = new Date("2024-01-01T00:00:00Z").getTime();',
          'const soon = new Date("2024-01-10T00:00:00Z").getTime();',
          'const later = new Date("2024-03-01T00:00:00Z").getTime();',
          '',
          'console.log("9 days  :", discountFor(signup, soon));',
          'console.log("60 days :", discountFor(signup, later));',
          'console.log("readable:", daysBetween(signup, later));',
        ].join('\n'),
        output: [
          '9 days  : 0',
          '60 days : 0.2',
          'readable: 60',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Name what it means, not what it is',
        body: [
          '`userArray` tells you the type, which the code already shows. `activeUsers` tells you what is in it, which the code does not.',
          '`data`, `info`, `item`, `temp`, `result`, `handleData` — these are placeholders that survived into production. If a name would fit equally well in a completely different function, it is not carrying information.',
          'Length is not the goal. `i` is a perfectly good loop index, `id` is clearer than `identifier`, and `getUserAccountInformationFromDatabase` is worse than `findUser`. Aim for the shortest name that is unambiguous **in its context**.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Conventions that carry meaning',
      },
      {
        kind: SECTION.TABLE,
        headers: ['Kind', 'Convention', 'Examples'],
        rows: [
          ['Boolean', '`is` / `has` / `can` / `should`', '`isActive`, `hasPermission`, `canEdit`, `shouldRetry`'],
          ['Function returning a value', 'A verb phrase', '`calculateTotal`, `findUser`, `formatDate`'],
          ['Function performing an effect', 'A verb phrase naming the effect', '`saveOrder`, `renderList`, `sendEmail`'],
          ['Collection', 'Plural noun', '`users`, `activeOrders`'],
          ['Constant', '`SCREAMING_SNAKE_CASE` for fixed configuration', '`MAX_RETRIES`, `API_BASE_URL`'],
          ['Class', '`PascalCase` noun', '`ShoppingCart`, `HttpError`'],
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Boolean names that read as questions.',
        code: [
          '"use strict";',
          '',
          '// Unclear: what does a truthy `status` mean?',
          'function canCheckoutUnclear(user) {',
          '  const status = user.verified && user.balance > 0;',
          '  return status;',
          '}',
          '',
          '// Clear: each condition names itself, and the whole reads as English',
          'function canCheckout(user) {',
          '  const isVerified = user.verified;',
          '  const hasFunds = user.balance > 0;',
          '  const isSuspended = user.suspendedUntil !== null;',
          '',
          '  return isVerified && hasFunds && !isSuspended;',
          '}',
          '',
          'const ready = { verified: true, balance: 50, suspendedUntil: null };',
          'const broke = { verified: true, balance: 0, suspendedUntil: null };',
          'const banned = { verified: true, balance: 50, suspendedUntil: "2030-01-01" };',
          '',
          'console.log("ready  :", canCheckout(ready));',
          'console.log("broke  :", canCheckout(broke));',
          'console.log("banned :", canCheckout(banned));',
        ].join('\n'),
        output: [
          'ready  : true',
          'broke  : false',
          'banned : false',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'Avoid negated boolean names',
        body: [
          '`isNotActive` reads badly the moment you negate it: `if (!isNotActive)` is a double negative the reader must decode. Name the positive — `isActive` — and negate at the point of use.',
          'The same applies to `disabled` versus `enabled`. Pick whichever is the more natural default state to talk about, and stick to it across the codebase; mixing both is what causes real confusion.',
          'Note the intermediate constants in `canCheckout` are not wasted. Naming `user.suspendedUntil !== null` as `isSuspended` turns a comparison into a concept, which is the whole point of the technique.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Magic values',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Which literals deserve names, and which do not.',
        code: [
          '"use strict";',
          '',
          'const MAX_RETRIES = 3;',
          'const HTTP_TOO_MANY_REQUESTS = 429;',
          'const FREE_SHIPPING_THRESHOLD = 50;',
          '',
          'function shouldRetry(status, attempt) {',
          '  // The named constants say WHY these numbers matter',
          '  if (attempt >= MAX_RETRIES) return false;',
          '',
          '  return status >= 500 || status === HTTP_TOO_MANY_REQUESTS;',
          '}',
          '',
          'function shippingCost(subtotal) {',
          '  // 0 and 5 need no names — their meaning is fully local',
          '  return subtotal >= FREE_SHIPPING_THRESHOLD ? 0 : 5;',
          '}',
          '',
          'console.log("retry 500 :", shouldRetry(500, 1));',
          'console.log("retry 429 :", shouldRetry(429, 1));',
          'console.log("retry 404 :", shouldRetry(404, 1));',
          'console.log("exhausted :", shouldRetry(500, 3));',
          '',
          'console.log("free ship :", shippingCost(60));',
          'console.log("paid ship :", shippingCost(20));',
        ].join('\n'),
        output: [
          'retry 500 : true',
          'retry 429 : true',
          'retry 404 : false',
          'exhausted : false',
          'free ship : 0',
          'paid ship : 5',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Do not extract every literal',
        body: [
          'A constant earns its name when the number is **arbitrary** (why 3 retries and not 4?), **repeated**, or **domain-specific** (429 means something particular). `MAX_RETRIES` and `HTTP_TOO_MANY_REQUESTS` all qualify.',
          'Extracting `const ZERO = 0` or `const ONE = 1` is worse than the literal — it adds indirection while communicating nothing, and it goes badly wrong if someone ever "updates" it.',
          'Note `status >= 500` was left inline. It is a well-known convention and the surrounding function name explains it; naming it `SERVER_ERROR_MINIMUM` would be defensible but is not an improvement here. Judgement, not a rule.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Comments',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Comments that earn their place, and ones that do not.',
        code: [
          '"use strict";',
          '',
          'function applyLateFee(balance, daysLate) {',
          '  // BAD: this just translates the next line into English',
          '  // increment the balance',
          '  let total = balance;',
          '',
          '  // GOOD: explains a decision the code cannot state',
          '  // Regulation caps late fees at 15% of the balance, so the daily',
          '  // rate is deliberately ignored once that ceiling is reached.',
          '  const cap = balance * 0.15;',
          '  const accrued = Math.min(daysLate * 2, cap);',
          '',
          '  total += accrued;',
          '  return total;',
          '}',
          '',
          'console.log("2 days on 100 :", applyLateFee(100, 2));',
          'console.log("capped        :", applyLateFee(100, 50));',
          '',
          '// GOOD: warns about a non-obvious constraint',
          'function parseIdList(text) {',
          '  // The upstream service separates ids with a semicolon, not a comma,',
          '  // despite what its documentation says. Verified 2024-03.',
          '  return text.split(";").filter(Boolean);',
          '}',
          '',
          'console.log("ids           :", parseIdList("a;b;;c"));',
        ].join('\n'),
        output: [
          '2 days on 100 : 104',
          'capped        : 115',
          'ids           : ["a", "b", "c"]',
        ].join('\n'),
      },
      {
        kind: SECTION.LIST,
        items: [
          '**Explain why, not what.** The code already says what it does. `// increment count` above `count++` is noise that will eventually contradict the code.',
          '**Document constraints and decisions.** Why this cap exists, why this order matters, why the obvious approach was rejected.',
          '**Warn about surprises.** External systems that behave contrary to their documentation, workarounds for known bugs — with a date, so a reader knows how stale it might be.',
          '**Prefer a name over a comment.** If a comment explains what a block does, extracting it into a named function usually says the same thing more durably.',
          '**Delete commented-out code.** Version control remembers it; the file should not.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Comments rot; code does not',
        body: [
          'A comment describing *what* the code does is a second copy of the logic, and nothing forces the two to stay in sync. When they drift, the comment is worse than useless — it actively misleads, because readers trust it.',
          'A comment describing *why* has no such duplicate, so it stays true for as long as the reason does.',
          'This is not an argument against comments. It is an argument for comments that say something the code genuinely cannot.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// Which of these names is the problem?',
          '',
          'function process(data) {',
          '  const result = data.filter((item) => item.flag);',
          '  return result;',
          '}',
        ].join('\n'),
        options: [
          'All of them — process, data, item, flag and result each name a type or a placeholder rather than a meaning',
          'Only `data`',
          'None — they are short and readable',
          'Only `flag`',
        ],
        correct: 0,
        explanation:
          'Every name here would fit equally well in a completely unrelated function, which is the test for an uninformative name. `process` names no particular action; `data` and `item` name shapes rather than contents; `result` says only "the thing returned"; and `flag` names the type of the property rather than what it signifies. Compare `function activeUsers(users) { return users.filter((user) => user.isActive); }` — the same code, where the name now tells you what comes back and the predicate reads as a sentence. Note `item` inside a genuinely generic utility would be fine; it is uninformative here precisely because this function is **not** generic.',
      },
    ],
    exercises: [
      {
        id: 'ex-m40-01-a',
        title: 'Rename for intent',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.EASY,
        xp: 25,
        topicIds: ['clean-code'],
        instructions:
          'Rewrite `chk(a, b)` as a well-named function. It returns whether an order qualifies for free shipping: the subtotal must reach the threshold and the order must not be a gift card. Name it, its parameters, and extract the threshold as a constant.',
        starterCode: [
          '// function chk(a, b) {',
          '//   return a >= 50 && !b;',
          '// }',
          '',
          '// Write the clear version. It must accept (subtotal, isGiftCard).',
        ].join('\n'),
        tests: [
          { name: 'qualifies above the threshold', body: 'expect(qualifiesForFreeShipping(60, false)).toBe(true);' },
          { name: 'qualifies exactly at the threshold', body: 'expect(qualifiesForFreeShipping(50, false)).toBe(true);' },
          { name: 'does not qualify below', body: 'expect(qualifiesForFreeShipping(49, false)).toBe(false);' },
          { name: 'a gift card never qualifies', body: 'expect(qualifiesForFreeShipping(500, true)).toBe(false);' },
          { name: 'returns a boolean', body: 'expect(typeof qualifiesForFreeShipping(60, false)).toBe("boolean");' },
          { name: 'handles zero', body: 'expect(qualifiesForFreeShipping(0, false)).toBe(false);' },
          { name: 'the threshold is a named constant', body: 'expect(typeof FREE_SHIPPING_THRESHOLD).toBe("number");', hidden: true },
        ],
        hints: [
          'The function name should read as a question, since it returns a boolean.',
          'Declare `const FREE_SHIPPING_THRESHOLD = 50;` above it.',
          'Name the parameters `subtotal` and `isGiftCard`.',
        ],
        solution: [
          'const FREE_SHIPPING_THRESHOLD = 50;',
          '',
          'function qualifiesForFreeShipping(subtotal, isGiftCard) {',
          '  return subtotal >= FREE_SHIPPING_THRESHOLD && !isGiftCard;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The name now states the question the function answers, so a call site reads as a sentence — `if (qualifiesForFreeShipping(total, isGift))` needs no comment. Naming the parameters is what makes the argument order safe: `chk(a, b)` gave a caller no way to know which was which. The constant explains that `50` is a business rule rather than an arbitrary number, and it means changing the policy is a one-line edit in one place rather than a search across the codebase.',
      },
      {
        id: 'ex-m40-01-b',
        title: 'Which literal needs a name?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['clean-code'],
        instructions:
          'Which of these literals most deserves extraction into a named constant?',
        options: [
          '`0` in `let total = 0;`',
          '`429` in `if (status === 429) retry();`',
          '`1` in `index + 1`',
          '`2` in `values.length / 2`',
        ],
        correct: 1,
        hints: [
          'Which number carries meaning a reader cannot infer?',
        ],
        solution: '`429` in `if (status === 429) retry();`',
        solutionExplanation:
          '`429` is **domain-specific** — it means "too many requests", which the digits do not convey to anyone who has not memorised HTTP status codes. `HTTP_TOO_MANY_REQUESTS` says it outright. The others are **structural**: `0` as an accumulator seed, `1` for the next index, and `2` for a midpoint are idioms whose meaning is fully local and obvious. Extracting them would add indirection while communicating nothing — a constant earns its name when the value is arbitrary, repeated, or domain-specific.',
      },
      {
        id: 'ex-m40-01-c',
        title: 'Name the booleans',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['clean-code'],
        instructions:
          'Write `canPublish(post, user)` returning whether a post may be published: it must have a title and body, the user must have the `editor` role, and the post must not already be published.',
        starterCode: [
          'function canPublish(post, user) {',
          '  // Name each condition before combining them.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'allows a complete draft by an editor', body: 'expect(canPublish({ title: "t", body: "b", published: false }, { role: "editor" })).toBe(true);' },
          { name: 'rejects a missing title', body: 'expect(canPublish({ title: "", body: "b", published: false }, { role: "editor" })).toBe(false);' },
          { name: 'rejects a missing body', body: 'expect(canPublish({ title: "t", body: "", published: false }, { role: "editor" })).toBe(false);' },
          { name: 'rejects a non-editor', body: 'expect(canPublish({ title: "t", body: "b", published: false }, { role: "viewer" })).toBe(false);' },
          { name: 'rejects an already-published post', body: 'expect(canPublish({ title: "t", body: "b", published: true }, { role: "editor" })).toBe(false);' },
          { name: 'returns a boolean', body: 'expect(typeof canPublish({ title: "t", body: "b", published: false }, { role: "editor" })).toBe("boolean");' },
          { name: 'rejects a whitespace-only title', body: 'expect(canPublish({ title: "   ", body: "b", published: false }, { role: "editor" })).toBe(false);', hidden: true },
        ],
        hints: [
          'Declare `const hasTitle = ...` and similar before the return.',
          '`.trim()` handles a whitespace-only title.',
          'Combine the named conditions in a single readable expression.',
        ],
        solution: [
          'function canPublish(post, user) {',
          '  const hasTitle = post.title.trim().length > 0;',
          '  const hasBody = post.body.trim().length > 0;',
          '  const isEditor = user.role === "editor";',
          '  const isAlreadyPublished = post.published;',
          '',
          '  return hasTitle && hasBody && isEditor && !isAlreadyPublished;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Each condition gets a name that states what it means, so the final line reads as the business rule rather than as four comparisons — and a reader can check the rule without decoding any of them. `trim()` is what makes the hidden test pass: a whitespace-only title is not a title, and a bare `length > 0` check would accept `"   "`. Naming the positive `isAlreadyPublished` and negating at the point of use is clearer than an `isNotPublished` that would read as a double negative when combined.',
      },
      {
        id: 'ex-m40-01-d',
        title: 'Which comment is worth keeping?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['clean-code'],
        instructions:
          'Which comment adds genuine value?',
        options: [
          '`// loop through the users` above `for (const user of users)`',
          '`// The API returns dates in local time despite documenting UTC, so we normalise here`',
          '`// set x to 5` above `const x = 5;`',
          '`// function` above a function declaration',
        ],
        correct: 1,
        hints: [
          'Which one says something the code cannot?',
        ],
        solution: '`// The API returns dates in local time despite documenting UTC, so we normalise here`',
        solutionExplanation:
          'That comment records a fact about an **external system** that no amount of reading the code could reveal, and it explains why an otherwise-puzzling normalisation step exists — without it, a future reader might "clean up" the conversion and introduce a bug. The other three restate what the next line plainly says. Such comments are worse than absent: they are a second copy of the logic that nothing keeps in sync, so when they drift they actively mislead readers who trust them.',
      },
    ],
    quiz: {
      id: 'qz-m40-01',
      questions: [
        {
          id: 'q-m40-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['clean-code'],
          prompt: 'What is the test for an uninformative name?',
          options: [
            'It is shorter than five characters',
            'It would fit equally well in a completely unrelated function',
            'It does not include the type',
            'It is not camelCase',
          ],
          correct: 1,
          optionExplanations: [
            '`id` and `i` are short and fine.',
            'Correct — it carries no information about this code.',
            'Including the type is usually noise.',
            'Casing is a separate concern.',
          ],
          explanation:
            '`data`, `result`, `process` and `item` fit anywhere, which is exactly why they say nothing. A good name would look wrong if moved elsewhere.',
        },
        {
          id: 'q-m40-01-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['clean-code'],
          prompt: 'Why avoid names like isNotActive?',
          options: [
            'They are too long',
            'Negating them creates a double negative the reader must decode',
            'They cannot be used in conditions',
            'They break linting',
          ],
          correct: 1,
          optionExplanations: [
            'Length is not the issue.',
            'Correct — `!isNotActive` is hard to read.',
            'They work fine.',
            'No linter forbids them.',
          ],
          explanation:
            'Name the positive form and negate at the point of use. Mixing `enabled` and `disabled` across a codebase causes the same confusion.',
        },
        {
          id: 'q-m40-01-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['clean-code'],
          prompt: 'Every numeric literal should be extracted into a named constant.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            '`const ZERO = 0` communicates nothing.',
            'Correct — extract arbitrary, repeated or domain-specific values.',
          ],
          explanation:
            'Structural literals like `0` for an accumulator or `1` for the next index are idioms whose meaning is local. Extract values that are arbitrary, repeated, or carry domain meaning such as `429`.',
        },
        {
          id: 'q-m40-01-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['clean-code'],
          prompt: 'Why is a comment describing what the code does worse than no comment?',
          options: [
            'It takes up space',
            'It duplicates the logic with nothing keeping the two in sync, so when it drifts it misleads',
            'Comments are always bad',
            'It slows the parser',
          ],
          correct: 1,
          optionExplanations: [
            'Space is not the concern.',
            'Correct — readers trust comments.',
            'Comments explaining why are valuable.',
            'Parsing cost is irrelevant.',
          ],
          explanation:
            'A "what" comment is a second copy of the code that nothing forces to stay accurate. A "why" comment has no duplicate, so it remains true as long as the reason does.',
        },
      ],
    },
    summary:
      'A **name is the cheapest documentation** you can write. Name for **intent**, not type or mechanics: `userArray` states what the code already shows, while `activeUsers` states what the code cannot. The test for an uninformative name is whether it would fit equally well in an unrelated function — `data`, `result`, `process`, `item`, `temp` all fail it. Length is not the goal: `i` is a fine loop index and `getUserAccountInformationFromDatabase` is worse than `findUser`; aim for the shortest name unambiguous **in context**. Conventions carry meaning for free — `is`/`has`/`can`/`should` for booleans, verb phrases for functions, plurals for collections, `SCREAMING_SNAKE_CASE` for fixed configuration. **Avoid negated names**: `!isNotActive` is a double negative, so name the positive and negate at the point of use. Extract a **magic value** when it is **arbitrary**, **repeated**, or **domain-specific** (`429` means "too many requests"; the digits do not say so) — but `const ZERO = 0` is worse than the literal, and structural numbers like `0` and `1` should stay inline. For **comments**, explain **why, not what**: a "what" comment duplicates the logic with nothing keeping the two in sync, so when it drifts it **actively misleads** readers who trust it, whereas a "why" comment stays true as long as its reason does. Prefer extracting a named function over commenting a block, and delete commented-out code.',
    keyTakeaways: [
      'A good name would look wrong if moved to another function',
      'Name for meaning, not type — activeUsers, not userArray',
      'Booleans read as questions: is, has, can, should',
      'Name the positive form and negate at the point of use',
      'Extract arbitrary, repeated or domain-specific values — not every literal',
      'Comments explain why; "what" comments drift and mislead',
    ],
    relatedLessons: ['l-m40-02', 'l-m40-03'],
    interviewConnections: [
      'What makes a good variable name?',
      'When should a number become a named constant?',
      'What kinds of comments are worth writing?',
      'Why are negated boolean names a problem?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m40-02',
    slug: 'functions-and-control-flow',
    moduleId: M,
    order: 2,
    title: 'Functions and Control Flow',
    description: 'Guard clauses, one responsibility, and flattening code without dogma.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 17,
    xp: 45,
    topicIds: ['clean-code'],
    prerequisites: ['l-m40-01'],
    learningObjectives: [
      'Flatten nested conditionals with guard clauses',
      'Judge whether a function has one responsibility',
      'Keep a function at a single level of abstraction',
      'Manage parameter count with options objects',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Guard clauses',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The same rules, nested and flattened.',
        code: [
          '"use strict";',
          '',
          '// NESTED: the happy path is buried four levels deep',
          'function checkoutNested(user, cart) {',
          '  if (user) {',
          '    if (user.verified) {',
          '      if (cart.items.length > 0) {',
          '        if (cart.total > 0) {',
          '          return { ok: true, charged: cart.total };',
          '        } else {',
          '          return { ok: false, reason: "empty total" };',
          '        }',
          '      } else {',
          '        return { ok: false, reason: "empty cart" };',
          '      }',
          '    } else {',
          '      return { ok: false, reason: "unverified" };',
          '    }',
          '  } else {',
          '    return { ok: false, reason: "no user" };',
          '  }',
          '}',
          '',
          '// GUARDED: each failure exits immediately; the happy path is last and flat',
          'function checkout(user, cart) {',
          '  if (!user) return { ok: false, reason: "no user" };',
          '  if (!user.verified) return { ok: false, reason: "unverified" };',
          '  if (cart.items.length === 0) return { ok: false, reason: "empty cart" };',
          '  if (cart.total <= 0) return { ok: false, reason: "empty total" };',
          '',
          '  return { ok: true, charged: cart.total };',
          '}',
          '',
          'const good = { verified: true };',
          'const cart = { items: ["a"], total: 25 };',
          '',
          'console.log("nested  :", checkoutNested(good, cart));',
          'console.log("guarded :", checkout(good, cart));',
          'console.log("agree   :", JSON.stringify(checkoutNested(null, cart)) === JSON.stringify(checkout(null, cart)));',
          'console.log("empty   :", checkout(good, { items: [], total: 0 }));',
        ].join('\n'),
        output: [
          'nested  : {ok: true, charged: 25}',
          'guarded : {ok: true, charged: 25}',
          'agree   : true',
          'empty   : {ok: false, reason: "empty cart"}',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Why flatter reads better here',
        body: [
          'In the nested version, understanding the success case means tracking four open conditions simultaneously, and each `else` is separated from its `if` by the whole block it guards.',
          'With guards, every line is a complete thought — "no user? stop" — and the reader can discard each one immediately after reading it. The success path ends up **unindented and last**, which is where the eye expects the answer.',
          'This also makes adding a rule a one-line change, rather than another level of nesting that pushes everything right.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Guard clauses are not always the answer',
        body: [
          'Two genuinely balanced branches read better as `if`/`else` than as a guard plus a fallthrough — `if (isWeekend) return weekendRate; return weekdayRate;` obscures that the two are equal alternatives.',
          'And twelve guards in a row is its own smell: it usually means the function is validating something that deserves its own `validate()` function returning a list of problems.',
          'The principle is "keep the main path visible and shallow", not "always return early".',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'One responsibility',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A function doing four jobs, split into four.',
        code: [
          '"use strict";',
          '',
          'const log = [];',
          '',
          '// BEFORE: validates, calculates, formats and reports',
          'function processOrderBefore(order) {',
          '  if (!order.items || order.items.length === 0) {',
          '    log.push("error: empty order");',
          '    return null;',
          '  }',
          '',
          '  let total = 0;',
          '  for (const item of order.items) total += item.price * item.quantity;',
          '',
          '  const withTax = total * 1.2;',
          '  const formatted = `$${withTax.toFixed(2)}`;',
          '',
          '  log.push(`processed ${order.id}: ${formatted}`);',
          '  return formatted;',
          '}',
          '',
          '// AFTER: each function does one thing and can be tested alone',
          'function validateOrder(order) {',
          '  if (!order.items || order.items.length === 0) return "empty order";',
          '  return null;',
          '}',
          '',
          'function subtotal(items) {',
          '  return items.reduce((sum, item) => sum + item.price * item.quantity, 0);',
          '}',
          '',
          'function withTax(amount, rate) {',
          '  return amount * (1 + rate);',
          '}',
          '',
          'function formatCurrency(amount) {',
          '  return `$${amount.toFixed(2)}`;',
          '}',
          '',
          '// The orchestrator names the steps and holds the effects',
          'function processOrder(order, report) {',
          '  const problem = validateOrder(order);',
          '',
          '  if (problem) {',
          '    report(`error: ${problem}`);',
          '    return null;',
          '  }',
          '',
          '  const formatted = formatCurrency(withTax(subtotal(order.items), 0.2));',
          '',
          '  report(`processed ${order.id}: ${formatted}`);',
          '  return formatted;',
          '}',
          '',
          'const order = { id: 7, items: [{ price: 10, quantity: 2 }, { price: 5, quantity: 1 }] };',
          '',
          'console.log("before:", processOrderBefore(order));',
          'console.log("after :", processOrder(order, (line) => log.push(line)));',
          '',
          '// Every piece is now testable with plain values, no setup',
          'console.log("subtotal :", subtotal(order.items));',
          'console.log("with tax :", withTax(25, 0.2));',
          'console.log("formatted:", formatCurrency(30));',
          'console.log("invalid  :", validateOrder({ items: [] }));',
        ].join('\n'),
        output: [
          'before: $30.00',
          'after : $30.00',
          'subtotal : 25',
          'with tax : 30',
          'formatted: $30.00',
          'invalid  : empty order',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'The test is reasons to change, not line count',
        body: [
          '"Functions must be under 10 lines" is a rule that produces worse code — it forces arbitrary splits that scatter one idea across several functions, so the reader has to reassemble it.',
          'The useful test is Module 28\'s: **does this function have more than one reason to change?** `processOrderBefore` changes when validation rules change, when the tax rate changes, when the currency format changes, and when logging changes. Four reasons, four responsibilities.',
          'Notice `report` is **passed in** rather than the function reaching for a module-level `log`. That is the dependency inversion from Module 28, and it is what let the example test `processOrder` by handing it a plain function.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'One level of abstraction',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Mixed levels, and levelled.',
        code: [
          '"use strict";',
          '',
          '// MIXED: a high-level step sits next to character-by-character parsing',
          'function summariseMixed(csv) {',
          '  const rows = csv.split("\\n");',
          '  const header = rows[0].split(",");',
          '  let total = 0;',
          '',
          '  for (let i = 1; i < rows.length; i++) {',
          '    const cells = rows[i].split(",");',
          '    const amountIndex = header.indexOf("amount");',
          '    total += Number(cells[amountIndex]);',
          '  }',
          '',
          '  return `${rows.length - 1} rows totalling ${total}`;',
          '}',
          '',
          '// LEVELLED: the top function reads as a description of the process',
          'function parseCsv(csv) {',
          '  const [headerRow, ...dataRows] = csv.split("\\n");',
          '  const header = headerRow.split(",");',
          '',
          '  return dataRows.map((row) => {',
          '    const cells = row.split(",");',
          '    return Object.fromEntries(header.map((key, i) => [key, cells[i]]));',
          '  });',
          '}',
          '',
          'function sumField(records, field) {',
          '  return records.reduce((sum, record) => sum + Number(record[field]), 0);',
          '}',
          '',
          'function summarise(csv) {',
          '  const records = parseCsv(csv);',
          '',
          '  return `${records.length} rows totalling ${sumField(records, "amount")}`;',
          '}',
          '',
          'const csv = "name,amount\\nada,10\\nbo,25";',
          '',
          'console.log("mixed   :", summariseMixed(csv));',
          'console.log("levelled:", summarise(csv));',
          'console.log("records :", parseCsv(csv));',
        ].join('\n'),
        output: [
          'mixed   : 2 rows totalling 35',
          'levelled: 2 rows totalling 35',
          'records : [{name: "ada", amount: "10"}, {name: "bo", amount: "25"}]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`summarise` now reads at one level: parse, sum, format. The splitting and index-hunting live one level down, where a reader only goes if they care.',
          'That is the practical meaning of "single level of abstraction" — a function should not mix *what* is being done with the details of *how*. The mixed version forces you to context-switch between the two on adjacent lines.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Parameters',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Too many parameters, and the options object.',
        code: [
          '"use strict";',
          '',
          '// Callers cannot read this, and the booleans are unguessable',
          'function createUserPositional(name, email, isAdmin, isVerified, sendWelcome) {',
          '  return { name, email, isAdmin, isVerified, sendWelcome };',
          '}',
          '',
          '// Named at the call site, order-independent, with defaults',
          'function createUser({ name, email, isAdmin = false, isVerified = false, sendWelcome = true }) {',
          '  return { name, email, isAdmin, isVerified, sendWelcome };',
          '}',
          '',
          'console.log("positional:", createUserPositional("Ada", "a@x.com", false, true, false));',
          '',
          'console.log("options   :", createUser({',
          '  name: "Ada",',
          '  email: "a@x.com",',
          '  isVerified: true,',
          '  sendWelcome: false,',
          '}));',
          '',
          '// Defaults mean callers state only what differs',
          'console.log("minimal   :", createUser({ name: "Bo", email: "b@x.com" }));',
        ].join('\n'),
        output: [
          'positional: {name: "Ada", email: "a@x.com", isAdmin: false, isVerified: true, sendWelcome: false}',
          'options   : {name: "Ada", email: "a@x.com", isAdmin: false, isVerified: true, sendWelcome: false}',
          'minimal   : {name: "Bo", email: "b@x.com", isAdmin: false, isVerified: false, sendWelcome: true}',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'Boolean parameters are the worst offenders',
        body: [
          '`createUserPositional("Ada", "a@x.com", false, true, false)` is unreadable at the call site — you must open the function to learn what each flag means, and swapping two of them is a silent bug.',
          'An options object fixes all of it: the call names each value, order stops mattering, and defaults let callers state only what differs.',
          'The threshold is roughly **three**. One or two positional parameters are clearer as positional; beyond that, especially with booleans or optional values, switch to an object. Note this is the same shape as the `fetch(url, options)` API from Module 26.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'function save(user, validate, notify, force) {',
          '  // ...',
          '}',
          '',
          'save(user, true, false, true);',
        ].join('\n'),
        options: [
          'The call site is unreadable — the three booleans cannot be interpreted without opening the function, and swapping any two is a silent bug',
          'It is fine — the parameter names are clear in the definition',
          'It will throw a TypeError',
          'The booleans should be strings instead',
        ],
        correct: 0,
        explanation:
          'The **definition** is readable; the **call site** is not, and that is where the code is actually read. `save(user, true, false, true)` gives a reader no way to know which flag is which, and transposing `validate` and `notify` produces a completely different behaviour with no error to catch it — the types match, so nothing detects the mistake. An options object fixes all three problems at once: `save(user, { validate: true, notify: false, force: true })` names each value at the point of use, makes order irrelevant, and allows defaults so callers state only what differs.',
      },
    ],
    exercises: [
      {
        id: 'ex-m40-02-a',
        title: 'Flatten with guard clauses',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['clean-code'],
        instructions:
          'Rewrite `getDiscount(user)` using guard clauses instead of nesting. It returns `0.3` for a premium member with over 100 points, `0.1` for any other member, and `0` for a non-member or a missing user.',
        starterCode: [
          '// Nested version:',
          '// function getDiscount(user) {',
          '//   if (user) { if (user.isMember) { if (user.tier === "premium") {',
          '//     if (user.points > 100) { return 0.3; } else { return 0.1; }',
          '//   } else { return 0.1; } } else { return 0; } } else { return 0; }',
          '// }',
          '',
          'function getDiscount(user) {',
          '  // Exit early on each failure; leave the main path flat.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'gives the premium discount', body: 'expect(getDiscount({ isMember: true, tier: "premium", points: 150 })).toBe(0.3);' },
          { name: 'gives the base discount to a low-points premium member', body: 'expect(getDiscount({ isMember: true, tier: "premium", points: 50 })).toBe(0.1);' },
          { name: 'gives the base discount to a standard member', body: 'expect(getDiscount({ isMember: true, tier: "standard", points: 500 })).toBe(0.1);' },
          { name: 'gives nothing to a non-member', body: 'expect(getDiscount({ isMember: false, tier: "premium", points: 500 })).toBe(0);' },
          { name: 'handles a missing user', body: 'expect(getDiscount(null)).toBe(0);' },
          { name: 'handles undefined', body: 'expect(getDiscount(undefined)).toBe(0);' },
          { name: 'treats exactly 100 points as base', body: 'expect(getDiscount({ isMember: true, tier: "premium", points: 100 })).toBe(0.1);', hidden: true },
        ],
        hints: [
          'Guard the missing user first, then the non-member.',
          'Then the non-premium case returns the base discount.',
          'Whatever survives every guard is a premium member — check the points last.',
        ],
        solution: [
          'const PREMIUM_POINTS_THRESHOLD = 100;',
          'const PREMIUM_DISCOUNT = 0.3;',
          'const MEMBER_DISCOUNT = 0.1;',
          '',
          'function getDiscount(user) {',
          '  if (!user) return 0;',
          '  if (!user.isMember) return 0;',
          '  if (user.tier !== "premium") return MEMBER_DISCOUNT;',
          '',
          '  return user.points > PREMIUM_POINTS_THRESHOLD ? PREMIUM_DISCOUNT : MEMBER_DISCOUNT;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Each guard removes one case and lets the reader forget it, so by the final line the only remaining possibility is a premium member and the code says exactly that. `!user` handles both `null` and `undefined` in one check. The hidden test pins the boundary: `>` rather than `>=` means exactly 100 points does **not** qualify, which is the kind of off-by-one the nested version made hard to see. Naming the thresholds turns the last line into the business rule rather than three unexplained numbers.',
      },
      {
        id: 'ex-m40-02-b',
        title: 'Split the responsibilities',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['clean-code'],
        instructions:
          'A single function validates, totals and formats. Split it into `validateCart(cart)` (returning a problem string or `null`), `cartTotal(items)` and `formatPrice(amount)`, plus a `summariseCart(cart)` that uses all three and returns the formatted total or the problem string.',
        starterCode: [
          'function validateCart(cart) {',
          '}',
          '',
          'function cartTotal(items) {',
          '}',
          '',
          'function formatPrice(amount) {',
          '}',
          '',
          'function summariseCart(cart) {',
          '}',
        ].join('\n'),
        tests: [
          { name: 'validates an empty cart', body: 'expect(validateCart({ items: [] })).toBe("empty cart");' },
          { name: 'accepts a valid cart', body: 'expect(validateCart({ items: [{ price: 1, quantity: 1 }] })).toBe(null);' },
          { name: 'totals price times quantity', body: 'expect(cartTotal([{ price: 10, quantity: 2 }, { price: 5, quantity: 3 }])).toBe(35);' },
          { name: 'totals an empty list as zero', body: 'expect(cartTotal([])).toBe(0);' },
          { name: 'formats to two decimals', body: 'expect(formatPrice(30)).toBe("$30.00");' },
          { name: 'summarises a valid cart', body: 'expect(summariseCart({ items: [{ price: 10, quantity: 2 }] })).toBe("$20.00");' },
          { name: 'summarises an invalid cart', body: 'expect(summariseCart({ items: [] })).toBe("empty cart");' },
          { name: 'each piece works independently', body: 'expect(formatPrice(cartTotal([{ price: 1.5, quantity: 2 }]))).toBe("$3.00");', hidden: true },
        ],
        hints: [
          '`validateCart` returns a string describing the problem, or `null` when fine.',
          '`cartTotal` uses `reduce` with an initial `0`.',
          '`summariseCart` calls validate first and returns the problem if there is one.',
        ],
        solution: [
          'function validateCart(cart) {',
          '  if (!cart.items || cart.items.length === 0) return "empty cart";',
          '',
          '  return null;',
          '}',
          '',
          'function cartTotal(items) {',
          '  return items.reduce((sum, item) => sum + item.price * item.quantity, 0);',
          '}',
          '',
          'function formatPrice(amount) {',
          '  return `$${amount.toFixed(2)}`;',
          '}',
          '',
          'function summariseCart(cart) {',
          '  const problem = validateCart(cart);',
          '',
          '  if (problem) return problem;',
          '',
          '  return formatPrice(cartTotal(cart.items));',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Each function now has **one reason to change**: validation rules, the totalling formula, the currency format, and the orchestration are four separate concerns that previously all lived in one place. The payoff is visible in the tests — three of them exercise a single function with plain values and no cart setup at all, and the hidden test composes two of them in a way the original monolith made impossible. `summariseCart` reads as a description of the process because every detail moved one level down.',
      },
      {
        id: 'ex-m40-02-c',
        title: 'Replace positional booleans',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['clean-code'],
        instructions:
          'Rewrite `formatDate(date, showTime, showYear, useShortMonth)` to take `(date, options)`. Default all three flags to `false`. Return an object `{ showTime, showYear, useShortMonth }` merged with the date\'s ISO string as `iso`, so the resolution is testable.',
        starterCode: [
          'function formatDate(date, options) {',
          '  // Destructure with defaults; return { iso, showTime, showYear, useShortMonth }.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'defaults every flag to false', body: 'expect(formatDate(new Date(0), {})).toEqual({ iso: "1970-01-01T00:00:00.000Z", showTime: false, showYear: false, useShortMonth: false });' },
          { name: 'honours one flag', body: 'expect(formatDate(new Date(0), { showTime: true }).showTime).toBe(true);' },
          { name: 'leaves the others defaulted', body: 'expect(formatDate(new Date(0), { showTime: true }).showYear).toBe(false);' },
          { name: 'order does not matter', body: 'expect(formatDate(new Date(0), { useShortMonth: true, showTime: true })).toEqual(formatDate(new Date(0), { showTime: true, useShortMonth: true }));' },
          { name: 'includes the iso string', body: 'expect(formatDate(new Date(0), {}).iso).toBe("1970-01-01T00:00:00.000Z");' },
          { name: 'works with no options argument', body: 'expect(formatDate(new Date(0)).showTime).toBe(false);' },
          { name: 'an explicit false stays false', body: 'expect(formatDate(new Date(0), { showTime: false }).showTime).toBe(false);', hidden: true },
        ],
        hints: [
          'Default the whole options object: `options = {}`.',
          'Destructure with defaults inside the parameter list or the body.',
          'Return the flags alongside `date.toISOString()`.',
        ],
        solution: [
          'function formatDate(date, options = {}) {',
          '  const {',
          '    showTime = false,',
          '    showYear = false,',
          '    useShortMonth = false,',
          '  } = options;',
          '',
          '  return {',
          '    iso: date.toISOString(),',
          '    showTime,',
          '    showYear,',
          '    useShortMonth,',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Destructuring with defaults means a caller states only what differs, and the fourth test shows the real win over positional arguments: **order stops mattering**, so transposing two flags is no longer a silent bug. Defaulting `options = {}` is what makes the sixth test pass — destructuring `undefined` would throw. The hidden test checks a subtlety of default values: they apply only for `undefined`, so an explicit `false` is respected rather than being overridden.',
      },
      {
        id: 'ex-m40-02-d',
        title: 'When is a long function acceptable?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['clean-code'],
        instructions:
          'A function is 40 lines long. What determines whether it should be split?',
        options: [
          'It should always be split — functions must be short',
          'Whether it has more than one reason to change; 40 cohesive lines doing one job are fine',
          'Whether it has more than three parameters',
          'Whether it contains a loop',
        ],
        correct: 1,
        hints: [
          'What would cause someone to edit this function?',
        ],
        solution: 'Whether it has more than one reason to change; 40 cohesive lines doing one job are fine',
        solutionExplanation:
          'Line-count rules produce worse code, because they force arbitrary splits that scatter one idea across several functions and leave the reader reassembling it. The useful test is **reasons to change**: a function that must be edited when validation rules change *and* when the currency format changes *and* when logging changes has three responsibilities regardless of its length. Conversely a long function implementing one algorithm cohesively is fine — a parser or a state machine may legitimately be long.',
      },
    ],
    quiz: {
      id: 'qz-m40-02',
      questions: [
        {
          id: 'q-m40-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['clean-code'],
          prompt: 'What does a guard clause achieve?',
          options: [
            'It runs faster',
            'It handles a failure case immediately, so the main path stays flat and last',
            'It removes the need for validation',
            'It prevents exceptions',
          ],
          correct: 1,
          optionExplanations: [
            'Performance is unchanged.',
            'Correct — each line is a complete thought.',
            'The validation is still there.',
            'Unrelated to exceptions.',
          ],
          explanation:
            'Each guard lets the reader discard a case and forget it, leaving the success path unindented and last — where the eye expects the answer.',
        },
        {
          id: 'q-m40-02-2',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['clean-code'],
          prompt: 'Every function should be under ten lines.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Arbitrary limits force bad splits.',
            'Correct — judge by reasons to change.',
          ],
          explanation:
            'Line limits scatter one idea across several functions. A cohesive 40-line function doing one job is better than four fragments the reader must reassemble.',
        },
        {
          id: 'q-m40-02-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['clean-code'],
          prompt: 'Why replace positional booleans with an options object?',
          options: [
            'Objects are faster',
            'The call site names each value, order stops mattering, and defaults let callers state only what differs',
            'Booleans are deprecated',
            'It reduces the function length',
          ],
          correct: 1,
          optionExplanations: [
            'Performance is not the reason.',
            'Correct — the call site is where code is read.',
            'Booleans are fine as values.',
            'Length is unchanged.',
          ],
          explanation:
            '`save(user, true, false, true)` is unreadable and transposing two flags is a silent bug, since the types match. Naming them at the call site fixes both.',
        },
        {
          id: 'q-m40-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['clean-code'],
          prompt: 'What does "one level of abstraction" mean?',
          options: [
            'Only one function per file',
            'A function should not mix what is being done with the details of how',
            'No nested functions',
            'Only one return statement',
          ],
          correct: 1,
          optionExplanations: [
            'File organisation is separate.',
            'Correct — details belong one level down.',
            'Nesting is unrelated.',
            'Guard clauses need several returns.',
          ],
          explanation:
            'A high-level step next to character-by-character parsing forces the reader to context-switch on adjacent lines. Push the details down so the top reads as a description of the process.',
        },
      ],
    },
    summary:
      '**Guard clauses** flatten nested conditionals by handling each failure immediately, so every line is a complete thought the reader can discard, and the success path ends up **unindented and last** — where the eye expects it. They are not universal: two genuinely balanced branches read better as `if`/`else`, and twelve guards in a row usually means validation deserves its own function. Judge a function by **reasons to change**, not line count — "under ten lines" forces arbitrary splits that scatter one idea, while a cohesive forty-line function doing one job is fine. Splitting a four-responsibility function into validate / calculate / format / orchestrate makes each piece testable **with plain values and no setup**, and passing collaborators like `report` **in** rather than reaching for module state is what makes the orchestrator testable too. Keep a function at **one level of abstraction**: mixing a high-level step with character-by-character detail forces a context switch on adjacent lines, so push the details one level down until the top function reads as a description of the process. For **parameters**, one or two positional arguments are clearer as positional; beyond roughly three — especially with booleans or optional values — use an **options object**, which names each value at the call site, makes order irrelevant, and supports defaults. `save(user, true, false, true)` is unreadable, and transposing two flags is a silent bug because the types match.',
    keyTakeaways: [
      'Guard clauses keep the main path flat and last',
      'They are not universal — balanced branches still read better as if/else',
      'Split by reasons to change, never by line count',
      'Pass collaborators in so the orchestrator stays testable',
      'Do not mix what is being done with the details of how',
      'Beyond three parameters, or any boolean flags, use an options object',
    ],
    relatedLessons: ['l-m40-01', 'l-m40-03'],
    interviewConnections: [
      'What is a guard clause and why use one?',
      'How do you decide whether a function is doing too much?',
      'Why are boolean parameters a problem?',
      'What does single level of abstraction mean?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m40-03',
    slug: 'principles-and-refactoring',
    moduleId: M,
    order: 3,
    title: 'Principles and Refactoring',
    description: 'DRY, KISS and YAGNI without dogma — and refactoring as behaviour-preserving change.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 18,
    xp: 45,
    topicIds: ['clean-code'],
    prerequisites: ['l-m40-02'],
    learningObjectives: [
      'Apply DRY to duplicated knowledge, not duplicated characters',
      'Recognise premature abstraction and over-engineering',
      'Separate concerns in a small application',
      'Refactor without changing observable behaviour',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'DRY — duplicated knowledge, not duplicated text',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'One of these duplications matters. The other does not.',
        code: [
          '"use strict";',
          '',
          '// REAL duplication: the same RULE stated twice.',
          '// Change the VAT rate and you must remember both.',
          'function invoiceTotalBad(amount) { return amount * 1.2; }',
          'function quoteTotalBad(amount) { return amount * 1.2; }',
          '',
          '// Extracted: one place to change',
          'const VAT_RATE = 0.2;',
          'function withVat(amount) { return amount * (1 + VAT_RATE); }',
          '',
          'function invoiceTotal(amount) { return withVat(amount); }',
          'function quoteTotal(amount) { return withVat(amount); }',
          '',
          '// COINCIDENTAL duplication: identical code, unrelated reasons.',
          '// A username length limit and a postcode length limit are',
          '// separate decisions that happen to share a number today.',
          'const MAX_USERNAME_LENGTH = 8;',
          'const MAX_POSTCODE_LENGTH = 8;',
          '',
          'function isValidUsername(value) { return value.length <= MAX_USERNAME_LENGTH; }',
          'function isValidPostcode(value) { return value.length <= MAX_POSTCODE_LENGTH; }',
          '',
          'console.log("invoice :", invoiceTotal(100));',
          'console.log("quote   :", quoteTotal(100));',
          'console.log("username:", isValidUsername("abcdefgh"), isValidUsername("abcdefghi"));',
          'console.log("postcode:", isValidPostcode("SW1A 1AA"));',
        ].join('\n'),
        output: [
          'invoice : 120',
          'quote   : 120',
          'username: true false',
          'postcode: true',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'DRY is about knowledge, not characters',
        body: [
          'The principle is that **every piece of knowledge should have one authoritative representation** — not that no two lines may look alike.',
          'The VAT rate is one piece of knowledge stated twice, so a change must be made in both places or the system becomes inconsistent. That is real duplication and worth extracting.',
          'The two length limits are **coincidentally identical**. Extracting a shared `MAX_LENGTH` would couple two unrelated decisions, so the day someone raises the username limit they either break postcodes or have to undo the abstraction. Note the fix is not to duplicate the literal `8` — it is to give each rule **its own named constant**.',
          'The question to ask is: *if this changes, must the other change too?* If yes, extract. If no, leave them apart.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'KISS and YAGNI',
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Over-engineered',
          code: [
            'class FormatterFactory {',
            '  static create(type) {',
            '    switch (type) {',
            '      case "currency":',
            '        return new',
            '          CurrencyFormatter();',
            '      default:',
            '        throw new Error(type);',
            '    }',
            '  }',
            '}',
            '',
            '// One formatter exists.',
          ].join('\n'),
        },
        right: {
          title: 'Adequate',
          code: [
            'function formatCurrency(',
            '  amount,',
            ') {',
            '  return `$${',
            '    amount.toFixed(2)',
            '  }`;',
            '}',
            '',
            '',
            '',
            '',
            '',
            '// Add a factory when',
            '// there are formatters',
            '// to choose between.',
          ].join('\n'),
        },
        note: 'The factory anticipates formatters that do not exist. It costs a file, a class hierarchy and an indirection today, in exchange for flexibility that may never be needed — and if a second formatter does arrive, its actual requirements will probably not match what was guessed. **YAGNI**: build it when you need it.',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Simple is not the same as simplistic',
        body: [
          '**KISS** means preferring the simplest solution that **actually satisfies the requirements** — including the error cases, the empty input, and the concurrent user. A solution that is simple because it ignores half the requirements is not simple, it is incomplete.',
          '**YAGNI** argues against building for hypothetical futures, not against thinking ahead. Choosing a data structure that will not collapse at scale is not speculation; adding a plugin system for the one plugin you have is.',
          'The honest tension: under-engineering is fixable, over-engineering is expensive to remove, and both are real failures. When genuinely unsure, prefer the simpler option — it is cheaper to add structure later than to unpick it.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Separating concerns',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        needsDom: true,
        html: '<div id="app"><ul id="list"></ul><p id="status"></p></div>',
        caption: 'A small feature with its layers tangled, then separated.',
        code: [
          '// BEFORE: fetching, business rules, formatting and DOM in one function',
          'function renderTasksBefore(rawTasks, container) {',
          '  const open = rawTasks.filter((t) => !t.done);',
          '  open.sort((a, b) => a.priority - b.priority);',
          '',
          '  container.innerHTML = "";',
          '',
          '  for (const task of open) {',
          '    const li = document.createElement("li");',
          '    li.textContent = `[P${task.priority}] ${task.title.toUpperCase()}`;',
          '    container.append(li);',
          '  }',
          '',
          '  return open.length;',
          '}',
          '',
          '// AFTER: three layers, each testable alone',
          '',
          '// 1. Business rules — pure',
          'function openTasksByPriority(tasks) {',
          '  return tasks.filter((task) => !task.done).sort((a, b) => a.priority - b.priority);',
          '}',
          '',
          '// 2. Formatting — pure',
          'function taskLabel(task) {',
          '  return `[P${task.priority}] ${task.title.toUpperCase()}`;',
          '}',
          '',
          '// 3. DOM — the only part that touches the page',
          'function renderList(container, labels) {',
          '  container.replaceChildren(',
          '    ...labels.map((label) => {',
          '      const li = document.createElement("li");',
          '      li.textContent = label;',
          '      return li;',
          '    }),',
          '  );',
          '}',
          '',
          'const tasks = [',
          '  { title: "write", priority: 2, done: false },',
          '  { title: "ship", priority: 1, done: false },',
          '  { title: "old", priority: 3, done: true },',
          '];',
          '',
          '// The rules and formatting need no DOM at all',
          'console.log("rules    :", openTasksByPriority(tasks).map((t) => t.title));',
          'console.log("format   :", taskLabel(tasks[1]));',
          '',
          'const list = document.getElementById("list");',
          'renderList(list, openTasksByPriority(tasks).map(taskLabel));',
          '',
          'console.log("rendered :", list.children.length);',
          'console.log("first    :", list.children[0].textContent);',
        ].join('\n'),
        output: [
          'rules    : ["ship", "write"]',
          'format   : [P1] SHIP',
          'rendered : 2',
          'first    : [P1] SHIP',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The layers can now be tested and changed independently',
        body: [
          'Two of the three functions are **pure** (Module 37) and need no DOM whatsoever — the first two log lines prove it. Changing the sort order, or the label format, is now a change in one small function with an obvious test.',
          '`renderList` knows nothing about tasks. It takes strings and produces list items, so it works for any list and cannot be broken by a change to the business rules.',
          'Note `replaceChildren` rather than `innerHTML = ""` followed by appends: it is a single operation, it does not reparse HTML, and it avoids the injection risk Module 44 covers.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Refactoring',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Refactoring means behaviour does not change',
        body: [
          'Refactoring is **changing the structure of code without changing its observable behaviour**. If the output differs, you did not refactor — you rewrote, and the two need very different amounts of care.',
          'This is why tests come **first**. Without them you cannot know whether a restructuring preserved behaviour, and "it looks equivalent" is exactly the reasoning that introduces bugs.',
          'The discipline: get it under test, make one structural change, run the tests, repeat. Not: rewrite everything and hope.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A refactor in steps, with behaviour pinned at each stage.',
        code: [
          '"use strict";',
          '',
          '// The original — works, but tangled',
          'function summariseOriginal(orders) {',
          '  let s = "";',
          '  let t = 0;',
          '',
          '  for (let i = 0; i < orders.length; i++) {',
          '    if (orders[i].status === "paid") {',
          '      t = t + orders[i].amount;',
          '      s = s + orders[i].id + ",";',
          '    }',
          '  }',
          '',
          '  if (s.length > 0) s = s.substring(0, s.length - 1);',
          '',
          '  return s + "|" + t;',
          '}',
          '',
          '// The refactored version — same behaviour, clearer structure',
          'function paidOrders(orders) {',
          '  return orders.filter((order) => order.status === "paid");',
          '}',
          '',
          'function summarise(orders) {',
          '  const paid = paidOrders(orders);',
          '  const ids = paid.map((order) => order.id).join(",");',
          '  const total = paid.reduce((sum, order) => sum + order.amount, 0);',
          '',
          '  return `${ids}|${total}`;',
          '}',
          '',
          '// Pin the behaviour across every case that matters',
          'const cases = [',
          '  [],',
          '  [{ id: "a", status: "paid", amount: 10 }],',
          '  [{ id: "a", status: "paid", amount: 10 }, { id: "b", status: "pending", amount: 5 }],',
          '  [{ id: "a", status: "pending", amount: 5 }],',
          '  [{ id: "a", status: "paid", amount: 0 }],',
          '];',
          '',
          'for (const orders of cases) {',
          '  const before = summariseOriginal(orders);',
          '  const after = summarise(orders);',
          '',
          '  console.log(`${after.padEnd(8)} match: ${before === after}`);',
          '}',
        ].join('\n'),
        output: [
          '|0       match: true',
          'a|10     match: true',
          'a|10     match: true',
          '|0       match: true',
          'a|0      match: true',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Comparing the two implementations across every case is the cheapest possible safety net, and it caught the detail that matters: the original produces `"|0"` for an empty list, not `""`. A rewrite that "cleaned that up" would have changed behaviour that something downstream may depend on.',
          'Notice also that the `substring` trailing-comma trick disappeared entirely — `join(",")` never adds one. That is the usual experience: restructuring removes whole categories of code rather than tidying them.',
        ],
      },
      {
        kind: SECTION.LIST,
        items: [
          '**Smell: a comment explaining a block.** Extract the block into a function named after the comment.',
          '**Smell: a long parameter list.** Group related parameters into an options object, or pass the whole object the caller already has.',
          '**Smell: the same conditional repeated.** Extract it into a well-named predicate, or reconsider the data shape.',
          '**Smell: deep nesting.** Guard clauses, then extraction.',
          '**Smell: a function you cannot name.** It probably does several things — the difficulty naming it *is* the diagnosis.',
          '**Smell: shotgun surgery.** One conceptual change requiring edits in six files means the knowledge is scattered.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Controlled mutation is fine',
        body: [
          'Module 37 made the distinction: mutating a **local** value nobody outside can observe is not a side effect. Building a result array with `push` inside a function is clear, fast and pure by the definition that matters.',
          'What causes bugs is **unexpected shared-state mutation** — changing a caller\'s argument, or a module-level object that other code holds. That is the thing to avoid, not the `let` keyword.',
          'So do not rewrite every loop into a `reduce` in the name of cleanliness. Choose whichever expresses the intent more directly, and keep mutation local.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// Two functions currently share an identical line:',
          '',
          'function isValidUsername(v) { return v.length <= 8; }',
          'function isValidPostcode(v) { return v.length <= 8; }',
          '',
          '// Should you extract a shared helper?',
        ].join('\n'),
        options: [
          'No — they are coincidentally identical; give each its own named constant instead',
          'Yes — DRY requires removing all duplication',
          'Yes — extract `isValidLength(v)`',
          'No — but duplicate the literal 8 in both',
        ],
        correct: 0,
        explanation:
          'The two rules are **unrelated decisions that happen to share a number today**. Extracting a shared helper couples them, so the day someone raises the username limit they either silently break postcode validation or have to undo the abstraction — and the second outcome is the *good* one. DRY concerns **duplicated knowledge**, not duplicated characters: ask *if this changes, must the other change too?* Here the answer is no. But note the fix is not to leave a bare `8` in each function either — give each rule **its own named constant**, so the two limits are independently adjustable and each says what it means.',
      },
    ],
    exercises: [
      {
        id: 'ex-m40-03-a',
        title: 'Real or coincidental duplication?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['clean-code'],
        instructions:
          'Which duplication genuinely warrants extraction?',
        options: [
          'Two unrelated validators that both happen to check `length <= 8`',
          'The VAT rate 1.2 appearing in an invoice calculation and a quote calculation',
          'Two functions that both start with a `for` loop',
          'Two components that both render a `<div>`',
        ],
        correct: 1,
        hints: [
          'If one changes, must the other change too?',
        ],
        solution: 'The VAT rate 1.2 appearing in an invoice calculation and a quote calculation',
        solutionExplanation:
          'The VAT rate is a **single piece of knowledge** stated in two places, so a rate change must be applied to both or the system becomes inconsistent — that is real duplication and worth one authoritative definition. The two validators are **coincidentally** identical: their limits are separate decisions that share a number today, and coupling them means raising one silently breaks the other. Sharing a loop keyword or an element type is duplicated syntax, not duplicated knowledge. The test is always: *if this changes, must the other change too?*',
      },
      {
        id: 'ex-m40-03-b',
        title: 'Refactor without changing behaviour',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['clean-code'],
        instructions:
          'Rewrite `summarise(orders)` clearly. It must return `"<comma-separated paid ids>|<total>"`, preserving the existing behaviour exactly — including returning `"|0"` for an empty list.',
        starterCode: [
          '// Original behaviour to preserve:',
          '//   let s = ""; let t = 0;',
          '//   for (let i = 0; i < orders.length; i++) {',
          '//     if (orders[i].status === "paid") { t += orders[i].amount; s += orders[i].id + ","; }',
          '//   }',
          '//   if (s.length > 0) s = s.substring(0, s.length - 1);',
          '//   return s + "|" + t;',
          '',
          'function summarise(orders) {',
          '}',
        ].join('\n'),
        tests: [
          { name: 'summarises one paid order', body: 'expect(summarise([{ id: "a", status: "paid", amount: 10 }])).toBe("a|10");' },
          { name: 'ignores unpaid orders', body: 'expect(summarise([{ id: "a", status: "paid", amount: 10 }, { id: "b", status: "pending", amount: 5 }])).toBe("a|10");' },
          { name: 'joins several ids', body: 'expect(summarise([{ id: "a", status: "paid", amount: 1 }, { id: "b", status: "paid", amount: 2 }])).toBe("a,b|3");' },
          { name: 'returns "|0" for an empty list', body: 'expect(summarise([])).toBe("|0");' },
          { name: 'returns "|0" when nothing is paid', body: 'expect(summarise([{ id: "a", status: "pending", amount: 5 }])).toBe("|0");' },
          { name: 'handles a zero amount', body: 'expect(summarise([{ id: "a", status: "paid", amount: 0 }])).toBe("a|0");' },
          { name: 'does not mutate the input', body: 'const o = [{ id: "a", status: "paid", amount: 1 }]; summarise(o); expect(o.length).toBe(1);' },
          { name: 'adds no trailing comma', body: 'expect(summarise([{ id: "a", status: "paid", amount: 1 }]).includes(",|")).toBe(false);', hidden: true },
        ],
        hints: [
          '`filter` for paid orders, then `map` and `join(",")` for the ids.',
          '`reduce` with an initial `0` for the total.',
          '`join` on an empty array gives `""`, which preserves the `"|0"` behaviour.',
        ],
        solution: [
          'function summarise(orders) {',
          '  const paid = orders.filter((order) => order.status === "paid");',
          '',
          '  const ids = paid.map((order) => order.id).join(",");',
          '  const total = paid.reduce((sum, order) => sum + order.amount, 0);',
          '',
          '  return `${ids}|${total}`;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The fourth and fifth tests are the point of the exercise: `"|0"` looks like a bug worth "fixing", but changing it would alter behaviour something downstream may rely on — and that would be a rewrite, not a refactor. `join(",")` on an empty array returns `""`, which reproduces the original exactly and also eliminates the trailing-comma `substring` trick entirely (hidden test). That is the usual experience of refactoring: restructuring removes whole categories of code rather than tidying them.',
      },
      {
        id: 'ex-m40-03-c',
        title: 'Separate the layers',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['clean-code'],
        instructions:
          'Split a tangled report function into `activeUsers(users)` (not deleted, sorted by name), `userLabel(user)` (returning `"<name> (<email>)"`), and `buildReport(users)` returning an array of labels for active users.',
        starterCode: [
          'function activeUsers(users) {',
          '}',
          '',
          'function userLabel(user) {',
          '}',
          '',
          'function buildReport(users) {',
          '}',
        ].join('\n'),
        tests: [
          { name: 'filters deleted users', body: 'expect(activeUsers([{ name: "a", deleted: true }, { name: "b", deleted: false }]).map((u) => u.name)).toEqual(["b"]);' },
          { name: 'sorts by name', body: 'expect(activeUsers([{ name: "c", deleted: false }, { name: "a", deleted: false }]).map((u) => u.name)).toEqual(["a", "c"]);' },
          { name: 'formats a label', body: 'expect(userLabel({ name: "Ada", email: "a@x.com" })).toBe("Ada (a@x.com)");' },
          { name: 'builds the report', body: 'expect(buildReport([{ name: "Bo", email: "b@x.com", deleted: false }])).toEqual(["Bo (b@x.com)"]);' },
          { name: 'excludes deleted users from the report', body: 'expect(buildReport([{ name: "Bo", email: "b@x.com", deleted: true }])).toEqual([]);' },
          { name: 'handles an empty list', body: 'expect(buildReport([])).toEqual([]);' },
          { name: 'does not mutate the input order', body: 'const u = [{ name: "c", deleted: false }, { name: "a", deleted: false }]; activeUsers(u); expect(u[0].name).toBe("c");' },
          { name: 'the pieces compose', body: 'expect(activeUsers([{ name: "z", email: "z@x", deleted: false }]).map(userLabel)).toEqual(["z (z@x)"]);', hidden: true },
        ],
        hints: [
          '`filter` then `sort` — but sort a copy, since sort mutates.',
          '`localeCompare` compares names properly.',
          '`buildReport` is just `activeUsers(...).map(userLabel)`.',
        ],
        solution: [
          'function activeUsers(users) {',
          '  return users',
          '    .filter((user) => !user.deleted)',
          '    .sort((a, b) => a.name.localeCompare(b.name));',
          '}',
          '',
          'function userLabel(user) {',
          '  return `${user.name} (${user.email})`;',
          '}',
          '',
          'function buildReport(users) {',
          '  return activeUsers(users).map(userLabel);',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`filter` returns a **new** array, so the subsequent `sort` mutates that copy rather than the caller\'s input — which is what the seventh test checks, and why the order of the two calls matters. Each function is independently testable with plain values, and `buildReport` reads as a description of the process because both details moved one level down. The hidden test shows the real payoff: because `userLabel` takes a single user, it can be passed **directly** to `map` with no wrapper — the unary-function benefit from Module 37.',
      },
      {
        id: 'ex-m40-03-d',
        title: 'What is refactoring?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['clean-code'],
        instructions:
          'You restructure a function and also fix an edge case that returned the wrong value. What did you do?',
        options: [
          'Refactored it',
          'Both refactored and changed behaviour — those are two separate changes and should be done and reviewed separately',
          'Nothing significant',
          'Optimised it',
        ],
        correct: 1,
        hints: [
          'Does refactoring change what the function returns?',
        ],
        solution: 'Both refactored and changed behaviour — those are two separate changes and should be done and reviewed separately',
        solutionExplanation:
          'Refactoring means changing **structure** while **observable behaviour stays identical** — that is precisely what makes it safe, and what lets tests verify it. Mixing a behaviour fix into a restructuring destroys that guarantee: when the tests change too, they can no longer tell you whether the restructuring was faithful, and a reviewer cannot separate the intentional change from an accidental one. Do the behaviour fix in one commit and the restructuring in another, so each can be checked on its own terms.',
      },
    ],
    quiz: {
      id: 'qz-m40-03',
      questions: [
        {
          id: 'q-m40-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['clean-code'],
          prompt: 'What does DRY actually target?',
          options: [
            'Any two identical lines',
            'Duplicated knowledge — a single fact represented in more than one place',
            'Long functions',
            'Repeated variable names',
          ],
          correct: 1,
          optionExplanations: [
            'Coincidental duplication should stay.',
            'Correct — ask whether both must change together.',
            'Length is a separate concern.',
            'Names are unrelated.',
          ],
          explanation:
            'If one copy changes, must the other? If yes, extract. If they are coincidentally identical, coupling them creates a worse problem than the duplication.',
        },
        {
          id: 'q-m40-03-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['clean-code'],
          prompt: 'What does YAGNI argue against?',
          options: [
            'Writing tests',
            'Building complexity for hypothetical future requirements with no evidence',
            'Using classes',
            'Thinking about design at all',
          ],
          correct: 1,
          optionExplanations: [
            'Tests are present-tense value.',
            'Correct — build it when you need it.',
            'Classes are fine when warranted.',
            'It is about speculation, not design.',
          ],
          explanation:
            'A factory for one implementation costs indirection today for flexibility that may never arrive — and if it does, the real requirements rarely match what was guessed.',
        },
        {
          id: 'q-m40-03-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['clean-code'],
          prompt: 'Refactoring may change a function\'s observable behaviour if the new behaviour is better.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'That is a rewrite, not a refactor.',
            'Correct — behaviour must stay identical.',
          ],
          explanation:
            'Preserved behaviour is what makes refactoring safe and testable. A behaviour change is a separate concern and belongs in its own commit.',
        },
        {
          id: 'q-m40-03-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['clean-code'],
          prompt: 'Which kind of mutation is genuinely a problem?',
          options: [
            'Any use of let',
            'Mutating a caller\'s argument or shared module state, which other code can observe',
            'push into a local array',
            'Reassigning a loop counter',
          ],
          correct: 1,
          optionExplanations: [
            '`let` is fine.',
            'Correct — unexpected shared-state change.',
            'Local and invisible outside.',
            'Entirely normal.',
          ],
          explanation:
            'Local mutation nobody can observe is not a side effect (Module 37). The hazard is changing state a caller holds, which produces action at a distance.',
        },
      ],
    },
    summary:
      '**DRY targets duplicated knowledge, not duplicated characters.** A VAT rate written twice is one fact in two places — extract it. Two validators that coincidentally both check `length <= 8` are unrelated decisions sharing a number, so coupling them means raising one silently breaks the other; give each **its own named constant** instead. The test is: *if this changes, must the other change too?* **KISS** means the simplest solution that actually satisfies the requirements — a solution that is simple because it ignores the error cases is incomplete, not simple. **YAGNI** argues against building for hypothetical futures, not against thinking ahead: a factory for one implementation costs indirection now for flexibility that may never arrive, and under-engineering is far cheaper to fix than over-engineering is to unpick. **Separating concerns** into business rules, formatting and DOM makes two of the three **pure** and testable without any DOM, and leaves the render function reusable because it knows nothing about the domain. **Refactoring means changing structure while observable behaviour stays identical** — if the output differs you rewrote, which needs different care. That is why tests come first, why a surprising result like `"|0"` for an empty list must be **preserved** rather than tidied, and why a behaviour fix belongs in a separate commit. Finally, **controlled local mutation is fine**; the hazard is mutating a caller\'s argument or shared module state.',
    keyTakeaways: [
      'DRY applies to duplicated knowledge — coincidental duplication should stay apart',
      'Give unrelated rules their own named constants rather than a shared one',
      'Simple means adequate, not incomplete; YAGNI targets speculation, not design',
      'Separating layers makes business rules and formatting pure and testable',
      'Refactoring preserves observable behaviour — including surprising behaviour',
      'Local mutation is fine; mutating a caller\'s state is not',
    ],
    relatedLessons: ['l-m40-02', 'l-m40-01'],
    interviewConnections: [
      'What does DRY really mean, and when should you not apply it?',
      'What is the difference between refactoring and rewriting?',
      'How would you separate concerns in this function?',
      'When is duplication better than abstraction?',
    ],
  },
];
