import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm42';

export default [
  /* ================================================================== */
  {
    id: 'l-m42-01',
    slug: 'why-and-how-to-test',
    moduleId: M,
    order: 1,
    title: 'Why and How to Test',
    description: 'What tests actually buy you, the anatomy of one, and choosing cases that earn their place.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 17,
    xp: 45,
    topicIds: ['testing'],
    prerequisites: ['l-m41-03'],
    learningObjectives: [
      'State honestly what automated tests do and do not prove',
      'Write a test with a clear arrange, act and assert structure',
      'Choose test cases that cover boundaries rather than repeating one path',
      'Explain the trade-offs between unit, integration and end-to-end tests',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'What tests are for',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Tests increase confidence; they do not prove correctness',
        body: [
          'A passing suite means **the cases you thought of behave as you expected**. It says nothing about the cases you did not think of, which is where most bugs live.',
          'So "100% coverage means no bugs" is false, and believing it is worse than having no tests, because it replaces judgement with a number. Coverage measures which **lines ran**, not whether the assertions were meaningful — a test that executes a function and asserts nothing counts fully covered.',
          'What tests genuinely buy: **confidence to change code**. Refactoring (Module 40) is only safe when something can tell you behaviour was preserved, and that is the single largest return on the effort.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The anatomy of a test.',
        code: [
          '"use strict";',
          '',
          '// In a real project you would import these from your test runner:',
          '//   import { describe, it, expect } from "vitest";',
          '// Here they are modelled so the structure is visible and runnable.',
          '',
          'function createRunner() {',
          '  const results = [];',
          '',
          '  function expect(actual) {',
          '    return {',
          '      toBe(want) {',
          '        if (!Object.is(actual, want)) throw new Error(`expected ${want}, got ${actual}`);',
          '      },',
          '    };',
          '  }',
          '',
          '  function it(name, fn) {',
          '    try {',
          '      fn();',
          '      results.push(`PASS ${name}`);',
          '    } catch (error) {',
          '      results.push(`FAIL ${name}: ${error.message}`);',
          '    }',
          '  }',
          '',
          '  return { it, expect, results };',
          '}',
          '',
          'const { it, expect, results } = createRunner();',
          '',
          '// The code under test',
          'function add(a, b) { return a + b; }',
          '',
          '// A test: a NAME describing the behaviour, and an assertion',
          'it("adds two positive numbers", () => {',
          '  expect(add(2, 3)).toBe(5);',
          '});',
          '',
          'it("handles negatives", () => {',
          '  expect(add(-2, 3)).toBe(1);',
          '});',
          '',
          'it("catches a wrong expectation", () => {',
          '  expect(add(2, 2)).toBe(5);',
          '});',
          '',
          'results.forEach((line) => console.log(line));',
        ].join('\n'),
        output: [
          'PASS adds two positive numbers',
          'PASS handles negatives',
          'FAIL catches a wrong expectation: expected 5, got 4',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'That is the whole mechanism: a function that throws on a failed comparison, and a wrapper that catches the throw and records it. Every test framework is a more polished version of this.',
          'Real projects use a runner such as **Vitest** or **Jest**, which add file discovery, watch mode, parallelism, better failure output and a large matcher library. The concepts are identical.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        caption: 'The same tests as you would actually write them — illustrative.',
        code: [
          'import { describe, it, expect } from "vitest";',
          'import { add } from "./math.js";',
          '',
          'describe("add", () => {',
          '  it("adds two positive numbers", () => {',
          '    expect(add(2, 3)).toBe(5);',
          '  });',
          '',
          '  it("handles negatives", () => {',
          '    expect(add(-2, 3)).toBe(1);',
          '  });',
          '',
          '  it("returns the other operand when one is zero", () => {',
          '    expect(add(0, 7)).toBe(7);',
          '  });',
          '});',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The test name is documentation',
        body: [
          '`it("adds two positive numbers")` describes a **behaviour**. `it("test 1")` or `it("works")` describes nothing, and when it fails you learn only that something broke.',
          'A good name completes the sentence "it ...", states the condition and the expected outcome, and would still make sense to someone who has not read the implementation.',
          '`describe` groups related tests, which keeps failure output readable — `add > handles negatives` locates the problem immediately.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Arrange, act, assert',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Three phases, usually without needing labels.',
        code: [
          '"use strict";',
          '',
          'function createCart() {',
          '  const items = [];',
          '',
          '  return {',
          '    add(item) { items.push(item); },',
          '    total() { return items.reduce((sum, i) => sum + i.price * i.quantity, 0); },',
          '    get count() { return items.length; },',
          '  };',
          '}',
          '',
          '// ARRANGE: set up the world the test needs',
          'const cart = createCart();',
          'cart.add({ price: 10, quantity: 2 });',
          'cart.add({ price: 5, quantity: 1 });',
          '',
          '// ACT: perform the one thing under test',
          'const total = cart.total();',
          '',
          '// ASSERT: check the outcome',
          'console.log("total is 25 :", total === 25);',
          'console.log("count is 2  :", cart.count === 2);',
          '',
          '// A test with an empty arrange phase is perfectly normal',
          'console.log("empty total :", createCart().total() === 0);',
        ].join('\n'),
        output: [
          'total is 25 : true',
          'count is 2  : true',
          'empty total : true',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'The structure is a habit, not a ritual',
        body: [
          'Writing `// Arrange` / `// Act` / `// Assert` above every three-line test is noise — the structure is already visible. The value is in **noticing when a test has no clear act phase**, or two of them.',
          'Two act phases usually means the test is checking two behaviours and should be split, so a failure tells you which one broke.',
          'A very long arrange phase is a design signal: if a function needs elaborate setup to test, it probably has too many dependencies — which is Module 40\'s point about separating concerns, arriving from the testing side.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Choosing cases',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Cases that find bugs, and cases that only add count.',
        code: [
          '"use strict";',
          '',
          'function applyDiscount(total, percent) {',
          '  if (typeof total !== "number" || total < 0) throw new RangeError("invalid total");',
          '  if (percent < 0 || percent > 100) throw new RangeError("invalid percent");',
          '',
          '  return total * (1 - percent / 100);',
          '}',
          '',
          '// WEAK: five tests exercising the identical path',
          'const weak = [',
          '  applyDiscount(100, 10) === 90,',
          '  applyDiscount(200, 10) === 180,',
          '  applyDiscount(300, 10) === 270,',
          '];',
          '',
          'console.log("weak all pass:", weak.every(Boolean), "| cases:", weak.length);',
          '',
          '// STRONG: boundaries, edges and error paths',
          'const checks = {',
          '  "typical": applyDiscount(100, 10) === 90,',
          '  "zero percent": applyDiscount(100, 0) === 100,',
          '  "full discount": applyDiscount(100, 100) === 0,',
          '  "zero total": applyDiscount(0, 50) === 0,',
          '  "rejects negative percent": (() => {',
          '    try { applyDiscount(100, -1); return false; } catch { return true; }',
          '  })(),',
          '  "rejects percent over 100": (() => {',
          '    try { applyDiscount(100, 101); return false; } catch { return true; }',
          '  })(),',
          '  "rejects negative total": (() => {',
          '    try { applyDiscount(-1, 10); return false; } catch { return true; }',
          '  })(),',
          '};',
          '',
          'for (const [name, passed] of Object.entries(checks)) {',
          '  console.log(`${passed ? "PASS" : "FAIL"} ${name}`);',
          '}',
        ].join('\n'),
        output: [
          'weak all pass: true | cases: 3',
          'PASS typical',
          'PASS zero percent',
          'PASS full discount',
          'PASS zero total',
          'PASS rejects negative percent',
          'PASS rejects percent over 100',
          'PASS rejects negative total',
        ].join('\n'),
      },
      {
        kind: SECTION.LIST,
        items: [
          '**The typical case.** One is usually enough — three variations of the same path find the same bugs.',
          '**Boundaries.** `0`, `100`, exactly at a threshold, one either side. Off-by-one errors live here, as Module 39\'s binary search showed.',
          '**Empty and single.** An empty array, an empty string, a one-element collection. These break naive implementations constantly.',
          '**Error paths.** If the function documents that it throws, test that it does — otherwise the guard can be deleted and nothing notices.',
          '**Falsy values.** `0`, `""`, `false` and `null` where a truthiness check might wrongly reject them.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Unit, integration, end-to-end',
      },
      {
        kind: SECTION.TABLE,
        headers: ['', 'Unit', 'Integration', 'End-to-end'],
        rows: [
          ['Scope', 'One function or module', 'Several pieces together', 'The whole application in a browser'],
          ['Speed', '**Milliseconds**', 'Fast to moderate', 'Seconds to minutes'],
          ['Failure clarity', '**Points at one function**', 'Points at an interaction', 'Says something broke somewhere'],
          ['Confidence it works for users', 'Low on its own', 'Moderate', '**Highest**'],
          ['Brittleness', 'Low', 'Moderate', '**High** — timing, selectors, environment'],
          ['Typical proportion', 'Many', 'Some', 'A few critical journeys'],
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A unit test and an integration test of the same feature.',
        code: [
          '"use strict";',
          '',
          '// Pure business rules — the UNIT',
          'function validateSignup({ email, password }) {',
          '  const problems = [];',
          '',
          '  if (!email.includes("@")) problems.push("email invalid");',
          '  if (password.length < 8) problems.push("password too short");',
          '',
          '  return problems;',
          '}',
          '',
          '// A service that composes the rule with a dependency — the INTEGRATION',
          'function createSignupService({ save }) {',
          '  return {',
          '    submit(form) {',
          '      const problems = validateSignup(form);',
          '',
          '      if (problems.length > 0) return { ok: false, problems };',
          '',
          '      const id = save(form);',
          '      return { ok: true, id };',
          '    },',
          '  };',
          '}',
          '',
          '// UNIT: no dependencies, no setup',
          'console.log("unit valid   :", validateSignup({ email: "a@x.com", password: "longenough" }));',
          'console.log("unit invalid :", validateSignup({ email: "nope", password: "short" }));',
          '',
          '// INTEGRATION: real rule, fake persistence',
          'const saved = [];',
          'const service = createSignupService({ save: (form) => { saved.push(form); return saved.length; } });',
          '',
          'console.log("service ok   :", service.submit({ email: "a@x.com", password: "longenough" }));',
          'console.log("service bad  :", service.submit({ email: "nope", password: "x" }));',
          'console.log("saved once   :", saved.length);',
        ].join('\n'),
        output: [
          'unit valid   : []',
          'unit invalid : ["email invalid", "password too short"]',
          'service ok   : {ok: true, id: 1}',
          'service bad  : {ok: false, problems: ["email invalid", "password too short"]}',
          'saved once   : 1',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Where end-to-end fits',
        body: [
          'An **end-to-end** test drives a real browser — clicking, typing, waiting for navigation — with tools such as **Playwright** or **Cypress**. It is the only kind that proves the whole system works for an actual user.',
          'It is also the slowest and most brittle: a changed selector, a slow network, or an animation can fail a test for reasons unrelated to the code. So keep a handful covering the **critical journeys** (sign up, check out, the core workflow) rather than testing every branch that way.',
          'The usual shape is many fast unit tests, a solid layer of integration tests around the seams, and a few end-to-end tests. Note the integration test above needed **no framework at all** — the dependency was passed in, so a plain function served as the fake.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'function parseAge(input) {',
          '  const n = Number(input);',
          '  if (Number.isNaN(n)) return null;',
          '  return n;',
          '}',
          '',
          '// The suite contains only:',
          '//   expect(parseAge("30")).toBe(30);',
          '//   expect(parseAge("45")).toBe(45);',
          '//   expect(parseAge("7")).toBe(7);',
          '// Line coverage reports 100%. What is untested?',
        ].join('\n'),
        options: [
          'The null path, empty string, whitespace, negatives and non-numeric input — coverage counts lines executed, not cases considered',
          'Nothing — 100% coverage means it is fully tested',
          'Only performance',
          'Only the return type',
        ],
        correct: 0,
        explanation:
          'Three tests of the same path do not become three times as valuable. The `null` branch never runs, so deleting it would not fail a single test; and several genuinely surprising cases are unexamined — `Number("")` is **0**, `Number(" ")` is **0**, and `Number(null)` is **0**, so an empty form field silently produces an age of zero rather than the `null` the function seems to promise. Note coverage would *still* not reach 100% here in branch terms, but line coverage can, which is exactly why the number misleads: it measures which lines **ran**, never whether the cases that matter were considered.',
      },
    ],
    exercises: [
      {
        id: 'ex-m42-01-a',
        title: 'What does a passing suite prove?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['testing'],
        instructions:
          'Your test suite passes with 100% line coverage. What does that establish?',
        options: [
          'The code has no bugs',
          'Every line executed and the cases you thought of behave as expected — nothing about cases you did not consider',
          'The code is well designed',
          'The code is fast enough',
        ],
        correct: 1,
        hints: [
          'What does coverage actually measure?',
        ],
        solution: 'Every line executed and the cases you thought of behave as expected — nothing about cases you did not consider',
        solutionExplanation:
          'Coverage measures which **lines ran**, not whether the assertions were meaningful — a test that calls a function and asserts nothing counts as fully covered. Most bugs live in cases nobody imagined, and no coverage number can reveal those. What a passing suite genuinely buys is **confidence to change code**: refactoring is only safe when something can tell you behaviour was preserved, which is the largest return on the effort.',
      },
      {
        id: 'ex-m42-01-b',
        title: 'Choose the test cases',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['testing'],
        instructions:
          'Write `describeCases(fn)` returning an object mapping case names to results, exercising `clamp(value, min, max)`. Cover the typical case, both boundaries, both out-of-range directions, and an inverted range where `min > max` (which should return `min`).',
        starterCode: [
          'function clamp(value, min, max) {',
          '  return Math.min(Math.max(value, min), max);',
          '}',
          '',
          'function describeCases(fn) {',
          '  // Return { typical, atMin, atMax, belowMin, aboveMax, inverted }',
          '}',
        ].join('\n'),
        tests: [
          { name: 'covers the typical case', body: 'expect(describeCases(clamp).typical).toBe(5);' },
          { name: 'covers the lower boundary', body: 'expect(describeCases(clamp).atMin).toBe(0);' },
          { name: 'covers the upper boundary', body: 'expect(describeCases(clamp).atMax).toBe(10);' },
          { name: 'covers below the range', body: 'expect(describeCases(clamp).belowMin).toBe(0);' },
          { name: 'covers above the range', body: 'expect(describeCases(clamp).aboveMax).toBe(10);' },
          { name: 'covers an inverted range', body: 'expect(describeCases(clamp).inverted).toBe(2);' },
          { name: 'reports six distinct cases', body: 'expect(Object.keys(describeCases(clamp)).length).toBe(6);', hidden: true },
        ],
        hints: [
          'Use a range of 0 to 10 throughout so the cases are comparable.',
          '`atMin` calls `fn(0, 0, 10)`; `belowMin` calls `fn(-5, 0, 10)`.',
          'For `inverted`, call `fn(1, 5, 2)` — with min above max.',
        ],
        solution: [
          'function clamp(value, min, max) {',
          '  return Math.min(Math.max(value, min), max);',
          '}',
          '',
          'function describeCases(fn) {',
          '  return {',
          '    typical: fn(5, 0, 10),',
          '    atMin: fn(0, 0, 10),',
          '    atMax: fn(10, 0, 10),',
          '    belowMin: fn(-5, 0, 10),',
          '    aboveMax: fn(99, 0, 10),',
          '    inverted: fn(1, 5, 2),',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The six cases each probe something different — one typical path, both **boundaries** (where off-by-one errors live), both out-of-range directions, and a degenerate input. Three variations of `typical` would have found nothing extra. The `inverted` case is the instructive one: `clamp(1, 5, 2)` returns **2**, not the `5` most people predict — `Math.max(1, 5)` gives `5`, and `Math.min(5, 2)` then clamps it back down to the *max*. With a contradictory range the upper bound silently wins. Writing the test is what forces you to discover and **document** that, and to decide whether it is acceptable, rather than meeting it in production.',
      },
      {
        id: 'ex-m42-01-c',
        title: 'Unit or integration?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['testing'],
        instructions:
          'You want to verify that submitting a form runs validation, calls the save function once, and returns the new id. What kind of test is that?',
        options: [
          'A unit test',
          'An integration test — it checks that several pieces work together',
          'An end-to-end test',
          'A performance test',
        ],
        correct: 1,
        hints: [
          'How many pieces are involved?',
        ],
        solution: 'An integration test — it checks that several pieces work together',
        solutionExplanation:
          'It exercises the interaction between validation, the service, and persistence — more than one unit, but far less than the whole application in a browser. A **unit** test would check `validateSignup` alone with no dependencies; an **end-to-end** test would drive a real browser through the actual form. Note that this integration test needs **no framework**: because the save dependency is passed in, a plain function serves as the fake, which is what Module 28\'s dependency inversion buys at testing time.',
      },
      {
        id: 'ex-m42-01-d',
        title: 'Improve the test name',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['testing'],
        instructions:
          'Which test name is most useful when it appears in a failure report?',
        options: [
          '`it("works")`',
          '`it("returns null when the input contains no digits")`',
          '`it("test parseAge 3")`',
          '`it("calls Number() on the input")`',
        ],
        correct: 1,
        hints: [
          'Which one tells you what broke without opening the file?',
        ],
        solution: '`it("returns null when the input contains no digits")`',
        solutionExplanation:
          'It states the **condition** and the **expected outcome**, so a failure immediately tells you which behaviour regressed without opening the test file. "works" and "test 3" describe nothing. The last option is subtly worse than it looks: it names an **implementation detail** rather than a behaviour, so renaming or replacing `Number()` would make the test name a lie even though the behaviour is unchanged — which is lesson 3\'s point about brittle tests.',
      },
    ],
    quiz: {
      id: 'qz-m42-01',
      questions: [
        {
          id: 'q-m42-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['testing'],
          prompt: 'What is the largest practical benefit of a test suite?',
          options: [
            'It proves the code is correct',
            'It gives you confidence to change code, which makes refactoring safe',
            'It replaces documentation entirely',
            'It guarantees performance',
          ],
          correct: 1,
          optionExplanations: [
            'It covers only the cases you thought of.',
            'Correct — behaviour preservation becomes checkable.',
            'Tests document behaviour but are not a substitute.',
            'Performance needs separate measurement.',
          ],
          explanation:
            'Refactoring means changing structure while behaviour stays identical (Module 40) — which is only verifiable if something checks the behaviour.',
        },
        {
          id: 'q-m42-01-2',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['testing'],
          prompt: '100% line coverage means every meaningful case has been tested.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Coverage counts lines run, not cases considered.',
            'Correct — a test asserting nothing still counts as covered.',
          ],
          explanation:
            'Coverage is a signal about what was **not** exercised. It cannot tell you whether the assertions were meaningful or whether the important inputs were considered.',
        },
        {
          id: 'q-m42-01-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['testing'],
          prompt: 'What does a very long arrange phase usually indicate?',
          options: [
            'A thorough test',
            'A design problem — the code under test has too many dependencies',
            'That mocks are needed',
            'Nothing in particular',
          ],
          correct: 1,
          optionExplanations: [
            'Length is not thoroughness.',
            'Correct — testability is a design signal.',
            'More mocks would make it worse.',
            'It is worth noticing.',
          ],
          explanation:
            'Elaborate setup means many collaborators. Separating concerns (Module 40) and passing dependencies in usually shrinks the arrange phase to almost nothing.',
        },
        {
          id: 'q-m42-01-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['testing'],
          prompt: 'Why keep end-to-end tests few?',
          options: [
            'They cannot find real bugs',
            'They are slow and brittle — selectors, timing and environment cause failures unrelated to the code',
            'They require a paid tool',
            'They only work on mobile',
          ],
          correct: 1,
          optionExplanations: [
            'They find the most realistic bugs.',
            'Correct — reserve them for critical journeys.',
            'Playwright and Cypress are free.',
            'They run anywhere.',
          ],
          explanation:
            'They give the highest confidence and the lowest failure clarity. Cover the critical journeys and push detailed branch checking down to faster tests.',
        },
      ],
    },
    summary:
      'Tests **increase confidence; they do not prove correctness** — a passing suite means the cases you thought of behave as expected, and says nothing about the ones you did not. **Coverage measures lines executed, not cases considered**, so a test that asserts nothing counts as fully covered and "100% means no bugs" is false. The genuine return is **confidence to change code**: refactoring is only safe when something verifies behaviour was preserved. A test is just a function that throws on a failed comparison plus a wrapper that catches it — real runners like **Vitest** and **Jest** add discovery, watch mode and better output, not new concepts. The **name is documentation**: state the condition and expected outcome so a failure is legible without opening the file, and avoid naming implementation details. **Arrange, act, assert** is a habit rather than a ritual — the value is noticing when a test has **two act phases** (split it) or a **very long arrange phase**, which signals too many dependencies. Choose cases that earn their place: one typical path, both **boundaries**, **empty and single**, documented **error paths**, and **falsy values** — three variations of the same path find the same bugs. Finally, prefer **many fast unit tests**, a solid layer of **integration** tests around the seams, and **a few end-to-end** tests for critical journeys, since those give the highest confidence and the lowest failure clarity.',
    keyTakeaways: [
      'Tests give confidence to change code; they do not prove correctness',
      'Coverage counts lines run, never whether assertions were meaningful',
      'A test name should state the condition and the expected outcome',
      'Two act phases means two tests; a long arrange phase is a design signal',
      'Test boundaries, empty cases and error paths — not the same path repeatedly',
      'Many unit tests, some integration tests, a few end-to-end journeys',
    ],
    relatedLessons: ['l-m42-02', 'l-m42-03'],
    interviewConnections: [
      'What do tests actually prove?',
      'Is 100% coverage a meaningful goal?',
      'What is the difference between unit, integration and end-to-end tests?',
      'How do you decide which test cases to write?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m42-02',
    slug: 'test-doubles-and-async',
    moduleId: M,
    order: 2,
    title: 'Test Doubles and Async Tests',
    description: 'Replacing dependencies deliberately, verifying calls, and testing asynchronous code without sleeping.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 18,
    xp: 50,
    topicIds: ['testing'],
    prerequisites: ['l-m42-01'],
    learningObjectives: [
      'Distinguish stubs, spies and mocks',
      'Replace a dependency by injection rather than by patching',
      'Test asynchronous code deterministically',
      'Avoid arbitrary sleeps in tests',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Why replace a dependency',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Some dependencies make a test **slow** (a network call), **non-deterministic** (the clock, randomness), **destructive** (sending a real email), or simply **unavailable** (a service that does not exist yet).',
          'A **test double** stands in for the real thing. The word covers several distinct roles that are worth separating, because the terminology is used loosely and the distinction affects what your test actually checks.',
        ],
      },
      {
        kind: SECTION.TABLE,
        headers: ['Double', 'Purpose', 'What the test asserts'],
        rows: [
          ['**Stub**', 'Supplies a canned answer', 'The **result** the code under test produced'],
          ['**Spy**', 'Records how it was called', 'That a call **happened**, and with what'],
          ['**Mock**', 'A double with expectations built in', 'That the interaction matched the expectation'],
          ['**Fake**', 'A working but simplified implementation', 'Behaviour, using an in-memory version'],
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A stub, a spy and a fake — built by hand.',
        code: [
          '"use strict";',
          '',
          'function createOrderService({ fetchPrice, notify, repository }) {',
          '  return {',
          '    async place(sku, quantity) {',
          '      const price = await fetchPrice(sku);',
          '      const total = price * quantity;',
          '',
          '      const id = repository.save({ sku, quantity, total });',
          '      notify(`order ${id} placed for ${total}`);',
          '',
          '      return { id, total };',
          '    },',
          '  };',
          '}',
          '',
          '// STUB: a canned answer, no recording',
          'const fetchPrice = async () => 25;',
          '',
          '// SPY: records the calls it received',
          'function createSpy() {',
          '  const calls = [];',
          '  const fn = (...args) => { calls.push(args); return undefined; };',
          '  fn.calls = calls;',
          '  return fn;',
          '}',
          '',
          'const notify = createSpy();',
          '',
          '// FAKE: a real, simplified implementation',
          'function createFakeRepository() {',
          '  const rows = [];',
          '  return {',
          '    save(row) { rows.push(row); return rows.length; },',
          '    get all() { return [...rows]; },',
          '  };',
          '}',
          '',
          'const repository = createFakeRepository();',
          '',
          'async function main() {',
          '  const service = createOrderService({ fetchPrice, notify, repository });',
          '',
          '  const result = await service.place("abc", 2);',
          '',
          '  console.log("result      :", result);',
          '  console.log("spy calls   :", notify.calls.length);',
          '  console.log("spy argument:", notify.calls[0][0]);',
          '  console.log("fake stored :", repository.all);',
          '}',
          '',
          'main();',
        ].join('\n'),
        output: [
          'result      : {id: 1, total: 50}',
          'spy calls   : 1',
          'spy argument: order 1 placed for 50',
          'fake stored : [{sku: "abc", quantity: 2, total: 50}]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Injection beats patching',
        body: [
          'Every double above was simply **passed in**. No framework, no module patching, no `jest.mock` — because `createOrderService` declares its dependencies as parameters (Module 28).',
          'The alternative is reaching into a module and replacing its exports at runtime. That works, but it couples the test to the implementation\'s **import structure**, so moving a function between files breaks tests that never mentioned it.',
          'Frameworks provide `vi.fn()` and `jest.fn()` with richer assertions, and they are genuinely convenient. But the design that makes doubles easy is dependency injection — a codebase that needs heavy module patching is usually telling you something about its coupling.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        caption: 'The same test with a real framework — illustrative.',
        code: [
          'import { it, expect, vi } from "vitest";',
          '',
          'it("notifies once when an order is placed", async () => {',
          '  const notify = vi.fn();',
          '  const repository = { save: vi.fn(() => 7) };',
          '',
          '  const service = createOrderService({',
          '    fetchPrice: async () => 25,',
          '    notify,',
          '    repository,',
          '  });',
          '',
          '  const result = await service.place("abc", 2);',
          '',
          '  expect(result).toEqual({ id: 7, total: 50 });',
          '  expect(notify).toHaveBeenCalledTimes(1);',
          '  expect(notify).toHaveBeenCalledWith("order 7 placed for 50");',
          '  expect(repository.save).toHaveBeenCalledWith({ sku: "abc", quantity: 2, total: 50 });',
          '});',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Do not mock everything',
        body: [
          'A test where every collaborator is a mock verifies only that your code calls the functions you told it to call. It will pass happily while the real integration is broken, because nothing real was exercised.',
          'Mock at the **boundaries** — the network, the clock, the filesystem, anything slow, destructive or non-deterministic. Use the real thing for your own pure logic, which is fast and deterministic already.',
          'A useful smell: if a test asserts mostly on **calls** rather than on **results**, it is probably testing the implementation rather than the behaviour — which lesson 3 develops.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Asynchronous tests',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Awaiting the work rather than guessing how long it takes.',
        code: [
          '"use strict";',
          '',
          'async function fetchUser(id, request) {',
          '  const response = await request(`/users/${id}`);',
          '',
          '  if (!response.ok) throw new Error(`request failed: ${response.status}`);',
          '',
          '  return response.data;',
          '}',
          '',
          'async function main() {',
          '  // A stubbed request — resolved, deterministic, no network',
          '  const ok = async () => ({ ok: true, status: 200, data: { id: 1, name: "Ada" } });',
          '  const failing = async () => ({ ok: false, status: 500 });',
          '',
          '  // SUCCESS: await the promise and assert on the value',
          '  const user = await fetchUser(1, ok);',
          '  console.log("resolved :", user);',
          '',
          '  // FAILURE: await inside try/catch and assert on the error',
          '  try {',
          '    await fetchUser(1, failing);',
          '    console.log("rejected : NO — it should have thrown");',
          '  } catch (error) {',
          '    console.log("rejected :", error.message);',
          '  }',
          '',
          '  // A rejection that is never awaited would pass silently — always await',
          '  const settled = await Promise.allSettled([fetchUser(1, ok), fetchUser(1, failing)]);',
          '  console.log("statuses :", settled.map((r) => r.status));',
          '}',
          '',
          'main();',
        ].join('\n'),
        output: [
          'resolved : {id: 1, name: "Ada"}',
          'rejected : request failed: 500',
          'statuses : ["fulfilled", "rejected"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'A forgotten `await` makes a test pass for the wrong reason',
        body: [
          'If a test calls an async function without awaiting it, the test function **returns before the assertion runs**. The runner sees no failure and reports a pass — including when the code under test throws.',
          'That is one of the most dangerous test bugs, because the suite looks green while checking nothing. Always `await` the call, and when asserting a rejection make sure the test **fails if no error was thrown** — the "NO — it should have thrown" line above exists for exactly that reason.',
          'Frameworks provide `await expect(fn()).rejects.toThrow()` which handles this properly. Note this curriculum\'s own sandbox has no `.rejects` matcher, so exercises here await and inspect the error directly.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Testing time-dependent code without sleeping.',
        code: [
          '"use strict";',
          '',
          '// BAD DESIGN: reaches for the real clock, so tests must sleep',
          'function isExpiredBad(token) {',
          '  return token.expiresAt < Date.now();',
          '}',
          '',
          '// GOOD DESIGN: the clock is a parameter (Module 37)',
          'function isExpired(token, now) {',
          '  return token.expiresAt < now;',
          '}',
          '',
          '// Every case is instant and deterministic',
          'console.log("expired    :", isExpired({ expiresAt: 100 }, 200));',
          'console.log("valid      :", isExpired({ expiresAt: 300 }, 200));',
          'console.log("exactly now:", isExpired({ expiresAt: 200 }, 200));',
          '',
          '// The same idea for scheduling: inject the scheduler',
          'function createRetrier({ schedule }) {',
          '  return {',
          '    run(task, attempts) {',
          '      const outcomes = [];',
          '',
          '      for (let attempt = 1; attempt <= attempts; attempt++) {',
          '        outcomes.push(task(attempt));',
          '        if (attempt < attempts) schedule(attempt * 1000);',
          '      }',
          '',
          '      return outcomes;',
          '    },',
          '  };',
          '}',
          '',
          '// A fake scheduler records the delays instead of waiting for them',
          'const delays = [];',
          'const retrier = createRetrier({ schedule: (ms) => delays.push(ms) });',
          '',
          'console.log("outcomes   :", retrier.run((n) => `try ${n}`, 3));',
          'console.log("delays     :", delays, "<- no wait after the last attempt");',
        ].join('\n'),
        output: [
          'expired    : true',
          'valid      : false',
          'exactly now: false',
          'outcomes   : ["try 1", "try 2", "try 3"]',
          'delays     : [1000, 2000] <- no wait after the last attempt',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Never make a sleep your default testing tool',
        body: [
          '`await new Promise(r => setTimeout(r, 500))` is slow when it works and **flaky** when the machine is loaded — the delay that was generous on your laptop is not on a busy CI runner. A suite full of sleeps is both slow and intermittently red.',
          'The fixes in order of preference: **inject the clock or scheduler** (as above), so no time passes at all; use the framework\'s **fake timers** (`vi.useFakeTimers()`), which let you advance time instantly; or, if you must wait for a real event, **poll for the condition** with a generous deadline rather than sleeping a fixed duration.',
          'Note the third option is what this curriculum\'s own interval exercises use, after a fixed-duration wait proved flaky under load.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'it("rejects an invalid id", () => {',
          '  // note: no async, no await',
          '  expect(fetchUser(-1)).rejects.toThrow();',
          '});',
          '',
          '// fetchUser(-1) returns a promise that rejects.',
        ].join('\n'),
        options: [
          'The test passes regardless — the assertion is never awaited, so the test function returns before it settles',
          'The test correctly verifies the rejection',
          'The test fails',
          'It throws a SyntaxError',
        ],
        correct: 0,
        explanation:
          '`expect(...).rejects.toThrow()` returns a **promise**, and nothing awaits it — so the test function returns immediately and the runner records a pass before the assertion has had a chance to settle. The test would pass even if `fetchUser` resolved successfully, which means it verifies nothing at all while looking entirely reasonable. The fix is `await expect(fetchUser(-1)).rejects.toThrow();` inside an `async` test. This is among the most dangerous test bugs precisely because the suite stays green — and note some runners now warn about floating assertions, but you cannot rely on that.',
      },
    ],
    exercises: [
      {
        id: 'ex-m42-02-a',
        title: 'Build a spy',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['testing'],
        instructions:
          'Write `createSpy(implementation)` returning a function that records every call\'s arguments on `.calls`, exposes `.callCount`, forwards to `implementation` when given, and returns its result.',
        starterCode: [
          'function createSpy(implementation) {',
          '  // Record, then delegate.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'records a call', body: 'const spy = createSpy(); spy(1); expect(spy.callCount).toBe(1);' },
          { name: 'records the arguments', body: 'const spy = createSpy(); spy("a", "b"); expect(spy.calls[0]).toEqual(["a", "b"]);' },
          { name: 'records several calls', body: 'const spy = createSpy(); spy(1); spy(2); expect(spy.calls).toEqual([[1], [2]]);' },
          { name: 'starts with no calls', body: 'expect(createSpy().callCount).toBe(0);' },
          { name: 'returns undefined without an implementation', body: 'expect(createSpy()(1)).toBe(undefined);' },
          { name: 'forwards to the implementation', body: 'const spy = createSpy((a, b) => a + b); expect(spy(2, 3)).toBe(5);' },
          { name: 'still records when forwarding', body: 'const spy = createSpy((a) => a); spy(9); expect(spy.calls[0]).toEqual([9]);' },
          { name: 'records a call with no arguments', body: 'const spy = createSpy(); spy(); expect(spy.calls[0]).toEqual([]);', hidden: true },
        ],
        hints: [
          'Collect arguments with a rest parameter.',
          'Attach `calls` to the function object itself.',
          '`callCount` reads well as a getter via `Object.defineProperty`, or just derive it.',
        ],
        solution: [
          'function createSpy(implementation) {',
          '  const calls = [];',
          '',
          '  function spy(...args) {',
          '    calls.push(args);',
          '',
          '    return implementation ? implementation(...args) : undefined;',
          '  }',
          '',
          '  spy.calls = calls;',
          '',
          '  Object.defineProperty(spy, "callCount", {',
          '    get() { return calls.length; },',
          '  });',
          '',
          '  return spy;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'A rest parameter captures any arity, so a call with no arguments records an empty array rather than nothing — the hidden test. Attaching `calls` to the function object is what makes a spy usable as a drop-in replacement: it is still a function, so the code under test cannot tell the difference. Recording **before** delegating means the call is captured even if the implementation throws. `callCount` is a getter so it stays accurate as calls accumulate, rather than being a snapshot taken at creation.',
      },
      {
        id: 'ex-m42-02-b',
        title: 'Inject the clock',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['testing'],
        instructions:
          'Rewrite `isSessionActive(session)` — which currently calls `Date.now()` — as `isSessionActive(session, now)` so it is testable without waiting. A session is active when `now` is before `session.expiresAt`; exactly at expiry counts as expired.',
        starterCode: [
          '// function isSessionActive(session) {',
          '//   return session.expiresAt > Date.now();',
          '// }',
          '',
          'function isSessionActive(session, now) {',
          '}',
        ].join('\n'),
        tests: [
          { name: 'active before expiry', body: 'expect(isSessionActive({ expiresAt: 200 }, 100)).toBe(true);' },
          { name: 'expired after expiry', body: 'expect(isSessionActive({ expiresAt: 100 }, 200)).toBe(false);' },
          { name: 'exactly at expiry counts as expired', body: 'expect(isSessionActive({ expiresAt: 100 }, 100)).toBe(false);' },
          { name: 'returns a boolean', body: 'expect(typeof isSessionActive({ expiresAt: 200 }, 100)).toBe("boolean");' },
          { name: 'is deterministic', body: 'const s = { expiresAt: 500 }; expect(isSessionActive(s, 100)).toBe(isSessionActive(s, 100));' },
          { name: 'does not read the real clock', body: 'expect(isSessionActive({ expiresAt: 0 }, -1)).toBe(true);' },
          { name: 'handles a far-future expiry', body: 'expect(isSessionActive({ expiresAt: 1e15 }, 0)).toBe(true);', hidden: true },
        ],
        hints: [
          'Compare `session.expiresAt` with the `now` parameter.',
          '`>` rather than `>=` makes exact expiry count as expired.',
          'Do not call `Date.now()` anywhere.',
        ],
        solution: [
          'function isSessionActive(session, now) {',
          '  return session.expiresAt > now;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Turning the hidden clock dependency into a **parameter** makes the function pure (Module 37), so every case runs instantly and deterministically — no sleeping, no fake timers, no flakiness. The sixth test is the proof that the real clock is gone: passing `-1` as `now` makes an `expiresAt` of `0` active, which is impossible if `Date.now()` is being consulted. `>` rather than `>=` is what makes exact expiry count as expired, which the third test pins down explicitly. The caller supplies `Date.now()` at the edge.',
      },
      {
        id: 'ex-m42-02-c',
        title: 'Test an async function',
        kind: EXERCISE_KIND.ASYNC_TASK,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['testing'],
        instructions:
          'Write `loadProfile(id, request)` that awaits `request(url)`, returns `response.data` when `response.ok` is true, and throws an `Error` containing the status otherwise. Then it must be testable with a stubbed request.',
        starterCode: [
          'async function loadProfile(id, request) {',
          '  // Await, check ok, return or throw.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'returns the data on success', body: 'const r = async () => ({ ok: true, data: { id: 1 } }); expect(await loadProfile(1, r)).toEqual({ id: 1 });' },
          { name: 'requests the right url', body: 'let seen = null; const r = async (url) => { seen = url; return { ok: true, data: {} }; }; await loadProfile(7, r); expect(seen.includes("7")).toBe(true);' },
          { name: 'throws on a failed response', body: 'const r = async () => ({ ok: false, status: 500 }); let caught = null; try { await loadProfile(1, r); } catch (e) { caught = e; } expect(caught instanceof Error).toBe(true);' },
          { name: 'includes the status in the message', body: 'const r = async () => ({ ok: false, status: 404 }); let msg = ""; try { await loadProfile(1, r); } catch (e) { msg = e.message; } expect(msg.includes("404")).toBe(true);' },
          { name: 'returns a promise', body: 'const r = async () => ({ ok: true, data: 1 }); expect(typeof loadProfile(1, r).then).toBe("function");' },
          { name: 'fails the test if no error is thrown', body: 'const r = async () => ({ ok: false, status: 500 }); let threw = false; try { await loadProfile(1, r); } catch { threw = true; } expect(threw).toBe(true);' },
          { name: 'propagates a rejected request', body: 'const r = async () => { throw new Error("offline"); }; let msg = ""; try { await loadProfile(1, r); } catch (e) { msg = e.message; } expect(msg).toBe("offline");', hidden: true },
        ],
        hints: [
          '`const response = await request(...)`.',
          'Guard with `if (!response.ok) throw new Error(...)`.',
          'Do not wrap the call in try/catch — a rejected request should propagate.',
        ],
        solution: [
          'async function loadProfile(id, request) {',
          '  const response = await request(`/profiles/${id}`);',
          '',
          '  if (!response.ok) {',
          '    throw new Error(`request failed with status ${response.status}`);',
          '  }',
          '',
          '  return response.data;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Taking `request` as a parameter is what makes every test instant and deterministic — no network, no `fetch` patching, just a stub returning a plain object. The sixth test encodes the discipline from the lesson: it sets a flag in the `catch` and asserts the flag, so the test **fails if no error was thrown** rather than passing silently. Deliberately not wrapping the `await` in try/catch lets a rejected request propagate unchanged (hidden test), which is the right behaviour — the function reports HTTP failures, and transport failures are the caller\'s to handle.',
      },
      {
        id: 'ex-m42-02-d',
        title: 'Why not sleep in tests?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['testing'],
        instructions:
          'A test waits 500ms with `setTimeout` before asserting. What is wrong with that, and what should replace it?',
        options: [
          'Nothing — it is a standard technique',
          'It is slow when it works and flaky when the machine is loaded; inject the clock or scheduler, use fake timers, or poll for the condition',
          'setTimeout does not work in tests',
          'The delay should be longer',
        ],
        correct: 1,
        hints: [
          'What happens to that delay on a busy CI machine?',
        ],
        solution: 'It is slow when it works and flaky when the machine is loaded; inject the clock or scheduler, use fake timers, or poll for the condition',
        solutionExplanation:
          'A fixed sleep encodes an assumption about machine speed that stops holding under load, so the suite becomes intermittently red for reasons unrelated to the code — and every such test slows the suite even when it passes. Increasing the delay makes it slower without removing the flakiness. In order of preference: **inject** the clock or scheduler so no time passes at all, use the framework\'s **fake timers** to advance time instantly, or **poll for the condition** with a generous deadline when you genuinely must wait for a real event.',
      },
    ],
    quiz: {
      id: 'qz-m42-02',
      questions: [
        {
          id: 'q-m42-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['testing'],
          prompt: 'What distinguishes a spy from a stub?',
          options: [
            'A spy is faster',
            'A stub supplies a canned answer; a spy records how it was called',
            'A spy only works on classes',
            'They are the same',
          ],
          correct: 1,
          optionExplanations: [
            'Speed is not the distinction.',
            'Correct — result versus interaction.',
            'Both are plain functions.',
            'They serve different assertions.',
          ],
          explanation:
            'A stub lets you assert on the **result** your code produced; a spy lets you assert that a **call happened** and with what arguments. Many doubles do both.',
        },
        {
          id: 'q-m42-02-2',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['testing'],
          prompt: 'A test that forgets to await an async assertion will fail.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'The test returns before it settles.',
            'Correct — it passes while checking nothing.',
          ],
          explanation:
            'The test function returns before the promise settles, so the runner records a pass — even if the code under test threw. Always await, and make rejection tests fail when nothing throws.',
        },
        {
          id: 'q-m42-02-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['testing'],
          prompt: 'Why is injecting a dependency better than patching a module?',
          options: [
            'It runs faster',
            'Patching couples the test to the import structure, so moving a function between files can break unrelated tests',
            'Patching is deprecated',
            'Injection needs no framework',
          ],
          correct: 1,
          optionExplanations: [
            'Speed is comparable.',
            'Correct — it tests structure, not behaviour.',
            'Frameworks still support it.',
            'True but not the main reason.',
          ],
          explanation:
            'Injection declares dependencies in the signature, so a double is just an argument. Module patching binds the test to where code lives, which changes for reasons unrelated to behaviour.',
        },
        {
          id: 'q-m42-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['testing'],
          prompt: 'What should you mock?',
          options: [
            'Everything, for isolation',
            'Boundaries — network, clock, filesystem, and anything slow, destructive or non-deterministic',
            'Nothing, ever',
            'Only classes',
          ],
          correct: 1,
          optionExplanations: [
            'Then nothing real is exercised.',
            'Correct — use the real thing for your own pure logic.',
            'Some dependencies genuinely must be replaced.',
            'The kind of value is irrelevant.',
          ],
          explanation:
            'A test where everything is mocked verifies only that you called the functions you told it to call. Mock at the edges; run your own logic for real.',
        },
      ],
    },
    summary:
      'Replace a dependency when it is **slow, non-deterministic, destructive or unavailable**. The roles are worth separating: a **stub** supplies a canned answer (assert on the **result**), a **spy** records how it was called (assert the **interaction**), a **mock** carries built-in expectations, and a **fake** is a working simplified implementation. All of them are easy when dependencies are **passed in** — no framework, no module patching, which would otherwise couple tests to the import structure so that moving a function breaks unrelated tests. **Do not mock everything**: a fully mocked test verifies only that you called what you said you would, and a suite asserting mostly on **calls** rather than **results** is testing the implementation. For async code, **always `await`** — a forgotten `await` makes the test function return before the assertion settles, so the runner reports a pass even when the code throws, which is among the most dangerous test bugs because the suite stays green. Make rejection tests **fail when nothing throws**. Finally, **never sleep by default**: a fixed delay is slow when it works and flaky under load. In order of preference, **inject the clock or scheduler** so no time passes, use the framework\'s **fake timers**, or **poll for the condition** with a generous deadline when a real event must be awaited.',
    keyTakeaways: [
      'Stub for results, spy for interactions, fake for simplified real behaviour',
      'Injection makes doubles trivial; patching couples tests to file structure',
      'Mock the boundaries only — run your own logic for real',
      'A forgotten await makes a test pass while checking nothing',
      'Rejection tests must fail when no error is thrown',
      'Inject the clock, use fake timers, or poll — never sleep a fixed duration',
    ],
    relatedLessons: ['l-m42-01', 'l-m42-03'],
    interviewConnections: [
      'What is the difference between a stub, a spy and a mock?',
      'How do you test code that depends on the current time?',
      'What goes wrong if you forget to await in a test?',
      'What should and should not be mocked?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m42-03',
    slug: 'testing-behaviour-not-implementation',
    moduleId: M,
    order: 3,
    title: 'Testing Behaviour, Not Implementation',
    description: 'DOM testing from the user\'s perspective, and why brittle tests are worse than none.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 17,
    xp: 45,
    topicIds: ['testing'],
    prerequisites: ['l-m42-02'],
    learningObjectives: [
      'Distinguish behaviour tests from implementation tests',
      'Test DOM code by interacting and observing',
      'Recognise and repair brittle tests',
      'Explain what coverage does and does not tell you',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'The distinction',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'A brittle test is worse than no test',
        body: [
          'A test that breaks when you rename a private function, reorder statements, or change a data structure — **without any change in what the code does** — is testing the implementation.',
          'This is worse than having no test, because it produces failures that carry no information. Teams learn that red is normal, and eventually a real failure is dismissed with the others.',
          'It also actively **prevents refactoring**, which is the main thing a test suite was supposed to enable. When every restructuring means rewriting tests, people stop restructuring.',
          'The rule: assert on what a **caller or user can observe** — return values, rendered output, calls to genuine collaborators. Not on internal names, private state, or the order of internal steps.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The same feature, tested two ways.',
        code: [
          '"use strict";',
          '',
          'function createCounter() {',
          '  let count = 0;',
          '',
          '  function bump(by) { count += by; }',
          '',
          '  return {',
          '    increment() { bump(1); return count; },',
          '    incrementBy(n) { bump(n); return count; },',
          '    get value() { return count; },',
          '  };',
          '}',
          '',
          '// BEHAVIOUR: only uses the public surface',
          'const behaviour = [];',
          '{',
          '  const c = createCounter();',
          '  c.increment();',
          '  c.incrementBy(4);',
          '  behaviour.push(c.value === 5);',
          '  behaviour.push(createCounter().value === 0);',
          '}',
          '',
          '// IMPLEMENTATION: reaches for internals that are none of its business',
          'const implementation = [];',
          '{',
          '  const c = createCounter();',
          '  implementation.push(typeof c.bump === "function");   // internal helper',
          '  implementation.push(Object.keys(c).length === 2);    // exact surface shape',
          '}',
          '',
          'console.log("behaviour     :", behaviour);',
          'console.log("implementation:", implementation);',
          '',
          '// Now RENAME the private helper — behaviour is unchanged',
          'function createCounterRefactored() {',
          '  let count = 0;',
          '  const applyDelta = (by) => { count += by; };',
          '',
          '  return {',
          '    increment() { applyDelta(1); return count; },',
          '    incrementBy(n) { applyDelta(n); return count; },',
          '    get value() { return count; },',
          '  };',
          '}',
          '',
          'const after = createCounterRefactored();',
          'after.increment();',
          'after.incrementBy(4);',
          '',
          'console.log("behaviour still holds:", after.value === 5);',
        ].join('\n'),
        output: [
          'behaviour     : [true, true]',
          'implementation: [false, false]',
          'behaviour still holds: true',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Notice the implementation checks were already failing **before** any refactoring — `bump` was never public, and `Object.keys` does not include getters. They were asserting things the module never promised.',
          'The behaviour checks keep passing across a rename of the internal helper, which is exactly what you want: the tests constrain the contract, not the code that fulfils it.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Testing the DOM',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        needsDom: true,
        html: '<div id="app"><button id="add">Add</button><ul id="items"></ul><p id="empty">No items yet</p></div>',
        caption: 'Interact the way a user would, then observe what they would see.',
        code: [
          'function mountList(root) {',
          '  const button = root.querySelector("#add");',
          '  const list = root.querySelector("#items");',
          '  const empty = root.querySelector("#empty");',
          '  let count = 0;',
          '',
          '  function render() {',
          '    empty.hidden = count > 0;',
          '  }',
          '',
          '  button.addEventListener("click", () => {',
          '    count += 1;',
          '',
          '    const li = document.createElement("li");',
          '    li.textContent = `Item ${count}`;',
          '    list.append(li);',
          '',
          '    render();',
          '  });',
          '',
          '  render();',
          '}',
          '',
          'const app = document.getElementById("app");',
          'mountList(app);',
          '',
          '// BEFORE: what would a user see?',
          'console.log("empty visible :", !app.querySelector("#empty").hidden);',
          'console.log("items         :", app.querySelectorAll("li").length);',
          '',
          '// ACT: click, exactly as a user would',
          'app.querySelector("#add").click();',
          'app.querySelector("#add").click();',
          '',
          '// AFTER: observe the rendered result, not the internals',
          'console.log("items         :", app.querySelectorAll("li").length);',
          'console.log("first item    :", app.querySelector("li").textContent);',
          'console.log("empty hidden  :", app.querySelector("#empty").hidden);',
        ].join('\n'),
        output: [
          'empty visible : true',
          'items         : 0',
          'items         : 2',
          'first item    : Item 1',
          'empty hidden  : true',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The test never mentions the implementation',
        body: [
          'It does not check that a `click` listener was registered, that `render` exists, or that `count` is a number. It clicks a button and looks at the page — precisely what a user does.',
          'That means the whole thing could be rewritten with a different internal structure, a framework, or a completely different state approach, and the test would still pass **if the behaviour is preserved**. That is the property that makes tests useful during refactoring.',
          'Note `mountList` takes `root` as a parameter rather than reaching for `document`. That is what lets a test mount several independent instances, and it is Module 28\'s dependency inversion again.',
        ],
      },
      {
        kind: SECTION.LIST,
        items: [
          '**Query the way a user finds things.** Visible text and roles are stable; deeply nested CSS selectors like `div > div:nth-child(3) span` break on any markup change.',
          '**Act through the interface.** `button.click()`, dispatching an `input` event, submitting a form — not calling the handler directly.',
          '**Assert what is observable.** Rendered text, whether an element exists, whether it is hidden or disabled.',
          '**Do not assert on handler names.** "a function called `handleClick` exists" tests a name, not a behaviour.',
          '**Do not assert on internal state.** If a counter is private, its value is not the contract — what appears on screen is.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        needsDom: true,
        html: '<div id="app"><form id="signup"><input id="email" name="email" /><button type="submit">Join</button></form><p id="error"></p></div>',
        caption: 'An integration test of a form, from the outside.',
        code: [
          'function mountSignup(root, { submit }) {',
          '  const form = root.querySelector("#signup");',
          '  const email = root.querySelector("#email");',
          '  const error = root.querySelector("#error");',
          '',
          '  form.addEventListener("submit", (event) => {',
          '    event.preventDefault();',
          '',
          '    if (!email.value.includes("@")) {',
          '      error.textContent = "Enter a valid email";',
          '      return;',
          '    }',
          '',
          '    error.textContent = "";',
          '    submit({ email: email.value });',
          '  });',
          '}',
          '',
          '// A spy stands in for the real submission',
          'const submitted = [];',
          'const app = document.getElementById("app");',
          '',
          'mountSignup(app, { submit: (data) => submitted.push(data) });',
          '',
          'const form = app.querySelector("#signup");',
          'const email = app.querySelector("#email");',
          '',
          '// INVALID: type a bad value and submit',
          'email.value = "not-an-email";',
          'form.dispatchEvent(new Event("submit", { cancelable: true }));',
          '',
          'console.log("error shown  :", app.querySelector("#error").textContent);',
          'console.log("not submitted:", submitted.length);',
          '',
          '// VALID: correct it and submit again',
          'email.value = "ada@example.com";',
          'form.dispatchEvent(new Event("submit", { cancelable: true }));',
          '',
          'console.log("error cleared:", JSON.stringify(app.querySelector("#error").textContent));',
          'console.log("submitted    :", submitted);',
        ].join('\n'),
        output: [
          'error shown  : Enter a valid email',
          'not submitted: 0',
          'error cleared: ""',
          'submitted    : [{email: "ada@example.com"}]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'This is an integration test worth having',
        body: [
          'It exercises the real form, the real event handling, the real validation and the real DOM updates — replacing only the **boundary** (`submit`) with a spy. That is exactly the guidance from lesson 2: mock the edges, run your own logic.',
          'It also catches a whole class of bug a unit test of the validator would miss: the handler could validate perfectly and forget `preventDefault`, or update the wrong element, and only a test at this level notices.',
          'Note `dispatchEvent` with a real `Event` rather than calling the listener directly. Calling the handler would skip the browser\'s own event plumbing, which is part of what is being tested.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Repairing a brittle test',
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Brittle',
          code: [
            '// Asserts internals',
            'expect(',
            '  cart._items.length',
            ').toBe(2);',
            '',
            'expect(',
            '  typeof cart.recalc',
            ').toBe("function");',
            '',
            'expect(',
            '  Object.keys(cart)',
            ').toEqual([',
            '  "add", "total",',
            ']);',
          ].join('\n'),
        },
        right: {
          title: 'Behavioural',
          code: [
            '// Asserts the contract',
            'cart.add({ price: 10 });',
            'cart.add({ price: 5 });',
            '',
            'expect(cart.total())',
            '  .toBe(15);',
            '',
            'expect(cart.count)',
            '  .toBe(2);',
          ].join('\n'),
        },
        note: 'The left-hand tests break if `_items` is renamed, if `recalc` is inlined, or if a method is added — none of which changes what the cart does. The right-hand tests break only if the cart stops totalling correctly, which is the only failure worth being told about.',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Coverage is a signal, not a target',
        body: [
          '**Line coverage** tells you which lines ran. **Branch coverage** tells you whether both sides of each condition ran — more useful, since an untested `else` is a common hiding place. **Function coverage** tells you which functions were called at all.',
          'The honest use is to look for **surprising gaps**: a whole module at 0%, an error path never exercised. That is genuine information.',
          'The dishonest use is a target. Chasing a percentage produces tests written to execute lines rather than to check behaviour — and those are exactly the brittle, assertion-light tests this lesson warns about. A suite at 95% coverage full of implementation assertions is worse than one at 60% testing behaviour.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// A test for a search box:',
          '',
          'it("filters the list", () => {',
          '  const app = mount();',
          '  const input = app.querySelector(".search-input");',
          '',
          '  // Calls the internal handler directly',
          '  app.handleSearchInput({ target: { value: "ada" } });',
          '',
          '  expect(app.state.filtered.length).toBe(1);',
          '});',
        ].join('\n'),
        options: [
          'It tests the implementation — it bypasses the real event and asserts on internal state, so it can pass while the feature is broken for users',
          'It is a good behavioural test',
          'It will throw',
          'It is an end-to-end test',
        ],
        correct: 0,
        explanation:
          'Two separate problems. Calling `handleSearchInput` directly **bypasses the event plumbing**, so the test passes even if the listener was never attached, was attached to the wrong element, or was registered for the wrong event — the feature would be entirely broken for users while the test stays green. And asserting on `app.state.filtered` checks **internal state** rather than what is rendered, so it also passes if the filtered results never reach the screen. The behavioural version sets `input.value`, dispatches a real `input` event, and asserts on the **visible list items** — which fails in exactly the cases that matter and survives any internal restructuring.',
      },
    ],
    exercises: [
      {
        id: 'ex-m42-03-a',
        title: 'Identify the brittle assertion',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['testing'],
        instructions:
          'Which assertion will break during a harmless refactor?',
        options: [
          '`expect(cart.total()).toBe(15)`',
          '`expect(typeof cart.recalculateTotals).toBe("function")`',
          '`expect(cart.count).toBe(2)`',
          '`expect(() => cart.add(null)).toThrow()`',
        ],
        correct: 1,
        hints: [
          'Which one names something that is not part of the contract?',
        ],
        solution: '`expect(typeof cart.recalculateTotals).toBe("function")`',
        solutionExplanation:
          'It asserts that a **particular internal function exists by name**, which is not something callers depend on. Renaming it, inlining it, or replacing it with a different approach would fail the test while the cart behaves identically — a failure carrying no information. The other three assert observable contract: the total, the count, and a documented error. Those break only when the cart genuinely stops working, which is the only failure worth being told about.',
      },
      {
        id: 'ex-m42-03-b',
        title: 'Test the rendered result',
        kind: EXERCISE_KIND.DOM_TASK,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['testing'],
        instructions:
          'Write `mountToggle(root)` that wires the existing `#toggle` button so each click shows or hides `#panel` (using the `hidden` property) and updates the button text to `"Hide"` or `"Show"`. The panel starts hidden.',
        html: '<div id="app"><button id="toggle">Show</button><div id="panel" hidden>Panel content</div></div>',
        starterCode: [
          'function mountToggle(root) {',
          '  // Wire the button; the test will click it and observe the page.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'panel starts hidden', body: 'const r = document.createElement("div"); r.innerHTML = `<button id="toggle">Show</button><div id="panel" hidden>Panel content</div>`; mountToggle(r); expect(r.querySelector("#panel").hidden).toBe(true);' },
          { name: 'a click reveals the panel', body: 'const r = document.createElement("div"); r.innerHTML = `<button id="toggle">Show</button><div id="panel" hidden>Panel content</div>`; mountToggle(r); r.querySelector("#toggle").click(); expect(r.querySelector("#panel").hidden).toBe(false);' },
          { name: 'the button text updates', body: 'const r = document.createElement("div"); r.innerHTML = `<button id="toggle">Show</button><div id="panel" hidden>Panel content</div>`; mountToggle(r); r.querySelector("#toggle").click(); expect(r.querySelector("#toggle").textContent).toBe("Hide");' },
          { name: 'a second click hides it again', body: 'const r = document.createElement("div"); r.innerHTML = `<button id="toggle">Show</button><div id="panel" hidden>Panel content</div>`; mountToggle(r); const b = r.querySelector("#toggle"); b.click(); b.click(); expect(r.querySelector("#panel").hidden).toBe(true);' },
          { name: 'the text returns to Show', body: 'const r = document.createElement("div"); r.innerHTML = `<button id="toggle">Show</button><div id="panel" hidden>Panel content</div>`; mountToggle(r); const b = r.querySelector("#toggle"); b.click(); b.click(); expect(b.textContent).toBe("Show");' },
          { name: 'three clicks leave it visible', body: 'const r = document.createElement("div"); r.innerHTML = `<button id="toggle">Show</button><div id="panel" hidden>Panel content</div>`; mountToggle(r); const b = r.querySelector("#toggle"); b.click(); b.click(); b.click(); expect(r.querySelector("#panel").hidden).toBe(false);' },
        ],
        hints: [
          'Query the button and panel from `root`, not from `document`.',
          'Toggle `panel.hidden` on each click.',
          'Set the button text from the new hidden state.',
        ],
        solution: [
          'function mountToggle(root) {',
          '  const button = root.querySelector("#toggle");',
          '  const panel = root.querySelector("#panel");',
          '',
          '  button.addEventListener("click", () => {',
          '    panel.hidden = !panel.hidden;',
          '    button.textContent = panel.hidden ? "Show" : "Hide";',
          '  });',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Every test **clicks the real button** and then inspects what a user would see — the panel\'s visibility and the button\'s text. None mentions the listener, an internal flag, or a handler name, so the implementation could be rewritten entirely and these tests would still pass provided the behaviour holds. Deriving the button text from `panel.hidden` **after** toggling keeps the two in sync by construction, rather than tracking a separate variable that could drift.Notice each test builds a **fresh element** rather than reusing a shared one. That is not tidiness — mounting twice on the same element attaches a **second listener**, so one click would toggle twice and land back where it started. Accumulating listeners is a real bug in application code too (Module 32), and it shows up first in tests that share a container.',
      },
      {
        id: 'ex-m42-03-c',
        title: 'Rewrite the brittle test',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['testing'],
        instructions:
          'Write `behaviourChecks(createCart)` returning an object of boolean results that tests a cart **only through its public surface**: `add(item)`, `total()` and `count`. Include an empty cart, one item, two items, and that adding does not mutate the item passed in.',
        starterCode: [
          'function createCart() {',
          '  const items = [];',
          '  return {',
          '    add(item) { items.push({ ...item }); },',
          '    total() { return items.reduce((s, i) => s + i.price, 0); },',
          '    get count() { return items.length; },',
          '  };',
          '}',
          '',
          'function behaviourChecks(factory) {',
          '  // Return { empty, single, multiple, noMutation }',
          '}',
        ].join('\n'),
        tests: [
          { name: 'empty cart totals zero', body: 'expect(behaviourChecks(createCart).empty).toBe(true);' },
          { name: 'single item', body: 'expect(behaviourChecks(createCart).single).toBe(true);' },
          { name: 'multiple items', body: 'expect(behaviourChecks(createCart).multiple).toBe(true);' },
          { name: 'does not mutate the input item', body: 'expect(behaviourChecks(createCart).noMutation).toBe(true);' },
          { name: 'returns exactly four checks', body: 'expect(Object.keys(behaviourChecks(createCart)).length).toBe(4);' },
          { name: 'uses only the public surface', body: 'const spy = () => { const c = createCart(); return new Proxy(c, { get(t, p) { if (!["add", "total", "count"].includes(p)) throw new Error(`touched ${String(p)}`); return t[p]; } }); }; expect(() => behaviourChecks(spy)).not.toThrow();', hidden: true },
        ],
        hints: [
          'Build a fresh cart for each check.',
          '`empty` checks `total() === 0` and `count === 0`.',
          'For `noMutation`, keep a reference to the item you passed and compare it afterwards.',
        ],
        solution: [
          'function createCart() {',
          '  const items = [];',
          '  return {',
          '    add(item) { items.push({ ...item }); },',
          '    total() { return items.reduce((s, i) => s + i.price, 0); },',
          '    get count() { return items.length; },',
          '  };',
          '}',
          '',
          'function behaviourChecks(factory) {',
          '  const emptyCart = factory();',
          '',
          '  const singleCart = factory();',
          '  singleCart.add({ price: 10 });',
          '',
          '  const multiCart = factory();',
          '  multiCart.add({ price: 10 });',
          '  multiCart.add({ price: 5 });',
          '',
          '  const item = { price: 3 };',
          '  const mutationCart = factory();',
          '  mutationCart.add(item);',
          '',
          '  return {',
          '    empty: emptyCart.total() === 0 && emptyCart.count === 0,',
          '    single: singleCart.total() === 10 && singleCart.count === 1,',
          '    multiple: multiCart.total() === 15 && multiCart.count === 2,',
          '    noMutation: item.price === 3 && Object.keys(item).length === 1,',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Every check goes through `add`, `total` and `count` — the documented surface — so the cart\'s internals could be rewritten entirely and these would still pass. The hidden test enforces that directly: it wraps the cart in a `Proxy` that throws on any other property access, so touching an internal such as `items` would fail. Building a **fresh cart per check** keeps them independent, and the `noMutation` case verifies a real contract that a caller depends on, rather than inspecting how the copy is made.',
      },
      {
        id: 'ex-m42-03-d',
        title: 'What is coverage good for?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['testing'],
        instructions:
          'Your team sets a mandatory 95% coverage threshold. What is the likely outcome?',
        options: [
          'Higher quality across the board',
          'Tests written to execute lines rather than check behaviour — often brittle and assertion-light',
          'Faster test runs',
          'Fewer end-to-end tests',
        ],
        correct: 1,
        hints: [
          'What is the cheapest way to raise a coverage number?',
        ],
        solution: 'Tests written to execute lines rather than check behaviour — often brittle and assertion-light',
        solutionExplanation:
          'The cheapest way to raise coverage is to call code without asserting anything meaningful about it, so a mandatory threshold rewards exactly the tests this lesson warns against. Coverage is genuinely useful as a **signal** — a module at 0%, or an error path never exercised, is real information worth acting on — but it measures which lines **ran**, never whether the assertions mattered. A suite at 60% testing behaviour is more valuable than one at 95% asserting on internals.',
      },
    ],
    quiz: {
      id: 'qz-m42-03',
      questions: [
        {
          id: 'q-m42-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['testing'],
          prompt: 'Why is a brittle test worse than no test?',
          options: [
            'It runs slowly',
            'It fails without a behaviour change, so failures stop carrying information and refactoring becomes expensive',
            'It uses more memory',
            'It cannot be automated',
          ],
          correct: 1,
          optionExplanations: [
            'Speed is not the issue.',
            'Correct — teams learn to ignore red.',
            'Memory is irrelevant.',
            'It is automated; that is part of the problem.',
          ],
          explanation:
            'Failures that carry no information train people to dismiss red, and they block the refactoring the suite was meant to enable.',
        },
        {
          id: 'q-m42-03-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['testing'],
          prompt: 'How should a DOM test trigger a click?',
          options: [
            'Call the handler function directly',
            'Click the element, so the real event path is exercised',
            'Set a flag on the component',
            'Reload the page',
          ],
          correct: 1,
          optionExplanations: [
            'That skips listener registration entirely.',
            'Correct — it tests what a user does.',
            'That bypasses the interface.',
            'Unnecessary and slow.',
          ],
          explanation:
            'Calling the handler passes even if the listener was never attached or was bound to the wrong element — the feature would be broken for users while the test stays green.',
        },
        {
          id: 'q-m42-03-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['testing'],
          prompt: 'Asserting on a component\'s internal state is a reliable way to test it.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Internal state is not the contract.',
            'Correct — assert on what is rendered.',
          ],
          explanation:
            'Internal state can be correct while nothing reaches the screen. Assert on the rendered output, which is what the user actually gets.',
        },
        {
          id: 'q-m42-03-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['testing'],
          prompt: 'What is branch coverage more useful than line coverage for?',
          options: [
            'Measuring speed',
            'Revealing whether both sides of a condition were exercised — an untested else is a common hiding place',
            'Counting assertions',
            'Finding slow tests',
          ],
          correct: 1,
          optionExplanations: [
            'Coverage measures execution, not time.',
            'Correct — a line can run with only one branch taken.',
            'Coverage never counts assertions.',
            'That needs timing data.',
          ],
          explanation:
            'A conditional line counts as covered when either side runs, so line coverage can hide an entirely untested branch. Neither metric says whether assertions were meaningful.',
        },
      ],
    },
    summary:
      'A **brittle test is worse than no test**: it fails when you rename a private function or reorder statements **without any behaviour change**, so failures stop carrying information, teams learn to ignore red, and the refactoring the suite was meant to enable becomes expensive. The rule is to assert on what a **caller or user can observe** — return values, rendered output, calls to genuine collaborators — never on internal names, private state, or the order of internal steps. For **DOM testing**, query the way a user finds things (visible text and roles, not deep CSS selectors), **act through the interface** (`button.click()`, dispatching a real event — calling the handler directly passes even when the listener was never attached), and assert on **rendered output**. An integration test of a real form with only the **boundary** replaced by a spy catches bugs a validator unit test cannot: a missing `preventDefault`, an update to the wrong element. **Coverage is a signal, not a target**: line coverage says which lines ran, branch coverage additionally whether both sides of a condition ran, and function coverage which functions were called at all — none says whether the assertions were meaningful. Use it to spot **surprising gaps**; a mandatory percentage rewards tests written to execute lines, which are precisely the brittle, assertion-light tests to avoid. A suite at 60% testing behaviour beats one at 95% asserting on internals.',
    keyTakeaways: [
      'Assert on observable behaviour, never on internal names or private state',
      'A brittle test blocks refactoring and trains people to ignore failures',
      'Click the element — calling the handler skips listener registration entirely',
      'Assert on rendered output, not on internal component state',
      'Mock only the boundary so the real event and DOM path is exercised',
      'Coverage is a signal for finding gaps, never a target to chase',
    ],
    relatedLessons: ['l-m42-02', 'l-m42-01'],
    interviewConnections: [
      'What is the difference between testing behaviour and testing implementation?',
      'How would you test a button that updates the page?',
      'Why is a brittle test worse than no test?',
      'Is code coverage a good quality metric?',
    ],
  },
];
