import { INTERVIEW_KIND as K, INTERVIEW_LEVEL as L } from '../schema/types.js';

/**
 * Browser platform and asynchronous patterns — the half of a JavaScript
 * interview that is not really about the language.
 *
 * The DOM, events, timers, `fetch`, storage and the observer APIs are all
 * supplied by the host, and interviewers probe them because most production
 * bugs live at that boundary rather than in the language semantics.
 *
 * The coding problems here are small, DOM- and async-flavoured utilities of
 * the kind that actually get written in a real codebase, with the platform
 * details (passive listeners, abort signals, focus management) that separate a
 * working answer from a correct one.
 */

const BROWSER = 'Browser Platform';
const ASYNC = 'Async Patterns';
const RUNTIME = 'Runtime & Tooling';

export const questions = [
  /* --------------------------------------------------------------- browser */
  {
    id: 'iv-bp-target-vs-currenttarget',
    question: 'What is the difference between `event.target` and `event.currentTarget`?',
    topic: BROWSER,
    level: L.JUNIOR,
    kind: K.BROWSER,
    topicIds: ['events'],
    relatedLessons: ['l-m19-02'],
    shortAnswer:
      '`target` is the deepest element where the event originated. `currentTarget` is the element whose listener is currently running. They are the same for a direct listener and differ whenever the event has bubbled — which is exactly the case delegation relies on.',
    deepAnswer: [
      'Click an icon inside a button inside a list item, with the listener on the list. `event.target` is the icon — the deepest element under the pointer. `event.currentTarget` is the list, because that is where this listener is attached.',
      'The distinction matters most for delegated handlers. Using `currentTarget` there always gives you the container, which tells you nothing about which row was clicked. Using raw `target` gives you whatever inner element happened to be hit, which may be an icon or a text node\'s parent rather than the control you care about.',
      'The robust pattern bridges the two:\n\n```js\nlist.addEventListener("click", (event) => {\n  const button = event.target.closest("[data-id]");\n  if (!button || !list.contains(button)) return;\n  remove(button.dataset.id);\n});\n```\n\n`closest` walks up from `target` to the nearest matching ancestor, so it works no matter how deeply nested the click landed. The `contains` check guards against a `closest` match outside the container, which can happen with portals or moved nodes.',
      'A practical detail: `currentTarget` is only valid **during** dispatch. Reading it later — inside a `setTimeout`, or after an `await` in an async handler — gives `null`, because the browser clears it once dispatch finishes. Capture what you need synchronously.',
      '`this` inside a non-arrow listener equals `currentTarget`, which is a small argument for `function` handlers. An arrow handler has no such binding, so `currentTarget` is the explicit way to get it either way.',
      'Related properties worth knowing: `relatedTarget` (the element being left or entered on `mouseover`/`focusin`), and `composedPath()`, which gives the full path including nodes inside a shadow root that `target` deliberately hides.',
    ],
    keyPoints: [
      '`target` = where it originated; `currentTarget` = where the listener is attached',
      'They differ only when the event has propagated',
      'Delegation should use `target.closest(selector)`, not either one raw',
      '`currentTarget` is `null` after dispatch ends — capture it synchronously',
      '`this` in a non-arrow listener equals `currentTarget`',
      '`composedPath()` reveals the path through shadow DOM',
    ],
    commonMistakes: [
      'Using `currentTarget` in a delegated handler and always getting the container.',
      'Reading `currentTarget` after an `await` inside the handler.',
    ],
    followUps: ['Why does `closest` make delegation robust?', 'Why is `currentTarget` null after dispatch?'],
  },

  {
    id: 'iv-bp-prevent-vs-stop',
    question: 'Compare `preventDefault`, `stopPropagation` and `stopImmediatePropagation`.',
    topic: BROWSER,
    level: L.JUNIOR_PLUS,
    kind: K.BROWSER,
    topicIds: ['events'],
    relatedLessons: ['l-m19-03'],
    shortAnswer:
      '`preventDefault` cancels the browser\'s built-in action but lets the event keep travelling. `stopPropagation` stops the event reaching further elements but lets the default action happen. `stopImmediatePropagation` additionally stops other listeners on the **same** element. They are independent — neither implies the other.',
    deepAnswer: [
      '**`preventDefault()`** cancels the default behaviour: navigating a link, submitting a form, checking a checkbox, showing the context menu. The event continues to propagate normally, so other listeners still run and can still see that it was cancelled via `event.defaultPrevented`.',
      '**`stopPropagation()`** halts travel through the tree. Ancestor listeners never fire. The default action still happens — a link with only `stopPropagation` still navigates, which surprises people.',
      '**`stopImmediatePropagation()`** does that and also prevents any remaining listeners on the same element from running, in registration order. Useful when one handler must be authoritative; also a good way to create bugs that are very hard to find, since another team\'s listener simply stops firing with no error.',
      'The default-action nuance: `preventDefault` only works if the event is cancelable (`event.cancelable`). `scroll` is not cancelable, and a `touchstart` listener registered as `{ passive: true }` cannot cancel — the browser assumes it will not, which is what lets scrolling start without waiting for JavaScript. Chrome makes wheel and touch listeners on the document passive by default for that reason.',
      '`stopPropagation` is overused. It is a local fix with global consequences: any delegated handler higher up — analytics, a click-outside-to-close dropdown, a framework\'s root listener — silently stops receiving events. Prefer a condition in the outer handler over stopping the event at the source.',
      'Two more details: returning `false` from a jQuery handler did both `preventDefault` and `stopPropagation`, which is a common source of confusion when people carry the habit into plain DOM code, where returning `false` only cancels the default in inline `on*` attributes. And a form\'s submit handler must `preventDefault` **before** any `await`, because the default action is decided synchronously during dispatch.',
    ],
    keyPoints: [
      '`preventDefault`: cancel the built-in action, keep propagating',
      '`stopPropagation`: stop travelling, keep the default action',
      '`stopImmediatePropagation`: also stop other listeners on the same element',
      'Only cancelable events can be prevented; passive listeners cannot cancel',
      '`stopPropagation` silently breaks delegated handlers higher up',
      'Call `preventDefault` before any `await` in the handler',
    ],
    commonMistakes: [
      'Believing `stopPropagation` prevents the default action.',
      'Reaching for `stopPropagation` instead of a condition in the outer handler.',
    ],
    followUps: ['Why can a passive listener not call `preventDefault`?', 'What breaks when you stop propagation?'],
  },

  {
    id: 'iv-bp-live-collections',
    question: 'What is a live collection, and why does looping over one sometimes skip elements?',
    topic: BROWSER,
    level: L.JUNIOR_PLUS,
    kind: K.BROWSER,
    topicIds: ['dom', 'dom-manipulation'],
    relatedLessons: ['l-m18-06'],
    shortAnswer:
      '`getElementsByClassName` and `getElementsByTagName` return **live** `HTMLCollection`s that update as the DOM changes. Removing elements while iterating forwards shrinks the collection underneath the loop, so elements get skipped. `querySelectorAll` returns a static `NodeList` and does not have this problem.',
    deepAnswer: [
      'A live collection is a query, not a snapshot. It re-reflects the document whenever it is read, so adding or removing matching elements changes its `length` immediately.',
      'The classic failure:\n\n```js\nconst items = document.getElementsByClassName("row");\nfor (let i = 0; i < items.length; i++) {\n  items[i].remove(); // collection shrinks; i still increments\n}\n```\n\nEvery other row survives — the same shape as the `splice`-while-iterating bug, for the same reason.',
      'The fixes: take a snapshot with `[...items]` or `Array.from(items)` before looping; iterate backwards; or use `querySelectorAll`, which returns a static `NodeList` that is unaffected by later DOM changes.',
      '`NodeList` from `querySelectorAll` has `forEach` but not `map`, `filter` or `reduce` — it is array-**like**, not an array. Spread it when you want array methods. `HTMLCollection` has no iteration methods at all, only indexing and `length`, though it is iterable with `for...of`.',
      'Liveness is occasionally useful — `document.forms`, `document.images` and `element.children` are live, and a live collection is genuinely convenient when you want a continuously accurate count. But as a default it surprises people, which is why `querySelectorAll` is the modern choice.',
      'Performance is the other side: `getElementById` and `getElementsByClassName` are highly optimised, while `querySelectorAll` parses a selector and builds a snapshot. In a hot loop that is measurable — but the correct move is to hoist the query out of the loop rather than to choose the API by micro-benchmark.',
    ],
    keyPoints: [
      '`getElementsBy*` return live `HTMLCollection`s; `querySelectorAll` returns a static `NodeList`',
      'Removing while iterating a live collection skips elements',
      'Snapshot with `[...items]`, iterate backwards, or use `querySelectorAll`',
      '`NodeList` has `forEach` only; `HTMLCollection` has no array methods',
      '`document.forms`, `element.children` are live too',
    ],
    commonMistakes: [
      'Assuming every DOM query returns a static list.',
      'Calling `.map` on a `NodeList` without spreading it first.',
    ],
    followUps: ['Which built-in collections are live?', 'Why does `NodeList` have `forEach` but not `map`?'],
  },

  {
    id: 'iv-bp-attributes-vs-properties',
    question: 'What is the difference between an HTML attribute and a DOM property?',
    topic: BROWSER,
    level: L.JUNIOR_PLUS,
    kind: K.BROWSER,
    topicIds: ['dom', 'forms'],
    relatedLessons: ['l-m17-04'],
    shortAnswer:
      'Attributes are the values written in the markup and are always strings; properties live on the DOM object and have real types. They are initialised from attributes, but for form controls the property tracks the **current** state while the attribute keeps the original — which is why `value` and `checked` behave the way they do.',
    deepAnswer: [
      'At parse time the browser creates a property for each recognised attribute. `<input value="ada">` gives `input.getAttribute("value") === "ada"` and `input.value === "ada"`.',
      'Once the user types, they diverge: `input.value` becomes what is in the field now, while `getAttribute("value")` still returns `"ada"` — it is the **default** value, which is exactly what a form reset restores. The same holds for `checked` (property = current state, attribute = default) and `selected`.',
      'So for reading what the user actually entered, always use the **property**. Reading `getAttribute("value")` is the classic bug behind "my form always submits the initial value".',
      'Types differ too. Properties are properly typed: `input.checked` is a boolean, `a.href` is the resolved absolute URL, `input.valueAsNumber` is a number. Attributes are strings, so `getAttribute("checked")` returns `""` for a present boolean attribute and `null` when absent — never `false`.',
      'Names occasionally differ where the attribute collides with a reserved word: the `class` attribute is the `className` property, and `for` on a label is `htmlFor`. `classList` is the better API for classes in either case.',
      'Custom attributes have no matching property, which is why `data-*` exists: `<li data-id="7">` is readable as `li.dataset.id`, with the kebab-case name converted to camelCase. That is the right channel for attaching your own data to an element.',
      'A useful consequence: because `href` resolves relatively, `link.href` gives an absolute URL while `link.getAttribute("href")` gives exactly the string in the markup. Which one you want depends on whether you are comparing or reproducing.',
    ],
    keyPoints: [
      'Attributes are markup strings; properties are typed values on the DOM object',
      'For form controls the property is current state, the attribute is the default',
      'Read user input from the property, never from `getAttribute`',
      '`getAttribute("checked")` returns `""` or `null`, never a boolean',
      '`class` → `className`, `for` → `htmlFor`; prefer `classList`',
      'Custom data belongs in `data-*`, read via `dataset`',
    ],
    commonMistakes: [
      'Reading form state with `getAttribute("value")`.',
      'Treating a boolean attribute\'s string value as a boolean.',
    ],
    followUps: ['Why does a form reset restore the attribute value?', 'Why does `link.href` differ from its attribute?'],
  },

  {
    id: 'iv-bp-observers',
    question: 'What do `IntersectionObserver`, `MutationObserver` and `ResizeObserver` do, and when would you use each?',
    topic: BROWSER,
    level: L.INTERMEDIATE,
    kind: K.BROWSER,
    topicIds: ['web-apis', 'performance', 'dom'],
    relatedLessons: ['l-m27-04'],
    shortAnswer:
      'They are push-based replacements for polling. `IntersectionObserver` reports when an element enters or leaves the viewport, `ResizeObserver` reports element size changes, and `MutationObserver` reports DOM changes. All three run off the main thread\'s hot path and avoid the forced layout that manual polling causes.',
    deepAnswer: [
      '**`IntersectionObserver`** — lazy-loading images, infinite scroll, "is this ad visible", triggering animations on scroll into view, and sticky-header state. The pre-observer approach was a scroll listener calling `getBoundingClientRect()` on every event, which forces synchronous layout dozens of times a second. The observer does the work asynchronously in the browser\'s own layout pass.\n\n```js\nconst io = new IntersectionObserver((entries) => {\n  for (const entry of entries) {\n    if (entry.isIntersecting) load(entry.target);\n  }\n}, { rootMargin: "200px" });\n```\n\n`rootMargin` is what makes lazy loading feel instant — start loading before the element is actually visible.',
      '**`ResizeObserver`** — an element changing size for any reason, not just a window resize. A `window.resize` listener misses size changes caused by content, a sibling collapsing, or a CSS container query, which is exactly why this API exists. It is the correct tool for responsive components that must react to their own box rather than the viewport.',
      '**`MutationObserver`** — reacting to DOM changes you do not control: a third-party widget injecting content, or an integration with code you cannot modify. In your own application it is usually a smell, because you already know when you changed the DOM. It is also the API that replaced the deprecated and catastrophically slow mutation events.',
      'All three batch their callbacks and deliver them asynchronously, so a burst of changes produces one callback with many entries rather than one callback each. That batching is most of the performance benefit.',
      'All three need cleanup: `disconnect()` when the component goes away, or `unobserve(el)` for a single target. An observer holding element references is the same leak shape as an unremoved listener.',
      'A detail people miss: `IntersectionObserver` fires once on observe with the current state, so you get an initial reading without a scroll. And `ResizeObserver` callbacks that resize the observed element can loop — the browser detects this and logs "loop limit exceeded" rather than hanging, but the design is still wrong.',
    ],
    keyPoints: [
      'Push-based replacements for polling; no forced synchronous layout',
      '`IntersectionObserver`: visibility, lazy loading, infinite scroll — use `rootMargin`',
      '`ResizeObserver`: element size from any cause, which `window.resize` misses',
      '`MutationObserver`: DOM you do not control; a smell inside your own app',
      'Callbacks are batched and asynchronous',
      'Always `disconnect()`/`unobserve` — observers retain their targets',
    ],
    commonMistakes: [
      'Using a scroll listener plus `getBoundingClientRect` where an observer applies.',
      'Using `MutationObserver` to react to your own DOM updates.',
    ],
    followUps: ['Why does `window.resize` miss element size changes?', 'What does `rootMargin` buy you?'],
  },

  {
    id: 'iv-bp-custom-events',
    question: 'How would you let two unrelated components communicate without a framework?',
    topic: BROWSER,
    level: L.INTERMEDIATE,
    kind: K.BROWSER,
    topicIds: ['events', 'design-patterns'],
    relatedLessons: ['l-m19-06'],
    shortAnswer:
      'Dispatch a `CustomEvent` that carries data in `detail` and let interested parties listen. The DOM already provides a pub/sub system with bubbling, so a shared element — or a plain `EventTarget` used as a bus — avoids importing one component into the other.',
    deepAnswer: [
      'The mechanism:\n\n```js\n// publisher\nel.dispatchEvent(new CustomEvent("cart:add", {\n  detail: { id, quantity },\n  bubbles: true,\n}));\n\n// subscriber, anywhere up the tree\ndocument.addEventListener("cart:add", (event) => {\n  update(event.detail);\n});\n```\n\n`bubbles: true` is not the default for custom events, and forgetting it is the usual reason "my listener never fires".',
      '`detail` is the only place data belongs — it is the property the constructor is designed to carry, and it can hold any value including objects.',
      'Namespacing the event type (`cart:add`, not `add`) prevents collisions with built-in events and with other features, and makes the source obvious when reading a listener.',
      'For components with no common ancestor, a standalone bus works and needs no library: `const bus = new EventTarget()` supports `addEventListener` and `dispatchEvent` exactly like a DOM node, without being attached to the document.',
      'The tradeoff to state honestly: events decouple the publisher from the subscriber, which is the point — but they also make control flow implicit. With more than a handful, "what happens when I click this?" becomes a search across the codebase. That is the same critique as a global event bus in any architecture.',
      'When to prefer something else: parent-to-child is a direct method call or a property; child-to-parent is a callback passed in; genuinely shared application state belongs in a store, not in a stream of events. Custom events fit best for genuinely broadcast notifications with unknown or variable subscribers.',
      'Two platform details: `dispatchEvent` is **synchronous** — every listener runs before the call returns, so a slow listener blocks the publisher. And for a custom event to escape a shadow root it needs `composed: true` as well as `bubbles: true`.',
    ],
    keyPoints: [
      '`CustomEvent` with data in `detail`; `bubbles: true` is not the default',
      'Namespace the type to avoid collisions',
      '`new EventTarget()` is a dependency-free bus for unrelated components',
      'Events decouple but make control flow implicit — use them sparingly',
      'Prefer props/callbacks for parent-child, a store for shared state',
      '`dispatchEvent` is synchronous; `composed: true` to cross a shadow boundary',
    ],
    commonMistakes: [
      'Omitting `bubbles: true` and wondering why nothing listens.',
      'Using an event bus for state that should live in a store.',
    ],
    followUps: ['Why is `dispatchEvent` being synchronous a hazard?', 'When is a callback prop better than an event?'],
  },

  {
    id: 'iv-bp-classlist',
    question: 'How do you change how an element looks from JavaScript, and which approach do you prefer?',
    topic: BROWSER,
    level: L.JUNIOR,
    kind: K.BROWSER,
    topicIds: ['dom-manipulation'],
    relatedLessons: ['l-m17-05', 'l-m17-06'],
    shortAnswer:
      'Toggle a class with `classList` and keep the styling in CSS. Inline styles via `element.style` are for values that are genuinely dynamic and computed — a position, a percentage width — not for appearance that could be expressed as a state.',
    deepAnswer: [
      '`classList` gives `add`, `remove`, `toggle`, `contains` and `replace`, each operating on one class without disturbing the others. `element.className = "active"` replaces the entire attribute and silently destroys classes other code relies on.',
      '`classList.toggle("open", isOpen)` with the second argument is worth knowing: it forces the class on or off rather than flipping it, which removes a whole category of state-drift bugs where the DOM and your variable disagree.',
      'Keeping appearance in CSS means media queries, `prefers-reduced-motion`, `prefers-color-scheme`, hover and focus states, and the design system\'s tokens all keep working. Inline styles bypass all of it and are difficult to override because of their specificity.',
      'Inline styles are right when the value cannot be known in advance: `el.style.transform = "translateX(" + x + "px)"` for a drag, or a computed bar width. Even then, a CSS custom property is often cleaner — `el.style.setProperty("--progress", pct)` — because the styling stays in the stylesheet and JavaScript only supplies a number.',
      'For state, prefer semantic attributes over presentational classes where one exists: `aria-expanded`, `aria-selected`, `disabled`, `hidden`, or a `data-state`. CSS can select on them (`[aria-expanded="true"]`), and assistive technology gets the state for free instead of it being encoded only in a class name.',
      'The performance footnote: batch class changes and avoid interleaving them with geometry reads, since each write invalidates layout and the next read forces a recalculation.',
    ],
    keyPoints: [
      '`classList` for state; keep the appearance in CSS',
      '`className =` replaces every class — avoid it',
      '`classList.toggle(name, force)` sets rather than flips',
      'Inline styles for genuinely computed values; prefer CSS custom properties',
      'Drive styling from `aria-*`/`data-*` state where one exists',
      'Batch writes; do not interleave them with geometry reads',
    ],
    commonMistakes: [
      'Assigning `className` and wiping unrelated classes.',
      'Encoding state only in a class name, leaving assistive technology unaware.',
    ],
    followUps: ['Why is `[aria-expanded="true"]` better than an `.open` class?', 'When is an inline style unavoidable?'],
  },

  {
    id: 'iv-bp-modal-focus',
    question: 'What does a modal dialog need to get right beyond showing and hiding?',
    topic: BROWSER,
    level: L.INTERMEDIATE,
    kind: K.BROWSER,
    topicIds: ['dom', 'events', 'forms'],
    relatedLessons: ['l-m19-05'],
    shortAnswer:
      'Focus management and keyboard behaviour: move focus in on open, trap it inside while open, close on Escape, return focus to the trigger on close, and hide the rest of the page from assistive technology. `<dialog>` with `showModal()` gives most of this for free.',
    deepAnswer: [
      'A visually-correct modal that ignores focus is unusable with a keyboard or a screen reader — the user tabs into content behind the overlay that they cannot see, with no way back.',
      'The checklist: move focus to the dialog (or its first control) on open; keep Tab and Shift+Tab cycling within it; close on Escape; restore focus to the element that opened it; prevent the background from scrolling; and mark the dialog with `role="dialog"` and `aria-modal="true"`, labelled by its heading.',
      '`<dialog>` with `showModal()` implements almost all of it natively — the top layer, the `::backdrop`, Escape-to-close, inertness of the rest of the page, and focus containment. Using it is the correct answer in a modern codebase; hand-rolling is worth knowing mainly because you will meet hand-rolled ones.',
      'Returning focus is the step most often missed, and the most disorienting when absent. Capture `document.activeElement` before opening and restore it after closing — otherwise focus falls back to `<body>` and keyboard users start again from the top of the page.',
      'The `inert` attribute is the modern way to make everything outside the dialog unfocusable and hidden from assistive technology, replacing the older technique of setting `aria-hidden` on siblings and stripping tabindex.',
      'Closing on a backdrop click needs care: check that the click actually landed on the backdrop rather than bubbling up from inside, and do not close on a drag that started inside and ended outside.',
      'Escape must also be handled at the right level. A listener on `document` competes with other components; scoping it to the dialog, and removing it on close (or using an `AbortController` signal), avoids a stack of stale Escape handlers.',
    ],
    keyPoints: [
      'Move focus in, trap it, restore it to the trigger on close',
      'Escape closes; the background does not scroll',
      '`role="dialog"`, `aria-modal="true"`, labelled by its heading',
      '`<dialog>` + `showModal()` provides most of this natively',
      '`inert` hides the rest of the page from focus and assistive technology',
      'Scope the Escape listener and remove it on close',
    ],
    commonMistakes: [
      'Trapping focus but never returning it to the trigger.',
      'Closing on any click that reaches the backdrop element, including bubbled ones.',
    ],
    followUps: ['What does `inert` replace?', 'Why is restoring focus so important?'],
  },

  {
    id: 'iv-bp-critical-path',
    question: 'What happens between the browser receiving HTML and the first pixels appearing?',
    topic: BROWSER,
    level: L.INTERMEDIATE,
    kind: K.BROWSER,
    topicIds: ['js-runtime', 'performance', 'dom'],
    relatedLessons: ['l-m43-03'],
    shortAnswer:
      'Parse HTML into the DOM, parse CSS into the CSSOM, combine them into a render tree, compute layout (geometry), paint (pixels), and composite layers. Scripts can block parsing and stylesheets block rendering, which is why script and style placement dominates first-paint time.',
    deepAnswer: [
      '**Parse** — the HTML is tokenised into the DOM incrementally, so the browser can start rendering before the document has fully arrived. A preload scanner runs ahead of the parser to start fetching subresources early.',
      '**CSSOM** — stylesheets are parsed into a second tree. CSS is **render-blocking** by design: painting with incomplete styles would cause a flash of unstyled content, so the browser waits. This is why a stylesheet in `<head>` delays first paint and why inlining the critical subset helps.',
      '**Render tree** — DOM plus CSSOM, containing only what will be displayed. `display: none` nodes are excluded entirely; `visibility: hidden` nodes are included, because they still occupy space.',
      '**Layout (reflow)** — computing the geometry of every box. Cost scales with the number of elements, which is why very large DOMs are slow independently of any JavaScript.',
      '**Paint** — filling in pixels, potentially onto several layers. **Composite** — assembling the layers, which the GPU can do. This is why animating `transform` and `opacity` is cheap: they skip layout and paint and only require a recomposite.',
      'Where JavaScript intervenes: a synchronous `<script>` blocks parsing, and because a script might query styles, it also waits for any pending stylesheet — so a stylesheet above a script blocks that script too. `defer` and `type="module"` avoid the parser block entirely.',
      'The practical levers follow directly from the sequence: inline critical CSS and defer the rest, `defer` your scripts, preload the LCP image, set explicit dimensions on images to avoid layout shift, and keep the DOM small. Each maps to a stage above rather than being a folk remedy.',
    ],
    keyPoints: [
      'DOM + CSSOM → render tree → layout → paint → composite',
      'HTML parsing is incremental; a preload scanner fetches ahead',
      'CSS is render-blocking by design to prevent unstyled flashes',
      'A synchronous script blocks parsing and waits on pending stylesheets',
      '`transform`/`opacity` changes skip layout and paint',
      'Inline critical CSS, defer scripts, preload the LCP image, size your images',
    ],
    commonMistakes: [
      'Believing `display: none` and `visibility: hidden` are equivalent to the render tree.',
      'Not knowing that a stylesheet can delay a script.',
    ],
    followUps: ['Why does a stylesheet block a script below it?', 'Why is compositing cheaper than painting?'],
  },

  /* ----------------------------------------------------------------- async */
  {
    id: 'iv-as-timer-accuracy',
    question: 'Why does `setTimeout(fn, 100)` not run exactly 100ms later?',
    topic: ASYNC,
    level: L.JUNIOR,
    kind: K.ASYNC,
    topicIds: ['event-loop', 'async-foundations'],
    relatedLessons: ['l-m23-02'],
    shortAnswer:
      'The delay is a **minimum**, not a guarantee. After it elapses the callback is queued, and it only runs when the call stack is empty and the event loop reaches it — so any long-running synchronous work delays it further. Browsers also clamp nested timers and throttle background tabs.',
    deepAnswer: [
      '`setTimeout` schedules; it does not preempt. Once the timer expires the callback becomes a macrotask, and it waits behind whatever is already running or queued. A 200ms synchronous loop means a 100ms timer fires at roughly 200ms.',
      'The microtask queue drains completely before any macrotask, so a burst of promise reactions also delays a timer.',
      '**Clamping**: after about five levels of nesting, browsers enforce a minimum of roughly 4ms, so `setTimeout(fn, 0)` in a recursive chain is not zero. Background tabs are throttled much harder — often to once per second, and in some cases far less — which is why a timer-based counter drifts badly if the user switches away.',
      'Because of all that, never accumulate time by counting timer fires. Store a target timestamp and compute the remaining time from `Date.now()` on each tick; the display then stays correct regardless of how much drift occurred.',
      'For animation, `requestAnimationFrame` is the right tool — it runs before the next paint, aligns with the display refresh rate, and pauses entirely in a background tab. Using a timer for animation produces uneven motion because timer fires and frames are not synchronised.',
      'For precise elapsed-time measurement, use `performance.now()`: it is monotonic, sub-millisecond, and unaffected by the system clock being adjusted mid-measurement, which `Date.now()` is not.',
      'The general point worth making in an interview: timing in a single-threaded environment is cooperative. A timer is a request to be run soon after a deadline, not an interrupt — nothing preempts running JavaScript.',
    ],
    keyPoints: [
      'The delay is a minimum; the callback queues and waits for an empty stack',
      'Long synchronous work and microtask bursts both delay timers',
      'Nested timers are clamped to ~4ms; background tabs are throttled hard',
      'Derive elapsed time from a timestamp instead of counting fires',
      '`requestAnimationFrame` for animation; `performance.now()` for measurement',
      'Nothing preempts running JavaScript — timers are cooperative',
    ],
    commonMistakes: [
      'Treating the delay as a guarantee.',
      'Accumulating a countdown by decrementing on each tick.',
    ],
    followUps: ['Why is `performance.now()` better for measurement?', 'What happens to timers in a background tab?'],
  },

  {
    id: 'iv-as-unhandled-rejection',
    question: 'What is an unhandled promise rejection, and what should you do about it?',
    topic: ASYNC,
    level: L.INTERMEDIATE,
    kind: K.ASYNC,
    topicIds: ['promises', 'errors'],
    relatedLessons: ['l-m24-03'],
    shortAnswer:
      'A promise that rejects with no rejection handler attached by the time the microtask queue drains. The browser fires `unhandledrejection` and logs it; Node terminates the process by default. The fix is that every promise needs an owner that awaits it, catches it, or returns it to someone who will.',
    deepAnswer: [
      'The runtime tracks whether a rejected promise has a handler. If none is attached by the end of the current microtask checkpoint, it reports the rejection. Attaching a handler later still works functionally, but the warning has already fired.',
      'The usual sources: calling an `async` function without awaiting or catching it ("floating promise"); a `.then` chain with no terminal `.catch`; a `forEach` with an `async` callback, which discards every promise it creates; and a promise created inside a `try`/`catch` but not awaited there, so the `catch` never sees it.',
      'Node exits on an unhandled rejection by default, which is deliberate: an unknown failed operation means the process is in an undefined state. Browsers keep going but surface it in the console and on `window.onunhandledrejection`.',
      'A global handler is for **reporting**, not for handling:\n\n```js\nwindow.addEventListener("unhandledrejection", (event) => {\n  report(event.reason);\n  event.preventDefault(); // suppress the default console error, if you have reported it\n});\n```\n\nIt catches the failures your per-call handling missed, which is exactly what makes it valuable in production monitoring — and it must not become the place where errors are quietly swallowed.',
      'Deliberate fire-and-forget should be explicit. If you truly do not care about the result, write `void doThing().catch(reportOnly)` so the intent is visible and the rejection is still observed. Silence is what makes these bugs invisible.',
      '`@typescript-eslint/no-floating-promises` catches the majority of these statically, and it is one of the highest-value lint rules for async-heavy code.',
      'The counterpart worth knowing: `rejectionhandled` fires when a handler is attached to an already-reported rejection, which lets monitoring retract a false positive.',
    ],
    keyPoints: [
      'A rejection with no handler by the end of the microtask checkpoint',
      'Node exits by default; browsers report on `unhandledrejection`',
      'Sources: floating async calls, chains with no `.catch`, `forEach` with `async`',
      'A global handler is for reporting, never for silently handling',
      'Make fire-and-forget explicit with `void ...catch(report)`',
      'Lint for floating promises',
    ],
    commonMistakes: [
      'Using the global handler to suppress errors instead of reporting them.',
      'Assuming a `try`/`catch` covers a promise created but not awaited inside it.',
    ],
    followUps: ['Why does Node exit by default?', 'What does `rejectionhandled` tell you?'],
  },

  {
    id: 'iv-as-abort',
    question: 'How do you cancel an asynchronous operation that is already in flight?',
    topic: ASYNC,
    level: L.INTERMEDIATE,
    kind: K.ASYNC,
    topicIds: ['async-await', 'http', 'web-apis'],
    relatedLessons: ['l-m26-05'],
    shortAnswer:
      'A promise itself cannot be cancelled — it is a value representing a result, and it will settle. Cancellation is a property of the **operation**, and the platform mechanism is `AbortController`: pass its `signal` to `fetch` (or your own async function), call `abort()`, and handle the resulting `AbortError`.',
    deepAnswer: [
      'The distinction matters conceptually. A promise has two outcomes and no cancel; what you cancel is the work behind it, and the promise then rejects with an `AbortError` to tell you so.',
      'The pattern:\n\n```js\nconst controller = new AbortController();\n\ntry {\n  const res = await fetch(url, { signal: controller.signal });\n  render(await res.json());\n} catch (err) {\n  if (err.name === "AbortError") return; // expected, not a failure\n  throw err;\n}\n\n// elsewhere\ncontroller.abort();\n```\n\nSwallowing `AbortError` specifically — and rethrowing everything else — is the part people get wrong, usually by catching everything and treating a real failure as a cancellation.',
      'A controller is single-use: after `abort()` its signal stays aborted, so each new operation needs a fresh controller.',
      'The same signal works beyond `fetch`. `addEventListener(type, fn, { signal })` removes the listener on abort, which is the cleanest teardown mechanism available. And your own functions can accept a signal:\n\n```js\nfunction sleep(ms, { signal } = {}) {\n  return new Promise((resolve, reject) => {\n    if (signal?.aborted) return reject(signal.reason);\n    const id = setTimeout(resolve, ms);\n    signal?.addEventListener("abort", () => {\n      clearTimeout(id);\n      reject(signal.reason);\n    }, { once: true });\n  });\n}\n```\n\nNote the check for already-aborted before subscribing — otherwise a signal aborted before the call never rejects.',
      '`AbortSignal.timeout(ms)` builds a signal that aborts itself, and `AbortSignal.any([a, b])` combines several, so "cancel on user navigation **or** after 5 seconds" needs no manual plumbing.',
      'Where cancellation matters: a search-as-you-type where superseded requests should stop; a component unmounting mid-request; and a long upload the user abandons. Aborting frees the connection and stops the server doing work nobody wants — and it also prevents the stale-response race, since an aborted request cannot deliver a result.',
      'What it does not do: aborting a `fetch` does not undo a server-side effect that already happened. For a mutation, the server may well have completed the write.',
    ],
    keyPoints: [
      'Promises are not cancellable; operations are',
      '`AbortController` + `signal`; handle `AbortError` and rethrow everything else',
      'A controller is single-use — create a fresh one per operation',
      'Signals also remove event listeners and can be threaded into your own functions',
      'Check `signal.aborted` before subscribing to `abort`',
      '`AbortSignal.timeout` and `AbortSignal.any` compose cancellation',
      'Aborting does not undo a server-side effect',
    ],
    commonMistakes: [
      'Catching everything and treating a real error as a cancellation.',
      'Reusing one controller for successive requests.',
    ],
    followUps: ['Why is a controller single-use?', 'What does `{ signal }` do for `addEventListener`?'],
  },

  {
    id: 'iv-as-thenable',
    question: 'What happens when you `await` something that is not a promise?',
    topic: ASYNC,
    level: L.JUNIOR_PLUS,
    kind: K.ASYNC,
    topicIds: ['promises', 'async-await'],
    relatedLessons: ['l-m25-01'],
    shortAnswer:
      'It still works, and it still defers. `await` wraps the value with `Promise.resolve` semantics, so `await 42` yields `42` — but only after suspending the function and scheduling the continuation as a microtask. Anything with a callable `then` is treated as a promise.',
    deepAnswer: [
      '`await x` where `x` is a plain value resolves to `x`. The important part is that it is **not** a no-op: the function suspends and the rest of the body runs as a microtask, so code after the call site executes first.',
      'This makes `await` safe in generic code — a function that may or may not return a promise can be awaited unconditionally, without a `typeof x.then === "function"` check.',
      'A **thenable** is any object with a callable `then` method. The promise machinery duck-types: it calls `then(resolve, reject)` and adopts whatever that does. That is how promises from different libraries, or from another realm such as an iframe, interoperate with native ones. It is also why `instanceof Promise` is the wrong check — `typeof x?.then === "function"` is what the specification itself uses.',
      'The sharp edge: an object that happens to have a `then` property becomes accidentally awaitable. Returning `{ then: "later" }` is fine because it is not callable, but a data object with a callable `then` will be treated as a promise and will hang or misbehave. It is rare, and memorable when it happens.',
      '`await` on a rejected promise throws at that line, which is what makes `try`/`catch` work around asynchronous code — the mechanism is the same as a synchronous throw from the resumed continuation.',
      'One micro-detail sometimes asked: awaiting a native promise takes fewer microtask ticks than awaiting a thenable, because a thenable must be assimilated through an extra job. It affects ordering puzzles, essentially never real code.',
    ],
    keyPoints: [
      '`await` on a non-promise yields the value but still defers to a microtask',
      'Safe to await anything, which helps generic code',
      'A thenable is any object with a callable `then` — duck-typed, not `instanceof`',
      'This is how cross-realm and library promises interoperate',
      'An accidental callable `then` makes an object awaitable',
      '`await` on a rejection throws at that line, enabling `try`/`catch`',
    ],
    commonMistakes: [
      'Guarding with `instanceof Promise` and rejecting valid thenables.',
      'Assuming `await` on a plain value is synchronous.',
    ],
    followUps: ['Why is `instanceof Promise` the wrong check?', 'What is a realm, in this context?'],
  },

  {
    id: 'iv-as-setinterval-vs-recursive',
    question: 'Compare `setInterval` with a recursive `setTimeout` for repeated work.',
    topic: ASYNC,
    level: L.JUNIOR_PLUS,
    kind: K.ASYNC,
    topicIds: ['async-foundations', 'event-loop'],
    relatedLessons: ['l-m23-02'],
    shortAnswer:
      '`setInterval` schedules by wall clock regardless of how long the work takes, so slow callbacks can queue up back to back. A recursive `setTimeout` schedules the next run only after the current one finishes, which guarantees a real gap between executions. For anything asynchronous, the recursive version is almost always correct.',
    deepAnswer: [
      '`setInterval(fn, 1000)` asks for a callback every second. If `fn` takes 1.5 seconds, the runtime does not skip — the callbacks queue, and once the stack clears they can run one immediately after another with no gap. The intent ("do this every second") becomes "do this constantly".',
      'This is much worse when the callback is asynchronous. `setInterval(() => fetch(url), 1000)` starts a request every second regardless of whether the previous one has returned. On a slow connection you accumulate overlapping requests, and responses can arrive out of order.',
      'The recursive alternative:\n\n```js\nlet timer;\n\nasync function poll() {\n  try {\n    await refresh();\n  } finally {\n    timer = setTimeout(poll, 1000);\n  }\n}\n\npoll();\n// stop with clearTimeout(timer)\n```\n\nThe next run is scheduled only after the current one settles, so there is always a real interval between completions and never more than one in flight. The `finally` ensures a failure does not silently stop the loop.',
      '`setInterval` remains fine for cheap synchronous work — updating a clock display, a progress animation — where the callback cannot outrun its period.',
      'Neither is accurate over time: both drift, and both are throttled in background tabs. Derive displayed times from a timestamp rather than counting iterations.',
      'For polling specifically, the production answer adds more: back off when the tab is hidden (`document.visibilityState`), back off after repeated failures, and stop entirely when the component unmounts. And consider whether polling is the right mechanism at all — server-sent events or a WebSocket push the data instead of asking repeatedly.',
      'Whichever you use, keep the handle and clear it. An interval that outlives its component is one of the most common leaks in single-page applications.',
    ],
    keyPoints: [
      '`setInterval` schedules by clock and can queue callbacks back to back',
      'With async work it starts overlapping operations',
      'Recursive `setTimeout` schedules after completion — a guaranteed gap, one in flight',
      'Use `finally` so a failure does not stop the loop',
      '`setInterval` is fine for cheap synchronous updates',
      'Back off when hidden or failing; consider SSE/WebSocket instead of polling',
      'Always keep the handle and clear it on teardown',
    ],
    commonMistakes: [
      'Polling an API with `setInterval` and creating overlapping requests.',
      'Scheduling the next run before the current work completes.',
    ],
    followUps: ['Why does the `finally` matter in the recursive version?', 'When is polling the wrong mechanism entirely?'],
  },

  {
    id: 'iv-as-ui-states',
    question: 'What states does a UI that loads data need to handle?',
    topic: ASYNC,
    level: L.JUNIOR_PLUS,
    kind: K.ASYNC,
    topicIds: ['http', 'clean-code', 'dom'],
    relatedLessons: ['l-m26-05'],
    shortAnswer:
      'At minimum idle, loading, success, empty and error — and "empty" is the one most often forgotten, because a successful response with zero results is not the same as a failure. Beyond that: refetching while showing stale data, and partial failure.',
    deepAnswer: [
      '**Idle** — nothing requested yet. **Loading** — a request is in flight, with a skeleton or spinner. **Success with data** — render it. **Success with no data** — an explicit empty state explaining what would appear here and, ideally, how to get some. **Error** — what failed and a way to retry.',
      'Conflating empty with error is the classic bug: a user with no orders sees "Something went wrong" and files a support ticket. Conflating empty with loading is the other half — a spinner that never resolves because the list is simply empty.',
      'Modelling matters. Independent booleans (`isLoading`, `hasError`, `isEmpty`) permit impossible combinations — loading and error at once — and every render has to defend against them. A single discriminated status (`"idle" | "loading" | "success" | "error"`) makes the impossible states unrepresentable, which is the point.',
      'Refetching is a separate state from initial loading. Replacing a populated list with a spinner on every refresh makes the UI flicker and feel slower than it is; keeping the stale data visible with a subtle indicator is what SWR-style caching does and why it feels fast.',
      'Errors should distinguish what the user can act on. Offline and a 500 are both "try again"; a 403 is "you do not have access"; a 404 is a not-found state; a validation error belongs next to the field. One generic message for all of them wastes the information the server sent.',
      'Two practical details: guard against showing a spinner for a 50ms response by delaying it slightly, which avoids a distracting flash; and make sure the states are announced to assistive technology with a live region, since a visual-only spinner tells a screen-reader user nothing.',
      'Finally, the race: after any `await`, check the result is still the one wanted before rendering. A component that unmounted, or a newer request that superseded this one, must not write to the DOM.',
    ],
    keyPoints: [
      'Idle, loading, success-with-data, success-empty, error — empty is not error',
      'Model one status value, not independent booleans',
      'Refetching is distinct from initial load — keep stale data visible',
      'Differentiate errors by what the user can do about them',
      'Delay the spinner slightly; announce state changes to assistive technology',
      'Re-check relevance after `await` before rendering',
    ],
    commonMistakes: [
      'Showing an error when the result is simply empty.',
      'Using independent booleans that allow impossible combinations.',
    ],
    followUps: ['Why is refetching a separate state?', 'How do you announce a loading state accessibly?'],
  },

  {
    id: 'iv-as-top-level-await',
    question: 'Can you use `await` at the top level of a file? What changed with modules?',
    topic: ASYNC,
    level: L.INTERMEDIATE,
    kind: K.ASYNC,
    topicIds: ['modules', 'async-await'],
    relatedLessons: ['l-m28-03'],
    shortAnswer:
      'Only in an ES module. Modules have an asynchronous evaluation model, so top-level `await` is legal there and makes the module\'s importers wait for it. In a classic script or a CommonJS module it is a syntax error, and the workaround is an immediately-invoked async function.',
    deepAnswer: [
      'ES modules are evaluated asynchronously by design — the loader already has to fetch and link dependencies before running them. Top-level `await` extends that: the module\'s evaluation simply does not complete until the awaited promise settles.',
      'The consequence is that the wait propagates. Every module that imports it waits too, transitively up to the entry point. That is a real cost: a slow top-level fetch delays the entire dependency subtree, so it is appropriate for genuine initialisation — loading configuration, initialising a WASM module, choosing an implementation dynamically — and not for ordinary data fetching.',
      'It composes with dynamic import, which is where it is most useful:\n\n```js\nconst { createClient } = await import(`./drivers/${name}.js`);\nexport const client = createClient();\n```\n\nThe module can choose and load an implementation before exporting anything.',
      'In a classic `<script>` — no `type="module"` — it is a `SyntaxError`. The workaround is the IIFE:\n\n```js\n(async () => {\n  const data = await load();\n  start(data);\n})();\n```\n\nNote this changes the semantics: nothing waits for it, so the rest of the script runs immediately and errors need their own handling.',
      'CommonJS cannot support it at all, because `require` is synchronous by definition — the module must be fully evaluated before `require` returns. This is one of the concrete, unbridgeable differences between the two systems.',
      'A caveat worth raising: a cycle involving top-level `await` can deadlock, since two modules can each be waiting for the other to finish evaluating. It is another reason to avoid circular imports.',
    ],
    keyPoints: [
      'Legal only in ES modules; a `SyntaxError` in classic scripts',
      'Module evaluation is already asynchronous, so it fits the model',
      'Importers wait transitively — use it for initialisation, not data fetching',
      'Pairs well with dynamic `import()` for choosing an implementation',
      'CommonJS cannot support it because `require` is synchronous',
      'A cycle plus top-level `await` can deadlock',
    ],
    commonMistakes: [
      'Assuming an async IIFE is equivalent — nothing waits for it.',
      'Using it for per-request data fetching and delaying the whole app.',
    ],
    followUps: ['Why can CommonJS never support it?', 'What does the IIFE workaround give up?'],
  },

  {
    id: 'iv-as-raf-ordering',
    question: 'Where does `requestAnimationFrame` sit relative to timers and microtasks?',
    topic: ASYNC,
    level: L.ADVANCED,
    kind: K.ASYNC,
    topicIds: ['event-loop', 'performance', 'web-apis'],
    relatedLessons: ['l-m33-02'],
    shortAnswer:
      '`requestAnimationFrame` callbacks run as part of the browser\'s rendering step, just before layout and paint, and at most once per frame. Microtasks still drain before them. Timers are ordinary macrotasks and are not tied to frames at all, which is why they are wrong for animation.',
    deepAnswer: [
      'A rough iteration of the loop: take one macrotask, drain the microtask queue completely, then — if the browser has decided to render this turn — run `requestAnimationFrame` callbacks, then style, layout, paint and composite.',
      'The consequences follow from the position. `rAF` callbacks run immediately before layout, so DOM changes made there are painted in the same frame with no intermediate visual state. A timer, by contrast, may fire twice between paints or not at all before one, producing uneven motion.',
      '`rAF` is throttled to the display refresh rate — usually 60Hz, but 120Hz on many modern displays, which is why animation should be driven by the elapsed time passed to the callback rather than by a fixed per-frame increment. It also stops entirely in a background tab, saving battery, whereas a timer keeps firing at a throttled rate.',
      'Microtasks still take priority: a `Promise.resolve().then()` queued inside a `rAF` callback runs before the browser proceeds to layout. And a microtask that enqueues another microtask can starve rendering entirely, because the loop cannot reach the rendering step until the queue is empty.',
      'The practical use beyond animation is batching DOM reads and writes. Doing all writes inside a single `rAF` callback groups them into one layout pass, which is why libraries schedule DOM updates there.',
      'A related detail: reading a geometry property inside a `rAF` callback still forces layout at that moment, so the read/write separation matters there too — `rAF` schedules the work well, it does not make thrashing free.',
      '`requestIdleCallback` sits at the opposite end: it runs only when the browser has spare time after rendering, making it right for genuinely deferrable work like prefetching or analytics flushing, and wrong for anything the user is waiting on.',
    ],
    keyPoints: [
      'Order: macrotask → all microtasks → `rAF` callbacks → style/layout/paint',
      '`rAF` runs at most once per frame, before layout — no intermediate paint',
      'Throttled to the refresh rate and paused in background tabs',
      'Drive animation by elapsed time, not a fixed per-frame step',
      'Microtask recursion can starve the rendering step entirely',
      'Batch DOM writes in `rAF`; reads there still force layout',
      '`requestIdleCallback` is for work the user is not waiting on',
    ],
    commonMistakes: [
      'Animating with `setInterval` and assuming frames align.',
      'Assuming `rAF` outranks microtasks.',
    ],
    followUps: ['Why does a 120Hz display break fixed per-frame increments?', 'How can microtasks starve rendering?'],
  },

  /* ---------------------------------------------------------------- runtime */
  {
    id: 'iv-rt-browser-vs-node',
    question: 'What is the difference between running JavaScript in a browser and in Node?',
    topic: RUNTIME,
    level: L.JUNIOR,
    kind: K.CONCEPT,
    topicIds: ['js-runtime', 'modules'],
    relatedLessons: ['l-m00-02'],
    shortAnswer:
      'The language is the same; the host is different. The browser supplies the DOM, `window`, `fetch`, storage and a security sandbox tied to an origin. Node supplies the filesystem, processes, networking and `process`, with no DOM and no origin-based sandbox.',
    deepAnswer: [
      'The ECMAScript specification defines syntax, types, objects like `Array`, `Promise` and `Math`, and the job queue. Everything else is host-provided.',
      '**Browser**: `document`, `window`, `localStorage`, `fetch`, `history`, `navigator`, the event loop with a rendering step, and a security model built on origins — same-origin policy, CORS, cookie rules. Code runs on someone else\'s machine and is fully visible to them.',
      '**Node**: `fs`, `path`, `process`, `Buffer`, `http`, `child_process`, and access to the whole machine within the user\'s permissions. It also has extra event-loop phases and `process.nextTick`, which runs before promise microtasks — a Node-specific ordering that does not exist in browsers.',
      'The **global object** differs: `window` in a browser, `global` in Node. `globalThis` works in both and is the portable way to reach it.',
      '**Modules** are the practical friction. Browsers speak ESM natively; Node supports both ESM and CommonJS, decided by file extension and by `"type"` in `package.json`. `require` is synchronous and cannot load ESM directly, which is why the two systems interoperate awkwardly.',
      'The consequences that matter day to day: environment variables and secrets are safe in Node and impossible to keep in a browser; the filesystem is available in Node and deliberately unavailable in the browser; and browser code must survive many different engines and versions while server code runs on the one you chose.',
      'Other hosts exist and use the same split — Deno and Bun, Cloudflare Workers and other edge runtimes (a browser-like subset, no filesystem), Electron (both at once). WinterCG is the effort to standardise a common subset like `fetch` and `URL` across them, which is why modern Node has `fetch` built in.',
    ],
    keyPoints: [
      'Same language, different host-provided APIs',
      'Browser: DOM, storage, origin-based security, a rendering step in the loop',
      'Node: filesystem, processes, `Buffer`, extra loop phases, `process.nextTick`',
      '`globalThis` is the portable global reference',
      'ESM everywhere in browsers; ESM and CommonJS in Node, awkwardly',
      'Secrets are safe server-side and impossible client-side',
    ],
    commonMistakes: [
      'Calling the DOM part of JavaScript.',
      'Assuming Node\'s microtask ordering matches the browser\'s.',
    ],
    followUps: ['Where does `process.nextTick` sit?', 'Why is `globalThis` preferable to `window`?'],
  },

  {
    id: 'iv-rt-single-threaded',
    question: 'What does it actually mean to say JavaScript is single-threaded?',
    topic: RUNTIME,
    level: L.JUNIOR,
    kind: K.CONCEPT,
    topicIds: ['js-runtime', 'event-loop'],
    relatedLessons: ['l-m23-01'],
    shortAnswer:
      'One call stack, so exactly one piece of your code executes at a time and it runs to completion before anything else starts. That gives you freedom from data races, and the corresponding cost that any slow synchronous work freezes everything — including rendering and input.',
    deepAnswer: [
      'There is one call stack per execution context. A function runs, calls others, and returns; nothing else — no timer, no event handler, no promise reaction — can interleave into the middle of it. This is called run-to-completion.',
      'The upside is substantial and worth naming: no locks, no mutexes, no deadlocks, and no torn reads. `count++` cannot be interrupted between the read and the write, which in a threaded language is a genuine hazard requiring synchronisation.',
      'The cost is that everything shares that one thread — including rendering. A 500ms synchronous loop means 500ms with no paint, no scroll response and no click handling. The tab appears frozen because it is.',
      'This is exactly why the asynchronous model exists. I/O is handed to the host, which does the waiting elsewhere, and only the **response handling** comes back to your thread. Without that, one slow request would block the page.',
      'What is single-threaded is precisely **your JavaScript**. The browser is heavily multi-threaded — networking, parsing, compositing, and often a separate process per tab. `rAF` callbacks, layout and paint are coordinated with your thread but much of the work is not on it.',
      'Web Workers add threads that run their own code with their own stack and loop, isolated by message passing. Because they share no mutable state by default, the no-data-races property survives.',
      'The practical rule that falls out: keep every task short. Anything above roughly 50ms is a "long task" and is perceptible as unresponsiveness, so heavy work must be chunked with explicit yields or moved to a worker.',
    ],
    keyPoints: [
      'One call stack; run-to-completion, no interleaving',
      'No locks, no deadlocks, no torn reads',
      'Rendering shares the thread — slow synchronous code freezes the page',
      'Asynchrony exists so waiting happens off-thread',
      'The browser itself is multi-threaded; your JavaScript is not',
      'Workers add threads, isolated by message passing',
      'Keep tasks under ~50ms or the page feels unresponsive',
    ],
    commonMistakes: [
      'Thinking `async` functions run on another thread.',
      'Assuming the browser as a whole is single-threaded.',
    ],
    followUps: ['What does run-to-completion guarantee?', 'Why is 50ms the threshold people cite?'],
  },

  {
    id: 'iv-rt-polyfill-transpile',
    question: 'What is the difference between a polyfill and a transpiler?',
    topic: RUNTIME,
    level: L.JUNIOR,
    kind: K.CONCEPT,
    topicIds: ['tooling', 'modern-js'],
    relatedLessons: ['l-m45-01'],
    shortAnswer:
      'A transpiler rewrites **syntax** the target engine cannot parse — arrow functions into `function`, optional chaining into conditionals. A polyfill supplies a missing **API** at runtime — `Array.prototype.at`, `Promise`, `fetch`. Syntax has to be handled at build time; missing functions can be added when the page loads.',
    deepAnswer: [
      'The split follows from when the failure happens. Unsupported syntax is a parse error — the file fails to load at all, before any of your code runs, so nothing at runtime can rescue it. A missing method is a runtime `TypeError` at the moment it is called, which means a script that runs earlier can define it.',
      '**Transpiling** (Babel, TypeScript, esbuild, SWC) rewrites source to an older syntax level. `const`, arrows, classes, `async`/`await`, optional chaining, private fields — all syntax, all build-time.',
      '**Polyfilling** adds the missing API: `Object.hasOwn`, `Array.prototype.flat`, `structuredClone`, `IntersectionObserver`. A polyfill should feature-detect and only install when absent (`if (!Object.hasOwn) { ... }`), and should behave like the specification — a partial implementation that differs in edge cases is worse than none, because code will branch on its presence.',
      'A **shim** is the looser term for a compatibility layer that may normalise behaviour rather than only fill a gap; a **ponyfill** exports the function instead of patching the global, which avoids modifying built-ins that other code shares.',
      'Both cost bytes, and the modern approach is to ship less of them. A browserslist target driven by real usage data, plus `core-js` with `useBuiltIns: "usage"`, includes only what the targeted browsers actually lack. Module/nomodule or differential builds go further: modern browsers get untranspiled code and legacy ones get the heavy build.',
      'Some things cannot be polyfilled — `Proxy`, `WeakRef`, and anything requiring engine-level behaviour. Those are genuine capability boundaries, not gaps to fill, and the answer there is a different design rather than a shim.',
      'The trend worth noting: as evergreen browsers became the norm, the amount of transpilation and polyfilling needed collapsed. Shipping ES2020 untranspiled is reasonable for most audiences now, and checking rather than assuming is the professional move.',
    ],
    keyPoints: [
      'Transpiler rewrites syntax at build time; a polyfill adds an API at runtime',
      'Unsupported syntax is a parse error — nothing at runtime can fix it',
      'Polyfills must feature-detect and match the specification',
      'A ponyfill exports rather than patching a global',
      'Target with browserslist and `useBuiltIns: "usage"` to ship less',
      'Some features cannot be polyfilled at all',
    ],
    commonMistakes: [
      'Believing a polyfill can enable new syntax.',
      'Shipping a broad polyfill bundle to browsers that need none of it.',
    ],
    followUps: ['Why can `Proxy` not be polyfilled?', 'What does a ponyfill avoid?'],
  },

  {
    id: 'iv-rt-url-to-page',
    question: 'What happens between typing a URL and the page becoming interactive?',
    topic: RUNTIME,
    level: L.INTERMEDIATE,
    kind: K.CONCEPT,
    topicIds: ['http', 'js-runtime', 'performance'],
    relatedLessons: ['l-m26-01'],
    shortAnswer:
      'URL parsing, DNS resolution, TCP and TLS handshakes, the HTTP request, the response streaming back, HTML parsing into the DOM while subresources are fetched, CSS into the CSSOM, script execution, then layout, paint and composite — with interactivity arriving once the main thread stops being busy.',
    deepAnswer: [
      '**Resolution and connection.** The URL is parsed, the browser checks its caches, then DNS resolves the hostname (often cached at several levels). A TCP connection is established, and for HTTPS a TLS handshake negotiates encryption. Each of these is a round trip, which is why connection setup dominates on high-latency links and why HTTP/2 and HTTP/3 focus on reducing them.',
      '**Request and response.** The browser sends the request with its headers and cookies; the server responds with a status, headers and a body. Caching headers on that response decide whether the next visit repeats any of this.',
      '**Parsing.** HTML is parsed incrementally into the DOM as bytes arrive, so rendering can begin before the document is complete. A preload scanner runs ahead to start fetching images, stylesheets and scripts early.',
      '**Blocking.** Stylesheets block rendering by design. A synchronous script blocks parsing, and also waits on any pending stylesheet before it can run. `defer` and `type="module"` avoid the parse block.',
      '**Render.** DOM and CSSOM combine into the render tree; layout computes geometry; paint produces pixels; compositing assembles layers. First Contentful Paint is the first of these to show anything, and Largest Contentful Paint marks the main content.',
      '**Interactivity.** The page can look finished while still being unresponsive, because event handling shares the main thread with script execution. Hydration in a server-rendered application is the usual culprit — the markup is visible but the JavaScript that makes it work has not finished running. That gap is what INP measures.',
      'A good answer names where the levers are rather than reciting the list: CDN and connection reuse for the network phase, critical CSS and `defer` for the parse phase, code splitting and smaller bundles for the execution phase, and image dimensions for layout stability.',
    ],
    keyPoints: [
      'DNS → TCP → TLS → request → response, each round trip costing latency',
      'HTML parses incrementally; a preload scanner fetches ahead',
      'CSS blocks rendering; a synchronous script blocks parsing and waits on CSS',
      'Render tree → layout → paint → composite',
      'Looking finished is not being interactive — the main thread may still be busy',
      'The levers map to phases: CDN, critical CSS, `defer`, code splitting, image sizing',
    ],
    commonMistakes: [
      'Stopping at "the server sends HTML and it renders".',
      'Conflating first paint with interactivity.',
    ],
    followUps: ['Why can a page look ready but not respond?', 'Which phase does code splitting help?'],
  },

  /* --------------------------------------------------------- coding: DOM/async */
  {
    id: 'iv-code-delegate-helper',
    question: 'Write a `delegate(container, selector, type, handler)` helper.',
    topic: BROWSER,
    level: L.JUNIOR_PLUS,
    kind: K.CODING,
    topicIds: ['events', 'dom-manipulation'],
    relatedLessons: ['l-m19-04'],
    code: [
      'const off = delegate(list, "[data-id]", "click", (event, el) => {',
      '  remove(el.dataset.id);',
      '});',
      '',
      'off(); // remove the listener',
    ].join('\n'),
    shortAnswer:
      'Attach one listener to the container, use `event.target.closest(selector)` to find the matching element, verify it is actually inside the container, then call the handler with both the event and the matched element. Return an unsubscribe function.',
    deepAnswer: [
      'The implementation:\n\n```js\nfunction delegate(container, selector, type, handler, options) {\n  const listener = (event) => {\n    const match = event.target.closest(selector);\n    if (!match || !container.contains(match)) return;\n    handler(event, match);\n  };\n\n  container.addEventListener(type, listener, options);\n  return () => container.removeEventListener(type, listener, options);\n}\n```',
      '`closest` walks up from the deepest element the event hit, so a click on an icon inside the button still resolves to the button. Comparing `event.target` directly against the selector would fail for any nested markup.',
      'The `container.contains(match)` check matters more than it looks: `closest` can walk past the container to an ancestor that also matches, and with portals or moved nodes the match may not be a descendant at all. Without the check the handler fires for the wrong element.',
      'Returning the unsubscribe function removes the need for callers to keep both the type and the exact listener reference — the usual reason delegated listeners are never cleaned up.',
      'The event-type caveat: `focus`, `blur`, `mouseenter` and `mouseleave` do not bubble, so they never reach the container. Use `focusin`/`focusout`, which do, or register with `{ capture: true }` to catch them on the way down.',
      'The payoff is one listener regardless of how many rows exist, working for rows added after registration, with no per-row cleanup. For a 500-row table that is 500 fewer listener registrations and 500 fewer references to release.',
      'A refinement worth mentioning: for high-frequency types such as `mousemove` or `scroll`, add `{ passive: true }` where you will not call `preventDefault`, so the browser need not wait for the handler before scrolling.',
    ],
    keyPoints: [
      'One listener on the container; `target.closest(selector)` to match',
      'Verify the match is inside the container — `closest` can escape it',
      'Pass both the event and the matched element to the handler',
      'Return an unsubscribe function',
      '`focus`/`blur`/`mouseenter` do not bubble — use `focusin` or capture',
      'Works for elements added later; no per-element cleanup',
    ],
    commonMistakes: [
      'Comparing `event.target` to the selector and failing on nested markup.',
      'Delegating `focus` and wondering why it never fires.',
    ],
    followUps: ['Why is the `contains` check necessary?', 'Which events cannot be delegated normally?'],
  },

  {
    id: 'iv-code-focus-trap',
    question: 'Implement a focus trap for a dialog.',
    topic: BROWSER,
    level: L.ADVANCED,
    kind: K.CODING,
    topicIds: ['events', 'dom'],
    relatedLessons: ['l-m19-05'],
    code: [
      'const release = trapFocus(dialog);',
      '// ... when the dialog closes',
      'release();',
    ].join('\n'),
    shortAnswer:
      'Intercept Tab on the container, compute the focusable elements at that moment, and wrap from last to first (and first to last on Shift+Tab). Store the previously focused element on entry and restore it on release, and register everything through one `AbortController` so teardown is a single call.',
    deepAnswer: [
      'The implementation:\n\n```js\nconst FOCUSABLE = [\n  "a[href]", "button:not([disabled])", "input:not([disabled])",\n  "select:not([disabled])", "textarea:not([disabled])",\n  \'[tabindex]:not([tabindex="-1"])\',\n].join(",");\n\nfunction trapFocus(container) {\n  const previouslyFocused = document.activeElement;\n  const controller = new AbortController();\n\n  const focusable = () =>\n    [...container.querySelectorAll(FOCUSABLE)]\n      .filter((el) => el.offsetParent !== null || el === document.activeElement);\n\n  container.addEventListener("keydown", (event) => {\n    if (event.key !== "Tab") return;\n\n    const items = focusable();\n    if (items.length === 0) {\n      event.preventDefault();\n      return;\n    }\n\n    const first = items[0];\n    const last = items[items.length - 1];\n\n    if (event.shiftKey && document.activeElement === first) {\n      event.preventDefault();\n      last.focus();\n    } else if (!event.shiftKey && document.activeElement === last) {\n      event.preventDefault();\n      first.focus();\n    }\n  }, { signal: controller.signal });\n\n  (focusable()[0] ?? container).focus();\n\n  return () => {\n    controller.abort();\n    previouslyFocused?.focus?.();\n  };\n}\n```',
      'Recomputing the focusable list **on each Tab** rather than caching it at setup is the detail that makes it survive dynamic content — a dialog that reveals a field, disables a button, or renders a list asynchronously.',
      'Filtering out hidden elements matters: `querySelectorAll` happily returns controls inside a collapsed section, and focusing one moves focus somewhere invisible. `offsetParent !== null` is a cheap visibility approximation; it is not perfect (it misfires for `position: fixed`), and a production implementation would also check `getClientRects().length` and `visibility`.',
      'Restoring focus on release is the step most implementations forget, and its absence is the most disorienting part for a keyboard user — focus falls back to `<body>` and they restart from the top of the page.',
      'The `AbortController` makes teardown one call and keeps the listener from outliving the dialog. That is both correctness and leak prevention.',
      'What this does not cover: a trap should usually also handle Escape to close, prevent background scrolling, and set `aria-modal="true"` with a label. And it does not restrict the browser\'s own UI — the user can still Tab out to the address bar, which is correct behaviour and not something to fight.',
      'The professional conclusion: use `<dialog>` with `showModal()`, which implements all of this natively including inertness of the rest of the page. Write this only when a native dialog genuinely cannot be used — the exercise is worth knowing because plenty of codebases contain a hand-rolled one.',
    ],
    keyPoints: [
      'Intercept Tab; wrap last→first and first→last on Shift+Tab',
      'Recompute the focusable list on each Tab, not once at setup',
      'Filter hidden elements or focus lands somewhere invisible',
      'Store and restore the previously focused element',
      'Register through an `AbortController` for one-call teardown',
      'Also needs Escape, scroll lock and `aria-modal`',
      '`<dialog>` + `showModal()` does all of this natively',
    ],
    commonMistakes: [
      'Caching the focusable list and breaking on dynamic content.',
      'Trapping focus but never restoring it on close.',
    ],
    followUps: ['Why recompute the list every time?', 'What does `<dialog>` give you for free?'],
  },

  {
    id: 'iv-code-load-image',
    question: 'Write a promise-returning `loadImage(src)`.',
    topic: BROWSER,
    level: L.JUNIOR_PLUS,
    kind: K.CODING,
    topicIds: ['promises', 'dom', 'web-apis'],
    relatedLessons: ['l-m24-01'],
    code: [
      'const img = await loadImage("/hero.jpg");',
      'container.append(img);',
      'console.log(img.naturalWidth);',
    ].join('\n'),
    shortAnswer:
      'Create an `Image`, attach `load` and `error` handlers **before** setting `src`, and resolve or reject from them. Register with `{ once: true }` so the handlers clean themselves up, and reject with a real `Error` — the `error` event carries no useful detail.',
    deepAnswer: [
      'The implementation:\n\n```js\nfunction loadImage(src, { signal } = {}) {\n  return new Promise((resolve, reject) => {\n    if (signal?.aborted) return reject(signal.reason);\n\n    const img = new Image();\n\n    img.addEventListener("load", () => resolve(img), { once: true });\n    img.addEventListener("error", () => {\n      reject(new Error(`Failed to load image: ${src}`));\n    }, { once: true });\n\n    signal?.addEventListener("abort", () => {\n      img.src = "";            // cancel the in-flight fetch\n      reject(signal.reason);\n    }, { once: true });\n\n    img.src = src;             // last — setting src starts the load\n  });\n}\n```',
      'Setting `src` **last** is the critical ordering. A cached image can fire `load` synchronously during the assignment, so a handler attached afterwards would miss it and the promise would hang forever. This is a real bug, not a theoretical one, and it only reproduces on a warm cache — which is why it survives testing.',
      'The `error` event object contains nothing useful about what went wrong — no status code, no reason. Rejecting with a constructed `Error` naming the source is the most information you can honestly provide. If you need the status, fetch the bytes instead and build a blob URL.',
      '`{ once: true }` removes each listener after it fires, which matters because the image object may be retained by the resolved promise.',
      'Cancellation is worth including: assigning `img.src = ""` aborts an in-flight image request in current browsers, which is the only lever available for this API.',
      'The `new Promise` constructor is appropriate here — this is adapting an event-based API, which is exactly what it is for, unlike wrapping something that already returns a promise.',
      'Two related details: for a cross-origin image whose pixels you intend to read on a canvas, set `img.crossOrigin = "anonymous"` before `src` or the canvas becomes tainted. And `decode()` returns a promise that resolves once the image is decoded and ready to paint — awaiting it before insertion avoids a decode hitch on the first frame.',
    ],
    keyPoints: [
      'Attach `load`/`error` before setting `src` — a cached image can fire immediately',
      'Reject with a constructed `Error`; the event carries no detail',
      '`{ once: true }` cleans up the listeners',
      '`img.src = ""` is the way to cancel an in-flight image load',
      '`new Promise` is right here — it adapts an event API',
      '`crossOrigin` before `src` for canvas use; `decode()` to avoid a paint hitch',
    ],
    commonMistakes: [
      'Setting `src` before attaching handlers and hanging on cached images.',
      'Rejecting with the raw error event, which contains nothing useful.',
    ],
    followUps: ['Why does the cached case only fail sometimes?', 'What does `decode()` add?'],
  },

  {
    id: 'iv-code-serialize-form',
    question: 'Write `serializeForm(form)` that turns a form into a plain object.',
    topic: BROWSER,
    level: L.JUNIOR,
    kind: K.CODING,
    topicIds: ['forms', 'objects'],
    relatedLessons: ['l-m20-03'],
    code: [
      'serializeForm(form);',
      '// { name: "Ada", tags: ["js", "css"], subscribe: true }',
    ].join('\n'),
    shortAnswer:
      'Build a `FormData`, then fold its entries into an object, collecting repeated names into arrays. Handle unchecked checkboxes separately, because `FormData` omits them entirely rather than reporting `false`.',
    deepAnswer: [
      'The implementation:\n\n```js\nfunction serializeForm(form) {\n  const data = new FormData(form);\n  const out = {};\n\n  for (const [key, value] of data) {\n    if (key in out) {\n      if (Array.isArray(out[key])) out[key].push(value);\n      else out[key] = [out[key], value];\n    } else {\n      out[key] = value;\n    }\n  }\n\n  // FormData omits unchecked boxes entirely, so report them explicitly\n  for (const el of form.elements) {\n    if (el.type === "checkbox" && el.name && !(el.name in out)) {\n      out[el.name] = false;\n    }\n  }\n\n  return out;\n}\n```',
      '`Object.fromEntries(new FormData(form))` is the one-liner and it is wrong for two cases: repeated names (a multi-select, or several checkboxes sharing a name) collapse to the last value, and unchecked boxes vanish. The manual fold fixes the first, the second loop fixes the second.',
      'The repeated-name handling deliberately produces a single value for one occurrence and an array for several, matching what most APIs expect. If the server always wants an array for a known field, that is better handled by a schema than by guessing from the DOM — worth saying, because guessing from shape is a source of intermittent bugs when a user selects exactly one option.',
      'Everything comes out as a string except file inputs, which yield `File` objects. Numeric fields need explicit conversion — `valueAsNumber` if you read the element directly, since it gives `NaN` for empty rather than `Number("")`\'s misleading `0`.',
      'Controls without a `name` are omitted, and so are disabled ones. Both are by specification and both are common surprises.',
      'A `key in out` check rather than truthiness matters: a first value of `""` is falsy but present, and a truthiness check would overwrite rather than collect it.',
      'For a JSON API this object is what you `JSON.stringify`. For a file upload, skip the conversion and pass the `FormData` itself as the `fetch` body, which sets the multipart boundary automatically.',
    ],
    keyPoints: [
      '`Object.fromEntries` loses repeated names — fold manually',
      'Unchecked checkboxes are omitted, not `false` — add them explicitly',
      'Use `key in out`, not truthiness, so an empty first value still collects',
      'Values are strings except files; convert numbers deliberately',
      'Unnamed and disabled controls are excluded by specification',
      'Pass `FormData` straight to `fetch` for uploads',
    ],
    commonMistakes: [
      'Shipping the `Object.fromEntries` one-liner and losing multi-values.',
      'Expecting an unchecked box to serialise as `false`.',
    ],
    followUps: ['Why does a single-selection multi-select cause intermittent bugs?', 'When would you skip the conversion entirely?'],
  },

  {
    id: 'iv-code-hash-router',
    question: 'Implement a minimal client-side router.',
    topic: BROWSER,
    level: L.INTERMEDIATE,
    kind: K.CODING,
    topicIds: ['web-apis', 'events', 'design-patterns'],
    relatedLessons: ['l-m27-03'],
    code: [
      'const router = createRouter({',
      '  "/": renderHome,',
      '  "/items/:id": renderItem,',
      '});',
      '',
      'router.navigate("/items/42");',
    ].join('\n'),
    shortAnswer:
      'Match the current path against route patterns, render the handler\'s output, and update history with `pushState`. Listen for `popstate` so the back button works, intercept internal link clicks, and render once on load for a deep link.',
    deepAnswer: [
      'A workable core:\n\n```js\nfunction createRouter(routes, { outlet = document.body } = {}) {\n  const compiled = Object.entries(routes).map(([pattern, handler]) => ({\n    handler,\n    keys: [...pattern.matchAll(/:(\\w+)/g)].map((m) => m[1]),\n    regex: new RegExp("^" + pattern.replace(/:\\w+/g, "([^/]+)") + "$"),\n  }));\n\n  function resolve(path) {\n    for (const route of compiled) {\n      const match = route.regex.exec(path);\n      if (match) {\n        const params = Object.fromEntries(\n          route.keys.map((key, i) => [key, decodeURIComponent(match[i + 1])]),\n        );\n        return { handler: route.handler, params };\n      }\n    }\n    return null;\n  }\n\n  function render() {\n    const found = resolve(location.pathname);\n    outlet.replaceChildren(found ? found.handler(found.params) : notFound());\n  }\n\n  function navigate(path) {\n    if (path === location.pathname) return;\n    history.pushState(null, "", path);\n    render();\n  }\n\n  addEventListener("popstate", render);\n\n  document.addEventListener("click", (event) => {\n    const link = event.target.closest("a[href]");\n    if (!link || link.target || link.hasAttribute("download")) return;\n    if (event.metaKey || event.ctrlKey || event.shiftKey || event.button !== 0) return;\n    const url = new URL(link.href);\n    if (url.origin !== location.origin) return;\n    event.preventDefault();\n    navigate(url.pathname);\n  });\n\n  render();\n  return { navigate };\n}\n```',
      'The details that separate a demo from something usable are mostly in the click handler. Modifier-key and middle-button clicks must fall through so "open in new tab" keeps working; `target="_blank"`, `download`, and external origins must be left alone. Hijacking those is one of the most irritating bugs a hand-rolled router produces.',
      '`popstate` fires for back and forward navigation but **not** for your own `pushState`, so `navigate` must call `render` itself. That asymmetry catches people out.',
      'Rendering once on creation is what makes a deep link work — without it, loading `/items/42` directly shows nothing until the user navigates.',
      'The server side is a requirement, not an optional extra: `pushState` routing needs the server to return the application shell for any path, otherwise a refresh on `/items/42` is a genuine 404. Hash-based routing (`#/items/42`) avoids that entirely and is the pragmatic choice on static hosting that cannot be configured.',
      'What a real router adds: nested routes, route-level data loading, scroll restoration, focus management on navigation (moving focus to the new heading, which keyboard and screen-reader users depend on), and `replaceState` for redirects so the back button does not bounce.',
      'The modern platform alternative worth naming is the Navigation API, which unifies all of this behind a single `navigate` event — better than `popstate` plus click interception, though support is still uneven.',
    ],
    keyPoints: [
      'Compile patterns to regexes; extract and decode params',
      '`pushState` does not fire `popstate` — render explicitly after navigating',
      'Let modifier clicks, `target`, `download` and external links fall through',
      'Render once on load or deep links break',
      '`pushState` routing requires the server to serve the shell for any path',
      'Real routers add data loading, scroll restoration and focus management',
      'The Navigation API is the emerging platform replacement',
    ],
    commonMistakes: [
      'Intercepting every click and breaking open-in-new-tab.',
      'Forgetting that a refresh on a deep path needs server configuration.',
    ],
    followUps: ['Why does hash routing avoid the server requirement?', 'What should happen to focus after navigation?'],
  },

  {
    id: 'iv-code-on-visible',
    question: 'Write `onVisible(element, callback)` that fires once when an element scrolls into view.',
    topic: BROWSER,
    level: L.INTERMEDIATE,
    kind: K.CODING,
    topicIds: ['web-apis', 'performance', 'dom'],
    relatedLessons: ['l-m27-04'],
    code: [
      'onVisible(img, () => {',
      '  img.src = img.dataset.src;',
      '});',
    ].join('\n'),
    shortAnswer:
      'Use an `IntersectionObserver`, unobserve the element as soon as it intersects so the callback fires once, and return a cancel function. Add `rootMargin` so the work starts slightly before the element is actually visible.',
    deepAnswer: [
      'The implementation:\n\n```js\nfunction onVisible(element, callback, { rootMargin = "200px", threshold = 0 } = {}) {\n  if (typeof IntersectionObserver !== "function") {\n    callback(); // no observer support: do the work immediately\n    return () => {};\n  }\n\n  const observer = new IntersectionObserver((entries) => {\n    for (const entry of entries) {\n      if (!entry.isIntersecting) continue;\n      observer.unobserve(entry.target);\n      callback(entry.target, entry);\n    }\n  }, { rootMargin, threshold });\n\n  observer.observe(element);\n  return () => observer.disconnect();\n}\n```',
      'Unobserving **before** calling the callback is what guarantees "once". If the callback throws, or triggers a layout change that re-intersects the element, having already unobserved means it cannot fire twice.',
      '`rootMargin: "200px"` expands the detection box, so a lazily-loaded image begins downloading before it reaches the viewport and appears instantly to the user. Without it, lazy loading is visibly late.',
      '`threshold` controls how much of the element must be visible. `0` means any pixel — right for lazy loading. Something like `0.5` suits "was this actually seen", which is how impression tracking is usually defined.',
      'Returning a cancel function matters because the element may be removed before it is ever seen — a filtered-out list item, an unmounted component. Without `disconnect`, the observer keeps a reference to a detached node.',
      'The graceful-degradation branch is a judgment call worth stating: for lazy loading, doing the work immediately when the API is unavailable is the right failure mode — slower, but correct. For impression tracking, doing nothing would be more honest than recording an impression that never happened.',
      'A platform note that often closes the question: `<img loading="lazy">` is native, needs no JavaScript at all, and should be the first choice for images. `IntersectionObserver` remains the tool for everything else — infinite scroll, animations on entry, sticky-state detection, and analytics.',
      'One detail people miss: the observer fires once immediately on `observe` with the current state, so an already-visible element triggers without any scrolling.',
    ],
    keyPoints: [
      '`IntersectionObserver`; `unobserve` before calling back to guarantee once',
      '`rootMargin` starts the work before the element is visible',
      '`threshold` distinguishes "any pixel" from "actually seen"',
      'Return a cancel function — the element may be removed first',
      'Choose the degraded behaviour deliberately per use case',
      '`<img loading="lazy">` is native and needs none of this',
      'The observer fires immediately on observe with the current state',
    ],
    commonMistakes: [
      'Calling back before unobserving, allowing a double fire.',
      'Omitting `rootMargin` and making lazy loading visibly late.',
    ],
    followUps: ['Why unobserve before the callback?', 'When is `<img loading="lazy">` not enough?'],
  },

  {
    id: 'iv-code-cancellable-sleep',
    question: 'Write a `sleep(ms)` that can be cancelled.',
    topic: ASYNC,
    level: L.INTERMEDIATE,
    kind: K.CODING,
    topicIds: ['promises', 'async-await', 'web-apis'],
    relatedLessons: ['l-m24-01'],
    code: [
      'const controller = new AbortController();',
      '',
      'try {',
      '  await sleep(5000, { signal: controller.signal });',
      '} catch (err) {',
      '  if (err.name === "AbortError") console.log("cancelled");',
      '}',
    ].join('\n'),
    shortAnswer:
      'Wrap `setTimeout` in a promise, and subscribe to the signal\'s `abort` event to clear the timer and reject. Check `signal.aborted` **before** subscribing, so a signal that was already aborted rejects immediately instead of waiting the full duration.',
    deepAnswer: [
      'The implementation:\n\n```js\nfunction sleep(ms, { signal } = {}) {\n  return new Promise((resolve, reject) => {\n    if (signal?.aborted) {\n      reject(signal.reason);\n      return;\n    }\n\n    const id = setTimeout(() => {\n      signal?.removeEventListener("abort", onAbort);\n      resolve();\n    }, ms);\n\n    function onAbort() {\n      clearTimeout(id);\n      reject(signal.reason);\n    }\n\n    signal?.addEventListener("abort", onAbort, { once: true });\n  });\n}\n```',
      'The already-aborted check is the case most implementations miss. A signal aborted before `sleep` is called will never fire another `abort` event, so without the check the promise waits out the full delay and then resolves — the opposite of what the caller asked for.',
      'Clearing the timeout on abort matters beyond correctness: without it the callback still runs later, and in Node a pending timer keeps the process alive.',
      'Removing the abort listener on the success path prevents the signal — which may be long-lived and shared — from accumulating listeners across many sleeps.',
      '`signal.reason` is an `AbortError` `DOMException` by default, or whatever value was passed to `abort(reason)`. Rejecting with it rather than a hand-made error means callers can use the same `err.name === "AbortError"` check they use for `fetch`, which is what makes cancellation composable across APIs.',
      'This is the canonical adapter shape: `new Promise` around an event-based API, with cleanup on both paths. The same skeleton wraps `loadImage`, a WebSocket open, or any other callback API.',
      'Where it is used in practice: the delay between retry attempts, so abandoning a request also abandons the pending backoff; a polling loop that stops on teardown; and a deliberate delay before showing a spinner, cancelled if the response arrives first.',
      'Worth naming: `AbortSignal.timeout(ms)` produces a signal that aborts itself, and `AbortSignal.any([...])` combines several — so "give up after 5 seconds or when the user navigates" needs no manual wiring.',
    ],
    keyPoints: [
      'Check `signal.aborted` before subscribing — an already-aborted signal fires nothing',
      '`clearTimeout` on abort; a pending timer also keeps Node alive',
      'Remove the abort listener on success so a shared signal does not accumulate them',
      'Reject with `signal.reason` so `AbortError` checks work uniformly',
      'The `new Promise` + event + cleanup shape adapts any callback API',
      '`AbortSignal.timeout` and `AbortSignal.any` compose cancellation',
    ],
    commonMistakes: [
      'Omitting the already-aborted check and sleeping the full duration.',
      'Rejecting with a custom error, breaking `AbortError` detection.',
    ],
    followUps: ['Why reject with `signal.reason` rather than a new Error?', 'Where would you use a cancellable sleep?'],
  },
];

export default questions;
