import { INTERVIEW_KIND as K, INTERVIEW_LEVEL as L } from '../schema/types.js';

/**
 * Debugging questions.
 *
 * Each one shows code that is broken in a way that actually reaches production,
 * and asks for the diagnosis and the fix. These are open-ended: there is no
 * option to click, so each carries the expected key points, the model answer
 * and the mistakes an interviewer is listening for — assess yourself against
 * the checklist rather than against a score the app cannot honestly compute.
 *
 * The bugs are drawn from real failure modes: lost `this`, unawaited promises,
 * stale closures, race conditions, mutation of shared state, and listeners that
 * are never removed.
 */

const TOPIC = 'Debugging';

export const questions = [
  {
    id: 'iv-dbg-settimeout-this',
    question: 'The countdown never updates the label and throws after one second. What is wrong?',
    topic: TOPIC,
    level: L.JUNIOR_PLUS,
    kind: K.DEBUGGING,
    topicIds: ['this', 'classes', 'debugging'],
    relatedLessons: ['l-m29-02', 'l-m29-04'],
    code: [
      'class Timer {',
      '  constructor(el) {',
      '    this.el = el;',
      '    this.remaining = 10;',
      '  }',
      '',
      '  start() {',
      '    setInterval(function () {',
      '      this.remaining -= 1;',
      '      this.el.textContent = this.remaining;',
      '    }, 1000);',
      '  }',
      '}',
    ].join('\n'),
    shortAnswer:
      'The callback is a plain `function`, so its `this` is decided by how the timer calls it — not by the enclosing method. It is `undefined` in strict mode (or the global/timer object in sloppy mode), so `this.remaining` throws. Use an arrow function, which has no `this` of its own and inherits the instance.',
    deepAnswer: [
      '`this` is set at the call site. `setInterval` invokes the callback with no receiver, so a `function` expression gets `undefined` as `this` under strict mode — and class bodies are always strict. Reading `.remaining` off `undefined` throws `TypeError`.',
      'The fix is to make the callback lexical:\n\n```js\nthis.intervalId = setInterval(() => {\n  this.remaining -= 1;\n  this.el.textContent = this.remaining;\n}, 1000);\n```\n\nAn arrow has no own `this` binding, so `this` resolves through the enclosing `start` method to the instance.',
      'The older equivalents are worth naming: `.bind(this)` on the function expression, or capturing `const self = this` before the callback. Both work; the arrow is simply the modern spelling.',
      'There is a second, separate bug the interviewer is probably also waiting for: the interval id is never stored, so nothing can ever stop it. The counter runs past zero into negative numbers and keeps firing after the element is gone. Store the id and clear it:\n\n```js\nstop() {\n  clearInterval(this.intervalId);\n  this.intervalId = null;\n}\n```\n\nand clear it automatically when `remaining` reaches `0`.',
      'A third point that shows production experience: an uncleared interval holding `this.el` keeps the element and its whole subtree reachable, so this is also a memory leak in a single-page app that creates and destroys timers.',
      'Finally, `setInterval` drifts — it does not guarantee exactly 1000ms between callbacks, and browsers throttle timers in background tabs. For a visible countdown, compute the remaining time from a stored `Date.now()` deadline rather than by decrementing a counter.',
    ],
    keyPoints: [
      'A `function` callback gets its `this` from the call site — `undefined` in strict mode',
      'Arrow functions inherit `this` lexically; `bind` is the older fix',
      'The interval id is never stored, so it can never be cleared',
      'An uncleared interval holding a DOM node is a memory leak',
      'Do not accumulate time by decrementing — derive it from a deadline',
    ],
    commonMistakes: [
      'Fixing `this` and stopping there, missing the uncleared interval.',
      'Claiming `setInterval` guarantees the stated period.',
    ],
    followUps: ['How would you make the countdown accurate in a background tab?', 'Where should `clearInterval` be called in a component?'],
  },

  {
    id: 'iv-dbg-map-parseint',
    question: '`["10", "10", "10"].map(parseInt)` returns `[10, NaN, 2]`. Explain and fix.',
    topic: TOPIC,
    level: L.JUNIOR_PLUS,
    kind: K.DEBUGGING,
    topicIds: ['array-methods', 'coercion', 'debugging'],
    relatedLessons: ['l-m03-02'],
    code: [
      'const raw = ["10", "10", "10"];',
      '',
      'const parsed = raw.map(parseInt);',
      '// => [10, NaN, 2]',
    ].join('\n'),
    shortAnswer:
      '`map` passes three arguments — value, index, array — and `parseInt` takes two: string and **radix**. So the calls are `parseInt("10", 0)`, `parseInt("10", 1)` and `parseInt("10", 2)`. Fix it with `raw.map((s) => parseInt(s, 10))` or `raw.map(Number)`.',
    deepAnswer: [
      '`parseInt("10", 0)` — radix `0` is falsy and treated as "unspecified", so it defaults to base 10 and gives `10`.',
      '`parseInt("10", 1)` — base 1 is not a valid radix (valid range is 2–36), so the result is `NaN`.',
      '`parseInt("10", 2)` — binary, so `"10"` is `2`.',
      'The general lesson is about **arity mismatch when passing a function reference directly**. Point-free style is only safe when the callee ignores the extra arguments. The same trap bites `map(Number)` — safe, because `Number` takes one argument — versus `map(parseFloat)` — also safe — versus anything with an optional second parameter.',
      'The safe fix is an explicit arrow that passes exactly what you mean: `raw.map((s) => parseInt(s, 10))`. Always pass the radix anyway; it is a habit worth keeping even outside `map`.',
      '`Number(s)` is the better choice for whole strings, because it rejects trailing junk: `parseInt("12abc", 10)` is `12`, while `Number("12abc")` is `NaN`. Which you want depends on whether partial parsing is a feature or a silent data corruption — for user input it is almost always the latter.',
      'A caveat worth adding: `Number("")` is `0` and `Number(" ")` is `0`, so validate for emptiness before converting form input.',
    ],
    keyPoints: [
      '`map` passes (value, index, array) — the index becomes `parseInt`\'s radix',
      'Radix `0` means default, `1` is invalid, `2` is binary',
      'Passing a function reference is unsafe when it has optional extra parameters',
      'Use `(s) => parseInt(s, 10)` or `Number`',
      '`parseInt` stops at junk; `Number` rejects it — and `Number("")` is `0`',
    ],
    commonMistakes: [
      'Blaming `map` rather than the arity mismatch.',
      'Recommending `Number` without mentioning that it treats `""` as `0`.',
    ],
    followUps: ['Which other built-ins are unsafe to pass directly to `map`?', 'When is `parseInt` preferable to `Number`?'],
  },

  {
    id: 'iv-dbg-innerhtml-listeners',
    question: 'After adding a row, the delete buttons on all the earlier rows stop working. Why?',
    topic: TOPIC,
    level: L.INTERMEDIATE,
    kind: K.DEBUGGING,
    topicIds: ['dom-manipulation', 'events', 'debugging'],
    relatedLessons: ['l-m19-04'],
    code: [
      'function addRow(item) {',
      '  list.innerHTML += `<li>${item.name} <button class="del">x</button></li>`;',
      '',
      '  document.querySelectorAll(".del").forEach((btn) => {',
      '    btn.addEventListener("click", () => remove(btn));',
      '  });',
      '}',
    ].join('\n'),
    shortAnswer:
      '`innerHTML +=` re-parses the entire list and replaces every existing node with a new one, so all previously attached listeners are destroyed. Re-attaching to everything also stacks duplicate listeners on the survivors. Use event delegation: one listener on the container.',
    deepAnswer: [
      '`list.innerHTML += html` is read-modify-write: it serialises the current DOM to a string, appends, and re-parses the whole thing. The original elements are discarded, and listeners live on element objects, not on markup — so they go with them. It also resets any DOM state that has no HTML representation: focus, scroll position, form values, `<video>` playback.',
      'The re-attach loop makes it worse. Every call binds a listener to every button, so after three rows the first button has three identical handlers and `remove` runs three times per click.',
      'The correct fix is delegation — one listener, attached once, on the stable parent:\n\n```js\nlist.addEventListener("click", (event) => {\n  const btn = event.target.closest(".del");\n  if (!btn || !list.contains(btn)) return;\n  remove(btn.closest("li"));\n});\n```\n\nIt works for rows that do not exist yet, costs one listener regardless of row count, and needs no cleanup when rows are removed. `closest` is what makes it robust when the click lands on an icon inside the button.',
      'And append properly instead of re-serialising:\n\n```js\nconst li = document.createElement("li");\nli.textContent = item.name;\nconst btn = document.createElement("button");\nbtn.className = "del";\nbtn.textContent = "x";\nli.append(btn);\nlist.append(li);\n```\n\nThis is O(1) per row rather than O(n) re-parsing, and preserves everything already on the page.',
      'There is a security bug here too, and it is the one that matters most: `item.name` is interpolated straight into HTML. If a name can contain markup — and any user-supplied field can — this is a stored cross-site scripting hole. `textContent` assigns text and never parses it, which is why the rewritten version is safe by construction.',
      'For batch inserts, build into a `DocumentFragment` and append once, so layout is recalculated a single time.',
    ],
    keyPoints: [
      '`innerHTML +=` re-parses and replaces every node, destroying listeners and DOM state',
      'Re-attaching to all buttons stacks duplicate handlers',
      'Delegate: one listener on the stable container, with `closest`',
      'Build nodes with `createElement` and `textContent`',
      'Interpolating user text into HTML is an XSS hole — `textContent` avoids it',
    ],
    commonMistakes: [
      'Fixing only the listener duplication and keeping `innerHTML +=`.',
      'Missing that the interpolated name is an injection point.',
    ],
    followUps: ['Why does `closest` matter in the delegated handler?', 'What DOM state besides listeners is lost?'],
  },

  {
    id: 'iv-dbg-missing-await',
    question: 'This logs `undefined` and the `catch` never fires. What is wrong?',
    topic: TOPIC,
    level: L.JUNIOR_PLUS,
    kind: K.DEBUGGING,
    topicIds: ['async-await', 'errors', 'debugging'],
    relatedLessons: ['l-m25-02'],
    code: [
      'async function loadUser(id) {',
      '  try {',
      '    const user = fetchUser(id);',
      '    console.log(user.name);',
      '    return user;',
      '  } catch (err) {',
      '    console.error("failed", err);',
      '    return null;',
      '  }',
      '}',
    ].join('\n'),
    shortAnswer:
      'The `await` is missing. `fetchUser(id)` returns a pending promise, so `user.name` is `undefined` on a promise object, and any rejection happens after `try` has already exited — making the `catch` unreachable and producing an unhandled rejection instead.',
    deepAnswer: [
      'Without `await`, `user` is a `Promise`, not the resolved value. Reading `.name` on it gives `undefined` rather than throwing, which is what makes this bug quiet: nothing crashes at the point of the mistake.',
      'The `catch` problem is more subtle and more important. `try`/`catch` catches synchronous throws in its block. `fetchUser(id)` returns successfully — it just returns a promise that will reject later. By the time the rejection happens the `try` block has long finished, so nothing catches it, and it surfaces as an unhandled rejection far from the code that caused it.',
      'The fix is one word:\n\n```js\nconst user = await fetchUser(id);\n```\n\n`await` on a rejected promise throws inside the `async` function, at that line, which is exactly what makes the surrounding `try`/`catch` work.',
      'The habit worth stating: a `try`/`catch` around asynchronous code is only meaningful if there is an `await` inside the `try`. If there is not, the block is decorative.',
      'The catching mechanism: `@typescript-eslint/no-floating-promises` flags a promise that is neither awaited, returned, nor `.catch`ed. In plain JavaScript, treat "this function is `async` but nothing in the body awaits" as a smell.',
      'A related trap in the same family: `return await x` inside a `try` is not redundant — it makes the rejection catchable there. A bare `return x` hands the promise back to the caller and skips your `catch` entirely, which matters if the `catch` does cleanup or logging.',
    ],
    keyPoints: [
      'Missing `await` gives you a promise, so property reads are `undefined`',
      'A rejection after `try` exits cannot be caught by it',
      'The result is an unhandled rejection reported far from the cause',
      '`try`/`catch` around async code needs an `await` inside to mean anything',
      '`return await x` inside `try` differs from `return x`',
    ],
    commonMistakes: [
      'Explaining the `undefined` but missing why the `catch` is dead.',
      'Calling `return await` inside `try` a pointless extra `await`.',
    ],
    followUps: ['When is `return await` meaningfully different from `return`?', 'How do you catch unhandled rejections globally?'],
  },

  {
    id: 'iv-dbg-sort-boolean',
    question: 'This comparator sorts inconsistently across browsers and array sizes. Why?',
    topic: TOPIC,
    level: L.INTERMEDIATE,
    kind: K.DEBUGGING,
    topicIds: ['array-methods', 'algorithms', 'debugging'],
    relatedLessons: ['l-m12-02'],
    code: [
      'const byAge = (a, b) => a.age > b.age;',
      '',
      'people.sort(byAge);',
    ].join('\n'),
    shortAnswer:
      'A comparator must return a **number**: negative, zero, or positive. This returns a boolean, which coerces to `1` or `0` — so it never says "a comes before b", only "after" or "equal". The result depends on the engine\'s sort algorithm and on the input size, which is why it looks browser-dependent.',
    deepAnswer: [
      '`true` coerces to `1` and `false` to `0`. The comparator can therefore express only two of the three required relations. The engine is being told "these are equal" whenever `a.age <= b.age`, including when `a` is genuinely smaller.',
      'Because the comparator is inconsistent, the outcome depends entirely on the sort implementation and the comparison sequence it happens to choose. V8 uses insertion sort for short arrays and TimSort for longer ones, so the same code can appear to work on a 5-element test fixture and fail on 100 elements — an unusually nasty way to lose confidence in a test suite.',
      'The fix for numbers is subtraction:\n\n```js\nconst byAge = (a, b) => a.age - b.age;\n```',
      'For strings, subtraction produces `NaN`, which is also an invalid comparator result. Use `a.name.localeCompare(b.name)`, which handles case and accents according to locale rules rather than raw code-unit order.',
      'For multi-key sorting, chain with `||` — it falls through only on a `0` tie:\n\n```js\nconst byAgeThenName = (a, b) => a.age - b.age || a.name.localeCompare(b.name);\n```',
      'Two properties a correct comparator must have: it must be consistent (`cmp(a, b)` and `cmp(b, a)` must have opposite signs) and transitive. Violating either gives an implementation-defined result — the specification does not promise anything, not even that the elements are preserved in some order you can predict.',
      'And remember `sort` mutates. `people.sort(...)` reorders the original array; use `[...people].sort(...)` or `people.toSorted(...)` when the caller\'s array must not change.',
    ],
    keyPoints: [
      'A comparator must return a negative, zero or positive number',
      'A boolean gives only `1`/`0` — "before" is unrepresentable',
      'Results vary by engine and array length, so small tests can pass',
      '`a - b` for numbers; `localeCompare` for strings; `||` to chain keys',
      'The comparator must be consistent and transitive; `sort` mutates',
    ],
    commonMistakes: [
      'Saying it "sometimes works" without explaining that the algorithm choice varies by size.',
      'Using subtraction on strings.',
    ],
    followUps: ['How would you sort by two keys?', 'Why can a 5-element test fixture pass?'],
  },

  {
    id: 'iv-dbg-localstorage-object',
    question: 'Reading the saved profile back gives the string `[object Object]`. What went wrong?',
    topic: TOPIC,
    level: L.JUNIOR,
    kind: K.DEBUGGING,
    topicIds: ['storage', 'debugging'],
    relatedLessons: ['l-m27-01'],
    code: [
      'localStorage.setItem("profile", profile);',
      '',
      '// later',
      'const saved = localStorage.getItem("profile");',
      'console.log(saved.name); // undefined',
    ].join('\n'),
    shortAnswer:
      '`localStorage` stores strings only. `setItem` coerces the object with `String()`, producing `"[object Object]"`. Serialise with `JSON.stringify` on the way in and `JSON.parse` on the way out — inside a `try`/`catch`, because stored data can be absent or corrupt.',
    deepAnswer: [
      'The Web Storage API has a string-only value type. Passing an object calls `ToString` on it, and the default `Object.prototype.toString` yields `"[object Object]"` — the data is gone at the moment of writing, not at the moment of reading.',
      'The correct round trip:\n\n```js\nlocalStorage.setItem("profile", JSON.stringify(profile));\n\nconst raw = localStorage.getItem("profile");\nconst saved = raw ? JSON.parse(raw) : null;\n```',
      '`getItem` returns `null` for a missing key, and `JSON.parse(null)` returns `null` rather than throwing — but `JSON.parse` of a corrupted or truncated string throws `SyntaxError`. Storage is shared with other tabs, older versions of your app and the user\'s devtools, so treat it as untrusted input:\n\n```js\nfunction read(key, fallback) {\n  try {\n    const raw = localStorage.getItem(key);\n    return raw === null ? fallback : JSON.parse(raw);\n  } catch {\n    return fallback;\n  }\n}\n```',
      'Writes fail too. `setItem` throws `QuotaExceededError` when the ~5MB limit is hit, and it throws in Safari private browsing. A write helper should catch and degrade rather than break the page.',
      'Type fidelity is limited: JSON has no `Date`, no `Map`/`Set`, no `undefined`. A `Date` comes back as an ISO string, so revive it explicitly rather than assuming `saved.createdAt.getTime()` works.',
      'One thing to say unprompted: never store tokens, passwords or personal data here. `localStorage` is readable by any script on the origin, so any XSS becomes a credential theft. Session identifiers belong in `HttpOnly` cookies, which JavaScript cannot read at all.',
    ],
    keyPoints: [
      '`localStorage` values are strings — objects become `"[object Object]"`',
      '`JSON.stringify` in, `JSON.parse` out',
      'Guard reads with `try`/`catch`; stored data can be missing or corrupt',
      '`setItem` can throw on quota or in private browsing',
      'JSON loses `Date`, `Map`, `Set` and `undefined`',
      'Never store credentials — any XSS can read the whole origin\'s storage',
    ],
    commonMistakes: [
      'Adding `JSON.parse` without handling `null` or a `SyntaxError`.',
      'Treating storage as a safe place for auth tokens.',
    ],
    followUps: ['How do you restore a `Date` from JSON?', 'Where should a session token live instead?'],
  },

  {
    id: 'iv-dbg-listener-not-removed',
    question: 'Scrolling gets slower every time the user opens and closes the panel. Why?',
    topic: TOPIC,
    level: L.INTERMEDIATE,
    kind: K.DEBUGGING,
    topicIds: ['events', 'performance', 'debugging'],
    relatedLessons: ['l-m19-05', 'l-m43-02'],
    code: [
      'function openPanel() {',
      '  window.addEventListener("scroll", () => reposition(panel));',
      '  panel.hidden = false;',
      '}',
      '',
      'function closePanel() {',
      '  panel.hidden = true;',
      '}',
    ].join('\n'),
    shortAnswer:
      'The scroll listener is added on every open and never removed, so listeners accumulate and every scroll event runs `reposition` N times. It also keeps `panel` reachable forever. Remove the listener on close — which requires a stable reference, or an `AbortController` signal.',
    deepAnswer: [
      'Each `openPanel` call registers a **new** anonymous function. `removeEventListener` could not remove it even if it were called, because it needs the identical function reference — a fresh arrow with the same body is a different object.',
      'The visible symptom is degrading scroll performance: after ten open/close cycles, every scroll event runs `reposition` ten times, on the main thread, during the most latency-sensitive interaction there is.',
      'The invisible symptom is the leak. The listener closes over `panel`, so the element and its subtree stay reachable from the `window` listener list even after the panel is removed from the DOM. In a long-lived single-page app this accumulates.',
      'The modern fix is `AbortController`, which removes the need to keep references at all:\n\n```js\nlet controller = null;\n\nfunction openPanel() {\n  controller = new AbortController();\n  window.addEventListener("scroll", () => reposition(panel), { signal: controller.signal });\n  panel.hidden = false;\n}\n\nfunction closePanel() {\n  controller?.abort();\n  controller = null;\n  panel.hidden = true;\n}\n```\n\nOne `abort()` removes every listener registered with that signal, which scales cleanly when a component adds several.',
      'The classic alternative is a named handler stored somewhere stable, and `removeEventListener("scroll", handler)` in `closePanel`. Both are correct; the signal approach is harder to get wrong.',
      'Two performance points worth adding: register scroll listeners as `{ passive: true }` so the browser need not wait to see whether you will call `preventDefault`, and throttle `reposition` to animation frames with `requestAnimationFrame` rather than running layout work on every scroll event. If the goal is purely to detect visibility, `IntersectionObserver` avoids the scroll listener entirely.',
      'How to confirm it: DevTools has a listener count per element in the Elements panel, and a heap snapshot comparison across open/close cycles shows the retained detached nodes.',
    ],
    keyPoints: [
      'A new anonymous function per call cannot be removed and accumulates',
      'Every scroll event then runs the work N times on the main thread',
      'The closure retains the element — a real memory leak',
      '`AbortController` + `{ signal }` removes all listeners in one call',
      'Use `{ passive: true }`, `requestAnimationFrame`, or `IntersectionObserver`',
    ],
    commonMistakes: [
      'Calling `removeEventListener` with a new arrow function and believing it worked.',
      'Treating this as only a performance issue and missing the retained DOM.',
    ],
    followUps: ['Why does `removeEventListener` need the same reference?', 'How would you confirm the leak in DevTools?'],
  },

  {
    id: 'iv-dbg-debounce-broken',
    question: 'This debounce fires on every keystroke anyway. Find the bug.',
    topic: TOPIC,
    level: L.INTERMEDIATE,
    kind: K.DEBUGGING,
    topicIds: ['closures', 'performance', 'debugging'],
    relatedLessons: ['l-m32-02'],
    code: [
      'function debounce(fn, wait) {',
      '  let timer;',
      '  return function (...args) {',
      '    timer = setTimeout(() => fn.apply(this, args), wait);',
      '  };',
      '}',
      '',
      'input.addEventListener("input", debounce(handleInput, 300));',
    ].join('\n'),
    shortAnswer:
      'The pending timer is never cancelled, so each call simply schedules another one — every keystroke still fires, just 300ms later. The missing line is `clearTimeout(timer)` before scheduling the new one.',
    deepAnswer: [
      'Debouncing means "run once, after the calls stop". That requires cancelling the previous pending run each time a new call arrives. Without `clearTimeout`, all N timers survive and all N fire, delayed but complete.',
      'The corrected implementation:\n\n```js\nfunction debounce(fn, wait) {\n  let timer;\n  return function (...args) {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn.apply(this, args), wait);\n  };\n}\n```\n\n`clearTimeout(undefined)` is a harmless no-op, so the first call needs no special case.',
      'Note what the original does get right, and say so: `function` rather than an arrow for the returned wrapper, plus `fn.apply(this, args)`, preserves the caller\'s `this`. Writing the wrapper as an arrow would break debounced methods.',
      'A production version usually also offers `cancel()` for cleanup on unmount, and sometimes a leading-edge option to fire immediately then suppress:\n\n```js\ndebounced.cancel = () => clearTimeout(timer);\n```',
      'The distinction the interviewer will probe: **debounce** waits for a pause and is right for search-as-you-type, resize handlers and autosave. **Throttle** guarantees at most one call per interval and is right for scroll position, mousemove and analytics — things where you want steady updates rather than only a final one. Debouncing a scroll handler means nothing happens at all while the user keeps scrolling.',
      'One caveat for the search case specifically: debouncing reduces requests but does not order them. The stale-response race still needs a sequence guard or `AbortController`.',
    ],
    keyPoints: [
      'Missing `clearTimeout` — every scheduled call still fires',
      '`clearTimeout(undefined)` is safe, so no first-call special case is needed',
      '`function` + `fn.apply(this, args)` correctly preserves `this`',
      'Expose `cancel()` for cleanup',
      'Debounce waits for a pause; throttle rate-limits — they are not interchangeable',
    ],
    commonMistakes: [
      'Rewriting the wrapper as an arrow and silently breaking `this`.',
      'Describing debounce and throttle as the same thing.',
    ],
    followUps: ['When would throttle be correct instead?', 'How do you cancel a pending debounce on unmount?'],
  },

  {
    id: 'iv-dbg-object-includes',
    question: 'The "already in cart" check never matches, so items get added twice. Why?',
    topic: TOPIC,
    level: L.JUNIOR,
    kind: K.DEBUGGING,
    topicIds: ['objects', 'arrays', 'debugging'],
    relatedLessons: ['l-m14-05'],
    code: [
      'function addToCart(cart, product) {',
      '  if (cart.includes({ id: product.id })) return cart;',
      '  return [...cart, product];',
      '}',
    ].join('\n'),
    shortAnswer:
      '`includes` compares by identity, and `{ id: product.id }` is a brand-new object that is not identical to anything in the cart — so the check is always `false`. Compare by a key instead: `cart.some((item) => item.id === product.id)`.',
    deepAnswer: [
      'Objects are compared by reference. Two object literals with identical contents are two different values, so `{ id: 1 } === { id: 1 }` is `false` and `includes`, which uses SameValueZero, can never match a freshly-built literal.',
      'The fix is to compare on the field that defines identity for your domain:\n\n```js\nif (cart.some((item) => item.id === product.id)) return cart;\n```\n\n`some` short-circuits on the first match, and the predicate makes the identity rule explicit and reviewable.',
      '`includes` **is** correct when you hold the same reference — `cart.includes(product)` works if `product` came out of the cart. The bug is constructing a lookalike.',
      'For a cart that is checked frequently, a linear `some` per add is O(n) and the whole build is O(n²). A `Map` keyed by id gives O(1) lookups and also solves quantity merging naturally:\n\n```js\nconst byId = new Map(cart.map((item) => [item.id, item]));\n```',
      'The wider point about equality: JavaScript has no built-in structural comparison. `===`, `includes`, `indexOf`, `Set` membership and `Map` keys are all reference-based for objects. Structural equality means either comparing chosen fields, or serialising to a canonical key — and `JSON.stringify` is not canonical, because key order and `undefined` handling make two equivalent objects produce different strings.',
      'A likely follow-up: with `some` fixed, adding the same product twice should probably increment a quantity rather than silently do nothing. Returning the cart unchanged is a design decision the interviewer may want you to notice.',
    ],
    keyPoints: [
      'Objects compare by reference — a new literal never matches',
      '`some` with an explicit id predicate is the fix',
      '`includes` is fine when you hold the same reference',
      'A `Map` keyed by id turns O(n) lookups into O(1)',
      'JavaScript has no structural equality; `JSON.stringify` is not canonical',
    ],
    commonMistakes: [
      'Suggesting `JSON.stringify` comparison without noting key-order fragility.',
      'Missing that silently ignoring a duplicate may itself be the wrong behaviour.',
    ],
    followUps: ['How would you handle incrementing quantity instead?', 'Why is `JSON.stringify` unsafe for equality?'],
  },

  {
    id: 'iv-dbg-return-in-foreach',
    question: 'This validator always reports success, even with an invalid field. Why?',
    topic: TOPIC,
    level: L.JUNIOR,
    kind: K.DEBUGGING,
    topicIds: ['array-methods', 'control-flow', 'debugging'],
    relatedLessons: ['l-m13-01'],
    code: [
      'function validate(fields) {',
      '  fields.forEach((field) => {',
      '    if (!field.value) {',
      '      return { ok: false, field: field.name };',
      '    }',
      '  });',
      '',
      '  return { ok: true };',
      '}',
    ].join('\n'),
    shortAnswer:
      '`return` inside a `forEach` callback returns from the **callback**, not from `validate`. `forEach` discards that value and keeps iterating, so control always reaches `return { ok: true }`. Use `find`, or a `for...of` loop where `return` exits the function.',
    deepAnswer: [
      'The callback is a separate function. Returning from it ends that one invocation; `forEach` ignores the return value entirely and calls the callback for the next element. There is no way to break out of `forEach` — not with `return`, not with `break` (a syntax error there).',
      'The clearest fix expresses the intent directly:\n\n```js\nconst invalid = fields.find((field) => !field.value);\nreturn invalid ? { ok: false, field: invalid.name } : { ok: true };\n```\n\n`find` short-circuits on the first match, which is exactly the "first failure wins" semantics the original was reaching for.',
      'A `for...of` loop also works and is preferable when the body does several things:\n\n```js\nfor (const field of fields) {\n  if (!field.value) return { ok: false, field: field.name };\n}\nreturn { ok: true };\n```\n\nHere `return` really does exit `validate`, and `break`/`continue` are available.',
      'Choosing the right array method by the shape of the answer is the underlying skill: `some` for "is there any", `every` for "are they all", `find` for "which one", `filter` for "all of them", `map` for "one output per input", `reduce` for "fold to a single value", `forEach` only for side effects with no early exit.',
      'The design question an interviewer may push on: returning only the first invalid field means the user fixes one error, resubmits, and sees the next. Collecting all failures with `filter` gives a better form experience:\n\n```js\nconst errors = fields.filter((f) => !f.value).map((f) => f.name);\nreturn { ok: errors.length === 0, errors };\n```',
    ],
    keyPoints: [
      '`return` in a `forEach` callback exits only the callback',
      '`forEach` cannot be broken out of at all',
      '`find` gives first-match-wins semantics directly',
      '`for...of` allows a real `return`, `break` and `continue`',
      'Collecting every error is usually better UX than reporting only the first',
    ],
    commonMistakes: [
      'Trying to `break` inside `forEach`.',
      'Fixing the mechanics without questioning first-error-only behaviour.',
    ],
    followUps: ['How do you choose between `some`, `every`, `find` and `filter`?', 'Why can you not `break` out of `forEach`?'],
  },

  {
    id: 'iv-dbg-nan-check',
    question: 'The "invalid number" branch never runs. What is wrong with the check?',
    topic: TOPIC,
    level: L.JUNIOR,
    kind: K.DEBUGGING,
    topicIds: ['numbers', 'coercion', 'debugging'],
    relatedLessons: ['l-m02-04'],
    code: [
      'const value = Number(input.value);',
      '',
      'if (value === NaN) {',
      '  showError("Please enter a number");',
      '}',
    ].join('\n'),
    shortAnswer:
      '`NaN` is the only value not equal to itself, so `value === NaN` is always `false`. Use `Number.isNaN(value)` — and note that a check for valid numeric input needs more than that anyway, since `Number("")` is `0`.',
    deepAnswer: [
      'IEEE-754 defines `NaN` as unordered with respect to everything, itself included. Every comparison involving it — `===`, `<`, `>` — is `false`, and `NaN !== NaN` is the only way to detect it with operators alone.',
      '`Number.isNaN(x)` returns `true` only for the actual `NaN` value. The older global `isNaN(x)` coerces first, so `isNaN("abc")` is `true` and `isNaN(undefined)` is `true` and `isNaN("")` is `false` — a different and usually wrong question. Prefer `Number.isNaN`.',
      'For validating input, `Number.isFinite(value)` is usually the better test: it rejects `NaN`, `Infinity` and `-Infinity` in one check, and — unlike the global `isFinite` — does not coerce.',
      'The bug that survives even after fixing the comparison: `Number("")` is `0`, and `Number("  ")` is `0`. An empty field therefore passes any numeric check. Validate emptiness separately:\n\n```js\nconst raw = input.value.trim();\nif (raw === "") return showError("Required");\nconst value = Number(raw);\nif (!Number.isFinite(value)) return showError("Please enter a number");\n```',
      'Also worth knowing: `Number(null)` is `0` while `Number(undefined)` is `NaN`, and `Number("0x10")` is `16`. These asymmetries are why explicit trimming and an explicit finite check beat relying on coercion.',
      'Where `NaN` usually comes from in practice is arithmetic on an unparsed value — `undefined * 2`, or adding a form field before converting it. When you see `NaN` propagating through a calculation, trace back to the first operation with a non-numeric operand rather than checking at the end.',
    ],
    keyPoints: [
      '`NaN !== NaN` — equality can never detect it',
      '`Number.isNaN` is exact; the global `isNaN` coerces first',
      '`Number.isFinite` rejects `NaN` and both infinities in one test',
      '`Number("")` and `Number(null)` are `0` — check emptiness separately',
      '`NaN` propagates; trace to the first non-numeric operand',
    ],
    commonMistakes: [
      'Using the global `isNaN` and inheriting its coercion.',
      'Assuming a finite check also rejects empty input.',
    ],
    followUps: ['Why is `Number("")` zero?', 'How would you validate a currency field?'],
  },

  {
    id: 'iv-dbg-stale-closure-count',
    question: 'The handler always logs the count as it was when the panel opened. Why?',
    topic: TOPIC,
    level: L.INTERMEDIATE,
    kind: K.DEBUGGING,
    topicIds: ['closures', 'events', 'debugging'],
    relatedLessons: ['l-m32-04'],
    code: [
      'function setup(getCount) {',
      '  const count = getCount();',
      '',
      '  button.addEventListener("click", () => {',
      '    console.log("count is", count);',
      '  });',
      '}',
    ].join('\n'),
    shortAnswer:
      'A stale closure. `count` is read once, at setup time, and the handler closes over that constant binding — not over a live value. Read the current value inside the handler instead: call `getCount()` at click time.',
    deepAnswer: [
      'Closures capture bindings, and `count` is a `const` that is assigned exactly once. The handler faithfully reports the value from setup, however long ago that was. Nothing about closures is broken here — the code asked for a snapshot and got one.',
      'The fix moves the read to the moment it is needed:\n\n```js\nbutton.addEventListener("click", () => {\n  console.log("count is", getCount());\n});\n```\n\nNow the closure captures `getCount`, a stable function, and the value is fetched fresh on each click.',
      'The general shape of the bug: **capturing a value when you meant to capture a source**. Capture the getter, the store, the ref, or the object — anything whose contents can change — rather than the extracted value.',
      'This is the exact mechanism behind the React stale-closure problem: an effect or callback registered with an empty dependency array closes over the first render\'s state. The framework-level fixes (dependency arrays, functional `setState` updaters, refs) are all ways of saying "capture a source, not a snapshot".',
      'It also explains why the fix for the `var`-in-a-loop bug is different in kind. There, the problem was too **few** bindings — one shared `i`. Here there are enough bindings; the problem is that the value was frozen too early. Both are "closures capture bindings", read from opposite directions.',
      'How to spot it while reviewing: any value read **outside** an asynchronous or event-driven callback but used **inside** it is a candidate. Ask "can this change between registration and invocation?" — if yes, read it inside.',
    ],
    keyPoints: [
      'The closure captured a one-time value, not a live source',
      'Nothing is broken — the code asked for a snapshot',
      'Capture the getter/store/object, and read inside the callback',
      'Same mechanism as React stale closures over state',
      'Review heuristic: values read outside a callback but used inside it',
    ],
    commonMistakes: [
      'Blaming the closure mechanism rather than where the read happens.',
      'Confusing this with the `var`-in-a-loop bug, which has the opposite cause.',
    ],
    followUps: ['How is this different from the `var` loop bug?', 'How does React solve the same problem?'],
  },

  {
    id: 'iv-dbg-json-parse-untrusted',
    question: 'A malformed cached entry takes the whole page down. Fix the loading code.',
    topic: TOPIC,
    level: L.JUNIOR_PLUS,
    kind: K.DEBUGGING,
    topicIds: ['errors', 'storage', 'debugging'],
    relatedLessons: ['l-m22-03'],
    code: [
      'function loadCache() {',
      '  const raw = localStorage.getItem("cache");',
      '  const data = JSON.parse(raw);',
      '  return data.items;',
      '}',
    ].join('\n'),
    shortAnswer:
      '`JSON.parse` throws a `SyntaxError` on anything that is not valid JSON, and stored data can be truncated, written by an older version of the app, or edited by hand. The throw propagates and breaks initialisation. Parse inside `try`/`catch`, validate the shape, and fall back to a safe default.',
    deepAnswer: [
      'Three distinct failure modes hide in these four lines. `raw` can be `null` for a missing key — `JSON.parse(null)` happens to return `null` rather than throwing, so that one is quiet. `raw` can be invalid JSON, which throws. And `data` can be valid JSON of the wrong shape — `"5"` parses fine, and `data.items` is then `undefined`, or `data` is `null` and the property read throws.',
      'A defensive version:\n\n```js\nfunction loadCache() {\n  try {\n    const raw = localStorage.getItem("cache");\n    if (raw === null) return [];\n    const data = JSON.parse(raw);\n    return Array.isArray(data?.items) ? data.items : [];\n  } catch {\n    localStorage.removeItem("cache");\n    return [];\n  }\n}\n```\n\nNote it clears the corrupt entry — otherwise the failure repeats on every load forever.',
      'The principle: **anything crossing a trust boundary must be validated, not assumed**. `localStorage`, URL parameters, `postMessage` payloads, API responses and file uploads are all input, even when your own code wrote them. Storage in particular is shared across versions of your app, so yesterday\'s schema is today\'s malformed data.',
      'The shape check matters as much as the parse. `Array.isArray(data?.items)` is the minimum; for anything larger, a schema validator at the boundary converts a class of runtime `TypeError`s into one clear failure at the point of entry.',
      'On the `catch`: swallowing silently is right here because a cache miss is recoverable, but it should still be observable — log it, or increment a metric. A `catch` that hides a systematic corruption bug forever is its own defect.',
      'What this specifically must **not** become: `eval(raw)`. Parsing untrusted text by executing it turns a data problem into arbitrary code execution. `JSON.parse` exists precisely so that never has to happen.',
    ],
    keyPoints: [
      '`JSON.parse` throws `SyntaxError` on malformed input',
      '`getItem` returns `null` for a missing key; `JSON.parse(null)` is `null`',
      'Valid JSON of the wrong shape still breaks the property read',
      'Clear the corrupt entry, or the failure repeats every load',
      'Validate everything crossing a trust boundary; never `eval` stored text',
    ],
    commonMistakes: [
      'Adding `try`/`catch` but leaving the corrupt entry in place.',
      'Checking the parse succeeded without checking the shape.',
    ],
    followUps: ['What else counts as a trust boundary in a browser app?', 'When is swallowing an error acceptable?'],
  },

  {
    id: 'iv-dbg-handler-invoked',
    question: 'The click handler runs once at page load and never again. Why?',
    topic: TOPIC,
    level: L.JUNIOR,
    kind: K.DEBUGGING,
    topicIds: ['events', 'dom', 'debugging'],
    relatedLessons: ['l-m19-01'],
    code: [
      'button.addEventListener("click", handleClick());',
      '',
      'function handleClick() {',
      '  console.log("clicked");',
      '}',
    ].join('\n'),
    shortAnswer:
      'The parentheses **call** `handleClick` immediately and register its return value — `undefined` — as the listener. Pass the function itself: `addEventListener("click", handleClick)`.',
    deepAnswer: [
      '`handleClick()` evaluates during the `addEventListener` call, which is why the log appears at load time. Its return value is `undefined`, and `addEventListener` accepts a non-callable second argument without complaint, so nothing is registered and no error is reported. The silence is what makes this cost more time than it should.',
      'Correct: `button.addEventListener("click", handleClick)` — a reference, not a call.',
      'The variant that is genuinely useful is when you need to pass an argument. Then a wrapper is correct, and the parentheses belong inside it:\n\n```js\nbutton.addEventListener("click", () => handleClick(item.id));\n```\n\nBut be aware this creates a new function each time it is evaluated, so it cannot later be removed with `removeEventListener` unless you keep the reference.',
      'A factory that returns a handler is the other legitimate reason to see parentheses at registration:\n\n```js\nconst makeHandler = (id) => (event) => handleClick(id, event);\nbutton.addEventListener("click", makeHandler(item.id));\n```\n\nHere `makeHandler(item.id)` is called on purpose and returns the actual listener.',
      'A related mistake in the same family is `setTimeout(doThing(), 1000)`, which has the identical cause and the identical silent failure.',
      'Worth noting: `handleClick` is a function **declaration**, so hoisting means the code works despite being defined below the registration. Had it been `const handleClick = () => {}`, the same line would throw a `ReferenceError` from the temporal dead zone — a different bug that at least announces itself.',
    ],
    keyPoints: [
      'The parentheses call the function and register its return value',
      '`addEventListener` accepts `undefined` silently — no error is raised',
      'Pass the reference; use an arrow wrapper only when passing arguments',
      'A wrapper arrow cannot be removed later without keeping the reference',
      '`setTimeout(fn(), ms)` is the same mistake',
    ],
    commonMistakes: [
      'Fixing it with `.bind()` unnecessarily when a plain reference suffices.',
      'Not realising an arrow wrapper makes removal harder.',
    ],
    followUps: ['How do you pass an argument to a listener?', 'Why does hoisting matter in this snippet?'],
  },

  {
    id: 'iv-dbg-arrow-prototype-method',
    question: 'Every instance reports `undefined` for its own name. Find the bug.',
    topic: TOPIC,
    level: L.JUNIOR_PLUS,
    kind: K.DEBUGGING,
    topicIds: ['this', 'prototypes', 'debugging'],
    relatedLessons: ['l-m29-04'],
    code: [
      'function User(name) {',
      '  this.name = name;',
      '}',
      '',
      'User.prototype.greet = () => {',
      '  return `Hi, ${this.name}`;',
      '};',
      '',
      'const u = new User("Ada");',
      'u.greet(); // "Hi, undefined"',
    ].join('\n'),
    shortAnswer:
      'An arrow function has no `this` of its own — it captures the `this` of the scope where it was **defined**, which here is module or global scope, not the instance. A prototype method must be a regular function so the call site can supply the receiver.',
    deepAnswer: [
      'Arrows resolve `this` lexically. At the point `greet` is defined, the enclosing `this` is whatever the module or script has — `undefined` in a module, the global object in a classic script. Calling `u.greet()` does not change that, because arrows ignore the receiver entirely.',
      'The fix is a regular function, whose `this` is bound by the call site:\n\n```js\nUser.prototype.greet = function () {\n  return `Hi, ${this.name}`;\n};\n```\n\nOr the class equivalent, which does the same thing more clearly:\n\n```js\nclass User {\n  constructor(name) { this.name = name; }\n  greet() { return `Hi, ${this.name}`; }\n}\n```',
      'The rule to state: use an arrow when you **want** to inherit the surrounding `this` — a callback inside a method, a `setTimeout`, an array-method callback that needs the instance. Use a regular function when the caller is supposed to supply `this` — object methods, prototype methods, class methods.',
      'A useful diagnostic detail: in a module (or under strict mode) the outer `this` is `undefined`, so this same code throws `TypeError: Cannot read properties of undefined` instead of returning `"Hi, undefined"`. Which symptom you see tells you which mode the file is running in.',
      'The related failure worth mentioning: arrows also have no `arguments`, no `prototype`, and cannot be called with `new`. `new (() => {})` throws `TypeError`, so an arrow can never serve as a constructor.',
      '`call`, `apply` and `bind` are equally powerless against an arrow — they cannot override a lexical `this`. If a function seems to ignore `bind`, that is the giveaway.',
    ],
    keyPoints: [
      'Arrows capture `this` lexically from the definition site',
      'Prototype and object methods need a regular function',
      'Arrows are right for callbacks that should inherit the surrounding `this`',
      'In a module the outer `this` is `undefined`, so it throws instead',
      'Arrows have no `arguments`, no `prototype`, and cannot be `new`ed or rebound',
    ],
    commonMistakes: [
      'Trying to fix it with `.bind(u)` — `bind` cannot override a lexical `this`.',
      'Treating arrows as always-safer shorthand for function expressions.',
    ],
    followUps: ['Why does `bind` not help here?', 'When is an arrow the right choice for a method?'],
  },

  {
    id: 'iv-dbg-key-collision-numeric',
    question: 'The grouped report comes out in the wrong order and one key is missing. Diagnose.',
    topic: TOPIC,
    level: L.INTERMEDIATE,
    kind: K.DEBUGGING,
    topicIds: ['objects', 'data-structures', 'debugging'],
    relatedLessons: ['l-m15-01'],
    code: [
      'function groupByYear(records) {',
      '  const out = {};',
      '  for (const r of records) {',
      '    out[r.year] = out[r.year] || [];',
      '    out[r.year].push(r);',
      '  }',
      '  return Object.entries(out);',
      '}',
      '',
      '// records arrive newest-first; the report should keep that order',
    ].join('\n'),
    shortAnswer:
      'Numeric-looking keys are integer indices, so `Object.entries` returns them in ascending numeric order regardless of insertion order — the newest-first ordering is silently reversed. A `Map` preserves insertion order and keeps the key type; that is the right structure here.',
    deepAnswer: [
      '`r.year` is a number, and object property names are always strings — `2024` becomes `"2024"`. Because `"2024"` is a valid array index, it is ordered as an integer key, ahead of any non-integer string key and sorted ascending. The insertion order the code relied on is discarded.',
      'The fix keeps the same loop shape but changes the container:\n\n```js\nfunction groupByYear(records) {\n  const out = new Map();\n  for (const r of records) {\n    if (!out.has(r.year)) out.set(r.year, []);\n    out.get(r.year).push(r);\n  }\n  return [...out];\n}\n```\n\n`Map` iterates in insertion order, keeps `year` as a number, and has no prototype keys to collide with.',
      'If a plain object is required — because the result is serialised to JSON, which has no `Map` — then sort explicitly at the end rather than relying on any order at all: `Object.entries(out).sort((a, b) => b[0] - a[0])`. Relying on implicit ordering is the underlying mistake; making the ordering explicit is the durable fix.',
      'The "missing key" half of the question is the second hazard: `out[r.year] || []` treats any falsy existing value as absent, and a plain object also inherits keys from `Object.prototype`. A record with `year` of `"constructor"` or `"toString"` would find an inherited function instead of `undefined` and take the wrong branch. `Object.create(null)`, `Object.hasOwn`, or a `Map` all avoid this — `Map` most simply.',
      'This is the general case for `Map` over an object: non-string keys, keys that come from data rather than from code, guaranteed insertion order, a real `size`, and direct iterability. Use a plain object for fixed, code-authored shapes; use a `Map` for dynamic collections.',
      'ES2024 adds `Object.groupBy` and `Map.groupBy` for exactly this, and `Map.groupBy` is the one that keeps insertion order and non-string keys.',
    ],
    keyPoints: [
      'Integer-like keys are ordered numerically, ignoring insertion order',
      'Object keys are always strings — the number type is lost',
      '`Map` preserves insertion order and key type',
      'Data-derived keys on a plain object can collide with `Object.prototype`',
      'If ordering matters, make it explicit with `sort` rather than implicit',
    ],
    commonMistakes: [
      'Assuming object key order always follows insertion.',
      'Missing the prototype-key hazard of a data-keyed plain object.',
    ],
    followUps: ['When is a plain object still the better choice?', 'What does `Object.create(null)` give you here?'],
  },

  {
    id: 'iv-dbg-form-numeric-concat',
    question: 'Adding a quantity of 1 to a quantity of 2 produces 12. What is happening?',
    topic: TOPIC,
    level: L.JUNIOR,
    kind: K.DEBUGGING,
    topicIds: ['forms', 'coercion', 'debugging'],
    relatedLessons: ['l-m20-01'],
    code: [
      'const current = quantityInput.value;',
      'const added = otherInput.value;',
      '',
      'total.textContent = current + added;',
    ].join('\n'),
    shortAnswer:
      '`input.value` is always a string, even for `<input type="number">`. `+` with two strings concatenates, so `"1" + "2"` is `"12"`. Convert explicitly before doing arithmetic, and validate the conversion.',
    deepAnswer: [
      'The DOM `value` property is defined as a string. `type="number"` constrains what the user can type and enables the spinner, but it does not change the property type — the same is true of `type="date"` and `type="range"`.',
      'Because `+` is overloaded, string operands make it concatenate rather than add. Notice that `-`, `*` and `/` would have coerced to number and appeared to work, which is why this bug often shows up only in the one place that uses `+`.',
      'Convert at the boundary, once, and validate there:\n\n```js\nconst current = Number(quantityInput.value);\nconst added = Number(otherInput.value);\n\nif (!Number.isFinite(current) || !Number.isFinite(added)) {\n  return showError("Enter a valid quantity");\n}\n\ntotal.textContent = String(current + added);\n```',
      '`valueAsNumber` is the purpose-built alternative for numeric and date inputs: `quantityInput.valueAsNumber` returns a number directly, and `NaN` when the field is empty or invalid — which is a cleaner signal than `Number("")` returning `0`.',
      'The general principle: convert once, at the edge where data enters, and keep the interior of your code working in real types. Scattering `Number(...)` through business logic is a sign the boundary is in the wrong place.',
      'For money specifically, do not sum floats. Parse to integer minor units — cents — do the arithmetic there, and format only when writing back to the DOM.',
    ],
    keyPoints: [
      '`input.value` is always a string, including for `type="number"`',
      '`+` concatenates when either operand is a string',
      '`-`, `*`, `/` coerce, which is why only `+` misbehaves',
      '`valueAsNumber` gives a number and `NaN` for empty, unlike `Number("")`',
      'Convert and validate once at the boundary; use integer cents for money',
    ],
    commonMistakes: [
      'Assuming `type="number"` makes `value` a number.',
      'Using `parseInt` without a radix, or without checking the result.',
    ],
    followUps: ['Why does subtraction appear to work?', 'What does `valueAsNumber` return for an empty field?'],
  },

  {
    id: 'iv-dbg-recursion-no-base',
    question: 'This crashes with "Maximum call stack size exceeded" on some inputs. Why, and how do you make it safe?',
    topic: TOPIC,
    level: L.INTERMEDIATE,
    kind: K.DEBUGGING,
    topicIds: ['recursion', 'debugging'],
    relatedLessons: ['l-m38-02'],
    code: [
      'function flatten(node) {',
      '  return [node.value, ...node.children.flatMap(flatten)];',
      '}',
    ].join('\n'),
    shortAnswer:
      'Two problems: `node.children` is assumed always to exist, and nothing handles a cycle. A leaf with no `children` throws `TypeError`; a graph where a node reaches itself recurses forever until the stack overflows. Guard the missing field, and track visited nodes.',
    deepAnswer: [
      'The missing base case is the simpler half. `node.children.flatMap` throws immediately if `children` is `undefined` — which is the natural representation for a leaf. `const children = node.children ?? []` handles it, and recursion terminates naturally when a node has no children.',
      'The stack overflow needs a different fix, because a cycle has no depth at which it stops:\n\n```js\nfunction flatten(node, seen = new Set()) {\n  if (seen.has(node)) return [];\n  seen.add(node);\n  const children = node.children ?? [];\n  return [node.value, ...children.flatMap((child) => flatten(child, seen))];\n}\n```\n\nA `Set` of visited nodes compares by reference, which is exactly right for graph identity.',
      'Note the wrapper arrow in `flatMap`: passing `flatten` directly would hand `flatMap`\'s index as the `seen` argument — the same arity trap as `map(parseInt)`.',
      'Depth is the third consideration. Even an acyclic tree overflows if it is deep enough; engine stack limits are around 10,000 frames and are not part of the specification. For untrusted or deep data, convert to an explicit stack:\n\n```js\nfunction flatten(root) {\n  const out = [];\n  const seen = new Set();\n  const stack = [root];\n  while (stack.length > 0) {\n    const node = stack.pop();\n    if (seen.has(node)) continue;\n    seen.add(node);\n    out.push(node.value);\n    const children = node.children ?? [];\n    for (let i = children.length - 1; i >= 0; i--) stack.push(children[i]);\n  }\n  return out;\n}\n```\n\nThis has no recursion depth limit — it is bounded by heap, not by stack — at the cost of being longer to read. Note it also reverses the child push order to preserve left-to-right traversal.',
      'JavaScript engines do not implement tail-call optimisation in practice, despite it being specified — Safari is the only engine that shipped it. So "make it tail recursive" is not a portable answer; converting to iteration is.',
      'Something to say about the debugging process rather than the fix: a stack-overflow trace shows the same few frames repeating, which immediately distinguishes "missing base case" from "legitimately deep data". If the repeating cycle spans several distinct functions, suspect mutual recursion or a cycle in the data.',
    ],
    keyPoints: [
      'Missing base case: `children` may be `undefined` on a leaf',
      'A cycle recurses forever — track visited nodes in a `Set`',
      'Passing `flatten` directly to `flatMap` reintroduces the arity trap',
      'Deep-but-acyclic data still overflows; convert to an explicit stack',
      'Tail-call optimisation is specified but not implemented in practice',
    ],
    commonMistakes: [
      'Adding a depth limit instead of detecting cycles.',
      'Claiming tail recursion solves stack depth in browsers.',
    ],
    followUps: ['How would you detect a cycle without a `Set`?', 'What does a stack-overflow trace tell you?'],
  },

  {
    id: 'iv-dbg-optional-chain-swallow',
    question: 'A code review flags this "defensive" line as harmful. Why might the reviewer be right?',
    topic: TOPIC,
    level: L.ADVANCED,
    kind: K.DEBUGGING,
    topicIds: ['clean-code', 'errors', 'debugging'],
    relatedLessons: ['l-m21-04'],
    code: [
      'function renderTotal(order) {',
      '  const total = order?.summary?.total ?? 0;',
      '  element.textContent = formatMoney(total);',
      '}',
    ].join('\n'),
    shortAnswer:
      'It converts a missing or malformed order into a confident display of `$0.00`. Optional chaining is right at genuine optional boundaries, but here it hides a data bug behind a plausible-looking number — which is worse than an error, because nobody investigates a total that renders fine.',
    deepAnswer: [
      'The question to ask of every `?.` is: **is absence expected here?** If `summary` is legitimately optional — a draft order that has not been priced yet — the chain is correct and `0` may be the right display. If `summary` should always be present by the time this renders, the chain is silently absorbing a broken invariant.',
      'The failure mode is specifically bad because it is plausible. A thrown error produces a stack trace pointing at the exact property; a rendered `$0.00` produces a support ticket six weeks later saying "the totals are sometimes wrong", with nothing to trace.',
      'The alternative is to be explicit about which case you are in:\n\n```js\nfunction renderTotal(order) {\n  if (!order?.summary) {\n    renderPending();\n    return;\n  }\n  element.textContent = formatMoney(order.summary.total);\n}\n```\n\nNow "not priced yet" has its own visible state, and a malformed order still throws where the mistake is.',
      'The same critique applies to a blanket `try`/`catch` that returns a default, and to `||` defaulting on a value that should never be falsy. The shared anti-pattern is treating "make the error go away" as equivalent to "handle the error".',
      'Where optional chaining genuinely earns its place: reading from a response whose schema legitimately varies, an event target that may be `null`, an optional callback (`options.onDone?.()`), or DOM lookups that may not match. In those cases absence is part of the contract, not a symptom.',
      'A pragmatic middle ground for a case like this is to default **and** report: render `0`, but log or increment a metric so the invariant violation is visible. Resilient for the user, still observable for you — which is usually the right shape for anything user-facing.',
      'The reviewer\'s deeper point is about where validation belongs. If orders are validated once at the boundary where they enter the app, the interior can read `order.summary.total` directly and any violation surfaces at the edge with full context. Scattered `?.` throughout the interior is a sign the boundary check is missing.',
    ],
    keyPoints: [
      'Ask whether absence is expected — if not, `?.` hides a broken invariant',
      'A plausible wrong value is worse than a loud error',
      'Give "legitimately absent" its own explicit state',
      'Same critique applies to blanket `try`/`catch` and `||` defaults',
      'Default **and** report when the UI must stay resilient',
      'Scattered `?.` in the interior usually means the boundary check is missing',
    ],
    commonMistakes: [
      'Treating optional chaining as universally good defensive practice.',
      'Equating "no error is thrown" with "the error is handled".',
    ],
    followUps: ['Where is optional chaining clearly correct?', 'Where should the validation for this live instead?'],
  },

  {
    id: 'iv-dbg-test-time-dependent',
    question: 'This test passes locally and fails in CI about once a week. Diagnose and fix.',
    topic: TOPIC,
    level: L.ADVANCED,
    kind: K.DEBUGGING,
    topicIds: ['testing', 'dates', 'debugging'],
    relatedLessons: ['l-m42-02'],
    code: [
      'test("expires after 30 days", () => {',
      '  const created = new Date();',
      '  const token = createToken(created);',
      '',
      '  expect(isExpired(token, new Date())).toBe(false);',
      '  expect(token.expiresAt.getMonth()).toBe(created.getMonth() + 1);',
      '});',
    ].join('\n'),
    shortAnswer:
      'The test depends on the real clock. `getMonth() + 1` is wrong whenever the 30-day window lands in the same month or wraps past December, and it also breaks across daylight-saving transitions. Inject a fixed clock and assert the actual instant, not a derived calendar field.',
    deepAnswer: [
      'Three separate sources of nondeterminism are in play. Real "now" varies, so the arithmetic lands differently depending on the date CI happens to run. `getMonth() + 1` overflows: run it in December and `created.getMonth() + 1` is `12`, which is not a valid month index — the assertion compares against a number `getMonth()` can never return. And in a timezone with daylight saving, 30 days is not always 720 hours, so a naive day-count can be off by an hour and cross a date boundary.',
      'The fix is to make time an input rather than an ambient global:\n\n```js\ntest("expires 30 days after creation", () => {\n  const created = new Date("2024-01-15T12:00:00Z");\n  const token = createToken(created);\n\n  expect(token.expiresAt.toISOString()).toBe("2024-02-14T12:00:00.000Z");\n  expect(isExpired(token, new Date("2024-02-13T12:00:00Z"))).toBe(false);\n  expect(isExpired(token, new Date("2024-02-15T12:00:00Z"))).toBe(true);\n});\n```\n\nA fixed instant makes the expected value a constant you can compute by hand, and comparing ISO strings in UTC removes the timezone variable entirely.',
      'Note the test now also checks the **boundary on both sides**. The original only asserted "not expired", which would still pass if `isExpired` always returned `false`. Testing one side of a threshold is a common way to write a test that cannot fail.',
      'If the production code calls `Date.now()` internally rather than accepting a date, that is the real defect and the test is only revealing it. Injecting the clock — a `now = () => Date.now()` parameter, or a `Clock` dependency — makes the code testable and is the change worth arguing for. Fake timers (`vi.useFakeTimers`, `jest.useFakeTimers`) are the alternative when you cannot change the signature.',
      'Pin the environment too: run CI with a fixed `TZ` so a machine in a different region does not produce different results from a developer laptop.',
      'The general rule for flaky tests: find the ambient input. Clock, timezone, locale, random numbers, network, filesystem ordering, test execution order and shared state between tests are the usual suspects. "Passes locally, fails weekly in CI" is almost always the clock or a date boundary.',
    ],
    keyPoints: [
      'The test reads the real clock — the result depends on the run date',
      '`getMonth() + 1` overflows in December and assumes month-length arithmetic',
      'Daylight saving means 30 days is not always 720 hours',
      'Inject the clock; assert a fixed ISO instant, and test both sides of the boundary',
      'Pin `TZ` in CI; flakiness usually traces to an ambient input',
    ],
    commonMistakes: [
      'Fixing the assertion arithmetic while leaving the real clock in place.',
      'Asserting only the "not expired" side, leaving a test that cannot fail.',
    ],
    followUps: ['How would you inject a clock into existing code?', 'What are the other usual causes of flaky tests?'],
  },
];

export default questions;
