/**
 * The content registry — the single way the application reads content.
 *
 * Two tiers:
 *
 *  1. **Manifest** (statically imported, small). Titles, counts, difficulty,
 *     relationships, search keywords. Every list screen reads only this, so the
 *     curriculum, dashboard, search and practice hub render instantly without
 *     pulling a single lesson body into the bundle.
 *  2. **Bodies** (lazily imported). Full lessons, exercises, challenges, projects
 *     and so on, fetched on demand from per-module chunks.
 *
 * The manifest is generated by `scripts/generate-manifest.mjs` from the authored
 * content, and regenerated by `predev` / `prebuild`, so it cannot go stale.
 */
import manifest from './generated/manifest.json';

/* Lazy module loaders. Vite turns these globs into separate chunks. */
const loaders = {
  ...import.meta.glob('./curriculum/**/*.js'),
  ...import.meta.glob('./exercises/**/*.js'),
  ...import.meta.glob('./challenges/**/*.js'),
  ...import.meta.glob('./projects/**/*.js'),
  ...import.meta.glob('./interview/**/*.js'),
  ...import.meta.glob('./references/**/*.js'),
  ...import.meta.glob('./cheat-sheets/**/*.js'),
};

const fileCache = new Map();

/** Convert a manifest `source` path into a glob key relative to this file. */
function globKey(source) {
  return './' + String(source).replace(/^src\/content\//, '');
}

async function loadFile(source) {
  const key = globKey(source);
  if (fileCache.has(key)) return fileCache.get(key);
  const loader = loaders[key];
  if (!loader) throw new Error(`Content file not found: ${source}`);
  const promise = loader().then((mod) => [].concat(mod.default ?? mod.lessons ?? mod.questions ?? []));
  fileCache.set(key, promise);
  return promise;
}

/* ------------------------------------------------------------------ *
 * Metadata (synchronous)
 * ------------------------------------------------------------------ */

export const modules = manifest.modules;
export const lessons = manifest.lessons;
export const exercises = manifest.exercises;
export const challenges = manifest.challenges;
export const projects = manifest.projects;
export const interviewQuestions = manifest.interview;
export const references = manifest.references;
export const cheatSheets = manifest.cheatSheets;
export const topics = manifest.topics;

const index = (arr, key = 'id') => Object.fromEntries(arr.map((x) => [x[key], x]));

export const moduleById = index(modules);
export const moduleBySlug = index(modules, 'slug');
export const lessonById = index(lessons);
export const lessonBySlug = index(lessons, 'slug');
export const exerciseById = index(exercises);
export const challengeById = index(challenges);
export const challengeBySlug = index(challenges, 'slug');
export const projectById = index(projects);
export const projectBySlug = index(projects, 'slug');
export const interviewById = index(interviewQuestions);
export const referenceById = index(references);
export const referenceBySlug = index(references, 'slug');
export const cheatSheetById = index(cheatSheets);
export const cheatSheetBySlug = index(cheatSheets, 'slug');
export const topicById = index(topics);

/** Quizzes live inside lessons; this maps a quiz id back to its lesson. */
export const quizToLesson = Object.fromEntries(
  lessons.filter((l) => l.quizId).map((l) => [l.quizId, l.id]),
);

/**
 * Lightweight quiz metadata for the mastery engine, which needs to know which
 * topics each question covers without loading every lesson body.
 * Question-level topics are stored on the lesson in the manifest.
 */
export const quizIndex = lessons
  .filter((l) => l.quizId)
  .map((l) => ({ id: l.quizId, lessonId: l.id, moduleId: l.moduleId, topicIds: l.topicIds }));

export const lessonsByModule = modules.reduce((acc, m) => {
  acc[m.id] = m.lessonIds.map((id) => lessonById[id]).filter(Boolean);
  return acc;
}, {});

/** Ordered flat lesson list — powers previous/next navigation across modules. */
export const lessonOrder = modules.flatMap((m) => m.lessonIds);

export function adjacentLessons(lessonId) {
  const i = lessonOrder.indexOf(lessonId);
  if (i === -1) return { previous: null, next: null };
  return {
    previous: i > 0 ? lessonById[lessonOrder[i - 1]] : null,
    next: i < lessonOrder.length - 1 ? lessonById[lessonOrder[i + 1]] : null,
  };
}

/** The manifest slice the mastery and achievement engines expect. */
export const contentIndex = {
  modules,
  lessons,
  exercises,
  challenges,
  projects,
  topics,
  quizzes: quizIndex,
};

/* ------------------------------------------------------------------ *
 * Bodies (asynchronous)
 * ------------------------------------------------------------------ */

async function findInFile(source, id) {
  const items = await loadFile(source);
  const found = items.find((x) => x.id === id);
  if (!found) throw new Error(`"${id}" was not found in ${source}`);
  return found;
}

export async function getLesson(lessonId) {
  const meta = lessonById[lessonId];
  if (!meta) throw new Error(`Unknown lesson: ${lessonId}`);
  return findInFile(meta.source, lessonId);
}

export async function getLessonBySlug(slug) {
  const meta = lessonBySlug[slug];
  if (!meta) throw new Error(`Unknown lesson: ${slug}`);
  return getLesson(meta.id);
}

export async function getExercise(exerciseId) {
  const meta = exerciseById[exerciseId];
  if (!meta) throw new Error(`Unknown exercise: ${exerciseId}`);
  // Inline exercises live inside their lesson; standalone ones are top-level.
  if (meta.lessonId) {
    const lesson = await getLesson(meta.lessonId);
    const found = (lesson.exercises ?? []).find((e) => e.id === exerciseId);
    if (found) return found;
  }
  return findInFile(meta.source, exerciseId);
}

export async function getQuiz(quizId) {
  const lessonId = quizToLesson[quizId];
  if (!lessonId) throw new Error(`Unknown quiz: ${quizId}`);
  const lesson = await getLesson(lessonId);
  return lesson.quiz;
}

export async function getChallenge(challengeId) {
  const meta = challengeById[challengeId];
  if (!meta) throw new Error(`Unknown challenge: ${challengeId}`);
  return findInFile(meta.source, challengeId);
}

export async function getProject(projectId) {
  const meta = projectById[projectId];
  if (!meta) throw new Error(`Unknown project: ${projectId}`);
  return findInFile(meta.source, projectId);
}

export async function getInterviewQuestion(id) {
  const meta = interviewById[id];
  if (!meta) throw new Error(`Unknown interview question: ${id}`);
  return findInFile(meta.source, id);
}

export async function getReference(id) {
  const meta = referenceById[id];
  if (!meta) throw new Error(`Unknown reference entry: ${id}`);
  return findInFile(meta.source, id);
}

export async function getCheatSheet(id) {
  const meta = cheatSheetById[id];
  if (!meta) throw new Error(`Unknown cheat sheet: ${id}`);
  return findInFile(meta.source, id);
}

/** Load several interview questions at once — used by interview sessions. */
export async function getInterviewQuestions(ids) {
  return Promise.all(ids.map((id) => getInterviewQuestion(id)));
}

export async function getChallenges(ids) {
  return Promise.all(ids.map((id) => getChallenge(id)));
}

export const contentStats = {
  modules: modules.length,
  lessons: lessons.length,
  exercises: exercises.length,
  quizQuestions: lessons.reduce((n, l) => n + l.quizQuestionCount, 0),
  challenges: challenges.length,
  projects: projects.length,
  interviewQuestions: interviewQuestions.length,
  references: references.length,
  cheatSheets: cheatSheets.length,
  totalMinutes: lessons.reduce((n, l) => n + l.estimatedMinutes, 0),
};

export { manifest };
