import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm12';

export default [
  /* ================================================================== */
  {
    id: 'l-m12-01',
    slug: 'creating-and-accessing-arrays',
    moduleId: M,
    order: 1,
    title: 'Creating and Accessing Arrays',
    description: 'Why ordered collections exist, zero-based indexing, length, and reading past the end.',
    difficulty: DIFFICULTY.BEGINNER,
    estimatedMinutes: 15,
    xp: 30,
    topicIds: ['arrays'],
    prerequisites: ['l-m11-05'],
    learningObjectives: [
      'Create arrays with literals and explain when `Array()` is needed',
      'Read and write elements by index, including with `at()`',
      'Explain how `length` behaves and that it is writable',
      'Work with nested arrays',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          'An **array** is an ordered collection. You met the basics in Module 02 — arrays are objects with numeric keys — and used them throughout the loops module. This module makes them precise, because arrays are the data structure you will use most.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Creating arrays',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The literal is almost always what you want.',
        code: [
          'const empty = [];',
          'const numbers = [1, 2, 3];',
          'const mixed = [1, "two", true, null, { a: 1 }, [2]];',
          '',
          'console.log(numbers, numbers.length);',
          'console.log(mixed.length);',
          '',
          '// Trailing commas are allowed and keep diffs clean',
          'const tidy = [',
          '  "first",',
          '  "second",',
          '];',
          'console.log(tidy.length);',
        ].join('\n'),
        output: ['[1, 2, 3] 3', '6', '2'].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'The `Array()` constructor is inconsistent',
        body: [
          '`Array(3)` creates an array of **length 3 with no elements** — not `[3]`. But `Array(1, 2, 3)` creates `[1, 2, 3]`. A single numeric argument means "this length"; anything else means "these elements".',
          'That inconsistency is why the literal `[]` is the default. When you genuinely need a sized array, `Array.from({ length: 3 }, (_, i) => i)` or `Array(3).fill(0)` is clearer and produces real elements.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Empty slots are not the same as `undefined` values.',
        code: [
          'const sized = Array(3);',
          'console.log(sized.length, sized[0]);',
          '',
          '// Empty slots are skipped by most array methods',
          'console.log("map over empty slots:", sized.map(() => "x"));',
          '',
          '// fill creates real elements',
          'const filled = Array(3).fill(0);',
          'console.log("filled:", filled, filled.map(() => "x"));',
          '',
          '// Array.from can build from an index',
          'console.log("from  :", Array.from({ length: 4 }, (_, i) => i * 10));',
        ].join('\n'),
        output: [
          '3 undefined',
          'map over empty slots: [undefined, undefined, undefined]',
          'filled: [0, 0, 0] ["x", "x", "x"]',
          'from  : [0, 10, 20, 30]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Look closely at the second line. Mapping over `Array(3)` produced no `"x"` values at all — the callback was **never called**, because there are no elements to visit. The empty slots simply survived the map. `Array(3).fill(0)` creates three actual elements, and the map then works normally, producing three `"x"` values.',
          'A caveat about that output: this console prints an empty slot as `undefined`, which makes it look like an ordinary value. Browser devtools show `<3 empty items>` instead, and Node prints `[ <3 empty items> ]`. The distinction is real even when the display hides it — which is a good reason to avoid `Array(n)` on its own.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Indexes and access',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Zero-based, with `at()` for counting from the end.',
        code: [
          'const fruits = ["apple", "banana", "cherry"];',
          '',
          'console.log(fruits[0]);',
          'console.log(fruits[2]);',
          'console.log(fruits[fruits.length - 1]);',
          'console.log(fruits.at(-1));',
          'console.log(fruits.at(-2));',
          '',
          '// Reading past the end gives undefined, not an error',
          'console.log(fruits[10]);',
          'console.log(fruits[-1]);',
        ].join('\n'),
        output: [
          'apple',
          'cherry',
          'cherry',
          'cherry',
          'banana',
          'undefined',
          'undefined',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: '`at(-1)` versus `[-1]`',
        body: [
          'Bracket access with a negative number does **not** count from the end — `fruits[-1]` looks for a property literally named `"-1"`, finds none, and gives `undefined`.',
          '`at()` was added in ES2022 specifically to support negative indexes, so `fruits.at(-1)` is the readable way to get the last element. It works on strings too, as Module 05 covered.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Modifying by index',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Assigning past the end creates gaps.',
        code: [
          'const items = ["a", "b"];',
          '',
          'items[0] = "changed";',
          'console.log(items);',
          '',
          '// Assigning beyond the end extends the array with empty slots',
          'items[4] = "far";',
          'console.log(items, items.length);',
          'console.log("index 2 is", items[2]);',
        ].join('\n'),
        output: [
          '["changed", "b"]',
          '["changed", "b", undefined, undefined, "far"] 5',
          'index 2 is undefined',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Assigning to an index beyond the current end silently extends `length` and leaves empty slots at indexes 2 and 3. As above, this console shows them as `undefined`; browser devtools would show `<2 empty items>`. Either way the array now has a length of 5 and two positions that were never deliberately set.',
          'This is almost never intentional — use `push` to add to the end, which cannot create a gap.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: '`length` is writable',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Setting `length` truncates or extends.',
        code: [
          'const nums = [1, 2, 3, 4, 5];',
          '',
          'nums.length = 3;',
          'console.log("truncated:", nums);',
          '',
          'nums.length = 0;',
          'console.log("emptied  :", nums, nums.length);',
        ].join('\n'),
        output: [
          'truncated: [1, 2, 3]',
          'emptied  : [] 0',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Setting `length = 0` is a genuine idiom for emptying an array **in place**, which matters when other code holds a reference to the same array. If you can simply rebind, `arr = []` is clearer.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Nested arrays',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'An array of arrays models a grid.',
        code: [
          'const grid = [',
          '  [1, 2, 3],',
          '  [4, 5, 6],',
          '  [7, 8, 9],',
          '];',
          '',
          'console.log("row 1   :", grid[1]);',
          'console.log("row 1 col 2:", grid[1][2]);',
          'console.log("rows    :", grid.length);',
          'console.log("cols    :", grid[0].length);',
          '',
          '// Reading a whole column needs a loop over rows',
          'const column = [];',
          'for (const row of grid) {',
          '  column.push(row[0]);',
          '}',
          'console.log("column 0:", column);',
        ].join('\n'),
        output: [
          'row 1   : [4, 5, 6]',
          'row 1 col 2: 6',
          'rows    : 3',
          'cols    : 3',
          'column 0: [1, 4, 7]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: '`fill` with an array shares one reference',
        body: [
          '`Array(3).fill([])` produces three references to the **same** array, so pushing into one appears to affect all three. This is the reference behaviour from Module 02 biting in a very confusing way.',
          'Build rows individually instead: `Array.from({ length: 3 }, () => [])` calls the function once per row and produces three distinct arrays.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The shared-reference trap, and the fix.',
        code: [
          'const shared = Array(3).fill([]);',
          'shared[0].push("x");',
          'console.log("shared:", shared);',
          '',
          'const distinct = Array.from({ length: 3 }, () => []);',
          'distinct[0].push("x");',
          'console.log("distinct:", distinct);',
        ].join('\n'),
        output: [
          'shared: [["x"], ["x"], ["x"]]',
          'distinct: [["x"], [], []]',
        ].join('\n'),
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const a = ["x", "y", "z"];',
          '',
          'console.log(a[1], a.at(-1), a[-1], a[5]);',
        ].join('\n'),
        options: [
          'y z undefined undefined',
          'y z x undefined',
          'x z undefined undefined',
          'y y undefined undefined',
        ],
        correct: 0,
        explanation:
          '`a[1]` is the second element, `"y"`, since indexes are zero-based. `a.at(-1)` counts from the end and gives `"z"`. `a[-1]` does **not** count from the end — bracket access looks for a property named `"-1"`, which does not exist, so it gives `undefined`. And `a[5]` is past the end, also `undefined`. Reading a missing index never throws; it quietly yields `undefined`.',
      },
    ],
    exercises: [
      {
        id: 'ex-m12-01-a',
        title: 'Predict the Array constructor',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.EASY,
        xp: 10,
        topicIds: ['arrays'],
        instructions: 'What does this print?',
        code: ['console.log(Array(3).length, Array(1, 2, 3).length);'].join('\n'),
        options: ['3 3', '1 3', '3 1', '1 1'],
        correct: 0,
        hints: [
          'A single numeric argument is treated as a length.',
          'Multiple arguments are treated as elements.',
        ],
        solution: '3 3',
        solutionExplanation:
          '`Array(3)` creates an array of length 3 containing no actual elements — empty slots rather than `undefined` values. `Array(1, 2, 3)` creates `[1, 2, 3]`, which also has length 3. The lengths coincide here, but the arrays are quite different: the first has nothing to iterate, so `map` and `forEach` skip every slot. That inconsistency between one argument and several is why array literals are preferred.',
      },
      {
        id: 'ex-m12-01-b',
        title: 'Get the last element safely',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.BEGINNER,
        xp: 15,
        topicIds: ['arrays'],
        instructions:
          'Write `lastOf(items)` returning the final element, or `null` if the array is empty. Do not use `pop`, which would modify the array.',
        starterCode: [
          'function lastOf(items) {',
          '  // at(-1) reads from the end without modifying anything.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'returns the last element', body: 'expect(lastOf([1, 2, 3])).toBe(3);' },
          { name: 'works with one element', body: 'expect(lastOf(["only"])).toBe("only");' },
          { name: 'returns null for an empty array', body: 'expect(lastOf([])).toBe(null);' },
          { name: 'does not modify the array', body: 'const a = [1, 2]; lastOf(a); expect(a.length).toBe(2);' },
          { name: 'handles a falsy last element', body: 'expect(lastOf([1, 0])).toBe(0);', hidden: true },
        ],
        hints: [
          '`items.at(-1)` gives the last element, or `undefined` when empty.',
          'Convert that `undefined` to `null` — but be careful not to convert a legitimate falsy element.',
          '`items.length === 0` is the reliable emptiness test.',
        ],
        solution: [
          'function lastOf(items) {',
          '  if (items.length === 0) return null;',
          '  return items.at(-1);',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Checking `length` explicitly rather than testing the returned value is what makes the hidden test pass. A version like `return items.at(-1) ?? null;` would work for `undefined`, but `return items.at(-1) || null;` would wrongly convert a legitimate last element of `0` into `null`. `at(-1)` reads without modifying, unlike `pop`, which would remove the element and shorten the caller\'s array — the fourth test guards against that.',
      },
      {
        id: 'ex-m12-01-c',
        title: 'Build a grid',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['arrays'],
        instructions:
          'Write `makeGrid(rows, cols, value)` returning a nested array of the given dimensions, every cell holding `value`. Each row must be an independent array — modifying one row must not affect the others.',
        starterCode: [
          'function makeGrid(rows, cols, value) {',
          '  // Careful: Array(n).fill([]) shares one array across every row.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'builds the right shape', body: 'const g = makeGrid(2, 3, 0); expect(g.length).toBe(2); expect(g[0].length).toBe(3);' },
          { name: 'fills every cell', body: 'expect(makeGrid(2, 2, "x")).toEqual([["x", "x"], ["x", "x"]]);' },
          { name: 'rows are independent', body: 'const g = makeGrid(2, 2, 0); g[0][0] = 9; expect(g[1][0]).toBe(0);' },
          { name: 'handles a single cell', body: 'expect(makeGrid(1, 1, 5)).toEqual([[5]]);' },
          { name: 'handles zero rows', body: 'expect(makeGrid(0, 3, 0)).toEqual([]);' },
          { name: 'pushing to one row does not affect others', body: 'const g = makeGrid(2, 1, 0); g[0].push(1); expect(g[1].length).toBe(1);', hidden: true },
        ],
        hints: [
          '`Array.from({ length: rows }, ...)` calls its function once per row.',
          'Each call should build a fresh row array.',
          '`Array(cols).fill(value)` is safe here because `value` is copied per cell when it is a primitive.',
        ],
        solution: [
          'function makeGrid(rows, cols, value) {',
          '  return Array.from({ length: rows }, () => Array(cols).fill(value));',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`Array.from` with a mapping function calls that function once per row, so each row is a brand-new array — which is exactly what the independence tests check. Using `Array(rows).fill(Array(cols).fill(value))` would evaluate the inner expression **once** and store the same reference in every row, so `g[0][0] = 9` would appear to change every row. Note the inner `fill(value)` is safe for primitives; if `value` were an object every cell would share it, and you would need a mapping function there too.',
      },
    ],
    quiz: {
      id: 'qz-m12-01',
      questions: [
        {
          id: 'q-m12-01-1',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['arrays'],
          prompt: 'What do these two accesses give?',
          code: [
            'const a = ["x", "y"];',
            'console.log(a[-1], a.at(-1));',
          ].join('\n'),
          options: ['y y', 'undefined y', 'undefined undefined', 'x y'],
          correct: 1,
          optionExplanations: [
            'Bracket access does not support negative indexes.',
            'Correct — only `at()` counts from the end.',
            '`at(-1)` does work.',
            'Neither gives the first element.',
          ],
          explanation:
            'Bracket notation with `-1` looks for a property literally named `"-1"`, which does not exist, so it gives `undefined`. `at(-1)` was added specifically to count from the end and returns the last element.',
        },
        {
          id: 'q-m12-01-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['arrays'],
          prompt: 'What does `Array(3)` create?',
          options: [
            'The array `[3]`',
            'An array of length 3 with three empty slots and no elements',
            'An array `[0, 1, 2]`',
            'An array `[undefined, undefined, undefined]` with real elements',
          ],
          correct: 1,
          optionExplanations: [
            'A single numeric argument sets the length rather than becoming an element.',
            'Correct — the slots are empty, not filled with `undefined`.',
            'No values are generated.',
            'Reading a slot gives `undefined`, but the slots are genuinely empty and are skipped by array methods.',
          ],
          explanation:
            'A single numeric argument to `Array()` sets the length and creates empty slots. Those slots are skipped by `map` and `forEach`, which is why `Array(3).map(() => "x")` still yields empty slots. Use `Array(3).fill(0)` or `Array.from` to create real elements.',
        },
        {
          id: 'q-m12-01-3',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['arrays'],
          prompt: 'Why do all three rows change?',
          code: [
            'const g = Array(3).fill([]);',
            'g[0].push(1);',
            'console.log(g[2].length);',
          ].join('\n'),
          options: ['0', '1', '3', 'undefined'],
          correct: 1,
          optionExplanations: [
            'They are not independent arrays.',
            'Correct — `fill` stored one reference three times.',
            'Only one push happened.',
            'The row is a real array with a length.',
          ],
          explanation:
            '`fill([])` evaluates the empty array literal once and stores that single reference in all three slots, so every row is the same array. Pushing through one is visible through all of them. Use `Array.from({ length: 3 }, () => [])`, which calls the function per row and produces distinct arrays.',
        },
      ],
    },
    summary:
      'Arrays are ordered collections created most reliably with a literal, because the `Array()` constructor treats a single numeric argument as a length and anything else as elements. `Array(n)` produces empty slots that array methods skip entirely, so use `fill` or `Array.from` when you need real elements. Indexes are zero-based; bracket access with a negative number does not count from the end, which is why `at(-1)` exists. Reading a missing index gives `undefined` rather than throwing, and assigning past the end silently extends `length` and leaves gaps. `length` is writable — setting it truncates, and `length = 0` empties an array in place. Nested arrays model grids, but `fill` with an array or object stores one shared reference, so rows must be built individually.',
    keyTakeaways: [
      'Prefer array literals; `Array(3)` makes empty slots, not elements',
      'Indexes are zero-based; `a[-1]` is `undefined` but `a.at(-1)` is the last element',
      'Reading a missing index gives `undefined` and never throws',
      '`length` is writable — `length = 0` empties in place',
      '`Array(n).fill([])` shares one array; use `Array.from` with a function',
    ],
    relatedLessons: ['l-m11-05', 'l-m12-02'],
    interviewConnections: [
      'What is the difference between a[-1] and a.at(-1)?',
      'What does Array(3) create?',
      'Why does Array(3).fill([]) behave unexpectedly?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m12-02',
    slug: 'mutating-methods',
    moduleId: M,
    order: 2,
    title: 'Methods That Mutate',
    description: 'push, pop, shift, unshift, splice, sort and reverse — every one changes the original array.',
    difficulty: DIFFICULTY.EASY,
    estimatedMinutes: 17,
    xp: 35,
    topicIds: ['arrays'],
    prerequisites: ['l-m12-01'],
    learningObjectives: [
      'Add and remove elements at either end of an array',
      'Use `splice` to insert, remove or replace at any position',
      'State what each mutating method returns, which is rarely the array',
      'Explain why mutation is visible to every holder of the array',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          'Array methods divide cleanly into two groups: those that **change the array they are called on**, and those that **return a new array and leave the original alone**. Knowing which is which prevents a large share of real bugs.',
          'This lesson covers the mutating group. The next covers the non-mutating group, and lesson 4 puts them side by side.',
        ],
      },
      {
        kind: SECTION.TABLE,
        headers: ['Method', 'Does', 'Returns'],
        rows: [
          ['`push(...items)`', 'Adds to the **end**', 'The new length'],
          ['`pop()`', 'Removes from the **end**', 'The removed element'],
          ['`unshift(...items)`', 'Adds to the **start**', 'The new length'],
          ['`shift()`', 'Removes from the **start**', 'The removed element'],
          ['`splice(start, count, ...items)`', 'Removes and/or inserts anywhere', 'An array of removed elements'],
          ['`sort(compare)`', 'Reorders in place', 'The same array'],
          ['`reverse()`', 'Reverses in place', 'The same array'],
          ['`fill(value, start, end)`', 'Overwrites a range', 'The same array'],
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'Most of them do not return the array',
        body: [
          '`push` returns the new **length**, not the array — so `const result = arr.push(1)` gives you a number. Chaining `arr.push(1).push(2)` throws, because numbers have no `push`.',
          '`pop` and `shift` return the **removed element**. Only `sort`, `reverse` and `fill` return the array itself, which is why only those three chain.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Adding and removing at the ends',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Note what each call evaluates to.',
        code: [
          'const stack = ["a", "b"];',
          '',
          'console.log("push returns:", stack.push("c"));',
          'console.log("array now  :", stack);',
          '',
          'console.log("pop returns :", stack.pop());',
          'console.log("array now  :", stack);',
          '',
          'console.log("unshift ret :", stack.unshift("start"));',
          'console.log("array now  :", stack);',
          '',
          'console.log("shift returns:", stack.shift());',
          'console.log("array now  :", stack);',
        ].join('\n'),
        output: [
          'push returns: 3',
          'array now  : ["a", "b", "c"]',
          'pop returns : c',
          'array now  : ["a", "b"]',
          'unshift ret : 3',
          'array now  : ["start", "a", "b"]',
          'shift returns: start',
          'array now  : ["a", "b"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'End operations are cheaper than start operations',
        body: [
          '`push` and `pop` work at the end, so nothing else moves. `shift` and `unshift` work at the start, so **every remaining element must be reindexed** — an O(n) operation rather than O(1).',
          'For a few dozen items this is irrelevant. For a queue processing hundreds of thousands, repeatedly calling `shift` becomes a genuine bottleneck, and an index pointer or a different structure is better.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'splice: the general-purpose editor',
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`splice(start, deleteCount, ...itemsToInsert)` can remove, insert, or do both at any position. It is the most flexible mutating method and the easiest to misread.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Remove, insert, replace — and what comes back.',
        code: [
          '// Remove 2 elements starting at index 1',
          'const a = ["a", "b", "c", "d"];',
          'console.log("removed:", a.splice(1, 2));',
          'console.log("left   :", a);',
          '',
          '// Insert without removing: deleteCount of 0',
          'const b = ["a", "d"];',
          'b.splice(1, 0, "b", "c");',
          'console.log("inserted:", b);',
          '',
          '// Replace: remove 1, insert 1',
          'const c = ["a", "X", "c"];',
          'c.splice(1, 1, "b");',
          'console.log("replaced:", c);',
          '',
          '// Remove everything from an index onwards: omit deleteCount',
          'const d = ["a", "b", "c", "d"];',
          'd.splice(2);',
          'console.log("trimmed :", d);',
        ].join('\n'),
        output: [
          'removed: ["b", "c"]',
          'left   : ["a", "d"]',
          'inserted: ["a", "b", "c", "d"]',
          'replaced: ["a", "b", "c"]',
          'trimmed : ["a", "b"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Omitting `deleteCount` removes everything after `start`',
        body: [
          '`splice(2)` removes from index 2 to the end. `splice(2, 0)` removes nothing. That single missing argument is the difference between trimming an array and leaving it untouched.',
          'A negative `start` counts from the end, so `splice(-1, 1)` removes the last element.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'sort mutates, and sorts as strings',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'You met this in Module 04. It belongs here too, because it is the most commonly reported array surprise and it is also a mutation.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The default comparison converts everything to strings.',
        code: [
          'const nums = [10, 9, 1, 100];',
          '',
          'console.log("default :", [...nums].sort());',
          'console.log("numeric :", [...nums].sort((a, b) => a - b));',
          'console.log("descending:", [...nums].sort((a, b) => b - a));',
          '',
          '// And it mutates',
          'const original = [3, 1, 2];',
          'const returned = original.sort((a, b) => a - b);',
          'console.log("original:", original);',
          'console.log("same object:", returned === original);',
        ].join('\n'),
        output: [
          'default : [1, 10, 100, 9]',
          'numeric : [1, 9, 10, 100]',
          'descending: [100, 10, 9, 1]',
          'original: [1, 2, 3]',
          'same object: true',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The comparator returns a number: **negative** means `a` comes first, **positive** means `b` comes first, and **zero** leaves their relative order unchanged. `a - b` is negative when `a` is smaller, giving ascending order; `b - a` reverses it.',
          'Note also `returned === original` is `true` — `sort` returns the same array it mutated, not a copy. Assigning the result does not protect the original.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Sorting objects and strings.',
        code: [
          'const people = [',
          '  { name: "Grace", age: 45 },',
          '  { name: "Ada", age: 36 },',
          '  { name: "alan", age: 41 },',
          '];',
          '',
          'const byAge = [...people].sort((a, b) => a.age - b.age);',
          'console.log("by age :", byAge.map((p) => p.name));',
          '',
          'const byName = [...people].sort((a, b) => a.name.localeCompare(b.name));',
          'console.log("by name:", byName.map((p) => p.name));',
        ].join('\n'),
        output: [
          'by age : ["Ada", "alan", "Grace"]',
          'by name: ["Ada", "alan", "Grace"]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Subtraction works for numbers but not for strings, since `"a" - "b"` is `NaN`. Use `localeCompare`, which returns a negative number, zero or a positive number exactly as a comparator requires — and handles case and accents the way a reader expects, unlike raw code-unit comparison.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Mutation is visible to everyone',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Two names, one array.',
        code: [
          'const original = ["a", "b"];',
          'const alias = original;',
          '',
          'alias.push("c");',
          '',
          'console.log("original:", original);',
          'console.log("same object:", original === alias);',
          '',
          '// Passing to a function is the same situation',
          'function addItem(list) {',
          '  list.push("added");',
          '}',
          '',
          'addItem(original);',
          'console.log("after function:", original);',
        ].join('\n'),
        output: [
          'original: ["a", "b", "c"]',
          'same object: true',
          'after function: ["a", "b", "c", "added"]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'This is the reference behaviour from Module 02. A function receiving an array receives a reference to the caller\'s array, so mutating it is a side effect the caller feels — which is sometimes exactly what you want and sometimes a bug that takes an hour to find.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const a = [1, 2, 3];',
          'const result = a.push(4);',
          '',
          'console.log(result, a.length);',
        ].join('\n'),
        options: ['4 4', '[1,2,3,4] 4', '3 4', '4 3'],
        correct: 0,
        explanation:
          '`push` returns the **new length** of the array, not the array itself and not the pushed element. After adding `4` the array has four elements, so `push` returns `4` and `a.length` is also `4` — the two values coincide here by arithmetic, not by meaning. This is why `const newArr = arr.push(x)` is a common bug: it stores a number where an array was expected.',
      },
    ],
    exercises: [
      {
        id: 'ex-m12-02-a',
        title: 'Predict the push return',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.BEGINNER,
        xp: 10,
        topicIds: ['arrays'],
        instructions: 'What does this print?',
        code: [
          'const a = ["x"];',
          'console.log(a.push("y"));',
        ].join('\n'),
        options: ['["x", "y"]', '2', '"y"', 'undefined'],
        correct: 1,
        hints: [
          '`push` does not return the array.',
          'What number would be useful to know after adding an element?',
        ],
        solution: '2',
        solutionExplanation:
          '`push` returns the new length of the array, which is `2` after adding a second element. It does not return the array, so `const updated = arr.push(x)` gives you a number — a common bug when someone expects a new array. It also cannot be chained: `arr.push(1).push(2)` throws, because numbers have no `push` method.',
      },
      {
        id: 'ex-m12-02-b',
        title: 'Remove an item by value',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['arrays'],
        instructions:
          'Write `removeFirst(items, value)` that removes the **first** occurrence of `value` from the array in place and returns the array. If the value is absent, leave the array unchanged. Use `indexOf` and `splice`.',
        starterCode: [
          'function removeFirst(items, value) {',
          '  // Find the index, then splice it out — but only if it exists.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'removes an element', body: 'expect(removeFirst(["a", "b", "c"], "b")).toEqual(["a", "c"]);' },
          { name: 'removes only the first occurrence', body: 'expect(removeFirst(["a", "b", "a"], "a")).toEqual(["b", "a"]);' },
          { name: 'leaves the array alone when absent', body: 'expect(removeFirst(["a", "b"], "z")).toEqual(["a", "b"]);' },
          { name: 'handles an empty array', body: 'expect(removeFirst([], "a")).toEqual([]);' },
          { name: 'mutates in place', body: 'const src = ["a", "b"]; const out = removeFirst(src, "a"); expect(out).toBe(src);' },
          { name: 'removes a falsy value correctly', body: 'expect(removeFirst([1, 0, 2], 0)).toEqual([1, 2]);', hidden: true },
        ],
        hints: [
          '`indexOf` returns `-1` when the value is absent.',
          'Only call `splice` when the index is not `-1`.',
          '`splice(index, 1)` removes exactly one element.',
        ],
        solution: [
          'function removeFirst(items, value) {',
          '  const index = items.indexOf(value);',
          '',
          '  if (index !== -1) {',
          '    items.splice(index, 1);',
          '  }',
          '',
          '  return items;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The `index !== -1` guard is essential: `splice(-1, 1)` would remove the **last** element, so a missing value would silently delete something. Comparing explicitly against `-1` rather than using truthiness also matters, because index `0` is falsy — the hidden test removes a `0` at index 1, but an implementation using `if (index)` would fail to remove a value found at index 0. Returning `items` rather than a copy keeps the in-place contract that the fifth test checks.',
      },
      {
        id: 'ex-m12-02-c',
        title: 'Sort objects by a field',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['arrays'],
        instructions:
          'Write `sortByPrice(products)` returning a **new** array sorted by ascending `price`, leaving the input untouched. Products with equal prices keep their original relative order.',
        starterCode: [
          'function sortByPrice(products) {',
          '  // sort mutates — copy first.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'sorts ascending by price', body: 'expect(sortByPrice([{ price: 30 }, { price: 10 }, { price: 20 }]).map((p) => p.price)).toEqual([10, 20, 30]);' },
          { name: 'does not modify the input', body: 'const src = [{ price: 2 }, { price: 1 }]; sortByPrice(src); expect(src[0].price).toBe(2);' },
          { name: 'returns a different array', body: 'const src = [{ price: 1 }]; expect(sortByPrice(src)).not.toBe(src);' },
          { name: 'handles an empty array', body: 'expect(sortByPrice([])).toEqual([]);' },
          { name: 'handles a single product', body: 'expect(sortByPrice([{ price: 5 }]).length).toBe(1);' },
          { name: 'handles decimal prices', body: 'expect(sortByPrice([{ price: 1.5 }, { price: 1.25 }]).map((p) => p.price)).toEqual([1.25, 1.5]);' },
          { name: 'keeps equal prices in original order', body: 'const src = [{ price: 1, id: "a" }, { price: 1, id: "b" }]; expect(sortByPrice(src).map((p) => p.id)).toEqual(["a", "b"]);', hidden: true },
        ],
        hints: [
          'Spread into a new array before sorting: `[...products]`.',
          'The comparator subtracts the two prices.',
          'Modern JavaScript sorts are stable, so equal elements keep their order automatically.',
        ],
        solution: [
          'function sortByPrice(products) {',
          '  return [...products].sort((a, b) => a.price - b.price);',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The spread is what makes this non-mutating — without it, `sort` would reorder the caller\'s array and the second test would fail. Note the spread is a *shallow* copy: the new array holds the same product objects, so mutating a product would still be visible to the caller, but reordering is not. Subtraction is the standard numeric comparator: negative means `a` first, positive means `b` first. The stable-order test passes automatically because sorting has been guaranteed stable since ES2019.',
      },
      {
        id: 'ex-m12-02-d',
        title: 'Insert at a position',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['arrays'],
        instructions:
          'Write `insertAt(items, index, ...values)` that inserts every value at the given index, in place, without removing anything, and returns the array. An index beyond the end appends; a negative index counts from the end.',
        starterCode: [
          'function insertAt(items, index, ...values) {',
          '  // splice with a deleteCount of 0 inserts without removing.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'inserts in the middle', body: 'expect(insertAt(["a", "d"], 1, "b", "c")).toEqual(["a", "b", "c", "d"]);' },
          { name: 'inserts a single value', body: 'expect(insertAt(["a", "c"], 1, "b")).toEqual(["a", "b", "c"]);' },
          { name: 'inserts at the start', body: 'expect(insertAt(["b"], 0, "a")).toEqual(["a", "b"]);' },
          { name: 'appends beyond the end', body: 'expect(insertAt(["a"], 10, "b")).toEqual(["a", "b"]);' },
          { name: 'handles a negative index', body: 'expect(insertAt(["a", "c"], -1, "b")).toEqual(["a", "b", "c"]);' },
          { name: 'inserting nothing leaves it unchanged', body: 'expect(insertAt(["a"], 0)).toEqual(["a"]);' },
          { name: 'mutates in place', body: 'const src = ["a"]; expect(insertAt(src, 0, "z")).toBe(src);', hidden: true },
        ],
        hints: [
          '`splice(index, 0, ...values)` inserts without deleting.',
          'A rest parameter collects the values into an array.',
          'Spread that array into the splice call.',
        ],
        solution: [
          'function insertAt(items, index, ...values) {',
          '  items.splice(index, 0, ...values);',
          '  return items;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The `0` as `deleteCount` is what makes this a pure insertion — omitting it entirely would remove everything from `index` onwards. The rest parameter gathers the values and the spread scatters them back into `splice`, which is the gather-then-scatter pairing from Module 08. `splice` handles the edge cases for free: an index past the end is clamped so the values append, and a negative index counts from the end, which is why those two tests pass without any extra code.',
      },
    ],
    quiz: {
      id: 'qz-m12-02',
      questions: [
        {
          id: 'q-m12-02-1',
          kind: QUIZ_KIND.MULTIPLE,
          topicIds: ['arrays'],
          prompt: 'Which of these mutate the array they are called on? (Select all that apply.)',
          options: ['`push`', '`splice`', '`sort`', '`reverse`'],
          correct: [0, 1, 2, 3],
          explanation:
            'All four mutate. `push` adds to the end, `splice` edits at any position, and `sort` and `reverse` reorder in place — `sort` even returns the same array it mutated, so assigning the result does not protect the original. The non-mutating counterparts are `concat`, `slice`, `toSorted` and `toReversed`, covered in the next lesson.',
        },
        {
          id: 'q-m12-02-2',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['arrays'],
          prompt: 'What does splice return here?',
          code: [
            'const a = ["a", "b", "c"];',
            'console.log(a.splice(1, 1));',
          ].join('\n'),
          options: ['["a", "c"]', '["b"]', '"b"', '1'],
          correct: 1,
          optionExplanations: [
            'That is what the array becomes, not what is returned.',
            'Correct — an array of the removed elements.',
            'It returns an array even for a single removal.',
            'The count is not returned.',
          ],
          explanation:
            '`splice` returns an **array** of the removed elements, even when only one was removed. The array it was called on becomes `["a", "c"]`. Confusing the return value with the resulting array is a common mistake.',
        },
        {
          id: 'q-m12-02-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['arrays'],
          prompt: 'Why does `[10, 9, 1].sort()` give `[1, 10, 9]`?',
          options: [
            'Because sort is broken for numbers',
            'Because the default comparison converts elements to strings and compares them character by character',
            'Because the array was already partly sorted',
            'Because sort only handles single digits',
          ],
          correct: 1,
          optionExplanations: [
            'It behaves exactly as specified.',
            'Correct — `"10"` sorts before `"9"` because `"1"` precedes `"9"`.',
            'Initial order does not cause this.',
            'Digit count is not the rule.',
          ],
          explanation:
            'Without a comparator, `sort` converts every element to a string and compares those. `"10"` comes before `"9"` because the first characters `"1"` and `"9"` are compared. Supply `(a, b) => a - b` for numeric order.',
        },
        {
          id: 'q-m12-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['arrays'],
          prompt: 'Why is `shift` more expensive than `pop` on a large array?',
          options: [
            '`shift` copies the whole array',
            '`shift` removes from the start, so every remaining element must be reindexed',
            '`pop` is implemented in native code and `shift` is not',
            'They cost the same',
          ],
          correct: 1,
          optionExplanations: [
            'It does not copy, but it does reindex.',
            'Correct — that makes it O(n) rather than O(1).',
            'Both are native methods.',
            'The costs genuinely differ.',
          ],
          explanation:
            '`pop` removes the last element and nothing else moves. `shift` removes the first, so every remaining element shifts down one index — proportional to the array length. Irrelevant for small arrays, but a real bottleneck for a large queue.',
        },
      ],
    },
    summary:
      'The mutating methods change the array they are called on, and that change is visible to every reference holding it — including a caller who passed the array into your function. `push` and `pop` work at the end, `unshift` and `shift` at the start, and the start operations are O(n) because everything must be reindexed. Most of these return something other than the array: `push` and `unshift` return the new **length**, `pop` and `shift` return the **removed element**, and `splice` returns an **array of removed elements**. Only `sort`, `reverse` and `fill` return the array itself. `splice(start, deleteCount, ...items)` removes and inserts anywhere; omitting `deleteCount` removes everything from `start` onward. `sort` mutates *and* compares as strings by default, so numeric sorting needs `(a, b) => a - b` and text sorting needs `localeCompare`.',
    keyTakeaways: [
      'push/pop/unshift/shift/splice/sort/reverse/fill all mutate',
      '`push` returns the new length; `pop` returns the removed element',
      '`splice` returns an array of removed elements; omitting `deleteCount` removes to the end',
      '`sort` mutates and returns the same array — copy first with spread',
      '`sort` compares as strings by default; use `a - b` or `localeCompare`',
      '`shift`/`unshift` are O(n); `push`/`pop` are O(1)',
    ],
    relatedLessons: ['l-m12-01', 'l-m12-03'],
    interviewConnections: [
      'Which array methods mutate the original?',
      'What does push return?',
      'What does splice return?',
      'Why does the default sort misorder numbers?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m12-03',
    slug: 'non-mutating-methods',
    moduleId: M,
    order: 3,
    title: 'Methods That Do Not Mutate',
    description: 'slice, concat, join, includes and the modern non-mutating replacements for sort and reverse.',
    difficulty: DIFFICULTY.EASY,
    estimatedMinutes: 16,
    xp: 35,
    topicIds: ['arrays'],
    prerequisites: ['l-m12-02'],
    learningObjectives: [
      'Extract portions of an array with `slice`, including negative indexes',
      'Combine arrays with `concat` and spread',
      'Search with `indexOf`, `lastIndexOf` and `includes`',
      'Use the modern non-mutating alternatives to `sort` and `reverse`',
    ],
    sections: [
      {
        kind: SECTION.PROSE,
        body: [
          'These methods return a **new array or value** and leave the original untouched. That makes them safe to use on data other code depends on, and it is why they chain so naturally.',
        ],
      },
      {
        kind: SECTION.TABLE,
        headers: ['Method', 'Returns', 'Original'],
        rows: [
          ['`slice(start, end)`', 'A new array — a portion', 'Unchanged'],
          ['`concat(...arrays)`', 'A new combined array', 'Unchanged'],
          ['`join(separator)`', 'A string', 'Unchanged'],
          ['`indexOf(value)`', 'A number, or `-1`', 'Unchanged'],
          ['`lastIndexOf(value)`', 'A number, or `-1`', 'Unchanged'],
          ['`includes(value)`', 'A boolean', 'Unchanged'],
          ['`toSorted(compare)`', 'A new sorted array', 'Unchanged'],
          ['`toReversed()`', 'A new reversed array', 'Unchanged'],
          ['`with(index, value)`', 'A new array with one element replaced', 'Unchanged'],
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'slice',
      },
      {
        kind: SECTION.PROSE,
        body: [
          '`slice(start, end)` copies elements from `start` up to **but not including** `end`. It follows exactly the same rules as string `slice` from Module 05, including negative indexes counting from the end.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Every form of slice.',
        code: [
          'const letters = ["a", "b", "c", "d", "e"];',
          '',
          'console.log(letters.slice(1, 3));',
          'console.log(letters.slice(2));',
          'console.log(letters.slice(-2));',
          'console.log(letters.slice(1, -1));',
          'console.log(letters.slice());',
          '',
          '// An impossible range gives an empty array',
          'console.log(letters.slice(3, 1));',
          '',
          '// The original is untouched throughout',
          'console.log("original:", letters);',
        ].join('\n'),
        output: [
          '["b", "c"]',
          '["c", "d", "e"]',
          '["d", "e"]',
          '["b", "c", "d"]',
          '["a", "b", "c", "d", "e"]',
          '[]',
          'original: ["a", "b", "c", "d", "e"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: '`slice()` with no arguments is a shallow copy',
        body: [
          'It was the standard way to copy an array before spread existed, and you will still see it constantly. `[...arr]` is now more idiomatic and reads more clearly as "a copy".',
          'Both are **shallow**: the new array holds the same objects. Mutating an object inside either array is visible through both, as Module 02 established.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Shallow copying, demonstrated.',
        code: [
          'const original = [{ n: 1 }, { n: 2 }];',
          'const copy = original.slice();',
          '',
          'console.log("different arrays:", copy !== original);',
          'console.log("same objects   :", copy[0] === original[0]);',
          '',
          '// Adding to the copy does not affect the original',
          'copy.push({ n: 3 });',
          'console.log("lengths:", original.length, copy.length);',
          '',
          '// But mutating a shared object does',
          'copy[0].n = 99;',
          'console.log("original[0].n:", original[0].n);',
        ].join('\n'),
        output: [
          'different arrays: true',
          'same objects   : true',
          'lengths: 2 3',
          'original[0].n: 99',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'Combining arrays',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: '`concat` and spread do the same job.',
        code: [
          'const a = [1, 2];',
          'const b = [3, 4];',
          '',
          'console.log(a.concat(b));',
          'console.log(a.concat(b, [5, 6]));',
          'console.log(a.concat(5));',
          '',
          '// Spread is the modern equivalent and more flexible',
          'console.log([...a, ...b]);',
          'console.log([0, ...a, 99, ...b]);',
          '',
          'console.log("originals untouched:", a, b);',
        ].join('\n'),
        output: [
          '[1, 2, 3, 4]',
          '[1, 2, 3, 4, 5, 6]',
          '[1, 2, 5]',
          '[1, 2, 3, 4]',
          '[0, 1, 2, 99, 3, 4]',
          'originals untouched: [1, 2] [3, 4]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Spread is preferred in modern code because it can place elements anywhere in the new array, not just at the ends. Note `concat` flattens one level of arrays passed to it but leaves non-array arguments alone, which is why `a.concat(5)` appends the number rather than erroring.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'join',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: '`join` produces a string, so the array is unchanged.',
        code: [
          'const parts = ["2024", "01", "15"];',
          '',
          'console.log(parts.join("-"));',
          'console.log(parts.join(""));',
          'console.log(parts.join());',
          '',
          '// null and undefined become empty strings',
          'console.log(["a", null, undefined, "b"].join("-"));',
          '',
          'console.log("original:", parts);',
        ].join('\n'),
        output: [
          '2024-01-15',
          '20240115',
          '2024,01,15',
          'a---b',
          'original: ["2024", "01", "15"]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The default separator is a comma, which is why `String([1,2,3])` gives `"1,2,3"` — it calls `join()` internally. Note that `null` and `undefined` become empty strings rather than the text `"null"`, which is different from how they behave in template literals.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Searching',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The same `-1` trap as with strings.',
        code: [
          'const items = ["a", "b", "c", "b"];',
          '',
          'console.log(items.indexOf("b"));',
          'console.log(items.lastIndexOf("b"));',
          'console.log(items.indexOf("z"));',
          'console.log(items.includes("b"));',
          'console.log(items.includes("z"));',
          '',
          '// indexOf uses strict equality, so objects compare by identity',
          'const target = { id: 1 };',
          'const list = [{ id: 1 }, target];',
          'console.log("by value   :", list.indexOf({ id: 1 }));',
          'console.log("by identity:", list.indexOf(target));',
          '',
          '// includes finds NaN; indexOf cannot',
          'console.log([NaN].includes(NaN), [NaN].indexOf(NaN));',
        ].join('\n'),
        output: [
          '1',
          '3',
          '-1',
          'true',
          'false',
          'by value   : -1',
          'by identity: 1',
          'true -1',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'Two traps in one place',
        body: [
          '**The `-1` trap.** `indexOf` returns `-1` when absent, which is truthy, while a match at index `0` is falsy. So `if (arr.indexOf(x))` is wrong in both directions. Use `includes` for a yes-or-no question, or compare `!== -1`.',
          '**Objects compare by identity.** `indexOf` uses strict equality, so searching for `{ id: 1 }` never matches a *different* object with the same contents. To find by contents you need `find` or `findIndex`, which Module 13 covers.',
        ],
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The last line is a genuine difference worth knowing: `includes` uses a comparison that treats `NaN` as equal to itself, so it can find `NaN` in an array. `indexOf` uses strict equality, and since `NaN !== NaN`, it never can.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The modern non-mutating alternatives',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'ES2023 added copying versions of the mutating methods.',
        code: [
          'const nums = [3, 1, 2];',
          '',
          'const sorted = nums.toSorted((a, b) => a - b);',
          'const reversed = nums.toReversed();',
          'const replaced = nums.with(0, 99);',
          '',
          'console.log("sorted  :", sorted);',
          'console.log("reversed:", reversed);',
          'console.log("replaced:", replaced);',
          'console.log("original:", nums);',
        ].join('\n'),
        output: [
          'sorted  : [1, 2, 3]',
          'reversed: [2, 1, 3]',
          'replaced: [99, 1, 2]',
          'original: [3, 1, 2]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'These solve a real annoyance: previously the only way to sort without mutating was `[...arr].sort(...)`, which reads as two operations. `toSorted` says exactly what it does. There is also `toSpliced`, the non-mutating counterpart of `splice`.',
          'They are recent, so `[...arr].sort()` remains common and entirely correct — and is what you should use if you must support older environments.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const a = [1, 2, 3];',
          'const b = a.slice(1);',
          'b.push(4);',
          '',
          'console.log(a.length, b.length, a.includes(4));',
        ].join('\n'),
        options: [
          '3 3 false',
          '3 4 false',
          '4 3 true',
          '3 3 true',
        ],
        correct: 0,
        explanation:
          '`slice(1)` returns a **new** array `[2, 3]` containing two elements, leaving `a` with its original three. Pushing `4` onto `b` makes it `[2, 3, 4]` — three elements — and does not touch `a`, because `b` is a genuinely separate array. So `a.length` is 3, `b.length` is 3, and `a` does not contain `4`. The two lengths coinciding is a coincidence of the numbers, not a sign the arrays are linked.',
      },
    ],
    exercises: [
      {
        id: 'ex-m12-03-a',
        title: 'Predict the slice result',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.EASY,
        xp: 10,
        topicIds: ['arrays'],
        instructions: 'What does this print?',
        code: [
          'const a = ["a", "b", "c", "d"];',
          'console.log(a.slice(1, 3), a.length);',
        ].join('\n'),
        options: [
          '["b", "c"] 4',
          '["b", "c", "d"] 4',
          '["b", "c"] 2',
          '["a", "b", "c"] 4',
        ],
        correct: 0,
        hints: [
          '`slice` excludes the end index.',
          'Does `slice` modify the original?',
        ],
        solution: '["b", "c"] 4',
        solutionExplanation:
          '`slice(1, 3)` takes elements from index 1 up to **but not including** index 3, so it returns `["b", "c"]`. Because `slice` returns a new array and never mutates, the original still has all four elements. A helpful check: `end - start` gives the result length, here `3 - 1 = 2`.',
      },
      {
        id: 'ex-m12-03-b',
        title: 'Paginate an array',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['arrays'],
        instructions:
          'Write `page(items, pageNumber, pageSize)` returning the items for that page, where `pageNumber` starts at 1. Return an empty array for a page beyond the end. The input must not be modified.',
        starterCode: [
          'function page(items, pageNumber, pageSize) {',
          '  // Work out the start index, then slice.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'returns the first page', body: 'expect(page([1, 2, 3, 4, 5], 1, 2)).toEqual([1, 2]);' },
          { name: 'returns the second page', body: 'expect(page([1, 2, 3, 4, 5], 2, 2)).toEqual([3, 4]);' },
          { name: 'returns a partial last page', body: 'expect(page([1, 2, 3, 4, 5], 3, 2)).toEqual([5]);' },
          { name: 'returns empty beyond the end', body: 'expect(page([1, 2, 3], 5, 2)).toEqual([]);' },
          { name: 'handles a page size larger than the array', body: 'expect(page([1, 2], 1, 10)).toEqual([1, 2]);' },
          { name: 'does not modify the input', body: 'const src = [1, 2, 3]; page(src, 1, 2); expect(src).toEqual([1, 2, 3]);' },
          { name: 'handles an empty array', body: 'expect(page([], 1, 5)).toEqual([]);', hidden: true },
        ],
        hints: [
          'Page 1 starts at index 0, page 2 at index `pageSize`.',
          'The start index is `(pageNumber - 1) * pageSize`.',
          '`slice` clamps automatically, so a start past the end gives an empty array.',
        ],
        solution: [
          'function page(items, pageNumber, pageSize) {',
          '  const start = (pageNumber - 1) * pageSize;',
          '  return items.slice(start, start + pageSize);',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The `- 1` converts a one-based page number into a zero-based index, which is the only piece of arithmetic here. `slice` handles every edge case for free: a start past the end returns an empty array, and an end past the length simply stops at the last element, which is why the partial-page and oversized-page tests pass without extra code. Because `slice` never mutates, the input is safe.',
      },
      {
        id: 'ex-m12-03-c',
        title: 'Fix the search check',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['arrays'],
        instructions:
          'This function should report whether the array contains the value. It gets both the found-at-index-0 case and the not-found case wrong. Fix it.',
        starterCode: [
          'function hasValue(items, value) {',
          '  if (items.indexOf(value)) {',
          '    return true;',
          '  }',
          '  return false;',
          '}',
        ].join('\n'),
        tests: [
          { name: 'finds a middle element', body: 'expect(hasValue(["a", "b"], "b")).toBe(true);' },
          { name: 'finds the first element', body: 'expect(hasValue(["a", "b"], "a")).toBe(true);' },
          { name: 'reports an absent value as false', body: 'expect(hasValue(["a", "b"], "z")).toBe(false);' },
          { name: 'handles an empty array', body: 'expect(hasValue([], "a")).toBe(false);' },
          { name: 'uses strict equality', body: 'expect(hasValue([1, 2], "1")).toBe(false);' },
          { name: 'finds NaN', body: 'expect(hasValue([NaN], NaN)).toBe(true);', hidden: true },
        ],
        hints: [
          '`indexOf` returns `0` for a first-element match, which is falsy.',
          'It returns `-1` when absent, which is truthy.',
          '`includes` answers this question directly and also finds `NaN`.',
        ],
        solution: [
          'function hasValue(items, value) {',
          '  return items.includes(value);',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`includes` returns a boolean, so there is no numeric result to misinterpret. The original was wrong in both directions: a match at index `0` is falsy and reported `false`, while an absent value gave `-1` which is truthy and reported `true`. Writing `return items.indexOf(value) !== -1;` would fix those two cases but still fail the hidden `NaN` test — `includes` uses a comparison that treats `NaN` as equal to itself, whereas `indexOf` uses strict equality and `NaN !== NaN`.',
      },
      {
        id: 'ex-m12-03-d',
        title: 'Merge without mutating',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['arrays'],
        instructions:
          'Write `mergeUnique(a, b)` returning a new array containing every element of `a` followed by only those elements of `b` that are not already present. Neither input may be modified.',
        starterCode: [
          'function mergeUnique(a, b) {',
          '  // Combine, then skip duplicates.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'merges with no overlap', body: 'expect(mergeUnique([1, 2], [3, 4])).toEqual([1, 2, 3, 4]);' },
          { name: 'skips duplicates from b', body: 'expect(mergeUnique([1, 2], [2, 3])).toEqual([1, 2, 3]);' },
          { name: 'handles complete overlap', body: 'expect(mergeUnique([1, 2], [1, 2])).toEqual([1, 2]);' },
          { name: 'handles empty inputs', body: 'expect(mergeUnique([], [1])).toEqual([1]); expect(mergeUnique([1], [])).toEqual([1]);' },
          { name: 'does not modify the inputs', body: 'const x = [1]; const y = [2]; mergeUnique(x, y); expect(x).toEqual([1]); expect(y).toEqual([2]);' },
          { name: 'keeps duplicates already within a', body: 'expect(mergeUnique([1, 1], [1])).toEqual([1, 1]);' },
          { name: 'skips duplicates within b too', body: 'expect(mergeUnique([1], [2, 2])).toEqual([1, 2]);', hidden: true },
        ],
        hints: [
          'Start from a copy of `a` using spread.',
          'Loop over `b` and push only when the result does not already include the value.',
          'Check against the growing result, not against `a`, so duplicates within `b` are also skipped.',
        ],
        solution: [
          'function mergeUnique(a, b) {',
          '  const result = [...a];',
          '',
          '  for (const item of b) {',
          '    if (!result.includes(item)) {',
          '      result.push(item);',
          '    }',
          '  }',
          '',
          '  return result;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Starting from `[...a]` copies the first array so neither input is touched, and pushing into that copy is safe. Checking `result.includes(item)` rather than `a.includes(item)` is what makes the hidden test pass — as `result` grows, a repeated value within `b` is already present and gets skipped. Note duplicates *already inside* `a` are preserved, since they are copied wholesale, which the sixth test pins down. For large arrays this is O(n × m) because `includes` scans each time; a `Set` would make it O(n + m), which Module 34 covers.',
      },
    ],
    quiz: {
      id: 'qz-m12-03',
      questions: [
        {
          id: 'q-m12-03-1',
          kind: QUIZ_KIND.MULTIPLE,
          topicIds: ['arrays'],
          prompt: 'Which of these leave the original array unchanged? (Select all that apply.)',
          options: ['`slice`', '`concat`', '`splice`', '`join`'],
          correct: [0, 1, 3],
          explanation:
            '`slice` returns a new portion, `concat` returns a new combined array, and `join` returns a string — none touch the original. `splice` is the mutating one, despite its similar name to `slice`. The similarity of those two names is exactly why the distinction is worth memorising.',
        },
        {
          id: 'q-m12-03-2',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['arrays'],
          prompt: 'Why does this find nothing?',
          code: [
            'const list = [{ id: 1 }];',
            'console.log(list.indexOf({ id: 1 }));',
          ].join('\n'),
          options: ['0', '-1', '1', 'undefined'],
          correct: 1,
          optionExplanations: [
            'That would require the same object identity.',
            'Correct — `indexOf` compares by identity, not contents.',
            'Indexes start at 0 and no match was found.',
            '`indexOf` always returns a number.',
          ],
          explanation:
            '`indexOf` uses strict equality, and two separately-created objects are never `===` even with identical contents. To search by contents you need `findIndex` with a predicate, which Module 13 covers.',
        },
        {
          id: 'q-m12-03-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['arrays'],
          prompt: 'What is the difference between `sort` and `toSorted`?',
          options: [
            '`toSorted` is faster',
            '`sort` mutates the array and returns it; `toSorted` returns a new sorted array and leaves the original alone',
            '`toSorted` only works with numbers',
            'They are identical',
          ],
          correct: 1,
          optionExplanations: [
            'Performance is not the distinction.',
            'Correct — `toSorted` is the non-mutating counterpart.',
            'Both accept any comparator.',
            'The mutation behaviour genuinely differs.',
          ],
          explanation:
            '`sort` reorders in place and returns the same array, so assigning the result does not protect the original. `toSorted`, added in ES2023, returns a new array. Before it existed the idiom was `[...arr].sort(...)`, which remains correct and is what you need for older environments.',
        },
        {
          id: 'q-m12-03-4',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['arrays', 'copying'],
          prompt: '`arr.slice()` produces a deep copy of an array of objects.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Only the array itself is new.',
            'Correct — it is shallow, so the objects are shared.',
          ],
          explanation:
            '`slice()` and `[...arr]` both create a new array holding the **same** object references. Adding or removing elements affects only the copy, but mutating an object inside it is visible through both. `structuredClone` is the built-in deep copy.',
        },
      ],
    },
    summary:
      'The non-mutating methods return a new array or value and leave the original untouched. `slice(start, end)` copies a portion, excluding `end` and accepting negative indexes; called with no arguments it is a shallow copy, as is `[...arr]`. `concat` and spread combine arrays, with spread preferred because it can place elements anywhere. `join` produces a string, turning `null` and `undefined` into empty strings. `indexOf`, `lastIndexOf` and `includes` search without modifying — but `indexOf` carries the `-1` trap in both directions and compares objects by identity, while `includes` returns a boolean and can find `NaN`. ES2023 added `toSorted`, `toReversed`, `with` and `toSpliced` as copying counterparts to the mutating methods, replacing the older `[...arr].sort()` idiom.',
    keyTakeaways: [
      '`slice` copies; `splice` mutates — the names are similar and the behaviour is opposite',
      '`slice()` and `[...arr]` are shallow copies — nested objects stay shared',
      'Spread is preferred over `concat` because it can insert anywhere',
      '`includes` is safer than `indexOf` and can find `NaN`',
      '`indexOf` compares objects by identity, never by contents',
      '`toSorted`, `toReversed`, `with` and `toSpliced` are the non-mutating versions',
    ],
    relatedLessons: ['l-m12-02', 'l-m12-04'],
    interviewConnections: [
      'What is the difference between slice and splice?',
      'Is arr.slice() a deep copy?',
      'Why can indexOf not find NaN?',
      'How do you sort an array without mutating it?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m12-04',
    slug: 'references-copying-destructuring',
    moduleId: M,
    order: 4,
    title: 'References, Copying and Destructuring',
    description: 'Why const arrays can change, what a copy really copies, and unpacking values by position.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 17,
    xp: 40,
    topicIds: ['arrays', 'copying'],
    prerequisites: ['l-m12-03'],
    learningObjectives: [
      'Explain why a `const` array can be modified',
      'Copy arrays shallowly and explain the limits',
      'Deep copy nested arrays correctly',
      'Destructure arrays, including defaults, skipping and rest',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: '`const` arrays can change',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'You met this in Module 01. It is worth restating with arrays specifically, because it is where it confuses people most.',
          '`const` freezes the **binding** — the connection between the name and the value. It says nothing about the array\'s contents.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Mutation is allowed; reassignment is not.',
        code: [
          'const items = ["a"];',
          '',
          'items.push("b");',
          'items[0] = "changed";',
          'items.length = 1;',
          'console.log("after mutation:", items);',
          '',
          'try {',
          '  items = ["new"];',
          '} catch (error) {',
          '  console.log(error.name + ":", error.message);',
          '}',
        ].join('\n'),
        output: [
          'after mutation: ["changed"]',
          'TypeError: Assignment to constant variable.',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'To make the contents unchangeable you need `Object.freeze(items)`, which prevents adding, removing and changing elements. Even that is shallow — objects inside the frozen array can still be mutated.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: '`Object.freeze` stops array mutation, but only one level deep.',
        code: [
          'const frozen = Object.freeze([1, 2, { n: 3 }]);',
          '',
          'try {',
          '  frozen.push(4);',
          '} catch (error) {',
          '  console.log("push:", error.name);',
          '}',
          '',
          '// The nested object is not frozen',
          'frozen[2].n = 99;',
          'console.log("nested changed:", frozen[2].n);',
        ].join('\n'),
        output: ['push: TypeError', 'nested changed: 99'].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'Copying arrays',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Four ways to copy — all shallow.',
        code: [
          'const source = [1, 2, 3];',
          '',
          'const bySpread = [...source];',
          'const bySlice = source.slice();',
          'const byConcat = [].concat(source);',
          'const byFrom = Array.from(source);',
          '',
          'console.log(bySpread, bySlice, byConcat, byFrom);',
          'console.log("all different objects:",',
          '  bySpread !== source && bySlice !== source && byFrom !== source);',
          '',
          '// Assignment is NOT a copy',
          'const alias = source;',
          'alias.push(4);',
          'console.log("after alias push:", source);',
        ].join('\n'),
        output: [
          '[1, 2, 3] [1, 2, 3] [1, 2, 3] [1, 2, 3]',
          'all different objects: true',
          'after alias push: [1, 2, 3, 4]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'Assignment shares; it does not copy',
        body: [
          '`const b = a` gives you a second name for the same array. Every mutation through either name is visible through both, and `a === b` is `true`.',
          'This is the single most common array bug: taking a "copy" to experiment with safely, and discovering the original changed too.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Shallow versus deep',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A shallow copy shares nested structures.',
        code: [
          'const original = [[1, 2], [3, 4]];',
          'const shallow = [...original];',
          '',
          '// Top level is independent',
          'shallow.push([5, 6]);',
          'console.log("lengths:", original.length, shallow.length);',
          '',
          '// Nested arrays are shared',
          'shallow[0].push(99);',
          'console.log("original[0]:", original[0]);',
          '',
          '// structuredClone copies every level',
          'const deep = structuredClone(original);',
          'deep[0].push(100);',
          'console.log("after deep push, original[0]:", original[0]);',
        ].join('\n'),
        output: [
          'lengths: 2 3',
          'original[0]: [1, 2, 99]',
          'after deep push, original[0]: [1, 2, 99]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The nested array was shared by the shallow copy, so pushing `99` was visible through `original`. After `structuredClone`, pushing `100` affected only the deep copy — `original[0]` still shows the earlier `99` but not the `100`.',
          '`structuredClone` handles nested arrays, objects, Dates, Maps and Sets, and copes with circular references. It cannot clone functions. The old `JSON.parse(JSON.stringify(x))` trick works for plain data but silently corrupts Dates and drops `undefined`, as Module 02 covered.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Array destructuring',
      },
      {
        kind: SECTION.PROSE,
        body: [
          '**Destructuring** unpacks values from an array into separate variables, matched by **position**.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Every form of array destructuring.',
        code: [
          'const colours = ["red", "green", "blue"];',
          '',
          '// Basic',
          'const [first, second] = colours;',
          'console.log(first, second);',
          '',
          '// Skipping with a hole',
          'const [, , third] = colours;',
          'console.log("third:", third);',
          '',
          '// Rest collects the remainder',
          'const [head, ...tail] = colours;',
          'console.log("head:", head, "tail:", tail);',
          '',
          '// Defaults apply when the value is undefined',
          'const [a = "x", b = "y", c = "z", d = "fallback"] = ["1", "2"];',
          'console.log(a, b, c, d);',
          '',
          '// Nested',
          'const [[x, y], [z]] = [[1, 2], [3]];',
          'console.log(x, y, z);',
        ].join('\n'),
        output: [
          'red green',
          'third: blue',
          'head: red tail: ["green", "blue"]',
          '1 2 z fallback',
          '1 2 3',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Defaults follow the same rule as parameters',
        body: [
          'A destructuring default applies only when the value is `undefined` — including when the index does not exist. It does **not** apply for `null`, `0`, `""` or `false`.',
          'In the example above, `c` and `d` both used their defaults because indexes 2 and 3 do not exist in a two-element array.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Two practical uses of destructuring.',
        code: [
          '// Swapping without a temporary variable',
          'let p = 1;',
          'let q = 2;',
          '[p, q] = [q, p];',
          'console.log("swapped:", p, q);',
          '',
          '// Unpacking in a loop header',
          'const pairs = [["a", 1], ["b", 2]];',
          'for (const [key, value] of pairs) {',
          '  console.log(key, value);',
          '}',
          '',
          '// Returning several values from a function',
          'function minMax(numbers) {',
          '  return [Math.min(...numbers), Math.max(...numbers)];',
          '}',
          '',
          'const [low, high] = minMax([5, 1, 9]);',
          'console.log("range:", low, high);',
        ].join('\n'),
        output: [
          'swapped: 2 1',
          'a 1',
          'b 2',
          'range: 1 9',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The swap works because the right-hand side `[q, p]` is fully evaluated into a new array before any assignment happens — the same "right side first" rule from Module 01.',
          'Returning an array and destructuring it is how a function hands back several values. When the values have distinct meanings rather than an order, returning an object is usually clearer, since destructuring by name does not depend on position.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Destructuring `null` or `undefined` throws',
        body: [
          '`const [a] = null;` throws a TypeError, because destructuring needs something iterable. Guard with a default on the whole value: `const [a] = maybeArray ?? [];`.',
          'The same applies to a function parameter: `function f([a] = []) { }` protects against being called with no argument.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const a = [[1], [2]];',
          'const b = [...a];',
          '',
          'b.push([3]);',
          'b[0].push(99);',
          '',
          'console.log(a.length, a[0]);',
        ].join('\n'),
        options: [
          '2 [1, 99]',
          '3 [1, 99]',
          '2 [1]',
          '3 [1]',
        ],
        correct: 0,
        explanation:
          'Spread creates a new top-level array, so pushing `[3]` onto `b` does not change `a` — its length stays 2. But the copy is **shallow**: `b[0]` and `a[0]` are the *same* nested array, so pushing `99` through `b[0]` is visible as `a[0]` becoming `[1, 99]`. This mixed behaviour — top level independent, nested shared — is exactly what makes shallow-copy bugs so confusing.',
      },
    ],
    exercises: [
      {
        id: 'ex-m12-04-a',
        title: 'Predict the shared reference',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.EASY,
        xp: 10,
        topicIds: ['arrays', 'copying'],
        instructions: 'What does this print?',
        code: [
          'const a = [1, 2];',
          'const b = a;',
          'b.push(3);',
          'console.log(a.length);',
        ].join('\n'),
        options: ['2', '3', '0', 'A TypeError'],
        correct: 1,
        hints: [
          'Did `const b = a` create a new array?',
        ],
        solution: '3',
        solutionExplanation:
          'Assignment copies the **reference**, not the array, so `a` and `b` are two names for one array — `a === b` is `true`. Pushing through either is visible through both. There is no TypeError because `const` forbids reassigning the binding, not mutating the array. To get an independent array you need `[...a]` or `a.slice()`.',
      },
      {
        id: 'ex-m12-04-b',
        title: 'Copy without sharing',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['arrays', 'copying'],
        instructions:
          'Write `duplicateGrid(grid)` returning a deep copy of a two-dimensional array of numbers. Modifying any cell of the copy must not affect the original.',
        starterCode: [
          'function duplicateGrid(grid) {',
          '  // A shallow copy would share the row arrays.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'copies the contents', body: 'expect(duplicateGrid([[1, 2], [3, 4]])).toEqual([[1, 2], [3, 4]]);' },
          { name: 'returns a different outer array', body: 'const g = [[1]]; expect(duplicateGrid(g)).not.toBe(g);' },
          { name: 'returns different row arrays', body: 'const g = [[1]]; expect(duplicateGrid(g)[0]).not.toBe(g[0]);' },
          { name: 'modifying a cell does not affect the original', body: 'const g = [[1, 2]]; const c = duplicateGrid(g); c[0][0] = 99; expect(g[0][0]).toBe(1);' },
          { name: 'pushing to a row does not affect the original', body: 'const g = [[1]]; const c = duplicateGrid(g); c[0].push(2); expect(g[0].length).toBe(1);' },
          { name: 'handles an empty grid', body: 'expect(duplicateGrid([])).toEqual([]);' },
          { name: 'handles rows of differing length', body: 'expect(duplicateGrid([[1], [2, 3]])).toEqual([[1], [2, 3]]);', hidden: true },
        ],
        hints: [
          '`[...grid]` copies the outer array but shares the rows.',
          'Each row needs copying too.',
          '`grid.map((row) => [...row])` copies both levels.',
        ],
        solution: [
          'function duplicateGrid(grid) {',
          '  return grid.map((row) => [...row]);',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`map` builds a new outer array, and spreading each row inside the callback builds a new inner array for every row — so both levels are independent, which the third and fifth tests check from different angles. A plain `[...grid]` would pass the first two tests and fail the rest, because the rows would still be shared. `structuredClone(grid)` is an equally correct answer and generalises to deeper nesting; the `map` version is explicit about the two levels and works in older environments.',
      },
      {
        id: 'ex-m12-04-c',
        title: 'Destructure a coordinate',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['arrays', 'destructuring'],
        instructions:
          'Write `describePoint(point)` taking a `[x, y]` array and returning a string like `"(3, 4)"`. Use destructuring. A missing coordinate defaults to `0`, and a missing or null array is treated as `[0, 0]`.',
        starterCode: [
          'function describePoint(point) {',
          '  // Destructure with defaults, and guard against a missing array.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'formats a full point', body: 'expect(describePoint([3, 4])).toBe("(3, 4)");' },
          { name: 'defaults a missing y', body: 'expect(describePoint([3])).toBe("(3, 0)");' },
          { name: 'defaults an empty array', body: 'expect(describePoint([])).toBe("(0, 0)");' },
          { name: 'handles a missing argument', body: 'expect(describePoint()).toBe("(0, 0)");' },
          { name: 'handles null', body: 'expect(describePoint(null)).toBe("(0, 0)");' },
          { name: 'preserves a legitimate zero', body: 'expect(describePoint([0, 5])).toBe("(0, 5)");' },
          { name: 'ignores extra elements', body: 'expect(describePoint([1, 2, 3])).toBe("(1, 2)");', hidden: true },
        ],
        hints: [
          'Destructuring `null` throws, so supply a fallback with `??` first.',
          '`const [x = 0, y = 0] = point ?? [];` handles both cases.',
          'Extra elements are simply ignored by destructuring.',
        ],
        solution: [
          'function describePoint(point) {',
          '  const [x = 0, y = 0] = point ?? [];',
          '  return `(${x}, ${y})`;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The `?? []` guard is essential: destructuring `null` or `undefined` throws a TypeError because neither is iterable, so the fourth and fifth tests would fail without it. The per-element defaults handle a short array, since a missing index yields `undefined` which is exactly what triggers a default. The sixth test confirms a supplied `0` survives — defaults fire only on `undefined`, never on other falsy values. Extra elements are ignored automatically, since destructuring only takes the positions you name.',
      },
      {
        id: 'ex-m12-04-d',
        title: 'Return several values',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['arrays', 'destructuring'],
        instructions:
          'Write `splitAt(items, index)` returning a two-element array `[before, after]`, where `before` holds the elements up to `index` and `after` holds the rest. Neither part may share structure with the input in a way that lets a push affect it.',
        starterCode: [
          'function splitAt(items, index) {',
          '  // slice twice — it never mutates.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'splits in the middle', body: 'expect(splitAt([1, 2, 3, 4], 2)).toEqual([[1, 2], [3, 4]]);' },
          { name: 'splits at zero', body: 'expect(splitAt([1, 2], 0)).toEqual([[], [1, 2]]);' },
          { name: 'splits at the end', body: 'expect(splitAt([1, 2], 2)).toEqual([[1, 2], []]);' },
          { name: 'handles an index past the end', body: 'expect(splitAt([1], 5)).toEqual([[1], []]);' },
          { name: 'handles an empty array', body: 'expect(splitAt([], 1)).toEqual([[], []]);' },
          { name: 'does not modify the input', body: 'const src = [1, 2, 3]; splitAt(src, 1); expect(src).toEqual([1, 2, 3]);' },
          { name: 'the parts are independent of the source', body: 'const src = [1, 2]; const [b] = splitAt(src, 1); b.push(9); expect(src.length).toBe(2);', hidden: true },
        ],
        hints: [
          '`slice(0, index)` gives the first part.',
          '`slice(index)` gives the rest.',
          'Return both inside an array so the caller can destructure.',
        ],
        solution: [
          'function splitAt(items, index) {',
          '  return [items.slice(0, index), items.slice(index)];',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`slice` never mutates and always returns a new array, so both parts are independent of the source — which the last two tests verify. It also clamps out-of-range indexes automatically: an index past the end makes the second slice empty, and an index of 0 makes the first one empty, so no edge-case handling is needed. Returning an array lets the caller write `const [before, after] = splitAt(...)`, which is the standard shape for a function producing two positional results.',
      },
    ],
    quiz: {
      id: 'qz-m12-04',
      questions: [
        {
          id: 'q-m12-04-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['arrays', 'variables'],
          prompt: 'Why can you push to an array declared with `const`?',
          options: [
            'Because arrays are exempt from `const`',
            'Because `const` freezes the binding between name and value, not the array’s contents',
            'Because `push` creates a new array',
            'Because `const` only applies to primitives',
          ],
          correct: 1,
          optionExplanations: [
            'There is no exemption; the rule simply targets the binding.',
            'Correct — mutation is allowed, reassignment is not.',
            '`push` mutates in place and returns a length.',
            '`const` applies to every type, always in the same way.',
          ],
          explanation:
            '`const` guarantees the name will always refer to the same array. Adding, removing or changing elements does not move the binding, so it is permitted. `Object.freeze` is what prevents content changes — and it is shallow.',
        },
        {
          id: 'q-m12-04-2',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['arrays', 'copying'],
          prompt: 'What are the two lengths?',
          code: [
            'const a = [[1]];',
            'const b = [...a];',
            'b[0].push(2);',
            'console.log(a[0].length, b.length);',
          ].join('\n'),
          options: ['1 1', '2 1', '1 2', '2 2'],
          correct: 1,
          optionExplanations: [
            'The nested array is shared, so it did grow.',
            'Correct — nested array shared, outer array independent.',
            '`b` gained no new top-level elements.',
            '`b` still has one element.',
          ],
          explanation:
            'Spread copies the outer array but stores the same nested array reference, so pushing through `b[0]` also grows `a[0]` to length 2. `b` itself still has one element, since nothing was pushed onto `b` directly. This is the shallow-copy trap.',
        },
        {
          id: 'q-m12-04-3',
          kind: QUIZ_KIND.OUTPUT,
          topicIds: ['arrays', 'destructuring'],
          prompt: 'What does this destructuring produce?',
          code: [
            'const [a = 1, b = 2] = [null, undefined];',
            'console.log(a, b);',
          ].join('\n'),
          options: ['1 2', 'null 2', 'null undefined', '1 undefined'],
          correct: 1,
          optionExplanations: [
            '`null` is a supplied value and does not trigger a default.',
            'Correct — only `undefined` triggers a default.',
            '`b` receives `undefined`, so its default applies.',
            '`a` keeps the supplied `null`.',
          ],
          explanation:
            'Destructuring defaults follow the same rule as parameter defaults: they apply only when the value is `undefined`. `null` counts as deliberately supplied, so `a` stays `null`, while `b` receives `undefined` and takes its default of 2.',
        },
        {
          id: 'q-m12-04-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['arrays', 'destructuring'],
          prompt: 'Why does `const [x] = null;` throw?',
          options: [
            'Because `null` has no length',
            'Because destructuring requires an iterable, and `null` is not one',
            'Because `x` was not initialised',
            'Because `const` cannot be destructured',
          ],
          correct: 1,
          optionExplanations: [
            'Length is not what destructuring uses.',
            'Correct — array destructuring iterates the value.',
            'The failure happens before any binding occurs.',
            '`const` destructuring is entirely normal.',
          ],
          explanation:
            'Array destructuring works by iterating the value, and `null` and `undefined` are not iterable, so it throws a TypeError. Guard with `const [x] = value ?? [];`, or give a parameter a default of `[]`.',
        },
      ],
    },
    summary:
      '`const` on an array freezes the binding, not the contents — pushing and index assignment are allowed while reassignment throws; `Object.freeze` prevents content changes but only one level deep. Assignment shares a reference rather than copying, which is the most common array bug. `[...arr]`, `arr.slice()`, `[].concat(arr)` and `Array.from(arr)` all produce genuine but **shallow** copies: the top level is independent while nested arrays and objects remain shared. `structuredClone` copies every level. Array destructuring unpacks by **position** and supports holes for skipping, a rest element for the remainder, defaults that fire only on `undefined`, and nesting — but destructuring `null` or `undefined` throws, so guard with `?? []`.',
    keyTakeaways: [
      '`const` prevents reassignment, not mutation',
      'Assignment shares a reference; only spread, `slice`, `concat` or `Array.from` copy',
      'All those copies are shallow — nested structures stay shared',
      '`structuredClone` copies every level',
      'Destructuring matches by position; defaults fire only on `undefined`',
      'Destructuring `null` throws — guard with `?? []`',
    ],
    relatedLessons: ['l-m12-03', 'l-m02-06'],
    interviewConnections: [
      'Why can you modify a const array?',
      'What is the difference between a shallow and a deep copy?',
      'How do you swap two variables without a temporary?',
      'What happens if you destructure null?',
    ],
  },
];
