import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm33';

export default [
  /* ================================================================== */
  {
    id: 'l-m33-01',
    slug: 'execution-contexts-and-the-call-stack',
    moduleId: M,
    order: 1,
    title: 'Execution Contexts and the Call Stack',
    description: 'What the engine tracks when a function runs, and why the stack explains errors you have already seen.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 18,
    xp: 45,
    topicIds: ['execution-context'],
    prerequisites: ['l-m32-04'],
    learningObjectives: [
      'Describe what an execution context holds',
      'Trace the call stack through nested calls',
      'Connect lexical environments to scope and closures',
      'Explain stack overflow and stack traces',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'What happens when a function is called',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Calling a function is not just "jump to that code". The engine creates an **execution context** — the bookkeeping for that particular invocation — and pushes it onto the **call stack**.',
          'An execution context holds three things worth knowing: a **lexical environment** (the variables declared in this call, plus a link to the enclosing environment), the value of **`this`**, and where to resume when the call returns.',
          'Two of those you already understand. The lexical environment is what Module 10 called scope and what Module 32 called the thing a closure retains. `this` is Module 29. This lesson is mostly about connecting them.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Tracing the stack as it grows and unwinds.',
        code: [
          '"use strict";',
          '',
          'const trace = [];',
          'let depth = 0;',
          '',
          'function enter(name) { trace.push(`${"  ".repeat(depth++)}-> ${name}`); }',
          'function leave(name) { trace.push(`${"  ".repeat(--depth)}<- ${name}`); }',
          '',
          'function inner() {',
          '  enter("inner");',
          '  leave("inner");',
          '}',
          '',
          'function middle() {',
          '  enter("middle");',
          '  inner();',
          '  leave("middle");',
          '}',
          '',
          'function outer() {',
          '  enter("outer");',
          '  middle();',
          '  leave("outer");',
          '}',
          '',
          'outer();',
          '',
          'trace.forEach((line) => console.log(line));',
          'console.log("depth at end:", depth);',
        ].join('\n'),
        output: [
          '-> outer',
          '  -> middle',
          '    -> inner',
          '    <- inner',
          '  <- middle',
          '<- outer',
          'depth at end: 0',
        ].join('\n'),
      },
      {
        kind: SECTION.CODE,
        language: 'text',
        caption: 'The stack at its deepest point.',
        code: [
          '        +-----------+',
          '        |  inner    |   <- currently running',
          '        +-----------+',
          '        |  middle   |   waiting for inner to return',
          '        +-----------+',
          '        |  outer    |   waiting for middle',
          '        +-----------+',
          '        |  global   |   waiting for outer',
          '        +-----------+',
          '',
          '  Last in, first out. Only the top frame runs.',
          '  A frame is removed when its call returns.',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'A model, not the machine',
        body: [
          'This is the **language-level** model the specification describes and that every tool — debuggers, stack traces, profilers — presents. It is what you reason with, and what interviews are asking about.',
          'Real engines optimise heavily: inlining calls, keeping values in registers, and eliminating frames entirely. So "the call stack" is an accurate mental model of *behaviour*, not a claim about machine memory layout.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Only the top frame runs',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'This single fact explains blocking.',
        code: [
          '"use strict";',
          '',
          'const events = [];',
          '',
          'function slow() {',
          '  // A genuinely synchronous loop — nothing else can run meanwhile',
          '  let total = 0;',
          '  for (let i = 0; i < 200000; i++) total += i;',
          '  events.push("slow finished");',
          '  return total;',
          '}',
          '',
          'setTimeout(() => events.push("timer"), 0);',
          '',
          'events.push("before");',
          'slow();',
          'events.push("after");',
          '',
          '// The timer has NOT run, even though its delay was 0',
          'console.log("synchronously:", events);',
          '',
          'setTimeout(() => console.log("eventually  :", events), 5);',
        ].join('\n'),
        output: [
          'synchronously: ["before", "slow finished", "after"]',
          'eventually  : ["before", "slow finished", "after", "timer"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'This is why a long synchronous task freezes a page',
        body: [
          'A timer callback cannot run while `slow()` is on the stack, because only the top frame runs and nothing removes a frame but returning. The same applies to click handlers, rendering, and everything else the browser wants to do.',
          'So "JavaScript is single-threaded" means precisely this: **one call stack**. It does not mean nothing else exists — the host provides timers, network and rendering — it means your code never runs in two places at once, which is also why you never need locks around ordinary variables.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: '"JavaScript is asynchronous" is not accurate',
        body: [
          'JavaScript **execution** is synchronous: statements run one after another on a single stack, to completion.',
          'What is asynchronous is the **host environment** — the browser or Node — which performs work outside your stack (timers, network, file I/O) and **schedules callbacks** to be run later, on that same single stack, once it is empty.',
          'The distinction matters because it predicts behaviour: `await` does not run anything in parallel, and a `Promise` does not make code faster. Lesson 2 covers the scheduling rules.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Stack overflow and stack traces',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The stack has a finite depth.',
        code: [
          '"use strict";',
          '',
          'let reached = 0;',
          '',
          'function recurse() {',
          '  reached += 1;',
          '  recurse();          // never returns, so no frame is ever removed',
          '}',
          '',
          'try {',
          '  recurse();',
          '} catch (error) {',
          '  console.log("error   :", error.name);',
          '  console.log("is Error:", error instanceof RangeError);',
          '  console.log("reached deep recursion:", reached > 1000);',
          '}',
          '',
          '// A base case lets frames unwind, so any depth within the limit is fine',
          'function countdown(n) {',
          '  if (n === 0) return "done";',
          '  return countdown(n - 1);',
          '}',
          '',
          'console.log("bounded :", countdown(1000));',
        ].join('\n'),
        output: [
          'error   : RangeError',
          'is Error: true',
          'reached deep recursion: true',
          'bounded : done',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'The maximum depth is not a specified number',
        body: [
          'It depends on the engine, the platform, and how much each frame holds — a function with many local variables uses more per frame. Never write code that relies on a particular depth being safe.',
          '`RangeError: Maximum call stack size exceeded` almost always means **runaway recursion**, not "my data was too deep". Look for a missing base case first.',
          'Note JavaScript engines generally do **not** implement tail-call elimination despite it being specified, so a tail-recursive function still consumes a frame per call. For deep recursion, use a loop or an explicit stack — Module 38 covers this.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A stack trace is a snapshot of the stack at throw time.',
        code: [
          '"use strict";',
          '',
          'function level3() { throw new Error("something failed"); }',
          'function level2() { level3(); }',
          'function level1() { level2(); }',
          '',
          'try {',
          '  level1();',
          '} catch (error) {',
          '  const frames = error.stack',
          '    .split("\\n")',
          '    .map((line) => line.trim())',
          '    .filter((line) => line.startsWith("at "))',
          '    .map((line) => line.split(" ")[1]);',
          '',
          '  // The innermost call is listed FIRST',
          '  console.log("top three:", frames.slice(0, 3));',
          '}',
        ].join('\n'),
        output: [
          'top three: ["level3", "level2", "level1"]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'That ordering is worth internalising: the **first** line is where the error was thrown, and each line below is the caller of the one above. Reading a trace top-down walks you back towards the origin of the request.',
          'This is exactly the stack diagram from earlier, captured at the moment of the throw — which is why Module 22 insisted on preserving the original error rather than rethrowing a new one, since a new `Error` captures a *different* stack.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Environments, revisited',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Scope is the environment chain; the stack is separate.',
        code: [
          '"use strict";',
          '',
          'const scopeChain = [];',
          '',
          'function outerScope() {',
          '  const outerVar = "outer";',
          '',
          '  function innerScope() {',
          '    const innerVar = "inner";',
          '    // Reads from its own environment, then the enclosing one',
          '    scopeChain.push(innerVar, outerVar);',
          '  }',
          '',
          '  return innerScope;',
          '}',
          '',
          '// The returned function is called from the GLOBAL context...',
          'const fn = outerScope();',
          'fn();',
          '',
          '// ...yet it still reads outerVar. The stack said nothing about that.',
          'console.log("read:", scopeChain);',
        ].join('\n'),
        output: [
          'read: ["inner", "outer"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The stack and the scope chain are different things',
        body: [
          'The **call stack** records who called whom — it is about **time**, and it changes constantly. The **scope chain** records what a function can see — it is about **source structure**, and it is fixed when the function is created.',
          'When `fn()` ran, the stack was `global -> innerScope`, with `outerScope` long gone. Yet `outerVar` was still readable, because `innerScope`\'s environment links to the environment `outerScope` created — that link is the closure from Module 32.',
          'Confusing the two produces the belief that a function can see its **caller\'s** variables. It cannot. Only `this` is decided by the call; variables are decided by where the function was written.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '"use strict";',
          '',
          'function a() { return b(); }',
          'function b() { return c(); }',
          'function c() { return "done"; }',
          '',
          '// At the moment c() is executing, what is on the stack?',
        ].join('\n'),
        options: [
          'global, a, b, c — with c on top',
          'Only c',
          'c, b, a — with a on top',
          'global and c only',
        ],
        correct: 0,
        explanation:
          'Each call pushes a frame and none has returned yet: `a` called `b` before returning, and `b` called `c` before returning. So all four contexts are live, with the **global** context at the bottom and `c` on top as the only one currently executing. When `c` returns `"done"`, its frame is removed and `b` resumes at the point it left off — the "where to resume" part of an execution context. A stack trace thrown from `c` would list them in exactly the reverse order of the stack: `c`, then `b`, then `a`.',
      },
    ],
    exercises: [
      {
        id: 'ex-m33-01-a',
        title: 'What is in an execution context?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['execution-context'],
        instructions:
          'What does an execution context track for a function call?',
        options: [
          'Only the function\'s arguments',
          'A lexical environment for this call, the value of `this`, and where to resume when it returns',
          'The function\'s source code',
          'The call stack itself',
        ],
        correct: 1,
        hints: [
          'Two of the three are things you already learned in earlier modules.',
        ],
        solution: 'A lexical environment for this call, the value of `this`, and where to resume when it returns',
        solutionExplanation:
          'The lexical environment holds this call\'s variables plus a link to the enclosing environment — the same thing Module 10 called scope and Module 32 called what a closure retains. `this` is bound per call from the call site, as Module 29 established. The resume point is what lets the caller continue after the call returns. Arguments live inside the environment, and the source code is not per-call at all.',
      },
      {
        id: 'ex-m33-01-b',
        title: 'Trace the stack',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['execution-context'],
        instructions:
          'Write `traceCalls()` returning an array of `"enter:name"` / `"exit:name"` strings in the order they occur, for a fixed chain `a` calls `b` calls `c`.',
        starterCode: [
          'function traceCalls() {',
          '  const log = [];',
          '',
          '  // Define a, b, c so that a() calls b() calls c(),',
          '  // each pushing enter/exit around its inner call.',
          '',
          '  return log;',
          '}',
        ].join('\n'),
        tests: [
          { name: 'records six events', body: 'expect(traceCalls().length).toBe(6);' },
          { name: 'enters outermost first', body: 'expect(traceCalls()[0]).toBe("enter:a");' },
          { name: 'exits outermost last', body: 'expect(traceCalls()[5]).toBe("exit:a");' },
          { name: 'is correctly nested', body: 'expect(traceCalls()).toEqual(["enter:a", "enter:b", "enter:c", "exit:c", "exit:b", "exit:a"]);' },
          { name: 'innermost enters and exits consecutively', body: 'const t = traceCalls(); expect([t[2], t[3]]).toEqual(["enter:c", "exit:c"]);' },
          { name: 'is repeatable', body: 'expect(traceCalls()).toEqual(traceCalls());', hidden: true },
        ],
        hints: [
          'Push `enter:x` at the start of each function and `exit:x` at the end.',
          'Call the next function between those two pushes.',
          'Define the functions inside `traceCalls` so they share the log.',
        ],
        solution: [
          'function traceCalls() {',
          '  const log = [];',
          '',
          '  function c() {',
          '    log.push("enter:c");',
          '    log.push("exit:c");',
          '  }',
          '',
          '  function b() {',
          '    log.push("enter:b");',
          '    c();',
          '    log.push("exit:b");',
          '  }',
          '',
          '  function a() {',
          '    log.push("enter:a");',
          '    b();',
          '    log.push("exit:a");',
          '  }',
          '',
          '  a();',
          '  return log;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The output is the shape of the stack over time: frames are pushed in call order and removed in **reverse** order, so the entries nest perfectly and the outermost function is the first to enter and the last to exit. Defining the three functions inside `traceCalls` lets them close over one `log` — a closure, doing exactly what Module 32 described. The hidden test passes because a fresh `log` is created on each call, so no state carries over.',
      },
      {
        id: 'ex-m33-01-c',
        title: 'Diagnose a stack overflow',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['execution-context'],
        instructions:
          'Code throws `RangeError: Maximum call stack size exceeded`. What is the most likely cause?',
        options: [
          'The data is too large for memory',
          'Recursion without a reachable base case, so no frame is ever removed',
          'Too many variables',
          'An infinite for loop',
        ],
        correct: 1,
        hints: [
          'What removes a frame from the stack?',
        ],
        solution: 'Recursion without a reachable base case, so no frame is ever removed',
        solutionExplanation:
          'A frame is removed only when its call **returns**, so recursion that never reaches a base case pushes frames indefinitely until the limit is hit. An infinite `for` loop is a different failure — it freezes the page without growing the stack, because no calls are being made. Note the maximum depth is engine- and platform-specific and depends on frame size, so never rely on a particular depth being safe; and JavaScript engines generally do not eliminate tail calls, so tail recursion still consumes a frame.',
      },
      {
        id: 'ex-m33-01-d',
        title: 'Stack or scope chain?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.HARD,
        xp: 25,
        topicIds: ['execution-context', 'scope'],
        instructions:
          'A function declared at the top level is called from deep inside another function. Which variables can it read?',
        options: [
          'The caller\'s local variables, because the caller is below it on the stack',
          'Only those in scope where it was written — the stack does not affect variable access',
          'Both its own and the caller\'s',
          'Only global variables',
        ],
        correct: 1,
        hints: [
          'Is variable access decided by time or by source structure?',
        ],
        solution: 'Only those in scope where it was written — the stack does not affect variable access',
        solutionExplanation:
          'The **call stack** records who called whom, which is about time; the **scope chain** records what a function can see, which is fixed by where the function was written. A function can never read its caller\'s locals, however deep the stack. The reverse case proves the same point from the other side: a closure returned from a finished function still reads that function\'s variables even though its frame is long gone. Only `this` is decided by the call.',
      },
    ],
    quiz: {
      id: 'qz-m33-01',
      questions: [
        {
          id: 'q-m33-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['execution-context'],
          prompt: 'How many frames can execute at once?',
          options: ['As many as are on the stack', 'One — the top frame', 'One per function', 'Unlimited'],
          correct: 1,
          optionExplanations: [
            'The rest are waiting.',
            'Correct — which is why long tasks block.',
            'A function can appear in many frames.',
            'Only the top one runs.',
          ],
          explanation:
            'Only the top frame executes; every frame below is waiting for the one above to return. That single fact is why a long synchronous task blocks timers, clicks and rendering.',
        },
        {
          id: 'q-m33-01-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['execution-context'],
          prompt: 'Is it accurate to say "JavaScript is asynchronous"?',
          options: [
            'Yes',
            'No — execution is synchronous on one stack; the host provides asynchronous work and schedules callbacks onto that stack',
            'Yes, since ES6',
            'Only in Node',
          ],
          correct: 1,
          optionExplanations: [
            'Statements run to completion in order.',
            'Correct — the asynchrony belongs to the host.',
            'Promises did not change execution.',
            'Both hosts work this way.',
          ],
          explanation:
            'Your code runs synchronously on a single stack. Timers, network and I/O are performed by the host, which schedules callbacks to run later on that same stack — which is why `await` does not run anything in parallel.',
        },
        {
          id: 'q-m33-01-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['execution-context'],
          prompt: 'In a stack trace, which frame is listed first?',
          options: [
            'The outermost caller',
            'The innermost frame — where the error was thrown',
            'The global context',
            'The order is unspecified',
          ],
          correct: 1,
          optionExplanations: [
            'That is listed last.',
            'Correct — read downward towards the origin.',
            'It appears at the bottom.',
            'Innermost first is consistent.',
          ],
          explanation:
            'The throw site is first, and each line below is the caller of the one above — the stack captured at the moment of the throw, which is why creating a new Error when rethrowing loses the original trace.',
        },
        {
          id: 'q-m33-01-4',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['execution-context', 'scope'],
          prompt: 'A function can read variables from whatever called it.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'The stack does not grant variable access.',
            'Correct — only lexical scope does.',
          ],
          explanation:
            'Variable access follows the scope chain, fixed where the function was written. The stack records call order only. Only `this` is decided by the call site.',
        },
      ],
    },
    summary:
      'Calling a function creates an **execution context** — a **lexical environment** for that call (its variables plus a link to the enclosing environment), the value of **`this`**, and where to resume — and pushes it onto the **call stack**. Frames are pushed in call order and removed in reverse, and **only the top frame executes**; everything below waits. That single fact explains blocking: a timer, a click handler, or a repaint cannot run while a long synchronous function is on the stack, which is what "single-threaded" actually means — **one call stack**, not "nothing else exists". So **"JavaScript is asynchronous" is inaccurate**: execution is synchronous, and the **host** performs asynchronous work and schedules callbacks onto that same stack. Depth is finite, and `RangeError: Maximum call stack size exceeded` almost always means **runaway recursion**, since only returning removes a frame; the limit is engine- and platform-specific, and engines generally do not eliminate tail calls. A **stack trace** is the stack captured at the throw, listing the **innermost frame first**. Finally, the **call stack and the scope chain are different**: the stack is about time and changes constantly, the scope chain is about source structure and is fixed at creation — which is why a function can never read its caller\'s variables, and why a closure still reads variables from a frame that is long gone. This is a **model** of behaviour, not a claim about machine memory.',
    keyTakeaways: [
      'An execution context holds a lexical environment, this, and a resume point',
      'Only the top stack frame runs — this is exactly why long tasks block',
      'Execution is synchronous; the host supplies asynchrony and schedules callbacks',
      'Stack overflow means runaway recursion; the depth limit is not specified',
      'A stack trace lists the innermost frame first',
      'The stack is about time; the scope chain is about source structure',
    ],
    relatedLessons: ['l-m33-02', 'l-m32-01'],
    interviewConnections: [
      'What is an execution context?',
      'What happens on the call stack when a function is called?',
      'Why does a long synchronous task freeze the page?',
      'Can a function access its caller\'s variables?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m33-02',
    slug: 'tasks-and-microtasks',
    moduleId: M,
    order: 2,
    title: 'Tasks and Microtasks',
    description: 'The two queues, the checkpoint that drains one of them, and why promises always beat timers.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 19,
    xp: 50,
    topicIds: ['event-loop'],
    prerequisites: ['l-m33-01'],
    learningObjectives: [
      'Distinguish the task queue from the microtask queue',
      'Describe the microtask checkpoint',
      'Predict ordering for mixed synchronous, promise and timer code',
      'Explain how a microtask loop can starve rendering',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'The event loop, stated carefully',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: '"The event loop executes callbacks" is a poor description',
        body: [
          'The event loop does not run your code — the **call stack** does. The loop **coordinates**: when the stack is empty, it decides what becomes eligible to run next, according to the host\'s rules.',
          'A more useful phrasing: the event loop repeatedly takes the next eligible **task**, lets it run to completion on the stack, then performs a **microtask checkpoint**, and only then considers rendering and the next task.',
          'Note the event loop is defined by the **host** — the HTML specification for browsers, libuv for Node — not by the JavaScript language. That is why Node has extra phases browsers do not.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'text',
        caption: 'One turn of the loop.',
        code: [
          '   +-------------------------------------------+',
          '   |  1. Take ONE task from the task queue     |',
          '   |     and run it to completion on the stack |',
          '   +-------------------------------------------+',
          '                      |',
          '                      v',
          '   +-------------------------------------------+',
          '   |  2. Microtask checkpoint:                 |',
          '   |     drain the microtask queue COMPLETELY, |',
          '   |     including microtasks added while      |',
          '   |     draining                              |',
          '   +-------------------------------------------+',
          '                      |',
          '                      v',
          '   +-------------------------------------------+',
          '   |  3. Possibly render                       |',
          '   +-------------------------------------------+',
          '                      |',
          '                      +---> back to 1',
        ].join('\n'),
      },
      {
        kind: SECTION.TABLE,
        headers: ['', 'Task (macrotask)', 'Microtask'],
        rows: [
          ['Sources', '`setTimeout`, `setInterval`, I/O, events', '`Promise` reactions, `queueMicrotask`, `MutationObserver`'],
          ['How many run per turn', '**One**', '**All of them**, until the queue is empty'],
          ['Newly added ones', 'Wait for a later turn', '**Run in the same checkpoint**'],
          ['Can starve rendering', 'No — one per turn', '**Yes** — an endless chain never yields'],
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The ordering that follows',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The canonical example.',
        code: [
          '"use strict";',
          '',
          'const order = [];',
          '',
          'order.push("A");',
          '',
          'setTimeout(() => order.push("timer"), 0);',
          '',
          'Promise.resolve().then(() => order.push("promise"));',
          '',
          'order.push("B");',
          '',
          '// Everything synchronous has run; neither queue has been touched',
          'console.log("sync only:", [...order]);',
          '',
          'setTimeout(() => console.log("final    :", order), 5);',
        ].join('\n'),
        output: [
          'sync only: ["A", "B"]',
          'final    : ["A", "B", "promise", "timer"]',
        ].join('\n'),
      },
      {
        kind: SECTION.LIST,
        ordered: true,
        items: [
          '`"A"` runs — plain synchronous code on the stack.',
          '`setTimeout` **registers** a callback with the host and returns immediately. Nothing runs.',
          '`Promise.resolve().then(...)` queues a **microtask**. Nothing runs.',
          '`"B"` runs. The synchronous script is now finished and the stack empties.',
          '**Microtask checkpoint**: the queue is drained, so `"promise"` runs.',
          'A later turn takes the timer task, so `"timer"` runs.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Promises always beat timers — and here is the actual reason',
        body: [
          'It is not that promises are "faster" or higher priority in some vague sense. The **checkpoint drains microtasks before the loop considers the next task**, so any pending promise reaction runs before any timer, even a `setTimeout(..., 0)` registered earlier.',
          'This holds no matter how the code is arranged, which is what makes ordering questions predictable rather than a matter of luck.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Microtasks drain completely',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A microtask queued during the checkpoint runs in the same checkpoint.',
        code: [
          '"use strict";',
          '',
          'const order = [];',
          '',
          'setTimeout(() => order.push("T"), 0);',
          '',
          'Promise.resolve().then(() => {',
          '  order.push("P1");',
          '',
          '  // Queued DURING the checkpoint — it does not wait for a later turn',
          '  Promise.resolve().then(() => {',
          '    order.push("P2");',
          '',
          '    Promise.resolve().then(() => order.push("P3"));',
          '  });',
          '});',
          '',
          'setTimeout(() => console.log(order), 5);',
        ].join('\n'),
        output: [
          '["P1", "P2", "P3", "T"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Which is also how you starve the page',
        body: [
          'Because newly queued microtasks are drained in the **same** checkpoint, a microtask that always queues another one never lets the checkpoint end. The loop never reaches rendering or the next task, and the page freezes just as thoroughly as an infinite `for` loop — with no error and no stack overflow, since each microtask returns normally.',
          'A recursive **`setTimeout`** does not do this: each callback is a separate task, so the loop renders and handles input between them. That is the correct pattern for breaking up long work.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Splitting work across tasks so the loop can breathe.',
        code: [
          '"use strict";',
          '',
          'function processInChunks(items, chunkSize, onDone) {',
          '  const results = [];',
          '  let index = 0;',
          '',
          '  function step() {',
          '    const end = Math.min(index + chunkSize, items.length);',
          '',
          '    for (; index < end; index++) {',
          '      results.push(items[index] * 2);',
          '    }',
          '',
          '    if (index < items.length) {',
          '      // A NEW TASK — the loop can render and handle input first',
          '      setTimeout(step, 0);',
          '    } else {',
          '      onDone(results);',
          '    }',
          '  }',
          '',
          '  step();',
          '}',
          '',
          'const numbers = [1, 2, 3, 4, 5, 6, 7];',
          '',
          'processInChunks(numbers, 3, (results) => {',
          '  console.log("chunked result:", results);',
          '});',
          '',
          'console.log("not blocked   :", true);',
        ].join('\n'),
        output: [
          'not blocked   : true',
          'chunked result: [2, 4, 6, 8, 10, 12, 14]',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'queueMicrotask',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Queueing a microtask directly, without a promise.',
        code: [
          '"use strict";',
          '',
          'console.log("available:", typeof queueMicrotask);',
          '',
          'const order = [];',
          '',
          'setTimeout(() => order.push("task"), 0);',
          '',
          'queueMicrotask(() => order.push("micro-1"));',
          'Promise.resolve().then(() => order.push("promise"));',
          'queueMicrotask(() => order.push("micro-2"));',
          '',
          'order.push("sync");',
          '',
          'setTimeout(() => console.log(order), 5);',
        ].join('\n'),
        output: [
          'available: function',
          '["sync", "micro-1", "promise", "micro-2", "task"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'One queue, in registration order',
        body: [
          '`queueMicrotask` and promise reactions share the **same** microtask queue, so they interleave strictly in the order they were queued — `micro-1`, `promise`, `micro-2` above, not all the `queueMicrotask` ones first.',
          'Prefer `queueMicrotask(fn)` over `Promise.resolve().then(fn)` when you only want the scheduling: it says what it means, and it does not create a promise whose rejection you would need to handle. An error thrown inside it becomes an uncaught error rather than a silently rejected promise.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Timers are a minimum, not a promise',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Ordering between timers is by delay, then by registration.',
        code: [
          '"use strict";',
          '',
          'const order = [];',
          '',
          'setTimeout(() => order.push("second registered, 0ms"), 0);',
          'setTimeout(() => order.push("third registered, 0ms"), 0);',
          'setTimeout(() => order.push("first registered, 10ms"), 10);',
          '',
          'setTimeout(() => console.log(order), 30);',
        ].join('\n'),
        output: [
          '["second registered, 0ms", "third registered, 0ms", "first registered, 10ms"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'A delay means "not before", never "at"',
        body: [
          '`setTimeout(fn, 0)` means "queue this as a task as soon as possible", and it still waits for the stack to empty and for the microtask queue to drain. If a long synchronous function is running, the callback waits for it regardless of the delay.',
          'Browsers also **clamp** nested timers to a minimum (commonly 4ms after several levels of nesting) and throttle timers in background tabs heavily. Never build logic that depends on a timer firing at a precise moment.',
          'This is exactly why Module 25 forbade asserting on elapsed milliseconds and required asserting on **ordering** instead — as every example in this lesson does.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '"use strict";',
          '',
          'console.log("1");',
          '',
          'setTimeout(() => console.log("2"), 0);',
          '',
          'Promise.resolve()',
          '  .then(() => console.log("3"))',
          '  .then(() => console.log("4"));',
          '',
          'queueMicrotask(() => console.log("5"));',
          '',
          'console.log("6");',
        ].join('\n'),
        options: [
          '1 6 3 5 4 2',
          '1 6 3 4 5 2',
          '1 6 2 3 5 4',
          '1 3 5 6 4 2',
        ],
        correct: 0,
        explanation:
          'Synchronous first: `1`, then `6`. Now the checkpoint drains the microtask queue **in registration order** — and the key detail is that only the **first** `.then` was queued during the synchronous run; the second is queued only when the first *settles*. So the queue initially holds `[3, 5]`. Running `3` queues `4` at the **back**, behind `5`. The checkpoint continues draining: `5`, then `4`. Only when the queue is empty does the loop take the timer task, giving `2`. Hence **1 6 3 5 4 2** — chained `.then` steps do not run consecutively when other microtasks are already waiting.',
      },
    ],
    exercises: [
      {
        id: 'ex-m33-02-a',
        title: 'Why do promises beat timers?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['event-loop'],
        instructions:
          'A `setTimeout(..., 0)` is registered before a `Promise.resolve().then(...)`. Which callback runs first, and why?',
        options: [
          'The timer, because it was registered first',
          'The promise reaction — the microtask queue is drained completely before the loop takes the next task',
          'Whichever the engine chooses',
          'They run at the same time',
        ],
        correct: 1,
        hints: [
          'What happens between one task and the next?',
        ],
        solution: 'The promise reaction — the microtask queue is drained completely before the loop takes the next task',
        solutionExplanation:
          'Registration order between the two queues is irrelevant. After the current task finishes and the stack empties, the host performs a **microtask checkpoint** and drains that queue entirely; only then does the loop take another task. So any pending promise reaction runs before any timer, regardless of delay or registration order. This is a structural rule rather than a priority heuristic, which is what makes ordering questions answerable with certainty.',
      },
      {
        id: 'ex-m33-02-b',
        title: 'Predict the mixed ordering',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.HARD,
        xp: 30,
        topicIds: ['event-loop'],
        instructions:
          'What is the output order of: `log("A")`; `setTimeout(() => log("B"))`; `Promise.resolve().then(() => log("C"))`; `log("D")`?',
        options: ['A D C B', 'A B C D', 'A D B C', 'A C D B'],
        correct: 0,
        hints: [
          'Synchronous first, then the checkpoint, then a task.',
        ],
        solution: 'A D C B',
        solutionExplanation:
          '`A` and `D` are plain synchronous statements, so they run first in source order — the `setTimeout` and `.then` calls only **register** callbacks and return immediately. When the script finishes and the stack empties, the microtask checkpoint drains the queue, running `C`. Only after the queue is empty does the loop take a task from the task queue, running `B`. The general shape to remember: **all synchronous, then all microtasks, then one task**.',
      },
      {
        id: 'ex-m33-02-c',
        title: 'Chunk long work',
        kind: EXERCISE_KIND.ASYNC_TASK,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['event-loop'],
        instructions:
          'Write `processChunked(items, size)` returning a promise for the mapped array (each item doubled), processing `size` items per **task** so the loop can render between chunks.',
        starterCode: [
          'function processChunked(items, size) {',
          '  // Use setTimeout between chunks, not a microtask.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'processes every item', body: 'expect(await processChunked([1, 2, 3, 4, 5], 2)).toEqual([2, 4, 6, 8, 10]);' },
          { name: 'handles an exact multiple', body: 'expect(await processChunked([1, 2, 3, 4], 2)).toEqual([2, 4, 6, 8]);' },
          { name: 'handles a single chunk', body: 'expect(await processChunked([1, 2], 10)).toEqual([2, 4]);' },
          { name: 'handles an empty list', body: 'expect(await processChunked([], 3)).toEqual([]);' },
          { name: 'returns a promise', body: 'expect(typeof processChunked([1], 1).then).toBe("function");' },
          { name: 'does not resolve synchronously', body: 'let done = false; processChunked([1, 2, 3], 1).then(() => { done = true; }); expect(done).toBe(false);' },
          { name: 'preserves order across chunks', body: 'expect(await processChunked([5, 1, 4, 2], 2)).toEqual([10, 2, 8, 4]);', hidden: true },
        ],
        hints: [
          'Wrap the whole thing in `new Promise((resolve) => { ... })`.',
          'A `step` function processes one chunk, then schedules itself with `setTimeout` if more remain.',
          'Resolve when the index reaches the end.',
        ],
        solution: [
          'function processChunked(items, size) {',
          '  return new Promise((resolve) => {',
          '    const results = [];',
          '    let index = 0;',
          '',
          '    function step() {',
          '      const end = Math.min(index + size, items.length);',
          '',
          '      for (; index < end; index++) {',
          '        results.push(items[index] * 2);',
          '      }',
          '',
          '      if (index < items.length) {',
          '        setTimeout(step, 0);',
          '      } else {',
          '        resolve(results);',
          '      }',
          '    }',
          '',
          '    step();',
          '  });',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Scheduling the next chunk with `setTimeout` makes it a **separate task**, so the event loop can render and handle input between chunks — a recursive `queueMicrotask` would keep the checkpoint open and block the page exactly as an infinite loop does. The sixth test confirms the work is genuinely deferred rather than completed synchronously. Tracking a single `index` across chunks is what preserves order, which the hidden test checks with unsorted input. The empty case resolves on the first `step`, since `index` already equals `items.length`.',
      },
      {
        id: 'ex-m33-02-d',
        title: 'Why does a microtask loop freeze the page?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.HARD,
        xp: 25,
        topicIds: ['event-loop'],
        instructions:
          'A microtask that always queues another microtask freezes the page. A recursive `setTimeout` does not. Why?',
        options: [
          'setTimeout runs on another thread',
          'The checkpoint drains microtasks including newly added ones, so it never ends; each setTimeout callback is a separate task, letting the loop render in between',
          'Microtasks have higher priority',
          'setTimeout is slower',
        ],
        correct: 1,
        hints: [
          'What must happen before the loop can render?',
        ],
        solution: 'The checkpoint drains microtasks including newly added ones, so it never ends; each setTimeout callback is a separate task, letting the loop render in between',
        solutionExplanation:
          'The checkpoint continues until the microtask queue is **empty**, and a microtask queued during draining joins that same checkpoint — so an endlessly self-queueing microtask means the loop never reaches rendering or the next task. There is no error and no stack overflow, because each microtask returns normally, which makes it a genuinely nasty freeze to diagnose. A recursive `setTimeout` queues a **task**, and the loop takes only one per turn, rendering and handling input in between — which is why it is the correct way to break up long work.',
      },
    ],
    quiz: {
      id: 'qz-m33-02',
      questions: [
        {
          id: 'q-m33-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['event-loop'],
          prompt: 'How many microtasks run at a checkpoint?',
          options: [
            'One',
            'All of them, including any queued while draining',
            'One per promise',
            'As many as fit in 4ms',
          ],
          correct: 1,
          optionExplanations: [
            'That is the task rule.',
            'Correct — which is how a microtask loop starves rendering.',
            'The queue is shared.',
            'There is no time budget.',
          ],
          explanation:
            'The checkpoint drains the queue completely, and a microtask queued during draining joins the same checkpoint. That is why an endlessly self-queueing microtask freezes the page.',
        },
        {
          id: 'q-m33-02-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['event-loop'],
          prompt: 'How many tasks run per turn of the loop?',
          options: ['All queued tasks', 'One', 'One per source', 'Unlimited'],
          correct: 1,
          optionExplanations: [
            'Only one is taken.',
            'Correct — then a checkpoint, then possibly rendering.',
            'One overall.',
            'One per turn.',
          ],
          explanation:
            'The loop takes one task, runs it to completion, performs a microtask checkpoint and may render — then repeats. That is what lets recursive `setTimeout` yield to the browser.',
        },
        {
          id: 'q-m33-02-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['event-loop'],
          prompt: 'Do queueMicrotask callbacks and promise reactions share a queue?',
          options: [
            'No, promises have their own higher-priority queue',
            'Yes — one queue, drained in registration order',
            'No, queueMicrotask is a task',
            'Only in Node',
          ],
          correct: 1,
          optionExplanations: [
            'There is no separate promise queue.',
            'Correct — they interleave by registration order.',
            'It is a microtask.',
            'The rule is the same in browsers.',
          ],
          explanation:
            'They share the microtask queue and interleave strictly by when they were queued. Prefer `queueMicrotask` when you only want the scheduling — it creates no promise whose rejection you must handle.',
        },
        {
          id: 'q-m33-02-4',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['event-loop'],
          prompt: 'setTimeout(fn, 0) guarantees fn runs after approximately 0ms.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'The delay is a minimum only.',
            'Correct — it waits for the stack, the checkpoint, and clamping.',
          ],
          explanation:
            'A delay means "not before". The callback also waits for the stack to empty and the microtask queue to drain, and browsers clamp nested timers and throttle background tabs. Never assert on elapsed time.',
        },
      ],
    },
    summary:
      'The **event loop does not execute your code** — the call stack does. The loop **coordinates**: take one **task**, run it to completion, perform a **microtask checkpoint**, possibly render, repeat. It is defined by the **host** (the HTML specification, or libuv in Node), not by the language. The two queues differ in one decisive way: the loop takes **one task per turn**, but the checkpoint **drains microtasks completely — including any queued while draining**. That is the entire reason promise reactions always run before timers regardless of registration order, and it is a structural rule rather than a priority heuristic. It is also how you freeze a page: a microtask that always queues another never lets the checkpoint end, with no error and no stack overflow, while a recursive **`setTimeout`** queues a separate task each time and so lets the loop render and handle input — the correct way to break up long work. `queueMicrotask` shares the **same queue** as promise reactions and interleaves by registration order; prefer it when you only want the scheduling, since it creates no promise whose rejection you must handle. Finally, a timer delay is a **minimum, not an appointment**: the callback waits for the stack to empty and the checkpoint to drain, browsers clamp nested timers and throttle background tabs — which is exactly why every example here asserts on **ordering**, never elapsed time.',
    keyTakeaways: [
      'The loop coordinates; the call stack executes',
      'One task per turn, but microtasks drain completely at each checkpoint',
      'Newly queued microtasks join the same checkpoint — hence starvation',
      'Promises beat timers structurally, not by priority',
      'queueMicrotask shares the promise queue and runs in registration order',
      'A timer delay is a minimum; assert on ordering, never elapsed time',
    ],
    relatedLessons: ['l-m33-01', 'l-m33-03'],
    interviewConnections: [
      'What is the difference between the task and microtask queues?',
      'Why does a promise callback run before a setTimeout(0)?',
      'What is a microtask checkpoint?',
      'How can you break up long work without freezing the page?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m33-03',
    slug: 'promise-and-await-ordering',
    moduleId: M,
    order: 3,
    title: 'Promise and await Ordering',
    description: 'Executors run immediately, `await` schedules a continuation — and every ordering puzzle follows.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 19,
    xp: 50,
    topicIds: ['event-loop'],
    prerequisites: ['l-m33-02'],
    learningObjectives: [
      'Explain that a Promise executor runs synchronously',
      'Explain what await does to the rest of a function',
      'Predict output for mixed async/await, promise and timer code',
      'Reason about chained promises without memorising cases',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'The executor runs immediately',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The example that removes a very common misconception.',
        code: [
          '"use strict";',
          '',
          'const order = [];',
          '',
          'order.push(1);',
          '',
          'new Promise((resolve) => {',
          '  // This runs SYNCHRONOUSLY, right now — not later',
          '  order.push(2);',
          '  resolve();',
          '}).then(() => {',
          '  // Only the REACTION is deferred, as a microtask',
          '  order.push(4);',
          '});',
          '',
          'order.push(3);',
          '',
          'console.log("synchronous:", [...order]);',
          '',
          'queueMicrotask(() => console.log("after      :", order));',
        ].join('\n'),
        output: [
          'synchronous: [1, 2, 3]',
          'after      : [1, 2, 3, 4]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'A promise does not make code asynchronous',
        body: [
          'The executor — the function you pass to `new Promise` — runs **immediately and synchronously**, before `new Promise` even returns. Only the `.then` **reaction** is scheduled as a microtask.',
          'So wrapping a slow synchronous loop in `new Promise` does **not** stop it blocking. The loop still runs on the stack, right there, and the page still freezes. Promises describe *when a result becomes available*; they do not move work off the stack.',
          'To actually stop blocking you need something else: split the work across tasks (lesson 2), or move it to a Web Worker (Module 27).',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Proving it — wrapping does not defer the work.',
        code: [
          '"use strict";',
          '',
          'const events = [];',
          '',
          'new Promise((resolve) => {',
          '  let total = 0;',
          '  for (let i = 0; i < 100000; i++) total += i;',
          '',
          '  events.push("heavy work done");',
          '  resolve(total);',
          '});',
          '',
          'events.push("after the constructor");',
          '',
          '// The work finished BEFORE the next line ran',
          'console.log(events);',
        ].join('\n'),
        output: [
          '["heavy work done", "after the constructor"]',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'What `await` actually does',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'An `async` function runs **synchronously** until it hits its first `await`. At that point it **returns** to its caller, and everything after the `await` is scheduled as a **microtask** to resume when the awaited value settles.',
          'That is the whole rule. "Pauses the function" is a good intuition, but the precise version — *returns now, resumes as a microtask* — is what lets you predict ordering.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The canonical async ordering example.',
        code: [
          '"use strict";',
          '',
          'const order = [];',
          '',
          'async function run() {',
          '  order.push(2);            // synchronous — runs on the call',
          '  await Promise.resolve();',
          '  order.push(4);            // resumed later, as a microtask',
          '}',
          '',
          'order.push(1);',
          'run();',
          'order.push(3);              // runs because run() already returned',
          '',
          'console.log("synchronous:", [...order]);',
          '',
          'queueMicrotask(() => console.log("after      :", order));',
        ].join('\n'),
        output: [
          'synchronous: [1, 2, 3]',
          'after      : [1, 2, 3, 4]',
        ].join('\n'),
      },
      {
        kind: SECTION.CODE,
        language: 'text',
        caption: 'Where the function splits.',
        code: [
          '  async function run() {',
          '    order.push(2);           <-- runs synchronously,',
          '                                 on the call to run()',
          '    await Promise.resolve();',
          '  ---------------------------  the function RETURNS here',
          '    order.push(4);           <-- scheduled as a microtask',
          '  }',
          '',
          '  So run() behaves like:',
          '',
          '    order.push(2);',
          '    return Promise.resolve().then(() => { order.push(4); });',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Reading `await` as "the rest becomes a .then"',
        body: [
          'Rewriting an `async` function into explicit `.then` chains is the most reliable way to answer an ordering question. Everything before the first `await` is synchronous; each subsequent section is one microtask further along.',
          'It also explains why an `async` function **always returns a promise**, even one containing no `await`: the return value is wrapped.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Two async functions interleaving.',
        code: [
          '"use strict";',
          '',
          'const order = [];',
          '',
          'async function first() {',
          '  order.push("first: start");',
          '  await null;                       // await on a non-promise still defers',
          '  order.push("first: after await");',
          '}',
          '',
          'async function second() {',
          '  order.push("second: start");',
          '  await null;',
          '  order.push("second: after await");',
          '}',
          '',
          'first();',
          'second();',
          'order.push("sync end");',
          '',
          'queueMicrotask(() => queueMicrotask(() => console.log(order)));',
        ].join('\n'),
        output: [
          '["first: start", "second: start", "sync end", "first: after await", "second: after await"]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Both functions ran their synchronous prefix immediately, in call order, then both returned. The continuations were queued in the same order and ran during the checkpoint — so the two functions **interleave** rather than one completing before the other starts.',
          'Note `await null`: awaiting a non-promise still defers the continuation to a microtask. `await` always yields, even when there is nothing to wait for.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Awaiting a promise costs an extra tick',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A subtle but predictable difference.',
        code: [
          '"use strict";',
          '',
          'const order = [];',
          '',
          'async function withAwait() {',
          '  await Promise.resolve();',
          '  order.push("await: 1");',
          '  await Promise.resolve();',
          '  order.push("await: 2");',
          '}',
          '',
          'withAwait();',
          '',
          'Promise.resolve()',
          '  .then(() => order.push("then: 1"))',
          '  .then(() => order.push("then: 2"))',
          '  .then(() => order.push("then: 3"));',
          '',
          'setTimeout(() => console.log(order), 5);',
        ].join('\n'),
        output: [
          '["await: 1", "then: 1", "await: 2", "then: 2", "then: 3"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Do not memorise tick counts — reason about the queue',
        body: [
          'The interleaving above follows from one rule: each `await` and each `.then` resumes one microtask later, and the checkpoint drains **in registration order**. Counting exact ticks for adversarial cases is a trivia exercise, and modern engines have optimised away a historical extra tick for awaited native promises.',
          'What is genuinely worth knowing and stable: **independent chains interleave**, and their relative ordering is not something to rely on in application code. Module 24 made the same point. If two operations must happen in a definite order, chain them — do not depend on queue arithmetic.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Putting it together',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Everything in one example.',
        code: [
          '"use strict";',
          '',
          'const order = [];',
          '',
          'order.push("script start");',
          '',
          'setTimeout(() => order.push("timer"), 0);',
          '',
          'async function work() {',
          '  order.push("async start");',
          '  await Promise.resolve();',
          '  order.push("async end");',
          '}',
          '',
          'work();',
          '',
          'new Promise((resolve) => {',
          '  order.push("executor");',
          '  resolve();',
          '}).then(() => order.push("then"));',
          '',
          'order.push("script end");',
          '',
          'setTimeout(() => console.log(order), 5);',
        ].join('\n'),
        output: [
          '["script start", "async start", "executor", "script end", "async end", "then", "timer"]',
        ].join('\n'),
      },
      {
        kind: SECTION.LIST,
        ordered: true,
        items: [
          '`"script start"` — synchronous.',
          'The timer is **registered**; nothing runs.',
          '`work()` runs its prefix synchronously: `"async start"`. It hits `await`, returns, and queues its continuation.',
          'The **executor** runs synchronously: `"executor"`. Its `.then` reaction is queued behind the async continuation.',
          '`"script end"` — synchronous. The stack now empties.',
          '**Checkpoint**: the queue drains in registration order — `"async end"`, then `"then"`.',
          'A later turn takes the timer task: `"timer"`.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '"use strict";',
          '',
          'async function f() {',
          '  console.log("A");',
          '  await g();',
          '  console.log("B");',
          '}',
          '',
          'async function g() {',
          '  console.log("C");',
          '}',
          '',
          'console.log("D");',
          'f();',
          'console.log("E");',
        ].join('\n'),
        options: [
          'D A C E B',
          'D A C B E',
          'A C D E B',
          'D E A C B',
        ],
        correct: 0,
        explanation:
          '`"D"` is plain synchronous code. Calling `f()` runs its prefix immediately, giving `"A"`, and then evaluates `g()` — which is **also** a call, so `g`\'s body runs synchronously too, giving `"C"`. Only now does `f` reach the `await`, return to its caller, and queue its continuation; so `"E"` runs. The checkpoint then resumes `f`, printing `"B"`. The point worth carrying: `await g()` **calls** `g` synchronously and only then defers — the deferral happens at the `await`, not at the call.',
      },
    ],
    exercises: [
      {
        id: 'ex-m33-03-a',
        title: 'When does a Promise executor run?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['event-loop'],
        instructions:
          'When does the function passed to `new Promise(...)` execute?',
        options: [
          'As a microtask, after the current script',
          'Synchronously and immediately, before new Promise returns',
          'When .then is attached',
          'On the next task',
        ],
        correct: 1,
        hints: [
          'What prints first — a log inside the executor, or the line after it?',
        ],
        solution: 'Synchronously and immediately, before new Promise returns',
        solutionExplanation:
          'The executor runs right there on the stack; only the `.then` **reaction** is deferred to a microtask. The practical consequence is important: wrapping a slow synchronous loop in `new Promise` does **not** stop it blocking, because the loop still runs on the stack at that moment. Promises describe when a result becomes available — they do not move work off the stack. To stop blocking, split across tasks or use a Worker.',
      },
      {
        id: 'ex-m33-03-b',
        title: 'Predict the async ordering',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.HARD,
        xp: 30,
        topicIds: ['event-loop'],
        instructions:
          'For `log(1); run(); log(3);` where `run` is `async function run() { log(2); await null; log(4); }`, what is the order?',
        options: ['1 2 3 4', '1 2 4 3', '1 3 2 4', '2 1 3 4'],
        correct: 0,
        hints: [
          'How much of an async function runs before the first await?',
        ],
        solution: '1 2 3 4',
        solutionExplanation:
          'An `async` function runs **synchronously until its first `await`**, so calling `run()` immediately logs `2`. At the `await` the function **returns to its caller**, and everything after it is queued as a microtask — so `3` runs next as ordinary synchronous code. Once the stack empties, the checkpoint resumes the function and logs `4`. Note `await null` still defers even though there is nothing to wait for: `await` always yields.',
      },
      {
        id: 'ex-m33-03-c',
        title: 'Convert await to then',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['event-loop'],
        instructions:
          'Write `runSteps(log)` producing exactly the ordering an async function would: push `"a"` synchronously, then `"b"` one microtask later, then `"c"` one after that. Return a promise resolving when all three are pushed. Do not use `async`/`await`.',
        starterCode: [
          'function runSteps(log) {',
          '  // Everything before the first await is synchronous.',
          '  // Each subsequent section is one microtask further along.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'pushes the first entry synchronously', body: 'const log = []; runSteps(log); expect(log).toEqual(["a"]);' },
          { name: 'completes all three', body: 'const log = []; await runSteps(log); expect(log).toEqual(["a", "b", "c"]);' },
          { name: 'returns a promise', body: 'expect(typeof runSteps([]).then).toBe("function");' },
          { name: 'does not use timers', body: 'const log = []; const p = runSteps(log); await Promise.resolve().then(() => {}).then(() => {}).then(() => {}); expect(log).toEqual(["a", "b", "c"]);' },
          { name: 'b comes before c', body: 'const log = []; await runSteps(log); expect(log.indexOf("b")).toBeLessThan(log.indexOf("c"));' },
          { name: 'works with separate logs', body: 'const a = []; const b = []; await Promise.all([runSteps(a), runSteps(b)]); expect([a, b]).toEqual([["a", "b", "c"], ["a", "b", "c"]]);', hidden: true },
        ],
        hints: [
          'Push `"a"` before returning anything.',
          'Return `Promise.resolve().then(...).then(...)`.',
          'Each `.then` is one microtask further along.',
        ],
        solution: [
          'function runSteps(log) {',
          '  log.push("a");',
          '',
          '  return Promise.resolve()',
          '    .then(() => { log.push("b"); })',
          '    .then(() => { log.push("c"); });',
          '}',
        ].join('\n'),
        solutionExplanation:
          'This is the mechanical translation the lesson describes: everything before the first `await` becomes the synchronous prefix, and each section after an `await` becomes one `.then`. The first test proves `"a"` really is synchronous — the function has pushed it before returning. The fourth test confirms only microtasks are involved, since three microtask turns are enough to complete it; a `setTimeout`-based version would still be unfinished. Being able to perform this rewrite is the most reliable way to answer any ordering question.',
      },
      {
        id: 'ex-m33-03-d',
        title: 'Does a promise stop blocking?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.HARD,
        xp: 25,
        topicIds: ['event-loop'],
        instructions:
          'A slow synchronous loop is wrapped in `new Promise((resolve) => { ...loop...; resolve(); })`. Does the page still freeze?',
        options: [
          'No — the promise moves the work off the main thread',
          'Yes — the executor runs synchronously on the stack, so the loop blocks exactly as before',
          'No, if you add .then',
          'Only in older browsers',
        ],
        correct: 1,
        hints: [
          'Where does the executor run?',
        ],
        solution: 'Yes — the executor runs synchronously on the stack, so the loop blocks exactly as before',
        solutionExplanation:
          'The executor runs immediately on the call stack, so the loop occupies the only thread just as it did unwrapped — the page cannot render or handle input until it returns. Adding `.then` changes nothing, because only the reaction is deferred. This is the most consequential form of the misconception that promises make code asynchronous: they describe **when a result becomes available**, not **where the work runs**. The real fixes are splitting across tasks or moving the work to a Web Worker.',
      },
    ],
    quiz: {
      id: 'qz-m33-03',
      questions: [
        {
          id: 'q-m33-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['event-loop'],
          prompt: 'How much of an async function runs synchronously when called?',
          options: [
            'None of it',
            'Everything up to the first await',
            'All of it',
            'Only the return statement',
          ],
          correct: 1,
          optionExplanations: [
            'The prefix runs immediately.',
            'Correct — then it returns and queues the rest.',
            'The await defers the remainder.',
            'The prefix runs too.',
          ],
          explanation:
            'The body runs on the stack until the first `await`, at which point the function returns to its caller and schedules the remainder as a microtask.',
        },
        {
          id: 'q-m33-03-2',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['event-loop'],
          prompt: 'await on a non-promise value resumes synchronously.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It still defers to a microtask.',
            'Correct — await always yields.',
          ],
          explanation:
            '`await null` still returns to the caller and queues the continuation. `await` always yields, even when there is nothing to wait for.',
        },
        {
          id: 'q-m33-03-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['event-loop'],
          prompt: 'In `await g()`, when does g\'s body run?',
          options: [
            'After the current function suspends',
            'Immediately — it is an ordinary call; the deferral happens at the await',
            'On the next task',
            'Only if g is async',
          ],
          correct: 1,
          optionExplanations: [
            'The call happens first.',
            'Correct — call, then defer.',
            'No task is involved.',
            'Either way the call is immediate.',
          ],
          explanation:
            '`g()` is evaluated first, so its synchronous prefix runs right away. Only then does `await` defer the remainder of the awaiting function.',
        },
        {
          id: 'q-m33-03-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['event-loop'],
          prompt: 'What does an async function return?',
          options: [
            'Whatever the return statement gives',
            'Always a promise, wrapping the returned value',
            'undefined until it finishes',
            'A generator',
          ],
          correct: 1,
          optionExplanations: [
            'The value is wrapped.',
            'Correct — even with no await inside.',
            'The promise is returned immediately.',
            'Different mechanism.',
          ],
          explanation:
            'An `async` function always returns a promise, wrapping the returned value — which is why callers can `.then` or `await` it even when the body is entirely synchronous.',
        },
      ],
    },
    summary:
      'Two rules generate every ordering puzzle. First, the **`Promise` executor runs synchronously and immediately**, before `new Promise` returns — only the `.then` **reaction** is a microtask. The consequence matters: wrapping a slow loop in a promise does **not** stop it blocking, because the loop still runs on the stack. Promises describe **when a result becomes available**, not **where the work runs**; to stop blocking, split across tasks or use a Worker. Second, an **`async` function runs synchronously until its first `await`**, then **returns to its caller** and schedules the remainder as a **microtask**. So `await g()` calls `g` — running *its* synchronous prefix immediately — and only then defers; and `await null` still yields, because `await` always does. The most reliable technique is to rewrite an `async` function as explicit `.then` chains: the prefix is synchronous, and each section afterwards is one microtask further along. An `async` function **always returns a promise**, even with no `await` inside. Independent chains **interleave**, and the exact tick arithmetic is not worth memorising — engines have optimised parts of it, and Module 24\'s advice stands: if two operations must happen in a definite order, **chain them** rather than relying on queue arithmetic.',
    keyTakeaways: [
      'The Promise executor runs synchronously — wrapping does not stop blocking',
      'An async function runs synchronously up to its first await, then returns',
      'await always yields, even on a non-promise',
      'await g() calls g immediately; the deferral happens at the await',
      'An async function always returns a promise',
      'Independent chains interleave — chain deliberately instead of counting ticks',
    ],
    relatedLessons: ['l-m33-02', 'l-m33-01'],
    interviewConnections: [
      'When does a Promise executor run?',
      'What exactly does await do to the rest of the function?',
      'Predict the output of this mixed async/timer snippet.',
      'Does wrapping code in a promise stop it blocking the page?',
    ],
  },
];
