import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm38';

export default [
  /* ================================================================== */
  {
    id: 'l-m38-01',
    slug: 'base-cases-and-recursive-cases',
    moduleId: M,
    order: 1,
    title: 'Base Cases and Recursive Cases',
    description: 'The two halves every recursive function needs, and the three questions that tell you it terminates.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 18,
    xp: 45,
    topicIds: ['recursion'],
    prerequisites: ['l-m37-03'],
    learningObjectives: [
      'Write a recursive function with a correct base case',
      'Verify that each call makes progress toward the base case',
      'Diagnose infinite recursion from the three questions',
      'Trace both the descent and the unwind',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'A function that calls itself',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Recursion is a function solving a problem by calling **itself** on a smaller version of the same problem, until the problem becomes small enough to answer directly.',
          'Module 33 already established what happens mechanically: each call pushes an execution context onto the call stack, and a frame is removed only when its call **returns**. This module is about using that deliberately.',
          'Every recursive function has exactly two parts. The **base case** answers directly and stops. The **recursive case** breaks the problem down and calls again.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The smallest useful example.',
        code: [
          '"use strict";',
          '',
          'const output = [];',
          '',
          'function countdown(number) {',
          '  // BASE CASE — answer directly, do not recurse',
          '  if (number <= 0) {',
          '    output.push("liftoff");',
          '    return;',
          '  }',
          '',
          '  // RECURSIVE CASE — do a little work, then call with a SMALLER value',
          '  output.push(number);',
          '  countdown(number - 1);',
          '}',
          '',
          'countdown(4);',
          '',
          'console.log(output);',
        ].join('\n'),
        output: [
          '[4, 3, 2, 1, "liftoff"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'The three questions',
        body: [
          'Before running any recursive function, answer these. If you cannot, it is not finished.',
          '**1. What stops it?** There must be at least one input for which the function returns without calling itself. Here: `number <= 0`.',
          '**2. What changes on each call?** Something must be different, or the next call faces the identical problem. Here: `number - 1`.',
          '**3. Does that change reach the base case?** Decreasing by one from a positive integer reaches `0`. Decreasing by one from `2.5` also reaches `<= 0` — but decreasing from `-1` would already have stopped, and *increasing* never would.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        caption: 'Three broken versions — illustrative, and deliberately not runnable.',
        code: [
          '// 1. NO BASE CASE — nothing stops it',
          'function noBase(n) {',
          '  console.log(n);',
          '  return noBase(n - 1);      // runs until RangeError',
          '}',
          '',
          '// 2. BASE CASE NEVER REACHED — the value moves the wrong way',
          'function wrongDirection(n) {',
          '  if (n === 0) return "done";',
          '  return wrongDirection(n + 1);   // n grows away from 0',
          '}',
          '',
          '// 3. NO PROGRESS — the argument never changes',
          'function noProgress(n) {',
          '  if (n === 0) return "done";',
          '  return noProgress(n);      // identical problem, forever',
          '}',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Why those blocks are not runnable here',
        body: [
          'Each of them throws `RangeError: Maximum call stack size exceeded` after thousands of frames — Module 33 lesson 1 explains the mechanism. That is a real, recoverable error, and you can safely try these in a browser console.',
          'They are marked illustrative in this lesson because unbounded recursion is a poor thing to run inside a verification harness. The behaviour is exactly what Module 33 described: only returning removes a frame, so a function that never returns fills the stack.',
          'Note case 2 is the nastiest. `n === 0` is a perfectly good base case, and it is simply **unreachable** from a positive `n` moving upward. A base case that exists is not the same as a base case that is reached.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The same three faults, made safe with a depth guard.',
        code: [
          '"use strict";',
          '',
          '// A guard lets us OBSERVE the fault without filling the stack',
          'function guarded(n, depth = 0) {',
          '  if (depth > 5) return `gave up at depth ${depth}`;',
          '  if (n === 0) return "reached base case";',
          '',
          '  return guarded(n + 1, depth + 1);   // wrong direction',
          '}',
          '',
          'console.log("from 1 :", guarded(1));',
          'console.log("from 0 :", guarded(0));',
          '',
          '// Correct direction reaches the base case well within the guard',
          'function correct(n, depth = 0) {',
          '  if (depth > 5) return `gave up at depth ${depth}`;',
          '  if (n === 0) return "reached base case";',
          '',
          '  return correct(n - 1, depth + 1);',
          '}',
          '',
          'console.log("fixed  :", correct(3));',
          'console.log("too far:", correct(50));',
        ].join('\n'),
        output: [
          'from 1 : gave up at depth 6',
          'from 0 : reached base case',
          'fixed  : reached base case',
          'too far: gave up at depth 6',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'Down, then back up',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Recursion that produces a value has two phases.',
        code: [
          '"use strict";',
          '',
          'const trace = [];',
          '',
          'function sumTo(n) {',
          '  trace.push(`enter sumTo(${n})`);',
          '',
          '  if (n === 1) {',
          '    trace.push("base case returns 1");',
          '    return 1;',
          '  }',
          '',
          '  const rest = sumTo(n - 1);          // descend first',
          '  const total = n + rest;             // then combine on the way back',
          '',
          '  trace.push(`sumTo(${n}) returns ${n} + ${rest} = ${total}`);',
          '  return total;',
          '}',
          '',
          'console.log("result:", sumTo(4));',
          'trace.forEach((line) => console.log(line));',
        ].join('\n'),
        output: [
          'result: 10',
          'enter sumTo(4)',
          'enter sumTo(3)',
          'enter sumTo(2)',
          'enter sumTo(1)',
          'base case returns 1',
          'sumTo(2) returns 2 + 1 = 3',
          'sumTo(3) returns 3 + 3 = 6',
          'sumTo(4) returns 4 + 6 = 10',
        ].join('\n'),
      },
      {
        kind: SECTION.CODE,
        language: 'text',
        caption: 'The two phases, drawn.',
        code: [
          '  DESCENT — each call defers, waiting for the one below',
          '',
          '    sumTo(4)  =  4 + sumTo(3)',
          '                     |',
          '    sumTo(3)  =      3 + sumTo(2)',
          '                         |',
          '    sumTo(2)  =          2 + sumTo(1)',
          '                             |',
          '    sumTo(1)  =              1        <- base case, no further call',
          '',
          '  UNWIND — values return upward and combine',
          '',
          '    sumTo(1) -> 1',
          '    sumTo(2) -> 2 + 1  = 3',
          '    sumTo(3) -> 3 + 3  = 6',
          '    sumTo(4) -> 4 + 6  = 10',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Nothing is computed until the base case is reached',
        body: [
          'Notice all four `enter` lines print **before** any result. Each frame stops at `n + sumTo(n - 1)` and waits — it cannot add anything until the inner call returns.',
          'That is why the stack grows to the full depth before shrinking, and why deep recursion costs memory: every deferred `n` is held in a frame.',
          'It is also the key to reading recursive code. Do **not** try to trace every call mentally. Instead, trust that the recursive call returns the right answer for a smaller input, and check only that you combine it correctly. That leap is the whole skill.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Trusting the recursion',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Writing a recursive function without tracing it.',
        code: [
          '"use strict";',
          '',
          '// Question: reverse a string.',
          '// 1. Base case: a string of 0 or 1 characters is already reversed.',
          '// 2. Smaller problem: the string without its first character.',
          '// 3. Combine: reversed-rest, then the first character on the end.',
          '',
          'function reverse(text) {',
          '  if (text.length <= 1) return text;',
          '',
          '  return reverse(text.slice(1)) + text[0];',
          '}',
          '',
          'console.log("reverse :", reverse("recursion"));',
          'console.log("empty   :", JSON.stringify(reverse("")));',
          'console.log("single  :", reverse("a"));',
          '',
          '// Same three steps for a different problem: is it a palindrome?',
          'function isPalindrome(text) {',
          '  if (text.length <= 1) return true;',
          '  if (text[0] !== text[text.length - 1]) return false;',
          '',
          '  return isPalindrome(text.slice(1, -1));',
          '}',
          '',
          'console.log("level   :", isPalindrome("level"));',
          'console.log("hello   :", isPalindrome("hello"));',
        ].join('\n'),
        output: [
          'reverse : noisrucer',
          'empty   : ""',
          'single  : a',
          'level   : true',
          'hello   : false',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The method, stated once',
        body: [
          '**1.** What input is small enough to answer immediately? That is the base case — and it is usually the *empty* or *single* case, not a large one.',
          '**2.** How do I make the problem smaller in a way that reaches that case?',
          '**3.** Given the answer to the smaller problem, how do I build the answer to this one?',
          'Answer those three and the function writes itself. `isPalindrome` needed one extra check before recursing, which is common — a recursive case may reject early as well as defer.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '"use strict";',
          '',
          'function mystery(n) {',
          '  if (n <= 0) return "";',
          '',
          '  return mystery(n - 1) + n;',
          '}',
          '',
          'console.log(mystery(4));',
        ].join('\n'),
        options: [
          '"1234"',
          '"4321"',
          '"10"',
          '""',
        ],
        correct: 0,
        explanation:
          'The recursive call comes **before** the concatenation, so nothing is appended until the descent reaches the base case and the unwind begins. `mystery(1)` returns `"" + 1` = `"1"`, then `mystery(2)` returns `"1" + 2` = `"12"`, and so on up to `"1234"` — the digits appear in **ascending** order even though the function counted down. Writing `return n + mystery(n - 1)` instead would give `"4321"`. Note the result is a **string**, because the base case returns `""` and `"" + 1` concatenates rather than adds — which is why `mystery(4)` is `"1234"` and not the number `10`.',
      },
    ],
    exercises: [
      {
        id: 'ex-m38-01-a',
        title: 'What makes recursion terminate?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.EASY,
        xp: 20,
        topicIds: ['recursion'],
        instructions:
          'A recursive function has a base case `if (n === 0) return 0;` and recurses with `f(n + 1)`. Starting from `n = 3`, what happens?',
        options: [
          'It returns 0 correctly',
          'It recurses until the stack overflows — the base case exists but is never reached',
          'It throws a SyntaxError',
          'It returns 3',
        ],
        correct: 1,
        hints: [
          'Does `n` move toward 0 or away from it?',
        ],
        solution: 'It recurses until the stack overflows — the base case exists but is never reached',
        solutionExplanation:
          'Having a base case is not enough; the recursive case must make **progress toward** it. Here `n` increases, so from `3` it goes to `4`, `5`, and onward — `n === 0` is a perfectly valid condition that is simply unreachable. Frames accumulate until `RangeError: Maximum call stack size exceeded`, since Module 33 established that only returning removes a frame. This is the subtlest of the three faults: the code *looks* correct because a base case is visibly present.',
      },
      {
        id: 'ex-m38-01-b',
        title: 'Write a recursive sum',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['recursion'],
        instructions:
          'Write `sumArray(numbers)` returning the total of an array, using recursion rather than a loop or `reduce`.',
        starterCode: [
          'function sumArray(numbers) {',
          '  // Base case: what array is trivially summed?',
          '  // Smaller problem: the array without its first element.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'sums several numbers', body: 'expect(sumArray([1, 2, 3, 4])).toBe(10);' },
          { name: 'handles a single element', body: 'expect(sumArray([5])).toBe(5);' },
          { name: 'returns 0 for an empty array', body: 'expect(sumArray([])).toBe(0);' },
          { name: 'handles negatives', body: 'expect(sumArray([5, -3, 2])).toBe(4);' },
          { name: 'does not mutate the input', body: 'const input = [1, 2, 3]; sumArray(input); expect(input).toEqual([1, 2, 3]);' },
          { name: 'handles zeros', body: 'expect(sumArray([0, 0, 0])).toBe(0);' },
          { name: 'works for a longer array', body: 'expect(sumArray([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])).toBe(10);', hidden: true },
        ],
        hints: [
          'An empty array sums to `0` — that is your base case.',
          '`numbers[0]` is the first element; `numbers.slice(1)` is the rest.',
          'Combine: first element plus the sum of the rest.',
        ],
        solution: [
          'function sumArray(numbers) {',
          '  if (numbers.length === 0) return 0;',
          '',
          '  return numbers[0] + sumArray(numbers.slice(1));',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The **empty** array is the right base case, not a one-element array — it is simpler and it makes the third test pass without a special branch. `slice(1)` returns a **new** array rather than modifying the original, which is why the input survives untouched (fifth test); `shift()` would have mutated the caller\'s array. Each call shortens the array by one, so an array of any length reaches `length === 0`. Note the combination step needs no knowledge of how the inner call works — trust it returns the sum of the rest, and add the first element.',
      },
      {
        id: 'ex-m38-01-c',
        title: 'Fix the broken recursion',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['recursion'],
        instructions:
          'Write `countDigits(n)` returning how many digits a non-negative integer has. `0` has one digit. A naive version that recurses on `n / 10` never terminates — fix that.',
        starterCode: [
          'function countDigits(n) {',
          '  // Broken idea: return 1 + countDigits(n / 10);',
          '  // Division alone never reaches a whole-number base case.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'counts a single digit', body: 'expect(countDigits(7)).toBe(1);' },
          { name: 'counts zero as one digit', body: 'expect(countDigits(0)).toBe(1);' },
          { name: 'counts two digits', body: 'expect(countDigits(42)).toBe(2);' },
          { name: 'counts many digits', body: 'expect(countDigits(1234567)).toBe(7);' },
          { name: 'handles a round number', body: 'expect(countDigits(1000)).toBe(4);' },
          { name: 'terminates rather than overflowing', body: 'expect(() => countDigits(99999)).not.toThrow();' },
          { name: 'counts a boundary value', body: 'expect(countDigits(10)).toBe(2);', hidden: true },
        ],
        hints: [
          '`Math.floor(n / 10)` removes the last digit and stays a whole number.',
          'The base case is a number below 10 — that is one digit.',
          'Check the base case before recursing, so `0` is handled.',
        ],
        solution: [
          'function countDigits(n) {',
          '  if (n < 10) return 1;',
          '',
          '  return 1 + countDigits(Math.floor(n / 10));',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`Math.floor` is what makes this terminate: plain division gives `4.2`, then `0.42`, then `0.042` — approaching zero without ever being an integer, so a base case like `n === 0` is never hit. Flooring guarantees each call removes exactly one digit and reaches a value below `10`. Choosing `n < 10` rather than `n === 0` as the base case handles `0` correctly (second test) while also stopping at any single digit — an `n === 0` base case would report `0` as having zero digits.',
      },
      {
        id: 'ex-m38-01-d',
        title: 'Predict the unwind order',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['recursion'],
        instructions:
          'A function logs `n`, then calls itself with `n - 1`, with a base case at `n === 0`. Called with `3`, in what order do the logs appear?',
        options: [
          '3, 2, 1 — the log runs before each recursive call, so on the way down',
          '1, 2, 3 — logs happen on the unwind',
          '3, 2, 1, 0',
          'Only 3',
        ],
        correct: 0,
        hints: [
          'Does the log statement run before or after the recursive call?',
        ],
        solution: '3, 2, 1 — the log runs before each recursive call, so on the way down',
        solutionExplanation:
          'The log runs **before** the recursive call, so it happens during the descent: `3`, then `2`, then `1`, then the base case returns without logging. Moving the log **after** the recursive call would reverse the output to `1, 2, 3`, because nothing after a recursive call executes until that call returns. That single choice — work before the call, or work after it — is what decides whether a recursive function produces results in descent order or unwind order, and it is the point the `mystery` prediction earlier made with string concatenation.',
      },
    ],
    quiz: {
      id: 'qz-m38-01',
      questions: [
        {
          id: 'q-m38-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['recursion'],
          prompt: 'What are the two required parts of a recursive function?',
          options: [
            'A loop and a condition',
            'A base case that returns without recursing, and a recursive case that calls with a smaller input',
            'A try and a catch',
            'A closure and a callback',
          ],
          correct: 1,
          optionExplanations: [
            'Recursion replaces the loop.',
            'Correct — and the recursive case must make progress.',
            'Error handling is unrelated.',
            'Neither is required.',
          ],
          explanation:
            'The base case stops the descent; the recursive case reduces the problem. Both are required, and the reduction must actually reach the base case.',
        },
        {
          id: 'q-m38-01-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['recursion'],
          prompt: 'What error does unbounded recursion produce?',
          options: [
            'A SyntaxError',
            'RangeError: Maximum call stack size exceeded',
            'A TypeError',
            'It runs forever with no error',
          ],
          correct: 1,
          optionExplanations: [
            'The code parses fine.',
            'Correct — frames accumulate until the limit.',
            'Nothing is the wrong type.',
            'The stack is finite.',
          ],
          explanation:
            'Only returning removes a frame, so a function that never returns fills the stack. The depth limit is engine-specific, not a fixed number.',
        },
        {
          id: 'q-m38-01-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['recursion'],
          prompt: 'Having a base case guarantees a recursive function terminates.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It must also be reachable.',
            'Correct — progress toward it is required.',
          ],
          explanation:
            'A base case that the recursion moves away from is never reached. `if (n === 0)` with `f(n + 1)` from a positive `n` overflows despite looking correct.',
        },
        {
          id: 'q-m38-01-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['recursion'],
          prompt: 'In `return n + f(n - 1)`, when does the addition happen?',
          options: [
            'Before the recursive call',
            'After the recursive call returns — during the unwind',
            'At the same time',
            'Only in the base case',
          ],
          correct: 1,
          optionExplanations: [
            'The call must be evaluated first.',
            'Correct — every frame waits for the one below.',
            'Execution is sequential.',
            'It happens in every recursive frame.',
          ],
          explanation:
            'The recursive call is evaluated before the addition, so each frame waits — the stack grows to full depth, then values combine on the way back up.',
        },
      ],
    },
    summary:
      'Recursion solves a problem by calling itself on a **smaller version of the same problem**. Every recursive function has a **base case** that returns without recursing and a **recursive case** that reduces the problem. Before running one, answer three questions: **what stops it**, **what changes on each call**, and **does that change reach the base case** — the third is the subtle one, since `if (n === 0)` with `f(n + 1)` has a perfectly valid base case that is simply unreachable, and the result is `RangeError: Maximum call stack size exceeded` (Module 33: only returning removes a frame, and the depth limit is engine-specific). Recursion producing a value has **two phases**: the **descent**, where every frame defers at `n + f(n - 1)` and waits, and the **unwind**, where values return upward and combine. Nothing is computed until the base case is reached, which is why the stack reaches full depth first and why deep recursion costs memory. Whether work happens **before** or **after** the recursive call decides whether output appears in descent or unwind order. The method for writing one: identify the input small enough to answer immediately (usually the **empty** case), find the reduction that reaches it, and describe how to combine the smaller answer into this one — then **trust** the recursive call rather than tracing it mentally.',
    keyTakeaways: [
      'Every recursive function needs a base case and a progressing recursive case',
      'A base case that exists is not the same as one that is reached',
      'Unbounded recursion gives RangeError: Maximum call stack size exceeded',
      'The descent defers all work; the unwind combines the returned values',
      'Work before the call runs descending; work after it runs unwinding',
      'Write recursion by trusting the smaller call, not by tracing every frame',
    ],
    relatedLessons: ['l-m38-02', 'l-m33-01'],
    interviewConnections: [
      'What are the two parts of a recursive function?',
      'Why might a function with a base case still overflow the stack?',
      'What is the difference between work done before and after a recursive call?',
      'How do you decide what the base case should be?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m38-02',
    slug: 'recursion-on-nested-data',
    moduleId: M,
    order: 2,
    title: 'Recursion on Nested Data',
    description: 'Where recursion genuinely earns its place — structures of unknown depth.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 19,
    xp: 50,
    topicIds: ['recursion'],
    prerequisites: ['l-m38-01'],
    learningObjectives: [
      'Traverse nested structures of arbitrary depth',
      'Search and transform tree-shaped data',
      'Accumulate results across a recursive traversal',
      'Recognise the shape that makes recursion the right tool',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'The shape that demands recursion',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Counting down and summing an array are teaching examples — a loop does both more plainly. Recursion earns its place when the data is **defined in terms of itself**.',
          'A category contains categories. A comment has replies, which have replies. A menu item has sub-items. In each case the depth is not known when you write the code, so no fixed number of nested loops can handle it.',
          'That is the tell: **a structure whose parts have the same shape as the whole**.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Flattening a structure of unknown depth.',
        code: [
          '"use strict";',
          '',
          'const nested = [1, [2, [3, [4, [5]]]], 6];',
          '',
          'function flatten(items) {',
          '  const result = [];',
          '',
          '  for (const item of items) {',
          '    if (Array.isArray(item)) {',
          '      // The item has the same shape as the whole — recurse',
          '      result.push(...flatten(item));',
          '    } else {',
          '      result.push(item);',
          '    }',
          '  }',
          '',
          '  return result;',
          '}',
          '',
          'console.log("flat  :", flatten(nested));',
          'console.log("empty :", flatten([]));',
          'console.log("nested empties:", flatten([1, [], [[]], 2]));',
          '',
          '// A loop cannot do this without its own stack, because the',
          '// depth is a property of the DATA, not of the code',
          'console.log("depth 5 reached:", flatten(nested).includes(5));',
        ].join('\n'),
        output: [
          'flat  : [1, 2, 3, 4, 5, 6]',
          'empty : []',
          'nested empties: [1, 2]',
          'depth 5 reached: true',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'The base case here is implicit',
        body: [
          'There is no `if (done) return` — the base case is an array with **no nested arrays**, at which point the loop runs and no recursive call happens. An empty array is the extreme case, and it works because the loop body simply never executes.',
          'This is common with structural recursion: the base case falls out of the structure rather than being a written condition. What matters is still the same — some inputs recurse no further.',
          'Note `Array.isArray` is the correct test, not `typeof`, which reports `"object"` for arrays (Module 02).',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Searching a tree',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Finding a node at unknown depth.',
        code: [
          '"use strict";',
          '',
          'const categories = {',
          '  id: "root",',
          '  name: "All",',
          '  children: [',
          '    {',
          '      id: "electronics",',
          '      name: "Electronics",',
          '      children: [',
          '        { id: "phones", name: "Phones", children: [] },',
          '        {',
          '          id: "computers",',
          '          name: "Computers",',
          '          children: [',
          '            { id: "laptops", name: "Laptops", children: [] },',
          '          ],',
          '        },',
          '      ],',
          '    },',
          '    { id: "books", name: "Books", children: [] },',
          '  ],',
          '};',
          '',
          'function findById(node, id) {',
          '  // Base case 1: this is it',
          '  if (node.id === id) return node;',
          '',
          '  // Recursive case: ask each child',
          '  for (const child of node.children) {',
          '    const found = findById(child, id);',
          '',
          '    // Stop as soon as any branch succeeds',
          '    if (found) return found;',
          '  }',
          '',
          '  // Base case 2: not here, and no children left',
          '  return null;',
          '}',
          '',
          'console.log("deep   :", findById(categories, "laptops").name);',
          'console.log("shallow:", findById(categories, "books").name);',
          'console.log("root   :", findById(categories, "root").name);',
          'console.log("missing:", findById(categories, "nope"));',
        ].join('\n'),
        output: [
          'deep   : Laptops',
          'shallow: Books',
          'root   : All',
          'missing: null',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Returning the result of a recursive call is not optional',
        body: [
          'The most common bug in tree search is calling `findById(child, id)` and **discarding** the result — the search runs correctly and then throws the answer away, so everything returns `null`.',
          'Equally common is `return findById(child, id)` directly inside the loop, which returns `null` from the **first** child that fails instead of trying the rest. The `if (found) return found;` shape is what allows the loop to continue searching siblings.',
          'This function returns `null` for "not found", which lets `if (found)` work naturally. Returning `undefined` would behave identically here; the important part is choosing one and being consistent.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Accumulating across a traversal',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Collecting every match, and tracking depth.',
        code: [
          '"use strict";',
          '',
          'const comments = {',
          '  id: 1, author: "ada", text: "first", replies: [',
          '    { id: 2, author: "bo", text: "reply", replies: [',
          '      { id: 3, author: "ada", text: "nested", replies: [] },',
          '    ] },',
          '    { id: 4, author: "cy", text: "another", replies: [] },',
          '  ],',
          '};',
          '',
          '// Collect all comments by one author, at any depth',
          'function findByAuthor(comment, author) {',
          '  const matches = comment.author === author ? [comment.id] : [];',
          '',
          '  for (const reply of comment.replies) {',
          '    matches.push(...findByAuthor(reply, author));',
          '  }',
          '',
          '  return matches;',
          '}',
          '',
          'console.log("ada :", findByAuthor(comments, "ada"));',
          'console.log("bo  :", findByAuthor(comments, "bo"));',
          'console.log("none:", findByAuthor(comments, "zz"));',
          '',
          '// Depth is tracked by passing it down, not by a shared variable',
          'function outline(comment, depth = 0) {',
          '  const lines = [`${"  ".repeat(depth)}${comment.author}: ${comment.text}`];',
          '',
          '  for (const reply of comment.replies) {',
          '    lines.push(...outline(reply, depth + 1));',
          '  }',
          '',
          '  return lines;',
          '}',
          '',
          'outline(comments).forEach((line) => console.log(line));',
          '',
          '// And the deepest nesting level',
          'function maxDepth(comment) {',
          '  if (comment.replies.length === 0) return 1;',
          '',
          '  return 1 + Math.max(...comment.replies.map(maxDepth));',
          '}',
          '',
          'console.log("max depth:", maxDepth(comments));',
        ].join('\n'),
        output: [
          'ada : [1, 3]',
          'bo  : [2]',
          'none: []',
          'ada: first',
          '  bo: reply',
          '    ada: nested',
          '  cy: another',
          'max depth: 3',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Pass state down; return results up',
        body: [
          '`outline` tracks depth by **passing `depth + 1`** to each child rather than mutating a shared counter. Each frame gets its own value, so sibling branches never interfere — the same independence closures gave you in Module 32.',
          'A shared `let depth` outside the function would be incremented on the way down and would need decrementing on the way back, which is easy to get wrong and impossible to run twice concurrently.',
          'Note `maxDepth` uses `Math.max(...)` with spread. That is fine for a modest tree but would fail on one with tens of thousands of siblings, since spread passes each as an argument — `reduce` avoids that limit.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Transforming a tree',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Producing a new structure without mutating the original.',
        code: [
          '"use strict";',
          '',
          'const menu = {',
          '  label: "File", items: [',
          '    { label: "New", items: [] },',
          '    { label: "Export", items: [',
          '      { label: "PDF", items: [] },',
          '    ] },',
          '  ],',
          '};',
          '',
          '// Add a `path` to every node, built from its ancestors',
          'function withPaths(node, parentPath = "") {',
          '  const path = parentPath ? `${parentPath}/${node.label}` : node.label;',
          '',
          '  return {',
          '    ...node,',
          '    path,',
          '    items: node.items.map((item) => withPaths(item, path)),',
          '  };',
          '}',
          '',
          'const annotated = withPaths(menu);',
          '',
          'console.log("root :", annotated.path);',
          'console.log("child:", annotated.items[1].path);',
          'console.log("deep :", annotated.items[1].items[0].path);',
          '',
          '// The original is untouched',
          'console.log("original has path:", "path" in menu);',
          'console.log("different object :", annotated !== menu);',
        ].join('\n'),
        output: [
          'root : File',
          'child: File/Export',
          'deep : File/Export/PDF',
          'original has path: false',
          'different object : true',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The pattern is worth memorising: **spread the node, override what changes, and map the children through the same function**. It produces a fully new tree with no mutation, at any depth, in four lines.',
          'Note the recursion appears inside `map` — each child is transformed by the same function that transformed the parent, which is exactly the "parts have the same shape as the whole" property.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Cycles will hang a naive traversal',
        body: [
          'Every example here assumes a **tree** — no node reachable from itself. If a structure can contain a cycle (a category that is its own ancestor, an object graph with back-references), a naive traversal recurses forever and overflows the stack.',
          'The fix is a **visited set**, exactly as Module 36\'s `deepFreeze` used the frozen state: track nodes already seen and return early on a repeat. Module 39 covers this properly for graphs.',
          'Data from an API is usually a tree. Data you built by linking objects together often is not — check before assuming.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '"use strict";',
          '',
          'const tree = { v: 1, kids: [{ v: 2, kids: [] }, { v: 3, kids: [] }] };',
          '',
          'function find(node, target) {',
          '  if (node.v === target) return node;',
          '',
          '  for (const kid of node.kids) {',
          '    find(kid, target);          // note: result not returned',
          '  }',
          '',
          '  return null;',
          '}',
          '',
          'console.log(find(tree, 3));',
        ].join('\n'),
        options: [
          'null',
          '{ v: 3, kids: [] }',
          'undefined',
          'It throws',
        ],
        correct: 0,
        explanation:
          'The search genuinely **finds** the node — the recursive call on the second child returns it — and then **throws the result away**, because the return value is never captured or returned. Every frame falls through to `return null`. This is the single most common tree-search bug, and it is invisible on a quick read since the recursive call is right there. The fix is to capture and check: `const found = find(kid, target); if (found) return found;` — note that `return find(kid, target)` directly would be wrong too, returning `null` from the **first** child that fails instead of trying the remaining siblings.',
      },
    ],
    exercises: [
      {
        id: 'ex-m38-02-a',
        title: 'Flatten nested arrays',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['recursion'],
        instructions:
          'Write `flatten(items)` returning a fully flattened array of any depth. Do not use the built-in `Array.prototype.flat`.',
        starterCode: [
          'function flatten(items) {',
          '  // An element that is itself an array has the same shape as the whole.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'flattens one level', body: 'expect(flatten([1, [2, 3]])).toEqual([1, 2, 3]);' },
          { name: 'flattens deeply', body: 'expect(flatten([1, [2, [3, [4]]]])).toEqual([1, 2, 3, 4]);' },
          { name: 'handles an already-flat array', body: 'expect(flatten([1, 2, 3])).toEqual([1, 2, 3]);' },
          { name: 'handles an empty array', body: 'expect(flatten([])).toEqual([]);' },
          { name: 'drops empty nested arrays', body: 'expect(flatten([1, [], [[]], 2])).toEqual([1, 2]);' },
          { name: 'preserves falsy values', body: 'expect(flatten([0, [null, [false, ""]]])).toEqual([0, null, false, ""]);' },
          { name: 'does not mutate the input', body: 'const input = [1, [2]]; flatten(input); expect(input).toEqual([1, [2]]);', hidden: true },
        ],
        hints: [
          '`Array.isArray(item)` decides which branch you are in.',
          'Push the recursive result with spread, or concat it.',
          'Build a new array — never push into the input.',
        ],
        solution: [
          'function flatten(items) {',
          '  const result = [];',
          '',
          '  for (const item of items) {',
          '    if (Array.isArray(item)) {',
          '      result.push(...flatten(item));',
          '    } else {',
          '      result.push(item);',
          '    }',
          '  }',
          '',
          '  return result;',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`Array.isArray` is the correct test — `typeof` reports `"object"` for arrays, so it cannot distinguish them. The base case is implicit: an array containing no nested arrays simply never recurses, and an empty array runs the loop zero times. Pushing values directly rather than filtering preserves `0`, `null`, `false` and `""`, which the sixth test checks; a truthiness guard would silently drop all four. Building a fresh `result` array leaves the input untouched, as the hidden test confirms.',
      },
      {
        id: 'ex-m38-02-b',
        title: 'Search a category tree',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['recursion'],
        instructions:
          'Write `findNode(node, id)` returning the node with that `id` from a tree whose children live in `node.children`, or `null` when absent. It must search every branch.',
        starterCode: [
          'function findNode(node, id) {',
          '  // Capture the recursive result — do not discard it.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'finds the root', body: 'expect(findNode({ id: "a", children: [] }, "a").id).toBe("a");' },
          { name: 'finds a direct child', body: 'expect(findNode({ id: "a", children: [{ id: "b", children: [] }] }, "b").id).toBe("b");' },
          { name: 'finds a deep node', body: 'expect(findNode({ id: "a", children: [{ id: "b", children: [{ id: "c", children: [] }] }] }, "c").id).toBe("c");' },
          { name: 'returns null when absent', body: 'expect(findNode({ id: "a", children: [] }, "zz")).toBe(null);' },
          { name: 'searches later siblings after an earlier one fails', body: 'expect(findNode({ id: "a", children: [{ id: "b", children: [] }, { id: "c", children: [] }] }, "c").id).toBe("c");' },
          { name: 'searches deep in a later branch', body: 'expect(findNode({ id: "a", children: [{ id: "b", children: [] }, { id: "c", children: [{ id: "d", children: [] }] }] }, "d").id).toBe("d");' },
          { name: 'returns the node itself, not a copy', body: 'const target = { id: "b", children: [] }; expect(findNode({ id: "a", children: [target] }, "b")).toBe(target);', hidden: true },
        ],
        hints: [
          'Check `node.id` first — that is the success base case.',
          'Loop the children, store each recursive result in a variable.',
          'Return it only when truthy, so the loop can continue.',
        ],
        solution: [
          'function findNode(node, id) {',
          '  if (node.id === id) return node;',
          '',
          '  for (const child of node.children) {',
          '    const found = findNode(child, id);',
          '',
          '    if (found) return found;',
          '  }',
          '',
          '  return null;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The `if (found) return found;` shape is the whole exercise. Discarding the result makes every call return `null` even though the node was located; returning `findNode(child, id)` directly would return `null` from the **first** failing child and never reach later siblings — which is precisely what the fifth and sixth tests catch. Returning the node object rather than a copy (hidden test) lets callers mutate or compare it by identity, which is what a `find` is expected to do.',
      },
      {
        id: 'ex-m38-02-c',
        title: 'Sum a nested structure',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['recursion'],
        instructions:
          'Write `totalSize(node)` returning the sum of `node.size` plus the total size of every descendant, for a tree whose children live in `node.children`.',
        starterCode: [
          'function totalSize(node) {',
          '  // This node, plus the totals of all its children.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'a leaf is its own size', body: 'expect(totalSize({ size: 5, children: [] })).toBe(5);' },
          { name: 'adds one level of children', body: 'expect(totalSize({ size: 1, children: [{ size: 2, children: [] }, { size: 3, children: [] }] })).toBe(6);' },
          { name: 'adds deeply', body: 'expect(totalSize({ size: 1, children: [{ size: 2, children: [{ size: 4, children: [] }] }] })).toBe(7);' },
          { name: 'handles a zero size', body: 'expect(totalSize({ size: 0, children: [{ size: 3, children: [] }] })).toBe(3);' },
          { name: 'handles a wide tree', body: 'expect(totalSize({ size: 0, children: [1, 2, 3, 4].map((n) => ({ size: n, children: [] })) })).toBe(10);' },
          { name: 'does not mutate the tree', body: 'const t = { size: 1, children: [{ size: 2, children: [] }] }; totalSize(t); expect(t.children.length).toBe(1);' },
          { name: 'handles an unbalanced tree', body: 'expect(totalSize({ size: 1, children: [{ size: 1, children: [{ size: 1, children: [{ size: 1, children: [] }] }] }, { size: 1, children: [] }] })).toBe(5);', hidden: true },
        ],
        hints: [
          'Start from `node.size`.',
          'Add `totalSize(child)` for each child.',
          '`reduce` over the children reads well here.',
        ],
        solution: [
          'function totalSize(node) {',
          '  return node.children.reduce(',
          '    (sum, child) => sum + totalSize(child),',
          '    node.size,',
          '  );',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Using `node.size` as the **initial accumulator** folds the base case into the reduce: a leaf has no children, so the callback never runs and the node\'s own size is returned. That removes the need for an explicit `if (children.length === 0)` branch entirely. Each child contributes its own full subtotal, which is the "trust the recursive call" leap from lesson 1 — you never need to think about how deep any branch goes. Nothing is mutated, since `reduce` only accumulates a number.',
      },
      {
        id: 'ex-m38-02-d',
        title: 'When is recursion the right tool?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['recursion'],
        instructions:
          'Which problem is recursion genuinely better suited to than a loop?',
        options: [
          'Summing an array of numbers',
          'Collecting every node from a category tree of unknown depth',
          'Formatting each item in a list',
          'Counting to ten',
        ],
        correct: 1,
        hints: [
          'Which one has a depth you cannot know when writing the code?',
        ],
        solution: 'Collecting every node from a category tree of unknown depth',
        solutionExplanation:
          'The tree is **defined in terms of itself** — a category contains categories — so no fixed number of nested loops can handle it, and the depth is a property of the data rather than the code. That is the tell for recursion. The other three are **linear**: one pass over a flat sequence, which a loop or an array method expresses more plainly. Writing them recursively is a valid exercise but not an improvement, and it adds stack depth for nothing.',
      },
    ],
    quiz: {
      id: 'qz-m38-02',
      questions: [
        {
          id: 'q-m38-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['recursion'],
          prompt: 'What shape of data makes recursion the natural choice?',
          options: [
            'Any array',
            'A structure whose parts have the same shape as the whole, at unknown depth',
            'Sorted data',
            'Data with more than 100 items',
          ],
          correct: 1,
          optionExplanations: [
            'A flat array suits a loop.',
            'Correct — self-similar and arbitrarily deep.',
            'Sorting is unrelated.',
            'Size is not the criterion.',
          ],
          explanation:
            'Trees, nested comments and nested menus are defined in terms of themselves, so the depth belongs to the data. No fixed nesting of loops can traverse them.',
        },
        {
          id: 'q-m38-02-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['recursion'],
          prompt: 'Why must a tree search capture the recursive call\'s result?',
          options: [
            'For performance',
            'Otherwise the node is found and the answer discarded, so every call returns the not-found value',
            'To avoid stack overflow',
            'It is only needed for deep trees',
          ],
          correct: 1,
          optionExplanations: [
            'Speed is unaffected.',
            'Correct — the most common tree-search bug.',
            'Depth is unchanged.',
            'It fails at any depth.',
          ],
          explanation:
            'The search succeeds and then throws the result away. Capture it and return only when truthy, so the loop can continue to later siblings on failure.',
        },
        {
          id: 'q-m38-02-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['recursion'],
          prompt: 'Tracking depth with a shared variable outside the function is safer than passing it as a parameter.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It must be decremented on unwind and breaks with concurrent use.',
            'Correct — pass it down instead.',
          ],
          explanation:
            'A parameter gives each frame its own value, so sibling branches never interfere. A shared counter must be decremented on the way back up and cannot support two traversals at once.',
        },
        {
          id: 'q-m38-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['recursion'],
          prompt: 'What happens if a "tree" actually contains a cycle?',
          options: [
            'Nothing — recursion handles it',
            'A naive traversal recurses forever and overflows the stack; a visited set is needed',
            'It returns null',
            'The cycle is skipped automatically',
          ],
          correct: 1,
          optionExplanations: [
            'There is no automatic protection.',
            'Correct — track visited nodes.',
            'It never terminates to return anything.',
            'Nothing detects it.',
          ],
          explanation:
            'A node reachable from itself makes the traversal loop indefinitely. Track visited nodes and return early on a repeat — the technique Module 36\'s deepFreeze used.',
        },
      ],
    },
    summary:
      'Recursion earns its place when data is **defined in terms of itself** — a category containing categories, a comment with replies, a menu with sub-items — because the **depth belongs to the data**, so no fixed nesting of loops can handle it. In structural recursion the **base case is often implicit**: an array with no nested arrays simply never recurses. Use `Array.isArray` rather than `typeof`, which reports `"object"` for arrays. Tree **search** has one dominant bug: calling recursively and **discarding the result**, so the node is found and the answer thrown away — capture it and `if (found) return found;`, since returning the call directly would abandon later siblings after the first failure. For **accumulation**, pass state **down** as a parameter (each frame gets its own copy, so branches never interfere) and return results **up**; a shared counter must be decremented on unwind and cannot support concurrent traversals. To **transform** a tree, spread the node, override what changes, and map the children through the same function — a whole new tree, no mutation, at any depth. Finally, every technique here assumes a genuine **tree**: a structure containing a **cycle** makes a naive traversal recurse forever, so track a **visited set** when back-references are possible.',
    keyTakeaways: [
      'Recursion fits data whose parts have the same shape as the whole',
      'In structural recursion the base case is often implicit',
      'Capture the recursive result — discarding it is the classic tree-search bug',
      'if (found) return found — returning directly abandons later siblings',
      'Pass state down as a parameter; return results up',
      'Cycles hang a naive traversal — use a visited set',
    ],
    relatedLessons: ['l-m38-01', 'l-m38-03'],
    interviewConnections: [
      'How would you flatten an arbitrarily nested array?',
      'How do you search a tree for a node by id?',
      'Why pass depth as a parameter rather than using a shared variable?',
      'What happens if the structure contains a cycle?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m38-03',
    slug: 'recursion-versus-iteration',
    moduleId: M,
    order: 3,
    title: 'Recursion versus Iteration',
    description: 'Converting between the two, the cost of repeated work, and choosing honestly.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 18,
    xp: 50,
    topicIds: ['recursion', 'algorithms'],
    prerequisites: ['l-m38-02'],
    learningObjectives: [
      'Convert a recursive function to an iterative one and back',
      'Replace deep recursion with an explicit stack',
      'Explain why naive recursive Fibonacci is slow',
      'Choose between recursion and iteration on real criteria',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'The same problem, both ways',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Linear problems: the loop is usually plainer.',
        code: [
          '"use strict";',
          '',
          'function factorialRecursive(n) {',
          '  if (n <= 1) return 1;',
          '  return n * factorialRecursive(n - 1);',
          '}',
          '',
          'function factorialIterative(n) {',
          '  let result = 1;',
          '',
          '  for (let i = 2; i <= n; i++) {',
          '    result *= i;',
          '  }',
          '',
          '  return result;',
          '}',
          '',
          'console.log("recursive:", factorialRecursive(6));',
          'console.log("iterative:", factorialIterative(6));',
          'console.log("agree    :", factorialRecursive(10) === factorialIterative(10));',
          '',
          '// The iterative version uses ONE frame regardless of n;',
          '// the recursive version uses n frames.',
          'console.log("large ok :", factorialIterative(170) < Infinity);',
        ].join('\n'),
        output: [
          'recursive: 720',
          'iterative: 720',
          'agree    : true',
          'large ok : true',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Recursion is not the more advanced choice',
        body: [
          'Both versions above are correct and clear. The recursive one mirrors the mathematical definition; the iterative one uses constant stack space. Neither is a sign of skill.',
          'For a **linear** problem — walk a sequence, accumulate a result — iteration is usually the plainer expression, and it cannot overflow. Reaching for recursion to look sophisticated is a real anti-pattern.',
          'Note `factorial(170)` is near the largest factorial `Number` can hold; beyond that it becomes `Infinity`. That is Module 06\'s floating-point range, not a recursion issue.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Converting a tree traversal to a loop',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Any recursion can become a loop with an explicit stack.',
        code: [
          '"use strict";',
          '',
          'const tree = {',
          '  id: 1, children: [',
          '    { id: 2, children: [{ id: 4, children: [] }, { id: 5, children: [] }] },',
          '    { id: 3, children: [] },',
          '  ],',
          '};',
          '',
          '// Recursive: the CALL STACK remembers where to resume',
          'function collectRecursive(node) {',
          '  const ids = [node.id];',
          '',
          '  for (const child of node.children) {',
          '    ids.push(...collectRecursive(child));',
          '  }',
          '',
          '  return ids;',
          '}',
          '',
          '// Iterative: an ARRAY does the remembering instead',
          'function collectIterative(root) {',
          '  const ids = [];',
          '  const stack = [root];',
          '',
          '  while (stack.length > 0) {',
          '    const node = stack.pop();',
          '    ids.push(node.id);',
          '',
          '    // Push children in reverse so the first is processed first',
          '    for (let i = node.children.length - 1; i >= 0; i--) {',
          '      stack.push(node.children[i]);',
          '    }',
          '  }',
          '',
          '  return ids;',
          '}',
          '',
          'console.log("recursive:", collectRecursive(tree));',
          'console.log("iterative:", collectIterative(tree));',
        ].join('\n'),
        output: [
          'recursive: [1, 2, 4, 5, 3]',
          'iterative: [1, 2, 4, 5, 3]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The call stack was always a stack',
        body: [
          'Recursion does not have a capability iteration lacks. What it has is the **call stack doing the bookkeeping for free** — remembering which node you were on and which child came next.',
          'Replace it with an explicit array and the loop does the same job. The cost is that you now manage the order yourself, which is why children are pushed **in reverse**: a stack is last-in-first-out, so pushing them forwards would visit the last child first.',
          'The benefit is real: the array lives in the heap, so depth is limited by memory rather than by the call stack. A tree 100,000 levels deep would overflow the recursive version and work fine here.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Swapping the stack for a queue changes the traversal order.',
        code: [
          '"use strict";',
          '',
          'const tree = {',
          '  id: 1, children: [',
          '    { id: 2, children: [{ id: 4, children: [] }, { id: 5, children: [] }] },',
          '    { id: 3, children: [] },',
          '  ],',
          '};',
          '',
          '// A QUEUE (first in, first out) visits level by level',
          'function breadthFirst(root) {',
          '  const ids = [];',
          '  const queue = [root];',
          '  let head = 0;',
          '',
          '  while (head < queue.length) {',
          '    const node = queue[head++];',
          '    ids.push(node.id);',
          '',
          '    for (const child of node.children) {',
          '      queue.push(child);',
          '    }',
          '  }',
          '',
          '  return ids;',
          '}',
          '',
          'console.log("depth first  :", [1, 2, 4, 5, 3]);',
          'console.log("breadth first:", breadthFirst(tree));',
        ].join('\n'),
        output: [
          'depth first  : [1, 2, 4, 5, 3]',
          'breadth first: [1, 2, 3, 4, 5]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Breadth-first has no simple recursive form',
        body: [
          'Depth-first falls out of recursion naturally, because the call stack **is** a stack. Breadth-first needs a **queue**, and the call stack cannot provide one — so this traversal is genuinely easier iteratively.',
          'That matters when you want the **nearest** match rather than any match: breadth-first finds the shallowest node first. Module 39 develops both properly.',
          'Note the `head` index rather than `queue.shift()`. Shifting removes the first element and moves every remaining one, so a loop of shifts does far more work than necessary — Module 39 covers this too.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'When recursion repeats itself',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Naive Fibonacci — correct, and doing enormous duplicate work.',
        code: [
          '"use strict";',
          '',
          'let calls = 0;',
          '',
          'function fib(n) {',
          '  calls += 1;',
          '',
          '  if (n <= 1) return n;',
          '',
          '  return fib(n - 1) + fib(n - 2);',
          '}',
          '',
          'for (const n of [5, 10, 20, 25]) {',
          '  calls = 0;',
          '  const value = fib(n);',
          '  console.log(`fib(${n}) = ${value}, calls: ${calls}`);',
          '}',
        ].join('\n'),
        output: [
          'fib(5) = 5, calls: 15',
          'fib(10) = 55, calls: 177',
          'fib(20) = 6765, calls: 21891',
          'fib(25) = 75025, calls: 242785',
        ].join('\n'),
      },
      {
        kind: SECTION.CODE,
        language: 'text',
        caption: 'Why — the same subproblems, over and over.',
        code: [
          '            fib(5)',
          '           /      \\',
          '      fib(4)        fib(3)',
          '      /    \\        /    \\',
          '  fib(3)  fib(2)  fib(2)  fib(1)',
          '   /  \\    /  \\    /  \\',
          'fib(2) fib(1) ...  ...',
          '',
          '  fib(3) is computed twice.',
          '  fib(2) is computed three times.',
          '  Each extra level roughly DOUBLES the work.',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Recursion does not make an algorithm efficient',
        body: [
          'Look at the call counts: `fib(20)` takes about 22,000 calls and `fib(25)` about 243,000 — roughly ten times more for five extra steps. This is **exponential** growth, and `fib(50)` would take longer than you are willing to wait.',
          'The function is perfectly correct. It is the **algorithm** that is wasteful, recomputing the same subproblems across separate branches. Module 39 gives this behaviour a name and a notation.',
          'Naive recursive Fibonacci is a fine teaching example and is **not** production code. Anyone presenting it as the recursive solution to Fibonacci is demonstrating the problem, not the answer.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Two fixes: remember results, or iterate.',
        code: [
          '"use strict";',
          '',
          'let calls = 0;',
          '',
          '// FIX 1: memoise — a cache in a closure (Module 32)',
          'function makeFib() {',
          '  const cache = new Map();',
          '',
          '  return function fib(n) {',
          '    calls += 1;',
          '',
          '    if (n <= 1) return n;',
          '    if (cache.has(n)) return cache.get(n);',
          '',
          '    const value = fib(n - 1) + fib(n - 2);',
          '    cache.set(n, value);',
          '    return value;',
          '  };',
          '}',
          '',
          'const memoFib = makeFib();',
          'calls = 0;',
          'console.log(`memoised fib(25) = ${memoFib(25)}, calls: ${calls}`);',
          '',
          '// FIX 2: iterate — build upward, no stack, no cache',
          'function fibIterative(n) {',
          '  if (n <= 1) return n;',
          '',
          '  let previous = 0;',
          '  let current = 1;',
          '',
          '  for (let i = 2; i <= n; i++) {',
          '    [previous, current] = [current, previous + current];',
          '  }',
          '',
          '  return current;',
          '}',
          '',
          'console.log("iterative fib(25):", fibIterative(25));',
          'console.log("agree            :", memoFib(30) === fibIterative(30));',
          '',
          '// Both fixes handle large n effortlessly — but the NUMBER TYPE',
          '// runs out of precision long before the algorithm struggles',
          'console.log("fib(78) exact?   :", Number.isSafeInteger(fibIterative(78)));',
          'console.log("fib(79) exact?   :", Number.isSafeInteger(fibIterative(79)));',
          'console.log("fib(80)          :", fibIterative(80), "<- no longer exact");',
        ].join('\n'),
        output: [
          'memoised fib(25) = 75025, calls: 49',
          'iterative fib(25): 75025',
          'agree            : true',
          'fib(78) exact?   : true',
          'fib(79) exact?   : false',
          'fib(80)          : 23416728348467684 <- no longer exact',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          '243,000 calls became **49**. The memoised version is still recursive — the recursion was never the problem, the **repeated work** was.',
          'The iterative version needs neither a cache nor stack depth. This is the general shape: when a recursive solution recomputes overlapping subproblems, either remember them or build upward instead.',
          'The last three lines are a reminder from a different direction. Once the algorithm stops being the constraint, the **number type** becomes one: `fib(79)` exceeds `Number.MAX_SAFE_INTEGER`, so `fib(80)` is computed instantly and is **off by one**. Module 06 covers why; use `BigInt` when exact large integers matter. Fixing an algorithm does not make its output correct.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Choosing',
      },
      {
        kind: SECTION.TABLE,
        headers: ['', 'Recursion', 'Iteration'],
        rows: [
          ['Natural for', '**Self-similar structures** — trees, nested data', '**Linear sequences** — arrays, ranges, counters'],
          ['Depth limit', 'The call stack — engine-specific', 'Memory only'],
          ['Bookkeeping', 'Handled by the call stack', 'You manage it explicitly'],
          ['Breadth-first traversal', 'Awkward — needs a queue anyway', '**Natural**'],
          ['Overlapping subproblems', 'Can be catastrophic without memoisation', 'Usually builds upward, so no repeats'],
          ['Debugging', 'Many similar frames to step through', 'One frame, inspectable state'],
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Depth is the practical constraint',
        body: [
          'Module 33 established that the maximum stack depth is engine- and platform-specific, and that JavaScript engines generally do **not** implement tail-call elimination despite it being specified — so writing a recursive function in "tail position" does not save a frame.',
          'In practice a few thousand frames is safe and tens of thousands is not. Tree data from an API is rarely deeper than dozens of levels, so recursion is fine. A linked list of 100,000 nodes, or a linear recursion over a large array, is not.',
          'If depth might be large and unbounded, use the explicit-stack conversion from earlier in this lesson.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '"use strict";',
          '',
          'let count = 0;',
          '',
          'function f(n) {',
          '  count += 1;',
          '  if (n <= 1) return n;',
          '  return f(n - 1) + f(n - 2);',
          '}',
          '',
          'f(5);',
          'console.log(count);',
        ].join('\n'),
        options: [
          '15',
          '5',
          '6',
          '8',
        ],
        correct: 0,
        explanation:
          'Each call spawns **two** more until the base case, so the calls form a binary tree rather than a chain: `f(5)` needs `f(4)` and `f(3)`, `f(4)` needs `f(3)` and `f(2)`, and so on — with `f(3)` computed twice and `f(2)` three times. Counting every node gives **15**. The important part is the growth: `f(10)` takes 177 calls and `f(25)` takes 242,785, roughly doubling per step. That is **exponential** work caused by recomputing overlapping subproblems, and it is a property of the *algorithm*, not of recursion — memoising the same recursive function reduces `f(25)` to 49 calls.',
      },
    ],
    exercises: [
      {
        id: 'ex-m38-03-a',
        title: 'Convert recursion to iteration',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['recursion'],
        instructions:
          'Rewrite `countNodes(node)` iteratively using an explicit stack, so it works on a tree of any depth without risking stack overflow. Children live in `node.children`.',
        starterCode: [
          '// Recursive version, for reference:',
          '// function countNodes(node) {',
          '//   return 1 + node.children.reduce((s, c) => s + countNodes(c), 0);',
          '// }',
          '',
          'function countNodes(root) {',
          '  // Use an array as the stack instead of the call stack.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'counts a single node', body: 'expect(countNodes({ children: [] })).toBe(1);' },
          { name: 'counts one level', body: 'expect(countNodes({ children: [{ children: [] }, { children: [] }] })).toBe(3);' },
          { name: 'counts deeply', body: 'expect(countNodes({ children: [{ children: [{ children: [] }] }] })).toBe(3);' },
          { name: 'counts an unbalanced tree', body: 'expect(countNodes({ children: [{ children: [{ children: [] }] }, { children: [] }] })).toBe(4);' },
          { name: 'uses no recursion depth on a deep chain', body: 'let deep = { children: [] }; for (let i = 0; i < 20000; i++) deep = { children: [deep] }; expect(countNodes(deep)).toBe(20001);' },
          { name: 'does not mutate the tree', body: 'const t = { children: [{ children: [] }] }; countNodes(t); expect(t.children.length).toBe(1);' },
          { name: 'counts a wide tree', body: 'expect(countNodes({ children: Array.from({ length: 50 }, () => ({ children: [] })) })).toBe(51);', hidden: true },
        ],
        hints: [
          'Start with `const stack = [root]` and a counter.',
          'While the stack is not empty, pop a node, count it, push its children.',
          'Order does not matter here — you are only counting.',
        ],
        solution: [
          'function countNodes(root) {',
          '  let count = 0;',
          '  const stack = [root];',
          '',
          '  while (stack.length > 0) {',
          '    const node = stack.pop();',
          '    count += 1;',
          '',
          '    for (const child of node.children) {',
          '      stack.push(child);',
          '    }',
          '  }',
          '',
          '  return count;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The array replaces the call stack: it remembers which nodes are still to visit, which is the only thing the recursion was using the call stack for. The fifth test is the reason this conversion matters — a 20,000-deep chain would throw `RangeError` in the recursive version, while the iterative one stores those nodes in the **heap** and completes. Because this only counts, the visit order is irrelevant, so no reversing is needed; a traversal that produced ordered output would need to push children in reverse.',
      },
      {
        id: 'ex-m38-03-b',
        title: 'Memoise a recursive function',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['recursion'],
        instructions:
          'Write `makeFib()` returning a memoised Fibonacci function. `fib(0)` is `0`, `fib(1)` is `1`. It must compute `fib(30)` without exponential work, and separate calls to `makeFib()` must not share a cache.',
        starterCode: [
          'function makeFib() {',
          '  // A cache in the closure; check it before recomputing.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'handles the base cases', body: 'const f = makeFib(); expect([f(0), f(1)]).toEqual([0, 1]);' },
          { name: 'computes small values', body: 'const f = makeFib(); expect([f(2), f(5), f(10)]).toEqual([1, 5, 55]);' },
          { name: 'computes a large value', body: 'expect(makeFib()(30)).toBe(832040);' },
          { name: 'is fast enough for 60', body: 'expect(makeFib()(60)).toBe(1548008755920);' },
          { name: 'caches across calls', body: 'const f = makeFib(); f(25); let n = 0; const before = f(25); expect(before).toBe(75025);' },
          { name: 'instances have separate caches', body: 'const a = makeFib(); const b = makeFib(); a(20); expect(b(20)).toBe(6765);' },
          { name: 'is consistent when called out of order', body: 'const f = makeFib(); expect([f(10), f(3), f(10)]).toEqual([55, 2, 55]);', hidden: true },
        ],
        hints: [
          '`const cache = new Map();` inside `makeFib`.',
          'Return a named function so it can recurse.',
          'Check the cache before computing, and store the result after.',
        ],
        solution: [
          'function makeFib() {',
          '  const cache = new Map();',
          '',
          '  return function fib(n) {',
          '    if (n <= 1) return n;',
          '    if (cache.has(n)) return cache.get(n);',
          '',
          '    const value = fib(n - 1) + fib(n - 2);',
          '',
          '    cache.set(n, value);',
          '    return value;',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The cache turns exponential work into linear: each `n` is computed once and reused, so `fib(60)` finishes instantly where the naive version would take effectively forever. Naming the returned function is what lets it recurse into **itself** — recursing into an outer helper would bypass the cache entirely. Declaring `cache` inside `makeFib` gives each instance its own, which the sixth test checks, and using `cache.has` rather than a truthiness check matters because `fib` legitimately returns `0`. Note the recursion was never the problem; the repeated work was.',
      },
      {
        id: 'ex-m38-03-c',
        title: 'Why is naive Fibonacci slow?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['recursion', 'algorithms'],
        instructions:
          'What makes `fib(n) = fib(n-1) + fib(n-2)` take exponentially long?',
        options: [
          'Recursion is inherently slow',
          'Each call spawns two more, and the same subproblems are recomputed across separate branches',
          'The call stack overflows',
          'Numbers get too large',
        ],
        correct: 1,
        hints: [
          'How many times is fib(2) computed when calculating fib(5)?',
        ],
        solution: 'Each call spawns two more, and the same subproblems are recomputed across separate branches',
        solutionExplanation:
          'The calls form a binary tree rather than a chain, and the branches overlap: computing `fib(5)` calculates `fib(3)` twice and `fib(2)` three times, with the duplication compounding at every level. That is a flaw in the **algorithm**, not in recursion — memoising the same recursive function cuts `fib(25)` from 242,785 calls to 49. The stack does not overflow, since the depth is only `n`; the problem is the **breadth**. Large numbers are a separate concern that appears well beyond `fib(80)`.',
      },
      {
        id: 'ex-m38-03-d',
        title: 'Choose the approach',
        kind: EXERCISE_KIND.CHOOSE_IMPLEMENTATION,
        difficulty: DIFFICULTY.HARD,
        xp: 25,
        topicIds: ['recursion'],
        instructions:
          'You must walk a linked structure that may be 100,000 nodes deep. Recursion or iteration?',
        options: [
          'Recursion — it is cleaner for linked structures',
          'Iteration with an explicit stack — the recursive version would exceed the call stack',
          'Recursion with tail calls, which JavaScript optimises away',
          'Either works identically',
        ],
        correct: 1,
        hints: [
          'How many frames would 100,000 levels need?',
        ],
        solution: 'Iteration with an explicit stack — the recursive version would exceed the call stack',
        solutionExplanation:
          'A few thousand frames is safe; 100,000 is far beyond any engine\'s limit, so the recursive version throws `RangeError`. Converting to an explicit stack moves that bookkeeping into an **array in the heap**, where depth is limited by memory instead. Crucially, writing the recursion in tail position does **not** help: Module 33 established that JavaScript engines generally do not implement tail-call elimination despite it being specified, so each call still consumes a frame.',
      },
    ],
    quiz: {
      id: 'qz-m38-03',
      questions: [
        {
          id: 'q-m38-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['recursion'],
          prompt: 'What replaces the call stack when converting recursion to iteration?',
          options: [
            'A closure',
            'An explicit stack — usually an array of pending work',
            'A generator',
            'Nothing is needed',
          ],
          correct: 1,
          optionExplanations: [
            'Closures capture variables, not pending work.',
            'Correct — the array does the remembering.',
            'A generator suspends, but does not replace the stack.',
            'The bookkeeping must live somewhere.',
          ],
          explanation:
            'The call stack was only remembering which nodes remained. An array does the same job, and lives in the heap so depth is limited by memory rather than frames.',
        },
        {
          id: 'q-m38-03-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['recursion'],
          prompt: 'Why push children in reverse onto an explicit stack?',
          options: [
            'For performance',
            'A stack is last-in-first-out, so pushing forwards would visit the last child first',
            'To avoid duplicates',
            'It is not necessary',
          ],
          correct: 1,
          optionExplanations: [
            'Order, not speed.',
            'Correct — to match the recursive visit order.',
            'Duplicates are unrelated.',
            'It matters when order does.',
          ],
          explanation:
            'A stack pops the most recently pushed item, so pushing children in order would reverse the traversal. This only matters when the output order does.',
        },
        {
          id: 'q-m38-03-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['recursion'],
          prompt: 'Writing a recursive function in tail position avoids growing the stack in JavaScript.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Engines generally do not implement it.',
            'Correct — each call still consumes a frame.',
          ],
          explanation:
            'Tail-call elimination is specified but generally not implemented by JavaScript engines, so tail position gives no depth benefit. Use an explicit stack when depth may be large.',
        },
        {
          id: 'q-m38-03-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['recursion'],
          prompt: 'Which traversal is genuinely easier iteratively than recursively?',
          options: [
            'Depth-first',
            'Breadth-first — it needs a queue, which the call stack cannot provide',
            'Both are equally easy',
            'Neither can be done iteratively',
          ],
          correct: 1,
          optionExplanations: [
            'Depth-first falls out of recursion naturally.',
            'Correct — level-by-level needs FIFO.',
            'They differ.',
            'Both can.',
          ],
          explanation:
            'The call stack is a stack, so depth-first is the natural recursive shape. Breadth-first needs first-in-first-out ordering, which requires an explicit queue either way.',
        },
      ],
    },
    summary:
      'Recursion is **not the more advanced choice**. For **linear** problems iteration is usually plainer and cannot overflow; for **self-similar structures** recursion expresses the traversal directly. Any recursion converts to a loop with an **explicit stack**, because the call stack was only ever remembering pending work — moving that into an array puts it in the **heap**, so depth is limited by memory rather than frames. Push children **in reverse** to preserve visit order, since a stack is last-in-first-out. Swapping the stack for a **queue** gives breadth-first traversal, which has no simple recursive form precisely because the call stack is a stack — and use a **head index** rather than `shift()`. Naive recursive Fibonacci is **correct and exponential**: each call spawns two, branches overlap, and `fib(25)` costs 242,785 calls. That is a flaw in the **algorithm**, not in recursion — memoising the same recursive function reduces it to **49**, and iterating upward needs no cache or stack at all. Choose on real criteria: **depth** (a few thousand frames is safe, tens of thousands is not, and tail position does **not** help since engines generally do not implement tail-call elimination), the **shape of the data**, whether **subproblems overlap**, and whether you need breadth-first order.',
    keyTakeaways: [
      'Iteration suits linear problems; recursion suits self-similar structures',
      'Any recursion becomes a loop with an explicit stack in the heap',
      'Push children in reverse to preserve depth-first order',
      'Breadth-first needs a queue, so it is naturally iterative',
      'Naive Fibonacci is exponential from overlapping subproblems, not from recursion',
      'Tail position does not save a frame in JavaScript engines',
    ],
    relatedLessons: ['l-m38-02', 'l-m38-01'],
    interviewConnections: [
      'How would you convert a recursive tree traversal to an iterative one?',
      'Why is naive recursive Fibonacci slow, and how do you fix it?',
      'When would you choose iteration over recursion?',
      'Does tail-call optimisation help in JavaScript?',
    ],
  },
];
