import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm41';

export default [
  /* ================================================================== */
  {
    id: 'l-m41-01',
    slug: 'creational-patterns',
    moduleId: M,
    order: 1,
    title: 'Module, Factory and Singleton',
    description: 'Patterns for creating and encapsulating things — and the honest cost of shared state.',
    difficulty: DIFFICULTY.MEDIUM,
    estimatedMinutes: 17,
    xp: 45,
    topicIds: ['design-patterns', 'clean-code'],
    prerequisites: ['l-m40-03'],
    learningObjectives: [
      'Explain what a design pattern is and is not',
      'Implement the module and factory patterns',
      'Explain the real costs of a singleton',
      'Choose between a factory function and a class',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'What a pattern is',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'A design pattern is a **named solution to a recurring design problem**. The value is mostly in the name: "this is an observer" communicates a whole structure in two words, which is why patterns are worth knowing even when you would have arrived at the same code anyway.',
          'They are not JavaScript inventions, and not language features. Most were catalogued for statically-typed object-oriented languages in the 1990s, and several exist to work around limitations JavaScript does not have — first-class functions and closures make some patterns nearly invisible here.',
          'They are also not a quality mark. Code is not better for containing a factory, and a pattern applied to a problem that did not need one makes things worse.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'The module pattern',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The historical form — an IIFE returning a public surface.',
        code: [
          '"use strict";',
          '',
          '// Before ES modules, this was how you got privacy and avoided globals',
          'const counter = (function () {',
          '  // Private — nothing outside can reach these',
          '  let count = 0;',
          '  const history = [];',
          '',
          '  function record(action) { history.push(action); }',
          '',
          '  // Public — the deliberate surface',
          '  return {',
          '    increment() { count += 1; record("inc"); return count; },',
          '    reset() { count = 0; record("reset"); },',
          '    get value() { return count; },',
          '    get log() { return [...history]; },',
          '  };',
          '})();',
          '',
          'counter.increment();',
          'counter.increment();',
          '',
          'console.log("value  :", counter.value);',
          'console.log("log    :", counter.log);',
          'console.log("private:", counter.count, counter.history);',
          '',
          '// The returned log is a copy, so this cannot corrupt the internals',
          'counter.log.push("forged");',
          'console.log("after  :", counter.log.length);',
        ].join('\n'),
        output: [
          'value  : 2',
          'log    : ["inc", "inc"]',
          'private: undefined undefined',
          'after  : 2',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'ES modules replaced this — recognise it, do not reach for it',
        body: [
          'The IIFE existed to solve two problems Module 28 showed ES modules solving properly: **polluting the global scope**, and **having no privacy**. A module file already gives you both — top-level declarations are private unless exported, and nothing leaks to the global scope.',
          'So in new code, the file *is* the module. Wrapping a module\'s contents in an IIFE adds a layer that does nothing.',
          'It is worth recognising because a great deal of existing JavaScript is written this way, and because the underlying mechanism — a closure over private state — is exactly what the factory pattern uses.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Factory',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A function that returns a configured object.',
        code: [
          '"use strict";',
          '',
          'function createUser(name, role = "member") {',
          '  // Private state, per instance',
          '  let loginCount = 0;',
          '',
          '  return {',
          '    name,',
          '    role,',
          '',
          '    login() { loginCount += 1; return loginCount; },',
          '    get logins() { return loginCount; },',
          '    describe() { return `${name} (${role})`; },',
          '  };',
          '}',
          '',
          'const ada = createUser("Ada", "admin");',
          'const bo = createUser("Bo");',
          '',
          'ada.login();',
          'ada.login();',
          'bo.login();',
          '',
          'console.log("ada :", ada.describe(), ada.logins);',
          'console.log("bo  :", bo.describe(), bo.logins);',
          '',
          '// Independent state, no `new`, no `this` to lose',
          'const detached = ada.login;',
          'console.log("detached works:", detached());',
        ].join('\n'),
        output: [
          'ada : Ada (admin) 2',
          'bo  : Bo (member) 1',
          'detached works: 3',
        ].join('\n'),
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Factory function',
          code: [
            'function createUser(name) {',
            '  let logins = 0;',
            '',
            '  return {',
            '    name,',
            '    login() {',
            '      return ++logins;',
            '    },',
            '  };',
            '}',
            '',
            '// No new, no this.',
            '// One function set',
            '// per instance.',
          ].join('\n'),
        },
        right: {
          title: 'Class',
          code: [
            'class User {',
            '  #logins = 0;',
            '',
            '  constructor(name) {',
            '    this.name = name;',
            '  }',
            '',
            '  login() {',
            '    return ++this.#logins;',
            '  }',
            '}',
            '',
            '// Shared prototype',
            '// methods, extends,',
            '// instanceof.',
          ].join('\n'),
        },
        note: 'Both give genuine privacy — the closure by unreachability, the `#` field by parse-time enforcement (Modules 31 and 32). Factories suit small numbers of objects and anything passed around as a callback, since there is no `this` to lose. Classes suit many instances (methods shared on the prototype), inheritance, and types other code checks with `instanceof`. Neither is universally better.',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Where a factory genuinely earns its name — choosing what to build.',
        code: [
          '"use strict";',
          '',
          'function createEmailNotifier(address) {',
          '  return { send: (msg) => `email to ${address}: ${msg}` };',
          '}',
          '',
          'function createSmsNotifier(number) {',
          '  return { send: (msg) => `sms to ${number}: ${msg}` };',
          '}',
          '',
          '// The factory decides WHICH implementation the caller gets',
          'function createNotifier(preference) {',
          '  if (preference.channel === "sms") {',
          '    return createSmsNotifier(preference.number);',
          '  }',
          '',
          '  return createEmailNotifier(preference.address);',
          '}',
          '',
          '// Calling code never learns which kind it received (Module 31)',
          'function notifyAll(preferences, message) {',
          '  return preferences.map((p) => createNotifier(p).send(message));',
          '}',
          '',
          'console.log(notifyAll([',
          '  { channel: "email", address: "a@x.com" },',
          '  { channel: "sms", number: "555-0100" },',
          '], "deploy done"));',
        ].join('\n'),
        output: [
          '["email to a@x.com: deploy done", "sms to 555-0100: deploy done"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Two things both called "factory"',
        body: [
          'A **factory function** is simply any function returning an object — an everyday JavaScript idiom rather than a pattern with ceremony.',
          'The **factory pattern** proper is about **encapsulating the decision** of which implementation to create, as `createNotifier` does. That is what buys something: callers state what they want, not which class to instantiate, so adding a channel changes one function.',
          'The distinction matters because "use a factory" can mean either, and only the second is a design decision worth debating.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Singleton',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'One shared instance.',
        code: [
          '"use strict";',
          '',
          '// In a module, module-level state IS a singleton (Module 28)',
          'const config = (function () {',
          '  let settings = { theme: "light" };',
          '',
          '  return {',
          '    get(key) { return settings[key]; },',
          '    set(key, value) { settings = { ...settings, [key]: value }; },',
          '  };',
          '})();',
          '',
          '// Every importer would share this one object',
          'config.set("theme", "dark");',
          'console.log("theme:", config.get("theme"));',
          '',
          '// The lazy-instantiation form, when creation is expensive',
          'function createConnectionPool() {',
          '  let instance = null;',
          '  let created = 0;',
          '',
          '  return {',
          '    get() {',
          '      if (instance === null) {',
          '        created += 1;',
          '        instance = { id: created, query: (sql) => `ran: ${sql}` };',
          '      }',
          '',
          '      return instance;',
          '    },',
          '    get creations() { return created; },',
          '  };',
          '}',
          '',
          'const pool = createConnectionPool();',
          '',
          'const a = pool.get();',
          'const b = pool.get();',
          '',
          'console.log("same instance:", a === b);',
          'console.log("created once :", pool.creations);',
          'console.log("query        :", a.query("SELECT 1"));',
        ].join('\n'),
        output: [
          'theme: dark',
          'same instance: true',
          'created once : 1',
          'query        : ran: SELECT 1',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'The singleton is the most over-used pattern, for three reasons',
        body: [
          '**It is hidden global state.** A function that reaches for a singleton has a dependency nothing in its signature reveals. Its behaviour depends on what some unrelated code did earlier, which is action at a distance.',
          '**It makes testing hard.** State persists between tests because the module is evaluated once (Module 28), so tests leak into each other and must be run in a particular order — or need a `reset()` method that exists purely for tests.',
          '**It couples everything to one concrete thing.** Substituting a fake in one place is impossible when every consumer reaches for the same global instance.',
          'The alternative is almost always **passing the instance in** — Module 28\'s dependency inversion. Create it once at the entry point and hand it down; consumers then declare what they need and can be tested with a fake.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The same feature, with the dependency passed in.',
        code: [
          '"use strict";',
          '',
          '// HIDDEN: reaches for shared state — untestable in isolation',
          'const sharedConfig = { currency: "USD" };',
          '',
          'function formatPriceHidden(amount) {',
          '  return `${amount.toFixed(2)} ${sharedConfig.currency}`;',
          '}',
          '',
          '// EXPLICIT: the dependency is a parameter',
          'function formatPrice(amount, config) {',
          '  return `${amount.toFixed(2)} ${config.currency}`;',
          '}',
          '',
          'console.log("hidden  :", formatPriceHidden(9.5));',
          '',
          '// Testing the explicit version needs no setup and no reset',
          'console.log("usd     :", formatPrice(9.5, { currency: "USD" }));',
          'console.log("eur     :", formatPrice(9.5, { currency: "EUR" }));',
          '',
          '// And the hidden version changes behaviour when something else mutates it',
          'sharedConfig.currency = "GBP";',
          'console.log("mutated :", formatPriceHidden(9.5), "<- nothing at the call site changed");',
        ].join('\n'),
        output: [
          'hidden  : 9.50 USD',
          'usd     : 9.50 USD',
          'eur     : 9.50 EUR',
          'mutated : 9.50 GBP <- nothing at the call site changed',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'When a singleton is genuinely right',
        body: [
          'When the thing being shared **is** genuinely singular and stateless-ish: a configuration object loaded once at startup, a logger, a connection pool, a cache deliberately shared across the application.',
          'The distinction is whether sharing is the **point** or merely convenient. One database connection pool is a real resource constraint. One `UserService` because it was easier than passing it down is not.',
          'Note that in JavaScript you rarely need the classical singleton *implementation* — a module\'s top-level state already gives you one instance per URL (Module 28). The `getInstance()` ceremony from other languages is usually unnecessary here.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// counter.js',
          'let count = 0;',
          'export function increment() { return ++count; }',
          '',
          '// a.js  ->  imports and calls increment()',
          '// b.js  ->  imports and calls increment()',
          '// Both are imported by main.js',
        ].join('\n'),
        options: [
          'They share one count — module-level state is already a singleton',
          'Each file gets its own count',
          'The count resets on each import',
          'It throws, because count is not exported',
        ],
        correct: 0,
        explanation:
          'A module is **evaluated once per URL** and the result cached (Module 28), so `count` exists exactly once no matter how many files import it — the second call returns `2`, not `1`. This is worth recognising because it means you get singleton behaviour **whether or not you intended it**: any mutable top-level binding is shared application-wide, with all the testing and hidden-coupling costs that implies. It also means the classical `getInstance()` ceremony is usually unnecessary in JavaScript. When each consumer needs its own state, export a **factory** instead.',
      },
    ],
    exercises: [
      {
        id: 'ex-m41-01-a',
        title: 'Build a factory with private state',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['design-patterns'],
        instructions:
          'Write `createTimer()` returning `{ start, stop, laps }`. `start(label)` records a label, `stop()` clears the current label, and `laps` returns a **copy** of all labels started so far. The internal array must not be reachable.',
        starterCode: [
          'function createTimer() {',
          '  // Closure over private state; expose a deliberate surface.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'records a start', body: 'const t = createTimer(); t.start("a"); expect(t.laps).toEqual(["a"]);' },
          { name: 'records several', body: 'const t = createTimer(); t.start("a"); t.start("b"); expect(t.laps).toEqual(["a", "b"]);' },
          { name: 'starts empty', body: 'expect(createTimer().laps).toEqual([]);' },
          { name: 'returns a copy', body: 'const t = createTimer(); t.start("a"); t.laps.push("forged"); expect(t.laps).toEqual(["a"]);' },
          { name: 'each read returns a fresh copy', body: 'const t = createTimer(); t.start("a"); expect(t.laps === t.laps).toBe(false);' },
          { name: 'timers are independent', body: 'const a = createTimer(); const b = createTimer(); a.start("x"); expect(b.laps).toEqual([]);' },
          { name: 'stop does not remove laps', body: 'const t = createTimer(); t.start("a"); t.stop(); expect(t.laps).toEqual(["a"]);', hidden: true },
        ],
        hints: [
          'Keep `const labels = []` inside the factory.',
          'Expose `laps` as a getter returning `[...labels]`.',
          'Spreading on every read means callers never share the internal array.',
        ],
        solution: [
          'function createTimer() {',
          '  const labels = [];',
          '  let current = null;',
          '',
          '  return {',
          '    start(label) { current = label; labels.push(label); },',
          '    stop() { current = null; },',
          '    get laps() { return [...labels]; },',
          '    get running() { return current; },',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Returning `[...labels]` from the getter is what makes the fourth test pass — handing out the internal array would let any caller mutate the timer\'s state, undoing the encapsulation entirely (Module 32). The fifth test proves the copy is made on **every** read rather than once: two consecutive reads of `laps` are different array objects, so no caller can ever hold a reference to the internal one. Each call to `createTimer` creates a fresh closure, giving the independence the sixth test checks, and the hidden test confirms `stop` affects only the current label rather than the recorded history.',
      },
      {
        id: 'ex-m41-01-b',
        title: 'Encapsulate the choice',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['design-patterns'],
        instructions:
          'Write `createStorage(kind)` returning an object with `save(key, value)` and `load(key)`. For `"memory"` use an internal `Map`; for `"prefixed"` use a `Map` but prefix every key with `"app:"`. Any other kind throws a `TypeError`.',
        starterCode: [
          'function createStorage(kind) {',
          '  // The caller says what they want, not how it is built.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'memory saves and loads', body: 'const s = createStorage("memory"); s.save("k", 1); expect(s.load("k")).toBe(1);' },
          { name: 'prefixed saves and loads', body: 'const s = createStorage("prefixed"); s.save("k", 1); expect(s.load("k")).toBe(1);' },
          { name: 'prefixed keys differ from memory keys', body: 'const p = createStorage("prefixed"); const m = createStorage("memory"); p.save("k", 1); expect(m.load("k")).toBe(undefined);' },
          { name: 'missing key gives undefined', body: 'expect(createStorage("memory").load("nope")).toBe(undefined);' },
          { name: 'rejects an unknown kind', body: 'expect(() => createStorage("ftp")).toThrow();' },
          { name: 'instances are independent', body: 'const a = createStorage("memory"); const b = createStorage("memory"); a.save("k", 1); expect(b.load("k")).toBe(undefined);' },
          { name: 'both kinds share an interface', body: 'const kinds = ["memory", "prefixed"].map(createStorage); expect(kinds.every((s) => typeof s.save === "function" && typeof s.load === "function")).toBe(true);', hidden: true },
        ],
        hints: [
          'Write a small builder for each kind, then dispatch on `kind`.',
          'The prefixed version applies `"app:" + key` inside both methods.',
          'Throw before returning anything for an unknown kind.',
        ],
        solution: [
          'function createMemoryStorage(prefix = "") {',
          '  const store = new Map();',
          '',
          '  return {',
          '    save(key, value) { store.set(prefix + key, value); },',
          '    load(key) { return store.get(prefix + key); },',
          '  };',
          '}',
          '',
          'function createStorage(kind) {',
          '  if (kind === "memory") return createMemoryStorage();',
          '  if (kind === "prefixed") return createMemoryStorage("app:");',
          '',
          '  throw new TypeError(`unknown storage kind: ${kind}`);',
          '}',
        ].join('\n'),
        solutionExplanation:
          'This is the factory pattern proper: the caller says **what they want** and never learns which construction happened, so adding a third kind is a change in one function. The hidden test states the requirement that makes it work — both kinds share the same interface, which is what lets calling code treat them interchangeably (Module 31\'s polymorphism). Throwing for an unknown kind fails loudly rather than returning something half-formed, and each call builds a fresh `Map`, giving the independence the sixth test checks.',
      },
      {
        id: 'ex-m41-01-c',
        title: 'What is wrong with a singleton?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['design-patterns'],
        instructions:
          'What is the main drawback of reaching for a shared singleton instance inside a function?',
        options: [
          'It uses more memory',
          'It is a hidden dependency nothing in the signature reveals, so behaviour depends on unrelated code and tests leak into each other',
          'Singletons are deprecated',
          'It cannot hold state',
        ],
        correct: 1,
        hints: [
          'What does the function signature tell a caller about what it needs?',
        ],
        solution: 'It is a hidden dependency nothing in the signature reveals, so behaviour depends on unrelated code and tests leak into each other',
        solutionExplanation:
          'The function\'s result depends on state some other code set earlier, with nothing at the call site indicating it — action at a distance. Because a module is evaluated once (Module 28), that state also persists **between tests**, so tests become order-dependent or need a `reset()` that exists purely for testing. And every consumer is coupled to the one concrete instance, so substituting a fake anywhere is impossible. The fix is to **pass the instance in**: create it once at the entry point and hand it down.',
      },
      {
        id: 'ex-m41-01-d',
        title: 'Factory or class?',
        kind: EXERCISE_KIND.CHOOSE_IMPLEMENTATION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['design-patterns'],
        instructions:
          'You need a handful of objects whose methods will be passed directly to `addEventListener`. Factory function or class?',
        options: [
          'Class — it is the modern approach',
          'Factory — closures need no `this`, so the methods survive being detached',
          'Either; they are identical',
          'Class, with all methods as arrow fields',
        ],
        correct: 1,
        hints: [
          'What happens to a prototype method passed as a listener?',
        ],
        solution: 'Factory — closures need no `this`, so the methods survive being detached',
        solutionExplanation:
          'A factory\'s methods close over the state directly, so there is no receiver to lose when one is handed to `addEventListener` — the detached-method problem from Module 29 simply does not arise. With only a handful of objects, the per-instance function cost is irrelevant. The last option would work (arrow class fields are permanently bound) but adds class ceremony to reach the same place. A class would win if there were many instances, inheritance, or an `instanceof` check.',
      },
    ],
    quiz: {
      id: 'qz-m41-01',
      questions: [
        {
          id: 'q-m41-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['design-patterns'],
          prompt: 'What is a design pattern?',
          options: [
            'A JavaScript language feature',
            'A named solution to a recurring design problem — the name is much of the value',
            'A guarantee of good code',
            'A framework requirement',
          ],
          correct: 1,
          optionExplanations: [
            'They predate and outlive any language.',
            'Correct — shared vocabulary for a structure.',
            'A misapplied pattern makes code worse.',
            'Frameworks use them; they do not require them.',
          ],
          explanation:
            'Patterns give a shared vocabulary — "this is an observer" communicates a structure in two words. Several were catalogued for languages lacking first-class functions, so closures make some nearly invisible in JavaScript.',
        },
        {
          id: 'q-m41-01-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['design-patterns'],
          prompt: 'What replaced the IIFE module pattern in modern JavaScript?',
          options: [
            'Classes',
            'ES modules — a file is already private and does not pollute the global scope',
            'Nothing; it is still standard',
            'Proxies',
          ],
          correct: 1,
          optionExplanations: [
            'Classes solve a different problem.',
            'Correct — the file is the module.',
            'It is legacy in new code.',
            'Unrelated.',
          ],
          explanation:
            'The IIFE existed to avoid globals and gain privacy, both of which a module file provides. Recognise it in existing code; do not add it to new code.',
        },
        {
          id: 'q-m41-01-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['design-patterns'],
          prompt: 'In JavaScript you need a getInstance() method to create a singleton.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Module state already provides one.',
            'Correct — a module is evaluated once.',
          ],
          explanation:
            'Module-level state is already one instance per URL (Module 28), so the classical ceremony is usually unnecessary. The lazy form is worth it only when creation is expensive and may not be needed.',
        },
        {
          id: 'q-m41-01-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['design-patterns'],
          prompt: 'What distinguishes the factory pattern from any function returning an object?',
          options: [
            'Nothing',
            'The factory pattern encapsulates the decision of which implementation to create',
            'It must use `new`',
            'It must return a class instance',
          ],
          correct: 1,
          optionExplanations: [
            'The names are used for both, but only one is a design decision.',
            'Correct — callers state what they want, not what to build.',
            '`new` is not involved.',
            'Plain objects are fine.',
          ],
          explanation:
            'A factory function is an everyday idiom. The pattern is about hiding the choice of implementation, so adding a variant changes one function rather than every call site.',
        },
      ],
    },
    summary:
      'A design pattern is a **named solution to a recurring design problem**, and much of the value is the **name** — "this is an observer" conveys a structure in two words. Patterns are not JavaScript inventions, not language features, and not a quality mark; several were catalogued for languages without first-class functions, so closures make some nearly invisible here. The **module pattern** (an IIFE returning a public surface) existed to avoid globals and gain privacy — both of which **ES modules now provide**, so recognise it in existing code rather than writing it. A **factory function** is any function returning an object, and it gives per-instance private state via closure with **no `this` to lose**, which is why it suits objects whose methods get passed to `addEventListener`. The **factory pattern** proper is narrower: it **encapsulates which implementation to create**, so callers state what they want and adding a variant changes one function. Choose factory versus class on real criteria — factories for few instances and detachment safety, classes for many instances (shared prototype methods), inheritance and `instanceof`. The **singleton** is the most over-used pattern, for three concrete reasons: it is **hidden global state** invisible in a signature, it **leaks between tests** because a module evaluates once, and it **couples every consumer** to one concrete instance. In JavaScript module-level state is *already* a singleton, whether you intended it or not. Prefer **passing the instance in**, and reserve genuine singletons for things that are genuinely singular.',
    keyTakeaways: [
      'A pattern is a named solution — the vocabulary is most of the value',
      'ES modules replaced the IIFE module pattern; recognise it, do not write it',
      'A factory function gives private per-instance state with no this to lose',
      'The factory pattern hides which implementation is created',
      'Module-level state is already a singleton, intended or not',
      'Singletons hide dependencies and leak between tests — pass instances in',
    ],
    relatedLessons: ['l-m41-02', 'l-m41-03'],
    interviewConnections: [
      'What is the module pattern, and is it still relevant?',
      'When would you use a factory function instead of a class?',
      'What are the drawbacks of the singleton pattern?',
      'How do you create a singleton in JavaScript?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m41-02',
    slug: 'behavioural-patterns',
    moduleId: M,
    order: 2,
    title: 'Observer, Strategy and Command',
    description: 'Patterns for behaviour that varies — decoupling notification, choice and action.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 18,
    xp: 50,
    topicIds: ['design-patterns'],
    prerequisites: ['l-m41-01'],
    learningObjectives: [
      'Implement observer and explain unsubscription',
      'Distinguish observer from publish/subscribe',
      'Replace conditional chains with strategy',
      'Implement command with undo',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Observer',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A subject notifying its observers.',
        code: [
          '"use strict";',
          '',
          'function createSubject(initialValue) {',
          '  let value = initialValue;',
          '  const observers = [];',
          '',
          '  return {',
          '    subscribe(observer) {',
          '      const entry = { observer };',
          '      observers.push(entry);',
          '',
          '      // Returning an unsubscribe function is essential (Module 32)',
          '      return () => {',
          '        const index = observers.indexOf(entry);',
          '        if (index !== -1) observers.splice(index, 1);',
          '      };',
          '    },',
          '',
          '    set(next) {',
          '      value = next;',
          '      for (const { observer } of [...observers]) observer(next);',
          '    },',
          '',
          '    get value() { return value; },',
          '    get observerCount() { return observers.length; },',
          '  };',
          '}',
          '',
          'const temperature = createSubject(20);',
          'const seen = [];',
          '',
          'const stopDisplay = temperature.subscribe((v) => seen.push(`display: ${v}`));',
          'temperature.subscribe((v) => seen.push(`log: ${v}`));',
          '',
          'temperature.set(25);',
          'stopDisplay();',
          'temperature.set(30);',
          '',
          'seen.forEach((line) => console.log(line));',
          'console.log("remaining:", temperature.observerCount);',
        ].join('\n'),
        output: [
          'display: 25',
          'log: 25',
          'log: 30',
          'remaining: 1',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Two details that make this correct',
        body: [
          '**`subscribe` returns an unsubscribe function.** Without it, observers accumulate and keep whatever they captured alive — Module 32\'s dominant real-world leak. Every subscription API worth using returns a remover.',
          '**`set` iterates a copy** (`[...observers]`). If an observer unsubscribes itself during notification, mutating the array mid-iteration would skip the next observer. Copying first makes the notification list stable for that round.',
          'Note each subscription gets its own `entry` object, so subscribing the **same function twice** creates two independent subscriptions that can be removed separately.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Observer versus publish/subscribe.',
        code: [
          '"use strict";',
          '',
          '// OBSERVER: observers register directly with the subject.',
          '// The subject knows who is listening.',
          'const subject = (function () {',
          '  const observers = [];',
          '  return {',
          '    subscribe(fn) { observers.push(fn); },',
          '    notify(data) { observers.forEach((fn) => fn(data)); },',
          '  };',
          '})();',
          '',
          '// PUB/SUB: a broker sits in between, keyed by topic.',
          '// Publisher and subscriber never reference each other.',
          'function createEventBus() {',
          '  const topics = new Map();',
          '',
          '  return {',
          '    on(topic, handler) {',
          '      if (!topics.has(topic)) topics.set(topic, []);',
          '      topics.get(topic).push(handler);',
          '',
          '      return () => {',
          '        const list = topics.get(topic);',
          '        const index = list.indexOf(handler);',
          '        if (index !== -1) list.splice(index, 1);',
          '      };',
          '    },',
          '',
          '    emit(topic, data) {',
          '      for (const handler of [...(topics.get(topic) ?? [])]) handler(data);',
          '    },',
          '  };',
          '}',
          '',
          'const bus = createEventBus();',
          'const log = [];',
          '',
          'bus.on("order:placed", (o) => log.push(`email for ${o.id}`));',
          'bus.on("order:placed", (o) => log.push(`analytics for ${o.id}`));',
          'bus.on("order:cancelled", (o) => log.push(`refund ${o.id}`));',
          '',
          'bus.emit("order:placed", { id: 7 });',
          'bus.emit("order:cancelled", { id: 8 });',
          'bus.emit("nobody:listening", {});',
          '',
          'log.forEach((line) => console.log(line));',
        ].join('\n'),
        output: [
          'email for 7',
          'analytics for 7',
          'refund 8',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'The distinction, and an honest caveat',
        body: [
          'In **observer**, observers hold a reference to the subject and register with it directly — the subject knows its observers. In **publish/subscribe**, a **broker** sits between them, keyed by topic, so a publisher never learns who (if anyone) is listening.',
          'Pub/sub is therefore more decoupled, which is both its advantage and its cost: emitting into a bus makes it genuinely hard to discover what happens next, and a typo in a topic string fails **silently** — as the `"nobody:listening"` line shows.',
          'The honest caveat: **these terms are not used consistently across libraries.** Many "event emitters" are called observers, and many observer implementations use topics. Understand the two shapes; do not argue about the labels.',
          'Note the browser already gives you both: `addEventListener` is observer-shaped, and `CustomEvent` dispatched on a shared target is pub/sub-shaped.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Strategy',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Replacing a conditional chain with interchangeable behaviour.',
        code: [
          '"use strict";',
          '',
          '// BEFORE: every new rule edits this function',
          'function priceBefore(order, kind) {',
          '  if (kind === "none") return order.total;',
          '  if (kind === "percentage") return order.total * 0.9;',
          '  if (kind === "fixed") return Math.max(0, order.total - 10);',
          '  if (kind === "bulk") return order.items >= 10 ? order.total * 0.8 : order.total;',
          '',
          '  throw new Error(`unknown discount: ${kind}`);',
          '}',
          '',
          '// AFTER: each rule is a separate function; adding one changes nothing else',
          'const discounts = {',
          '  none: (order) => order.total,',
          '  percentage: (order) => order.total * 0.9,',
          '  fixed: (order) => Math.max(0, order.total - 10),',
          '  bulk: (order) => (order.items >= 10 ? order.total * 0.8 : order.total),',
          '};',
          '',
          'function price(order, kind) {',
          '  const strategy = discounts[kind];',
          '',
          '  if (!strategy) throw new Error(`unknown discount: ${kind}`);',
          '',
          '  return strategy(order);',
          '}',
          '',
          'const order = { total: 100, items: 12 };',
          '',
          'for (const kind of ["none", "percentage", "fixed", "bulk"]) {',
          '  console.log(`${kind.padEnd(11)}: ${price(order, kind)} (before: ${priceBefore(order, kind)})`);',
          '}',
          '',
          '// A new strategy can be added without touching `price`',
          'discounts.loyalty = (o) => o.total * 0.75;',
          'console.log("loyalty    :", price(order, "loyalty"));',
        ].join('\n'),
        output: [
          'none       : 100 (before: 100)',
          'percentage : 90 (before: 90)',
          'fixed      : 90 (before: 90)',
          'bulk       : 80 (before: 80)',
          'loyalty    : 75',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.WARNING,
        title: 'Strategy is not "always replace `if` with an object"',
        body: [
          'The pattern pays off when the branches are **genuinely interchangeable** — same inputs, same output shape, differing only in the rule — and when the set is expected to grow or vary at runtime.',
          'It is the wrong move for two or three stable branches, or for branches that take different arguments and return different shapes. A short `if`/`else` shows all the cases together, which is genuinely easier to audit.',
          'Note the trade-off in the example: the lookup version scatters the four rules where the chain listed them in one visible place. That is a real loss, paid for by the ability to add a fifth without editing `price`.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Command',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'An action as an object, with undo.',
        code: [
          '"use strict";',
          '',
          'function createEditor() {',
          '  let text = "";',
          '  const history = [];',
          '  const undone = [];',
          '',
          '  function run(command) {',
          '    text = command.execute(text);',
          '    history.push(command);',
          '    undone.length = 0;          // a new action clears the redo stack',
          '    return text;',
          '  }',
          '',
          '  return {',
          '    run,',
          '',
          '    undo() {',
          '      const command = history.pop();',
          '      if (!command) return text;',
          '',
          '      text = command.undo(text);',
          '      undone.push(command);',
          '      return text;',
          '    },',
          '',
          '    redo() {',
          '      const command = undone.pop();',
          '      if (!command) return text;',
          '',
          '      text = command.execute(text);',
          '      history.push(command);',
          '      return text;',
          '    },',
          '',
          '    get value() { return text; },',
          '    get depth() { return history.length; },',
          '  };',
          '}',
          '',
          '// Each command knows how to do AND undo itself',
          'const append = (suffix) => ({',
          '  execute: (t) => t + suffix,',
          '  undo: (t) => t.slice(0, t.length - suffix.length),',
          '});',
          '',
          'const upper = () => ({',
          '  execute: (t) => t.toUpperCase(),',
          '  undo: (t) => t.toLowerCase(),',
          '});',
          '',
          'const editor = createEditor();',
          '',
          'console.log("append  :", editor.run(append("hello")));',
          'console.log("append  :", editor.run(append(" world")));',
          'console.log("upper   :", editor.run(upper()));',
          '',
          'console.log("undo    :", editor.undo());',
          'console.log("undo    :", editor.undo());',
          'console.log("redo    :", editor.redo());',
          'console.log("depth   :", editor.depth);',
          '',
          '// Undo on an empty history is safe',
          'const fresh = createEditor();',
          'console.log("empty   :", JSON.stringify(fresh.undo()));',
        ].join('\n'),
        output: [
          'append  : hello',
          'append  : hello world',
          'upper   : HELLO WORLD',
          'undo    : hello world',
          'undo    : hello',
          'redo    : hello world',
          'depth   : 2',
          'empty   : ""',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Undo is only as correct as the inverse you wrote',
        body: [
          '`upper()` has a **lossy** undo: lowercasing does not restore the original casing, so undoing `"Hello World"` gives `"hello world"` rather than the text you started with. The pattern gave you the *structure* for undo; it did not make the inverse correct.',
          'The robust alternative is to have each command **capture the previous state** rather than compute an inverse — `undo: () => previousText`, stored when the command executed. It uses more memory and is correct by construction.',
          'Note `undone.length = 0` on a new action. That is the standard behaviour of every editor: doing something new discards the redo stack, because the future you would have redone into no longer exists.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          'const observers = [];',
          '',
          'function subscribe(fn) { observers.push(fn); }',
          '',
          'function notify(data) {',
          '  for (const fn of observers) fn(data);',
          '}',
          '',
          '// One observer removes itself when it fires',
          'subscribe(function first(d) { observers.splice(0, 1); });',
          'subscribe(function second(d) { console.log("second ran"); });',
          '',
          'notify("x");',
        ].join('\n'),
        options: [
          '"second ran" never prints — removing an element mid-iteration shifts the array and skips it',
          '"second ran" prints normally',
          'It throws',
          '"second ran" prints twice',
        ],
        correct: 0,
        explanation:
          'Iterating an array while mutating it is the bug. `first` runs at index 0 and splices itself out, which shifts `second` **down** into index 0 — but the loop has already passed that position and moves on to index 1, which is now past the end. `second` is silently skipped. This is exactly why a correct `notify` iterates a **copy**: `for (const fn of [...observers])` fixes it, because the notification list for this round is fixed before any observer can modify it. The failure is silent, intermittent, and depends on which observer unsubscribes — which makes it genuinely hard to diagnose in production.',
      },
    ],
    exercises: [
      {
        id: 'ex-m41-02-a',
        title: 'Build an observable',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['design-patterns'],
        instructions:
          'Write `createObservable(initial)` returning `{ subscribe, set, value }`. `subscribe(fn)` returns an unsubscribe function, and `set` notifies all current subscribers. It must survive a subscriber unsubscribing during notification.',
        starterCode: [
          'function createObservable(initial) {',
          '  // Iterate a copy when notifying.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'notifies a subscriber', body: 'const o = createObservable(0); const seen = []; o.subscribe((v) => seen.push(v)); o.set(1); expect(seen).toEqual([1]);' },
          { name: 'notifies several', body: 'const o = createObservable(0); const seen = []; o.subscribe((v) => seen.push(`a${v}`)); o.subscribe((v) => seen.push(`b${v}`)); o.set(1); expect(seen).toEqual(["a1", "b1"]);' },
          { name: 'exposes the current value', body: 'const o = createObservable(5); expect(o.value).toBe(5); o.set(9); expect(o.value).toBe(9);' },
          { name: 'unsubscribe stops notifications', body: 'const o = createObservable(0); const seen = []; const off = o.subscribe((v) => seen.push(v)); off(); o.set(1); expect(seen).toEqual([]);' },
          { name: 'unsubscribing one leaves the others', body: 'const o = createObservable(0); const seen = []; const off = o.subscribe(() => seen.push("a")); o.subscribe(() => seen.push("b")); off(); o.set(1); expect(seen).toEqual(["b"]);' },
          { name: 'survives self-removal during notification', body: 'const o = createObservable(0); const seen = []; const off = o.subscribe(() => { seen.push("first"); off(); }); o.subscribe(() => seen.push("second")); o.set(1); expect(seen).toEqual(["first", "second"]);' },
          { name: 'the same function can subscribe twice', body: 'const o = createObservable(0); let n = 0; const fn = () => { n += 1; }; o.subscribe(fn); o.subscribe(fn); o.set(1); expect(n).toBe(2);', hidden: true },
        ],
        hints: [
          'Give each subscription its own entry object so duplicates are distinguishable.',
          'Return a closure that removes that specific entry.',
          'In `set`, spread the list before iterating it.',
        ],
        solution: [
          'function createObservable(initial) {',
          '  let value = initial;',
          '  const subscriptions = [];',
          '',
          '  return {',
          '    subscribe(fn) {',
          '      const entry = { fn };',
          '      subscriptions.push(entry);',
          '',
          '      return () => {',
          '        const index = subscriptions.indexOf(entry);',
          '        if (index !== -1) subscriptions.splice(index, 1);',
          '      };',
          '    },',
          '',
          '    set(next) {',
          '      value = next;',
          '',
          '      for (const { fn } of [...subscriptions]) fn(next);',
          '    },',
          '',
          '    get value() { return value; },',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Spreading in `set` is what makes the sixth test pass: the first subscriber removes itself mid-notification, and iterating the live array would shift the second down into the index the loop has already passed, silently skipping it. Copying fixes the notification list before any handler can change it. Wrapping each subscription in its own `entry` object gives it a **unique identity**, so the hidden test can subscribe the same function twice and get two independent notifications — searching for the function itself would have removed the wrong one.',
      },
      {
        id: 'ex-m41-02-b',
        title: 'Replace a conditional chain with strategy',
        kind: EXERCISE_KIND.REFACTOR,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['design-patterns'],
        instructions:
          'Write `applyDiscount(order, kind)` using a strategy lookup rather than an `if` chain. Support `"none"` (full price), `"half"` (50% off) and `"tenOff"` (10 off, never below 0). An unknown kind throws.',
        starterCode: [
          'function applyDiscount(order, kind) {',
          '  // Each rule is its own function in a lookup.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'applies no discount', body: 'expect(applyDiscount({ total: 100 }, "none")).toBe(100);' },
          { name: 'applies half off', body: 'expect(applyDiscount({ total: 100 }, "half")).toBe(50);' },
          { name: 'applies a fixed discount', body: 'expect(applyDiscount({ total: 100 }, "tenOff")).toBe(90);' },
          { name: 'never goes below zero', body: 'expect(applyDiscount({ total: 5 }, "tenOff")).toBe(0);' },
          { name: 'throws on an unknown kind', body: 'expect(() => applyDiscount({ total: 100 }, "mystery")).toThrow();' },
          { name: 'handles a zero total', body: 'expect(applyDiscount({ total: 0 }, "half")).toBe(0);' },
          { name: 'does not mutate the order', body: 'const o = { total: 100 }; applyDiscount(o, "half"); expect(o.total).toBe(100);', hidden: true },
        ],
        hints: [
          'Define the strategies as an object of functions.',
          'Look up by `kind` and throw if the entry is missing.',
          '`Math.max(0, ...)` enforces the floor.',
        ],
        solution: [
          'const discountStrategies = {',
          '  none: (order) => order.total,',
          '  half: (order) => order.total * 0.5,',
          '  tenOff: (order) => Math.max(0, order.total - 10),',
          '};',
          '',
          'function applyDiscount(order, kind) {',
          '  const strategy = discountStrategies[kind];',
          '',
          '  if (!strategy) throw new Error(`unknown discount: ${kind}`);',
          '',
          '  return strategy(order);',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Each rule is now an independent function with the same shape — order in, number out — which is what makes them interchangeable, and adding a fourth requires no change to `applyDiscount`. Checking for a missing strategy **before** calling is what turns an unknown kind into a clear error rather than "strategy is not a function". Every strategy computes a new value rather than assigning to `order.total`, so the input is untouched (hidden test). Note the trade-off from the lesson: this scatters the rules where a short `if` chain would show all three together.',
      },
      {
        id: 'ex-m41-02-c',
        title: 'Command with reliable undo',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['design-patterns'],
        instructions:
          'Write `createHistory(initial)` returning `{ apply, undo, value }`. `apply(fn)` sets the value to `fn(current)` and records enough to undo it **exactly**, even for lossy transformations like `toUpperCase`. `undo` on an empty history returns the current value unchanged.',
        starterCode: [
          'function createHistory(initial) {',
          '  // Capture the previous state rather than computing an inverse.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'applies a transformation', body: 'const h = createHistory("a"); h.apply((v) => v + "b"); expect(h.value).toBe("ab");' },
          { name: 'undoes it', body: 'const h = createHistory("a"); h.apply((v) => v + "b"); h.undo(); expect(h.value).toBe("a");' },
          { name: 'undoes a lossy transformation exactly', body: 'const h = createHistory("Hello World"); h.apply((v) => v.toUpperCase()); h.undo(); expect(h.value).toBe("Hello World");' },
          { name: 'undoes several steps', body: 'const h = createHistory(""); h.apply((v) => v + "a"); h.apply((v) => v + "b"); h.undo(); h.undo(); expect(h.value).toBe("");' },
          { name: 'undo on empty history is safe', body: 'const h = createHistory("x"); h.undo(); expect(h.value).toBe("x");' },
          { name: 'apply returns the new value', body: 'const h = createHistory(1); expect(h.apply((v) => v + 1)).toBe(2);' },
          { name: 'works with non-strings', body: 'const h = createHistory(10); h.apply((v) => v * 3); h.undo(); expect(h.value).toBe(10);', hidden: true },
        ],
        hints: [
          'Push the value *before* the change onto a stack.',
          '`undo` pops that previous value and restores it.',
          'No inverse function is needed at all.',
        ],
        solution: [
          'function createHistory(initial) {',
          '  let current = initial;',
          '  const previous = [];',
          '',
          '  return {',
          '    apply(fn) {',
          '      previous.push(current);',
          '      current = fn(current);',
          '',
          '      return current;',
          '    },',
          '',
          '    undo() {',
          '      if (previous.length === 0) return current;',
          '',
          '      current = previous.pop();',
          '      return current;',
          '    },',
          '',
          '    get value() { return current; },',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Capturing the **previous state** rather than computing an inverse is what makes the third test pass: no inverse of `toUpperCase` can restore `"Hello World"` from `"HELLO WORLD"`, because the original casing is genuinely gone. Storing the value before the change is correct by construction for **any** transformation, which is also why the hidden test works with numbers — nothing here assumes strings. The trade-off is memory: every step keeps a full copy, which matters for large values but is almost always the right choice for correctness.',
      },
      {
        id: 'ex-m41-02-d',
        title: 'Observer or pub/sub?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['design-patterns'],
        instructions:
          'What distinguishes publish/subscribe from the observer pattern?',
        options: [
          'Pub/sub is asynchronous, observer is synchronous',
          'Pub/sub puts a broker between publisher and subscriber, keyed by topic, so neither references the other',
          'Observer supports multiple listeners; pub/sub supports one',
          'They are identical',
        ],
        correct: 1,
        hints: [
          'Does the publisher know who is listening?',
        ],
        solution: 'Pub/sub puts a broker between publisher and subscriber, keyed by topic, so neither references the other',
        solutionExplanation:
          'In observer, observers register **directly** with the subject, so the subject knows its observers. Pub/sub routes through a broker keyed by topic, so a publisher never learns who is listening — more decoupled, at the cost that tracing what happens after an emit becomes genuinely hard and a mistyped topic fails **silently**. Neither is inherently asynchronous, and both support many listeners. Be aware the terms are used inconsistently across libraries: understand the two shapes rather than arguing about labels.',
      },
    ],
    quiz: {
      id: 'qz-m41-02',
      questions: [
        {
          id: 'q-m41-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['design-patterns'],
          prompt: 'Why should notification iterate a copy of the observer list?',
          options: [
            'For performance',
            'An observer unsubscribing during notification would shift the array and cause the next one to be skipped',
            'To avoid duplicates',
            'It is not necessary',
          ],
          correct: 1,
          optionExplanations: [
            'Copying costs slightly more.',
            'Correct — a silent, intermittent bug.',
            'Duplicates are unaffected.',
            'It is a real correctness issue.',
          ],
          explanation:
            'Splicing during iteration shifts later elements past the loop position, silently skipping them. Copying fixes the notification list before any handler can change it.',
        },
        {
          id: 'q-m41-02-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['design-patterns'],
          prompt: 'When is the strategy pattern the wrong choice?',
          options: [
            'When there are many rules that change often',
            'For two or three stable branches, or branches with different signatures — a short if chain shows all cases together',
            'When rules must be added at runtime',
            'When the rules are pure functions',
          ],
          correct: 1,
          optionExplanations: [
            'That is the ideal case.',
            'Correct — the lookup scatters what a chain shows in one place.',
            'That favours strategy.',
            'Purity helps.',
          ],
          explanation:
            'Strategy pays off when branches are genuinely interchangeable and the set grows. For a few stable branches the indirection costs visibility for nothing.',
        },
        {
          id: 'q-m41-02-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['design-patterns'],
          prompt: 'Implementing the command pattern guarantees undo works correctly.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It provides structure, not correctness.',
            'Correct — a lossy inverse still loses information.',
          ],
          explanation:
            'The pattern gives you the structure for undo. `toUpperCase` cannot be inverted by `toLowerCase`, so capture the previous state instead of computing an inverse.',
        },
        {
          id: 'q-m41-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['design-patterns'],
          prompt: 'Which browser API is observer-shaped?',
          options: ['fetch', 'addEventListener', 'JSON.parse', 'localStorage'],
          correct: 1,
          optionExplanations: [
            'A one-shot request.',
            'Correct — register a handler with a subject, get removal.',
            'A pure transformation.',
            'Key-value storage.',
          ],
          explanation:
            '`addEventListener` registers a handler directly with a target and pairs with `removeEventListener` — observer, built in. `CustomEvent` on a shared target is pub/sub-shaped.',
        },
      ],
    },
    summary:
      '**Observer** lets a subject notify registered observers. Two details make an implementation correct: `subscribe` must **return an unsubscribe function** (or observers accumulate and retain what they captured — Module 32\'s dominant leak), and `notify` must **iterate a copy**, because an observer unsubscribing mid-notification would shift the array and silently skip the next one. Giving each subscription its own entry object lets the same function subscribe twice independently. **Publish/subscribe** adds a **broker keyed by topic** so publisher and subscriber never reference each other — more decoupled, at the cost that tracing what happens after an emit is hard and a mistyped topic fails **silently**. The terms are used inconsistently across libraries; learn the shapes, not the labels. The browser provides both: `addEventListener` is observer-shaped, `CustomEvent` on a shared target is pub/sub-shaped. **Strategy** replaces a conditional chain with interchangeable functions, so adding a rule changes nothing else — but it is wrong for two or three stable branches, since the lookup **scatters** what a chain shows in one place. **Command** turns an action into an object with `execute` and `undo`, enabling history and redo (and a new action clears the redo stack). Crucially, the pattern supplies **structure, not correctness**: a lossy inverse like `toLowerCase` cannot restore original casing, so **capture the previous state** rather than computing an inverse.',
    keyTakeaways: [
      'subscribe must return an unsubscribe function',
      'Notify by iterating a copy, or self-removal silently skips an observer',
      'Pub/sub adds a topic broker — more decoupled, harder to trace, fails silently',
      'Strategy suits growing sets of interchangeable rules, not a few stable branches',
      'Command gives undo structure, not a correct inverse',
      'Capture previous state rather than computing an inverse',
    ],
    relatedLessons: ['l-m41-01', 'l-m41-03'],
    interviewConnections: [
      'Implement the observer pattern with unsubscription.',
      'What is the difference between observer and pub/sub?',
      'How would you replace a long if/else chain?',
      'How would you implement undo?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m41-03',
    slug: 'structural-patterns-and-misuse',
    moduleId: M,
    order: 3,
    title: 'Adapter, Facade, MVC and Pattern Misuse',
    description: 'Patterns that reshape interfaces, how to separate an application — and when a pattern is ceremony.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 18,
    xp: 45,
    topicIds: ['design-patterns', 'clean-code'],
    prerequisites: ['l-m41-02'],
    learningObjectives: [
      'Use an adapter to reconcile incompatible interfaces',
      'Use a facade to simplify a multi-step operation',
      'Explain the MVC separation conceptually',
      'Recognise when a pattern adds ceremony rather than value',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'Adapter',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Translating one interface into another.',
        code: [
          '"use strict";',
          '',
          '// Two services returning the same information in different shapes',
          'const legacyApi = {',
          '  fetchUser: () => ({ user_name: "Ada", email_address: "a@x.com", is_active: 1 }),',
          '};',
          '',
          'const modernApi = {',
          '  getUser: () => ({ name: "Bo", contact: { email: "b@x.com" }, status: "active" }),',
          '};',
          '',
          '// Our application works with ONE shape',
          'function legacyAdapter(api) {',
          '  return {',
          '    getUser() {',
          '      const raw = api.fetchUser();',
          '',
          '      return {',
          '        name: raw.user_name,',
          '        email: raw.email_address,',
          '        isActive: raw.is_active === 1,',
          '      };',
          '    },',
          '  };',
          '}',
          '',
          'function modernAdapter(api) {',
          '  return {',
          '    getUser() {',
          '      const raw = api.getUser();',
          '',
          '      return {',
          '        name: raw.name,',
          '        email: raw.contact.email,',
          '        isActive: raw.status === "active",',
          '      };',
          '    },',
          '  };',
          '}',
          '',
          '// Everything downstream is written once, against the internal shape',
          'function describe(source) {',
          '  const user = source.getUser();',
          '  return `${user.name} <${user.email}> ${user.isActive ? "active" : "inactive"}`;',
          '}',
          '',
          'console.log("legacy:", describe(legacyAdapter(legacyApi)));',
          'console.log("modern:", describe(modernAdapter(modernApi)));',
        ].join('\n'),
        output: [
          'legacy: Ada <a@x.com> active',
          'modern: Bo <b@x.com> active',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The adapter is where external shapes stop',
        body: [
          'Without adapters, `raw.is_active === 1` and `raw.status === "active"` would be scattered through the application, and every consumer would need to know which service it was talking to.',
          'With them, the translation happens **once at the boundary** and everything inward works with one internal shape. Swapping services becomes a change in one file.',
          'This is a genuinely valuable habit even without the pattern name: **do not let an external API\'s shape leak into your domain.** Third-party responses change, and an adapter is where that change is absorbed.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Facade',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'One simple entry point over several operations.',
        code: [
          '"use strict";',
          '',
          '// Several subsystems, each reasonable on its own',
          'function createValidator() {',
          '  return { check: (o) => (o.items.length > 0 ? null : "empty order") };',
          '}',
          '',
          'function createPricing(taxRate) {',
          '  return {',
          '    subtotal: (items) => items.reduce((s, i) => s + i.price, 0),',
          '    withTax: (amount) => amount * (1 + taxRate),',
          '  };',
          '}',
          '',
          'function createAuditLog() {',
          '  const entries = [];',
          '  return { record: (line) => entries.push(line), get entries() { return [...entries]; } };',
          '}',
          '',
          '// FACADE: callers get one method instead of orchestrating three subsystems',
          'function createCheckout({ validator, pricing, audit }) {',
          '  return {',
          '    place(order) {',
          '      const problem = validator.check(order);',
          '',
          '      if (problem) {',
          '        audit.record(`rejected: ${problem}`);',
          '        return { ok: false, reason: problem };',
          '      }',
          '',
          '      const total = pricing.withTax(pricing.subtotal(order.items));',
          '      audit.record(`placed: ${total}`);',
          '',
          '      return { ok: true, total };',
          '    },',
          '  };',
          '}',
          '',
          'const audit = createAuditLog();',
          '',
          'const checkout = createCheckout({',
          '  validator: createValidator(),',
          '  pricing: createPricing(0.2),',
          '  audit,',
          '});',
          '',
          'console.log("valid  :", checkout.place({ items: [{ price: 100 }] }));',
          'console.log("invalid:", checkout.place({ items: [] }));',
          'console.log("audit  :", audit.entries);',
        ].join('\n'),
        output: [
          'valid  : {ok: true, total: 120}',
          'invalid: {ok: false, reason: "empty order"}',
          'audit  : ["placed: 120", "rejected: empty order"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'Not every wrapper is a facade',
        body: [
          'A facade **simplifies a genuinely complex interaction** — several subsystems, a required order of operations, error handling that callers should not have to repeat. `checkout.place(order)` replaces four coordinated calls.',
          'A function that forwards one call to one other function is just a wrapper. Naming it a facade does not make it one, and adding a layer that does nothing costs a hop for every reader.',
          'The test: **does the caller\'s job get meaningfully simpler?** If a caller would otherwise have to know the order of operations or handle intermediate failures, yes. If they would just call the one thing underneath, no.',
          'Note the collaborators are passed **in** rather than constructed inside — so the facade simplifies without hiding what it depends on, and stays testable with fakes (Module 28).',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'MVC as a separation',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        needsDom: true,
        html: '<div id="app"><ul id="list"></ul><p id="count"></p></div>',
        caption: 'Model, view and controller in plain JavaScript.',
        code: [
          '// MODEL: data and rules. Knows nothing about the DOM.',
          'function createTaskModel() {',
          '  const tasks = [];',
          '  const listeners = [];',
          '',
          '  function emit() {',
          '    for (const fn of [...listeners]) fn(model.state);',
          '  }',
          '',
          '  const model = {',
          '    subscribe(fn) { listeners.push(fn); },',
          '',
          '    add(title) {',
          '      tasks.push({ id: tasks.length + 1, title, done: false });',
          '      emit();',
          '    },',
          '',
          '    toggle(id) {',
          '      const task = tasks.find((t) => t.id === id);',
          '      if (task) task.done = !task.done;',
          '      emit();',
          '    },',
          '',
          '    get state() {',
          '      return { tasks: tasks.map((t) => ({ ...t })), remaining: tasks.filter((t) => !t.done).length };',
          '    },',
          '  };',
          '',
          '  return model;',
          '}',
          '',
          '// VIEW: rendering only. Knows nothing about the rules.',
          'function createTaskView(listEl, countEl) {',
          '  return {',
          '    render(state) {',
          '      listEl.replaceChildren(',
          '        ...state.tasks.map((task) => {',
          '          const li = document.createElement("li");',
          '          li.textContent = `${task.done ? "[x]" : "[ ]"} ${task.title}`;',
          '          li.dataset.id = String(task.id);',
          '          return li;',
          '        }),',
          '      );',
          '',
          '      countEl.textContent = `${state.remaining} remaining`;',
          '    },',
          '  };',
          '}',
          '',
          '// CONTROLLER: wires input to the model, and the model to the view.',
          'function createTaskController(model, view) {',
          '  model.subscribe((state) => view.render(state));',
          '',
          '  return {',
          '    addTask(title) { model.add(title); },',
          '    toggleTask(id) { model.toggle(id); },',
          '  };',
          '}',
          '',
          'const model = createTaskModel();',
          'const view = createTaskView(document.getElementById("list"), document.getElementById("count"));',
          'const controller = createTaskController(model, view);',
          '',
          'controller.addTask("write lesson");',
          'controller.addTask("verify examples");',
          'controller.toggleTask(1);',
          '',
          'console.log("rendered :", document.getElementById("list").children.length);',
          'console.log("first    :", document.getElementById("list").children[0].textContent);',
          'console.log("count    :", document.getElementById("count").textContent);',
          '',
          '// The model can be tested with no DOM whatsoever',
          'const headless = createTaskModel();',
          'headless.add("a");',
          'headless.add("b");',
          'headless.toggle(1);',
          'console.log("headless :", headless.state.remaining);',
        ].join('\n'),
        output: [
          'rendered : 2',
          'first    : [x] write lesson',
          'count    : 1 remaining',
          'headless : 1',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'What MVC actually buys',
        body: [
          'The **model** holds data and rules and can be tested with no DOM — the last line proves it. The **view** renders a state object and knows nothing about tasks or rules. The **controller** connects them.',
          'The payoff is that each can change independently: a redesign touches only the view, a rule change only the model. The model also observes the pattern from lesson 2 — it notifies rather than calling the view directly, so it does not depend on the view existing.',
          'Be aware that "MVC" means noticeably different things in different frameworks and eras, and the boundaries are debated. Treat it as **a name for separating data, presentation and coordination**, not as a specification.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Pattern misuse',
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Pattern as ceremony',
          code: [
            'class AbstractGreeter {',
            '  greet() {',
            '    throw new Error(',
            '      "not implemented");',
            '  }',
            '}',
            '',
            'class EnglishGreeter',
            '  extends AbstractGreeter {',
            '  greet(n) {',
            '    return `Hello ${n}`;',
            '  }',
            '}',
            '',
            'new GreeterFactory()',
            '  .create("en")',
            '  .greet("Ada");',
          ].join('\n'),
        },
        right: {
          title: 'The actual requirement',
          code: [
            'function greet(name) {',
            '  return `Hello ${name}`;',
            '}',
            '',
            'greet("Ada");',
          ].join('\n'),
        },
        note: 'There is one greeting. The hierarchy and factory exist for languages that were never requested — YAGNI from Module 40, wearing a pattern name. When a second language genuinely arrives, its real requirements (pluralisation? right-to-left? interpolation order?) will almost certainly not match what was guessed.',
      },
      {
        kind: SECTION.LIST,
        items: [
          '**A pattern name is not a justification.** "It is a factory" answers what, not why. The reason must be a problem the pattern solves *here*.',
          '**Patterns solve problems you have, not problems you might have.** A strategy for one strategy, an observer with one observer, an adapter for one API — each is indirection with nothing on the other side.',
          '**JavaScript dissolves several patterns.** First-class functions mean strategy is often just passing a function; closures mean the module pattern is a file; iterators are built into the language.',
          '**Indirection has a cost.** Every layer is a hop the reader must follow to answer "what actually happens?". Two hops for real flexibility is a good trade; two hops for imagined flexibility is not.',
          '**Prefer the simplest thing that works, then refactor when the second case arrives.** The second case tells you what the abstraction actually needs to be.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The same intent, with and without ceremony.',
        code: [
          '"use strict";',
          '',
          '// CEREMONY: a strategy object for a single behaviour',
          'const sortStrategies = { byName: (a, b) => a.name.localeCompare(b.name) };',
          '',
          'function sortWithStrategy(items, name) {',
          '  const strategy = sortStrategies[name];',
          '  if (!strategy) throw new Error("unknown strategy");',
          '  return [...items].sort(strategy);',
          '}',
          '',
          '// DIRECT: in JavaScript the comparator IS the strategy',
          'function sortBy(items, compare) {',
          '  return [...items].sort(compare);',
          '}',
          '',
          'const people = [{ name: "cy" }, { name: "ada" }];',
          '',
          'console.log("ceremony:", sortWithStrategy(people, "byName").map((p) => p.name));',
          'console.log("direct  :", sortBy(people, (a, b) => a.name.localeCompare(b.name)).map((p) => p.name));',
          '',
          '// And the direct version already supports every future case',
          'console.log("reversed:", sortBy(people, (a, b) => b.name.localeCompare(a.name)).map((p) => p.name));',
        ].join('\n'),
        output: [
          'ceremony: ["ada", "cy"]',
          'direct  : ["ada", "cy"]',
          'reversed: ["cy", "ada"]',
        ].join('\n'),
      },
      {
        kind: SECTION.PROSE,
        body: [
          'The registry version restricts callers to strategies someone remembered to register, while the direct version accepts any comparator — so it is both simpler **and** more flexible. That is the specific way patterns designed for other languages misfire in JavaScript: they reimplement, with objects, what first-class functions already provide.',
          'A named registry is still right when the choice must come from **data** — a stored user preference, a URL parameter — because a string cannot be a function. That is the genuine version of this pattern, and it is a different situation from the one above.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// An application has exactly one payment provider.',
          '// A developer adds:',
          '//   - PaymentStrategy (abstract base)',
          '//   - StripeStrategy (the only implementation)',
          '//   - PaymentStrategyFactory',
          '//   - PaymentFacade wrapping the factory',
          '',
          '// What has been achieved?',
        ].join('\n'),
        options: [
          'Four layers of indirection for one implementation — the flexibility is imaginary until a second provider exists',
          'A well-architected, future-proof payment system',
          'Better performance',
          'Improved type safety',
        ],
        correct: 0,
        explanation:
          'Every layer costs a hop for anyone tracing what actually happens, and none of them is currently choosing between anything — the abstract base has one subclass, the factory has one branch, and the facade wraps a factory that returns the only option. The flexibility is imaginary. Worse, when a second provider does arrive its real requirements — different error shapes, different async flows, extra confirmation steps — will very likely not fit the interface guessed in advance, so the abstraction must be redesigned anyway. **Write the direct implementation, and extract the abstraction when the second case tells you what it needs to be.** Note the counter-case: if a second provider is already contracted and starts next month, building the seam now is planning, not speculation.',
      },
    ],
    exercises: [
      {
        id: 'ex-m41-03-a',
        title: 'Write an adapter',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['design-patterns'],
        instructions:
          'Write `adaptLegacyUser(raw)` converting `{ user_name, email_address, is_active }` into `{ name, email, isActive }`, where `isActive` is a real boolean derived from `is_active === 1`.',
        starterCode: [
          'function adaptLegacyUser(raw) {',
          '  // Translate once, at the boundary.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'maps the fields', body: 'expect(adaptLegacyUser({ user_name: "Ada", email_address: "a@x", is_active: 1 })).toEqual({ name: "Ada", email: "a@x", isActive: true });' },
          { name: 'converts inactive', body: 'expect(adaptLegacyUser({ user_name: "Bo", email_address: "b@x", is_active: 0 }).isActive).toBe(false);' },
          { name: 'isActive is a boolean, not a number', body: 'expect(typeof adaptLegacyUser({ user_name: "a", email_address: "b", is_active: 1 }).isActive).toBe("boolean");' },
          { name: 'drops the legacy field names', body: 'expect(Object.keys(adaptLegacyUser({ user_name: "a", email_address: "b", is_active: 1 })).sort()).toEqual(["email", "isActive", "name"]);' },
          { name: 'treats an unexpected value as inactive', body: 'expect(adaptLegacyUser({ user_name: "a", email_address: "b", is_active: 2 }).isActive).toBe(false);' },
          { name: 'does not mutate the input', body: 'const raw = { user_name: "a", email_address: "b", is_active: 1 }; adaptLegacyUser(raw); expect(raw.user_name).toBe("a");' },
          { name: 'handles a missing flag', body: 'expect(adaptLegacyUser({ user_name: "a", email_address: "b" }).isActive).toBe(false);', hidden: true },
        ],
        hints: [
          'Build and return a brand-new object.',
          '`raw.is_active === 1` already produces a boolean.',
          'Do not spread `raw`, or the legacy keys come along.',
        ],
        solution: [
          'function adaptLegacyUser(raw) {',
          '  return {',
          '    name: raw.user_name,',
          '    email: raw.email_address,',
          '    isActive: raw.is_active === 1,',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Constructing a fresh object rather than spreading `raw` is what makes the fourth test pass — spreading would carry the legacy key names through and defeat the purpose, letting the external shape leak inward. The strict `=== 1` comparison produces a genuine boolean and treats anything unexpected as inactive, which covers both the fifth test and the hidden missing-field case without extra guards. The value of doing this once at the boundary is that `is_active === 1` never appears anywhere else in the application.',
      },
      {
        id: 'ex-m41-03-b',
        title: 'Build a facade',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['design-patterns'],
        instructions:
          'Write `createOrderService({ validate, price, log })` returning `{ submit }`. `submit(order)` validates (returning `{ ok: false, reason }` and logging the rejection on failure), otherwise prices it, logs it, and returns `{ ok: true, total }`.',
        starterCode: [
          'function createOrderService({ validate, price, log }) {',
          '  // One method replacing three coordinated calls.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'submits a valid order', body: 'const s = createOrderService({ validate: () => null, price: () => 50, log: () => {} }); expect(s.submit({})).toEqual({ ok: true, total: 50 });' },
          { name: 'rejects an invalid order', body: 'const s = createOrderService({ validate: () => "bad", price: () => 50, log: () => {} }); expect(s.submit({})).toEqual({ ok: false, reason: "bad" });' },
          { name: 'does not price an invalid order', body: 'let priced = false; const s = createOrderService({ validate: () => "bad", price: () => { priced = true; return 0; }, log: () => {} }); s.submit({}); expect(priced).toBe(false);' },
          { name: 'logs a success', body: 'const lines = []; const s = createOrderService({ validate: () => null, price: () => 50, log: (l) => lines.push(l) }); s.submit({}); expect(lines.length).toBe(1);' },
          { name: 'logs a rejection', body: 'const lines = []; const s = createOrderService({ validate: () => "bad", price: () => 0, log: (l) => lines.push(l) }); s.submit({}); expect(lines.length).toBe(1);' },
          { name: 'passes the order to validate', body: 'let seen = null; const s = createOrderService({ validate: (o) => { seen = o; return null; }, price: () => 1, log: () => {} }); s.submit({ id: 7 }); expect(seen).toEqual({ id: 7 });' },
          { name: 'passes the order to price', body: 'let seen = null; const s = createOrderService({ validate: () => null, price: (o) => { seen = o; return 1; }, log: () => {} }); s.submit({ id: 9 }); expect(seen).toEqual({ id: 9 });', hidden: true },
        ],
        hints: [
          'Validate first and return early on a problem.',
          'Only call `price` once validation passed.',
          'Log on both paths, with different messages.',
        ],
        solution: [
          'function createOrderService({ validate, price, log }) {',
          '  return {',
          '    submit(order) {',
          '      const problem = validate(order);',
          '',
          '      if (problem) {',
          '        log(`rejected: ${problem}`);',
          '        return { ok: false, reason: problem };',
          '      }',
          '',
          '      const total = price(order);',
          '      log(`submitted: ${total}`);',
          '',
          '      return { ok: true, total };',
          '    },',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The facade removes real complexity from callers: they no longer need to know that validation comes first, that pricing must be skipped on failure, or that both outcomes are logged. The third test pins that ordering down explicitly — pricing an invalid order would be a genuine bug, and the guard clause prevents it. Because all three collaborators are **passed in**, every test here uses plain functions with no mocking framework, which is exactly why a facade should simplify without hiding what it depends on.',
      },
      {
        id: 'ex-m41-03-c',
        title: 'Is this pattern justified?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.HARD,
        xp: 25,
        topicIds: ['design-patterns', 'clean-code'],
        instructions:
          'A codebase has one notification channel (email) but includes an abstract base class, one subclass, and a factory. What is the honest assessment?',
        options: [
          'Good architecture — it is ready for future channels',
          'Three layers of indirection for one implementation; the flexibility is imaginary, and a real second channel will likely not fit the guessed interface',
          'It improves performance',
          'It is required for testability',
        ],
        correct: 1,
        hints: [
          'What is the factory currently choosing between?',
        ],
        solution: 'Three layers of indirection for one implementation; the flexibility is imaginary, and a real second channel will likely not fit the guessed interface',
        solutionExplanation:
          'The factory chooses between one option and the base class has one subclass, so nothing is being abstracted over — every layer is a hop a reader must follow for no current benefit. The deeper problem is that a real SMS or push channel will bring requirements nobody anticipated (delivery receipts, rate limits, different error shapes), so the interface guessed in advance usually needs redesigning anyway. Testability does not require it either: injecting a plain function is simpler. Write the direct implementation and extract the seam when the second case reveals what it actually needs to be.',
      },
      {
        id: 'ex-m41-03-d',
        title: 'Which pattern fits?',
        kind: EXERCISE_KIND.CHOOSE_IMPLEMENTATION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 20,
        topicIds: ['design-patterns'],
        instructions:
          'Your application consumes two weather APIs that return the same data in different shapes. Which pattern applies?',
        options: [
          'Singleton',
          'Adapter — translate each external shape into one internal shape at the boundary',
          'Command',
          'Observer',
        ],
        correct: 1,
        hints: [
          'The problem is incompatible interfaces, not shared state or notification.',
        ],
        solution: 'Adapter — translate each external shape into one internal shape at the boundary',
        solutionExplanation:
          'An adapter is exactly the pattern for reconciling incompatible interfaces: write one per API, translate at the boundary, and everything downstream is written once against a single internal shape. Without it, checks like `raw.temp_f` versus `raw.temperature.fahrenheit` spread through the application and every consumer must know which service it is talking to. The others solve different problems — shared instances, actions with undo, and change notification respectively.',
      },
    ],
    quiz: {
      id: 'qz-m41-03',
      questions: [
        {
          id: 'q-m41-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['design-patterns'],
          prompt: 'What problem does an adapter solve?',
          options: [
            'Sharing one instance',
            'Reconciling incompatible interfaces so downstream code works with one shape',
            'Notifying subscribers of change',
            'Undoing an action',
          ],
          correct: 1,
          optionExplanations: [
            'That is singleton.',
            'Correct — translate once at the boundary.',
            'That is observer.',
            'That is command.',
          ],
          explanation:
            'An adapter stops an external API\'s shape leaking inward. Translate at the boundary and swapping providers becomes a one-file change.',
        },
        {
          id: 'q-m41-03-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['design-patterns'],
          prompt: 'When is a wrapper NOT a facade?',
          options: [
            'When it has one method',
            'When it forwards a single call without simplifying anything for the caller',
            'When it is a function rather than a class',
            'When it takes parameters',
          ],
          correct: 1,
          optionExplanations: [
            'A facade may expose one method.',
            'Correct — a layer that adds nothing costs a hop.',
            'Functions are fine.',
            'Parameters are irrelevant.',
          ],
          explanation:
            'A facade coordinates several operations, an order of steps, or shared error handling. If a caller would just call the one thing underneath, the layer only adds a hop.',
        },
        {
          id: 'q-m41-03-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['design-patterns'],
          prompt: 'Using a named design pattern is evidence that code is well designed.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'A misapplied pattern makes code worse.',
            'Correct — the pattern must solve a problem you have.',
          ],
          explanation:
            'A pattern name answers what, not why. A strategy with one strategy or a factory with one product is indirection with nothing on the other side.',
        },
        {
          id: 'q-m41-03-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['design-patterns'],
          prompt: 'Why do some classic patterns look unnecessary in JavaScript?',
          options: [
            'JavaScript is not object-oriented',
            'First-class functions and closures already provide what several patterns simulate with objects',
            'JavaScript is too slow for them',
            'They are only for typed languages',
          ],
          correct: 1,
          optionExplanations: [
            'It supports objects fully.',
            'Correct — a comparator already is a strategy.',
            'Performance is irrelevant.',
            'Typing is not the deciding factor.',
          ],
          explanation:
            'Passing a comparator *is* strategy; a module file *is* the module pattern. Reimplementing those with object registries is usually both more complex and less flexible.',
        },
      ],
    },
    summary:
      'An **adapter** reconciles incompatible interfaces by translating **once at the boundary**, so downstream code is written against one internal shape and swapping providers is a one-file change — the habit worth keeping is *do not let an external API\'s shape leak into your domain*. A **facade** offers one entry point over a genuinely complex interaction: several subsystems, a required order of operations, shared error handling. A function that forwards one call to one other function is **just a wrapper**, and the test is whether the caller\'s job gets meaningfully simpler; passing collaborators **in** keeps a facade testable and honest about its dependencies. **MVC** separates data and rules (**model**, testable with no DOM), rendering (**view**, which knows nothing about the domain) and coordination (**controller**) — with the model **notifying** rather than calling the view, so it does not depend on the view existing. Treat MVC as a name for that separation, not a specification, since it means different things across frameworks. Finally, **pattern misuse**: a pattern name is not a justification, patterns solve problems you **have**, and every layer costs a hop for anyone tracing what happens. **JavaScript dissolves several patterns** — a comparator already *is* a strategy, a module file *is* the module pattern — and reimplementing them with object registries is usually both more complex and **less** flexible. Write the direct implementation; extract the abstraction when the second case reveals what it actually needs to be.',
    keyTakeaways: [
      'An adapter stops external shapes leaking into your domain',
      'A facade must genuinely simplify — otherwise it is just a wrapper',
      'Pass collaborators in so a facade stays testable and honest',
      'MVC names a separation; the model should notify, not call the view',
      'A pattern name answers what, not why',
      'First-class functions already provide what several patterns simulate',
    ],
    relatedLessons: ['l-m41-02', 'l-m41-01'],
    interviewConnections: [
      'What is the adapter pattern for?',
      'What distinguishes a facade from an ordinary wrapper?',
      'Explain the MVC separation.',
      'When does a design pattern make code worse?',
    ],
  },
];
