import { SECTION, CALLOUT_TONE, DIFFICULTY, EXERCISE_KIND, QUIZ_KIND } from '../../schema/types.js';

const M = 'm46';

export default [
  /* ================================================================== */
  {
    id: 'l-m46-01',
    slug: 'explaining-concepts',
    moduleId: M,
    order: 1,
    title: 'Explaining Concepts',
    description: 'A structure for answering "what is X?" — and short and deep versions of the core answers.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 18,
    xp: 50,
    topicIds: ['interview'],
    prerequisites: ['l-m45-02'],
    learningObjectives: [
      'Structure a technical answer so it lands in thirty seconds',
      'Give both a concise and a deep version of core answers',
      'State uncertainty professionally instead of bluffing',
      'Recognise the weak answers that lose offers',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'The shape of a strong answer',
      },
      {
        kind: SECTION.LIST,
        ordered: true,
        items: [
          '**Define it precisely.** One or two sentences that would satisfy someone who already knows the answer.',
          '**Say why it matters.** What problem does it solve, or what does it let you do?',
          '**Give a concrete example.** Short, specific, and ideally from real work rather than a textbook.',
          '**Add a caveat or trade-off.** This is what separates a memorised answer from an understood one.',
        ],
      },
      {
        kind: SECTION.COMPARISON,
        left: {
          title: 'Weak answer',
          code: [
            'Q: What is a closure?',
            '',
            'A: "It\'s a function',
            'inside another',
            'function."',
            '',
            '',
            '',
            '// Describes where',
            '// closures appear.',
            '// Defines nothing.',
          ].join('\n'),
        },
        right: {
          title: 'Strong answer',
          code: [
            'Q: What is a closure?',
            '',
            'A: "A function together',
            'with the lexical',
            'environment it keeps',
            'access to from where it',
            'was created. It lets a',
            'function retain private',
            'state after the outer',
            'call returns — a counter',
            'factory is the classic',
            'case. Worth knowing it',
            'captures the binding,',
            'not a snapshot."',
          ].join('\n'),
        },
        note: 'The strong answer follows the four steps: definition, purpose, example, caveat. It takes about twenty seconds to say, and the caveat about bindings signals that the candidate has actually hit the `var`-in-a-loop problem rather than read a definition.',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Definitions by location are the most common weak answer',
        body: [
          '"A closure is a function inside a function." "A promise is something that happens later." "`this` is the current object." Each describes where you would *see* the thing, and says nothing about what it **is**.',
          'The test: could someone use your definition to **decide a case they had not seen**? "A function inside a function" cannot tell you whether a callback passed to `filter` is a closure. "A function plus its retained environment" answers it immediately — yes, if it reads an outer variable.',
          'Interviewers ask follow-ups precisely to find out which kind of answer you gave.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Thirty seconds, then depth',
      },
      {
        kind: SECTION.PROSE,
        body: [
          'Lead with the concise version, then offer more. "That is the short answer — I can go into how the microtask queue makes that ordering deterministic if useful" gives the interviewer control over depth and demonstrates that you have it.',
          'Answering at length immediately is a real mistake: it buries the point, uses time you need for later questions, and can read as uncertainty rather than depth.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Core answers in both lengths.',
        code: [
          '"use strict";',
          '',
          'const answers = {',
          '  "What is a closure?": {',
          '    short: "A function plus the lexical environment it retains from where it was created.",',
          '    deep: "It captures the binding, not a copy — so a var loop shares one variable and let creates one per iteration.",',
          '  },',
          '',
          '  "How does this work?": {',
          '    short: "For an ordinary function, this is decided by the call site, not where it was written.",',
          '    deep: "Priority: new, then call/apply/bind, then obj.method(), then default — undefined in strict mode. Arrows have no this at all.",',
          '  },',
          '',
          '  "What is the prototype chain?": {',
          '    short: "Property lookup follows an object internal [[Prototype]] link until it reaches null.",',
          '    deep: "A function .prototype is a separate thing — it becomes the [[Prototype]] of instances that constructor creates.",',
          '  },',
          '',
          '  "Why does a promise callback run before setTimeout?": {',
          '    short: "The microtask queue is drained completely before the loop takes the next task.",',
          '    deep: "It is structural, not priority — registration order between the two queues is irrelevant.",',
          '  },',
          '',
          '  "What does fetch do on a 404?": {',
          '    short: "It resolves. Only a network failure rejects, so you must check response.ok.",',
          '    deep: "That surprises people because a 404 feels like an error, but the request succeeded — the server answered.",',
          '  },',
          '};',
          '',
          'for (const [question, answer] of Object.entries(answers)) {',
          '  console.log(question);',
          '  console.log("  30s :", answer.short);',
          '  console.log("  more:", answer.deep);',
          '}',
        ].join('\n'),
        output: [
          'What is a closure?',
          '  30s : A function plus the lexical environment it retains from where it was created.',
          '  more: It captures the binding, not a copy — so a var loop shares one variable and let creates one per iteration.',
          'How does this work?',
          '  30s : For an ordinary function, this is decided by the call site, not where it was written.',
          '  more: Priority: new, then call/apply/bind, then obj.method(), then default — undefined in strict mode. Arrows have no this at all.',
          'What is the prototype chain?',
          '  30s : Property lookup follows an object internal [[Prototype]] link until it reaches null.',
          '  more: A function .prototype is a separate thing — it becomes the [[Prototype]] of instances that constructor creates.',
          'Why does a promise callback run before setTimeout?',
          '  30s : The microtask queue is drained completely before the loop takes the next task.',
          '  more: It is structural, not priority — registration order between the two queues is irrelevant.',
          'What does fetch do on a 404?',
          '  30s : It resolves. Only a network failure rejects, so you must check response.ok.',
          '  more: That surprises people because a 404 feels like an error, but the request succeeded — the server answered.',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'The answers most often given badly',
      },
      {
        kind: SECTION.TABLE,
        headers: ['Question', 'Weak answer', 'What is missing'],
        rows: [
          ['`var` vs `let`', '"`let` is newer"', 'Block scope, the temporal dead zone, no redeclaration'],
          ['`==` vs `===`', '"`===` is stricter"', '`==` applies coercion rules; `===` compares type and value'],
          ['`null` vs `undefined`', '"They are both empty"', '`undefined` is absent-by-default; `null` is a deliberate empty value'],
          ['Event delegation', '"You put the listener on the parent"', '**Why**: bubbling, plus it covers elements added later'],
          ['`map` vs `forEach`', '"`map` returns an array"', '`forEach` is for effects; `map` is a transformation and should be pure'],
          ['Hoisting', '"Declarations move to the top"', 'Nothing moves — bindings are created at scope entry, and `let`/`const` sit in the TDZ'],
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: '"Hoisting moves declarations to the top" is worth unlearning',
        body: [
          'Nothing is moved. Bindings are **created when the scope is entered**, before any code runs — `function` declarations are fully initialised, `var` is initialised to `undefined`, and `let`/`const` are created but **uninitialised**, which is the temporal dead zone (Module 10).',
          'The moving-code metaphor gives the right answer for `var` and the **wrong** one for `let`: it predicts `undefined`, where the real behaviour is a `ReferenceError`.',
          'This matters in interviews because the follow-up is almost always "so what happens with `let`?" — and the metaphor cannot answer it.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'The distinction, demonstrated.',
        code: [
          '"use strict";',
          '',
          '// A function declaration is fully initialised at scope entry',
          'console.log("function :", callable());',
          'function callable() { return "works before its definition"; }',
          '',
          '// var is created and initialised to undefined',
          'console.log("var      :", typeof hoistedVar, hoistedVar);',
          'var hoistedVar = 1;',
          '',
          '// let is created but UNINITIALISED — the temporal dead zone',
          'try {',
          '  console.log(hoistedLet);',
          '} catch (error) {',
          '  console.log("let      :", error.name);',
          '}',
          'let hoistedLet = 1;',
          '',
          '// The error names the binding, proving it exists but is not ready.',
          '// "Not defined" would mean no binding at all:',
          'try {',
          '  console.log(neverDeclared);',
          '} catch (error) {',
          '  console.log("undeclared:", error.message.includes("not defined"));',
          '}',
        ].join('\n'),
        output: [
          'function : works before its definition',
          'var      : undefined undefined',
          'let      : ReferenceError',
          'undeclared: true',
        ].join('\n'),
      },
      {
        kind: SECTION.HEADING,
        text: 'Saying "I do not know" well',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Reason out loud, then say how you would check',
        body: [
          'Interviewers ask questions you cannot answer deliberately, to see what you do. Bluffing fails immediately — the follow-up exposes it — and silence tells them nothing.',
          'The strong shape: **say what you do know**, **reason from it**, and **name how you would verify**. "I have not used `Symbol.toPrimitive` directly, but I know well-known symbols let you hook into language operations, so I would expect it to control coercion. I would check the MDN page and try it in the console."',
          'That answer is often worth more than a memorised correct one, because it demonstrates method — which is what they will actually rely on when you meet something genuinely unfamiliar at work.',
          'Do not over-apologise either. "I am not sure" once is fine; "sorry, I am terrible at this" is not, and it invites the interviewer to agree.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Framing an uncertain answer.',
        code: [
          '"use strict";',
          '',
          'function frameAnswer({ known, inference, verification }) {',
          '  return [',
          '    `What I know: ${known}`,',
          '    `So I would expect: ${inference}`,',
          '    `I would confirm by: ${verification}`,',
          '  ].join("\\n");',
          '}',
          '',
          'console.log(frameAnswer({',
          '  known: "well-known symbols let objects hook into built-in operations",',
          '  inference: "Symbol.toPrimitive controls how an object converts to a primitive",',
          '  verification: "reading MDN and testing +obj and `${obj}` in the console",',
          '}));',
          '',
          'console.log("");',
          '',
          'console.log(frameAnswer({',
          '  known: "structuredClone deep-copies and handles Dates and Maps",',
          '  inference: "it probably cannot clone functions, since they are not data",',
          '  verification: "calling it on an object containing a function and seeing what it throws",',
          '}));',
        ].join('\n'),
        output: [
          'What I know: well-known symbols let objects hook into built-in operations',
          'So I would expect: Symbol.toPrimitive controls how an object converts to a primitive',
          'I would confirm by: reading MDN and testing +obj and `${obj}` in the console',
          '',
          'What I know: structuredClone deep-copies and handles Dates and Maps',
          'So I would expect: it probably cannot clone functions, since they are not data',
          'I would confirm by: calling it on an object containing a function and seeing what it throws',
        ].join('\n'),
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// Interviewer: "What is the difference between == and ===?"',
          '//',
          '// Candidate: "=== is strict equality and == is loose equality."',
          '',
          '// What is wrong with this answer?',
        ].join('\n'),
        options: [
          'It restates the names without saying what "loose" does — it applies coercion rules, which is the actual difference',
          'Nothing — it is correct and complete',
          'It should mention performance',
          'It should recommend always using ==',
        ],
        correct: 0,
        explanation:
          'The answer is **true and empty**: "strict" and "loose" are the names of the operators, so it restates the question. The content the interviewer is listening for is that `==` applies **type coercion** before comparing while `===` requires the same type — plus a concrete consequence such as `"" == 0` being `true` while `"" === 0` is `false`, and the usual advice to default to `===`. A strong version adds the caveat that `== null` is the one idiomatic use of loose equality, since it checks for `null` and `undefined` together. This pattern — naming the thing instead of explaining it — is the single most common way a candidate who *does* know the material gives a weak answer.',
      },
    ],
    exercises: [
      {
        id: 'ex-m46-01-a',
        title: 'Improve the closure answer',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['interview'],
        instructions:
          'Which answer to "what is a closure?" would satisfy a senior interviewer?',
        options: [
          '"A function inside another function."',
          '"A function together with the lexical environment it retains from where it was created — which lets it keep private state after the outer call returns. Note it captures the binding, not a snapshot."',
          '"Something to do with scope."',
          '"A way to make variables private."',
        ],
        correct: 1,
        hints: [
          'Which one could decide a case the candidate has not seen?',
        ],
        solution: '"A function together with the lexical environment it retains from where it was created — which lets it keep private state after the outer call returns. Note it captures the binding, not a snapshot."',
        solutionExplanation:
          'It **defines** rather than locating, states the **purpose**, and adds a **caveat** that only comes from experience — bindings versus snapshots is exactly what explains the `var`-in-a-loop puzzle. The first option describes where closures usually appear and could not tell you whether a callback passed to `filter` qualifies. The last is a **use**, not a definition, and would fail the follow-up "so is an arrow reading an outer variable a closure?" — it is, and it makes nothing private.',
      },
      {
        id: 'ex-m46-01-b',
        title: 'Write both answer lengths',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['interview'],
        instructions:
          'Write `answer(topic)` returning `{ short, deep }` for the topics `"hoisting"`, `"eventLoop"` and `"cors"`. Each `short` must be one sentence; each `deep` must add a caveat or mechanism. Unknown topics return `null`.',
        starterCode: [
          'function answer(topic) {',
          '  // A lookup of prepared answers.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'returns both lengths', body: 'const a = answer("hoisting"); expect(typeof a.short === "string" && typeof a.deep === "string").toBe(true);' },
          { name: 'hoisting mentions the temporal dead zone', body: 'expect(answer("hoisting").deep.toLowerCase().includes("temporal dead zone")).toBe(true);' },
          { name: 'hoisting does not claim code moves', body: 'expect(answer("hoisting").short.toLowerCase().includes("moves to the top")).toBe(false);' },
          { name: 'eventLoop mentions microtasks', body: 'expect(answer("eventLoop").short.toLowerCase().includes("microtask")).toBe(true);' },
          { name: 'cors says it is browser-enforced', body: 'expect(answer("cors").short.toLowerCase().includes("browser")).toBe(true);' },
          { name: 'cors notes it is not authentication', body: 'expect(answer("cors").deep.toLowerCase().includes("not authentication")).toBe(true);' },
          { name: 'returns null for an unknown topic', body: 'expect(answer("quantum")).toBe(null);' },
          { name: 'short answers are a single sentence', body: 'expect(["hoisting", "eventLoop", "cors"].every((t) => answer(t).short.split(". ").length <= 2)).toBe(true);', hidden: true },
        ],
        hints: [
          'Build an object keyed by topic.',
          'Return `?? null` for anything missing.',
          'Keep each `short` to one sentence and put the mechanism in `deep`.',
        ],
        solution: [
          'const ANSWERS = {',
          '  hoisting: {',
          '    short: "Bindings are created when a scope is entered, before any code runs.",',
          '    deep: "Nothing is relocated: function declarations are fully initialised, var is initialised to undefined, and let and const stay uninitialised in the temporal dead zone until their declaration is reached.",',
          '  },',
          '',
          '  eventLoop: {',
          '    short: "After each task the microtask queue is drained completely, so promise callbacks run before the next timer.",',
          '    deep: "It is structural rather than a priority: registration order between the two queues is irrelevant, and a microtask that queues another never lets the checkpoint end, which blocks rendering.",',
          '  },',
          '',
          '  cors: {',
          '    short: "A browser-enforced policy controlling whether one origin can read another origin response.",',
          '    deep: "It is not authentication and does not protect an API, since non-browser clients ignore it; permission comes from server response headers, so no change to the fetch call can grant it.",',
          '  },',
          '};',
          '',
          'function answer(topic) {',
          '  return ANSWERS[topic] ?? null;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Each `short` is a **definition** that could decide an unseen case, and each `deep` adds the mechanism or caveat that distinguishes understanding from recall. The third test enforces the specific correction from this lesson: the hoisting answer must not say code moves, because that metaphor predicts `undefined` for `let` when the real behaviour is a `ReferenceError`. The CORS answers carry the two corrections from Module 44 — browser-enforced, and not authentication. `?? null` handles unknown topics without a truthiness check that a legitimate empty answer would trip.',
      },
      {
        id: 'ex-m46-01-c',
        title: 'Frame an uncertain answer',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['interview'],
        instructions:
          'You are asked about an API you have never used. What is the strongest response?',
        options: [
          'Guess confidently and hope it is right',
          'State what you do know, reason to an expectation from it, and say how you would verify',
          'Say "I don\'t know" and stop',
          'Apologise at length for the gap',
        ],
        correct: 1,
        hints: [
          'What is the interviewer actually assessing here?',
        ],
        solution: 'State what you do know, reason to an expectation from it, and say how you would verify',
        solutionExplanation:
          'Interviewers ask unanswerable questions on purpose, to see how you handle the unfamiliar — which is what they will rely on daily. Reasoning from related knowledge and naming a verification step demonstrates **method**, and is often worth more than a memorised correct answer. Bluffing collapses at the first follow-up and costs your credibility on everything else you said. Flat refusal gives them nothing to assess, and extended apology invites agreement that you are weak — say "I am not sure" once, then reason.',
      },
      {
        id: 'ex-m46-01-d',
        title: 'Correct the hoisting explanation',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['interview'],
        instructions:
          'If "hoisting moves declarations to the top" were accurate, what would `console.log(x); let x = 1;` produce?',
        options: [
          '`undefined` — but it actually throws a ReferenceError, which is why the metaphor is wrong',
          '`1`',
          'A SyntaxError',
          'Nothing at all',
        ],
        correct: 0,
        hints: [
          'What would a declaration relocated to the top actually evaluate to?',
          'Then compare that prediction with what `let` really does.',
        ],
        solution: '`undefined` — but it actually throws a ReferenceError, which is why the metaphor is wrong',
        solutionExplanation:
          'The moving-code metaphor predicts `undefined`, because a declaration relocated to the top would exist and be unassigned. The real behaviour is a **`ReferenceError`**: the binding is created at scope entry but left **uninitialised** until the declaration is reached — the temporal dead zone. Note the error message names `x`, which proves the binding exists; an undeclared variable gives "is not defined" instead. The metaphor happens to give the right answer for `var` and the wrong one for `let` and `const`, which is exactly why interviewers follow up with the `let` case.',
      },
    ],
    quiz: {
      id: 'qz-m46-01',
      questions: [
        {
          id: 'q-m46-01-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['interview'],
          prompt: 'What are the four parts of a strong conceptual answer?',
          options: [
            'History, syntax, example, opinion',
            'Definition, why it matters, concrete example, caveat or trade-off',
            'Definition, code, code, code',
            'Short answer only',
          ],
          correct: 1,
          optionExplanations: [
            'History is rarely what is asked.',
            'Correct — and the caveat signals real experience.',
            'Examples without a definition do not answer the question.',
            'Offer depth after the short answer.',
          ],
          explanation:
            'Definition first so the answer lands, then purpose, a concrete example, and a caveat — which is what distinguishes understanding from recall.',
        },
        {
          id: 'q-m46-01-2',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['interview'],
          prompt: '"Hoisting moves declarations to the top of the scope" is an accurate description.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'It mispredicts let and const.',
            'Correct — bindings are created at scope entry, some uninitialised.',
          ],
          explanation:
            'Nothing is relocated. `var` is initialised to `undefined`, while `let` and `const` stay uninitialised in the temporal dead zone — so the metaphor predicts `undefined` where a `ReferenceError` occurs.',
        },
        {
          id: 'q-m46-01-3',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['interview'],
          prompt: 'Why is "a closure is a function inside a function" a weak answer?',
          options: [
            'It is too short',
            'It describes where closures appear rather than what one is, so it cannot decide an unseen case',
            'It is factually false',
            'It uses the wrong terminology',
          ],
          correct: 1,
          optionExplanations: [
            'Brevity is good.',
            'Correct — it cannot classify a filter callback.',
            'Closures usually are nested.',
            'The terms are fine.',
          ],
          explanation:
            'A definition should let you classify a case you have not seen. "A function plus its retained environment" immediately settles whether a callback reading an outer variable qualifies.',
        },
        {
          id: 'q-m46-01-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['interview'],
          prompt: 'What should you do when asked something you do not know?',
          options: [
            'Guess confidently',
            'Reason from what you do know and state how you would verify it',
            'Change the subject',
            'Apologise extensively',
          ],
          correct: 1,
          optionExplanations: [
            'The follow-up exposes it.',
            'Correct — it demonstrates method.',
            'That is obvious and worse.',
            'It invites agreement.',
          ],
          explanation:
            'These questions are asked deliberately. Showing how you would approach the unfamiliar is often worth more than a memorised answer, because it is what you will actually do at work.',
        },
      ],
    },
    summary:
      'A strong conceptual answer has four parts: **define precisely**, say **why it matters**, give a **concrete example**, and add a **caveat or trade-off** — the last being what distinguishes understanding from recall. Lead with the **thirty-second version** and offer depth, rather than answering at length immediately, which buries the point and can read as uncertainty. The most common weak answer is a **definition by location**: "a function inside a function", "`===` is strict equality". The test is whether your definition could **decide a case you have not seen** — "a function plus its retained environment" settles instantly whether a `filter` callback qualifies, while "a function inside a function" cannot. Several standard answers are routinely given badly, and one is worth unlearning outright: **"hoisting moves declarations to the top" is wrong**. Nothing is relocated — bindings are created at scope entry, with `function` declarations fully initialised, `var` initialised to `undefined`, and `let`/`const` left **uninitialised** in the temporal dead zone. The metaphor gives the right answer for `var` and the wrong one for `let`, which is exactly why the follow-up asks about `let`. Finally, when you do not know: **state what you do know, reason to an expectation, and name how you would verify it**. Interviewers ask such questions deliberately, and demonstrating method is often worth more than a memorised answer — bluffing collapses at the first follow-up, and extended apology invites agreement.',
    keyTakeaways: [
      'Define, justify, exemplify, caveat — in that order',
      'Lead with thirty seconds and offer depth rather than starting deep',
      'A definition must be able to classify a case you have not seen',
      'Hoisting does not move code — bindings are created at scope entry',
      'The TDZ is why the moving-code metaphor fails for let and const',
      'When unsure: what you know, what you infer, how you would check',
    ],
    relatedLessons: ['l-m46-02', 'l-m32-01'],
    interviewConnections: [
      'What is a closure?',
      'What is the difference between == and ===?',
      'Explain hoisting.',
      'How do you handle a question you cannot answer?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m46-02',
    slug: 'output-prediction-and-debugging',
    moduleId: M,
    order: 2,
    title: 'Output Prediction and Debugging',
    description: 'The snippets interviewers actually use, and how to reason through them reliably.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 19,
    xp: 50,
    topicIds: ['interview'],
    prerequisites: ['l-m46-01'],
    learningObjectives: [
      'Predict output for coercion, scope, closures, this and async ordering',
      'Apply a checklist rather than guessing',
      'Diagnose a broken snippet and name the fix',
      'Identify the test that would have caught the bug',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'A checklist for prediction questions',
      },
      {
        kind: SECTION.LIST,
        ordered: true,
        items: [
          '**Is anything asynchronous?** If so, separate the synchronous output first, then microtasks, then tasks (Module 33).',
          '**Is `this` involved?** Find the **call site**, and check whether the function is an arrow (Module 29).',
          '**Are there closures in a loop?** Ask **how many bindings exist**, not which keyword was used (Module 32).',
          '**Is coercion happening?** `==`, `+` with mixed types, and truthiness checks all convert (Module 03).',
          '**Are objects shared?** A copied reference is the same object; only the binding was copied (Module 14).',
          '**Which declaration?** `var` is function-scoped and initialised to `undefined`; `let`/`const` sit in the TDZ.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Coercion — the classics, with the reason for each.',
        code: [
          '"use strict";',
          '',
          'const cases = [',
          '  ["0 == \'\'", 0 == "", "both convert to 0"],',
          '  ["0 === \'\'", 0 === "", "different types, no conversion"],',
          '  ["null == undefined", null == undefined, "specified as equal to each other only"],',
          '  ["null === undefined", null === undefined, "different types"],',
          '  ["[] + []", [] + [], "both stringify to empty strings"],',
          '  ["typeof null", typeof null, "a historical bug, kept for compatibility"],',
          '  ["0.1 + 0.2 === 0.3", 0.1 + 0.2 === 0.3, "binary floating point"],',
          '  ["NaN === NaN", NaN === NaN, "NaN is not equal to anything"],',
          '  ["\'5\' - 2", "5" - 2, "minus has no string meaning, so it converts"],',
          '  ["\'5\' + 2", "5" + 2, "plus concatenates when either side is a string"],',
          '];',
          '',
          'for (const [expression, result, why] of cases) {',
          '  console.log(`${expression.padEnd(18)} ${String(JSON.stringify(result)).padEnd(7)} ${why}`);',
          '}',
        ].join('\n'),
        output: [
          '0 == \'\'            true    both convert to 0',
          '0 === \'\'           false   different types, no conversion',
          'null == undefined  true    specified as equal to each other only',
          'null === undefined false   different types',
          '[] + []            ""      both stringify to empty strings',
          'typeof null        "object" a historical bug, kept for compatibility',
          '0.1 + 0.2 === 0.3  false   binary floating point',
          'NaN === NaN        false   NaN is not equal to anything',
          '\'5\' - 2            3       minus has no string meaning, so it converts',
          '\'5\' + 2            "52"    plus concatenates when either side is a string',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Answer with the rule, not the memorised result',
        body: [
          '"`\'5\' - 2` is `3`" is a fact. "`-` has no string meaning, so both operands convert to numbers; `+` is overloaded for concatenation, so `\'5\' + 2` is `\'52\'`" is a **rule** that also predicts `\'5\' * 2` and `\'a\' - 1`.',
          'Interviewers follow up specifically to find out which you have. Stating the rule answers the follow-up before it is asked.',
          'Note `null == undefined` is `true` but `null == 0` is `false` — `null` is specified to equal only `undefined` under loose equality, which is why `x == null` is the one idiomatic use of `==`.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Async ordering — the question that appears most often.',
        code: [
          '"use strict";',
          '',
          'const order = [];',
          '',
          'order.push("1 script start");',
          '',
          'setTimeout(() => order.push("6 timeout"), 0);',
          '',
          'new Promise((resolve) => {',
          '  order.push("2 executor runs synchronously");',
          '  resolve();',
          '}).then(() => order.push("4 then — queued when .then was called"));',
          '',
          'async function run() {',
          '  order.push("3 async prefix");',
          '  await null;',
          '  order.push("5 after await — queued later, when run() ran");',
          '}',
          '',
          'run();',
          '',
          'order.push("script end (still synchronous)");',
          '',
          'setTimeout(() => {',
          '  order.forEach((line) => console.log(line));',
          '}, 5);',
        ].join('\n'),
        output: [
          '1 script start',
          '2 executor runs synchronously',
          '3 async prefix',
          'script end (still synchronous)',
          '4 then — queued when .then was called',
          '5 after await — queued later, when run() ran',
          '6 timeout',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Three facts settle almost every ordering question',
        body: [
          '**A `Promise` executor runs synchronously.** It is not deferred — only the `.then` reaction is.',
          '**An `async` function runs synchronously up to its first `await`**, then returns and queues the remainder as a microtask.',
          '**All microtasks drain before the next task.** So every promise reaction precedes every timer, regardless of registration order.',
          '**Microtasks run in registration order.** In the snippet above the `.then` reaction is queued the moment `.then` is called — which happens *before* `run()` is invoked — so it precedes the `await` continuation even though the `await` appears earlier in the reading order of the output. Registration time, not source position, decides.',
          'Work through a snippet in exactly that order — synchronous first, then microtasks in registration order, then tasks — and say your reasoning aloud. Getting the reasoning right with one position wrong scores better than a correct guess with no explanation.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Closures, `this` and references.',
        code: [
          '"use strict";',
          '',
          '// 1. Closures in a loop — count the bindings',
          'const withVar = [];',
          'for (var i = 0; i < 3; i++) withVar.push(() => i);',
          '',
          'const withLet = [];',
          'for (let j = 0; j < 3; j++) withLet.push(() => j);',
          '',
          'console.log("var :", withVar.map((f) => f()), "one shared binding");',
          'console.log("let :", withLet.map((f) => f()), "one binding per iteration");',
          '',
          '// 2. this — find the call site',
          'const user = {',
          '  name: "Ada",',
          '  regular() { return this?.name; },',
          '  arrow: () => (typeof this === "undefined" ? "no this" : "module this"),',
          '};',
          '',
          'const detached = user.regular;',
          '',
          'console.log("method   :", user.regular());',
          'console.log("detached :", detached());',
          'console.log("arrow    :", user.arrow());',
          '',
          '// 3. References — the binding was copied, not the object',
          'const a = { count: 1 };',
          'const b = a;',
          'b.count = 2;',
          '',
          'console.log("shared   :", a.count, a === b);',
          '',
          'let c = { count: 1 };',
          'let d = c;',
          'd = { count: 9 };            // reassigns d, does not touch c',
          '',
          'console.log("rebound  :", c.count, c === d);',
        ].join('\n'),
        output: [
          'var : [3, 3, 3] one shared binding',
          'let : [0, 1, 2] one binding per iteration',
          'method   : Ada',
          'detached : undefined',
          'arrow    : no this',
          'shared   : 2 true',
          'rebound  : 1 false',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.MISTAKE,
        title: 'The distinctions each of those tests',
        body: [
          '**Loop closures** turn on the number of **bindings**, not the keyword — a `let` declared *outside* the loop would print `[2, 2, 2]` just like `var`.',
          '**`this`** is decided by the **call site**, so `detached()` has no receiver. The `?.` above is what stops it throwing; without it you would get a `TypeError`, which is what a strict-mode class method does.',
          '**References**: `b = a` copies the reference, so both name the same object and a mutation is visible through either. But `d = {...}` **rebinds** `d` rather than mutating, leaving `c` untouched — the difference between changing an object and changing which object a name refers to.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Debugging questions',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A broken snippet of the kind interviewers hand you.',
        code: [
          '"use strict";',
          '',
          '// "This should total the paid orders, but returns 0. Why?"',
          'function totalPaidBroken(orders) {',
          '  let total = 0;',
          '',
          '  orders.forEach((order) => {',
          '    if (order.status = "paid") {          // BUG 1: assignment, not comparison',
          '      total += order.amount;',
          '    }',
          '  });',
          '',
          '  return total;',
          '}',
          '',
          '// "And this one returns undefined."',
          'function totalPaidBroken2(orders) {',
          '  return orders',
          '    .filter((order) => order.status === "paid")',
          '    .reduce((sum, order) => {',
          '      sum + order.amount;                 // BUG 2: no return',
          '    }, 0);',
          '}',
          '',
          'const orders = [',
          '  { status: "paid", amount: 10 },',
          '  { status: "pending", amount: 99 },',
          '];',
          '',
          'const copy = orders.map((o) => ({ ...o }));',
          '',
          'console.log("broken 1 :", totalPaidBroken(copy));',
          'console.log("side effect:", copy.map((o) => o.status), "<- all mutated to paid");',
          'console.log("broken 2 :", totalPaidBroken2(orders));',
          '',
          '// Fixed',
          'function totalPaid(orders) {',
          '  return orders',
          '    .filter((order) => order.status === "paid")',
          '    .reduce((sum, order) => sum + order.amount, 0);',
          '}',
          '',
          'console.log("fixed    :", totalPaid(orders));',
          'console.log("no mutation:", orders.map((o) => o.status));',
        ].join('\n'),
        output: [
          'broken 1 : 109',
          'side effect: ["paid", "paid"] <- all mutated to paid',
          'broken 2 : undefined',
          'fixed    : 10',
          'no mutation: ["paid", "pending"]',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Answer all four parts',
        body: [
          'A debugging question wants: **what is wrong**, **why**, **how to fix it**, and **what test would catch it**. Candidates routinely stop after the first.',
          'Bug 1: `=` **assigns** and evaluates to the assigned value, so the condition is always the truthy `"paid"` — and it **mutates every order** on the way through, which is the more serious half. A linter catches this class outright.',
          'Bug 2: the `reduce` callback has a **block body with no `return`**, so it yields `undefined`, which becomes the next accumulator. Removing the braces makes it an expression body that returns.',
          'The test that catches both: `expect(totalPaid([{status:"paid",amount:10},{status:"pending",amount:99}])).toBe(10)` — plus one asserting the input is unmutated, which is what would have caught the side effect.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '"use strict";',
          '',
          'const obj = {',
          '  items: [1, 2, 3],',
          '  total() {',
          '    return this.items.reduce(function (sum, n) {',
          '      return sum + n * this.multiplier;',
          '    }, 0);',
          '  },',
          '  multiplier: 2,',
          '};',
          '',
          'obj.total();',
        ].join('\n'),
        options: [
          'A TypeError — the ordinary callback is called with no receiver, so `this` is undefined in strict mode',
          '12',
          '6',
          'NaN',
        ],
        correct: 0,
        explanation:
          '`total` itself is fine — `obj.total()` puts `obj` to the left of the dot, so `this.items` resolves. The problem is the **inner** function: `reduce` invokes its callback as a plain call, so default binding applies and `this` is `undefined` in strict mode, making `this.multiplier` throw `TypeError: Cannot read properties of undefined`. Two fixes: make the callback an **arrow**, which has no `this` of its own and inherits `total`\'s; or capture `const { multiplier } = this` before the reduce. Note in **sloppy** mode this would not throw — `this` would be the global object and `this.multiplier` would be `undefined`, giving `NaN`. A wrong number is harder to diagnose than a thrown error, which is one more reason modules are always strict.',
      },
    ],
    exercises: [
      {
        id: 'ex-m46-02-a',
        title: 'Predict the async order',
        kind: EXERCISE_KIND.PREDICT_OUTPUT,
        difficulty: DIFFICULTY.HARD,
        xp: 30,
        topicIds: ['interview'],
        instructions:
          'For `log("A"); setTimeout(() => log("B")); Promise.resolve().then(() => log("C")); log("D");` — what is the order?',
        options: ['A D C B', 'A B C D', 'A C D B', 'A D B C'],
        correct: 0,
        hints: [
          'Synchronous first, then microtasks, then tasks.',
        ],
        solution: 'A D C B',
        solutionExplanation:
          '`A` and `D` are plain synchronous statements, so they run first in source order — `setTimeout` and `.then` only **register** callbacks and return immediately. When the script finishes and the stack empties, the microtask checkpoint drains the queue, running `C`. Only once that queue is empty does the loop take a task, running `B`. The general shape to carry into any ordering question: **all synchronous, then all microtasks, then one task** — and note this holds regardless of registration order, because it is structural rather than a priority.',
      },
      {
        id: 'ex-m46-02-b',
        title: 'Fix the reduce',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 30,
        topicIds: ['interview'],
        instructions:
          'Write `totalPaid(orders)` summing `amount` for orders whose `status` is `"paid"`. The broken version used `=` in the condition and omitted a `return` in the reduce. It must not mutate the input.',
        starterCode: [
          '// Broken: if (order.status = "paid") { ... }',
          '// Broken: .reduce((sum, o) => { sum + o.amount; }, 0)',
          '',
          'function totalPaid(orders) {',
          '}',
        ].join('\n'),
        tests: [
          { name: 'totals paid orders', body: 'expect(totalPaid([{ status: "paid", amount: 10 }, { status: "pending", amount: 99 }])).toBe(10);' },
          { name: 'sums several', body: 'expect(totalPaid([{ status: "paid", amount: 10 }, { status: "paid", amount: 5 }])).toBe(15);' },
          { name: 'returns 0 when none are paid', body: 'expect(totalPaid([{ status: "pending", amount: 99 }])).toBe(0);' },
          { name: 'returns 0 for an empty list', body: 'expect(totalPaid([])).toBe(0);' },
          { name: 'does not mutate the input', body: 'const o = [{ status: "pending", amount: 99 }]; totalPaid(o); expect(o[0].status).toBe("pending");' },
          { name: 'returns a number, not undefined', body: 'expect(typeof totalPaid([{ status: "paid", amount: 1 }])).toBe("number");' },
          { name: 'handles a zero amount', body: 'expect(totalPaid([{ status: "paid", amount: 0 }])).toBe(0);', hidden: true },
        ],
        hints: [
          '`===` compares; `=` assigns.',
          'An arrow with a block body needs an explicit `return`.',
          'An expression body returns automatically.',
        ],
        solution: [
          'function totalPaid(orders) {',
          '  return orders',
          '    .filter((order) => order.status === "paid")',
          '    .reduce((sum, order) => sum + order.amount, 0);',
          '}',
        ].join('\n'),
        solutionExplanation:
          '`===` fixes the more serious bug: `=` would assign `"paid"` to every order, mutating the caller\'s data **and** making the condition always truthy — which the fifth test catches. Using an **expression body** in the reduce returns automatically, where the broken block body returned `undefined` and poisoned the accumulator (sixth test). The `0` initial value handles both empty input and the no-matches case without a special branch, and `filter` returns a new array so nothing is mutated.',
      },
      {
        id: 'ex-m46-02-c',
        title: 'Diagnose the lost this',
        kind: EXERCISE_KIND.FIX_BUG,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['interview'],
        instructions:
          'Write `createCounter()` returning `{ items, addAll, total }` where `total()` multiplies each item by `this.multiplier` (which is `2`). The naive version uses an ordinary callback inside `reduce` and throws — fix it.',
        starterCode: [
          '// Broken: return this.items.reduce(function (sum, n) {',
          '//   return sum + n * this.multiplier;   // `this` is undefined here',
          '// }, 0);',
          '',
          'function createCounter() {',
          '}',
        ].join('\n'),
        tests: [
          { name: 'totals with the multiplier', body: 'const c = createCounter(); c.addAll([1, 2, 3]); expect(c.total()).toBe(12);' },
          { name: 'starts at zero', body: 'expect(createCounter().total()).toBe(0);' },
          { name: 'does not throw', body: 'const c = createCounter(); c.addAll([1]); expect(() => c.total()).not.toThrow();' },
          { name: 'handles one item', body: 'const c = createCounter(); c.addAll([5]); expect(c.total()).toBe(10);' },
          { name: 'accumulates across calls', body: 'const c = createCounter(); c.addAll([1]); c.addAll([2]); expect(c.total()).toBe(6);' },
          { name: 'counters are independent', body: 'const a = createCounter(); const b = createCounter(); a.addAll([5]); expect(b.total()).toBe(0);' },
          { name: 'exposes the multiplier', body: 'expect(createCounter().multiplier).toBe(2);', hidden: true },
        ],
        hints: [
          'An arrow inside the method inherits the method\'s `this`.',
          'Or destructure `const { multiplier } = this` before the reduce.',
          '`addAll` should push onto the existing array.',
        ],
        solution: [
          'function createCounter() {',
          '  return {',
          '    items: [],',
          '    multiplier: 2,',
          '',
          '    addAll(values) {',
          '      this.items.push(...values);',
          '    },',
          '',
          '    total() {',
          '      // An arrow has no this of its own, so it inherits total()\'s',
          '      return this.items.reduce((sum, n) => sum + n * this.multiplier, 0);',
          '    },',
          '  };',
          '}',
        ].join('\n'),
        solutionExplanation:
          'The arrow is the fix: it has **no `this` of its own**, so `this` inside it resolves to `total`\'s — which is the counter, because `c.total()` supplies it at the call site. An ordinary callback is invoked by `reduce` as a plain call, so `this` would be `undefined` in strict mode and the property access would throw. `total` and `addAll` must remain **ordinary methods** so they receive a receiver from the call site; making them arrows would look past the object literal, which is not a scope. Each call to `createCounter` builds a fresh object, giving the independence the sixth test checks.',
      },
      {
        id: 'ex-m46-02-d',
        title: 'Name the test',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['interview'],
        instructions:
          'A function used `if (order.status = "paid")`. Beyond the wrong total, what does that bug do, and which test catches it?',
        options: [
          'Nothing else; a total test is enough',
          'It mutates every order to "paid" — so you also need a test asserting the input is unchanged',
          'It throws a SyntaxError',
          'It only affects the first item',
        ],
        correct: 1,
        hints: [
          'What does an assignment inside a condition do to the object?',
        ],
        solution: 'It mutates every order to "paid" — so you also need a test asserting the input is unchanged',
        solutionExplanation:
          'The assignment **writes** `"paid"` to every order it evaluates, and the expression yields the assigned value, which is truthy — so the condition always passes *and* the caller\'s data is silently corrupted. The corrupted data is the more serious half, because it persists after the function returns and may be saved. A total-only test catches the wrong number; only a test asserting the input is unchanged catches the mutation. This is exactly why a debugging answer should name the test: it forces you to articulate the **full** consequence rather than the visible symptom.',
      },
    ],
    quiz: {
      id: 'qz-m46-02',
      questions: [
        {
          id: 'q-m46-02-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['interview'],
          prompt: 'What is the first question to ask about an output-prediction snippet?',
          options: [
            'How long is it?',
            'Is anything asynchronous — so the synchronous output can be separated first',
            'Which framework is it?',
            'Is it strict mode?',
          ],
          correct: 1,
          optionExplanations: [
            'Length is irrelevant.',
            'Correct — then microtasks, then tasks.',
            'Usually plain JavaScript.',
            'It matters, but later.',
          ],
          explanation:
            'Separating synchronous output, then microtasks, then tasks resolves most ordering questions mechanically rather than by guessing.',
        },
        {
          id: 'q-m46-02-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['interview'],
          prompt: 'Why is "5" - 2 equal to 3 but "5" + 2 equal to "52"?',
          options: [
            'A quirk with no rule',
            '`-` has no string meaning so both convert to numbers; `+` is overloaded for concatenation',
            '`+` is broken',
            'It depends on the engine',
          ],
          correct: 1,
          optionExplanations: [
            'There is a clear rule.',
            'Correct — and it predicts other cases too.',
            'It is specified behaviour.',
            'It is consistent everywhere.',
          ],
          explanation:
            'Stating the rule also predicts `"5" * 2` and `"a" - 1`, which is what an interviewer\'s follow-up is testing.',
        },
        {
          id: 'q-m46-02-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['interview'],
          prompt: 'A Promise executor function runs asynchronously.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Only the reaction is deferred.',
            'Correct — it runs immediately and synchronously.',
          ],
          explanation:
            'The executor runs before `new Promise` returns. Only the `.then` callback is queued as a microtask — which is why wrapping slow code in a promise does not stop it blocking.',
        },
        {
          id: 'q-m46-02-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['interview'],
          prompt: 'What four things should a debugging answer cover?',
          options: [
            'What is wrong, only',
            'What is wrong, why, how to fix it, and what test would catch it',
            'A rewrite of the function',
            'Which linter rule applies',
          ],
          correct: 1,
          optionExplanations: [
            'Candidates usually stop there.',
            'Correct — the test shows you would prevent a recurrence.',
            'Often more than asked.',
            'Useful but not the whole answer.',
          ],
          explanation:
            'Naming the test forces you to articulate the full consequence — which is how the input-mutation half of the `=` bug gets noticed rather than only the wrong total.',
        },
      ],
    },
    summary:
      'Work prediction questions with a **checklist** rather than intuition: is anything **asynchronous** (separate synchronous, then microtasks, then tasks); is **`this`** involved (find the call site, check for an arrow); are there **closures in a loop** (count the **bindings**, not the keyword); is **coercion** happening; are **objects shared**; and which **declaration** was used. For coercion, answer with the **rule** rather than the memorised result — "`-` has no string meaning so both operands convert; `+` is overloaded for concatenation" also predicts `"5" * 2`, which is what the follow-up tests. Three facts settle almost every async ordering question: a **`Promise` executor runs synchronously**, an **`async` function runs synchronously to its first `await`** then queues the rest as a microtask, and **all microtasks drain before the next task** — structurally, so registration order between queues is irrelevant. Say the reasoning aloud; correct reasoning with one position wrong scores better than a lucky guess. For **debugging questions**, answer all four parts — **what, why, the fix, and the test that would catch it** — since candidates routinely stop after the first. That last part matters: `if (order.status = "paid")` produces a wrong total *and* **silently mutates every order**, and only a test asserting the input is unchanged catches the more serious half.',
    keyTakeaways: [
      'Separate synchronous output, then microtasks, then tasks',
      'Answer coercion questions with the rule, not the remembered result',
      'A Promise executor is synchronous; only the reaction is deferred',
      'Loop closures depend on how many bindings exist, not the keyword',
      'A debugging answer covers what, why, the fix, and the test',
      '`=` in a condition corrupts data as well as breaking the check',
    ],
    relatedLessons: ['l-m46-01', 'l-m46-03'],
    interviewConnections: [
      'Predict the output of this mixed async snippet.',
      'Why does this loop print the same value three times?',
      'What is wrong with this function, and what test would catch it?',
      'Why is "5" - 2 different from "5" + 2?',
    ],
  },

  /* ================================================================== */
  {
    id: 'l-m46-03',
    slug: 'coding-rounds-and-readiness',
    moduleId: M,
    order: 3,
    title: 'Coding Rounds and Readiness',
    description: 'Working a coding question aloud, front-end specifics, and an honest self-assessment.',
    difficulty: DIFFICULTY.HARD,
    estimatedMinutes: 19,
    xp: 50,
    topicIds: ['interview'],
    prerequisites: ['l-m46-02'],
    learningObjectives: [
      'Work a coding question using a visible, repeatable process',
      'Discuss complexity and trade-offs while coding',
      'Answer the front-end specific questions confidently',
      'Assess your own readiness against a concrete checklist',
    ],
    sections: [
      {
        kind: SECTION.HEADING,
        text: 'The coding round',
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.DANGER,
        title: 'Silence is the most common failure',
        body: [
          'Interviewers are assessing **how you think**, and a candidate who types quietly for fifteen minutes gives them nothing to assess — even if the final code is correct.',
          'Narrate: what you are clarifying, which approach you are considering, why you rejected one, what you are worried about. "I could sort first, but that is O(n log n) and a `Set` gets me O(n) — I will use the `Set`" is a complete piece of evidence in one sentence.',
          'It also lets them help. A good interviewer will nudge you if you are heading somewhere unproductive, but only if they can tell where you are heading.',
        ],
      },
      {
        kind: SECTION.LIST,
        ordered: true,
        items: [
          '**Clarify.** Input types? Can it be empty? Duplicates? Sorted? What should it return when there is no answer?',
          '**Work an example by hand.** Out loud. This is where the algorithm usually appears.',
          '**State edge cases** before coding: empty, single element, all identical, the answer at either end.',
          '**Describe the approach in words**, including its complexity, and get agreement before typing.',
          '**Say the brute force**, then improve — "the naive version is O(n²); I can make it O(n) with a hash map" shows range.',
          '**Code it**, still talking.',
          '**Trace your own code** against the hand-worked example and the edge cases.',
          '**State the complexity**, in time and space, and mention one thing you would change with more time.',
        ],
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'A full walkthrough: "find the first non-repeating character".',
        code: [
          '"use strict";',
          '',
          '// 1. CLARIFY (aloud): case-sensitive? spaces count? return what if none?',
          '//    Assume: case-sensitive, all characters count, return null if none.',
          '//',
          '// 2. EXAMPLE BY HAND: "swiss" -> s,w,i,s,s -> w appears once first',
          '//',
          '// 3. EDGE CASES: "", "aa", "abc" (first is the answer), "aabb" (none)',
          '//',
          '// 4. BRUTE FORCE: for each character, scan the whole string -> O(n^2)',
          '// 5. BETTER: count in one pass, then scan once for the first count of 1',
          '//    -> O(n) time, O(k) space where k is the alphabet size',
          '',
          'function firstNonRepeating(text) {',
          '  const counts = new Map();',
          '',
          '  for (const char of text) {',
          '    counts.set(char, (counts.get(char) ?? 0) + 1);',
          '  }',
          '',
          '  // Scanning the STRING, not the Map, preserves original order',
          '  for (const char of text) {',
          '    if (counts.get(char) === 1) return char;',
          '  }',
          '',
          '  return null;',
          '}',
          '',
          '// 7. TRACE against the hand-worked example and every edge case',
          'for (const input of ["swiss", "", "aa", "abc", "aabb", "aabbc"]) {',
          '  console.log(`${JSON.stringify(input).padEnd(9)} -> ${JSON.stringify(firstNonRepeating(input))}`);',
          '}',
          '',
          '// 8. COMPLEXITY: two passes over the string is O(n); the Map holds at',
          '//    most one entry per distinct character. With more time I would ask',
          '//    whether Unicode grapheme clusters matter — for...of iterates code',
          '//    points, which is already better than indexing by UTF-16 unit.',
          'console.log("astral   ->", JSON.stringify(firstNonRepeating("a😀😀b")));',
        ].join('\n'),
        output: [
          '"swiss"   -> "w"',
          '""        -> null',
          '"aa"      -> null',
          '"abc"     -> "a"',
          '"aabb"    -> null',
          '"aabbc"   -> "c"',
          'astral   -> "a"',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'Two details that read as senior',
        body: [
          'The second loop iterates the **string**, not the `Map`. Iterating the map would also work here, since `Map` preserves insertion order — but saying *why* you chose the string ("it makes the ordering guarantee explicit rather than relying on the map\'s") shows you thought about it.',
          'Raising **Unicode** unprompted is the kind of caveat that distinguishes candidates. `for...of` iterates code points rather than UTF-16 units, so an emoji is handled correctly where `text[i]` would split it — worth one sentence, not a digression.',
          'Note the closing line: naming **one thing you would do with more time** ends the answer well and shows you know the solution is not the final word.',
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Front-end specific questions',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        needsDom: true,
        html: '<div id="app"><ul id="list"><li data-id="1">One</li><li data-id="2">Two</li></ul><button id="add">Add</button></div>',
        caption: 'Event delegation — asked in almost every front-end interview.',
        code: [
          'const list = document.getElementById("list");',
          'const clicked = [];',
          '',
          '// ONE listener on the parent, using bubbling',
          'list.addEventListener("click", (event) => {',
          '  // closest handles clicks on nested elements inside the item',
          '  const item = event.target.closest("li");',
          '',
          '  // Guard: the click may be on the list itself, or outside any item',
          '  if (!item || !list.contains(item)) return;',
          '',
          '  clicked.push(item.dataset.id);',
          '});',
          '',
          'list.querySelector(\'[data-id="1"]\').click();',
          'list.querySelector(\'[data-id="2"]\').click();',
          '',
          '// The decisive advantage: elements added LATER need no new listener',
          'const fresh = document.createElement("li");',
          'fresh.dataset.id = "3";',
          'fresh.textContent = "Three";',
          'list.append(fresh);',
          '',
          'fresh.click();',
          '',
          'console.log("clicked  :", clicked);',
          'console.log("listeners:", 1, "for", list.children.length, "items");',
          '',
          '// A click on the container itself is correctly ignored',
          'list.click();',
          'console.log("unchanged:", clicked.length);',
        ].join('\n'),
        output: [
          'clicked  : ["1", "2", "3"]',
          'listeners: 1 for 3 items',
          'unchanged: 3',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'Answer the "why", not just the "how"',
        body: [
          '"Put the listener on the parent" is the mechanism. The **reasons** are what the question is for: one listener instead of many, and — decisively — it works for elements added **after** the listener was attached, which per-element listeners cannot.',
          'The `closest` call handles a click on something nested inside the item, and the `contains` guard stops a `closest` match from outside the list. Mentioning both shows you have written this for real rather than recited it.',
          'Expect the follow-up: "when would delegation not work?" — events that do not bubble (`focus`, `blur`, `load`), and cases where you need the listener on a specific element for `stopPropagation` reasons.',
        ],
      },
      {
        kind: SECTION.TABLE,
        headers: ['Question', 'The answer they want'],
        rows: [
          ['Debounce vs throttle', 'Debounce waits for silence (search-as-you-type); throttle limits rate during activity (scroll)'],
          ['`fetch` error handling', 'It resolves on 404 — check `response.ok`; only network failure rejects'],
          ['Loading and error states', 'idle / loading / success / error as explicit states, not two booleans'],
          ['`localStorage` for tokens', 'A trade-off: XSS theft versus CSRF — not a rule'],
          ['Preventing XSS', '`textContent` for text, allowlist URL schemes, sanitiser for real HTML'],
          ['Why the page froze', 'Long synchronous work on the one main thread — chunk it or use a Worker'],
        ],
      },
      {
        kind: SECTION.HEADING,
        text: 'Readiness checklist',
      },
      {
        kind: SECTION.CODE,
        language: 'javascript',
        runnable: true,
        caption: 'Score yourself honestly — each item is a question you can be asked verbatim.',
        code: [
          '"use strict";',
          '',
          'const checklist = [',
          '  ["Fundamentals", "Explain the difference between == and === with the coercion rule", "m03"],',
          '  ["Fundamentals", "Explain hoisting without saying code moves to the top", "m10"],',
          '  ["Functions", "Define a closure without saying only \'a function inside a function\'", "m32"],',
          '  ["Functions", "Explain the var-in-a-loop puzzle in terms of bindings", "m32"],',
          '  ["this", "Determine this from the call site, including arrows", "m29"],',
          '  ["Objects", "Distinguish a function .prototype from an object [[Prototype]]", "m30"],',
          '  ["Objects", "Explain what instanceof actually checks", "m30"],',
          '  ["Classes", "Explain class methods versus class fields", "m31"],',
          '  ["Async", "Predict promise versus timer ordering and say why", "m33"],',
          '  ["Async", "Explain why fetch does not reject on a 404", "m26"],',
          '  ["DOM", "Implement event delegation and say why it beats per-element listeners", "m19"],',
          '  ["Data", "Say when a Map beats an object, and why a Set will not dedupe objects", "m34"],',
          '  ["Algorithms", "Give the complexity of your own code and improve an O(n^2)", "m39"],',
          '  ["Testing", "Explain behaviour versus implementation testing", "m42"],',
          '  ["Performance", "Implement debounce and throttle and choose between them", "m43"],',
          '  ["Security", "Explain XSS prevention and why client validation is not security", "m44"],',
          '];',
          '',
          '// Mark each honestly: can you answer it out loud, right now, unprompted?',
          'const confident = new Set(["Fundamentals", "Functions"]);',
          '',
          'const byArea = new Map();',
          '',
          'for (const [area, question, module] of checklist) {',
          '  if (!byArea.has(area)) byArea.set(area, []);',
          '  byArea.get(area).push({ question, module, ready: confident.has(area) });',
          '}',
          '',
          'for (const [area, items] of byArea) {',
          '  const ready = items.filter((i) => i.ready).length;',
          '  const revise = items.filter((i) => !i.ready).map((i) => i.module);',
          '',
          '  console.log(`${area.padEnd(13)} ${ready}/${items.length}${revise.length ? ` — revise ${[...new Set(revise)].join(", ")}` : ""}`);',
          '}',
        ].join('\n'),
        output: [
          'Fundamentals  2/2',
          'Functions     2/2',
          'this          0/1 — revise m29',
          'Objects       0/2 — revise m30',
          'Classes       0/1 — revise m31',
          'Async         0/2 — revise m33, m26',
          'DOM           0/1 — revise m19',
          'Data          0/1 — revise m34',
          'Algorithms    0/1 — revise m39',
          'Testing       0/1 — revise m42',
          'Performance   0/1 — revise m43',
          'Security      0/1 — revise m44',
        ].join('\n'),
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.TIP,
        title: 'The test is "out loud, unprompted"',
        body: [
          'Recognising a correct answer in a list is far easier than producing one under pressure. Score each item by whether you could **say it aloud right now**, to a person, without notes — that is the standard the interview applies.',
          'Where you cannot, the module is named. Revising a specific lesson beats re-reading everything, and the checklist tells you which.',
          'A useful drill: pick three items at random, set a timer for two minutes each, and answer aloud. The gap between "I know this" and "I can say this" is usually larger than expected, and it closes quickly with practice.',
        ],
      },
      {
        kind: SECTION.CALLOUT,
        tone: CALLOUT_TONE.INFO,
        title: 'What this module is, and what comes next',
        body: [
          'This module teaches **how to prepare and reason** in a JavaScript interview: how to structure an answer, how to work a coding question visibly, and how to assess your own readiness.',
          'It is deliberately not a question bank. Volume practice belongs in the dedicated interview area, where a large set of questions can be worked through repeatedly — this module gives you the method to apply to them.',
          'The most valuable preparation is not more questions, though. It is **building something and being able to explain the decisions**: why you chose that data structure, what you would do differently, what broke and how you found it. Every module in this curriculum was written to make those answers available to you.',
        ],
      },
      {
        kind: SECTION.PREDICT,
        code: [
          '// An interviewer asks you to find duplicates in an array.',
          '// You immediately start typing a nested loop.',
          '',
          '// What have you missed?',
        ].join('\n'),
        options: [
          'Clarifying the requirements, working an example, stating edge cases and discussing the approach before coding',
          'Nothing — a nested loop is a valid solution',
          'Using a more modern syntax',
          'Adding comments',
        ],
        correct: 0,
        explanation:
          'The nested loop may well be correct, but typing first skips everything the round is assessing. You have not asked what "duplicates" means (every repeat, or each value that repeats?), what to return when there are none, or whether the input is sorted — each of which changes the answer. You have not worked an example aloud, named the edge cases, or said that the nested loop is O(n²) and a `Set` makes it O(n). An interviewer watching silent typing learns nothing about your reasoning, and cannot redirect you if the approach is wrong. **Thirty seconds of clarification and one sentence about complexity changes the assessment more than the code does.**',
      },
    ],
    exercises: [
      {
        id: 'ex-m46-03-a',
        title: 'Work the question properly',
        kind: EXERCISE_KIND.WRITE_FUNCTION,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['interview'],
        instructions:
          'Write `firstNonRepeating(text)` returning the first character appearing exactly once, or `null`. It must be O(n) — no nested scanning — and preserve the original order.',
        starterCode: [
          'function firstNonRepeating(text) {',
          '  // Count in one pass, then find the first with a count of 1.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'finds the first non-repeating', body: 'expect(firstNonRepeating("swiss")).toBe("w");' },
          { name: 'returns the first character when unique', body: 'expect(firstNonRepeating("abc")).toBe("a");' },
          { name: 'returns null when all repeat', body: 'expect(firstNonRepeating("aabb")).toBe(null);' },
          { name: 'handles an empty string', body: 'expect(firstNonRepeating("")).toBe(null);' },
          { name: 'handles a single character', body: 'expect(firstNonRepeating("a")).toBe("a");' },
          { name: 'is case-sensitive', body: 'expect(firstNonRepeating("aA")).toBe("a");' },
          { name: 'preserves order over frequency', body: 'expect(firstNonRepeating("aabbc")).toBe("c");' },
          { name: 'counts spaces as characters', body: 'expect(firstNonRepeating("aa b")).toBe(" ");', hidden: true },
        ],
        hints: [
          'A `Map` counts in one pass.',
          'Then iterate the **string** again, not the map, to preserve order.',
          'Return `null` if the second pass finds nothing.',
        ],
        solution: [
          'function firstNonRepeating(text) {',
          '  const counts = new Map();',
          '',
          '  for (const char of text) {',
          '    counts.set(char, (counts.get(char) ?? 0) + 1);',
          '  }',
          '',
          '  for (const char of text) {',
          '    if (counts.get(char) === 1) return char;',
          '  }',
          '',
          '  return null;',
          '}',
        ].join('\n'),
        solutionExplanation:
          'Two separate passes are what make this **O(n)** — the naive approach of scanning the whole string for each character is O(n²). Iterating the **string** in the second pass rather than the map makes the ordering guarantee explicit rather than relying on `Map` insertion order, which is the choice worth explaining aloud. The hidden test confirms nothing is filtered: a space is a character like any other, and a `trim` or truthiness check would have wrongly skipped it. `for...of` iterates **code points**, so an emoji is handled correctly where `text[i]` would split a surrogate pair.',
      },
      {
        id: 'ex-m46-03-b',
        title: 'Implement event delegation',
        kind: EXERCISE_KIND.DOM_TASK,
        difficulty: DIFFICULTY.HARD,
        xp: 35,
        topicIds: ['interview'],
        instructions:
          'Write `delegate(list, onSelect)` attaching **one** listener to `list` that calls `onSelect` with the `data-id` of the clicked `<li>` — including items added later. Clicks outside an item are ignored.',
        html: '<div id="app"><ul id="list"><li data-id="1"><span>One</span></li><li data-id="2">Two</li></ul></div>',
        starterCode: [
          'function delegate(list, onSelect) {',
          '  // One listener on the container; use bubbling.',
          '}',
        ].join('\n'),
        tests: [
          { name: 'reports a clicked item', body: 'const l = document.createElement("ul"); l.innerHTML = \'<li data-id="1">One</li>\'; const seen = []; delegate(l, (id) => seen.push(id)); l.querySelector("li").click(); expect(seen).toEqual(["1"]);' },
          { name: 'works for a nested element', body: 'const l = document.createElement("ul"); l.innerHTML = \'<li data-id="1"><span>One</span></li>\'; const seen = []; delegate(l, (id) => seen.push(id)); l.querySelector("span").click(); expect(seen).toEqual(["1"]);' },
          { name: 'works for items added later', body: 'const l = document.createElement("ul"); const seen = []; delegate(l, (id) => seen.push(id)); const li = document.createElement("li"); li.dataset.id = "9"; l.append(li); li.click(); expect(seen).toEqual(["9"]);' },
          { name: 'ignores a click on the container', body: 'const l = document.createElement("ul"); const seen = []; delegate(l, (id) => seen.push(id)); l.click(); expect(seen).toEqual([]);' },
          { name: 'reports each of several items', body: 'const l = document.createElement("ul"); l.innerHTML = \'<li data-id="1">a</li><li data-id="2">b</li>\'; const seen = []; delegate(l, (id) => seen.push(id)); l.querySelectorAll("li").forEach((li) => li.click()); expect(seen).toEqual(["1", "2"]);' },
          { name: 'attaches only one listener', body: 'const l = document.createElement("ul"); l.innerHTML = \'<li data-id="1">a</li>\'; let calls = 0; delegate(l, () => { calls += 1; }); l.querySelector("li").click(); expect(calls).toBe(1);' },
          { name: 'ignores an li outside the list', body: 'const l = document.createElement("ul"); const seen = []; delegate(l, (id) => seen.push(id)); const outside = document.createElement("li"); outside.dataset.id = "x"; expect(seen).toEqual([]);', hidden: true },
        ],
        hints: [
          '`list.addEventListener("click", handler)` — once.',
          '`event.target.closest("li")` finds the item from any descendant.',
          'Guard with `list.contains(item)` before using it.',
        ],
        solution: [
          'function delegate(list, onSelect) {',
          '  list.addEventListener("click", (event) => {',
          '    const item = event.target.closest("li");',
          '',
          '    if (!item || !list.contains(item)) return;',
          '',
          '    onSelect(item.dataset.id);',
          '  });',
          '}',
        ].join('\n'),
        solutionExplanation:
          'One listener on the container catches clicks from every item by **bubbling**, which is why the third test passes — an item added after the listener was attached needs no new registration, and that is delegation\'s decisive advantage over per-element listeners. `closest` walks up from whatever was actually clicked, so a click on a nested `<span>` still resolves to its `<li>` (second test). The `!item` guard ignores clicks on the container itself, and `list.contains` ensures a matched item genuinely belongs to this list rather than being elsewhere in the document.',
      },
      {
        id: 'ex-m46-03-c',
        title: 'What is missing before coding?',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['interview'],
        instructions:
          'You are asked to "merge two sorted arrays". What should you establish before writing any code?',
        options: [
          'Nothing — the problem is clear',
          'Whether duplicates are kept, what happens with empty inputs, whether to mutate the inputs, and the expected complexity',
          'Which framework to use',
          'How to name the variables',
        ],
        correct: 1,
        hints: [
          'Which unstated assumptions would change the implementation?',
        ],
        solution: 'Whether duplicates are kept, what happens with empty inputs, whether to mutate the inputs, and the expected complexity',
        solutionExplanation:
          'Each of those genuinely changes the code. Deduplicating requires an extra check; mutating an input is a different function signature; and "merge" has an O(n + m) two-pointer solution that a candidate who reaches for `[...a, ...b].sort()` — O(n log n), discarding the sortedness you were given — misses entirely. Asking takes twenty seconds and demonstrates exactly the habit the round is assessing. Note the empty-input question is not pedantry: it is the case most naive implementations get wrong.',
      },
      {
        id: 'ex-m46-03-d',
        title: 'Assess a readiness answer',
        kind: EXERCISE_KIND.CONCEPTUAL,
        difficulty: DIFFICULTY.MEDIUM,
        xp: 25,
        topicIds: ['interview'],
        instructions:
          'How should you judge whether you are ready for a given interview topic?',
        options: [
          'You recognise the correct answer when you see it',
          'You can say a correct answer out loud, unprompted, without notes',
          'You have read the relevant documentation',
          'You have used it in a project once',
        ],
        correct: 1,
        hints: [
          'What does the interview actually require you to do?',
        ],
        solution: 'You can say a correct answer out loud, unprompted, without notes',
        solutionExplanation:
          'The interview requires **production** under time pressure, not recognition — and the gap between "I know this" and "I can say this" is consistently larger than people expect. Recognising a correct answer in a list is far easier and gives a false reading. Reading documentation and shipping a feature both build genuine understanding, but neither confirms you can articulate it on demand. The drill that closes the gap: pick a topic, set a two-minute timer, and answer aloud to a person or a recording.',
      },
    ],
    quiz: {
      id: 'qz-m46-03',
      questions: [
        {
          id: 'q-m46-03-1',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['interview'],
          prompt: 'What is the most common failure in a coding round?',
          options: [
            'Writing slow code',
            'Working in silence, so the interviewer cannot assess the reasoning or redirect you',
            'Using the wrong language feature',
            'Finishing too quickly',
          ],
          correct: 1,
          optionExplanations: [
            'Complexity can be discussed and improved.',
            'Correct — they are assessing how you think.',
            'Rarely decisive.',
            'Not a problem.',
          ],
          explanation:
            'Correct code produced in silence gives an interviewer nothing to evaluate, and prevents them nudging you away from a dead end.',
        },
        {
          id: 'q-m46-03-2',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['interview'],
          prompt: 'What is the decisive advantage of event delegation?',
          options: [
            'It is faster to type',
            'It handles elements added after the listener was attached, which per-element listeners cannot',
            'It avoids bubbling',
            'It works without JavaScript',
          ],
          correct: 1,
          optionExplanations: [
            'Brevity is minor.',
            'Correct — plus one listener instead of many.',
            'It depends on bubbling.',
            'It is JavaScript.',
          ],
          explanation:
            'One listener covers current and future items. Expect the follow-up about events that do not bubble, such as `focus` and `blur`.',
        },
        {
          id: 'q-m46-03-3',
          kind: QUIZ_KIND.TRUE_FALSE,
          topicIds: ['interview'],
          prompt: 'You should start coding as soon as you understand the problem.',
          options: ['True', 'False'],
          correct: 1,
          optionExplanations: [
            'Unstated assumptions change the implementation.',
            'Correct — clarify, work an example, state the approach first.',
          ],
          explanation:
            'Clarifying edge cases and stating the approach with its complexity takes under a minute and changes the assessment more than the code does.',
        },
        {
          id: 'q-m46-03-4',
          kind: QUIZ_KIND.SINGLE,
          topicIds: ['interview'],
          prompt: 'What is the best preparation beyond practising questions?',
          options: [
            'Memorising more answers',
            'Building something and being able to explain the decisions you made',
            'Reading the specification end to end',
            'Learning another framework',
          ],
          correct: 1,
          optionExplanations: [
            'Memorised answers fail the follow-up.',
            'Correct — real decisions are the strongest evidence.',
            'Useful for reference, not for interviews.',
            'Breadth without depth.',
          ],
          explanation:
            'Why you chose a data structure, what broke and how you found it, what you would change — these answers cannot be memorised and are exactly what distinguishes candidates.',
        },
      ],
    },
    summary:
      'In a **coding round**, silence is the most common failure — interviewers assess **how you think**, and quiet typing gives them nothing to evaluate and no chance to redirect you. Work visibly: **clarify** (types, empty input, duplicates, what to return when there is no answer), **work an example aloud**, **state edge cases**, **describe the approach and its complexity** before typing, **say the brute force then improve it**, code while narrating, **trace your own solution** against the edge cases, and close with the complexity plus one thing you would change with more time. Details that read as senior are cheap: explaining *why* you iterate the string rather than the map, or raising Unicode in one sentence. For **front-end questions**, answer the **why** rather than the mechanism — event delegation is not "put the listener on the parent" but "one listener, and it covers elements added **later**", with `closest` handling nested targets and a `contains` guard, and the expected follow-up about events that do not bubble. Judge **readiness** by whether you can say an answer **out loud, unprompted, without notes** — recognition is far easier than production and gives a false reading. Finally, this module teaches **method rather than volume**: the strongest preparation is building something and being able to explain the decisions, which is what no memorised answer survives a follow-up without.',
    keyTakeaways: [
      'Narrate throughout — silent correct code is assessed as nothing',
      'Clarify, example, edge cases and approach before typing',
      'State the brute force, then improve it, and give the complexity',
      'Delegation wins because it covers elements added later',
      'Readiness means saying it aloud unprompted, not recognising it',
      'Explaining real decisions beats memorising answers',
    ],
    relatedLessons: ['l-m46-02', 'l-m46-01'],
    interviewConnections: [
      'Walk me through how you would approach this problem.',
      'Implement event delegation for a dynamic list.',
      'What is the time and space complexity of your solution?',
      'What would you do differently with more time?',
    ],
  },
];
